### ISSUE TITLE
Pattern:  Content block - segmented design provided by Web Simplification

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1007]
### Notes
 - Lila is the web simplification designer.  This issue is to track the transition of the design work to the DDS engineering team members.  

#### Additional Information
 - [Designs]()
 - [Design specs]()
 - Designs are scheduled to be available on Jan 17.  The review meetings with DDS should be scheduled early the following week.

#### Acceptance Criteria
 - [ ] Specs received from Web Simplification and reviewed with DDS engineering 
 - [ ] Meetings conducted to review the designs

**Comment by RobertaJHahn** [comment]
Meetings with Web Simplification team members scheduled Jan 20 & 21.

**Comment by ljcarot** [comment]
@wonilsuhibm @RobertaJHahn can we rename this pattern to match AirTable naming convention? https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T/recXuOtibCzY9c8Oe?blocks=hide

**Comment by wonilsuhibm** [comment]
@ljcarot Absolutely.

@jeffchew I think we should do it in a coordinated fashion, with the Drupal team involved too — what do you think? And do you want to do it one by one or wait until other names are all finalized?

**Comment by RobertaJHahn** [comment]
@wonilsuhibm @ljcarot I agree with you Wonil.  I will have to keep track of the progress all the Github changes.  I was also thinking that I should begin with the pattern names that have been finalized.

**Comment by RobertaJHahn** [comment]
Meeting was conducted on Jan 20.  [Link to the Box note](https://ibm.ent.box.com/notes/443167473382) with the meeting notes and recording.
