### ISSUE TITLE
Make masthead links, Profile icon optional

### ISSUE THREAD

**Issue by sanjitbauli** [carbon-design-system/ibm-dotcom-library#101]
In URX we don't need any menu on the header, also the profile icon is not required, In Northstar header, there was an option masthead:'popup' this feature will help us to match the same behavior.

Make the masthead configurable,  hide links, profile bypassing props to the component.

A duplicate of this issue has been created in the Digital Design board.  [Make the masthead configurable, hide links, profile bypassing props to the component](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1772)

**Comment by ljcarot** [comment]
@jeffchew I believe we made masthead configurable.  Can you confirm?

**Comment by sanjitbauli** [comment]
I don't see any option. Maybe i am missing the trick. FYI, i am using own css to hide the menu and profile section at this moment.

**Comment by ljcarot** [comment]
It will be coming out in next release.  That's why you don't see it yet.
