### ISSUE TITLE
Expressive theme – Multi select

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1010]
### Default

<img width="325" alt="Screen Shot 2020-01-13 at 11 37 36 AM" src="https://user-images.githubusercontent.com/45692622/72274503-54431500-35fa-11ea-9dad-758d36657b5d.png">

- [ ] checkbox is not vertically centered with the text. The checkboxes are actually looking too big, let's discuss before you make updates.

- [ ] I can't seem to open the options menu with keyboard commands, can you please try? This might be an issue to submit to Carbon

 
### Inline

<img width="361" alt="Screen Shot 2020-01-13 at 11 48 25 AM" src="https://user-images.githubusercontent.com/45692622/72274742-b8fe6f80-35fa-11ea-95ca-b6eb999c1a34.png">

- [ ] update height to 40px tall.

<img width="334" alt="Screen Shot 2020-01-13 at 11 48 12 AM" src="https://user-images.githubusercontent.com/45692622/72274701-a4ba7280-35fa-11ea-8b03-77587998653a.png">

- [ ] error state icon is not vertically centered with text / chevron icon

## with Initial selected items
 *I'm not sure if this is a separate component, or if it will inherit the updates from the default, but same comments as the default options*

### Default
- [ ] checkbox is not vertically centered with the text. The checkboxes are actually looking too big, let's discuss before you make updates.

### Inline
- [ ] update height to 40px tall.
- [ ] error state icon is not vertically centered with text / chevron icon

**Comment by annawen1** [comment]
For *Inline* the alignment of the error state icon seems to be correct now with the latest updates.

**Comment by oliviaflory** [comment]
Could we look at the *inline* error state together, I'm still seeing the misalignment of the error state icon, but maybe I am looking at an outdated version?

**Comment by annawen1** [comment]
> Could we look at the _inline_ error state together, I'm still seeing the misalignment of the error state icon, but maybe I am looking at an outdated version?

I think this is probably a bug that we should create a ticket to Carbon for since I'm seeing the same problem on the react carbon storybook: http://react.carbondesignsystem.com/?path=/story/multiselect--default

**Comment by andysherman2121** [comment]
Waiting for Carbon team to fix icon bug

**Comment by RobertaJHahn** [comment]
@andysherman2121 Moving this issue out to Spr 20-05 since you are waiting for Carbon.

**Comment by annawen1** [comment]
This has been resolved with the chore(dependency): update carbon-components dependency #1204 PR
