### ISSUE TITLE
Expressive theme – loading

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1013]
### Default
:star: looks good! no changes

### Small

This might be a tricky one.. any chance we can find out how big the **small loading** is? In the design kit it's 16x16 (left), and we'd ideally like to bump it up to 20x20px (right).

I am assuming that the **small** is used *within* the inline loading component.

![Screen Shot 2020-01-13 at 4.42.51 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/4864d769-9fe7-452e-bc49-1404f3b8735f)

**Comment by annawen1** [comment]
Hey @joshblack, I'm noticing that the the radius of the loading circle is determined in the code
```
const spinnerRadius = small ? '26.8125' : '37.5';
```

If we wanted to bump it up for expressive, would we need to submit this as a request? Also do you know how the radius sizes were determined? Says `26.8125` but when I inspect the circle size in the console it's smaller than that. 

Thanks!
