### ISSUE TITLE
Pattern: Content block - segmented Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1024]
#### Additional Information
 - alpha Dev Issue link (#1020)
 - Design specs [sketch]( ) 
- Functional specs Issue link (#1028)
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Content block - segmented` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Design review performed and Github issues created for all defects found
- [ ] Defects are created and reviewed after fixes are made
- [ ] Approval that the code delivered works as designed

**Comment by kennylam** [comment]
@wonilsuhibm @RobertaJHahn this is ready to be reviewed
https://github.com/carbon-design-system/ibm-dotcom-library/pull/1437

**Comment by larahanlon2** [comment]
All design defects for this round have been opened. Closing this issue.
