### ISSUE TITLE
Pattern: Create the Content block - simple v2 functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1029]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the Content block - simple functional specs 

> so that I can:
so that I can properly code the Content block - simple v2 pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Pattern-roadmap) - _This URL may change as this linked wiki page may move to the public github_
 - Web Simplification designs (#1006)

#### Acceptance criteria
 - [ ] Documented Featured Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
 - [ ] Pattern roadmap wiki page is updated

**Comment by jeffchew** [comment]
This appears to be a dupe of https://github.com/carbon-design-system/ibm-dotcom-library/issues/1127? @photodow @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Duplicate of Issue (#1127)  Closing.
