### ISSUE TITLE
Pattern: Content block - simple v2 Functional QA testing - alpha version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1032]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library Content block - simple pattern

> I need to:
have a version of the pattern or component that has been tested on the latest Chrome browser and on the IOS and Android operating systems

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browserstack](https://ibm.ent.box.com/notes/578734426612)
 - Designs (#1006)
- alpha dev story (#1030)
 - Functional specs (#1029)

#### Acceptance criteria
- [ ] The pattern has been tested on the latest Chrome browser and on the IOS and Android operating systems
- [ ] Defects are recorded and retested when fixed

**Comment by jeffchew** [comment]
@RobertaJHahn came across this, I think we can close this right?

**Comment by RobertaJHahn** [comment]
This issue was created as part of the alpha QA process.  It is obsolete.  Closing.
