### ISSUE TITLE
Pattern: Content block - simple v2 Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1036]
#### Additional Information
 - alpha Dev link (# )
 - Design specs 
**Abstract:** https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca
**Box:** https://ibm.ent.box.com/file/600995262427

- Functional specs (#1029)

 #### Tasks
Ensure the `Content block - simple v2` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Design review performed and Github issues created for all defects found
- [ ] Defects are created and reviewed after fixes are made
- [ ] Approval that the code delivered works as designed

**Comment by larahanlon2** [comment]
FYI `Content block – simple` design specs are now updated and available on Abstract: https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca?

**Comment by kennylam** [comment]
@larahanlon2 @wonilsuhibm @RobertaJHahn this issue is ready for testing/review
https://github.com/carbon-design-system/ibm-dotcom-library/pull/1429

**Comment by kennylam** [comment]
@wonilsuhibm @larahanlon2 this is ready for review
https://github.com/carbon-design-system/ibm-dotcom-library/pull/1429

**Comment by larahanlon2** [comment]
All design defects for this round have been opened. Closing this issue.
