### ISSUE TITLE
Expressive theme – Progress indicator

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1039]
Update for default, interactive and vertical variations: 

<img width="663" alt="Screen Shot 2020-01-14 at 4 32 30 PM" src="https://user-images.githubusercontent.com/45692622/72385053-aebc9e00-36ec-11ea-9060-cf1707514c93.png">

- [ ] update status icons to 20x20 px

**Comment by annawen1** [comment]
Looks like `bx--progress-step--current` and `bx--progress-step--incomplete` svg icons don't scale accordingly when I bump up the width and height to 20px

<img width="1094" alt="Screen Shot 2020-01-16 at 10 47 26 AM" src="https://user-images.githubusercontent.com/54281166/72539934-19d1b600-384e-11ea-9857-396d26dbd2fe.png">

Looking at the carbon code
```
if (current) {
      return (
        <svg>
          <path d="M 7, 7 m -7, 0 a 7,7 0 1,0 14,0 a 7,7 0 1,0 -14,0" />
          <title>{description}</title>
        </svg>
      );
    }
    
     ....

    return (
      <svg>
        <title>{description}</title>
        <path d="M8 1C4.1 1 1 4.1 1 8s3.1 7 7 7 7-3.1 7-7-3.1-7-7-7zm0 13c-3.3 0-6-2.7-6-6s2.7-6 6-6 6 2.7 6 6-2.7 6-6 6z" />
      </svg>
```

There are no attributes for the those svg elements - I think we need the `viewBox` attribute in order for the `current` and `incomplete` to scale. Will submit a ticket to carbon to see if we can get that in

CC @oliviaflory @joshblack

**Comment by annawen1** [comment]
ticket opened: https://github.com/carbon-design-system/carbon/issues/5086

**Comment by annawen1** [comment]
PR has been submitted to Carbon: https://github.com/carbon-design-system/carbon/pull/5122
