### ISSUE TITLE
Pattern: Content group - simple v2 Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1044]
#### Additional Information
 - alpha Dev link (#1041)
 - Design specs [sketch]( ) 
- Functional specs (#1040)
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Simple Array v2` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [x] Design review performed and Github issues created for all defects found
- [x] Defects are created and reviewed after fixes are made
- [x] Approval that the code delivered works as designed

**Comment by larahanlon2** [comment]
FYI the design specs are now available on Abstract: https://share.goabstract.com/cc5cd1b3-a485-41af-ad83-1a44be57c5f6?

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm , @RobertaJHahn 
This was finally merged in and it's ready for QA,
Thank you!

**Comment by RobertaJHahn** [comment]
@wonilsuhibm I have assigned this issue to sprint 20-04.  If you could assign a designer to test, that would be great.
