### ISSUE TITLE
Finalize the ontology and pattern names

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1062]
#### User Story

> As a `[user role below]`:
As a DDS squad BA and leader

> I need to:
define and document the ontology list and pattern names

> so that I can:
provide this information to the designers and developers as well as external squads to ensure consistent management and ease of maintenance

#### Additional information

 - [Layout pattern airtable](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide)
 - [Layout Pattern Ontology Mural Board](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
 - The work must be done by the Friday, Jan 24.

#### Acceptance criteria
 - [x] Final ontology and pattern names are defined

**Comment by photodow** [comment]
Here is the airtable with the finalized list of pattern names and ontology: https://airtable.com/shrzdSpxwUIN3UTBe/tblsnDDtb57UVxHpH?blocks=hide

Here is the mural board which helps visualize the ontology:
https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7
