### ISSUE TITLE
Pattern: Develop Table of Contents pattern - Updates from W/S - Sprint 20-02

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1064]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
work closely with the Business Analyst and designer to begin developing the (pattern name) pattern

> so that I can:
become involved earlier in the design process and functional documentation to compress the schedule and develop a higher quality pattern

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Functional specs issue (#1063  )
 - [Functional Specs](https://ibm.ent.box.com/file/599375190897)
 - Design QA issue (#1203)
 - Prod QA issues (#1142)

#### Acceptance criteria
 - [x] Update the TOC with the option to dynamically generate the links based on the page content
 - [x] Remove the feature flag for this component
 - [x] Additional knobs or story necessary in Storybook to switch between dynamic and manual generation of the links
 - [x] Update the README for the react pattern and corresponding styles
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by larahanlon2** [comment]
FYI Table of Contents design specs are now available on Abstract: https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34?
