### ISSUE TITLE
Feature card: Card Needs to Hang

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1067]
## Detailed description

If you look at the as-is below you'll see that the text aligns flush with the edge of the card. What needs to happen is the card needs to hang into the gutters, so that the text inside the card lines up with the text above (assuming there were text in the left hand side, look at example instead).

##### As-is
![image](https://user-images.githubusercontent.com/3793636/72572268-a0ef5000-3887-11ea-9a1f-0744e64ab831.png)

##### To-be
![image](https://user-images.githubusercontent.com/3793636/72572453-2f63d180-3888-11ea-95d0-e5218268bfb4.png)

#### Additional information
- [FeaturedLink Functional Specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2)

#### Acceptance Criteria
- [ ] Card lines hangs into gutter
- [ ] text remains in column
- [ ] text aligns with content above

**Comment by RobertaJHahn** [comment]
@jeffchew @photodow @larahanlon2 @wonilsuhibm @oliviaflory Could you decide off-line how this treatment will be handled and document the decision in this issue?  Thanks
