### ISSUE TITLE
Feature card: Theming

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1069]
## Detailed description

This component right now isn't 100% themable. We need to make sure we add the right dependencies and such and make sure we're using the proper tokens so it can be themed properly.

#### Example in UseCase pattern
![image](https://user-images.githubusercontent.com/3793636/72571863-66d17e80-3886-11ea-9189-a9256a52a277.png)

#### Additional information

- [FeaturedLink Functional Specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2)
- [Carbon color tokens](https://www.carbondesignsystem.com/guidelines/color/usage)

#### Additional information

- [ ] Correct theme in UseCase pattern
- [ ] theme mixin like other patterns
- [ ] uses correct color tokens
- [ ] Knobs to change theming of

**Comment by RobertaJHahn** [comment]
The feature card should not include theming options at this time.  We will be creating a separate issue to fix the feature card for high contrast.  Closing.
