### ISSUE TITLE
Pattern:  Card High Contrast Modifier

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1070]
## Detailed description

The current alpha work has it themed using the basic colors. We need a high contrast version that we can use in scenarios like this, and the CardSection where the background color is dark on a light theme, or light on a dark theme. It leverages different color tokens.

##### As-is
![image](https://user-images.githubusercontent.com/3793636/72571471-4c4ad580-3885-11ea-90d2-b3f44163b864.png)

##### To-be
![image](https://user-images.githubusercontent.com/3793636/72571495-5ec50f00-3885-11ea-827d-97fc51bf74da.png)

Notice how the background is dark, and the text is light. This can be achieved through inverse colors. Check out the card functional specs and design specs for more information.

> Created a story to align icon, and style "button"

#### Additional information

- [FeaturedLink Functional Specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2)
- [Card Functional Specs](https://ibm.box.com/s/y1h8lgvn8zjdzr9r0owi7gvy5mjz7lcd)
- [Carbon Colors](https://www.carbondesignsystem.com/guidelines/color/overview)
- [CardSection Functional Specs](https://ibm.box.com/s/6lxup3zn1mbjgas1fv8ky19ntg7unpyv)

#### Acceptance Criteria

- [ ] Card has a inverse option for all themes, true or false
- [ ] Card follows functional specs data model, props, and naming

**Comment by ljcarot** [comment]
FYI @chetankan
