### ISSUE TITLE
Feature Card: Icon Position

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1071]
## Detailed description

The Icon Button on the featured link needs to be updated.

#### As-is

![image](https://user-images.githubusercontent.com/3793636/72571028-1822e500-3884-11ea-993d-3dec094257cb.png)

#### Expected
> 👀 see updated comments below from @larahanlon2 

Notice how the "button" needs to align right. ~Keep in mind this looks like a button, but does not function like a button because the whole thing is a clickable card link.~

#### Additional information

- [FeaturedLink Functional Specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2)
- [Card Functional Specs](https://ibm.box.com/s/y1h8lgvn8zjdzr9r0owi7gvy5mjz7lcd)
- [Carbon Button Mixins](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/button/_mixins.scss)
- [Carbon Colors](https://www.carbondesignsystem.com/guidelines/color/overview)

#### Acceptance criteria

- [ ] Align icon right
- [ ] Add "button" visuals and states

**Comment by larahanlon2** [comment]
After speaking with Wonil, Olivia and Lila, it's agreed that the blue button background should be **removed**. The icon will stay in the same position: bottom right of card.

**Design update. To be:**
<img width="970" alt="Screen Shot 2020-01-17 at 1 14 46 PM" src="https://user-images.githubusercontent.com/53093550/72635711-722ab580-392b-11ea-9909-c501f98f8294.png">

**Comment by larahanlon2** [comment]
In the current Storybook version, the icon is in the wrong place.

**Current:**
<img width="817" alt="Screen Shot 2020-01-17 at 10 57 43 AM" src="https://user-images.githubusercontent.com/53093550/72635915-ee24fd80-392b-11ea-9e8b-8f4206a7549a.png">

It should be placed to the bottom right. See above.

**Comment by photodow** [comment]
Thanks @larahanlon2 !

**Comment by photodow** [comment]
@RobertaJHahn Moving this under the feature card epic
