### ISSUE TITLE
FeaturedLink: Update Documentation

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1072]
The documentation is out of date for the component and needs to be updated. Also, a couple of components were changed to handle the features required from the FeaturedLink, and thus their documentation need to be updated to reflect the new changes.

#### Acceptance Criteria

- [ ] Image Component Docs Updated
- [ ] CardSection Pattern Docs Updated
- [ ] FeaturedLink Pattern Docs Updated

**Comment by RobertaJHahn** [comment]
Closing this issue as this work will be included as an AC when the pattern ontology documentation updates are done.
