### ISSUE TITLE
Abstract migration: Content block - simple (Simple long-form)

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1078]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conduct QA tests.

### Additional Information
- Prod QA Issue (#1293)

### Acceptance criteria
- [x] Change all instance of the name `Simple long-form` to `Content block — simple`
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file
 - [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by larahanlon2** [comment]
`Content block – simple` is now updated and available on Abstract: https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca?
