### ISSUE TITLE
Abstract migration: Content group — simple (Simple content array)

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1079]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conduct QA tests.

### Additional Information
- Prod QA issue (#1294)

### Acceptance criteria
- [x] Change all instance of the name `Content group — simple` to `Simple content array`
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by larahanlon2** [comment]
- [ ] Created a new Sketch file with `content group – simple` specs and removed old names
- [ ] Added Sketch file to [Box](https://ibm.box.com/s/rkkj4n9tmpiq3np9ng41dszf2y3cr4du) and [Abstract](https://share.goabstract.com/cc5cd1b3-a485-41af-ad83-1a44be57c5f6?)
- [ ] Added [README](https://ibm.ent.box.com/notes/611867483190) to Box with associated links
