### ISSUE TITLE
Abstract migration: Content block — with media (Use cases)

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1080]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Acceptance criteria
- [x] Change all instance of the name `Use cases` to `Content block — with media`
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file

**Comment by larahanlon2** [comment]
- [x] Sketch file updated and renamed to `content block – with media`
- [x] Sketch file `use cases` moved to archive folder in Box
- [x] [Abstract](https://share.goabstract.com/b477f6a2-6229-49d9-b83d-c5e25e6da171?) collection has been created
