### ISSUE TITLE
Abstract migration: Lead space — centered

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1082]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

#### Additional Information
 - Lead Space - centered QA Issue (#1097)

### Acceptance criteria
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Update functional specs to point to the new Abstract hosted file
- [x] Add or update README Box note with a link pointing to the hosted file

**Comment by RobertaJHahn** [comment]
@larahanlon2 We are boarding the QA testers this week.  Could you have this work finished by the end of the day today, Jan 20?

**Comment by larahanlon2** [comment]
`Lead space – centered` design specs have been updated and uploaded to Abstract. View collection [here](https://share.goabstract.com/3dc277d5-0f03-4ace-8c04-eb33d35085fb?).

**Comment by RobertaJHahn** [comment]
@jeffchew There is an AC to update the URL to point to the functional specs to the new Abstract location.  Could you do that update?

**Comment by jeffchew** [comment]
> @jeffchew There is an AC to update the URL to point to the functional specs to the new Abstract location. Could you do that update?

Done!

**Comment by larahanlon2** [comment]
[README](https://ibm.ent.box.com/notes/603977985183) has been added.

**Comment by RobertaJHahn** [comment]
@larahanlon2 Do we have to reopen this issue as the name has changed from Lead Space - Centered to Lead Space?
