### ISSUE TITLE
Abstract migration: Content block

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1083]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Notes
It's not clear if there is a design spec or func spec for this pattern exists.

### Acceptance criteria
- [ ] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [ ] A collection in Abstract is created and the link to it is available
- [ ] Associated Git stories have been updated with the new name and link
- [ ] Update functional specs to point to the new Abstract hosted file
- [ ] Add or update README Box note with a link pointing to the hosted file

**Comment by RobertaJHahn** [comment]
created in error.  Closing.
