### ISSUE TITLE
Expressive theme – time picker

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1085]
### Default
![Screen Shot 2020-01-17 at 9.38.58 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/50a1944c-ac8a-4478-a5ff-7e60fe7504e2)

- [ ] update chevron icon to match the size we used in [dropdown](https://carbon-expressive.mybluemix.net/?path=/story/dropdown--default)

**Comment by annawen1** [comment]
Looking at the codebase, `<TimePicker />` uses a different icon compared to `<DropDown />` component. It uses `<ChevronDownGlyph />` which sets the svg at width=10 and height=6. This makes bumping up the icon to 20x20 look weird.

We are thinking of opening a ticket with Carbon or contributing back changes to update the icon to `<ChevronDown16 />`

**Comment by annawen1** [comment]
PR to change icon submitted to Carbon: https://github.com/carbon-design-system/carbon/pull/5115
