### ISSUE TITLE
Expressive theme – File uploader

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1086]
### File Uploader Button
![Screen Shot 2020-01-17 at 10.05.02 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/76d81dfe-a1c6-4efb-bb67-a65ffa4da466)
![Screen Shot 2020-01-17 at 10.05.19 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/3db7805c-be81-46f6-bf06-6e5aa17c1898)

- [x] the tertiary button is smaller than the other styles, I'm not sure why this is happening because I don't see the same issue on the Carbon storybook. 

### File uploader item
![Screen Shot 2020-01-17 at 10.12.15 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/bb347b80-5e9b-4409-8a25-5c0b863ccdc0)

- [x] update container side to 40px tall
- [x] update close icon to 20x20px

![Screen Shot 2020-01-17 at 10.14.24 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/7e60bf82-db72-46ed-abd9-b4b56cec87f4)
- [x] update complete icon to 20x20px, reference size of [notification](https://carbon-expressive.mybluemix.net/?path=/story/notifications--inline) success icon

![Screen Shot 2020-01-17 at 10.16.24 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/01d796ed-244f-4371-95fa-943f0da79a4d)
- [x] check if loading icon is using the [small loading]() from the inline loading. Hopefully once we hear back from Josh it will be able to be 20x20px

**Comment by RobertaJHahn** [comment]
@andysherman2121 Moving this issue out to sprint 20-05, after the Learn Page release.  We would like all of your available time spent on the Learn page patterns scheduled in sprint 20-03.
