### ISSUE TITLE
ExpressiveModal: correct close button position

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1090]
## Detailed description
The close button doesn't match the specs exactly. Right now it's flushed top right at all times, and need to be adjusted. Notice how in the specs it's flushed `top: 0; right: 0;` on the `sm` breakpoint, but anything larger then that it goes to `top: 16px; right: 16px;`. To set the correct value we might need to use the grid gutter token.

##### As-is
`sm`, `md`, `lg`, `xlg`, `max`
![image](https://user-images.githubusercontent.com/3793636/72633117-63d59d00-391d-11ea-9f31-fcbb3165a845.png)

##### To-be

`sm`
![image](https://user-images.githubusercontent.com/3793636/72633331-d8a8d700-391d-11ea-8c99-eee14eb657cb.png)

`md`, `lg`, `xlg`, `max`
![image](https://user-images.githubusercontent.com/3793636/72633434-1148b080-391e-11ea-8213-3e121988cf81.png)

The other thing we should do is clear the close button on `sm`, and `md` by adding an additional `48px` to the top of the content container area.

![image](https://user-images.githubusercontent.com/3793636/72634594-77cece00-3920-11ea-953a-ac1accc3eb9c.png)

#### Additional information

- [LightboxMediaViewer Functional Specs](https://ibm.box.com/s/hq4eq9fdgb279o40h5ur5eonpo58359e)
- [ExpressiveModal Functional Specs](https://ibm.box.com/s/tcnaqe2k9c2kwue7t69nd2exhlws3ab8)

#### Acceptance criteria

- [ ] `sm` breakpoint `top: 0; right: 0;` 
- [ ] `md`, `lg`, `xlg`, `max` breakpoint `top: 16px; right: 16px;` 
- [ ] Leverage correct spacing tokens.
- [ ] `sm`, `md` Clear close button with additional `48px`

**Comment by wonilsuhibm** [comment]
That's how we spec'ed everything originally. But based on [this study](#1091 ) we should start changing it to flushed to corner.

@larahanlon2 @oliviaflory @JennySanchez @jacobottesen-dgc @sethibm any thoughts?
