### ISSUE TITLE
LightboxMediaViewer: fix image and content alignment issues

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1092]
## Detailed description

Right now the alignment of the image and content is a little all over the place. We need to align it back up to the specs. Feel free to reach out if you have any questions.

I love these visualizations @wonilsuhibm created.

`sm`, `md`
![image](https://user-images.githubusercontent.com/3793636/72634985-633f0580-3921-11ea-82d2-1f7b137201b2.png)

`lg`, `xlg`, `max`
![image](https://user-images.githubusercontent.com/3793636/72634953-4f939f00-3921-11ea-801a-d68420ad4560.png)

## Additional information

- [LightboxMediaViewer Functional Specs](https://ibm.box.com/s/hq4eq9fdgb279o40h5ur5eonpo58359e)
- [ExpressiveModal Functional Specs](https://ibm.box.com/s/tcnaqe2k9c2kwue7t69nd2exhlws3ab8)
- [@carbon/grid](https://www.npmjs.com/package/@carbon/grid)
- [Prototype](https://codepen.io/photodow/pen/abbQqpz)

## Acceptance criteria

- [ ] Image left aligned to modal, bottom aligned to content
- [ ] Image max-height: 100% (it shouldn't overflow)
- [ ] `sm` Image takes up rest of space that content doesn't fill, and as content is removed image area gets bigger
- [ ] `sm` Image  left-aligned, and vertical center if less than 100%
- [ ]  image and content container needs to vertical center

**Comment by Praveen-sr** [comment]
@RobertaJHahn @jeffchew 
On Windows and Mac book Air devices, the content is displayed after the image.
As per design, the content must be right aligned.

On Actual device:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/34e188ea-3e29-4c42-9040-9d433baaa426)

As per design:-
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/26ac55f4-9c5f-4740-adf5-02158a5bb22c)
