### ISSUE TITLE
Card: Text and icon should not change to blue

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1093]
## Detailed description

The text and should remain **white** on default and on hover/focus (or any interactive state). 
Please note that if this card becomes available in other themes, eg. light, the text and icon color will need to change from white to gray-100.

#### As-is

Currently, both the text and icon change to `blue` on hover:
![Screen Shot 2020-01-17 at 10.57.38 AM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/fa95d912-b6d2-4e0f-a63d-070d4256f3e0)

**Comment by photodow** [comment]
@RobertaJHahn this needs to be applied to the card work.
