### ISSUE TITLE
Feature card: Confirm that card title is H3

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1094]
## Detailed description

According to the original design specs, the card title should be `heading-02`. However, after speaking with Wonil it has been agreed that this title can increase to `expressing-heading-03`.

In the current [Storybook](https://ibmdotcom-patterns-react-experimental.mybluemix.net/?path=/story/featured-links--default) it looks like `expressing-heading-03` which is great if that is true. This issue is to confirm that it should not revert to previous specs. 

#### Original design spec

![Screen Shot 2020-01-17 at 1.29.09 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/9b065a6c-628b-4af6-8a1c-e786471d17ef)

#### Updated design
![Screen Shot 2020-01-17 at 1.14.08 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/d4dcd05c-ce19-419f-b599-a1a517beadf7)

**Comment by photodow** [comment]
@larahanlon2 let me know if you see something else, but it looks like this is using `expressive-heading-03`.

**Comment by larahanlon2** [comment]
@photodow yep, that's it. This issue was simply to confirm that the Storybook version was correct and shouldn't change to meet the actual design specs (which was actually heading-02)! Thanks.
