### ISSUE TITLE
Pattern:  Lead Space (a.k.a Lead Space - Centered) - Production Level

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1096]
This pattern has been renamed to Lead Space as part of the pattern ontology renaming.  [Airtable link](https://airtable.com/shrzdSpxwUIN3UTBe)

This epic includes the linked issues required to create the Production level version of the centered lead space pattern. 

 ### User story
As an IBM.com user, I need to have a high level understanding of the page's content, so that I can make a decision whether I should continue reading or not.

### Additional information
This is to develop and build the centered lead space module pattern captured from the STUF and NUT projects, and used by the Watson Marketing team.

<img width="922" alt="screen shot 2019-09-01 at 4 16 05 pm" src="https://media.github.ibm.com/user/25726/files/d2e68800-ccd3-11e9-8740-d54f729f4947">

**Comment by larahanlon2** [comment]
Design specs are now available on Abstract: https://share.goabstract.com/3dc277d5-0f03-4ace-8c04-eb33d35085fb?
