### ISSUE TITLE
Pattern: Lead Space QA testing - Prod level - Round 1

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1097]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library Lead Space - centered pattern

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - [Lead Space - centered designs](https://share.goabstract.com/3dc277d5-0f03-4ace-8c04-eb33d35085fb?)
 - [Lead Space - centered functional specifications](https://ibm.ent.box.com/file/602280774308)
 - Lead Space - centered design issue (#379)
 - Lead Space - centered alpha dev issue (#437)
 - Design QA testing issue (#1218)

#### Acceptance criteria
- [x] Accessibility testing is complete.  Pattern is compliant.
- [x] All browser versions are tested
- [x] All operating systems are tested
- [x] All devices are tested
- [x] Defects are recorded and retested when fixed

**Comment by larahanlon2** [comment]
The issue description above has been updated with the new Abstract link for design specs: 
https://share.goabstract.com/3dc277d5-0f03-4ace-8c04-eb33d35085fb?

**Comment by larahanlon2** [comment]
@Praveen-sr @chetankan for QA of `lead space – centered` designs, please find the specifications on [Abstract](https://share.goabstract.com/3dc277d5-0f03-4ace-8c04-eb33d35085fb?).

**Comment by jeffchew** [comment]
@RobertaJHahn @Praveen-sr @chetankan I have added the link to the functional specifications above.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I have added a link in the Additional Information section of this issue to the Box note with instructions on how to create a new Bug in Github.  Let me know if you have any questions.  Also, feel free to change/improve the instructions as needed.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I am closing this issue as the work is finished for sprint 20-04.  I have opened a new issue (#1554) for the work to be done in sprint 20-05.
