### ISSUE TITLE
Make recommendations regarding the browser scope, iOS and android versions included in QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1106]
Collect the information you have and be prepared to talk about the browser scope, iOS and android versions that should be included in the production level testing.

The goal is to make a decision in the Jan 21 meeting on these topics.  

#### Additional Information
 - [browser standards](https://w3.ibm.com/standards/web/browser/)
 - Jan 20 thoughts are to test both Tier 1 & Tier 2 browsers/versions.  Tier 1 defects will be created and Sev 1 & Sev 2.  Tier 2 defects will be created as Sev 3.

**Comment by Praveen-sr** [comment]
Here are the stats for worldwide devices and browser usage, for iOS,  Android, Windows and Mac. 
[BrowserStats.docx](https://github.com/carbon-design-system/ibm-dotcom-library/files/4090767/BrowserStats.docx)

**Comment by RobertaJHahn** [comment]
Jan 21, 2020 meeting decisions:  
**QA testing scope**
Platforms: Desktop 1, Mobile 2, Tablet 3

Mobile & Tablet iOS versions:  13.1 and 13.3
Mobile & Tablet Android versions:  9.0 Pie and 8.1 Oreo

**Browser versions**
Desktop:  Chrome, Firefox, Safari, Edge, IE
Tablet:  Safari, Chrome, Android
Mobile:  Chrome, Safari, Samsung Internet, UC Browser
