### ISSUE TITLE
Test case documentation

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1107]
Investigate the options to store the manual test cases and results for the QA testing.  Present your recommendation for discussion in the Jan 2, 2020 meeting with the DDS Leadership.

**Comment by Praveen-sr** [comment]
Here is the Test cases Template, we have created.
[IBM.comLib_Testcase.xlsx](https://github.com/carbon-design-system/ibm-dotcom-library/files/4090751/IBM.comLib_Testcase.xlsx)

**Comment by RobertaJHahn** [comment]
The testing template will be stored in the QA team Box folder.  [IBM Digital Design Squad/QA Docs](https://ibm.ent.box.com/folder/100898435251)

The test case spreadsheets will be stored in the ibm.com Library Box folder.  [ibm.com Library/QA Testing Docs](https://ibm.ent.box.com/folder/100897002419)
