### ISSUE TITLE
Masthead L0: dropdown does not close when another dropdown is opened

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#111]
Is it possible to close one dropdown menu when another L0 dropdown is selected? Right now, this is what happens if I don't manually close:
<img width="982" alt="Screen Shot 2019-09-23 at 11 54 59 AM" src="https://user-images.githubusercontent.com/53093550/65441899-35293900-ddf9-11e9-8f37-3e656a17e7f2.png">

**Comment by oliviaflory** [comment]
@kennylam one additional thing I noticed when reviewing the PR today and thought I'd point this out to you. We should make sure the L0 and L1 menus can't be open at the same time like the screenshot below. 

<img width="435" alt="Screen Shot 2019-10-03 at 8 58 31 AM" src="https://user-images.githubusercontent.com/45692622/66128738-7b7e5500-e5bc-11e9-8ed9-f78f94655825.png">

Let me know if this increases the scope of this issue too much and I can open a different one.
