### ISSUE TITLE
Component:  Video Player - Update the Kaltura interface to the Carbon specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1113]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter developer

> I need to:
swap the default icons in the Kaltura video player with the Carbon icons  

> so that I can:
provide a component that meets the design requirements

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Other Carbon style updates may be required
 - Visual specs Issue (#1723)
- Updated Functional specs issue (#  )
- Design QA testing issue (# )
- Prod QA testing issue (#  )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by jeffchew** [comment]
@RobertaJHahn @wonilsuhibm @ljcarot we probably wont' be getting to this in this sprint, right?

**Comment by RobertaJHahn** [comment]
@jeffchew The embedded video development was completed in sprint 20-05.  The Lightbox version development is scheduled for sprint 20-06.  Would it be best to make these changes after code is finished for the April release?  Is there design work to be done that should be scheduled in the next sprint?

cc:  @ljcarot @wonilsuhibm

**Comment by RobertaJHahn** [comment]
Not stale.  The work has not been scheduled due to other priorities.
