### ISSUE TITLE
Expressive theme – Data table

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1114]
*Note: all instances of `Sticky header (experimental)` knobs seem buggy :bug: Can we check with Carbon team if these are intended to be "experimental" or production ready.*

## Default
- [x] check that headline line height is 22px in CSS
*Row height changes applies to all variations*
- [x] update 24px row height to 32px (compact)
- [x] update 32px row height to 40px (short)
- [x] update 64px row height to 72px (tall)

## with toolbar 
- [x] update settings icon to 20x20px
- [x] update search icon to 20x20px
- [x] update close icon to 20x20px (when search has something typed into the field)

## with sorting
- No changes

## with selection
- [x] Note: checkbox needs to be reverted back to original size, and checked again.
- alignment of icon / text is weird, but consistent with Carbon

## with radio button selection
- No changes
- alignment of icon / text is weird, but consistent with Carbon

## with expansion
- [x] update chevron icon to 20x20px, reference dropdown icon size for reference.
- [ ] `zebra row styles` is broken (showing all white rows instead of alternating background colors), this might be a :bug: on Carbon side?

## with batch expansion
- [x] Note: checkbox needs to be reverted back to original size, and checked again.
- [x] update chevron icon to 20x20px *in table header*, reference dropdown icon size for reference.
- [ ] `zebra row styles` is broken (showing all white rows instead of alternating background colors), this might be a :bug: on Carbon side?

##  with batch actions
- [x] update icons to 20x20px *in table toolbar*
![Screen Shot 2020-01-20 at 4.09.56 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/29924395-ba5b-4579-bf59-b6e7fd657b67)

## with dynamic content
- [x] Note: checkbox needs to be reverted back to original size, and checked again.
- [x] update chevron icon to 20x20px, reference dropdown icon size for reference.
- [x] checkbox icons are not aligned with checkbox in table header
![Screen Shot 2020-01-20 at 4.12.12 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/6162a6bf-51e9-4ca7-af9f-3e7cb74559cf)

- [ ] `zebra row styles` is broken (showing all white rows instead of alternating background colors), this might be a :bug: on Carbon side?

## with boolean column
- [x] Note: checkbox needs to be reverted back to original size, and checked again.

## with options
- [x] Note: checkbox needs to be reverted back to original size, and checked again.
- [x] update chevron icon to 20x20px, reference dropdown icon size for reference.
- [x] checkbox icons are not aligned with checkbox in table header
![Screen Shot 2020-01-20 at 4.12.12 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/6162a6bf-51e9-4ca7-af9f-3e7cb74559cf)

- [ ] `zebra row styles` is broken (showing all white rows instead of alternating background colors), this might be a :bug: on Carbon side?

## with overflow menu
- [x] Note: checkbox needs to be reverted back to original size, and checked again.
- [x] confirm if this is using it's own version of overflow menu, or will inherit changes to [overflow menu](https://carbon-expressive.mybluemix.net/?path=/story/overflowmenu--basic)

**Comment by andysherman2121** [comment]
Zebra row styles is broken on the Carbon side, will submit a ticket for them

**Comment by RobertaJHahn** [comment]
@andysherman2121 Moving this issue out to spr 20-05 since you are waiting for Carbon.
