### ISSUE TITLE
[LeadSpace] Upgrade Lead Space and LeadSpaceCentered to spec v1.0.0

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1115]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have a consolidated Lead Space pattern available 

> so that I can:
utilize the right Lead Space pattern in my application

#### Additional information

 - [Functional specs v1.0.0](https://ibm.ent.box.com/file/600231329481)
 - [Lead Space Centered in Storybook](https://ibmdotcom-patterns-react-experimental.mybluemix.net/?path=/story/leadspace-centered--centered-with-no-image)
 - [Lead Space Left Aligned in Storybook](https://ibmdotcom-patterns-react-experimental.mybluemix.net/?path=/story/leadspace--default-with-no-image)
 - Design QA testing issue (#1208)
 - Prod QA testing issue (#1097)

#### Acceptance criteria
 - [x] Consolidate to a single component for Lead Space per functional specs
 - [ ] Minimum 80% unit test coverage
 - [x] Remove feature flag
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] Assign Wonil to the Design QA issue
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by RobertaJHahn** [comment]
@andysherman2121 @annawen1 Removing Anna and assigning Andy
