### ISSUE TITLE
Masthead: dropdown sub-link focus state is buggy

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#112]
When focusing on a dropdown sub-link, the blue border does not expand full width of the dropdown container. @kennylam I'm guessing this is the issue we talked about re: the divider lines indenting by 16px either side?

Also, 1px of the blue border is hidden _underneath_ the gray divider – can it appear above, instead?

<img width="891" alt="Screen Shot 2019-09-23 at 10 18 42 AM" src="https://user-images.githubusercontent.com/53093550/65442354-03fd3880-ddfa-11e9-9d17-f4d6ae556b13.png">

**Comment by kennylam** [comment]
> I'm guessing this is the issue we talked about re: the divider lines indenting by 16px either side?

@larahanlon2 Yep that's exactly what this is. I'm going to redo the layout and have the borders to full-width. We will add a gap for multiple subnavs when the time comes.
