### ISSUE TITLE
Pattern Ontology Update: Feature card Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1122]
The `Feature card` pattern needs to be updated to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2)

#### Acceptance criteria
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Dev issue created and added to the Epic: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1191

**Comment by larahanlon2** [comment]
Abstract specs can be found here: https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?
