### ISSUE TITLE
Pattern Ontology Update: Content group — with pictograms Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1123]
The `Content group — with pictograms` pattern needs to be updated to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/xngulixjv6oem8sdgreoslw2tu9d6udr)

#### Acceptance criteria
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
The following functional specs have been updated/added:
Content Group - With Pictograms: https://ibm.ent.box.com/file/566302506034
Pictogram Item: https://ibm.ent.box.com/file/604131694379
Link With Icon: https://ibm.ent.box.com/file/566276906925
Markdown Utility: https://ibm.ent.box.com/file/604090824435

**Comment by jeffchew** [comment]
Dev issues created: 
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1164
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1165
