### ISSUE TITLE
Pattern Ontology Update: Content group — with cards Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1124]
The `Content group — with cards` pattern needs to be updated to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/px2557guu928pwu3umr71t255u409teu)

#### Acceptance criteria
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Dev story created: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1172

**Comment by photodow** [comment]
I created this bug, and before realizing the irony of it. Figured I'd put it here since it's related.

https://github.com/carbon-design-system/ibm-dotcom-library/issues/1174
