### ISSUE TITLE
Pattern Ontology: Content group — simple Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1125]
The `Content group — simple` pattern needs to be fleshed out to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/qr79cf05udkczh5n1vxd65r1rwxxj39e)

#### Acceptance criteria
 - [x] Functional specs need to be finished
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Functional specs created: https://ibm.ent.box.com/file/597415097647

**Comment by jeffchew** [comment]
Dev story created: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1243

**Comment by larahanlon2** [comment]
FYI the design specs are now available on Abstract: https://share.goabstract.com/cc5cd1b3-a485-41af-ad83-1a44be57c5f6?
