### ISSUE TITLE
Pattern Ontology: Content block — simple Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1127]
The `Content block — simple` pattern needs to be fleshed out to reflect latest changes based on the pattern ontology work.

> referencing #1029

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/yg731a7jb3lo8958igx3cn7t649hf15y)

#### Acceptance criteria
 - [x] Functional specs need to be finished
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Functional specifications updated: https://ibm.ent.box.com/file/595011203539

**Comment by jeffchew** [comment]
Dev story created: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1275

**Comment by larahanlon2** [comment]
FYI `Content block – simple` design specs are now updated and available on Abstract: https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca?
