### ISSUE TITLE
Pattern Ontology Update: Card Section Functional Specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1133]
The `Card Section` pattern needs to be updated to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)
- [Functional Specs](https://ibm.box.com/s/6lxup3zn1mbjgas1fv8ky19ntg7unpyv)

#### Acceptance criteria
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Dev story created: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1196
