### ISSUE TITLE
Pattern Ontology Development: Card section - with images -ImageCards --> CardSectionImages

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1136]
We need to make updates to this pattern based on the latest changes to the ontology and functional specs. See acceptance criteria for specifics.

##### Old name:
`ImageCards`

##### New name:
`CardSectionImages`

#### Additional information
 - [Functional Specs](https://ibm.box.com/s/b29xfxv9nltaxva9jzc89x9toptnqsms)
 - [Code](https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/src/patterns/sections/CardSection/ImageCards.js)
 - [Storybook](http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-cardsection--cardsectionimages)
 - Design QA Testing Issue (#1286)
 - Prod QA Testing Issue (#1287)

#### Acceptance criteria
 - [x] Update name in code `classes`, `files`, `docs`, `component`, `stable-selectors`, `ect`
    - Do directory search to make sure we got everything.
 - [x] Align prop names to data model.
 - [ ] Validate data based on functional specs
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [ ] Assign Wonil to the Design QA issue
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by mkothur** [comment]
@RobertaJHahn 
This got merged and ready for QA testing.
