### ISSUE TITLE
Component:  Embedded Video Player prod level QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1140]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library embedded video player component

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - **When testing, focus on the visual aspect of the video player.**
 - [Functional specs Box link](https://ibm.ent.box.com/file/600045806474)
 - [For the design specs, refer to the video section of the following file](https://ibm.box.com/s/36x742wza48h9zl5p3jfkq55me0fbcij)
- [storybook video player](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-videoplayer--default)
 - [CTA link](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-cta--default)
 - The aspect ratio for the video player should always be 16 x 9
- The Kaltura video player is being used "as is".  
 - Dev issue (#1108)   

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
Olivia and Seth will create the pdf version and post to [this folder](https://ibm.ent.box.com/folder/94223126250)

**Comment by RobertaJHahn** [comment]
@sethibm I saw the slack conversation about using the Invision tool rather than creating a pdf.  Looks like Wonil decided to create the pdf.  Will you be posting the pdf link to the Box folder soon?  The QA team members have to begin their testing as soon as the development is finished.  

cc:  @Praveen-sr @chetankan

**Comment by sethibm** [comment]
@RobertaJHahn, yes, I'm trying to get a few last questions answered first, as it takes about 10 minutes or so to export everything and make a PDF.  Awaiting input from @photodow in squad thread.  It's close!  

cc: @Praveen-sr @chetankan

**Comment by sethibm** [comment]
@chetankan @Praveen-sr The visual design spec for the video player are complete and the latest link is posted above in the **Additional information** section. Please let me know if you have questions.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Another issue without status comments.

**Comment by Praveen-sr** [comment]
We have completed functional, design and accessibility (keyboard and screen reader) testing for this component.
