### ISSUE TITLE
Pattern:  Table of Contents Production level QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1142]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Table of Contents`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - Design specs on [Abstract](https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34)
 - Functional specs (#1063)
 - Dev issue (#1201)
 - Design QA testing is finished.  No notification is needed when the Prod QA testing is finished.

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by larahanlon2** [comment]
@RobertaJHahn @Praveen-sr @chetankan 
Table of Contents design specs are now available on Abstract: https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34?

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan The development is finished on this pattern.  It is ready for your testing to begin.

**Comment by RobertaJHahn** [comment]
First round of QA and accessibility testing is finished.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Could you do a second round of testing on this pattern.

**Comment by chetankan** [comment]
@RobertaJHahn : Sure.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan You have completed the second round of testing on this pattern.  I am closing it.
