### ISSUE TITLE
Component: Dev Video player Design & Prod level QA testing support

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1143]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
fix the defects created by the Designers, function testers and UAT testers 

> so that I can:
be confident that pattern developed is of high quality

#### Additional information

- Design (#1349  )
- Functional Specs (#1066  )
- Dev Issue (#1108  )

#### Acceptance criteria
 - [x] Sev 1-3 QA defects are fixed
 - [x] Tested React component within the Patterns Storybook
 - [x]  A message is posted to the Design QA issue, tagging @sethibm when finished, to let him know when he can begin the Design QA testing.

**Comment by kennylam** [comment]
@sethibm this is ready for design review
http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player

http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-videoplayer--default

**Comment by sethibm** [comment]
@kennylam Thanks.  Question: how does this review and work to date on video player relate to this story I've been working on?  

https://github.com/carbon-design-system/ibm-dotcom-library/issues/1350

It's the visual spec for the video player, and it's confusing whether I'm supposed to use this document, that's not quite done and approved, as the benchmark to review the latest video player?
