### ISSUE TITLE
Masthead: there is motion latency on dropdown rollover 

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#115]
When hovering/rolling over the `dropdown menu` in both L0 and L1 there is a slight delay in state change from top to bottom. It's taking too long for the `hover` state to deactivate when the mouse rolls over another menu item. It's as if it's sticking.

I don't know if it's a bug or styling issue? Either way, it should behave more like [Carbon's UI header](https://www.carbondesignsystem.com/components/UI-shell-header/code/).

Screen recordings in here for test:
[masthead-dropdown-rollover.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/3643318/masthead-dropdown-rollover.zip)

This is related to [issue #112](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/112)

____
REF: https://ibmdotcom-react.netlify.com/?path=/story/masthead--default-with-l1

**Comment by kennylam** [comment]
@larahanlon2 These transition values come directly from the Carbon components. We haven't modified those.
```
background-color 110ms, border-color 110ms, color 110ms;
```
http://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation-and-actions
