### ISSUE TITLE
Expressive theme – UI Shell

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1161]
# WIP issue
This component is quite complex and we'd like to make as little updates as possible, it would be helpful to sit with the developer handling this component to review before making these updates.

### Header base
- looks good

### Header base w/ navigation
- [ ] navigation link text is 14px on desktop, is it not connected to a body-01 type token? possibly increase size.
- [x] update height of left side panel link container from 32 -> 40px tall
![Screen Shot 2020-01-23 at 10.46.19 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/d2249355-e536-449f-9ed4-1cb611e0481e)

### Header base w/ action
- [x] looks good

### Header base w/ navigation, actions and side nav
- [ ] side nav links don't seem to be connected to a type token? possibly increase size.
- possibly update icon sizes
- [x] update height of left side panel link container from 32 -> 40px tall
![Screen Shot 2020-01-23 at 12.51.12 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/60a85a45-a726-4490-bf06-06cbe32e6a73)

### Header base w/ side nav
- hopefully inherits any changes we make from previous example

### Header base w/ actions and switcher
- [x] update height of switcher panel link container from 32 -> 40px tall
![Screen Shot 2020-01-23 at 12.59.50 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/e00cb53d-472d-4efd-9e4c-d98e776e85b7)

### Fixed side nav
- hopefully inherits any changes we make from header base w/ actions and right panel

### Fixed side nav w/ icons
- hopefully inherits any changes we make from header base w/ actions and right panel

### Side nav rail
- hopefully inherits any changes we make from header base w/ actions and right panel

### Side nav rail w/ header
- hopefully inherits any changes we make from header base w/ actions and right panel
- link 4 in the header looks broken or :bug: 
![Jan-23-2020 13-08-59.gif](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/35a09d0b-3fc8-47fb-a37a-0073618f1231)

### Side nav w/ large side nav items
- ~this one is... crazy. need to review further before making changes~
- hopefully inherits container size changes from other examples.
- leave "large" heading as is.

**Comment by annawen1** [comment]
### Header base w/ navigation
- the navigation link text seems to be hardcoded, not using the body-01 type token
<img width="581" alt="Screen Shot 2020-01-29 at 2 44 03 PM" src="https://user-images.githubusercontent.com/54281166/73391693-6ed9e700-42a6-11ea-9558-7310d5e256cc.png">

**Comment by RobertaJHahn** [comment]
@annawen1 Moving this issue to sprint 20-05 so that you can focus on the Learn page pattern and component assignments in sprint 20-03.

**Comment by jeffchew** [comment]
Moving out to sprint 9, will be focusing on the RFC instead.
