### ISSUE TITLE
Pictogram Item: Updates to the Pictogram Item per Functional Specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1164]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have a PIctogramItem component available

> so that I can:
use this sub-pattern in pattern blocks/sections

#### Additional information

 - Functional specs: https://ibm.ent.box.com/file/604131694379
- Component currently is nested under the `PictogramArray` (dev story to update to `ContentGroupPictograms`: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1165)

#### Acceptance criteria
 - [x] `PictogramItem` pattern added under `sub-patterns` in Storybook
 - [x] `PictogramItem` moved into the `sub-patterns` folder in the React package
 - [x] Minimum 80% unit test coverage

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Moving this issue to sprint 20-03 so that I can close out sprint 20-02.  You should continue your work with the expectation to finish it before the end of sprint 20-03, Friday Feb 14.
