### ISSUE TITLE
Content group - with Pictograms: Updates per functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1165]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have a ContentGroupPictograms component available

> so that I can:
use this block pattern in my application

#### Additional information

 - Functional specifications: https://ibm.ent.box.com/file/566302506034
 - Dev issue to update the `PictogramItem`: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1164, which should be a separate component entirely
- `ContentGroupPictograms` is a decorator pattern of `ContentGroup`
- Design QA testing issue (#1218)
- Prod QA testing issue (#1219)

#### Acceptance criteria
 - [x] `PictogramArray` renamed to `ContentGroupPictograms`
 - [x] `ContentGroupPictograms` under Block patterns
 - [x] Remove feature flag
 - [x] Update all corresponding documentation and Storybook stories
 - [x] Minimum 80% unit test coverage
- [x] A comment is posted in the Design QA issue, tagging Wonil, Olivia and Roberta, when development is finished
- [x] Assign the Design QA issue to Wonil and Olivia
 - [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is

**Comment by photodow** [comment]
Saw you created this, I discovered this "bug" as I was looking at the content group. Thought I'd share it here as apart of this work.

https://github.com/carbon-design-system/ibm-dotcom-library/issues/1174
