### ISSUE TITLE
ContentGroupPictogram & ContentGroupArray Grid is off

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1174]
## Detailed description

I'm seeing some grid alignment issues with the `ContentGroupCards`, and `ContentGroupPictogram`. I'm wondering if there is an issue with how the offset columns are working.

**Honestly, we need to remove the grid from these completely so it'll sit within the new `ContentBlock` sub-pattern.**

## Steps to reproduce the issue

1. Download chrome extension tool [IBM Dotcom Devtools](https://chrome.google.com/webstore/detail/ibm-dotcom-devtools/oejjaglcafcolafkjecfkoojgnpfpgca)
2. Turn the grid on using the extension
3. Resize browser and you'll see the issue.

## Additional information

![image](https://user-images.githubusercontent.com/3793636/73031171-fafc9200-3e00-11ea-9e94-ec5551955c5d.png)

![image](https://user-images.githubusercontent.com/3793636/73031224-297a6d00-3e01-11ea-9184-4e677d0cad0e.png)

**Comment by jeffchew** [comment]
@RobertaJHahn @ljcarot @wonilsuhibm need to set a severity for this one.

**Comment by RobertaJHahn** [comment]
@photodow Could you retest this to see whether the development updates have fixed this issue.  If fixed, feel free to close.
