### ISSUE TITLE
In Carbon, remove Cookie Notice in Canada Footer as was done in v18

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#1175]
Description:
In December 2019, a request came to DDS to remove the pop up Cookie Notice that appears only on Canada pages.  DDS fixed that in the v18 code but now DDS needs to do the same in Carbon code.  URX page is now live in Carbon and we noticed that the pop-up is displaying on a URX page viewed in Canada.
-->
> Is this a feature request : New request

> Is this issue related to a specific component?  Footer

> What did you expect to happen? What happened instead? What would you like to see changed?
(see above)

> What browser are you working in?
all are impacted

> What version of the IBM.com Library are you using?
Would have to check what URX page is using.

## Steps to reproduce the issue

1. Step one: Go to https://www.ibm.com/account/reg/ca-en/signup?formid=urx-19776
2. Step two: See that the Cookie Notice appears at bottom of form.

Notes: to see implementation working correctly go to any v18 page in Canada and note that Cookie Notice does not appear.

To be resolved:  For now in Carbon, let's leave Ad Choices below the Footer until Design has had a chance to resolve final design in Carbon.

**Comment by jeffchew** [comment]
@ljcarot this might not be us. They may still be on an older version of v18, but can't be certain since I can't find it on their page. We also never implemented the canada cookie popup in the IBM.com Library. According to the DigitalData object, the version is still showing v18, so the footer might be custom on their end?

**Comment by jeffchew** [comment]
@ljcarot is this still happening?

**Comment by RobertaJHahn** [comment]
@ljcarot moving this issue to sprint 20-06.  Just wondering if you have an update?

**Comment by RobertaJHahn** [comment]
@Jeff Chew can you check if this is the correct cookie notice that should be displaying on the canada version of [URX form?](https://www.ibm.com/account/reg/ca-en/signup?formid=urx-19776)

**Comment by jeffchew** [comment]
We never implemented the cookie notice in IBM.com Library. This implementation appears to be from TrustArc.
