### ISSUE TITLE
Pattern: Lead Space -  [Functional specs update] The image is outside the lead space section on mobile devices.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1177]
## Detailed description

Device:- iPhone 11 Pro 
OS - iOS 13 version
Browser:- Safari

Verified on Browser Stack 

Issue:-
1. Lead space centered with image, here the image is appearing outside the lead space section.
2. Lead Space Centered – The Title, copy and the buttons are left aligned.

Expected:- 
Image on the lead space centered must be at the background of the lead space.
The Title, copy and the buttons must be center aligned.
## Steps to reproduce the issue

1. Open Browser stack app and select Live Interactive cross browser testing
2. Select device as iOS and iPhone 11 Pro
3. Select the browser as Safari and load the URL 
4. Verify the Lead Space centered with image section.

## Additional information

iPhone:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e5433476-c7c2-4706-95f4-d677271ddc02)

Android: 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/33cc6655-bd66-48ba-a2fc-f072064bdb37)

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I have linked this issue to Epic (#1149) instead of Lead Space - Centered Issue (#1096).  This pattern is affected by the remaining work.  I will be closing the Lead Space - Centered epic.  Please link the future bugs to epic (#1149)

**Comment by jeffchew** [comment]
@RobertaJHahn I'm trying to recall what the functional spec update is needed here, do you recall?

**Comment by RobertaJHahn** [comment]
@jeffchew Not sure how this is documented in the functional specs, but it looks like the title, copy and buttons must be centered at the small break point.  [https://ibm.ent.box.com/file/559973030344]

There are quite a few Lead Space issues.  Can't tell where this fix is going to be made in the code.

**Comment by RobertaJHahn** [comment]
Functional update:  Add to the mobile behavior for the centered lead space, the image will drop below the content.

**Comment by jeffchew** [comment]
Functional specifications updated: https://ibm.ent.box.com/file/600231329481

The section modified is under the "centered" leadspace type for mobile.
