### ISSUE TITLE
Pattern: Lead Space - Buttons are different size compared to the lead space left aligned section.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1178]
## Detailed description
Device:- Windows 10 and Mac
Browser:- Firefox 72.0.2, Chrome 79.0.3945.117, Safari 13

Verified on Actual device and Browser Stack

Issue:- Lead Space Centered – Buttons are of different size compared to the lead space left aligned. 
Expected:- Lead Space Centered - Buttons size should be aligned along with the Lead space left aligned section.

## Steps to reproduce the issue

1. Open the browser ( Firefox, chrome or Safari) 
2. Open the Storybook URL on the browser 
3. Select Lead Space Centered section
4. Verify the buttons on the lead Space Centered section.

## Additional information

Windows 10:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3128d407-2148-4a62-8b93-23d25f62541c)
Mac:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/0be4e825-dd54-4123-a055-64a8fa6d843f)
Lead Space left aligned buttons:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8cf40552-385b-49bc-9377-4abb77858742)

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I have linked this issue to Epic (#1149) instead of Lead Space - Centered Issue (#1096).  This pattern is affected by the remaining work.  I will be closing the Lead Space - Centered epic.  Please link the future bugs to epic (#1149)

**Comment by andysherman2121** [comment]
@Praveen-sr I noticed that this was an old issue assuming from the alpha version when LeadSpace and LeadSpace centered were two different components. @larahanlon2 and I looked this over and it seems to be working correctly. Wanted to make sure that you aren't still seeing this issue

**Comment by Praveen-sr** [comment]
@andysherman2121 Yes, this seems an old issue. 
As discussed on call, [#1574](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1574) is the issue which we facing on Mobile needs to be addressed.
Thanks!
