### ISSUE TITLE
Masthead L0: copy change request for Search

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#118]
When the masthead has **no** platform/page title can the `search` input text read: _Search all of IBM_ (instead of just _Search_).

<img width="1665" alt="Screen Shot 2019-09-23 at 1 47 57 PM" src="https://user-images.githubusercontent.com/53093550/65449643-63167980-de09-11e9-9d9d-2288bb6f7d78.png">

**Comment by jeffchew** [comment]
Can we check if this is being hardcoded or set from the translation file? The placeholder text in Northstar seems to be just `Search`.

**Comment by oliviaflory** [comment]
Looks like the platform/hasName version of the masthead also says *Search all of IBM* 

@kennylam Is it possible for the search placeholder to be different between the two variations? 

From a functionality standpoint, is the search bar searching all of IBM dotcom when it is a platform/hasName or is it limited to searching only within that platform (like Cloud)?
