### ISSUE TITLE
Leadspace: Content not staying aligned to the grid

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1182]
It looks like the content is not staying aligned to the grid for large, XL and max breakpoints.

All examples seen in Chrome:

Large:
![image](https://user-images.githubusercontent.com/57198117/73080293-99393800-3e93-11ea-8190-b20bf4afe315.png)

XL:
![image](https://user-images.githubusercontent.com/57198117/73080317-a22a0980-3e93-11ea-84ca-5113d84f6c46.png)

Max:
![image](https://user-images.githubusercontent.com/57198117/73080346-ad7d3500-3e93-11ea-94a1-8d79df82288d.png)

For all of these breakpoints the content should start aligned on the 5th column (4 empty on the left)

**Comment by jeffchew** [comment]
@RobertaJHahn @ljcarot @wonilsuhibm need to track this one as well.
