### ISSUE TITLE
Leadspace: Top spacing fixes

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1184]
Viewed on Chrome

Spacing above the text in the leadspace for Large, XL and Max sizes should be 64px. It is currently 32px.

![image](https://user-images.githubusercontent.com/57198117/73092074-d7d9ed00-3ea9-11ea-9d0e-b2842770b178.png)

**Comment by jeffchew** [comment]
@RobertaJHahn @ljcarot @wonilsuhibm we need to set a severity for this one, but I added it to the epic so we can track it.
