### ISSUE TITLE
Pattern: Table of Contents Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1203]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Table of Contents`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - alpha Dev link (#1064 )
- Functional specs (#1063 )

 #### Tasks
Ensure the `Table of Contents` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by larahanlon2** [comment]
FYI Table of Contents design specs are now available on Abstract: https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34?

**Comment by RobertaJHahn** [comment]
@wonilsuhibm The development is finished on this pattern and is ready for Design QA testing.

**Comment by jacobottesen-dgc** [comment]
I have finished QA for browser viewports, spacing, icon, and type size.

I still need to QA grid alignment in Google Chrome but I am having issues with Chrome opening on my computer. I'll be getting help from the Help desk on Monday then wrap this task issue. 

cc. @RobertaJHahn
