### ISSUE TITLE
Pattern: Using special characters (&, ",', <>) in 'Title' and 'Copy',  characters are shown as there hexadecimal values.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1206]
## Detailed description

Device:- Windows, Mac
Browser:- Chrome, Safari

Issue :- When we enter special characters in Title and copy, special characters are shown as there hexadecimal values.  
Expected :- Only the Special characters needs to shown.

This is not happening in Drupal.  This is only happening for adopters directly using the React patterns.

## Steps to reproduce the issue

1. Open the browser ( Firefox, chrome or Safari)
2. Open the Storybook URL on the browser
3. Select Lead Space Centered section
4. Edit knobs and enter special character values for Title, Copy
4. Verify the entered special characters view on the lead Space section.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f000d760-d62d-4c24-b3db-739f9b943bb2)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/764e0e9f-b7b7-4866-aa42-5c7ad2c3f92c)

**Comment by RobertaJHahn** [comment]
Wonil, heard from Jill that the patterns must allow special characters.

**Comment by RaphaelAmadeu** [comment]
This is only happening in storybook, due to the way it handles strings,
After testing it on an isolated environment, the usage of the HTML entities is working properly.

As we can see in this example I made:
https://codesandbox.io/s/cocky-napier-7t40y,

@RobertaJHahn I think we can close this issue,
Thanks!
