### ISSUE TITLE
Pattern Ontology:  Content block - with media functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1207]
The `Content block - with media` pattern needs to be created to reflect latest changes based on the pattern ontology work.

#### Additional information
- [Airtable with naming and ontology](https://airtable.com/shrzdSpxwUIN3UTBe)
- [Mural with visual ontology and relationships](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7)

#### Acceptance criteria
 - [x] Create functional specs for this
 - [x] file, directory, and code name is reflected of airtable
 - [x] References are updated to handle new names (search page for references outside of resources)
 - [x] Update with Type and Level
 - [x] Create stories for development based on changes to ontology

**Comment by jeffchew** [comment]
Functional specs created:
https://ibm.ent.box.com/file/607045243803

**Comment by jeffchew** [comment]
Dev story: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1238
