### ISSUE TITLE
Pattern: Feature Card Design QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1212]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Feature Card`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - alpha Dev link (#706 )
 - Alpha Design QA testing (#912)  
- Functional specs (#1122 )
- Abstract design specs can be found [here](https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?).

 #### Tasks
Ensure the `Feature Card` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by larahanlon2** [comment]
**Abstract** specs can be found here: https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?

**Comment by annawen1** [comment]
@wonilsuhibm @RobertaJHahn development is done
