### ISSUE TITLE
Pattern: Feature Card QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1213]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Feature card`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - [Feature Card Designs](https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?)
 - Functional specs Issue (#1122)
 - design issue (#659)
 - Alpha dev issue (#658)
 - Design QA testing issue (#1212)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [ ] Assign Wonil to the Design QA issue

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan We have decided that this pattern should be the next to test.  I will have one of the designers create that abstract version of the designs for you.  The epic with all of the linked issues is (#1138)

**Comment by larahanlon2** [comment]
**Abstract** specs can be found here: https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?

**Comment by annawen1** [comment]
@Praveen-sr @chetankan development is done

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan All of the defects for this pattern have been fixed.  Could you do a second round of testing on this pattern.  Thanks.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Moving this issue to sprint 20-05 for the second round of testing on this pattern.
