### ISSUE TITLE
Pattern: Content group - with pictograms Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1218]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content group - with pictograms`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Dev link (#1165 )
- design folder is on [Box](https://ibm.box.com/s/af11r4k5fv1wclv1yrl9aic5c68x29ra)
- [Functional specs](https://ibm.ent.box.com/file/566302506034)
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Content group - with pictograms` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm , @RobertaJHahn , @oliviaflory 
This was merged in, and it's ready for QA,
Thanks!
