### ISSUE TITLE
Pattern: Content group - with pictograms QA testing - Production level version 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1219]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Content group - with pictograms`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- design folder is on [Box](https://ibm.box.com/s/af11r4k5fv1wclv1yrl9aic5c68x29ra)
 - Dev link (#1165 )
- [Functional specs](https://ibm.ent.box.com/file/566302506034)- Link to the functional specs
 - Design QA testing issue (#1218)
 

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [ ] Assign Wonil to the Design QA issue

**Comment by wonilsuhibm** [comment]
@Praveen-sr @chetankan The design specs are available through the Box folder added in the above description.

**Comment by RobertaJHahn** [comment]
Testing Status on 2/5/2020:  functional testing is complete.  Design review in progress.  Accessibility testing in progress.

**Comment by RobertaJHahn** [comment]
Testing status 2/6/2020:  Screen reader accessibility testing is the only testing remaining.

**Comment by chetankan** [comment]
Testing Status:- Finished , Design and Accessibility(DAP, Keyboard, CCA) is done, and screen reader is in progress.

**Comment by RaphaelAmadeu** [comment]
@chetankan , @Praveen-sr ,
The updated version was merged in, and it's ready for QA,
Thanks!
