### ISSUE TITLE
Update Video page on v18 standards

### ISSUE THREAD

**Issue by bethyaeckel** [carbon-design-system/ibm-dotcom-library#1221]
On this page: https://www.ibm.com/standards/web/components/video/  can you please update the video standards to add the MANDATORY use of Kaltura ID? Please use the 3 bullets I have provided below. 
----------------------------------------------------------------------------------------
- All videos used on ibm.com web pages must be published in Media Center.

- Links to video CTAs pointing to YouTube must also include the alternate source from Media Center (Kaltura ID).
![Kaltura image](https://user-images.githubusercontent.com/32574847/73271354-6a320780-41ae-11ea-9f03-89fba2dcaa4a.png)

- If Kaltura ID is not possible to add due to template limitation, Media Center link must be used instead.

Best practices:
o   Add the duration of the video and the video icon on CTAs or,
o   Add the duration with the black bar for video players.

**Comment by ljcarot** [comment]
[VideoPlayerStandards-update032720.docx](https://github.com/carbon-design-system/ibm-dotcom-library/files/4393722/VideoPlayerStandards-update032720.docx)
@kennylam above the changes to the Overview section and the Usage section.  For now the rest of the page can stay the same.  Let me know if you have any questions.
