### ISSUE TITLE
Footer navigation fails and breaks page (500 error)

### ISSUE THREAD

**Issue by jcpalaci** [carbon-design-system/ibm-dotcom-library#1223]
## Detailed description

> Describe in detail the issue you're having.

Four spanish locales (es-ar, es-co, es-cl, es-pe) are failing in MH search, we are getting 500 errors:
https://www.ibm.com/search?lang=es&cc=ar&q=cloud
Bluemix URL:
https://ibm-com-search.mybluemix.net/search?lang=es&cc=ar&q=cloud

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Footer data or Translation (see screenshot)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No JS errors

> What browser are you working in?

All

> What version of the IBM.com Library are you using?

1.1.2 and 1.3.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM.com Search

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code

![image](https://user-images.githubusercontent.com/57272532/73276203-ee37bf80-41ad-11ea-8ad4-5b69019dc3b4.png)

![image](https://user-images.githubusercontent.com/57272532/73276245-fe4f9f00-41ad-11ea-9404-a39b86910567.png)

- Notes

**Comment by jeffchew** [comment]
The issue was corrupt data files on the EI server. This has been addressed. The following translations seemed to have been affected:

- ares
- boes
- cles
- coes
- eces
- pees
- pyes
- uyes
- vees
