### ISSUE TITLE
[Automation] Investigation of automatic visual testing

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1224]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
enable automated visual testing of the IBMN.com Library

> so that I can:
be consistently aware of any visual impacts from changes in the codebase

#### Additional information

 - Storybook automated visual testing: https://storybook.js.org/docs/testing/automated-visual-testing/
 - Storybook screenshot testing: https://medium.com/bleeding-edge/screenshot-testing-with-react-and-storybook-19ab7e49ec92
 - Visual validation tools: https://testguild.com/top-21-free-visual-validation-tools-testers/
- Include any investigations for cross-browser/device testing to be included in this (would we need the API level version of Browserstack to support this?)

#### Acceptance criteria
 - [ ] Determine the best approach in implementation of automated visual testing
 - [ ] Ideally will have a rough implementation, priority would be the Carbon Expressive storybook
 - [ ] Documentation creation

**Comment by jeffchew** [comment]
Followup meeting with Browserstack scheduled on March 12th.

**Comment by jeffchew** [comment]
Browserstack meeting rescheduled to March 31st.

**Comment by jeffchew** [comment]
Browserstack meeting rescheduled to April 21st at 9am ET.
cc: @RobertaJHahn @Praveen-sr @chetankan

**Comment by chetankan** [comment]
@jeffchew : Thanks for update.
