### ISSUE TITLE
Expressive theme – tertiary button too small

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1225]
The small tertiary button is not the correct container size, it's smaller than all other `small` button variants.
Height is 36px tall, should be 40px tall
![Screen Shot 2020-01-28 at 2.58.30 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/5023db27-faf5-453c-817e-c2171cbded89)

Knob settings to recreate:
![Screen Shot 2020-01-28 at 2.59.00 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/9c62765f-87e8-45d4-b1cb-468e8022027c)

**Comment by RobertaJHahn** [comment]
This problem may be resolved with the work in Issue (#1086).  Will close if this is the case.

**Comment by RobertaJHahn** [comment]
@andysherman2121 Moving this issue out to sprint 20-05, after the Learn Page release.  We would like all of your available time spent on the Learn page patterns scheduled in sprint 20-03.
