### ISSUE TITLE
Abstract migration: Content block - mixed groups (list section)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1226]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Additional Information
- Prod QA Issue (#1290)

### Acceptance criteria
- [x] Change all instance of the name `list section` to `Content block — mixed groups`
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [ ] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by jacobottesen-dgc** [comment]
@RobertaJHahn @Praveen-sr @chetankan
Card design specs are now available on Abstract: https://share.goabstract.com/8630ed30-646b-4be5-90a0-fbb81acd5602
