### ISSUE TITLE
Abstract migration: Table of Contents 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1227]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Additional Information
- Prod QA issue (#1142)

### Acceptance criteria
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by larahanlon2** [comment]
TOC is now available on Abstract: https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34?

**Comment by larahanlon2** [comment]
[README](https://ibm.ent.box.com/notes/611151178753) has been added to Box.
