### ISSUE TITLE
Expressive theme – unexpected behavior using keyboard

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1232]
When using the keyboard to tab through the modal component, the content is selectable. This is unexpected behavior because Carbon's modal content is not selectable. See examples below:

I don't think this is a huge problem, but we should likely follow the Carbon behavior so not to deviate.

**Carbon**
![Carbon modal](https://user-images.githubusercontent.com/45692622/73372508-586f6380-4285-11ea-8bd2-43e0e0e5be8f.gif)

**Expressive**
![Expressive modal](https://user-images.githubusercontent.com/45692622/73372522-602f0800-4285-11ea-9d07-55a34b97b7df.gif)

**Comment by guilhermelMoraes** [comment]
@oliviaflory we're not doing anything different, this is just a prop being passed to the component that changes it's behavior. The `Modal contains scrollable content (hasScrollingContent)` option in the storybook knobs activate/deactivate this selectable area. I can change the default option to false if you want me to do so.

**Comment by oliviaflory** [comment]
Oh ok, thanks for clarifying Gui! When I was comparing to the Carbon storybook it seemed different, but we don't want to change any default behavior, so sounds like we can close this issue!
