### ISSUE TITLE
Content block - mixed groups: Text size fixes

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1233]
Viewed in Chrome

Text sizes for the Title, intro text, and Section headers seem to be using incorrect sizes.

### **Title**
The title should always use Expressive Heading 05. In the current implementation the Title size looks too small.

As seen in Storybook (XL breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381419-b3a85280-4293-11ea-94b5-97a45c6ace3b.png)

As expected (XL breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381462-c884e600-4293-11ea-8924-f3da20cb651b.png)

----------------------------------

### **Intro copy**
The intro copy below the section title should always use Expressive Heading 03. In the current implementation the text does not seem to be scaling properly especially at the Max size.

As seen in Storybook (Max breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381623-10a40880-4294-11ea-89a5-234c872ea0d8.png)

As seen in Storybook (Max breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381637-1863ad00-4294-11ea-9256-70f67e3d112a.png)

----------------------------------

### **Section headers**
Section headers should always use Expressive Heading 04. In the current implementation the headers are looking smaller than expected.

As seen in Storybook (XL breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381886-84461580-4294-11ea-8a9b-74cd13434ecd.png)

As seen in Storybook (XL breakpoint):
![image](https://user-images.githubusercontent.com/57198117/73381904-8b6d2380-4294-11ea-886c-e0b081d6103b.png)

**Comment by ljcarot** [comment]
@ltitle We don't have list section after the rename exercise.  Which pattern are you testing? Can you provide link to where in Storybook you are testing?  thx

**Comment by ltitle** [comment]
@ljcarot I was just using the names in Storybook for the bug referencing. This is where I was testing https://ibmdotcom-patterns-react-experimental.mybluemix.net/?path=/story/sections-list-section--default

**Comment by jeffchew** [comment]
Based on the [Airtable](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide), it's being renamed to `Content Block - Mixed". @photodow is still working on updating the functional specs for it.

**Comment by jeffchew** [comment]
@ltitle also note, we are no longer using https://ibmdotcom-patterns-react-experimental.mybluemix.net. You can find latest under https://ibmdotcom-react-experimental.mybluemix.net.

**Comment by oliviaflory** [comment]
Let's double check if the pattern is using the **fluid** type styles vs a **fixed** size. Seems like the heading styles are not changing per breakpoint like they should.

**Comment by ljcarot** [comment]
Closing issue as this will be addressed as part of refactoring and is part of the spec for the  core pattern called  Content block.
