### ISSUE TITLE
Content block - mixed groups: Spacing fixes

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1234]
Viewed in Chrome

### **Spacing between intro text and the first section header**
This space should be 96px on L, XL, and Max sizes and then scale down to 64px on Med and Small sizes. It is currently only using 64px on L, XL and Max and 32px on Med and Small.

**As seen in Storybook (XL breakpoint):**

![image](https://user-images.githubusercontent.com/57198117/73382380-62995e00-4295-11ea-93e0-ca5492d79aad.png)

**As expected (XL breakpoint):**

![image](https://user-images.githubusercontent.com/57198117/73382409-6d53f300-4295-11ea-8809-68fdceba7c49.png)

-------------------------
### **Top of pattern spacing**
At the medium breakpoint the space at the top of the pattern should reduce to 32px. The current implementation is using 64px and only reducing to 32px for the Small breakpoint.

**As seen in storybook (med breakpoint):**

![image](https://user-images.githubusercontent.com/57198117/73382637-dcc9e280-4295-11ea-8ae9-2a63073a9fcd.png)

**As expected (med breakpoint):**

![image](https://user-images.githubusercontent.com/57198117/73382594-cb80d600-4295-11ea-8cff-0197e7bd9123.png)

---------------------------
### **Spacing between section header and list items**
At the Medium and Small breakpoints the space between the Section heading and the list items gets much larger than expected. It should maintain a 32px spacing at all breakpoints.

**As seen in Storybook (Med breakpoint):**

![image](https://user-images.githubusercontent.com/57198117/73382912-6b3e6400-4296-11ea-80ed-dae8bad6a9df.png)

**As expected (Med breakpoint:**

![image](https://user-images.githubusercontent.com/57198117/73382948-785b5300-4296-11ea-8ba2-aa6e61199100.png)

**Comment by ljcarot** [comment]
Closing issue as this will be addressed as part of refactoring and is part of the spec for the  core pattern called  Content block.
