### ISSUE TITLE
Content group - with pictograms: Section heading size

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1236]
Viewed in Chrome

The section heading for the Pictogram Array pattern should always use Expressive Heading 04. The current headline size being used looks too small.

**As seen in storybook (XL breakpoint):**
![image](https://user-images.githubusercontent.com/57198117/73384628-9e362700-4299-11ea-9945-e7275d7b2844.png)

**As expected:**
![image](https://user-images.githubusercontent.com/57198117/73384586-89f22a00-4299-11ea-835d-685f6645c950.png)

**Comment by oliviaflory** [comment]
Let's double check if the pattern is using the **fluid** type styles vs a **fixed** size. Seems like the heading styles are not changing per breakpoint like they should.

**Comment by ltitle** [comment]
@oliviaflory I am seeing these issues across the board for most patterns using any of the expressive headings

**Comment by photodow** [comment]
I don't believe this component has been updated with the new `ContentGroup` sub-pattern yet, which should be using the `expressive-heading-04` based on what I'm seeing.

**Comment by RobertaJHahn** [comment]
This should be retested after the dev refactoring work is finished.
