### ISSUE TITLE
Content block - mixed groups: Gray background behind some items

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1239]
Viewed in Chrome

I am seeing gray backgrounds appearing behind some list items in Storybook. 
Expected: All items should have a white background.

**As seen in Storybook:**

![image](https://user-images.githubusercontent.com/57198117/73388430-320af180-42a0-11ea-973d-0c5b224fd9bd.png)

**Comment by RobertaJHahn** [comment]
This should be retested after the dev refactoring is finished.
