### ISSUE TITLE
Content block - mixed groups: Misaligned section headers

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1240]
Viewed in Chrome

The section headers for this pattern are not aligning to the grid:

As seen in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73388650-a0e84a80-42a0-11ea-84b2-c5dd5c4d879d.png)

Expected: All content should left align to the grid
![image](https://user-images.githubusercontent.com/57198117/73388705-b8273800-42a0-11ea-9100-001331fb8913.png)

**Comment by RobertaJHahn** [comment]
Retest with the dev refactoring is finished.
