### ISSUE TITLE
April 2020 Release Plan (v1.6.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1242]
# Timeline

- **April 17, 2020**: Code freeze
- **April 20, 2020 - April 27, 2020**: Release Candidate(s) and testing
- **April 28, 2020**: Full Release

# Features
## React
- **Embedded video player** (#724 ):  Learn page template requirements
- **Video player - Lightbox version** (#1192 )
- **Lightbox** (#328 ):  Production ready version
- **Adding optional Linklist to various patterns** (#1920 )
- **Adding VideoPlayer option to various patterns** (#1672)

# Bugs
- **Layout containing ContentBlockSimple and LinkList is missing certain CSS styles** (#1676 )
- **Content Block Media is missing an autoid attribute for optional CTA** (#1747)
- **Card Section Simple Pattern Top Level Card Link is not the same height as the other cards**    (#1880)
- **Content Group Simple is missing an data-autoid attribute for optional CTA** (#1884)
- **Content Group Simple renders item title too high above optional image** (#1890)

**Comment by jeffchew** [comment]
Release created: https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.6.0
