### ISSUE TITLE
Pattern:  Content Group - simple - Create the ContentGroupSimple pattern per functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1243]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have the `ContentGroupSimple` block pattern available

> so that I can:
utilize within my application

#### Additional information

 - Functional specifications: https://ibm.ent.box.com/file/597415097647
 - Is utilized in the `ContentBlockMedia` and `ContentBlockMixed`
 - Design QA testing issue (#1044)
- Prod QA testing issue (#1294)

#### Acceptance criteria
 - [x] Create the `ContentGroupSimple` within the `block` patterns
 - [x] Storybook stories created
 - [x] README documentation
 - [x] Minimum 80% unit test coverage
- [x] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [x] Assign Wonil to the Design QA issue
 - [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Do you think that you can fit this work into sprint 20-03?  @jeffchew

**Comment by larahanlon2** [comment]
FYI the design specs are now available on Abstract: https://share.goabstract.com/cc5cd1b3-a485-41af-ad83-1a44be57c5f6?

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn, as my another tickets are mostly on review, I do think that we can do this on the current sprint.
