### ISSUE TITLE
Component:  Image - with caption functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1245]
The `image component` functional specs are needed to reflect the latest designs and scope agreed with the Web Simplification team.  

#### Additional information
- Image - with caption design Issue (#748)
- [Functional Specs]()

#### Acceptance criteria
 - [x] functional spec file created and shared
 - [x] design and development agree
 - [x] stories created for development to begin prioritizing

**Comment by RobertaJHahn** [comment]
@photodow @jeffchew Here is the functional spec issue for the `image - with caption` component we talked about earlier today.  I have assigned it to the next sprint.

**Comment by photodow** [comment]
@jeffchew @larahanlon2 @wonilsuhibm here are the functional specs for the image with caption. I included the icon and lightboxmediaview. We can just ignore, and release without that feature.

https://ibm.box.com/s/fm5mikceok20or85zm98631i3qt1f203

Also updated #1246.

**Comment by jeffchew** [comment]
Thanks @photodow , we will just include in the dev stories that the lightboxmediaview is out of scope for this initial release.

**Comment by larahanlon2** [comment]
Made some updates to the design specs based on recent conversations with Wonil and Lila re: button size and style. https://share.goabstract.com/c28dcfa6-a5a9-421b-b019-4a3390ff5184?
