### ISSUE TITLE
Component: Develop image - with caption component - Sprint 20-04

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1246]
#### User Story
> As a `[user role below]`:
IBM.com Library developer

> I need to:
develop the `image - with caption` component

> so that I can:
provide the component for the Learn page template

#### Additional information
- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs [[sketch](https://ibm.box.com/s/dtn9t9o1iy8h26rb66mr05gns98v42st)] [[abstract](https://share.goabstract.com/c28dcfa6-a5a9-421b-b019-4a3390ff5184??)]
- [Functional specs](https://ibm.box.com/s/fm5mikceok20or85zm98631i3qt1f203)
- Prototype for interactions [[codepen](https://codepen.io/photodow/full/dyoydBr)]
 - Design QA issue (#1247)
 - Prod QA issue (#1248)

> 🚨 copy, icon and lightbox media viewer are not in scope for this release

#### Acceptance criteria
 - [x] Image component is used
 - [x] caption included
 - [x] Follows functional specs and data model
 - [x] Update cotentItem with this component.
 - [x] The component development follows a modular component pattern
 - [x] The component should be accessible via ES6 import
 - [x] The component should be visible within the living documentation of the Dotcom components

**Comment by RobertaJHahn** [comment]
@jeffchew I don't know what AC's to add for this issue.  My template is for pattern development, which does not apply.  @photodow you may want to add some more information based on your functional spec work.  (A link to the functional spec's would be helpful.)  This issue will give you a place to include additional information.

**Comment by larahanlon2** [comment]
Latest design specs on Abstract: https://share.goabstract.com/c28dcfa6-a5a9-421b-b019-4a3390ff5184?
