### ISSUE TITLE
Component: Image - with caption Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1247]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `image - with caption`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Design Issue (#748 ) 
- Functional specs Issue (#1245 )
- [Functional specs](https://ibm.ent.box.com/file/612574896356)
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `image - with caption` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by larahanlon2** [comment]
Latest design specs on Abstract: https://share.goabstract.com/c28dcfa6-a5a9-421b-b019-4a3390ff5184?

**Comment by RobertaJHahn** [comment]
Design issues will be detected when testing the decorator patterns.  Closing this issue.
