### ISSUE TITLE
Abstract migration: Card

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1250]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Additional Information
 - Prod QA issue (#1253)

### Acceptance criteria
- [x] Create an Abstract file from the Sketch file
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [ ] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted file
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by jacobottesen-dgc** [comment]
@RobertaJHahn @Praveen-sr @chetankan
Card design specs are now available on Abstract: https://share.goabstract.com/a0cff2a8-f822-4f09-ba19-ba707e01ed38
