### ISSUE TITLE
Expressive theme – number input disappears when interacting with it in Storybook

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1251]
For some reason the Number input in our expressive theme storybook is disappearing when I try to interact with it, making it difficult to review from a design perspective.

![number-input-Jan-29-2020 17-09-03.gif](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/63098685-8ae8-487c-8ab5-254cf1eb4ad0)

**Comment by andysherman2121** [comment]
Spoke with Olivia and confirmed this is not an issue anymore. It was fixed when we updated the packages
