### ISSUE TITLE
Pattern: Card Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1252]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Dev Issue (#1249 )
 - Design and functional specs [sketch](https://ibm.ent.box.com/folder/95514001950) 

 #### Tasks
Ensure the `Card` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by annawen1** [comment]
@wonilsuhibm and @RobertaJHahn development for card is done

**Comment by wonilsuhibm** [comment]
@RobertaJHahn did we decide to not do this QA since this is a sub-pattern?

**Comment by RobertaJHahn** [comment]
@wonilsuhibm closing this issue as agreed.
