### ISSUE TITLE
Pattern: Card QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1253]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library ?pattern name?

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - Link to the abstract version of the designs
 - [Functional specs and design specs](https://ibm.ent.box.com/folder/95514001950)
 - Functional specs issue (#768)
 - Dev issue (#1249)
- Design QA testing issue (#1252)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [ ] Assign Wonil to the Design QA issue

**Comment by jacobottesen-dgc** [comment]
The Abstract work for card is finished. Link to collection in Abstract: https://share.goabstract.com/a0cff2a8-f822-4f09-ba19-ba707e01ed38

cc. @chetankan @Praveen-sr

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan You can begin the QA testing on this pattern.  The majority of the development is finished.  Bug (#1070) is still open.  You can monitor the progress of this work on the board as you test.  @annawen1 will send another message when she has completely finished the development.

**Comment by annawen1** [comment]
@Praveen-sr @chetankan development for card has been done

**Comment by chetankan** [comment]
@RobertaJHahn : Testing of functionality and design is done, accessibility testing is in progress.
