### ISSUE TITLE
Pattern: Create the Link list functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1257]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Link list` functional specs 

> so that I can:
so that I can properly code the `Link list` pattern

#### Additional information

 - Design Issue (#1255  )
 - [Design Specs](https://ibm.ent.box.com/folder/101876058407)

#### Acceptance criteria
 - [ ] Documented Link list functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by wonilsuhibm** [comment]
The design spec story has been updated with a link to the specs. I also added a new box folder here: https://ibm.box.com/s/dgnfrnpaqepbuyifa04aoc091v4cnz3d
