### ISSUE TITLE
Pattern: Link list Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1259]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Link list`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Dev link (#1258 )
 - Design Link (#1255 ) 
- Functional specs (#1257 )
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Link list` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by mkothur** [comment]
@wonilsuhibm @RobertaJHahn : #1258  dev work is completed and got merge and it is ready for QA testing.
