### ISSUE TITLE
CountryList file missing

### ISSUE THREAD

**Issue by sanjitbauli** [carbon-design-system/ibm-dotcom-library#1261]
## In our project we are supporting total 74 different country language combination and unique 16 languages, i saw in many instances the country list JSON files are missing.

> here's a few lists
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/frfr-utf8.json 
Also when i change my language to German - Germany it tries to load this file
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/been-utf8.json
No idea what is be-en

Selected locale: Canadian french but locale shows United state English

<img width="1664" alt="Screenshot 2020-01-30 at 3 33 52 PM" src="https://user-images.githubusercontent.com/272230/73439860-5507d500-4376-11ea-9b43-cbf074d4464b.png">

German
<img width="1679" alt="Screenshot 2020-01-30 at 3 32 12 PM" src="https://user-images.githubusercontent.com/272230/73439516-c004dc00-4375-11ea-9713-62d8e3ad6a85.png">

**Comment by ljcarot** [comment]
Are you on latest version of footer?  Did this start after our last release or was it happening before. Can you provide test url?

**Comment by jeffchew** [comment]
Hi @sanjitbauli , 

We still haven't gone through the motions of translating all of the country lists yet, so only us-en is available today. However, one of the bugs that we fixed in `v1.3.0` is to show the correct country/language in the footer button, but will still show in english and not the translated language. We are still determining when we can get all of the translated country lists in place with the translation team.

**Comment by sanjitbauli** [comment]
@ljcarot yes i was trying the latest version. I do not have any test url for that.
@jeffchew - what i was looking for is, if there is an option to remove footer locale selector then probably we can avoid issues related to the locale files for now.

**Comment by jeffchew** [comment]
@sanjitbauli I believe this was already addressed in a patch release, so the language switching should be working now. Note, we are still looking into IE11 support which is tracked in a different issue (https://github.com/carbon-design-system/ibm-dotcom-library/issues/1475)
