### ISSUE TITLE
Pattern-LeadSpace with image- On actual devices (Windows/Mac) background image is not rendering

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1262]
## Detailed description
issue - On windows and mac system 'LeadSpace with image' in background image is not rendering. But on browser stack 'leadspace with image' is getting rendered properly.  

Expected Result:- on all the actual devices (Windows/Mac) background image should be rendered properly.

## Steps to reproduce the issue

1. Open the browser on 'windows/mac' 
2. Enter the 'Leadspace' url in the browser .
3. Select 'Lead space with image'
4.Verify the Lead Space with image is rendering .
## Additional information

URL:- http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-leadspace-centered--centered-with-image

OS:- Windows 10, Mac
Browsers:- FF 72.0.1 , Chrome 79.0.3945![mac-safari leadspace with image.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/042dc47c-4dcc-4abc-9c76-9d6dfde517ad)![Leadspace centered with image in windows 10 ff72.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/f87d1ebf-ab3f-44cb-bbc0-3a52f1c79b8c), Safari, ![Leadspace with image in browserstack windows 10.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/e72682f8-2e88-4c6e-ab55-9cb9f0467ad9)

**Comment by RobertaJHahn** [comment]
Praveen and Chetan will test this issue outside of the IBM office.  There may be an issue with the IBM India firewall.  The images are stored in the cloud.

**Comment by chetankan** [comment]
@RobertaJHahn @jeoffw @Praveen-sr : Yesterday i checked on my home network patterns with images are rendering properly (ex: Lead space with image) , as you said it maybe due to firewall, images are not displaying in office network.

**Comment by Praveen-sr** [comment]
@jeffchew , @RobertaJHahn  As discussed on call,  images are rendering from "https://picsum.photos/id/1003/1056/480" due to security policy.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/57c21d1f-dab0-44dc-9eba-aeec7ae0f24e)

**Comment by RobertaJHahn** [comment]
Closing this issue as the fix is tracked under (#1316)
