### ISSUE TITLE
[ContentBlockSimple] Rename "SimpleLongForm" to "ContentBlockSimple" and update per functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1275]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have a `ContentBlockSimple` block pattern available

> so that I can:
utilize within my application

#### Additional information

 - Functional specifications: https://ibm.ent.box.com/file/595011203539
 - Video is out of scope for this story.
- Design QA testing issue (#1036)
- Prod QA testing issue (#1293)
 
#### Acceptance criteria
 - [x] Rename `SimpleLongForm` to `ContentBlockSimple`
 - [x] Remove feature flag
 - [x] Update propTypes and defaultProps per functional specifications (required vs not required)
 - [x] Minimum 80% unit test coverage
 - [x] Update Design QA / Production QA issues when code is merged and ready for testing
- [x] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [x] Assign Wonil to the Design QA issue
 - [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is

**Comment by larahanlon2** [comment]
FYI `Content block – simple` design specs are now updated and available on Abstract: https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca?
