### ISSUE TITLE
Pattern: Card Section - simple Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1276]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card section - simple`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Dev link (#1199 )
 - Design specs on [Box](https://ibm.box.com/s/6prfrgt7dftdg47ejy3q3m4x7h47kbmo) 
- Functional specs (#1132 )
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Card section - simple` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by mkothur** [comment]
@wonilsuhibm @RobertaJHahn : #1199  dev work is completed and got merge and it is ready for QA testing.

**Comment by JennySanchez** [comment]
Design QA completed and [bug issue](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1498) created for correction.
