### ISSUE TITLE
Pattern: Feature Card - Text (without space) is not wrapped on pattern and card heading.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1278]
## Detailed description
Device:- Windows 10 and Mac
Browser:- Firefox, Chrome, Safari

Issue: The text (without space) on pattern and card heading is going out of the card layout.
Expected :- Text must be wrapped and fit inside the card layout.

## Steps to reproduce the issue

1. Open the browser ( Firefox, chrome or Safari)
2. Open the Storybook URL on the browser
3. Select Feature Card section
4. On knobs, enter long text without space
5. Verify the heading on the card, text is not wrapped.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8ea99817-756d-4605-b3c8-c8a58c69fc63)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f465b221-b989-401f-b2c3-7104671cc4b6)

**Comment by RobertaJHahn** [comment]
This scenario will be captured by the content management system or also by adopters to define within their application.
