### ISSUE TITLE
Pattern: Feature Card - The link (Arrow) on the card is not aligned and with long text, link goes out of card layout.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1280]
## Detailed description
Device:- Windows 10, Mac and Mobile
Browser:- Firefox, Chrome, Safari

Issue :- 
1. The link (right arrow) on the card is not aligned as per design
2. When we enter long text on the card the link arrow alignment is going out of the card layout.

## Steps to reproduce the issue

1. Open the browser ( Firefox, chrome or Safari)
2. Open the Storybook URL on the browser
3. Select Feature Card section
4. On knobs, enter long text 
5. Verify the link on the card.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/2a0103ef-7adb-4335-8c04-26af89e4e80e)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/195966cf-9503-4180-a041-a6be54f4f08f)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3fe1aee9-a5c4-4a74-b91d-4c6aa4ce6b68)

**Comment by RobertaJHahn** [comment]
Item 1 is a dup to issue (#1071).  Item 2 will be enforced by the content management system or the application using this pattern.  Closing.
