### ISSUE TITLE
Pattern: Card Section - with images Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1286]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card section - with images`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Design Issue (#656)
 - Design specs:  Sketch [Box Link](https://ibm.box.com/s/u4acyo9oeqya8xidimxtidh8k8y08fza)
 - [Functional Specs](https://ibm.ent.box.com/file/599336614411)
- Functional specs Issue (#1131 )
 - Dev link (#1136 )
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `Card section - with images` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by mkothur** [comment]
@wonilsuhibm @RobertaJHahn : #1136 dev work is completed and got merge and it is ready for QA testing.
