### ISSUE TITLE
Pattern: Content block - mixed groups Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1289]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `content block - mixed groups`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Functional specs (#1129 )
- Dev refactoring issue (#1263)
- Testing scope includes only Chrome browser

 #### Tasks
Ensure the `content block - mixed groups` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by kennylam** [comment]
@wonilsuhibm @RobertaJHahn this is ready for testing
https://github.com/carbon-design-system/ibm-dotcom-library/pull/1444

**Comment by larahanlon2** [comment]
All design defects for this round have been opened. Closing this issue.
