### ISSUE TITLE
Pattern: Content block - with media Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1296]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content block - with media`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Dev issue link (#1238 )
 - Design specs [sketch](https://ibm.ent.box.com/folder/94760926421) 
- Functional specs Issue (#1207 )
- [Functional specs] (https://ibm.ent.box.com/file/607045243803)

 #### Tasks
Ensure the `Content block - with media` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [x] Pattern is reviewed by designer and design defects are identified
- [x] New issues are opened to log individual defects
- [x] Screenshots of as-is and to-be design should be added to the issue when needed
- [x] Developer associated with building the pattern is assigned to the new issues
- [x] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by larahanlon2** [comment]
FYI design specs are now available on Abstract: https://share.goabstract.com/b477f6a2-6229-49d9-b83d-c5e25e6da171?

**Comment by RobertaJHahn** [comment]
@wonilsuhibm This pattern is ready for design QA testing.

cc:  @kennylam

**Comment by larahanlon2** [comment]
Opened up a bunch of issues with found design defects between Mon 10–Fri 14. Moving this to done.
