### ISSUE TITLE
Pattern: Content block - with media QA testing - Production level version 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1297]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Content block - with media`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - Link to the abstract version of the designs
 - Dev issue link (#1238 )
 - Design specs via [Abstract](https://share.goabstract.com/b477f6a2-6229-49d9-b83d-c5e25e6da171?)
- Design QA issue (#1296) 
- Functional specs Issue (#1207 )
- [Functional specs] (https://ibm.ent.box.com/file/607045243803)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by larahanlon2** [comment]
@RobertaJHahn @Praveen-sr @chetankan 

FYI design specs are now available on Abstract: https://share.goabstract.com/b477f6a2-6229-49d9-b83d-c5e25e6da171?

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Development is finished.  This pattern is ready for Prod QA testing.

cc:  @kennylam

**Comment by Praveen-sr** [comment]
@RobertaJHahn  We have completed the testing (Functional, design and accessibility) for this pattern.
