### ISSUE TITLE
Pattern: Content group - with cards QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1299]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library ?pattern name?

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, IE, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - alpha Dev link (#704 )
- Design folder with func specs and visual specs is here: [Box](https://ibm.box.com/s/709822ny79gfn2s3b68noeg1gd14s6zk)
- Functional specs Issue (#1124 )
 - [functional specs](https://ibm.ent.box.com/file/571218496531)
 - Design QA testing is finished.  No notification needed for their testing.

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by wonilsuhibm** [comment]
@Praveen-sr @chetankan The design specs are available in the Box folder linked in the description.

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr @chetankan 
This pattern is ready to QA,
Thanks!

**Comment by RobertaJHahn** [comment]
Testing status 2/5/2020:

**Comment by Praveen-sr** [comment]
Testing status :- Functional and design testing is done. Accessibility is in progress.
