### ISSUE TITLE
Pattern: Feature Card-  Card background should be in high contrast

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1301]
## Detailed description
Issue- In actual devices feature card appears to be in grey.
As per design feature card background should be in high contrast.

## Additional information

Device:- Windows 10 and Mac, iOS, Android
Browser:- Firefox, Chrome, Safari

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/bf75b907-cdc5-4959-ab36-c201e5efc0b9)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/9f896739-7230-418c-9fc5-3c032874bb5c)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3f6145ac-bc2c-4382-aa49-7ff72df3b809)

**Comment by annawen1** [comment]
This seems to be covered in https://github.com/carbon-design-system/ibm-dotcom-library/issues/1070 already

**Comment by ljcarot** [comment]
Agree with Anna.  Closing this bug since already captured in #1070
