### ISSUE TITLE
Date picker not displaying disabled dates

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1303]
The `Date picker` / `range with calendar and min/max dates` variant is not displaying the disabled dates. 

In our [Expressive storybook](https://carbon-expressive.mybluemix.net/?path=/story/datepicker--range-with-calendar-and-min-max-dates) I cannot select any dates between 29–9; 21–8, the type should be `$disabled-02`, mirroring Carbon's example

| **Expressive theme** | **Carbon** |
|---|---|
|![Screen Shot 2020-02-04 at 10.05.11 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/59100c32-9957-451f-8e59-096ff1488e05) |![Screen Shot 2020-02-04 at 10.05.22 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/1c610aa2-4a62-47a4-bd90-798380316422)|

**Comment by andysherman2121** [comment]
Was fixed in updated carbon dependency
