### ISSUE TITLE
Update L1 based on design modifications

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1304]
At the end of Q4 2019, the L1 title chip card was updated by design: spacing, type size and interactive states were finalized and tested. 

#### Tasks

- [ ] Design to provide dev with latest L1 design specs
- [ ] Dev to implement design changes as per specs

**Comment by jeffchew** [comment]
@larahanlon2 @RobertaJHahn I'm wondering if we can attach this issue to epic https://github.com/carbon-design-system/ibm-dotcom-library/issues/2092? We don't have a dev issue for the L1 work yet for the October release as far as I can tell.

**Comment by RobertaJHahn** [comment]
Things have changed since February 2020.  Closing this issue as the work is managed under (#4007)
