### ISSUE TITLE
Update time picker icon

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1305]
The `Time picker` icon is too large and does not align with the icon sizes used within the other components.

the chevron needs to match the size of the chevron used in [dropdown](https://carbon-expressive.mybluemix.net/?path=/story/dropdown--default)
I know we have run into components not using the same icon file or class before, so maybe this is a PR we can send to Carbon 

![Screen Shot 2020-02-04 at 10.57.14 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/7b814ad1-cbdc-4725-b05c-b5cc3d428cce)
![Screen Shot 2020-02-04 at 10.57.00 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/6713f7fc-f783-4779-a303-ced098a7cc33)

Acceptance criteria
- [ ] icon matches dropdown size
- [ ] reviewed by design team

**Comment by annawen1** [comment]
PR has been submitted for this and merged into carbon

https://github.com/carbon-design-system/ibm-dotcom-library/issues/1085

we are waiting for them to do a release before we bump up the carbon dependency.

**Comment by oliviaflory** [comment]
Thank you Anna!
