### ISSUE TITLE
Inline Loading UX example page is giving an error message

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1309]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug in Expressive storybook
<img width="939" alt="Screen Shot 2020-02-04 at 4 43 01 PM" src="https://user-images.githubusercontent.com/45692622/73789789-6cc3cc80-476d-11ea-819b-c6763b4243d7.png">

> Is this issue related to a specific component?
Happening in the UX Example of the InlineLoading component

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expected to see the same UX example as the [Carbon components storybook](https://react.carbondesignsystem.com/?path=/story/inlineloading--ux-example)
![carbon-inlineloading-ux-Feb-04-2020 16-38-12](https://user-images.githubusercontent.com/45692622/73789693-400fb500-476d-11ea-974a-ab1af92d9c9c.gif)

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
[Expressive theme Storybook](https://carbon-expressive.mybluemix.net/?path=/story/inlineloading--ux-example)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Open Expressive theme story book
2. Navigate to InlineLoading / UX Example
[Link to site](https://carbon-expressive.mybluemix.net/?path=/story/inlineloading--ux-example)

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@guilhermelMoraes keep these in `Done` for now. @RobertaJHahn will need to close out on her end including updating the air table, etc.

**Comment by guilhermelMoraes** [comment]
> @guilhermelMoraes keep these in `Done` for now. @RobertaJHahn will need to close out on her end including updating the air table, etc.

ok, sorry. I'll put them back at the `Done` pipeline.
