### ISSUE TITLE
[LocaleModal] Update labels to be sourced by the translation service

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1311]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
source all locale modal labels from the translation service

> so that I can:
have the modal not be hardcoded with the english text

#### Additional information

 - Story to track updates to the translation JSON file: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1310

#### Acceptance criteria
 - [x] Locale Modal labels are sourced from the translation service
 - [x] remove props for the labels

**Comment by jeffchew** [comment]
@RobertaJHahn @ljcarot @kennylam setting this as 3 story points for now, and is blocked by https://github.com/carbon-design-system/ibm-dotcom-library/issues/1310. I didn't set a milestone for this yet, but hoping we could get to this in the coming sprints.

**Comment by kennylam** [comment]
English translation here:
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/usen-utf8.json
