### ISSUE TITLE
[Masthead] Create functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1313]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
have functional specifications available for the Masthead

> so that I can:
create test cases for the Masthead and begin testing the component in ernest

#### Additional information

 - We may want to break this down into multiple specifications
 - Current Masthead: https://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default
 - We may want to think about L1 in a separate story or series of stories entirely

#### Acceptance criteria
 - [ ] Functional specification documentation created and added to the IBM.com Library folder in Box
 - [ ] Walkthrough of the functional specifications with the QA team
 - [ ] Walkthrough of the functional specifications with DDS leadership

**Comment by RobertaJHahn** [comment]
Abstract migration of the designs are needed.

**Comment by RobertaJHahn** [comment]
An epic (#884) was created to manage this work.  This is duplicate.  Closing this issue.
