### ISSUE TITLE
[Footer] Create functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1314]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
have functional specifications available for the Footer

> so that I can:
create test cases for the Footer and begin testing the component in earnest

#### Additional information

 - Should only include for the footer, we should have separate specs for the locale modal
 - Current footer: https://ibmdotcom-react.mybluemix.net/?path=/story/components-footer--default
 - [Footer folder](https://ibm.box.com/s/ijcy36qx6nxt8ofaem41l9jla487szjo)
 - These functional specifications should include the most current legal updates/changes

#### Acceptance criteria
 - [x] Functional specification documentation created and added to the IBM.com Library folder in Box
 - [ ] Walkthrough of the functional specifications with the QA team
 - [x] Walkthrough of the functional specifications with DDS leadership

**Comment by RobertaJHahn** [comment]
Design Abstract migration issue is needed.

**Comment by jeffchew** [comment]
These are functional specifications created by Ellen Choi awhile ago, which might be a good reference point: https://ibm.ent.box.com/notes/536279030198

**Comment by mbarry325** [comment]
Functional specs completed. 
https://ibm.box.com/s/05lmg7mkxc052ac4gsgyl0wjy8hb10j8
