### ISSUE TITLE
Locale Modal - Create functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1315]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
have functional specifications available for the Locale Selector

> so that I can:
create test cases for the Locale Selector and begin testing the component in earnest

#### Additional information

 - Current locale selector: https://ibmdotcom-react.mybluemix.net/?path=/story/components-footer--default
- Should create separate specifications for the page load logic, isn't part of this scope
- This might be a good starting point, the documentation from Ellen Choi: https://ibm.ent.box.com/notes/541266602503

#### Acceptance criteria
 - [ ] Functional specification documentation created and added to the IBM.com Library folder in Box
 - [ ] Walkthrough of the functional specifications with the QA team
 - [ ] Walkthrough of the functional specifications with DDS leadership

**Comment by RobertaJHahn** [comment]
Design Abstract migration issue is needed.

**Comment by jeffchew** [comment]
Process flow diagram created awhile ago:
https://docs.google.com/drawings/d/1yvl6_zX82Juz1kaiO4jlnjQLFdE_RyCwc4luJezKMp0/edit?usp=sharing

And functional specifications created by Ellen Choi:
https://ibm.ent.box.com/notes/541266602503

**Comment by photodow** [comment]
Here are some more relevant resources I've tracked down.
- [Design specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
- [Mary's functional specs](https://ibm.box.com/s/2xs1hozvkkyv4uxtx4o6dwzqkgqmt2c5)

**Comment by photodow** [comment]
Met with Kenny and Lara, and Olivia and Jacob. To try and align my understanding of the local selector at the moment. Created the below sketch to try and help me visualize what I'm thinking at this point. After talking to Jeff (meeting on Monday to dive deeper) I realized the services might need to be documented and are not reflected in the sketch below.

<img src="https://user-images.githubusercontent.com/3793636/79614736-c5490b80-80c6-11ea-8b22-54f552e2a37a.png" width="300px" />

**Comment by photodow** [comment]
Based on discussions I've been having, I've stubbed out a few different functional specs as placeholders to fill out. Continuing to explore if any of these can be pushed out until next sprint and if they all can be accomplished with the remaining time.

- [ ] [Translation service](https://ibm.ent.box.com/file/655018269775)
- [ ] [Locale service](https://ibm.ent.box.com/file/655020350305)
- [ ] [Locale selector](https://ibm.box.com/s/95m3v7svh3q0hepcbkqd6sbonm31blzk) 🤔
   - [ ] Region selector
   - [ ] Language search
- [ ] Locale banner (out of scope for #1315)
- [x] [Locale footer](https://ibm.ent.box.com/file/639660622895) (done)

> - [ ] TODO: Create an issue to create locale banner functional specs

> 🤔I'm looking to combine Region selector, and Language search into Locale selector, but my concern is logic (in particular around Language search) might make the file huge. Keeping an eye on this situation and might break them out into separate functional specs.

**Comment by photodow** [comment]
Here is the locale modal. Moving to review with Lara, and Kenny at the least. Should be in a good spot for QA to pick up. I'll create a seperate issue for locale service (already in progress with this one) and translation service.

https://ibm.ent.box.com/file/655028173280

**Comment by RobertaJHahn** [comment]
@photodow created issue (#2247) to create the Locale Service and the Translation Service func spec issues as a reminder. Included the issue in sprint 20-10.
