### ISSUE TITLE
Cupcake website dev fix - Horizontal spacing between cards on Components/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#1324]
(Original task issue #246)

#### Components/[Overview page](https://ibm-dotcom-library.netlify.com/components)

- [x] The thin divider rule between cards is too light and it should be grey 20. See the Gatsby Resource Card example [here](https://gatsby-theme-carbon.now.sh/components/ResourceCard#example) for reference.

<img width="880" alt="Screen Shot 2019-12-12 at 6 22 02 PM" src="https://user-images.githubusercontent.com/32881239/70759545-528ce580-1d0c-11ea-9df1-0afbf5815e64.png">

**Comment by JennySanchez** [comment]
@jeffchew We might need to see if we have a dev volunteer to work on this. Thank you.

**Comment by jeffchew** [comment]
@JennySanchez we should move this to the website repo instead. I'll do that now.

cc: @RobertaJHahn

**Comment by jeffchew** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #463](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/463) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jeffchew** [comment]
Move to: https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/463
