### ISSUE TITLE
Cupcake website dev fix - Gernal spacing fix across the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#1325]
#### General spacing fix

- [ ] The vertical space below the H2s across the website is inconsistent.
![Screen Shot 2019-12-18 at 11 36 26 AM](https://user-images.githubusercontent.com/45213839/71109381-ad9a5e80-218a-11ea-99f4-0d16648c5374.png)

- [ ] The vertical space below below the list.

(Original task issue #246)

What we currently have on the website - too much vertical spacing. 
![Screen Shot 2019-12-19 at 3 06 07 PM](https://user-images.githubusercontent.com/45213839/71210598-dbf36900-2272-11ea-8a9d-253a82f73520.png)

It should only be a line break and looks like this.
![Screen Shot 2019-12-19 at 3 27 30 PM](https://user-images.githubusercontent.com/45213839/71211154-21fcfc80-2274-11ea-8fd1-8df65600f7f5.png)

**Comment by RobertaJHahn** [comment]
This work is no longer needed.  Closing this issue.
