### ISSUE TITLE
carbon-components 10.9.3 introduces breaking change to masthead

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1328]
## Detailed description

It was just brought to my attention by @dfrsol that we want to be careful before updating to Carbon's latest or anything past 10.9.3. It looks like they introduced a breaking change based on how we're modifying our masthead.

The removed the role selectors form masthead.

https://github.com/carbon-design-system/carbon/commit/d9935c3500ab3a04e7472376e34563d6c25076de#diff-f8c1a41d640bb6e6c4213525998e936e

We're still using these selectors on the masthead
```scss
a.#{$prefix}--header__menu-item[role='menuitem'] {
```
https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/styles/scss/components/masthead/_masthead-l1.scss#L145

**Comment by jeffchew** [comment]
@kennylam is this something we should worry about at the moment? The comment above shows for L1, which is still behind an experimental flag.

cc: @photodow @RobertaJHahn

**Comment by kennylam** [comment]
> @kennylam is this something we should worry about at the moment? The comment above shows for L1, which is still behind an experimental flag.

@jeffchew let me take a look at this, but I think it's basically the one @andysherman2121 fixed two sprints ago.

**Comment by kennylam** [comment]
@jeffchew @RobertaJHahn @photodow confirmed that this is not currently affecting us. We are still on `carbon-components@10.9.0`. But we will need to update our `Masthead` styles eventually, as updating to their latest package will completely break the masthead.

Suggest closing this and creating a new story to audit all components with `carbon-components` as a dependency and how they will be affected if/when we update to the latest package.

**Comment by RobertaJHahn** [comment]
Created an epic and issue to manage the work required for a carbon-components upgrade.  epic (#1876), issue (#1878).  Closing this issue.
