### ISSUE TITLE
[Masthead] Style overlap with the content

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1331]
## Detailed description

> Describe in detail the issue you're having.

The masthead menus overlaps with the content on the page

<img width="953" alt="Screen Shot 2020-02-06 at 12 36 53 PM" src="https://user-images.githubusercontent.com/1641214/73963062-97349780-48dd-11ea-806e-2b3253b3db84.png">

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Spoke with @kennylam , we should think about possibly having more specificity with the Carbon components we are using within our own. This possibly means adding their style mixins and wrapping with our component wrapper classes as a practice going forward.

> What browser are you working in?

Chrome

> What version of the IBM.com Library are you using?

`v1.3.0`

## Steps to reproduce the issue

1. http://ibmdotcom-nextjs-test.mybluemix.net/
2. See style overlap issues

**Comment by RobertaJHahn** [comment]
@kennylam Is this fixed?  Can't find the PR.
