### ISSUE TITLE
Content group – cards hover state incorrect

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1335]
## Detailed description

> Describe in detail the issue you're having.
The heading text and icon within the card should not change colors on hover

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug 🐛 

> Is this issue related to a specific component?
Block Pattern -->  ContentGroupCards

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Text and icon should not change colors on hover
<img width="904" alt="Screen Shot 2020-02-06 at 3 08 50 PM" src="https://user-images.githubusercontent.com/45692622/73974599-a4a84c80-48f2-11ea-9f60-62b6d908074e.png">

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Web simplification

## Steps to reproduce the issue

1. Using Chrome
2. Go to [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default)
3. hover one of the cards

## Additional information

- Screenshots or code
- Notes

**Comment by RaphaelAmadeu** [comment]
I think this is being fixed at @annawen1 pull request, so it should be fixed once the changes are merged in.

**Comment by annawen1** [comment]
PR has been merged. Changes can be seen in the release branch here: https://ibmdotcom-react-staging.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default
