### ISSUE TITLE
Content group cards – text should span 90% width

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1342]
## Detailed description

> Describe in detail the issue you're having.
The spec states that the text within the cards should only span 90% of the card container width, currently it spans 100% width.
**Spec**
![Screen Shot 2020-02-07 at 11.25.37 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/68f71d08-d135-4775-84a6-934c998696aa)
**Current**
![Screen Shot 2020-02-07 at 11.06.02 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/066ecee0-806b-4c56-8358-586f9c2812a9)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?
ContentGroupCards pattern

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Update cards so text spans 90% container width instead of 100%

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
[ContentGroupCards](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Web simplification

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Hi Raph, this bug is a low severity, but apparently it is an easy fix.  Can you fix this while you are working on the pattern in this sprint?

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn Hi Roberta, sure thing, I can fix this in this sprint.
