### ISSUE TITLE
Issues deploying vanilla package in non-node environments

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1348]
## Detailed description

> Describe in detail the issue you're having.

``` I was experimenting with the Angular version, https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/vanilla/src/components/footer and noticed there was a dependency to have geolocation for the footer```

![Screen Shot 2020-02-07 at 10 42 52 AM](https://user-images.githubusercontent.com/1641214/74059796-acc9c000-49b6-11ea-8b5b-b82eabe23bb0.png)

> Is this issue related to a specific component?

Vanilla Footer

## Additional information

- Need to add a null check for `process` to get around this

**Comment by ljcarot** [comment]
Is this issue closed? @jeffchew  Can Epic for 1.3.1 be closed now too?

**Comment by jeffchew** [comment]
@ljcarot This issue is closed, but we haven't pushed out v1.3.1 yet as we were waiting for final feedback from adopters. We'll try to push out today.

cc: @kennylam @RobertaJHahn
