### ISSUE TITLE
Component: Embedded Video Player Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1349]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Embedded Video Player`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - alpha Dev link (#1108 )
 - January 8 & 13 Design meeting notes and recording [Box Link](https://ibm.ent.box.com/notes/443167473382) 
- Functional specs (#1066 )[NEED UPDATE BY DEVS]
 - [Media component designs](https://ibm.box.com/s/8pw7424kgiuoksf8uz1nvddvwtkm2lbk)
- [Storybook React Video player](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)

 #### Tasks
- Ensure the `Embedded Video Player` component has been tested and reviewed by design + dev.
- Visual QA is to be done only in Chrome.
- [QA guidelines](https://ibm.ent.box.com/notes/551613086170?s=jn94fkoogs22gi4saoqeqcoq614d61na)

#### Acceptance criteria
- [x] Pattern is reviewed by designer and design defects are identified
- [x] New issues are opened to log individual defects
- [x] Screenshots of as-is and to-be design should be added to the issue when needed
- [x] Developer associated with building the pattern is assigned to the new issues
- [x] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by sethibm** [comment]
@jeffchew @photodow I left a comment in #1066 but it's closed, and I can't find a task here for devs to update Image, Video, Media, and Media Switcher functional specs?  

It would be good to update the link to the correct and latest functional spec in this story.   At the moment, I placed previous functional specs here in this folder:

https://ibm.box.com/s/gpzvplwa5gyj1vvg1adl5apqmcnfa686
