### ISSUE TITLE
Clean up unused classes in Masthead

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-dotcom-library#135]
Does anyone know what `${prefix}--container-highlight-class` is doing? I didn't see a reference for it in the `SCSS`.

_Originally posted by @photodow in https://github.com/carbon-design-system/ibm-dotcom-library/pull/132_

**Comment by kennylam** [comment]
TODO: The auto-suggestion drop down in the search component has HTML/CSS that can be removed.

**Comment by jeffchew** [comment]
This looks like a clean up task that almost got pulled away from stalebot. Moving this for triaging.
