### ISSUE TITLE
Cookie consent notice: design part 1

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1359]
### User story
As a designer to work on the new design of the cookie notice, I need to understand what I am designing in order to achieve the goal successfully.

### Notes
- This story is to do the visual design based on the research findings.
- Once the design is completed, it will have to be shared and approved by stakeholders, which will be captured in a separate story.

### Acceptance criteria
- [ ] Design has been completed for all break points
- [ ] Design has been reviewed by IDL/Carbon
- [ ] Design has been accepted by DDS team and DGC design leadership

**Comment by wonilsuhibm** [comment]
A quick update on an old design exploration available in the [Box folder](https://ibm.box.com/s/sp8pcnyrpfuiat78xo0m7j0gzcrjk5ty)

![model-1-01 copy 3](https://user-images.githubusercontent.com/30183447/74613514-19db0500-50dd-11ea-836b-6548462461b4.png)

![model-1-01 copy 11](https://user-images.githubusercontent.com/30183447/74613518-1e9fb900-50dd-11ea-9c62-c2e89657cc02.png)

**Comment by ljcarot** [comment]
Much improved design.  Let's show Juan and team.

**Comment by wonilsuhibm** [comment]
@larahanlon2 @oliviaflory @jacobottesen-dgc @JennySanchez please comment if you ever get a chance.

**Comment by JennySanchez** [comment]
@wonilsuhibm I can not see what's in the folder. Can you add me to the folder? Thanks.
![Screen Shot 2020-02-28 at 1.39.37 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/2ddd08af-5068-48f2-b3e9-42211a5bb2e0)
