### ISSUE TITLE
IBM.com style models: project set up

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1362]
### User story
As a designer working on the IBM.com style models project, I need a way to save, track, and update my work in coordination with other designers on the project.

### Notes
This story is to set up project frameworks such as a shared git board, Box folder, mission statement, etc.

### Acceptance criteria
- [x] A board has been created
- [x] Stories for the immediate-future sprints have been created
- [x] Box folder has been created

**Comment by wonilsuhibm** [comment]
A git board has been created [here](https://github.ibm.com/Wonil-Suh1/ibm-dot-com-style-models). We created an internal board because we consider this work a potential IP.

**Comment by larahanlon2** [comment]
Moving this to **done** as all tasks per story have been addressed. @wonilsuhibm
