### ISSUE TITLE
Pattern: Table of contents - On Edge browser, the left menu scrolls up with the page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1380]
## Detailed description
Device - Windows 10
Browser - Edge

Issue :- On Edge browser, when the users scrolls up the table of contents the left menu also scroll up with the page.
Expected - Left menu must stick when the users scrolls up the page.

## Steps to reproduce the issue

1. Open the browser ( Edge)
2. Open the Storybook URL on the browser
3. Select Table of contents pattern
4. Scroll the page and verify the left menu

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/24a68143-f109-46d1-820d-492d9b1f9b17)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/34a87bd0-673e-4112-ae59-191d90dd12c2)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr Could you please confirm which version of Edge are you testing on? as I've tested on it's latest version and it's working finely

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu We reported this issue while testing on [URL ](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-image) i.e (experimental) on Edge version 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5c086d53-1175-4e4d-b0e5-b7f2a3d40a77)

I rechecked the same on "Staging" with the same Edge version and its working fine. Thanks!
