### ISSUE TITLE
Pattern-Table of Content- In iPhone with iOS 12 'Jump to' functionality is not working

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1381]
## Detailed description
Issue:- In 'Table of Content' pattern 'jump to' functionality is not working on iPhone's which are running on iOS 12 version.On selection options from 'jump to' nothing happens.

## Steps to reproduce the issue

1. Enter the pattern url in the mobile browser
2. Click on 'Jump to' option
3. Select an 3rd or 4th option from the list.

## Additional information

Pattern url :- http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--manually-define-menu-items

Devices :- iPhone xs, xs Max, XR, 8
OS:- iOS 12![Jumnp to section on mobile device.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/a3ab8bab-2e62-4f17-9c3b-0bf46a3d414a)

**Comment by RaphaelAmadeu** [comment]
@chetankan ,
Could you please test this again using this link,
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1423/index.html,
Thank you!

**Comment by chetankan** [comment]
@RaphaelAmadeu :- I checked the link which you have provided on iOS 12 'Jump to' functionality is working fine.
