### ISSUE TITLE
Pattern: Content Group Card - Accessibility - beginning and ending boundary for each card is not conveyed for the screen reader user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1383]
## Detailed description

Device - JAWS FF, VO iPhone Safari

Issue:- The beginning and ending boundary for each card is not conveyed for the screen reader user.
Suggestion:- Provide each card within the landmark region and give appropriate label. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3fe0f7b4-f238-4916-a339-c25b8be641a9)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr I've updated the outline, could you please confirm if it is okay now? thanks!

**Comment by Praveen-sr** [comment]
We tested this on staging (https://ibmdotcom-react-experimental.mybluemix.net/) but issue still persists. Please let us know if its deployed on staging. Thanks

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr , could you please try again? I've just seem the link you used and the outline is bigger than before.

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr , could you please test it with this link from (PR Build)[https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1414/index.html?path=/story/patterns-blocks-contentgroupcards--default].

Thank you!

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Could you provide an estimate for your work.  Thanks.

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Tested this on  PR build (https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1414/index.html?path=/story/patterns-blocks-contentgroupcards--default) its fine now.
