### ISSUE TITLE
Unable to build footer, missing "vars" file

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#1384]
![image](https://user-images.githubusercontent.com/15310250/74322086-ae630180-4d83-11ea-9591-fa9aab40874f.png)

**Comment by kyjak** [comment]
In the screenshot there is also the corresponding carbon directory open.

**Comment by kyjak** [comment]
Live url of the test build is http://ibmdocstest.mybluemix.net/

**Comment by RobertaJHahn** [comment]
@jeffchew can you investigate when you return from vacation.  Thanks

**Comment by jeffchew** [comment]
Hi @kyjak , apologies for the late response on this. I checked your test instance and looks like the footer is rendering. Is this still an issue?

cc: @annawen1

**Comment by kyjak** [comment]
The footer itself looks ok, but try to change the language...
the language modal is very broken.

**Comment by ljcarot** [comment]
It's work as designed on this test page http://ibmdotcom-nextjs-test.mybluemix.net/.

**Comment by kyjak** [comment]
I used your example usage code from dotcom dev site, I dont see anything wrong in the code we have, we render just masthead and footer and still broken. so no idea how to root cause this.

**Comment by RaphaelAmadeu** [comment]
@kyjak ,
Could you please try changing the SCSS import to:
`import "@carbon/ibmdotcom-styles";`
here's an example implementation using this style importing
https://codesandbox.io/s/stupefied-wright-pesol

Let us know if this solves your problem

**Comment by jeffchew** [comment]
Hi @kyjak , let us know when you get a chance to take a look at this. Let us know if a working session would also help.

cc: @RaphaelAmadeu

**Comment by kyjak** [comment]
Sorry, was on vacation for 2 weeks, going to try the fix.

**Comment by kyjak** [comment]
I had that style included used as stated above, did not work.
Anyway, for the sake I tried again with updated libraries. 
Now, I cannot fetch resources again, though proxy running.
Sorry, I'm not wasting another minute with this library, in the time spent on this we would have
implemented the footer on our own without errors and with the necessary corporate look, which we will do in the next sprints.

**Comment by kyjak** [comment]
Resolved by the 1.5.0 release.
