### ISSUE TITLE
Language selector in the footer generates javascript errors and renders faulty

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#1385]
![image](https://user-images.githubusercontent.com/15310250/74322557-655f7d00-4d84-11ea-92c7-2bc2b7022906.png)

**Comment by kyjak** [comment]
Screen source code follows
![image](https://user-images.githubusercontent.com/15310250/74322622-7f995b00-4d84-11ea-9fc2-52cdd5400d1a.png)

**Comment by kyjak** [comment]
Live url of the test build is http://ibmdocstest.mybluemix.net/

**Comment by ljcarot** [comment]
@kennylam When you have a minute, can you pls check if Miro is doing anything noticeably wrong?  thx

**Comment by kyjak** [comment]
I can post snipplets, but please tell me what interests you.

**Comment by jeffchew** [comment]
Hi @kyjak , 

We have fixed an issue where the locale modal styles were not getting included in the main styles import, which should be fixed in `v1.4.0`. Can you update to that version and see if you're still running into that problem?

cc: @annawen1

**Comment by jeffchew** [comment]
Hi @kyjak , checking to see if updating to the latest IBM.com Library has fixed this issue at all? We are currently on `v1.5.0`.

cc: @RaphaelAmadeu

**Comment by kyjak** [comment]
Yes, i'm at 1.5.0, I cannot confirm, CORS issue again, even with local proxy running. Sorry, we will probably abandon this library and develop the footer ourselves. MUCH faster than to solve issues with dotcom.

**Comment by ljcarot** [comment]
@kyjak Since dotcom Library is the new standard for masthead and footer, we'd like to understand and resolve the issues.  It can help other adopters who have something similar in the way you have developed.  I'll arrange a call for this morning with Engineers from dotcom.   Once an adopter creates their own code, then it breaks the ability to be aligned site wide.  It's not just about the look and feel.  Thanks for understanding.

**Comment by kyjak** [comment]
You need to adopt a lot, it did not happen during the development. For example language selector, we do not do countries, just languages.

**Comment by ljcarot** [comment]
You can turn off Locale Selector if it is not a feature that you need.   See here on URX, they use the default footer without locale selector because they have country selector on the form itself.   https://www.ibm.com/account/reg/us-en/signup?formid=urx-19776

**Comment by kyjak** [comment]
We need a language selector in the footer based on language and not country.

**Comment by ljcarot** [comment]
ah, okay, so you just need a custom combobox dropdown.  you don't need traditional locale selector.   @wonilsuhibm How should a language selector via dropdown be added to default footer?  Should it be a custom component in the footer or be an option for other adopters too?

**Comment by kyjak** [comment]
Closing as resolved with the latest release.

**Comment by kyjak** [comment]
There is a way to hide the country selector, maybe to provide a way to inject another component in that place is enough. As per the meeting, issue on hold, until decision made, if this is a main dotcom feature or to be developed and injected by consumers.
