### ISSUE TITLE
Early adopter starter kit development

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1390]
### User story
As an early adopter, I need some self-service guidelines on how to design my new pages.

### Notes
- This is to update this [adopter starter kit folder](https://ibm.box.com/s/ji9d47sf6r2e4z3vdhjuq2uk4ko02i65) with more information.
- We may have to convert this to an epic and add task stories.

**Comment by JennySanchez** [comment]
@wonilsuhibm This is the issue for the Adopter Starter Kit creation. As discussed, this will be worked on the post-April website release.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/digital-design-ideation #56](https://github.com/carbon-design-system/digital-design-ideation/issues/56) via [**ZenHub**](https://www.zenhub.com/)
