### ISSUE TITLE
Add external CTA guidance to lead space pattern page

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1392]
Currently, some teams are adding links to lead space CTA's that direct users off ibm.com to external sites. We don't believe this is the right strategy so we need to add guidance to the lead space content.

This was discussed during a Globalization and Drupal QA call.

**Comment by JennySanchez** [comment]
@larahanlon2 Is this something we can add to the CTA Guideline? It's WIP but you can see the detail via #341 and let me know.
