### ISSUE TITLE
Pattern: Table of contents - Accessibility(Keyboard) - Jump to (Hamburger) menu is not operable with enter key , its working fine with space bar 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1394]
## Detailed description
Device : Windows 10
Browser : Firefox

Issue:- Jump to (Hamburger) menu in zoom of 200% is not operable with enter key , its working fine with space bar

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8999be15-655e-48b2-856a-da7f1a414b37)

**Comment by kennylam** [comment]
This is the default browser behaviour for `<select /> elements, and how Carbon has developed this component. Spacebar to open, then spacebar/enter to select. Since the mobile TOC is a `<select />`, this is working as intended and not a bug.
