### ISSUE TITLE
Pattern: Table of contents - Accessibility - Focus doesn't switch to the section heading on click of table of content (anchor) links

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1395]
## Detailed description
Device / browser :- JAWS Firefox

Issue :- Upon clicking of each link on left navigation, the Screen reader focus is not set on the beginning of the relevant content. Focus remains on the triggered link itself. This would confuse the Screen reader user.
Expected :- Upon clicking of each link, set the screen reader focus on the relevant heading.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b58916fc-5836-4376-9d97-80c92076c15e)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr ,
Could you please test using this link https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1413/index.html?path=/story/patterns-sub-patterns-table-of-contents--manually-define-menu-items ? Thanks!

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu @RobertaJHahn Verified this on link you provided, its working now. (focus goes to the target section)

**Comment by RaphaelAmadeu** [comment]
@photodow Maybe should bring the discussion about the behaviour of these anchor buttons, as focussing the target section would not be a common behaviour in cases like this.

**Comment by jeffchew** [comment]
I like the simplicity of aria tagging as a navigation element (e.g. aria landmarks), I think whatever we decide on we should document in the functional specs.

**Comment by photodow** [comment]
Agreed, that's why I'm pushing for us to try and figure out how this should work.

**Comment by RobertaJHahn** [comment]
@photodow I have added you to this issue to keep track the decision needed to close this issue.  I have also moved it to sprint 20-05 since it was not resolved in the previous sprint.

**Comment by RobertaJHahn** [comment]
After talking to Ram:  We need to provide focus when the user clicks on a link.  The user needs to traverse the rest of the page to return.  A functional spec story is needed.  

Raph will store the logic that he had developed and approved by Ram.
