### ISSUE TITLE
IBM.com style model adopter research

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1397]
To make sure we're moving in the right direction with IBM.com Style Models, we need to conduct adopter research to understand their needs.

**Comment by larahanlon2** [comment]
Research and strategy items conducted:

- [ ] Explored objectives and intended outcomes
- [ ] Identified tasks
- [ ] Set up GitHub board
- [ ] Conducted needs statements with DDS designers
- [ ] Conducted needs statements with sponsor users (Shixie, Shenxun, Lila, Tam)

Mural can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1580768401431?sender=larahanlon9022&key=c3f04952-0e26-4a37-97ab-55930dc5aa29).
