### ISSUE TITLE
Pattern: content block – with media, too much vertical spacing

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1402]
## Detailed description

**Describe in detail the issue you're having.**
There is too much space between the top description and child (content group – simple).

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design layout defect

**What did you expect to happen? What happened instead? What would you like to see changed?**
The vertical space between description and child should be 64px.

**What browser are you working in?**
Chrome

## Steps to reproduce the issue

Go to [Storybook pattern](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default) and view.

## Additional information

This is what's happening in browser right now. There is additional space at the bottom of the first description + 96px above the following child. The total vertical space should be 64px. 

<img width="1464" alt="Screen Shot 2020-02-13 at 12 11 21 PM" src="https://user-images.githubusercontent.com/53093550/74460892-a8d8ea80-4e5b-11ea-989f-cf6c6936c59f.png">

**Comment by ljcarot** [comment]
@larahanlon2 Can you confirm this is bug with @kennylam ?  On QA call this morning, this was raised by QA team but Kenny said it may have to do with the breakpoint.  I trust it may be a bug but just want to make sure it's not a repeat of the item discussed with Kenny on the QA call.  Thx

**Comment by larahanlon2** [comment]
Yes, no problem.

@kennylam Hey, any thoughts on this? The excessive space is showing across different breakpoints for me:

**Desktop**
<img width="1464" alt="Screen Shot 2020-02-13 at 12 11 21 PM" src="https://user-images.githubusercontent.com/53093550/74468327-a92bb280-4e68-11ea-9017-f64c27a5e915.png">

**ipad**
<img width="1353" alt="Screen Shot 2020-02-13 at 1 56 05 PM" src="https://user-images.githubusercontent.com/53093550/74468354-b648a180-4e68-11ea-82e9-febda73370b9.png">

**Mobile**
<img width="397" alt="Screen Shot 2020-02-13 at 1 53 36 PM" src="https://user-images.githubusercontent.com/53093550/74468374-be084600-4e68-11ea-89e7-612fc7ddcce2.png">
