### ISSUE TITLE
Table of Contents: No sticky menu behavior in Edge browser 

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#1403]
## Table of Contents: No sticky menu on scroll in Edge browser 
-->

## Detailed description

> The issue is the table of contents side menu is not sticky when viewed in Windows Edge browser. As you scroll the side menu scrolls with the other content.

Not scrolled:
<img width="831" alt="Screen Shot 2020-02-13 at 11 19 02 AM" src="https://user-images.githubusercontent.com/56400049/74460596-bb9af180-4e52-11ea-8a59-e75e8e7edc67.png">

Scrolled:
<img width="804" alt="Screen Shot 2020-02-13 at 11 19 15 AM" src="https://user-images.githubusercontent.com/56400049/74460555-ad4cd580-4e52-11ea-838e-f97fa605ca3d.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Table of Contents

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The side menu should start with 64px on top then on scroll it will move up 32px then stay sticky. 

<img width="1145" alt="Screen Shot 2020-02-13 at 11 20 30 AM" src="https://user-images.githubusercontent.com/56400049/74460673-da998380-4e52-11ea-9f4a-0a67dba2b668.png">

Instead of staying sticky, the side menu is scrolling with the content on the right.

Please make sure the side menu is sticky. 

> What browser are you working in?
Edge Browser

## Steps to reproduce the issue

1. Open [table of contents](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--dynamic-items) in Windows Edge Browser 
2. Scroll to view scroll behavior

**Comment by ljcarot** [comment]
@jacobottesen-dgc This is duplicate, already reported here https://github.com/carbon-design-system/ibm-dotcom-library/issues/1380.  I'm going to close this.  Perhaps before opening a bug issue, search by Table of Contents in Zenhub to make sure a bug has not already been reported by QA  or others.  Thx!
