### ISSUE TITLE
Icons in cards should be blue

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1404]
## Detailed description

> Describe in detail the issue you're having.
The icons in the cards should be blue, and use the token `$link-01` 
**Current**
![Screen Shot 2020-02-13 at 10.55.17 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/86a45d3e-097a-4700-b7e1-8c04b42df22b)
**What we want**
![Screen Shot 2020-02-13 at 1.01.15 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/6b9825c6-aa3e-47c0-952f-6d28b31d6e45)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug

> Is this issue related to a specific component?
[ContentGroupCards](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default)

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The icons should be blue, not black or gray 100. Confirmed this with Wonil, the specs had a version with blue and black.
The color of the icon will **not** change on any interactive states.

> What browser are you working in?
Chrome 

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Web simplification

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by photodow** [comment]
Should specify here that the local selector I believe is the only caveat to this, correct?

**Comment by oliviaflory** [comment]
@photodow that is a great question! I was QAing this as if it only related to the ContentGroupCards pattern within the Learn page specs. 

Are these all using [Card](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-card--static) as the base, and then that would mean the pattern isn't pulling in the Card correctly, because the icon is blue in the liked example? 
And is Locale Selector using Card as well?

**Comment by photodow** [comment]
Right, from what I can see across the board all use blue except for local selector. They all will use the Card. So if we change it default to blue (which I think is accurate) then we just need to remember within the locale selector to override that.

**Comment by ljcarot** [comment]
@RobertaJHahn in slack team decided this is Sev 4 so I changed the label here accordingly.  Do we want to move it out?

**Comment by photodow** [comment]
@oliviaflory @RobertaJHahn I actually think @annawen1 already tackled this issue in #1387. We might need a different ticket to change back the local selector though. :wink:

**Comment by RobertaJHahn** [comment]
@oliviaflory @photodow @annawen1 @ljcarot @RaphaelAmadeu Based on the conversations above, I have created an issue to override the Locale Selector icon color default.  (#1408)  Closing this issue.
