### ISSUE TITLE
Pattern: content block – with media, missing dividing rule

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1410]
## Detailed description

**Describe in detail the issue you're having.**
There should be a 1px solid rule at the bottom of the block pattern, after the `feature card`.

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Missing design item

**What browser are you working in?**
Chrome, Firefox

## Steps to reproduce the issue

Open [Storybook pattern](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default) and scroll to the bottom

## Additional information

In browser right now, there is no rule:
<img width="1473" alt="Screen Shot 2020-02-14 at 10 00 33 AM" src="https://user-images.githubusercontent.com/53093550/74542514-c1a3d780-4f11-11ea-9673-2527d9abe16d.png">

Actual design specs:
<img width="646" alt="Screen Shot 2020-02-14 at 10 08 00 AM" src="https://user-images.githubusercontent.com/53093550/74542616-f0ba4900-4f11-11ea-8b89-80f65ebe9b5f.png">

**Comment by RobertaJHahn** [comment]
@larahanlon2 We discussed this topic with Kenny earlier in the week.  He said that this rule is not included in the functional specs so dev has not included it.  Could you confirm with @photodow that this is correct.  If it is could you contact Lila to have the design updated?

**Comment by photodow** [comment]
@RobertaJHahn there is no functionality to the divider thus it wouldn't be in the functional specs. Unless the adopter will toggle it on and off which I don't believe is in this case.

I was actually just talking to @larahanlon2 about this a couple minutes ago. I don't see this as bug. Something that needs to get done, but I'm looking at it more at the section level. So it would need to be applied to things like `Layout`, or `TableOfContents`. Let me see if I can setup some time with Lara to further investigate this, and make sure we're aligned..

**Comment by kennylam** [comment]
@RobertaJHahn @larahanlon2 @photodow This will be resolved in #1581
