### ISSUE TITLE
Component: Lightbox Design QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1419]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Lightbox`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - alpha Dev link (# )
 - [Design and functional specs](https://ibm.ent.box.com/folder/84558325642 ) 
- Gap analysis issue (#362 )

 #### Tasks
Ensure the `Lightbox` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ljcarot** [comment]
@wonilsuhibm Can we assign this to a designer for this sprint? cc @RobertaJHahn

**Comment by RobertaJHahn** [comment]
@ljcarot There are currently 79 design stories included in sprint 20-07 with a velocity of velocity of 47.  I have moved the story into sprint 20-07.  

cc:  @wonilsuhibm

**Comment by wonilsuhibm** [comment]
The design QAs are exploding. I'll assign myself to this.

**Comment by wonilsuhibm** [comment]
Added bugs:
#1927 
#1928 
#1929 
#1930 

Will continue.
