### ISSUE TITLE
Pattern: Content Group Simple - On Mobile, card section is not stretched to the edge of the screen, as per design.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1424]
## Detailed description

Device - iPhone 11 pro , Samsung S10
Browser - Safari, chrome

Issue:- The card section is not stretched to the edge of the screen as per the design on mobile devices.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c6963c24-150f-4aa0-842f-a6fa914b9798)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr can you please confirm the pattern name please?

**Comment by ljcarot** [comment]
@RaphaelAmadeu In the title it says, Content Group - Simple.  Are you questioning whether that is correct pattern?
