### ISSUE TITLE
Pattern: Content block Media - Accessibility - Screen reader - beginning and ending boundary for each card is not conveyed.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1426]
## Detailed description

Device - JAWS FF, VO iPhone Safari

Issue:- The beginning and ending boundary for each card is not conveyed for the screen reader user.
Suggestion:- Provide each card within the landmark region and give appropriate label.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/54fe0479-89e5-4206-b78b-f923f4834f60)

**Comment by RobertaJHahn** [comment]
@kennylam FYI, we have lowered the severity on this issue and moved to the next release.
