### ISSUE TITLE
Pattern: LightBoxMediaViewer - In landscape mode text is not visible 

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1436]
Devices:- iPhone, Samsung Galaxy, Google Pixel
OS:- iOS, Android 
Browsers:- Safari, Chrome, UC, Firefox

Issue :- On mobile devices in landscape mode 'Copy' (Text) is not visible to user, whereas in portrait mode copy text is visible.

## Steps to reproduce the issue

1. Open the browser on mobile device
2. Enter the url and click on 'Go' button
3. Once pattern is loaded turn mobile device to landscape mode.

## Additional information
URL:- http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--default![Lightboxmediaviewer in landscape mode.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/725eec7f-1304-4097-86d2-092175435443)

**Comment by RobertaJHahn** [comment]
This is a known issue with Landscape mode.  A design solution is needed.

**Comment by wonilsuhibm** [comment]
There isn't much we can do to make it usable on a small screen. One potential solution to this problem is simply displaying a message to tell the user to use in the portrait mode.

**Comment by RobertaJHahn** [comment]
Wonil will open a new design issue to design the message solution and reference this issue.

**Comment by RobertaJHahn** [comment]
New issue created.  Issue (#1706)  Closing this issue.
