### ISSUE TITLE
Update cupcake site to newest Gatsby Theme

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#1445]
> As a IBM.com Library website creator, 

> I need to have the most up to date Gatsby theme on the cupcake site,

> so that the correct update will come through and fix the anchor link issues we are currently having.

#### Additional information

Task:
Update cupcake site to newest Gatsby Theme

**Comment by JennySanchez** [comment]
@kennylam Is Sprint 20-04 still good for this task to be done?
