### ISSUE TITLE
Link with icon using incorrect type size

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1455]
#### Describe in detail the issue you're having.
The Link with icon component is using the wrong type size, and it throwing off the hierarchy in every place it is used in web simplification. 
Additionally the icon is the correct size for the _intended_ type size, but is too big for the current type size and going against the system.

**Current**
![Screen Shot 2020-02-24 at 12.03.17 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/4a01d5ad-f051-49ca-8e1d-b1c229e6caec)

**Intended**
![Screen Shot 2020-02-24 at 12.02.56 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/9783c568-4bea-47dc-b7b2-3a083b9714c8)

#### Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

#### Is this issue related to a specific component?
[CTA component](https://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--default)

#### What did you expect to happen? What happened instead? What would you like to see changed?
The specs show the body type should be $body-short-02 (16px) but the component is displaying at 14px, I'm guessing it's using $body-short-01

#### What browser are you working in?
Chrome

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

Here are the original specs

![Primary_Link_Text-and-icon.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/513e10e9-2fa9-4719-afc9-07e9f9f33fd4)

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
Review mtg decision:  The component will be hard coded to the Expressive Theme.  It will not be part of the March release.
