### ISSUE TITLE
Masthead L1 should shrink to 48px height when fixed to top on scroll

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#146]
When the L1 becomes sticky on scroll (and the L0 disappears), the L1 should shrink to 48px height. Like so:

<img width="1413" alt="Screen Shot 2019-10-02 at 3 56 28 PM" src="https://user-images.githubusercontent.com/53093550/66077088-395a0280-e52d-11e9-927f-b170e5b6320e.png">

When the `eyebrow` is active then leave the L1 at 80px, fixed to the top, just like it is right now.

**Comment by emerson-pereira** [comment]
Draft PR open and in discussion: #674
