### ISSUE TITLE
Component:  Create Masthead L0 (React) - Production level

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1464]
This epic will link all of the work required to create the Production level version of the L0 React Masthead.  

Masthead L0 func specs v1.1 uploaded to box: https://ibm.box.com/s/mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1

Refer to change log section for details of updates.

These specs were updated to align mostly with current state behavior as observed in storybook: http://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default. Any references to TBD or future updates to the component in the previous version (v1.0) were removed.

**Comment by ellenchoi1** [comment]
Masthead L0 func specs v1.1 uploaded to box: https://ibm.box.com/s/mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1

Refer to change log section for details of updates.

These specs were updated to align mostly with current state behavior as observed in storybook: http://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default. Any references to TBD or future updates to the component in the previous version (v1.0) were removed.
