### ISSUE TITLE
December 2019 Release Plan (v1.2.0)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#147]
# Timeline

- **December 9th, 2019**: Code freeze
- **December 9th - 13th, 2019**: Release Candidate(s) and testing
- **December 16th, 2019**: Full Release

# Features

## React

- **Locale Selector** (#252): Call to action from the footer, which will show a modal where the user can select the locale/language translation for the given page. It will also set the user's preference.
- Updated feature flag names to include prefix (#700) 

## Vanilla

- **Footer** (#356): New look with two different configurable types (full, slim)

## Patterns (React)

- **Simple Long Form** (#466): Simple Long Form pattern&ast;
- **List Section** (#449): List section pattern&ast;
- **Table of Contents** (#445): Table of Contents pattern&ast;
- **Lead Space, centered** (#437): Lead Space pattern, centered version&ast;
- **Next Steps (cards w/o images)** (#472): Next Steps pattern&ast;
- **Use Cases** (#469): Use Cases pattern&ast;
- Updated feature flag names to include prefix (#700) 
- Add data-autoid attributes to optional fields for Patterns (#637)
- **LeadSpace** (#732): Update styles to apply color theme as a container modifier

> &ast; NOTE: Behind a feature flag

## Utilities

- **Available Language utility** (#509): Utility for providing the available language translation on the current page

## Bugs

- Footer suddenly is in white background (#718)
- IBM logo in Masthead is not aligned with content in big screens (#719)
- Separate global imports into different package (#527)

**Comment by annawen1** [comment]
v1.2.0 has been released
