### ISSUE TITLE
[Locale Selector] Does not load in IE11

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1475]
## Detailed description

> Describe in detail the issue you're having.

This was reported from URX. The locale selector loads as blank when in IE11. Test environment from their end:

https://wwwstage.ibm.com/account/reg/us-en/signup?formid=urx-19907

This was also reproducable on our nextjs ssr environment:

<img width="1658" alt="Screen Shot 2020-02-25 at 11 15 03 AM" src="https://user-images.githubusercontent.com/1641214/75282114-7675a880-57de-11ea-9dd3-149a915c3230.png">

The issues appear to be missing polyfills for IE11:

<img width="1674" alt="Screen Shot 2020-02-25 at 11 19 31 AM" src="https://user-images.githubusercontent.com/1641214/75282133-7ecde380-57de-11ea-86db-d928de7df3d1.png">

> What browser are you working in?

IE11

> What version of the IBM.com Library are you using?

`v1.4.0-rc.2`

## Steps to reproduce the issue

1. Go to http://ibmdotcom-nextjs-test.mybluemix.net/ in IE11
2. See locale selector button in the footer

**Comment by RobertaJHahn** [comment]
This was an issue submitted by URX.  DDS dev provided a work around to turn off the Locale Selector for IE11.
