### ISSUE TITLE
Card section with images - minimum height

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1478]
#### Describe in detail the issue you're having.
The minimum height of the card section with images at the small breakpoint is incorrect, the height is too short, and doesn't follow the design specs.

| Current | Intent |
|---|---|
| ![Screen Shot 2020-02-25 at 4.53.58 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/ea9f2d07-48fc-495f-ba1a-a4b941e84274)  |  ![Screen Shot 2020-02-25 at 4.54.26 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/21cddf11-d0e8-45cf-acd7-2c8998ae425e) |

#### Is this a feature request (new component, new icon), a bug, or a general issue?
design defect / bug

#### Is this issue related to a specific component?
[Card section with images](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-cardsectionimages--default)

#### What did you expect to happen? What happened instead? What would you like to see changed?
Minimum space between body copy and icon should be 64px

#### What browser are you working in?
Chrome

#### What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Web simplification

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by mkothur** [comment]
@RobertaJHahn I have opened a [PR](https://github.com/carbon-design-system/ibm-dotcom-library/pull/1584) for this issue but later confirmed with @photodow  it is resolved here [1556](https://github.com/carbon-design-system/ibm-dotcom-library/pull/1556), so closing the issue and PR.
