### ISSUE TITLE
Pattern: Card Section : Spacing issue between heading and copy text

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1480]
Issue:- As per the design with 'lg-1056px-card section' difference between heading and copy text has be to 64 px , where as in actual it is more than 64 px.

1.Enter card section url in the browser.
2. Add some extra text in 'Heading' section through knobs.
3. Now check the spacing difference between 'Heading' and 'Copy' 

OS:- Windows 10, Mac
Browsers:- Chrome, FF, Safari, Edge

![lg-1056px abstract.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/f1b86d3a-5675-4dac-8f6d-b835ce2a1616)

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Can you provide a screen shot of the actual implementation.

**Comment by chetankan** [comment]
![Spacing difference in cardsection simple.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/a6b8b140-edcd-4c04-a6b0-c2b4b1befe05)
