### ISSUE TITLE
Pattern: Card Section Simple -Accessibility- screen reader - beginning and ending boundary for each card is not conveyed for the user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1481]
## Detailed description

Device - JAWS FF, VO iPhone Safari

Issue:- The beginning and ending boundary for each card is not conveyed for the screen reader user.
Suggestion:- Provide each card within the landmark region and give appropriate label.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/2f274907-7ead-4d4c-ac4a-43db62467abf)

**Comment by mkothur** [comment]
@Praveen-sr , I have added the role and aria-labelledby attributes  could you please test it here from [PR deploy preview](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1489/index.html?path=/story/patterns-sections-cardsectionsimple--default). And let me is it behaves as expected or not. thank you!

**Comment by Praveen-sr** [comment]
@mkothur @RobertaJHahn Re tested this on the link provided above, issue still persists.
Recommendation:
provide region role for the div which contains the card with aria-labelledby. and associate its id with the heading for that particular card.
below is an example link for reference.
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html 
Thanks

**Comment by mkothur** [comment]
@Praveen-sr: update the changes could test with the same above build URL.

**Comment by Praveen-sr** [comment]
@mkothur @RobertaJHahn Re tested this on the [PR build URL](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1489/index.html?path=/story/patterns-sections-cardsectionsimple--default) provided above, issue still persists.

#1383 - Is the same issue, its fixed and working.

**Comment by Praveen-sr** [comment]
@mkothur Re tested this with the new link, its working now. Cards beginning and ending boundary is conveyed to the user.
@RobertaJHahn We can close this issue. Thanks
