### ISSUE TITLE
Pattern: Card Section Simple - Accessibility - The heading and the body in each card is given as link.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1482]
## Detailed description

Device - JAWS FF, VO iPhone Safari

Issue :- The heading and the content in each card is given as link. This makes it redundant.
Suggestion:-
If both the links in each card is expected to perform the same action, there is no need to provide different links. Either the heading or the content under the heading can be given as link.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a6e6fe6c-48bf-43b2-8156-4346c75f7db3)

**Comment by Praveen-sr** [comment]
The whole card is given a link, 'heading' and 'copy'
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/2e05c78b-0af9-41af-b4db-790dc86cdbc2)

For screen readers - when they use tab / shift tab navigation,  focus reaches the link in each card heading and copy and announces them as separate links, so its confusing for screen readers.

Suggestion :- Is it possible if the entire content in the card is given in anchor tag. 
In this scenario, only the heading can be given in anchor tag. Instead of the copy too given as links.

**Comment by mkothur** [comment]
@RobertaJHahn @wonilsuhibm @jeffchew - I have tried some research on this issue what happening is for screen readers(keyboard users) when tab focus on a card the screen reader is reading (heading and copy) continuously and making trouble for readers to understand link text. And discussed with Ram about this he is saying could give the anchor tag only heading of the card. But I have explained to Ram we are passing like heading,copy type-"link" properties to the card and these props are rendering inside the ClikcableTile component and wrapping the entire card and props in a anchor element. Is their any way to brainstorm  in design perspective.

@oliviaflory any suggestions or workaround on this. thanks!

**Comment by wonilsuhibm** [comment]
Should there be an ARIA attached to the entire card—will this force the reader to read just the ARIA and skip the contents?

**Comment by mkothur** [comment]
yeah we added earlier `aria-lable` to the entire card itself but its not fixing the another issue related to accessability [1481](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1481)

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn 
I'll be taking this up, I'm currently working on a similar issue, so as soon as I finish that I can use the safe fix in this case, thanks!
