### ISSUE TITLE
Card section with images – icon placement

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1499]
#### Describe in detail the issue you're having.
The icon in the card is 4px off in alignment, it should be pinned to the bottom left edge. 

It looks like the `footer` area is 24px tall and the 20x20px icon is top aligned in that container.
![card-icon-footer](https://user-images.githubusercontent.com/45692622/75359033-c78aa880-5881-11ea-9c26-c04b4b189932.gif)

#### Is this a feature request (new component, new icon), a bug, or a general issue?
Bug / design defect

#### Is this issue related to a specific component?
Cards used within Card section with images

#### What did you expect to happen? What happened instead? What would you like to see changed?
Icon should align to the bottom margin of the card.

#### What browser are you working in?
Chrome

##### What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Web simplification

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

I had a discussion with Wonil, Lara, Jeff and Kenny about how we are using icons in the components and patterns and if we need to implement some standards around how to utilize icons. We are considering if a wrapper would be a better solution.

**Comment by oliviaflory** [comment]
Design exploration study to follow up on the conversation between design and development on Feb 26 – Icon placement standards #1500

**Comment by mkothur** [comment]
@RobertaJHahn while testing this issue in my local the footer icon in cardSection-images pattern looks like below not like in the ticket description. And I have checked with @oliviaflory it's fixed so, could you close this bug.
![image.png](https://images.zenhubusercontent.com/5d4853b7e9d69e67d3046b0f/9dbac345-13c1-4846-bf5f-f7ded24a29f3)

**Comment by RobertaJHahn** [comment]
closing issue based on Mahesh's comments above.
