### ISSUE TITLE
Pattern: Card Section Images - Card font text is not readable, while theme (g90 and g100) is changed.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1502]
## Detailed description
Devices - Windows, Mac and Mobile
Browsers - Firefox, chrome and Safari

Issue :- When a user changes the theme, the background color is merged with the card heading / copy text and not readable for the user.

## Steps to reproduce the issue

1. Open the Storybook URL on the browser
2. Select Content Section images
3. From Knobs, change the "theme" to g90 or g100
4. Verify background color and card heading , text

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6738becd-5430-4769-a3fb-e7cbd375354d)

**Comment by mkothur** [comment]
@Praveen-sr: can you test this with this [URL] (https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1539/index.html?path=/story/patterns-sections-cardsectionimages--default) and let me know is it as expected or not thanks!

**Comment by Praveen-sr** [comment]
@mkothur Re tested the issue on provided URL, working as expected now on windows, Mac and Mobile. Thanks!
