### ISSUE TITLE
Pattern: Card Section Images - If the card heading is large, then the cards do not align correctly. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1504]
## Detailed description
Browser - Chrome, Firefox and Safari

Issue:- When the card heading is big, alignment of the cards is not right.

## Steps to reproduce the issue

1. Open the Storybook URL on the browser
2. Select Card Section images
3. From Knobs, change the heading from "Topic or blog" to "Serving society ethically in the age of Artificial Intelligence."
4. Verify the cards alignment.
4. etc.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b67dbcff-d01a-4b36-9bbf-a6e565acfbc6)

**Comment by RobertaJHahn** [comment]
@mkothur Can you work on this to include in the March release?

**Comment by mkothur** [comment]
@RobertaJHahn: Opened the PR for this and will tag QA team and share the build url with them to test again. thanks!

**Comment by mkothur** [comment]
@Praveen-sr:  I have made change to address this issue, could you please test it here from [PR deploy preview](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1540/index.html?path=/story/patterns-sections-cardsectionimages--default). And let me know is it behaves as expected or not. thank you!

**Comment by Praveen-sr** [comment]
@mkothur @RobertaJHahn  Retested this on the PR link provided above, its working as expected on desktop and mobile.
Thanks.

**Comment by ljcarot** [comment]
QA retest confirms the fix is good.  Waiting for this PR to be merged before issue can be moved to done and closed.  Thx all.
