### ISSUE TITLE
Vis specs update: Card section — simple

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1508]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
- [ ] Design specs are available in [this Box fodler](https://ibm.box.com/s/6prfrgt7dftdg47ejy3q3m4x7h47kbmo)

**Comment by larahanlon2** [comment]
Note: on mobile, the spacing between the section title and cards should be `64px`. Need to update (currently specs show 32px).
