### ISSUE TITLE
Vis specs: Content block — simple

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1509]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns
- The design specs seem to be mismatching.
- It's okay to abandon Abstract and go with PDF in the box folder.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box - [ ] Design specs are available in [this Box fodler](https://ibm.box.com/s/7f8mb1xyqdu5pimx9k1xtpl7oqrme0qf)

**Comment by larahanlon2** [comment]
@wonilsuhibm @ltitle @ljcarot @Praveen-sr @chetankan @RobertaJHahn 

Design specs – as confirmed by Lila, Lara, Wonil 
**Abstract:** https://share.goabstract.com/06a41475-72e4-45d0-9bef-3fb0158bcdca
**Box:** https://ibm.ent.box.com/file/600995262427
