### ISSUE TITLE
Accessibility testing of Masthead and Footer

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#151]
#### User Story

> As a `[user role below]`:
ibm.com user with visual impairments

> I need to:
effectively navigate through ibm.com's header and footer

> so that I can:
find my way through ibm.com

#### Additional information

 - Use tools like Chromevox for testing keyboard navigation and voice announcements
 - Any automated accessibility tests
 - Should report any issues as separate issues in Github

#### Acceptance criteria
 - [ ] Masthead and footer passes WCAG AA compliance

**Comment by RobertaJHahn** [comment]
Plan to do this testing during sprint 21 code freeze.
