### ISSUE TITLE
Pattern: content block – simple, missing link list

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1514]
## Detailed description

**Describe in detail the issue you're having.**
The right side `link list` is missing from the current pattern in Storybook. This is part of MVP.

Current:
<img width="1122" alt="Screen Shot 2020-02-27 at 11 14 09 AM" src="https://user-images.githubusercontent.com/53093550/75462844-dc833c80-5952-11ea-8b6b-daf347b50e69.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Missing component/sub-pattern

**Is this issue related to a specific component?**
Link list

**What did you expect to happen? What happened instead? What would you like to see changed?**
Should include this:
<img width="787" alt="Screen Shot 2020-02-27 at 11 13 38 AM" src="https://user-images.githubusercontent.com/53093550/75462725-ab0a7100-5952-11ea-8b2b-a5250a1ad644.png">

**What browser are you working in?**
Chrome

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification

**Comment by RobertaJHahn** [comment]
@mkothur Can you look at this while you are working on this pattern in Sprint 20-04

**Comment by jeffchew** [comment]
As discussed, we have opened issue #1581 which would support the layout of the block patterns with the Link List.
