### ISSUE TITLE
Vis specs: update Card section — with images

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1519]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect the code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box - [ ] Design specs are available in PDF format in [this Box folder](https://ibm.box.com/s/u4acyo9oeqya8xidimxtidh8k8y08fza)

**Comment by wonilsuhibm** [comment]
The label color token needs to be updated per #1874

**Comment by sethibm** [comment]
This one is on temporary pause while focusing on Ideation stories around padding and visual spec standards, at least enough work to apply a rough working model for both on this visual spec.
