### ISSUE TITLE
Vis specs: content group - with pictograms

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1526]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

#### Additional Information
- This issue is dependent on the [Spacing and Pattern Structure in Visual Specs & Code #35](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/35) and the [Visual Spec Standards #36](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/36) issues included on the Ideation board.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box - [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/af11r4k5fv1wclv1yrl9aic5c68x29ra)

**Comment by RobertaJHahn** [comment]
Moving this work to backlog until the Ideation work is finished.
