### ISSUE TITLE
Vis specs: feature card block - medium

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1527]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box - [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/pasipprq3njaholcg9bgtnv7khzq4kkq)

**Comment by sethibm** [comment]
Have questions on what was changed within dev, versus what was missed between original spec and implementation.  Padding, background colors and hover state colors areas in question. Will check in first thing Monday.

![questions](https://user-images.githubusercontent.com/58601040/79611704-296ccf00-80c9-11ea-90c9-5c618464da10.jpg)

Fyi @wonilsuhibm @larahanlon2 @oliviaflory , if you have input on this meanwhile.

**Comment by sethibm** [comment]
This story is pending a new title for this pattern.  Pete on Reboot team is handling visual spec for the "Feature card", which is just the card part of this one, and will handle the hover states, colors, etc, there.  I will focus just on padding between elements for this spec.

**Comment by sethibm** [comment]
This one is on temporary pause while focusing on Ideation stories around padding and visual spec standards, at least enough work to apply a rough working model for both on this visual spec.
