### ISSUE TITLE
Vis specs: button group

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1528]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.
- This pattern is used in the [lead space pattern](https://ibm.box.com/s/nsf7xagea5sn3ov3ozav0cio6hpk1zok)
- With that, a part of this work will be:
   - Compare what's in the code and what in the current design specs (if exists)
   - If there are discrepancies, get agreement from Lara Hanlon and Wonil Suh on what is the intent
   - Update/create the visual specs.
- Assume that up to three buttons would be allowed.
- There can be only one primary button.
- Use the tertiary button style for the secondary action buttons.

### Acceptance criteria
- [x] Design specs are available in PDF format in [this Box folder](https://ibm.box.com/s/wwod5e4ouuhgnkppx78zxh0nnvwze0k1)
- [x] Add README Box note in [this Box folder](https://ibm.box.com/s/wwod5e4ouuhgnkppx78zxh0nnvwze0k1)

**Comment by sethibm** [comment]
@wonilsuhibm Can review this one and make sure ok to move to Done?

**Comment by sethibm** [comment]
This one is on temporary pause while focusing on Ideation stories around padding and visual spec standards, at least enough work to apply a rough working model for both on this visual spec.  @larahanlon2 Wonil asked to review finals on this and other ones with you when close, but it can wait a bit, until the above is farther along.

**Comment by larahanlon2** [comment]
Sounds good to me, just let me know when and how I can help. Thanks @sethibm
