### ISSUE TITLE
Vis specs: card

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1529]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box 
- [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/3ma5hudlb59s3jossq96yxduqyj68pq7)

**Comment by larahanlon2** [comment]
@wonilsuhibm minor updates to specs were needed – [final Sketch file ](https://ibm.box.com/s/ojyihmfd4xvgbjqvx81i2djb3t1wvxug)can be found here. 

But we will need to add the new Solutions cards. I just received specs from Lila so we may need to continue this story next sprint.

**Comment by wonilsuhibm** [comment]
@larahanlon2 Thank you. Let's continue this in sprint 7.

**Comment by larahanlon2** [comment]
We (Olivia, Lila and I) met with Shixie and Pete this morning for a final review of card specs. We discussed and agreed on the following items:

1. Active state for cards will be hover + focus border. Shixie to follow up with Carbon on this state as the Carbon tile is slightly different (link has underline, we don't want that)
2. Will continue using condensed grid for card group on sm breakpoints. Shixie has a proposal for Carbon to allow cards to go full bleed on grid. She will document the specs and meet with Carbon to discuss but our specs will be finalized with the current condensed grid.
3. Image hover will be 8% lighten/darken.

Shixie and Pete will make final adjustments to their files and share back with the team. Will need @wonilsuhibm to approve.

**Comment by larahanlon2** [comment]
[Here's](https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A167&scaling=min-zoom) Shixie's prototype for hover states on image cards.
