### ISSUE TITLE
Vis specs: content group

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1531]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.
- With that, a part of this work will be:
   - Compare what's in the code and what in the current design specs (if exists)
   - If there are discrepancies, get agreement from Lara Hanlon and Wonil Suh on what is the intent
   - Update/create the visual specs.

### Acceptance criteria
- [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/5n0sj6b3kkicnwimxmgnwb5owm46g8wz)

**Comment by sethibm** [comment]
This one is almost done. Pending input from design and dev on padding for the top and bottom of the pattern, for both breakpoints (it's different), and on question if padding on both top and bottom is causing potential conflicts within overall template layouts.

**Comment by sethibm** [comment]
This one is on temporary pause while focusing on Ideation stories around padding and visual spec standards, at least enough work to apply a rough working model for both on this visual spec.
