### ISSUE TITLE
Vis specs: Link list

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1534]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
- The specs for this pattern will be updated by the Reboot team.

### Acceptance criteria
- [ ] Review design specs from the Reboot team.
- [ ] Design specs are available in PDF format in [this Box folder](https://ibm.box.com/s/dgnfrnpaqepbuyifa04aoc091v4cnz3d)

**Comment by ljcarot** [comment]
Since Drupal is testing based on visual spec, can we pls make sure spec is updated ASAP ?

**Comment by sethibm** [comment]
@wonilsuhibm This one has spec for overall list, so I'm guessing this is for a single list item?  If you can provide visual reference and review if links are correct like other one, it would be helpful.
