### ISSUE TITLE
Vis specs: pictogram item

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1535]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.
- The `content group - with pictograms` design is [here](https://ibm.box.com/s/af11r4k5fv1wclv1yrl9aic5c68x29ra). This task is to create design specs for the sub-pattern, `pictogram item` seen below.

<img width="1574" alt="Screen Shot 2020-03-26 at 8 40 05 AM" src="https://user-images.githubusercontent.com/30183447/77647784-6f58cc00-6f3d-11ea-9700-7714db253b56.png">

### Acceptance criteria
- [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/kjio8inhxhkmf7245l2wccp8zsivka9l)
- [ ] The `Content group - with pictograms` pattern design spec file has been updated with reference to this sub-pattern. The `content group - with pictograms` pattern is [here](https://ibm.box.com/s/af11r4k5fv1wclv1yrl9aic5c68x29ra)

**Comment by sethibm** [comment]
@wonilsuhibm I'm not understanding what this is...the Box folder just indicates this is for Card section - with images.  I'm guessing it's a card where the image is a pictogram, how it looks, padding, etc?  The solution page has a pictogram over a gradient...perhaps this is it.  Can you help clarify and provide any visual examples here?  I'm guessing it needs to be added to the existing spec document in the folder, and then all the artboards need to be exported so there is an overall PDF spec in the folder?  I see in the README, a link to Abstract, which I can't access.  I've requested permission, but am guessing the Sketch file there is the same one as in Box folder.

**Comment by wonilsuhibm** [comment]
@sethibm Sorry about that. I added the correct Box folder in the description. There are two folders you need to look at—one is the folder that has the larger pattern, `Content group - with pictograms`. The other is this `Pictogram item`.

<img width="1574" alt="Screen Shot 2020-03-26 at 8 40 05 AM" src="https://user-images.githubusercontent.com/30183447/77647784-6f58cc00-6f3d-11ea-9700-7714db253b56.png">

**Comment by ltitle** [comment]
I have updated specs in both of these box folders.
