### ISSUE TITLE
IBM.com style model research part 1

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1538]
### Notes

In order to support our adopters and help them make the best decisions re: style models for ibm.com, we need to identify and communicate design research best practices.

### Problem

When designers are tasked with designing ibm.com experiences, they don't always know where to start. Design research can provide insights and best practices for designers to follow and apply to their work. IBM has robust user research tools but less design (visual, UX, interaction) guidelines.

### Tasks
1. Map out design research flow/steps 
2. Identify existing tools and resources that designers can use to get started
3. Propose new methods or tools that we need to provide
4. Consider how this fits into style model, library, system etc.

**Comment by larahanlon2** [comment]
Things to consider: 

- What kind of sprint epics/stories can we create around research
- What does the framework look like 
- How can our DDS designers research and feed into adopters

**Comment by larahanlon2** [comment]
Created[ this Mural ](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1584117576415?sender=larahanlon9022&key=6cb85be5-459b-407a-9233-0ddadc7cd438)to map out ideas and steps.

**Comment by larahanlon2** [comment]
Closing this issue. Will open a new one to track the continuation of this work.
