### ISSUE TITLE
[Layout] Add 4/8/4 layout type

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1543]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
Have a 3 column layout available from the Layout component

> so that I can:
quickly layout a 3 column structure for my application

#### Additional information

 - `Layout` currently supports a 4/12 layout
- `Layout` types are added here: https://github.com/carbon-design-system/ibm-dotcom-library/blob/e912e7af216374a07de44fdb5a4c73e00d8ed2e7/packages/react/src/patterns/sub-patterns/Layout/Layout.js#L24
- Should add a new type as `1-2-1`

#### Acceptance criteria
 - [ ] New layout type `1-2-1` available in `Layout` component
 - [ ] Updated README

**Comment by jeffchew** [comment]
@photodow think we are still doing this or we should close this?

cc: @RobertaJHahn @ljcarot

**Comment by photodow** [comment]
@jeffchew is there a reason for it? I can't think of a use case at the moment. This specific layout the latest modification can be accomplished, but there may still be value here. I almost say let's close it for now. I imagine we'll need more options as we expand.
