### ISSUE TITLE
[Layout] Create functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1544]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have a clear understanding on the functionality of the Layout sub-pattern

> so that I can:
develop, enhance, and test the Layout pattern successfully

#### Additional information

 - Layout is currently being used in the TableOfContents, and is referenced in the functional specifications: https://ibm.ent.box.com/file/599375190897
- Layout only has one layout type so far. Another issue has been created to add a second layout type: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1543
- Layout has a "sticky" attribute that can be added to any columns in the Layout. This feature is currently used in the Table of Contents

#### Acceptance criteria
 - [x] Functional specifications created in Box
- [x] Updated references to the Layout component (Table of Contents functional specifications)

**Comment by RobertaJHahn** [comment]
Functional specs reviewed with the DDS designers and developers April 14, 2020.

**Comment by photodow** [comment]
Here is the link for Layout.

https://ibm.ent.box.com/file/653598443308
