### ISSUE TITLE
Expressive theme – token usage:  Part 1

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1551]
In order to show Carbon the final solution for the expressive theme, we need to work out how the spacing tokens are applied throughout the two different type themes so we can present it to them and get agreement on the theming solution.

**Solution 1**
Ideal state of centering 48x40 and 48x48 icons
- identify new tokens that are required to achieve ideal 48x48 centered icons
   - propose name for the new tokens
- map out token usage throughout the two systems
- identify where the system breaks and new design proposal.

**Solution 2**
utilize the existing tokens, and have icons set in 52x48 box for expressive theme
- map out token usage throughout the two systems
- identify where we might want to propose new spacing tokens for small amount of symbols
   - tag
- identify where the system breaks and new design proposal.

Acceptance criteria
- [ ] Solutions are solid at a system level.
- [ ] documentation is able to be provided to Carbon as the ideal state.

**Comment by RobertaJHahn** [comment]
This work continues in the following sprint under issue (#1716).  Closing.
