### ISSUE TITLE
Test learn page design QA

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1559]
This story is to conduct design QA using the new test page from the story #1494.

The test learn page is hosted here:
http://ibmdotcom-nextjs-test.mybluemix.net/learn

### Acceptance criteria
- [ ] the overall user experience is at an acceptable level
- [ ] bug issues have been created
- [ ] prioritized bug fixes have been retested

**Comment by JennySanchez** [comment]
@oliviaflory #1626 is part of the learn page design QA outcome, correct?

**Comment by JennySanchez** [comment]
Comments added to the Box doc: https://ibm.box.com/s/8w6u4w2cxt9c086l2fyi43alepwgphz7
