### ISSUE TITLE
Pattern:- Card- On setting aspect ratio to 2:1, 4:3, and 16:9 title and copy text goes out of card space.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1562]
Issue:- In card patter when aspect ratio is set to 2:1 or 4:3 or 16:9 in that case if title and copy text is displayed out of card space.

## Steps to reproduce the issue

1. Enter the url in the browser
2. Open card pattern(Static or Link)
3. Add some extra text in title and copy section
4. Set aspect ratio to 2:1 or 4:3 or 16:9 
5. Open pattern in new page.

OS:- Windows 10, Mac, iOS, Android 
Browsers:- Chrome, Firefox, Safari, UC, Samsung.![Card with 2-1 aspect ratio.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/80f6d15b-c515-43b3-a30a-b767a394aa87)![Card with image in 2-1 ratio.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/273b66f8-c01a-4914-874d-0afb0d019075)

**Comment by RobertaJHahn** [comment]
This issue is a blocker for the QA team regression testing.   Must be fixed by EOD Friday, 3/6.

**Comment by RobertaJHahn** [comment]
Keeping this in v1.5.0 to hopefully patch the fix in next week.

**Comment by jeffchew** [comment]
Hey @RaphaelAmadeu do you have time to get this in before the next release candidate? @kennylam took a brief look and thinks might be a simple fix, you can reach out to him with any questions.

cc: @RobertaJHahn @ljcarot

**Comment by jeffchew** [comment]
@RobertaJHahn going to remove this from `v1.5.0` as the engineers discussed and isn't an issue with the Card itself but for the storybook story. 

cc: @RaphaelAmadeu @kennylam @photodow @annawen1 @andysherman2121

**Comment by RobertaJHahn** [comment]
@jeffchew I have added it to the April release.
