### ISSUE TITLE
Pattern: Content Block Segmented - On click on card section, whole page goes blank.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1564]
## Detailed description

Issue:- When user changes CTA type from 'local' to 'jump' on knobs and clicks on the card, the whole page (with all the section) goes blank.

## Steps to reproduce the issue

1. Open the storybook and load Content block segmented
2. Go to knobs, CTA type and change "local" to "jump" option
3. Click on the card section
4. Verify the card section and other sections.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1d4c8988-cb96-4b4a-ad32-9503d9064246)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/2ef0b166-9d7d-4d78-89c2-32d19895830d)

**Comment by kennylam** [comment]
@Praveen-sr I can't reproduce this. Toggling the knobs for both CTA `type` and `style` behave as expected.

http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblocksegmented--default
