### ISSUE TITLE
Lead space, buttons should be optional

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1568]
## Detailed description

**Describe in detail the issue you're having.**
For all lead space types, buttons should be optional. 

Currently, all lead space types use ButtonGroup.

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Missing feature

**Is this issue related to a specific component?**
Button / ButtonGroup

**What did you expect to happen? What happened instead? What would you like to see changed?**
An adopter should be able to choose the following:
- No button CTAs
- 1 button CTA (primary)
- 2 button CTAs (secondary + primary)

Examples of no button:
<img width="656" alt="Screen Shot 2020-03-03 at 10 57 01 AM" src="https://user-images.githubusercontent.com/53093550/75793733-c81db600-5d3d-11ea-9837-749f9bac6fc9.png">

Example of 1 button (primary):
<img width="657" alt="Screen Shot 2020-03-03 at 10 57 09 AM" src="https://user-images.githubusercontent.com/53093550/75793747-ceac2d80-5d3d-11ea-98e2-61e0eb65f495.png">

What browser are you working in?
Chrome

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification

## Steps to reproduce the issue
Open any lead space and go to add ons: https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image

## Additional information
- Already coded to have the buttons optional.  Storybook needs to be updated.  

Web simplification's Learn page does not require any button CTA's:
<img width="657" alt="Screen Shot 2020-03-03 at 10 42 23 AM" src="https://user-images.githubusercontent.com/53093550/75792291-bb985e00-5d3b-11ea-9930-68a167e9e28e.png">

**Comment by RobertaJHahn** [comment]
- Already coded to have the buttons optional.  Storybook needs to be updated.
