### ISSUE TITLE
Request to top-align text and icon in ButtonGroup

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1572]
### The problem
Currently, icons and text are vertically centered within all Carbon buttons. This works great until the text wraps to two lines or more. When that happens, the text and icon are no longer top-aligned.

Example of current alignment with single line of text:
<img width="716" alt="Screen Shot 2020-03-03 at 4 58 40 PM" src="https://user-images.githubusercontent.com/53093550/75823910-907c3180-5d70-11ea-964a-7a492ceaf2b9.png">

Example with two lines:
<img width="782" alt="Screen Shot 2020-03-03 at 4 46 19 PM" src="https://user-images.githubusercontent.com/53093550/75823966-ae499680-5d70-11ea-8df1-1e400d3c7a32.png">

Example with 3 lines:
<img width="742" alt="Screen Shot 2020-03-03 at 4 46 26 PM" src="https://user-images.githubusercontent.com/53093550/75823988-b7d2fe80-5d70-11ea-87de-840075e94bc4.png">

### The solution
Ideally, text and icon would align to the top like this:
<img width="737" alt="Screen Shot 2020-03-03 at 5 07 42 PM" src="https://user-images.githubusercontent.com/53093550/75824471-91fa2980-5d71-11ea-8b09-4cb46ce0e1ca.png">
<img width="719" alt="Screen Shot 2020-03-03 at 5 09 14 PM" src="https://user-images.githubusercontent.com/53093550/75824593-c79f1280-5d71-11ea-8931-af1aa7b7e077.png">

### Additional information
We can see how the misalignment impacts Learn page centered lead space today:
<img width="1077" alt="Screen Shot 2020-03-03 at 5 14 58 PM" src="https://user-images.githubusercontent.com/53093550/75825118-c6221a00-5d72-11ea-932f-637655f50481.png">

**Comment by larahanlon2** [comment]
Maybe this should be a feature request for Carbon team? TBD.

**Comment by JennySanchez** [comment]
@larahanlon2 I reached out to Anna to see if this is something we need to create a task issue on Carbon's Git repo - FYI.

**Comment by RobertaJHahn** [comment]
@larahanlon2 @JennySanchez Have you guys heard anything from the Carbon team?

**Comment by JennySanchez** [comment]
@RobertaJHahn No, but I will reach out to Anna again today.

**Comment by JennySanchez** [comment]
Ok. @larahanlon2 I think you might want to reach out to Jeannie about the button. Please see the Slack conversation I had with Anna below.
![Screen Shot 2020-03-23 at 1.34.54 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/bf31cc65-2ca3-4c9f-a606-3ae4f84f387d)

FYI - @RobertaJHahn
