### ISSUE TITLE
Lead space left-aligned, background does not keep bottom padding when content grows

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1573]
## Detailed description

**Describe in detail the issue you're having.**
When adding lots of content to `left-aligned` type, the buttons get pushed off the lead space area and onto the main page. The bottom padding of the background does not grow taller to accommodate lots of text.

<img width="1473" alt="Screen Shot 2020-03-03 at 5 20 28 PM" src="https://user-images.githubusercontent.com/53093550/75825688-ddadd280-5d73-11ea-9f98-768bfec64d07.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Lead space, ButtonGroup

**What did you expect to happen? What happened instead? What would you like to see changed?**
Although we never want authors to use so much text for this to happen, we should address this issue. It works correctly in `lead space centered`. 

<img width="899" alt="Screen Shot 2020-03-03 at 5 21 33 PM" src="https://user-images.githubusercontent.com/53093550/75825833-2bc2d600-5d74-11ea-8395-feb7715fed43.png">

See here. When text increases, the lead space background gets taller:

<img width="1050" alt="Screen Shot 2020-03-03 at 5 21 19 PM" src="https://user-images.githubusercontent.com/53093550/75825812-21084100-5d74-11ea-9a6f-131a8406cd8b.png">

**What browser are you working in?**
Chrome

## Steps to reproduce the issue

Open pattern in [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image) and add lots of content to lead space left-aligned.

**Comment by RobertaJHahn** [comment]
This is not a bug.  We will not limit the text to prevent this issue.
