### ISSUE TITLE
Pattern: Leadspace - Large text on button wraps to 2, 3 lines and makes only one of the buttons taller.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1574]
## Detailed description

Issue :- Large text on button warps to 2, 3 lines and makes either of the primary/ secondary buttons look taller.

## Steps to reproduce the issue

1. Open the ibm.com storybook url on Mobile
2. Navigate to Leadspace with image
3. Go to knobs, edit/add large text for secondary button
4. Go back to canvas and verify the button view

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/92ffd797-0036-4871-adb4-1278e54af672)

**Comment by caiobozato** [comment]
@Praveen-sr I was reading you request and checking the Storybook. But isn't this the correct behavior for the CTA when you have larger texts?

I think it would be incorrect if the text overlaps the CTA **container** when it's size increases.

@ltitle @photodow Could you please check this and see if I'm saying something wrong?

**Comment by ltitle** [comment]
The expectation would be that if the text is long and needs to wrap that the button height would increase (as shown in the visual above). However, if one button height increases both should increase even for the one with the shorter text string. That way they will always be the same size visually.
