### ISSUE TITLE
Pattern - Leadspace - Primary and Secondary buttons in landscape mode are getting displayed in square

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1575]
Issue:- In leadspace pattern with center in landscape mode on mobile devices 'Primary and Secondary' buttons are getting displayed in square box.

## Steps to reproduce the issue

1. Enter the url in the browser.
2. Select 'Leadspace' pattern(With or Without Image)
3. Select 'Center' in type.
4. Turn mobile in landscape mode

## Additional information

OS:- iOS, Android
Browsers:- Chrome, Safari, UC, Samsung

URL:- https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image![Leadspace centered button in landscape mode.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/5fa3e960-2bad-406f-a80a-729a6a3f6f5f)

**Comment by andysherman2121** [comment]
@chetankan I just tested this in Browserstack and wasn't able to duplicate this issue. Could you guys retest this and confirm it's still a bug. It's possible it was fixed as there have been a number of changes to buttongroup since this issue was first created. Thanks!

**Comment by chetankan** [comment]
@andysherman2121 : Verified in both 'Staging' and 'React-experimental' it is working fine. We can close this bug.

![Primary and seconday buttons.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/6f0d9801-bf1a-485b-99a1-ff67a3d88958)
