### ISSUE TITLE
Pattern: Accessibility- screen reader - beginning and ending boundary for each card is not conveyed for the user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1577]
## Detailed description

Device - JAWS FF, VO iPhone Safari

Issue:- The beginning and ending boundary for each card is not conveyed for the screen reader user.
Suggestion:- Provide each card within the landmark region and give appropriate label.

This issue appears on all the patterns where cards are used:
1. Content Group card (fixed in the decorator pattern)
2. Content Block Mixed 
3.Content Block Media 
4.Content Group Simple 
5.Content Section Simple 
6.Content Section images
7.Content Block Simple 
8.Content Block Segmented

**Comment by ariellalgilmore** [comment]
@Praveen-sr it looks like these isssues were fixed except for Content Section images where it doesn't completely wrap
![Screen Shot 2020-06-25 at 10.44.24 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/26671151-52e7-42d3-bd91-7ced1133aec6)

**Comment by diegomarcuz** [comment]
Hey @Praveen-sr, is this issue ok ? I have double checked here and everything is working well. 

It is working like this with screen reader: 
![video.gif](https://images.zenhubusercontent.com/5eed25994ac8fb057241e3b2/f4d8d92f-ce46-4b47-bafb-01d61463b8ab)

**Comment by Praveen-sr** [comment]
@diegomarcuz @RobertaJHahn Link used Staging 
Ram verified this on JAWS, for 
1. Content Block Segmented
2. Content Block Media
3. Content Section images
4. Content Block Simple
Here, card is identified with appropriate label -- Working.

Note: We need to verify this scenarios on iPhone voice over. (i'll update you once done.)
Thanks!

**Comment by diegomarcuz** [comment]
Thanks @Praveen-sr

**Comment by Praveen-sr** [comment]
@RobertaJHahn @diegomarcuz Ram verified this on JAWS & iPhone VO - please find the reports below,

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f7885e04-0f3b-4036-b27c-74cb7683f1a7)

**Comment by RobertaJHahn** [comment]
Thanks, closing.

**Comment by diegomarcuz** [comment]
@RobertaJHahn why did you close this issue ?
