### ISSUE TITLE
Pattern: Link List - On Mobile, link list is not stretched to edge of the screen and on click user doesn't navigate.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1579]
## Detailed description

Issue:- Link list is not stretched to the edge of the screen, when user clicks on the link list doesn't navigate to actual link.

## Steps to reproduce the issue

1. Open the storybook URL on Mobile
2. Navigate to Link List 
3. Click on the right corner of the link list

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1c16ce48-f12a-4aa3-bce1-c3f8c6f5ba3a)

**Comment by Praveen-sr** [comment]
We need to address this issue as well :-
@ break point 672px - Link list is not stretched to the edge of the screen. 

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8ffe6cc0-4257-43f9-826b-0fb8159fc146)

**Comment by RaphaelAmadeu** [comment]
Moving this to done, as it was fixed on another issue.

![Screen Shot 2020-03-16 at 4.20.37 PM.png](https://images.zenhubusercontent.com/5af9cd024b5806bc2bd31a6f/aba76ca9-bee8-49d6-8191-cc0b454b2b98)
