### ISSUE TITLE
Masthead: L0 dropdown first item focus state 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#158]
The focus state of the first item in the L0 dropdowns is only showing 1px of the 2px border on the **top side** . Is it possible to fix this? I looks like the rule at the bottom of the L0 is on top of the focus state.

<img width="842" alt="Screen Shot 2019-10-03 at 9 12 45 PM" src="https://user-images.githubusercontent.com/45692622/66174469-21fd4100-e623-11e9-9ef6-1aa24143d09b.png">

**Comment by photodow** [comment]
@RobertaJHahn Does this need to be closed? It looks like it got solved?

**Comment by RobertaJHahn** [comment]
@photodow Thanks for noticing.  Closing.
