### ISSUE TITLE
Content Block Simple pattern does not have caption for image.

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1589]
In v1.4.1 Content Block Simple pattern's image component seems to be missing the caption field. 

Story Book
https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-contentblocksimple--default

There is a caption below the image component in story book.  However the Content Block Simple pattern's image prop does not have a caption field in the code.

**Comment by RaphaelAmadeu** [comment]
The pattern `ContentBlockSimple` does support the caption for the image,
in order to use it, you'll need to add `heading` into the image prop object.

Here's an example on how you can achieve the desired result:
```
const image = {
      heading: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      image: {
        sources: [
          {
            src: 'https://dummyimage.com/320x180/ee5396/161616&text=16:9',
            breakpoint: 320,
          },
          {
            src: 'https://dummyimage.com/400x225/ee5396/161616&text=16:9',
            breakpoint: 400,
          },
          {
            src: 'https://dummyimage.com/672x378/ee5396/161616&text=16:9',
            breakpoint: 672,
          },
        ],
        alt: 'Image alt text',
        defaultSrc: 'https://dummyimage.com/672x378/ee5396/161616&text=16:9',
      },
    };
```
@jeffchew, We need to update `Image` documentation, as the `heading` prop is missing there.

Thanks!

**Comment by RaphaelAmadeu** [comment]
I've opened a PR in order to fix this.
