### ISSUE TITLE
Content Block Media is not generating all css 

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#1592]
Content Block Media is not generating all css.

## Detailed description
Drupal: I am trying to generate the html and css/js for the Content Block Media from 1.5.0-alpha.2918 version but I see html is getting generated properly but not css few of the example css it's missing for these classes - bx--content-group__col   bx--content-group__children
> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
Bug

> Is this issue related to a specific component? Content Block Media (Example Patter)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in? Chrome and FF

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by kennylam** [comment]
@RobertaJHahn I've gone through this issue with @sridharmula and it should be resolved in #1608

**Comment by sridharmula** [comment]
@RobertaJHahn  issue got resolved with @kennylam help with latest release changes. Thanks @kennylam
