### ISSUE TITLE
Unable to integrate ibm dot com footer component into our react application

### ISSUE THREAD

**Issue by tanvi-sambari** [carbon-design-system/ibm-dotcom-library#1594]
## Detailed description
We are using the following versions of carbon coponents:
"carbon-components": "^10.7.4",
"carbon-components-react": "^7.7.4",
Inorder to use the ibm-dotcom-library we have imported the "@carbon/ibmdotcom-styles/scss/components/footer/index.scss" into our scss file. Below is the error we are getting in the console:

./src/style/app.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/style/app.scss)
SassError: File to import not found or unreadable: carbon-components/scss/globals/scss/vars.
        on line 18 of node_modules/@carbon/ibmdotcom-styles/scss/globals/_imports.scss
        from line 8 of node_modules/@carbon/ibmdotcom-styles/scss/components/footer/index.scss
        from line 6 of D:\IBM DBG\UI_Shell\dynamic-loading-component-features-redux\ui\src\style\app.scss
>> @import 'carbon-components/scss/globals/scss/vars';

Can someone help in fixing this bug?

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@RaphaelAmadeu would you be able to assist?

cc: @ljcarot @RobertaJHahn

**Comment by RaphaelAmadeu** [comment]
@tanvi-sambari ,
Could you please attach your `package.json` file to the issue? So we can have a better idea of the issue.

Thanks!

**Comment by tanvi-sambari** [comment]
@RobertaJHahn: Here it is-
{
  "name": "ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@carbon/ibmdotcom-react": "^1.4.1",
    "@carbon/icons-react": "^10.6.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "carbon-components": "^10.7.4",
    "carbon-components-react": "^7.7.4",
    "js-cookie": "^2.2.1",
    "jwt-decode": "^2.2.0",
    "node-sass-chokidar": "^1.4.0",
    "query-string": "^6.10.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "concurrently": "^5.0.2",
    "node-sass": "^4.13.0"
  },
  "scripts": {
    "start": "npm run dev-server --verbose",
    "dev-server": "react-scripts start",
    "build": "react-scripts build --verbose",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by RaphaelAmadeu** [comment]
@tanvi-sambari ,
In order to use our footer and styling you have to install the following packages on your application:
`@carbon/ibmdotcom-styles`
`@carbon/ibmdotcom-react`

Then import the footer component from `@carbon/ibmdotcom-react`.
The import at your scss should be `@import '@carbon/ibmdotcom-styles'`

This should solve your issue, let us know if this worked,
Thanks!

**Comment by tanvi-sambari** [comment]
Thanks. Got it. Had to import {styles} from  '@carbon/ibmdotcom-styles'.

**Comment by tanvi-sambari** [comment]
@RaphaelAmadeu : Importing {styles} from  '@carbon/ibmdotcom-styles' does solve the error but it distorts the other styles on my page. I need to import only @carbon/ibmdotcom-styles/scss/components/footer/index.scss and that is still giving me the error - ./node_modules/@carbon/ibmdotcom-styles/scss/components/footer/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./node_modules/@carbon/ibmdotcom-styles/scss/components/footer/index.scss)
SassError: File to import not found or unreadable: carbon-components/scss/globals/scss/vars.
        on line 18 of node_modules/@carbon/ibmdotcom-styles/scss/globals/_imports.scss
        from line 8 of D:\IBM DBG\UI_Shell\dynamic-loading-component-features-redux\ui\node_modules\@carbon\ibmdotcom-styles\scss\components\footer\index.scss
>> @import 'carbon-components/scss/globals/scss/vars';
