### ISSUE TITLE
May 2020 Release Plan (v1.7.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1602]
# Timeline

- **May 18, 2020**: Code freeze (tentative)
- **May 19-27, 2020**: Release Candidate(s) and testing
- **May 28, 2020**: Full Release

# Features

## Core

- Upgraded to Carbon 10.11.2 (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2249)

## React
- **DotcomShell: Updates to Masthead/Footer prop handling** (https://github.com/carbon-design-system/ibm-dotcom-library/pull/2251)
- **Pattern: Card Section changes, including new Cards Group dev, needed for the Solutions page template** (#1793 )
- **Pattern: CTA section - Prod level version**  Epic (#1795 )
- **Pattern: Callout - quote - Prod level version** Epic (#1796 )
- **Pattern: Callout - with media - Prod level version** Epic (#1797 )
- **Pattern: Content block - with cards - Prod level version**   Epic (#1799 )
- **Pattern: Feature card block - large: Prod level version** Epic (#1803 )
- **Pattern: Callout - Prod level version** Epic (#1809 )
- **Pattern: Develop Quote - Prod level version**  Epic (#1806 )
- **Pattern: Content item - horizontal - Prod level version** Epic (#2284 )
- **Pattern: Content group - horizontal - Prod level version** Epic (#2285 )
 - **Pattern: Content Item changes needed for the Solutions page template** (#1812 )
- **Component: CTA changes needed for the Solutions page template** Epic (#1791 )
- **Component:  Create the Prod level version of the Footer** (#1659 )
- **Build the experimental Language only selector** Epic (#2223 )
- **Create an environment to test Arabic pages** Issue (#2021 )

#### DotcomShell
The `DotcomShell` formerly passed in `Footer` and `Masthead` props as flat props into the `DotcomShell` for functionality. We are now breaking them out into two separate prop objects, `footerProps` and `mastheadProps`. If you are upgrading to `v1.7.0` and are using the `DotcomShell`, you will need to make this modification to your code for it to continue to render properly.

#### CardSection

The `CardSection` pattern has been deprecated, so only `CardSectionImages` and `CardSectionSimple` should be used. The corresponding style imports should now be used for the respective patterns:

```
@import "~@carbon/ibmdotcom-styles/scss/patterns/sections/card-section-images/card-section-images";
@import "~@carbon/ibmdotcom-styles/scss/patterns/sections/card-section-simple/card-section-simple";
```

## Bug Fixes
- **Video Component light box media viewer does not work for many Kaltura Videos** Issue (#2303 )
- **ipcInfo cookie not set during locale change** (#2250)

**Comment by annawen1** [comment]
v1.7.0 has been released. Closing this issue
