### ISSUE TITLE
Learn Page: Feature card - Content Text is not readable, text color and the background is same.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1622]
## Detailed description

Issue :-  Content Text is not readable, text color and the background is same.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d54c8f7b-dea9-4102-83f2-ebaca86fd92d)

**Comment by ljcarot** [comment]
@Praveen-sr When you test and find something is an issue on Learn page template, can you also cross check if it is also an issue in Storybook?  If it is please note in Title or description if it is happening only on template or also in Storybook.  It will help us to know where to start the investigation.  Thx cc @jeffchew

**Comment by Praveen-sr** [comment]
@ljcarot Ok, sure thing. The above issue is only on 'Learn page' template. 
On Storybook its as expected - 
![image](https://user-images.githubusercontent.com/60002341/76299660-7e0a7680-62e1-11ea-85ba-4e318c86b525.png)

**Comment by jeffchew** [comment]
@reesedownes check if this is something we're doing with the Learn page or if we need to fix something in the `FeatureCard`:
https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test

**Comment by ljcarot** [comment]
If this is a bug with FeatureCard we'd definitely need to resolve in Patch.

**Comment by reesedownes** [comment]
this is the offending css:
```
.bx--tableofcontents .bx--tableofcontents__content h2, .bx--tableofcontents .bx--tableofcontents__content h3, .bx--tableofcontents .bx--tableofcontents__content h4, .bx--tableofcontents .bx--tableofcontents__content p {
  color: #161616;
}
```

it overrides the bx--inverse css:
```
.bx--card--inverse .bx--card__heading, .bx--card--inverse .bx--card__copy {
    color: #fff;
}
```

the reason, as far as i can tell, is that on the "learn" page it's being rendered within that tableofcontents wrapper, and the css that overrides bx-card-inverse targets h2, h3, and h4. i attached a screenshot that shows switching out for an h5 ignores the override.

@jeffchew thoughts on where to make the fix?

![Screen Shot 2020-03-20 at 4.31.53 PM.png](https://images.zenhubusercontent.com/5e70ee056aaeb9007aeb5f97/f707d7f4-9389-49bf-bbbe-bf047577b180)

**Comment by jeffchew** [comment]
@RaphaelAmadeu this looks similar to a fix you did for the p tag getting set. 

@reesedownes is the text being set as a p or some form of H tag? Wondering if the fix has already been applied in our rc.0?

**Comment by reesedownes** [comment]
@jeffchew as rendered in the nextjs app - and i assume everywhere - it's an H3 tag surrounding the text

![Screen Shot 2020-03-24 at 9.18.06 AM.png](https://images.zenhubusercontent.com/5e70ee056aaeb9007aeb5f97/b57bed14-f336-4cca-bf89-f69476b4d18a)

**Comment by reesedownes** [comment]
so the css assumes it's this rule:

```  .bx--tableofcontents .bx--tableofcontents__content h3 ```

**Comment by jeffchew** [comment]
Want to get a take from the other folks (@kennylam @annawen1 @RaphaelAmadeu @andysherman2121 @photodow ). Honestly, should we even be setting styles for the headings on the TOC level? I think these should be set on the block pattern level. Thoughts?

**Comment by annawen1** [comment]
> Want to get a take from the other folks (@kennylam @annawen1 @RaphaelAmadeu @andysherman2121 @photodow ). Honestly, should we even be setting styles for the headings on the TOC level? I think these should be set on the block pattern level. Thoughts?

I agree, it should be handled within the pattern

**Comment by jeffchew** [comment]
> > Want to get a take from the other folks (@kennylam @annawen1 @RaphaelAmadeu @andysherman2121 @photodow ). Honestly, should we even be setting styles for the headings on the TOC level? I think these should be set on the block pattern level. Thoughts?
> 
> I agree, it should be handled within the pattern

@reesedownes let's kill the heading tag styles.

**Comment by kennylam** [comment]
> Honestly, should we even be setting styles for the headings on the TOC level? I think these should be set on the block pattern level. Thoughts?

I feel like we should keep this on at the TOC level, otherwise we'll need to set the styles every time it's included in something. Also, do we have any plans of breaking this out as its own component? If so then we would definitely need to keep it as part of TOC.

**Comment by jeffchew** [comment]
> > Honestly, should we even be setting styles for the headings on the TOC level? I think these should be set on the block pattern level. Thoughts?
> 
> I feel like we should keep this on at the TOC level, otherwise we'll need to set the styles every time it's included in something. Also, do we have any plans of breaking this out as its own component? If so then we would definitely need to keep it as part of TOC.

Right now it's only setting color for the text, which I'm not sure if is the best way since on a per-pattern basis, we don't know what theme is being set.
