### ISSUE TITLE
Link list, links should be shorter on smaller breakpoints

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1629]
## Detailed description

**Describe in detail the issue you're having.**
When browser is set to med or small breakpoints the link list is retaining it's default height. It should not.

Current:
<img width="623" alt="Screen Shot 2020-03-09 at 1 13 55 PM" src="https://user-images.githubusercontent.com/53093550/76248089-0839d880-6217-11ea-9e3c-929f72435adb.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Card 

**What did you expect to happen? What happened instead? What would you like to see changed?**
According to the design specs, the height of each link should shrink. 

Desired:
<img width="837" alt="Screen Shot 2020-03-09 at 1 32 19 PM" src="https://user-images.githubusercontent.com/53093550/76248185-37e8e080-6217-11ea-81e2-54a9b8b80105.png">

**What browser are you working in?**
Chrome

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification

## Steps to reproduce the issue

1. Open the [Link List in Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-linklist--default) and view at different breakpoints.
2. Compare to design specs in [Abstract](https://app.abstract.com/projects/736617ba-6c6d-4ab0-a5ae-76de9f81ec42/branches/master/commits/c400d1d3eb91569ca29890e0df1fdff73a080919/files/c9c8a1c1-2087-4c40-a227-c504fe7fede6/layers/3D869ECC-AB07-4788-B36E-0B37A8ECB142?collectionId=7f11b1ed-750f-4503-a13d-73ab7bcddb3b&collectionLayerId=4502b6b6-7f39-4a3a-a7c9-dc8ff561d89a)

## Additional notes
When there are only 2 links this isn't a major problem. However, when there are 3 or more the list becomes very long on mobile/tablet. User has to scroll a ton to get to the next content piece.

<img width="574" alt="Screen Shot 2020-03-09 at 3 14 26 PM" src="https://user-images.githubusercontent.com/53093550/76249024-e04b7480-6218-11ea-872b-12bea29ec7fc.png">

**Comment by photodow** [comment]
@larahanlon2 here is the conversation you me and Lila had about this topic...

<img src="https://user-images.githubusercontent.com/3793636/76250871-0f131c00-6214-11ea-9618-f8e2f33c1952.png" width="300px" />

**Comment by larahanlon2** [comment]
Oh, I completely missed this. My bad. I guess we can close this issue then.

**Comment by photodow** [comment]
I think we have #1534 opened to address these changes.
