### ISSUE TITLE
TOC losing highlight on scroll

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1630]
## Detailed description

> Describe in detail the issue you're having.

The table of contents is losing the highlight of the current section on scroll 
![TOC-Mar-09-2020 14-55-44.gif](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/a24df063-5eac-4924-847a-61813b8fc9be)

*Note: this can be addressed after v1.5.0*

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Table of Contents

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The current section should remain highlighted 

> What browser are you working in?

Mac > Chrome

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Web simplification

## Steps to reproduce the issue

1. Scroll down the [Learn page](http://ibmdotcom-nextjs-test.mybluemix.net/learn)
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Can you take a look at this problem and let Jeff know who much work it is to fix it?

cc:  @jeffchew

**Comment by RaphaelAmadeu** [comment]
Sure @RobertaJHahn , I'm checking this right now
