### ISSUE TITLE
[CTA] Add Video Type

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1632]
#### User Story
> As a `[user role below]`:
user authoring IBM.com pages

> I need to:
I need to be able to choose video types within my ctas

> so that I can:
share our videos with the right user

#### Additional information
 - [CTA functional specs](https://ibm.box.com/s/ceu99rjzd0e87sm51n9cv550yssockme)

#### Acceptance criteria
 - [ ] CTA component allows for a video type
 - [ ] CTA can open videos
 - [ ] CTA copy can show meta information of video

**Comment by RobertaJHahn** [comment]
This is a duplicate of issue (#1111).  Closing
