### ISSUE TITLE
Right to left Arabic research

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1638]
#### User Story

> As a `[user role below]`:
IBM.com user using a right-to-left  language

> I need to:
I need to be able to read the contents properly (right to left) with all design renders in the right orientation

> so that I can:
learn, decide, purchase, and use effectively.

#### Additional information
- Google Material has good guidelines around this.
- Look for IBM's internal guidelines as well
- Find an SME within IBM

#### Acceptance criteria
- [ ] Collate RTL design guidelines from:
   - IBM internal
   - Google Material
   - Others (research)
- [ ] Form a combined guidelines (doesn't have to be final quality. Just enough for devs and designers to start looking at IBM.com Library)

**Comment by wonilsuhibm** [comment]
I'll take this story with #1419 and reduce the estimate since there will be much overlap.

**Comment by ljcarot** [comment]
@jacobottesen-dgc  Adir Pekarevich is willing to be consulted as needed to get us going on how to properly handle right to left in our components. His email is sadir@il.ibm.com and you can mention my name. I'd suggest getting a call scheduled for early this week taking in to account he is in Israel.  Thanks

**Comment by jacobottesen-dgc** [comment]
I talked with Adir last week to gather some resources. I've put together a set of RTL language guidelines in a box note: https://ibm.box.com/s/cqb6c8996x9jsz72n2aqb474vgsy3oag

I'm hoping to get feedback from our team before moving the issue to "Done."
