### ISSUE TITLE
Video player - Lightbox version Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1640]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the Lightbox version of the video player

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - The Kaltura video product is the IBM enterprise solution, branded internally as MediaCenter
 - Functional spec's are provided by the MediaCenter developer, Felipe Zutini Abella
- [Video player functional specs](https://ibm.ent.box.com/file/600045806474)

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by wonilsuhibm** [comment]
I'll take this story with #1419 and reduce the estimate since there will be much overlap.
