### ISSUE TITLE
Masthead IBM logo banding issue

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#165]
Currently, the SVG logo is showing banding issue on some monitors. It depends on the monitor's DPI, but here is a screen capture:

![Screen Shot 2019-10-04 at 6.26.04 PM.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/a97a448b-435a-4ebc-9f4d-cd3db4921c28)

* This is not critical for 1.0.0, but should be fixed before the new masthead hits the glass.

**Comment by kennylam** [comment]
@wonilsuhibm Do you have a better asset you can provide?

**Comment by wonilsuhibm** [comment]
@kennylam I'm attaching a zip file with different sizes. Any chance we can test them out so that we can find the right resolution?

[ibm--8bar-logo--png--sizes.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/3698224/ibm--8bar-logo--png--sizes.zip)

**Comment by RobertaJHahn** [comment]
Closing this issue as the work has been consolidated into the [Centralize logo for ibm.com #411](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/411)
