### ISSUE TITLE
Learn Page Template - The spacing between feature card , card with images and cards is too large.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1654]
## Detailed description

Issue :-  The spacing between feature card , card with images and cards is too large.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4606729a-965f-4dc5-a08b-9d79ce44ea36)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6e7a2f91-1549-4466-b7fd-827b77d12471)

**Comment by RobertaJHahn** [comment]
@jeffchew This is the first bug discussed in the QA meeting earlier today.  I have included it in this sprint and the March release.  A developer has to be assigned.  

cc:  @ljcarot
