### ISSUE TITLE
Learn page Template - The Jump to "icon", is not as per design

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1655]
## Detailed description

Devices - Windows, Mac and Mobile

Issue :- The Jump to icon is different on storybook and Learn Page template.
Note: Working as expected on Storybook.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3d70de4d-24be-482c-89d0-1b08ec3e2151)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/568a9c0c-ab7d-4c04-b4d2-5bb5db29b25f)

**Comment by RobertaJHahn** [comment]
@jeffchew This is the second bug discussed in the QA meeting earlier today.  I have assigned it to Kenny and included in the March release because Kenny said that he has a fixed for this.

cc:  @ljcarot

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn This has been resolved in #1503 

http://ibmdotcom-nextjs-staging.mybluemix.net/learn.html
