### ISSUE TITLE
Component:  Footer (React) - Prod level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1659]
This epic contains links for all of the work required to design and develop the production level version of the footer with the legal changes.    

### Story
As an IBM.com user, I'd like to see the legal footer contents in a more organized way.

**Comment by wonilsuhibm** [comment]
In updating the footer legal bar, please take a look at the following research results from the IBM.com Reboot team, and see if we need to update anything in terms of the content.

– Research findings & trends including links to quantitative reports & user verbatim: https://ibm.box.com/s/j7hdz85wp8gm0g3frnzbpi3s4l1ef0pf
 
 – Readout with Q&A – Video: https://ibm.box.com/s/nnfd3jrza3ni6ia4q2hvknnalulzz9ft
