### ISSUE TITLE
Masthead L1 scroll behavior

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#166]
Upon scroll, the L1 should hide the eye brow and only the bottom 48px should be sticky.![Screen Shot 2019-10-04 at 6.29.41 PM.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/cfc6ac63-2a38-46f2-87a8-c03261a5fff8)

**Comment by larahanlon2** [comment]
Closing this because it's the same at #146
