### ISSUE TITLE
Content blocks, heading not using the correct font weight

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1664]
##  Detailed description

**Describe in detail the issue you're having.**
The heading weight used for `content block` patterns is too heavy. It is rendering at 400 or regular but should be 300 or light.

**Current, in Learn test page and all contentBlocks in Storybook:**
<img width="1281" alt="Screen Shot 2020-03-11 at 11 18 07 AM" src="https://user-images.githubusercontent.com/53093550/76433326-8d91ca00-638a-11ea-9015-df597145ee6e.png">

<img width="1118" alt="Screen Shot 2020-03-11 at 11 20 24 AM" src="https://user-images.githubusercontent.com/53093550/76433258-7652dc80-638a-11ea-895e-efed1eb244dd.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
ContentBlock pattern

**What did you expect to happen? What happened instead? What would you like to see changed?**
Type token should be: $expressive-heading-05
Font weight should be: Light (300)

Desired as per specs:
<img width="1050" alt="Screen Shot 2020-03-11 at 11 05 20 AM" src="https://user-images.githubusercontent.com/53093550/76433467-c2058600-638a-11ea-8ca3-9076aada17c7.png">

**What browser are you working in?**
Chrome

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification

## Steps to reproduce the issue

Open any of the[ ContentBlock patterns in Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default). Compare heading font weight to design specs in [Abstract](https://share.goabstract.com/1953a962-8d60-42cf-9333-06986c6d3015?collectionLayerId=c145462b-fc7a-48c2-b70f-abc8cfca00d8&mode=design).

**Comment by photodow** [comment]
What I was trying to say in the call is that this appears to be a bug on Carbon, and we should open it up over there.

Carbon's code is using the `carbon--font-weight('regular')`

https://github.com/carbon-design-system/carbon/blob/master/packages/type/scss/_styles.scss#L241-L266

We are using `expressive-heading-05` there

https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/styles/scss/patterns/sub-patterns/content-block/_content-block.scss#L35

**Comment by kennylam** [comment]
@larahanlon2 Confirmed the weight is `300`
