### ISSUE TITLE
Link List Top and Bottom Spacing

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1667]
## Detailed description 

After plugging the link list into the [learn template example](http://ibmdotcom-nextjs-test.mybluemix.net/learn) we learned the spacing is off on the LinkList sub-pattern top and bottom.

#### as-is
![image](https://user-images.githubusercontent.com/3793636/76446828-a2278f80-6395-11ea-8661-0a83435d7c7c.png)

![image](https://user-images.githubusercontent.com/3793636/76447743-2c242800-6397-11ea-8b52-5e2c5bb9d79b.png)

#### to-be
![image](https://user-images.githubusercontent.com/3793636/76448697-c0db5580-6398-11ea-89a2-83a43fe1dcd3.png)

![image](https://user-images.githubusercontent.com/3793636/76448612-9ee1d300-6398-11ea-83f8-e8f9a42d4720.png)

## Additional information

- Need to consider adding the spacing correctly the link list, but also do we need to add any spacing to the Layout sub-pattern as well keeping in mind how they all interact with each other.
- There isn't a whole lot of design specs around this. In desktop it's almost as if the top is supposed to somehow line up with the content block copy (can adopters use sameHeight utility somehow?). The gotcha is when the title is 1 line vs. multiple lines.

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu We would like to get this fix in before cutting rc1
