### ISSUE TITLE
Masthead L1: need to adjust all L1 bottom padding

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#167]
1. The title in the dark chip area of L1 is not aligning-bottom to the rest of L1 links.
Current:
![Screen Shot 2019-10-04 at 6.10.25 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/8ba4d2df-11ca-4ac6-a764-5dbef2584b7e)

2. The L1 link items are sitting too far away from the bottom edge of L1. They need less .rem padding.
(see above).

3. Here are my **suggested adjustments**:
- change the L1 link items to have a `padding-bottom` of 0.875rem
- change the L1 title (in dark chip) to have a `padding-bottom`of 1.2rem
- this change seems to align them correctly and also keeps the spacing consistent when the L1 dropdown is open.

See my proposed edits:
![Screen Shot 2019-10-04 at 6.15.50 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/6751ba78-3ec8-4c44-8c2b-39829debc76c)

![Screen Shot 2019-10-04 at 6.24.40 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/27ff0397-496e-46a7-8002-ee15f203916a)

![Screen Shot 2019-10-04 at 6.19.46 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/8db67654-84ee-4507-8dad-e9f367cb3f1c)

**Comment by larahanlon2** [comment]
In addition! If you resize the browser window from small to large you'll see that **Stock Charts** has slightly more space between it and the blue-underline when it's at a larger breakpoint than when it's at the smaller size.

My guess is that when the first issues above are addressed this might resolve...

**Comment by annawen1** [comment]
1. The dark chip L1 title isn't aligning with the L1 links because the L1 links have a 2px transparent border on the `<li />` element that's pushing it up a bit. So maybe we can add some padding to the dark chip title (`$spacing-01`/ `0.125rem`) to even it out.
2. If I do the above, it looks pretty evened out with the dropdown open
