### ISSUE TITLE
Component: Footer Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1670]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Footer`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - Design specs Box folder [sketch](https://ibm.ent.box.com/folder/101562989787) 
- Functional specs issue (#1668 )

 #### Tasks
Ensure the `Footer` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by jacobottesen-dgc** [comment]
Task issue blocked until updates are made to legal copy area on footer.
