### ISSUE TITLE
Pattern:  Update all patterns that use the video player

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1672]
This is an issue that tracks the changes needed for the following patterns to include the `VideoPlayer` as an option:

- ContentBlockSimple
- ContentGroupSimple
- ContentBlockSegmented
- ContentItem

The embedded and lightbox version of the video player will be included in the April release.

Embedded video epic link (#724)
Lightbox video epic link (#1192)

Functional specifications:
- ContentBlockSimple: https://ibm.ent.box.com/file/595011203539
- ContentBlockSegmented: https://ibm.ent.box.com/file/651677070757
- ContentGroupSimple: https://ibm.ent.box.com/file/597415097647
- ContentItem: https://ibm.ent.box.com/folder/101273188385

**Comment by jeffchew** [comment]
I think this should get punted out of v1.6.0. We will need the Media component to be done first before this is done, but wondering what you want to do with this issue in particular @photodow ?

cc: @RobertaJHahn @ljcarot @wonilsuhibm

**Comment by photodow** [comment]
I'm not completely in the know of what 1.6.0 is, but I think it makes sense to hold on some of the video stories like this to wait for the solution pages' media manager and media components to be done.
