### ISSUE TITLE
Content Block Simple no longer renders an image

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1673]
The Content Block Simple pattern in v1.5.0-rc0, is not rendering the picture element.  This is with using the story book version of the image property

http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblocksimple--default

Upon closer inspection of the ImageWithCaption component, it seems to be expecting a customClassName?  But there is no documentation of how to populate this custom class name.

**Comment by RobertaJHahn** [comment]
Determined that this was not a bug during the Sandeep's Checkpoint meeting March 11.
