### ISSUE TITLE
Learn Page:- Top spacing issue with linklist heading

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1680]
Issue:- On learn page link list section is sticking to the leadspace section.

## Additional information
URL:- http://ibmdotcom-nextjs-staging.mybluemix.net/learn.html
OS:- Windows 10, Mac
Browsers:- Firefox, Chrome, Safari, Edge![Link list on learn page.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/877636ac-1f94-43cf-a05d-3c1014e47a57)

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn 
We can close this as padding was added to the LinkList in another issue,
Thanks!
