### ISSUE TITLE
Publish spacing guidelines to Library website

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1684]
### User story

As a designer building new editorial patterns and pages, I need to understand the standard spacing between visual elements so that I can design experiences that fit in the whole IBM.com journeys effectively.

## Notes
- When [this issue](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1681) is complete we will have updated spacing specs.
- Once we have a POV and specs we need to publish to Library site to help adopters

## Tasks
TBC

**Comment by JennySanchez** [comment]
@larahanlon2 Is this a duplication of the EPIC [#357](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/357)?

**Comment by larahanlon2** [comment]
@JennySanchez it is! Sorry, I didn't see that on the board when I search for `spacing`. Will close this issue.
