### ISSUE TITLE
Learn test page, extra padding between last layout pattern and footer

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1687]
## Detailed description

**Describe in detail the issue you're having.**
There is a `96px` spacer between `cards section` and `footer` at the bottom of the Learn test page. Looks like it's coming from the `dotcom shell`.

<img width="1680" alt="Screen Shot 2020-03-12 at 2 46 54 PM" src="https://user-images.githubusercontent.com/53093550/76557974-dde45700-6472-11ea-8c3d-5d87d0ce59a8.png">

<img width="1680" alt="Screen Shot 2020-03-12 at 3 02 12 PM" src="https://user-images.githubusercontent.com/53093550/76558036-f6ed0800-6472-11ea-85a6-c8bab7bdc8cd.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Dotcom shell (TBC)

What did you expect to happen? What happened instead? What would you like to see changed?
Final layout pattern on the page should be flush to the top of the `footer`, unless specified in specs.

Desired for Learn:
<img width="1113" alt="Screen Shot 2020-03-12 at 3 03 16 PM" src="https://user-images.githubusercontent.com/53093550/76558224-4af7ec80-6473-11ea-9bc8-fd23b440d71c.png">

**What browser are you working in?**
Chrome

**What version of the IBM.com Library are you using?**
The latest

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web Simplification

## Steps to reproduce the issue

Scroll to the bottom of Learn test page http://ibmdotcom-nextjs-test.mybluemix.net/learn.html

## Additional information

N/A

**Comment by jeffchew** [comment]
Yes, this is coming from the Dotcom Shell, I'm thinking we should probably remove it entirely, and leave it up to the page level contents to add or not add spacing above the footer.

**Comment by larahanlon2** [comment]
I agree with that approach @jeffchew
