### ISSUE TITLE
Profile developers are requesting adding back the "IBMid" to new IBM.com L0 mastheads (post-login)

### ISSUE THREAD

**Issue by tamcai** [carbon-design-system/ibm-dotcom-library#1692]
### The problem
While redesigning the MyIBM Profile, the developers from the Profile team have noticed the new IBM.com L0/L1 no longer retain the IBMid navigation link on far right. This IBMid only appears once a user has logged in and inside MyIBM environment.

### The solution
Profile developers want to add IBMid to new IBM.com L0/L1 mastheads for post-login experiences (i.e. MyIBM environment)

### Additional information
See attachments of v18 version VS new Carbon version

<img width="1314" alt="Screen Shot 2020-03-12 at 5 55 34 PM" src="https://user-images.githubusercontent.com/33553241/76570176-23148300-648b-11ea-8194-8a9d619ef36b.png">
<img width="1228" alt="v18-masthead-l1" src="https://user-images.githubusercontent.com/33553241/76570174-227bec80-648b-11ea-9717-332073e70b0c.png">

**Comment by tamcai** [comment]
<img width="1314" alt="Screen Shot 2020-03-12 at 5 55 34 PM" src="https://user-images.githubusercontent.com/33553241/76570269-57883f00-648b-11ea-824d-a80da22b2e50.png">

**Comment by JennySanchez** [comment]
@larahanlon2 FYI.

**Comment by larahanlon2** [comment]
I chatted with Tam about this and asked that he open a feature request. We don't currently support this in the masthead. I think we need to understand some of the following:

- What do users do with this ID?
- Why is it exposed in the masthead – can it be within the profile dropdown in L0?
- Does the entire ID need to be displayed at all times?
- Does this show up anywhere else across ibm.com?

Before Scott left he was working on some "wedding cake" explorations that included IBM ID.

**Comment by RobertaJHahn** [comment]
The Digital Design Squad has to reflect on the design and implementation options before scheduling the work at a later date.  In the meantime, please proceed without out this feature.

**Comment by RobertaJHahn** [comment]
Wonil will talk to Charlie Douglas about including this feature in Profile.

**Comment by RobertaJHahn** [comment]
Charlie Douglas agreed to include this feature in Profile.  Designs are in progress.  Closing this issue for the Digital Design Squad.
