### ISSUE TITLE
[Footer]: Adds White Space Below in mobile

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#170]
## Detailed description

It looks like the footer is currently adding a large amount of white space to the bottom of the page below it on the smallest breakpoint due to the accordion not hiding its content properly.

![image](https://user-images.githubusercontent.com/3793636/66337043-fa98c380-e903-11e9-8032-ec9bdc839480.png)

I think if we can just add `overflow: hidden;` to the `.bx--accordion` class then it'll fix the issue.

## Steps to reproduce the issue

1. Go to https://ibmdotcom-react.netlify.com/iframe.html?id=dotcom-shell--default
2. View at `sm` breakpoint.
3. Scroll to the bottom of page.

## Additional information

- We should also look into seeing if this is something we should contribute back to carbon as well.

**Comment by jeffchew** [comment]
@oliviaflory @annawen1 please triage accordingly.
