### ISSUE TITLE
Learn Page:- Clicking on back button in browser, mismatch in page focus and table of content scroll indicator 

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1703]
Issue:- when user clicks on any card or cta, user is navigated to respective landing page but on clicking back button(browser) here page focus stays on where user clicked but table of content scroll indicator (blue line) always sticks to first title

## Steps to reproduce the issue

1. Enter the url in the browser
2. Click on 'Learn More' card.
3. Click on 'Content Block - With Media'
4. Click on 'Feature Card'.
5. Once user is navigated to feature card link, click on browser back button.
6. Check the page focus and table of content blue tick.

## Additional information

URL:- http://ibmdotcom-nextjs-staging.mybluemix.net/learn.html

OS:- Windows 10, Mac
Browsers:- Chrome, Firefox, Safari, Edge![Back button issue on learn page.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/98ccf5c0-3b4a-4791-b680-a33b7ce52b7d)

**Comment by RaphaelAmadeu** [comment]
@chetankan 
Could you please test this again using our canary staging? thanks!
https://ibmdotcom-react-canary.mybluemix.net/
