### ISSUE TITLE
March 2020 v1.5.1 Patch release plan

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1711]
# Timeline

- **March 19th, 2020**: Branch created
- **March 19 - 27, 2020**: Release Candidate(s) and testing
- **March 30 2020**: Full Release

## Hot fixes
- **Table of contents - Accessibility - Focus doesn't switch to the section heading on click of table of content (anchor) links** (#1395 )
- **Feature card - Content Text is not readable, text color and the background is same** (#1622 )
- **Layout containing CardSectionImages is missing the card alignment if the image ratios are different between cards.** (#1721)
- **Link List Subpattern's CSS is getting overridden by selectors from other DDS components** (#1733)

**Comment by jeffchew** [comment]
Release completed: https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.5.1
