### ISSUE TITLE
Create Northstar r147 Next Release

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1714]
#### User Story

> As a `[user role below]`:
Release manager

> I need to:
Deploy the `Next` Release R147 of Northstar v18 to the EI server

> so that I can:
adopters can test R147 before it is deployed live

#### Additional information

- Release Management Playlist: https://ibm.ent.box.com/notes/498576715683, under `Next Deployment`
- Release Plan: https://github.ibm.com/webstandards/digital-design/issues/1855

#### Acceptance criteria
 - [x] R147 `next` deployment successfully completed
- [x] Release announced on #ibm-digital-design slack channel

**Comment by jeffchew** [comment]
Release has been created and announced.
