### ISSUE TITLE
IBM.com style model research part 2

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1718]
### Notes

In order to support our adopters and help them make the best decisions re: style models for ibm.com, we need to identify and communicate design research best practices.

### Problem

When designers are tasked with designing ibm.com experiences, they don't always know where to start. Design research can provide insights and best practices for designers to follow and apply to their work. IBM has robust user research tools but less design (visual, UX, interaction) guidelines.

### Additional Information
 - This issue is for additional research work.  Additional research issues are:  Issue (#1538)
      

### Tasks
1. Map out design research flow/steps 
2. Identify existing tools and resources that designers can use to get started
3. Propose new methods or tools that we need to provide
4. Consider how this fits into style model, library, system etc.

**Comment by larahanlon2** [comment]
Continuing this work in [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1584117576415?sender=larahanlon9022&key=6cb85be5-459b-407a-9233-0ddadc7cd438).

**Comment by larahanlon2** [comment]
Similar to last sprint for part 1, I'm considering my work for this part 2 story complete (1 story point). This work will need to continue.
