### ISSUE TITLE
Layout containing CardSectionImages is missing the card alignment if the image ratios are different between cards.

### ISSUE THREAD

**Issue by jpathan-dev** [carbon-design-system/ibm-dotcom-library#1721]
We are using the following sass imports for the pattern.

import '@carbon/ibmdotcom-styles/scss/patterns/sections/card-section/_card-section.scss';
import '@carbon/ibmdotcom-styles/scss/patterns/sub-patterns/content-section/_content-section.scss';

<img width="1440" alt="Screen Shot 2020-03-18 at 9 12 17 AM" src="https://user-images.githubusercontent.com/62308387/76964496-35624700-68f9-11ea-8e4c-465bd4bafe87.png">

**Comment by jeffchew** [comment]
Hi @jpathan-dev , change to the following import:

```
@import '@carbon/ibmdotcom-styles/scss/patterns/sections/card-section/index';
```

**Comment by kexuibm** [comment]
> @import '@carbon/ibmdotcom-styles/scss/patterns/sections/card-section/index';

Hey Jeff, I think the issue is that that path does not exist in V1.5.0 for the card section.  There is no index.scss in that directory.

**Comment by jeffchew** [comment]
> > @import '@carbon/ibmdotcom-styles/scss/patterns/sections/card-section/index';
> 
> Hey Jeff, I think the issue is that that path does not exist in V1.5.0 for the card section. There is no index.scss in that directory.

Yes Ke, realized that there's a mismatch in the documentation so we will need to fix that on our end.

We are looking into this and might need to be a code fix for the aspect ratio to work properly. @kennylam is looking into this.
