### ISSUE TITLE
Locale Selector: Run Accessibility on new Locale Selector

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#1726]
#### User Story
As a developer of the Locale Selector functionality

I need to:
have a version of the component that has been tested for accessibility compliance as well as on multiple browsers and platforms

so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information:
use this page for testing the locale selector in the footer at the bottom of the page:http://ibmdotcom-nextjs-test.mybluemix.net/learn.html

<img width="954" alt="imageoflocaleselector" src="https://user-images.githubusercontent.com/23237857/76989274-7881e180-691c-11ea-8a5c-21aeed7f72db.png">

 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)

#### Acceptance criteria
- [ ] Accessibility testing is complete.

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you please send the information along to Ram for testing.  Thanks.

**Comment by Praveen-sr** [comment]
@RobertaJHahn Yes, informed 'Ram' and provided necessary links. Thanks!
