### ISSUE TITLE
CardSection pattern is missing the card alignment if the short copy text is longer or shorter than other cards.

### ISSUE THREAD

**Issue by jpathan-dev** [carbon-design-system/ibm-dotcom-library#1727]
We are using the following sass imports for the pattern.

import '@carbon/ibmdotcom-styles/scss/patterns/sections/card-section/_card-section.scss';
import '@carbon/ibmdotcom-styles/scss/patterns/sub-patterns/content-section/_content-section.scss';

<img width="1392" alt="Screen Shot 2020-03-18 at 3 12 13 PM" src="https://user-images.githubusercontent.com/62308387/76998217-141a4e80-692b-11ea-8f54-fbf1c878f0a3.png">

First card is not aligned with the other cards.

**Comment by jeffchew** [comment]
Hi @jpathan-dev , are you initializing the client-side code for this pattern? We have a utility to detect same height of content that needs to be loaded in after the page loads.

cc: @annawen1 @photodow

**Comment by jpathan-dev** [comment]
@jeffchew, I am importing card section images pattern and passing the required props to that pattern and I checked with @mkothur last week https://codesandbox.io/s/lingering-mountain-nlos7, he provided the code sandbox and it is working fine there, but not after ingesting the pattern in drupal.

**Comment by jeffchew** [comment]
> @jeffchew, I am importing card section images pattern and passing the required props to that pattern and I checked with @mkothur last week https://codesandbox.io/s/lingering-mountain-nlos7, he provided the code sandbox and it is working fine there, but not after ingesting the pattern in drupal.

Understood. My question is the way that drupal is injecting the pattern, is it initializing the client-side react code after page load? That will be necessary for the pattern to set the heights properly.

**Comment by jpathan-dev** [comment]
Yes, it is initializing the client-side code.

**Comment by photodow** [comment]
@jpathan-dev do you have a reduced test can? Can you duplicate the issue on codesandbox? Do you have somewhere we can go to look at the code, or at least see it not working? We need more information in order to help you troubleshoot this problem.

**Comment by jeffchew** [comment]
Hi @kexu @jpathan-dev , can we have a meeting to discuss this one? We are fairly convinced that the client-side code is not activating properly on the drupal side as this works fine for our standard Javascript/Storybook/Node.js environments.

cc: @kennylam @ljcarot @annawen1 @photodow @RobertaJHahn

**Comment by jeffchew** [comment]
Speaking with Drupal team, this is identified as a FE architectural implementation issue where client-side React is not getting bootstrapped properly. Will keep this open as a support issue, but isn't targeted for any release.

cc: @RobertaJHahn @ljcarot

**Comment by RobertaJHahn** [comment]
Closing this issue as Drupal has ingested all of the Learn page patterns and moving forward on their MVP release.
