### ISSUE TITLE
Link List Subpattern's CSS is getting overridden by selectors from other DDS components

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1733]
Using v1.5.0, it looks like for the Link List sub-pattern  2 issues are happening:'

**1.  Some CSS selectors is being overridden by the CSS selectors of other DDS patterns and subpatterns.**

For example, the style of the link text for each of the links in Link List:
.bx--link-list .bx--card__copy p

This style is being overridden by 2 other style selectors:

From the TOC sub-pattern:
.bx--tableofcontents .bx--tableofcontents__content p

And from the Content Block Simple Pattern:
.bx--card__CTA .bx--card__copy p

Another example is the class:
.bx--link-list .bx--card {
    max-width: none;
}

It is getting overwritten by the class:
.bx--card__CTA {
    /* max-width: 20rem; */
}

However this style does not seem to exist in the built css file for Link List.

**Comment by RobertaJHahn** [comment]
@kexuibm  Can you provide a screen shot?
