### ISSUE TITLE
Table of contents, focus border is not going away on active item

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1737]
## Detailed description

**Describe in detail the issue you're having.**
When clicking on the TOC, the 2px focus border appears but does not disappear when the page moves to that selected section. 

<img width="1406" alt="Screen Shot 2020-03-19 at 3 57 06 PM" src="https://user-images.githubusercontent.com/53093550/77109613-97ef3c00-69fa-11ea-90a6-f43dd8cb7c04.png">

![TOC-border](https://user-images.githubusercontent.com/53093550/77109697-ccfb8e80-69fa-11ea-84d3-2658d529848a.gif)

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Bug

**Is this issue related to a specific component?**
TOC 

**What did you expect to happen? What happened instead? What would you like to see changed?**
The 2px border should not remain once the page and indicator reaches the selected section. Only the blue sidebar/scroll indicator should remain on an active item.

Desired:
<img width="1408" alt="Screen Shot 2020-03-19 at 4 02 12 PM" src="https://user-images.githubusercontent.com/53093550/77109840-0502d180-69fb-11ea-9bbe-6d7a51b0a953.png">

**What browser are you working in?**
Chrome

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification / IBM.com reboot

## Steps to reproduce the issue

Test this on the Learn page: http://ibmdotcom-nextjs-test.mybluemix.net/learn.html

## Additional information

The behavior is correct when scrolling on the page. This is only a problem when clicking through TOC items.

**Comment by larahanlon2** [comment]
FYI @ltitle

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Can you take a look at this issue.  Linda and Jeff would like to talk to you about whether "fixing" this problem will present accessibility issues.

cc:  @ljcarot @jeffchew

**Comment by RobertaJHahn** [comment]
Ram will investigate and provide an update.

**Comment by RobertaJHahn** [comment]
This behavior is a by product of the Accessibility fix included in issue (#1395).  Closing this design issue.
