### ISSUE TITLE
Error after adding @carbon/ibmdotcom-react to a new application 

### ISSUE THREAD

**Issue by markewallace** [carbon-design-system/ibm-dotcom-library#1739]
## Summary
Are there instructions on how to add `@carbon/ibmdotcom-react` to a new application created with create-react-app
Getting start just includes one instruction i.e. `npm i @carbon/ibmdotcom-react` but this is sufficient e.g. you also need to install `node-sass`
But even with that I’m seeing SassError: `File to import not found or unreadable: carbon-components/scss/globals/scss/vars`

**Comment by ljcarot** [comment]
Is this okay to close after slack discussion?

**Comment by elizabethlumban** [comment]
hi @markewallace - would you be able to share the fix for this? I'm encountering the same problem.. thanks in advance

**Comment by jeffchew** [comment]
> hi @markewallace - would you be able to share the fix for this? I'm encountering the same problem.. thanks in advance

Hi @elizabethlumban , let us know if you need assistance, you can either open a question issue or reach out to us on #ibm-digital-design in Slack.
