### ISSUE TITLE
CSS support issues in translated pages with Right to Left Languages

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1744]
V1.5.0

IBM.com pages are often translated into Right to Left languages (e.g Arabic).  The approach to this translation in V18 Northstar has been to invert the experience of each band and component.

So for example here is an US English and Arabic page on IBM.com using V18:

https://www.ibm.com/analytics/open-source
https://www.ibm.com/sa-ar/analytics/open-source

However, when doing the same exercise using the DDS Patterns, we see a number of RTL support styling issues in the following patterns:

- Masthead Header
- Table of Content
- Card Section
- Image Card Section

Here are 2 example Learn Pages in English and Arabic:

https://ode15.cms.ibm.net/analytics/ams-learn-page-mar4
https://ode15.cms.ibm.net/ar/analytics/ams-learn-page-mar4

Please note the styling differences in the arabic version for the above 4 patterns.

****Task****
 - DDS Developer will review the code, make the override style changes and perform a visual review

**Comment by ljcarot** [comment]
@kexuibm At this time we are not yet supporting Right to Left languages.  The plan for RTL support is later in the year, by July/August timeframe, and that is subject to resource availability to focus on it.  We will change this to Feature Request since it's not a bug.
