### ISSUE TITLE
Table of Contents scrolling behavior study

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1746]
#### User Story

> As a `[user role below]`:
As a DDS designer

> I need to:
study the table of contents scrolling behaviors

> so that I can:
design the Table of Contents behavior that provides the best user experience

#### Additional information

 - [Tocbot](https://tscanlin.github.io/tocbot/)

#### Acceptance criteria
 - [ ] Analyze and document the options
 - [ ] Provide input to the design specifications

**Comment by wonilsuhibm** [comment]
An example on IBM.com. This one shows how scrolling-back-to-the-top behavior should look like—as soon as the page reaches the previous section, the blue bar jumps to the associated heading.
https://www.ibm.com/products/help

**Comment by wonilsuhibm** [comment]
Shixie's motion prototype that demonstrates the expected behavior:
https://ibm.box.com/s/hgvx8bjwto75efiz72fba4ukh29gbzgx

**Comment by jeffchew** [comment]
Here is from an older prototype from a previous project: 
https://gvocale.github.io/jpm-content-animation-latest/
