### ISSUE TITLE
Content Block Media is missing an autoid attribute for optional CTA

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1747]
In V1.5.0, in the Content Block Media Pattern, there is an optional content group CTA:
 <div class="bx--content-group__cta-row">

However there is no data-autoid attribute for this Group CTA, so our ingestion logic cannot make this markup optionally renderable.  Can you please fix it by adding an auto-id attribute to this element?

**Comment by RobertaJHahn** [comment]
Defect review meeting:  This feature request (they would debate whether this is a feature request or not) is needed in MVP.  This missing data-autoid affects the analytics.  Drupal can go into Production without this fix, but that will create technical debt on both their team and the Analytics teams.  Requesting that we reconsider and include this fix in a patch.  Delivery date of the patch would be Friday, April 3.
