### ISSUE TITLE
Pattern: Video Player - The logo of the video player is clickable but doesn't have any action.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1748]
## Detailed description
Browsers - Chrome, Firefox, Safari

Issue :- The logo on the left corner of the video player is clickable and has focus but doesn't have any action.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/53034da5-ff1e-4a9d-9b75-cb87a675c4c4)

**Comment by RaphaelAmadeu** [comment]
This bug is happening on the embed player, so we can't fix it on our end.
I think we can close this issue as well.
cc: @ljcarot @RobertaJHahn @jeffchew
