### ISSUE TITLE
Content Block Media styles being overridden by TOC styles

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1749]
V1.5.0

The Content Block Media has a style for it's Primary CTA heading:

.bx--card--inverse .bx--card__heading, .bx--card--inverse .bx--card__copy {
    color: #fff;
}

However on the style of the heading is being overridden by CSS from other DDS patterns such as:

Table of Contents
.bx--tableofcontents .bx--tableofcontents__content h2, .bx--tableofcontents .bx--tableofcontents__content h3, .bx--tableofcontents .bx--tableofcontents__content h4, .bx--tableofcontents .bx--tableofcontents__content p {
    color: #161616;
}

**Comment by jeffchew** [comment]
@RaphaelAmadeu does this fix in https://github.com/carbon-design-system/ibm-dotcom-library/pull/1736 already address this?

**Comment by RaphaelAmadeu** [comment]
@jeffchew,
Yeah, the selector that must be interfering was the P selector, and this was removed on the another ticket,
Thanks!

**Comment by ljcarot** [comment]
Do you know the other ticket number @RaphaelAmadeu

**Comment by jeffchew** [comment]
> Do you know the other ticket number @RaphaelAmadeu

@ljcarot this is the related issue: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1733

cc: @RaphaelAmadeu

**Comment by RobertaJHahn** [comment]
Closing as this work is a dup of (#1733)
