### ISSUE TITLE
Pattern: Table of Contents - Update the functional specs for focus change to the content heading

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1753]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
have updated functional specifications available for the Table of Contents

> so that I can:
create test the Table of Contents Accessibility focus fix

#### Additional information

 - For background, see the Table of Contents focus issue (#1395)
 - This fix is included in Pull Request (#1752)

#### Acceptance criteria
 - [ ] Updated functional specification documentation added to the IBM.com Library folder in Box

**Comment by photodow** [comment]
@jeffchew updated `2a`, and `6` to set focus after smooth scrolling is finished.

https://ibm.box.com/s/3jy1tuk7zz6do61jfj55n7x7b2jpbzou

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
