### ISSUE TITLE
Error page redesign: cupcake vis design final

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#176]
### User story
As a user of IBM.com, I need to know when an http error has occurred, and what to do next in order to continue with my journey.

### Notes
- This story is to redesign the existing http error page template to IDL and Carbon specs.

### Acceptance criteria
- [ ] final design has been completed
- [ ] final design has been approved

**Comment by RobertaJHahn** [comment]
duplicate of [issue 350](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/350)  Closing
