### ISSUE TITLE
Component:  Locale selector design spec updates

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1760]
As an adopter or developer on the DDS team I need to know the design specs for `Locale Selector?` component. 

#### Additional Information
- [Locale Selector Box Folder](https://ibm.ent.box.com/folder/82255256134)

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Locale Selector ` design and specs
- [x] Create a Box folder for `Locale Selector ` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [ ] Links or documentation that needs `Locale Selector ` specs are updated

**Comment by larahanlon2** [comment]
Things needing updates in the `locale selector` [visual spec](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8):

- [ ] Update copy to reflect copy deck
- [ ] Double-check / add interactive states including active on language list
- [ ] Replace eyebrow with new link with icon compontent (review with design before finalizing)
- [ ] Cross check with functional specs
- [ ] Cross check with Storybook

**Comment by larahanlon2** [comment]
Ran into a few issues closing this issue out. Mainly: Sketch library updates messed up many layer styles. Hopefully fixed. 

### New Sketch file with specs `v1.2.0` can be found [here](https://ibm.box.com/s/ep91v9wq3m12pj0dv8n04p7m39n63krb).
### PDF of the same can be found [here](https://ibm.box.com/s/6950uz0hw76wb0or5wd4e1rnxa46wqei).
 —

**Changelog:**
– Original warning overlay is hidden from artboards
– Copy is updated
– Cards refer to card-component for specs
– HEX values removed
– UI tokens unlinked from expressive library (Carbon only)
– Internal padding rules for breakpoints as per dev added 


The outstanding item I did not get confirmation on is whether to replace the `eyebrow` to `link with icon` component following Olivia's recent design work #2146. It would make sense to keep things consistent and reusable from a system perspective. Olivia and I agree but would love @wonilsuhibm 's input here.

For reference. From this:
<img width="753" alt="Screen Shot 2020-05-19 at 10 19 23 AM" src="https://user-images.githubusercontent.com/53093550/82714079-2da58280-9c5b-11ea-9b17-54839e11d0b1.png">

to this? (alignment and copy FPO)
<img width="761" alt="Screen Shot 2020-05-19 at 10 19 31 AM" src="https://user-images.githubusercontent.com/53093550/82714090-35652700-9c5b-11ea-90ab-3540264f35a7.png">

**Comment by larahanlon2** [comment]
Wonil agreed to with the blue `link with icon `component instead of the original gray eyebrow. I'll make the updates to the file today and close this issue.
