### ISSUE TITLE
Masthead logo positioning

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1761]
The IBM logo in the new masthead is positioned outside of the content area in the medium breakpoint. See the screenshot in the comment below.

**Comment by RobertaJHahn** [comment]
@wonilsuhibm Could you add the screenshot for this bug?

**Comment by kennylam** [comment]
@RobertaJHahn Here is a screenshot. It happens where there is no navigation in the masthead (no nav means no hamburger).

![image](https://user-images.githubusercontent.com/909118/77427119-33dac800-6dac-11ea-9b00-9f8234285c6c.png)

**Comment by wonilsuhibm** [comment]
@kennylam Thank you. The logo should be aligned to the magenta line in the above screenshot.
