### ISSUE TITLE
Callback on DotcomShell.getDotcomShellWithData() issue in VueJS environment

### ISSUE THREAD

**Issue by tefiggins** [carbon-design-system/ibm-dotcom-library#1763]
## Detailed description
I am attempting to use your Vanilla **DotcomShell** componebnt from '@carbon/ibmdotcom-vanilla' with a VueJS project.   I'm following the example in the Readme  (https://ibmdotcom-vanilla.mybluemix.net/?path=/story/components-dotcom-shell--default)

What seems to be happening is that the:
`DotcomShell.getDotcomShellWithData({content, ...dotcomShellProps});`
doesn't appear to be returning a Promise.

In other words, it do not seem to await but to forge ahead to the next step.  I even attempted to call is in a different fashion:
`DotcomShell.getDotcomShellWithData({
	content,
	...dotcomShellProps,
}).then(html => {
	const yourapp = document.getElementById('app');  
	console.log(yourapp);
	yourapp.innerHTML = html;
	console.log(html);
	DotcomShell.init(yourapp);
	Root =new Vue({
		el: '#appcontent',
		template: '<App/>',
		i18n,
		store,
		components: { App },
		router
	})
});`

and **it never makes it into the .then clause** ... not console.log outputs.

Using chrome browser on a Macbook Pro: Version 80.0.3987.132 (Official Build) (64-bit)

In package.json
```
     "@carbon/ibmdotcom-vanilla": "^0.5.0",
    "@carbon/icon-helpers": "^10.6.0",
    "@carbon/type": "^10.9.2",
```
My project is a VueJS project and since you do not have this component in you Vue-based library previous use you html-base V18 library and now attempting to replace with this Vanilla Carbon-based one.

For a simple base example of what I was attempting to do you can reference  this stackoverflow link (with the following flow descriptions:
https://stackoverflow.com/questions/58972232/what-is-the-purpose-of-main-js-app-vue-in-vue-app

- I have a **index.html** with a <div id=app></div> tag 
- Added code in **main.js** to init the DotcomShell against the id=app tag
- Note the content of the DotconShell would be a simpe <div id=appcontent></div> tag
- Then I can instantiate my VueJS application to the id=appcontent tag.

Previously, I was instantiating VueJs application against id=app in index.html file with other V18 header/footer around it.  That worked well, thus my approach above.

Without the Promise being returned, the code continues and there is not id=appcontent to connect the VueJS app to.  Futhermore the nextwork tab n the Inspect Gui shows that the call in DotcomShell.getDotcomShellWithData() comes **after** the a code runs to attempt the to connect the VueJS application  due it not awaiting (contining on ahead).

## Steps to reproduce the issue

- Described above in the details...  see if you can get DotcomShell callback code to run.

## Additional information
- Work with Developer of this libary who ask me to open this issue after a show and tell on Webex.

**Comment by jeffchew** [comment]
Had a working session along with @kennylam , I believe the next steps is to build a codesandbox example with a `Hello World` VueJS application with our vanilla dotcomshell in place. We should also add this as an example application in our READMEs.

**Comment by RaphaelAmadeu** [comment]
@jeffchew ,
I worked with @kennylam , and he helped me to create a working environment with `Vue` and the `DotcomShell`,
We couldn't make it into codesandbox, but I built this repo instead, they can be used as a reference,
https://github.com/RaphaelAmadeu/vanilla-vuejs-dotcomshell

Thank you!

**Comment by ljcarot** [comment]
@tefiggins Not sure if you are getting notifications from Git or no but see notice above from April and let us know if you are still having any issues cc: @jeffchew
