### ISSUE TITLE
Locale selector:- Focus Order - Select region modal dialog

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1768]
Issue: - 1. Screen reader is not identifying the Scroll bar in tab/shift tab navigation. Instead, when focus reaches here, announces the entire dialog content. (this issue is not in iphone)
2. After activating the button that triggers the dialog, Screen reader focus still remains on the button itself. Hence the user does not know that the dialog is displayed.
3. After closing the dialog by pressing the "close button", Screen reader focus is not set back on the triggering control. 

Expected :- 1. Provide aria scrollbar role and the related properties to make it screen reader accessible. Please refer the following link for more information: 
https://developer.paciellogroup.com/blog/2016/02/short-note-on-improving-usability-of-scrollable-regions/ 
2. Once the dialog is displayed, set the focus on the first interactive element in the dialog. 
3. Set focus back on the triggering control after closing the dialog. 

URL:-  http://ibmdotcom-nextjs-test.mybluemix.net/learn.html

**Comment by kennylam** [comment]
@chetankan @Praveen-sr @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2093
