### ISSUE TITLE
Accessibility - Video Player - iPhone voice over - controls container (play/pause button, slider, skip back 15 sec button In normal screen)

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1771]
## Detailed description

Issue :- when we do right swipe from large play button, the focus is not reached to mentioned controls

Expected - focus should reach each and every elements and operable with screen reader.

**Comment by RobertaJHahn** [comment]
Moving this issue to sprint 20-08.  The dev work has to be done during the first week of the sprint to include it in release v1.6.0.

**Comment by RaphaelAmadeu** [comment]
This issue is on the embed player, so we can't fix it on our end,
We can close this.
CC: @ljcarot @RobertaJHahn @jeffchew

**Comment by jeffchew** [comment]
Removing from `1.6.0` release.
@ljcarot @RobertaJHahn are there labels we want to remove from here? Linda, are you consolidating this list for Jerry?

**Comment by ljcarot** [comment]
Yes, I will include this in items to send to Jerry. Closing this now.
