### ISSUE TITLE
Accessibility - Locale Selector - Screen reader is not identifying this (back button) control. Hence the user does not know its presence. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1777]
## Detailed description

Issue - 
Select by location or by language : back button - Screen reader is not identifying this control. Hence the user does not know its presence. 

Expected -
Screen reader should identify this control with appropriate Role/Label. And also this has to be made keyboard operable.

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr 
Could you please test the back button usage again?

Thank you!

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Yes, ram verified on the link you provided, but Screen reader is not identifying the link in each card, all are announced only as text.

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Sure, can you provide link to re test? 
Thanks!

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr 
You can use staging for the test,
Thanks!

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Now screen reader (jaws) is identifying the button role. But, the label is given as "select region". Since the triggering control also has the same label, this is confusing. 
Hence recommend to label this as "back".
Voiceover iPhone: VO is not identifying the button role still.

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr 
We updated this component some days ago,
we thought that hardcoding the label with 'back' is not a good approach as it would not adapt for language changes,
Can you test this again please?
Thanks!

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Re tested this, now screen reader is announcing the label as "select region" which is inappropriate. To avoid confusion, the label can be given as "Go back to Select region" ?

**Comment by wonilsuhibm** [comment]
I suggest "Select a different region" for the aria-label for the back button.

**Comment by ljcarot** [comment]
Since the icon is suggesting go back, how about 'Go back to select a different region'.
