### ISSUE TITLE
Leadspace background image not rendering properly

### ISSUE THREAD

**Issue by diegomarcuz** [carbon-design-system/ibm-dotcom-library#1780]
## Detailed description

> Describe in detail the issue you're having.

* Leadspace background image is not covering full width on big resolutions, like 2560 X 1440

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

* Bug

> Is this issue related to a specific component?
* Leadspace with images

> What did you expect to happen? What happened instead? What would you like to
> see changed?

* Leadspace needs to cover full width.

> What browser are you working in?
* I have tested on Chrome 80, Firefox 74 and Safari 13

> What version of the IBM.com Library are you using?
*  @carbon/ibmdotcom-react": "^1.6.0-alpha.3070",
*  @carbon/ibmdotcom-styles": "^1.6.0-alpha.3066",
*  @carbon/icons-react": "^10.9.1",
*  @carbon/pictograms-react": "^10.9.0",

## Steps to reproduce the issue

1. Step one
* Remove for bx--leadspace class: 
    * max-width;
    * margin-right;
    * margin-left.

2. Step two
* Add for bx--leadspace class:
   * background-size: cover;
   * background-position: center;
   * background-repeat: no-repeat.

## Additional information

![Screen Shot 2020-03-24 at 12 03 21](https://user-images.githubusercontent.com/37422384/77440831-81b0f980-6dc7-11ea-909c-a1b48eead967.png)

**Comment by jeffchew** [comment]
@diegomarcuz can you provide the image url you're using?

**Comment by diegomarcuz** [comment]
Sure, http://webdev01.webmaster.ibm.com/events/testing-images/2625-801-leadspace.jpg

**Comment by RobertaJHahn** [comment]
Reach out to Diego to have him use Backgound cover for the image.  DDS dev should also investigate why we are not using the image component.  @annawen1 @andysherman2121
