### ISSUE TITLE
Pattern: Create the Table of Contents scrolling behavior functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1783]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Table of Contents` functional specs updated

> so that I can:
so that I can properly code the `Table of Contents` pattern for my web site

#### Additional information

- Design Study issue (#1746)  

#### Acceptance criteria
 - [ ] Updated `Table of Contents` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by ellenchoi1** [comment]
Updated functional specs (v 1.3) uploaded to box: https://ibm.box.com/s/yfuicifhfeaefp4rl0pp62dpeacr18ry

@RobertaJHahn I don't think we currently have a dev ticket for this work. Could you create one? We need to make a modification to the scrolling behavior of the pattern and there may be some other minor modifications as well.

**Comment by RobertaJHahn** [comment]
@ellenchoi1 Dev and Prod QA issues are created.  Added the review of these func specs to the Tuesday engineering meeting agenda for sizing.  Thanks.
