### ISSUE TITLE
Component: Vanilla Footer QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1786]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Vanilla Footer`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - [Box folder with designs and functional specs](https://ibm.ent.box.com/folder/101562989787)
 - Design issue (#860)
 -  Dev issue (#356)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
This testing can not begin until the React version is finished.   Development for the visual changes are included in sprint 20-09.  The Production level changes may be finished in sprint 20-10.

**Comment by RobertaJHahn** [comment]
@andysherman2121 The Vanilla footer was developed at the end of 2019.  I found the PR, but I am not sure whether those are the correct links for Praveen and Chetan to use for their testing.  Could you provide the URL for the environment they can use for their testing?  Thanks.

**Comment by andysherman2121** [comment]
@RobertaJHahn 
This is the link they should use for in sprint testing - https://ibmdotcom-vanilla-canary.mybluemix.net

During the code freeze they should use this link - https://ibmdotcom-vanilla-staging.mybluemix.net

**Comment by RobertaJHahn** [comment]
7/7/2020:  All testing is finished.  Closing.
