### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/ibm-dotcom-library#182]
### The problem
Need an alert component to list and manage notifications from different sources and different level of importance.

### The solution
Upon page load an alert indicator is shown in the banner, to indicate there are one or multiple notifications of interest related to the page content.

### Additional information
These notifications are from various sources, and are specific to each IBM products.

They can be filtered.
User can optimize from various settings.

![image](https://user-images.githubusercontent.com/11738743/66517482-39b84780-eab1-11e9-9146-ce1f24cb9022.png)

**Comment by ljcarot** [comment]
@jeffchew @mattrosno this sounds like an enhancement for core Carbon for use in app.  do you agree?

**Comment by aiproulx** [comment]
@ljcarot This component is to be used in IBM Knowledge Center. Wonil suggested I logged it here. If it needs to be moved (or recreated) to another git repo, let me know.

**Comment by jeffchew** [comment]
Moving this to discuss in our next triage meeting.

cc: @ljcarot @wonilsuhibm @RobertaJHahn @annawen1 @oliviaflory

**Comment by ljcarot** [comment]
Closing this issue in the dotcom.  This should be requested in Carbon's git since this is request for behavior within the product itself.  https://github.com/carbon-design-system/carbon/issues/new/choose
