### ISSUE TITLE
Pattern: Update the Content block - segmented functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1821]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content block - segmented` functional specs 

> so that I can:
so that I can properly code the `Content block - segmented` component that meets the Solution template requirements

#### Additional information

  - Design Issue (#1988  )
 - Development issue (#1845 )

#### Acceptance criteria
 - [x] Documented `Content block - segmented` Link functional specifications
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints
- [x] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
@jeffchew @wonilsuhibm @ljcarot updated functional specs. Only update I made was I added `3.3 CTA`. I updated the dev story #1845 as well.

https://ibm.box.com/s/sjslu5d3le51s7w5q0ucponqe0cpuuuq

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
