### ISSUE TITLE
Pattern: Update the Content block functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1823]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content block` functional specs 

> so that I can:
so that I can properly code the `Content block` component that meets the Solution template requirements

#### Additional information

  - Design Issue (#1989  )
 - Development issue (#1847 )

#### Acceptance criteria
 - [x] Documented `Content block` Link functional specifications
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints
- [x] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
Updated content block's functional specs. I added button as a style option for content block cta under bullet point 4.

https://ibm.box.com/s/kw9b8eal4gi1yqmnautekub0djekcrof

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
