### ISSUE TITLE
Pattern: Update the Content item functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1824]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content item` functional specs 

> so that I can:
so that I can properly code the `Content item` component that meets the Solution template requirements

#### Additional information

 - Design Issue (#1990 )
 - Development issue (#1848)
 - Solution page designs [[Sketch](https://ibm.box.com/s/npvpwscwolvoevrpxnkgzsavp5o5d87s)]
 - Content item [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-contentitem--default)] [[functional specs](https://ibm.box.com/s/b64hvlc187xs653x07loh9zwh5nl8arf)] [[folder](https://ibm.box.com/s/xfm17x7dwbe4z7kjk482b8hbpjasft7o)]

We are adding in the capability to add the video player into this component. We need to update the functional specs to include this feature.  

#### Acceptance criteria
 - [ ] functional specs references new media – manager
 - [ ] update version number in name
 - [ ] change log updated to reflect updates and version
 - [ ] Documented `Content item` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by RobertaJHahn** [comment]
Iceboxing this issue as the Media Manager component will not be developed at this manager.

**Comment by ellenchoi1** [comment]
Completed draft of updated specs: https://ibm.box.com/s/69x77s8wwsko0q9nae5o924xeuo6nncs

**Comment by RobertaJHahn** [comment]
4/30/2020:  Reviewed in the meeting with Engineers.  Ellen to make some changes.

**Comment by ellenchoi1** [comment]
Updated func specs to reflect that this sub-pattern will use Video and Image with caption. Lightbox media viewer will be dependencies of those patterns, not of this pattern itself.
https://ibm.box.com/s/69x77s8wwsko0q9nae5o924xeuo6nncs

**Comment by ellenchoi1** [comment]
@jeffchew confirmed updates satsify dev team's needs. closing ticket as done.

**Comment by photodow** [comment]
@ellenchoi1 @jeffchew @sethibm Follow up from the meeting we just had. Content item will not contain the direct functionality to handle light box media viewer. Both Video Player and Image with caption will handle this functionality. See #2306, and #2025 for any updates based on this discussion.
