### ISSUE TITLE
Pattern: Update the Link list functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1826]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Link list` functional specs 

> so that I can:
so that I can properly code the `Link list` component that meets the Solution template requirements

#### Additional information

 - Design Issue (#2030)
 - Development issue (#1850)
 - [Airtable](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide)
 - Link list [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-linklist--default)] [[code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/patterns/sub-patterns/LinkList)] [[directory](https://ibm.ent.box.com/folder/101876058407)]
 - CTA [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--default)] [[code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/components/CTA)] [[directory](https://ibm.ent.box.com/folder/101164203823)]

![image](https://user-images.githubusercontent.com/3793636/79607747-5fa25280-80b9-11ea-8eb0-3eaeda4df043.png)

This issue is created to reflect all the updates necessary to support the latest designs coming from the solution page template.

 - Horizontal layout
 - Style: text
 - optional heading

> Need to check with Lila on the final decision around adding an optional eyebrow to the card style

#### Acceptance criteria
 - [ ] New text style option.
 - [ ] Horizontal link list
 - [ ] Documented `Link list` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by kathysaraf** [comment]
updated and ready for review!  https://ibm.ent.box.com/file/613262819069

**Comment by RobertaJHahn** [comment]
4/30/2020 meeting:  Reviewed with DDS engineers.
