### ISSUE TITLE
Pattern: Update the Table of contents functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1827]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Table of contents` functional specs 

> so that I can:
so that I can properly code the `Table of contents` component that meets the Solution template requirements

#### Additional information

  - Design Issue (#2008  )
 - Development issue (#1851 )

#### Acceptance criteria
 - [x] Documented `Table of contents` Link functional specifications
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments

**Comment by photodow** [comment]
- Added Link List — text as optional 3 annotations
- shifted sticky/fixed behavior to table of content 2 in annotations

https://ibm.box.com/s/ol2tqtwxv3nbcva29mp1flnqbxrxscjj

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
