### ISSUE TITLE
Pattern: Create the CTA section functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1829]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA section` functional specs 

> so that I can:
so that I can properly code the `CTA section` pattern that meets the Solution template requirements

#### Additional information

 - Design Issue (#2031)
 - Development issue (#1852 )
 - Solution page template design [[sketch](https://ibm.box.com/s/npvpwscwolvoevrpxnkgzsavp5o5d87s)]
 - CTA Block issue (#1833)

The CTA section is a new full section decorator pattern. It has a dependency on CTA Block.

![image](https://user-images.githubusercontent.com/3793636/78577377-99d73e80-77f3-11ea-9b66-cd789bdb8c2e.png)

#### Acceptance criteria
 - [x] Documented `CTA section` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by kathysaraf** [comment]
Ready for review: https://ibm.ent.box.com/file/651721650497

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
