### ISSUE TITLE
Pattern: Create the Content block - with cards functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1832]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content block - with cards` functional specs 

> so that I can:
so that I can properly code the `Content block - with cards` pattern that meets the Solution template requirements

#### Additional information

  - Design Issue (#2033  )
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/111084561933)
 - Development issue (#1855 )

#### Acceptance criteria
 - [ ] Documented `Content block - with cards` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Completed func specs draft: https://ibm.box.com/s/1bj93epgwc8thizgn9uxeklgz2h607cy

**Comment by ellenchoi1** [comment]
Reviewed and signed off on in engineering epic and story refinement meeting 5/4/2020
