### ISSUE TITLE
Pattern: Create the CTA block functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1833]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA block` functional specs 

> so that I can:
so that I can properly code the `CTA block` pattern that meets the Solution template requirements

#### Additional information

- Design Issue (#2005  )
- Development issue (#1856)
- Solution page template design [[sketch](https://ibm.box.com/s/npvpwscwolvoevrpxnkgzsavp5o5d87s)]
- Content block [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-contentblock--default)] [[functional specs](https://ibm.ent.box.com/file/653586626848)]
- Layout [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-layout--default)]
- Content item [[storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-contentitem--default)] [[functional specs](https://ibm.box.com/s/b64hvlc187xs653x07loh9zwh5nl8arf)]

The CTA Block (not to be confused with CTA Section) is a new block-level decorator pattern. It has a dependency with content block, layout, and content item.

![image](https://user-images.githubusercontent.com/3793636/78576917-f25a0c00-77f2-11ea-9c40-d1677d4d3232.png)

#### Acceptance criteria
 - [x] Documented `CTA block` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by RobertaJHahn** [comment]
@kathysaraf I have moved this issue into sprint 20-08 to align with delivery of the designs from Lila.  If you have started this work in the current sprint, you may have changes to do after the meeting on Monday.

cc:  @photodow

**Comment by kathysaraf** [comment]
Ready for review: https://ibm.ent.box.com/file/651730826496

**Comment by RobertaJHahn** [comment]
Review meeting conducted with DDS designers and dev's April 14, 2020.
