### ISSUE TITLE
Pattern: Create the Feature card block - large functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1834]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Feature block` functional specs 

> so that I can:
so that I can properly code the `Feature block` pattern that meets the Solution template requirements

#### Additional information

 - Design Issue (#2004  )
 - Development issue (https://github.com/carbon-design-system/ibm-dotcom-library/issues/1857)
 - [Airtable](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide)
 - Card [[Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-card--link-clickable)] [[Code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/patterns/sub-patterns/Card)] [[Directory](https://ibm.box.com/s/3ma5hudlb59s3jossq96yxduqyj68pq7)]
 - CTA [[Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--default)] [[Code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/components/CTA)] [[Directory](https://ibm.box.com/s/ceu99rjzd0e87sm51n9cv550yssockme)]

The feature block is similar in some ways to the feature card pattern, but it's much larger and without the content group heading. This block pattern decorates the existing card sub-pattern modifying some visual elements of it to help it stand out. Something that needs to be considered are the different types this pattern allows for. (e.g. download, video, local). They are similar to the CTA component. Is that needed here? How can we align both of these types and such better?

![image](https://user-images.githubusercontent.com/3793636/79257335-19e25180-7e4f-11ea-86a0-4c1e3ce5d8bd.png)

![image](https://user-images.githubusercontent.com/3793636/79257574-6fb6f980-7e4f-11ea-967c-84d99481242e.png)

#### Acceptance criteria
 - [ ] Documented `Feature block` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by jeffchew** [comment]
@kathysaraf what is the url for the docs?

**Comment by kathysaraf** [comment]
Here's the location: https://ibm.ent.box.com/file/655898992298

**Comment by kathysaraf** [comment]
updated functional spec to include CTA reference. Done
