### ISSUE TITLE
Pattern: Create the Leadspace block functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1835]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Leadspace block` functional specs 

> so that I can:
so that I can properly code the `Leadspace block` pattern that meets the Solution template requirements

#### Additional information

  - Design Issue (#1835  )
 - Development issue (#1858 )

#### Acceptance criteria
 - [ ] Documented `Leadspace block` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by kathysaraf** [comment]
First draft of spec is ready for review. https://ibm.ent.box.com/file/660157267815

**Comment by RobertaJHahn** [comment]
May 4, 2020: Reviewed with engineers for sizing.

**Comment by RobertaJHahn** [comment]
@kathysaraf The visuals were reviewed in the meeting today with the Reboot designers.  Are any changes needed to the func specs based on that review?

**Comment by RobertaJHahn** [comment]
5/5/2020 Slack response from Kathy:  yes there are updates needed for leadspace block but i can have that done very quickly to include linklist now that they've finalized the designs for it.

**Comment by kathysaraf** [comment]
Updated and ready for review: https://ibm.ent.box.com/file/660157267815

**Comment by kathysaraf** [comment]
small update made to include linklist update to include the jump style here as well https://ibm.ent.box.com/file/613262819069

**Comment by RobertaJHahn** [comment]
5/11/2020:  Reviewed with the DDS engineers.
