### ISSUE TITLE
Pattern: Create the Quote functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1836]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Quote` functional specs 

> so that I can:
so that I can properly code the `Quote` pattern that meets the Solution template requirements

#### Additional information

- scope includes English and 3 minimal quote variations.  
 - Design Issue (#2011  )
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/110531199928)
 - Development issue (#1859 )

#### Acceptance criteria
 - [ ] Documented `Quote` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
Going to drop this here for now. Reached out to Tina Williams, and she directed me to 15 of her globalization experts (one for each language). Latoya is helping me collect feedback from everyone.

Block Quote Design for Standard Languages
https://ibm.box.com/s/6h01jvokt3ixczfgc9upcrlrwikrsir5

**Comment by photodow** [comment]
Here are the latest functional specs. Need to review with Lila to make sure some of the optional ones make sense as optional.

https://ibm.ent.box.com/file/653670368937

**Comment by photodow** [comment]
I got the answers I needed from Lila, and Jill. Sounds like this is good to go after our review earlier this morning. Also updated the dev story.
