### ISSUE TITLE
Pattern: Create the Callout functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1837]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Callout` functional specs 

> so that I can:
so that I can properly code the `Callout` pattern that meets the Solution template requirements

#### Additional information

  - Design Issue (#  )
 - Development issue (# )

#### Acceptance criteria
 - [x] Documented `Callout` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
@RobertaJHahn pulling this issue in as it is relevant to some of the other work going on, and is a pretty quick win.

These functional specs are ready to be reviewed. I'll go through and try to update the dev story.
https://ibm.ent.box.com/file/653654334281
