### ISSUE TITLE
Pattern: Update the Card section functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1839]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card section` functional specs 

> so that I can:
so that I can properly code the `Cards section` pattern that meets the Solution template requirements

#### Additional information

- This pattern is only used in the Drupal Learn page template. 
 - This pattern will be updated to include the cards group decorator pattern.
 - Design Issue (#2007  )
 - Development issue (#1844 )

#### Acceptance criteria
 - [ ] Documented `Card section` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Completed updates to func specs: https://ibm.box.com/s/5kloi9iu7rg5iessx1i8cx390kexpn17

**Comment by ellenchoi1** [comment]
Updated func specs to reflect that this pattern can be retired and is no longer needed as a standalone since it is covered by CardSectionImages and CardSectionSimple: https://ibm.box.com/s/5kloi9iu7rg5iessx1i8cx390kexpn17
