### ISSUE TITLE
Pattern: Create the Logo functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1841]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Logo` functional specs 

> so that I can:
so that I can properly code the `Logo` pattern that meets the Solution template requirements

#### Additional information

  - Design Issue (#2036  )
 - Development issue (#1864 )

#### Acceptance criteria
 - [ ] Documented `Logo` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
I think this was included as part of the logo grid functional specs. #645
