### ISSUE TITLE
Pattern:  Change the Card section, including creating the new Cards group,  based on the Solution page designs and updated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1844]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Card section` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

![image](https://user-images.githubusercontent.com/3793636/77663222-d4ff8500-6f4a-11ea-9999-fa6340462d70.png)

![image](https://user-images.githubusercontent.com/3793636/77662982-881bae80-6f4a-11ea-9742-58fdc0467776.png)

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2007  )
- Card section Functional specs issue (#1820 )
- Cards group functional specs issue (#1839)
- Design QA testing issue (#2132 )
 - Prod QA testing issue (#2273 )
 -  Changes summary:  Remove the Cards group in Card Section, create a new Cards group pattern, create new cards group story and corresponding documentation, include the logic for the image and simple cards into the Cards group
- Existing Card section is actively being used by another team.  Changes to the Card Section must be transparent to this adopter.

#### Acceptance criteria
- [ ] New Card group sub-pattern
 - [ ] Card section uses the new Card group subpattern
 - [ ] Card group has 2 options:  simple and with image
 - [ ] Ensure the Cards group is properly exported as a component
 - [ ] Ensure the Cards group styles are properly exported
 - [ ] Include a sandbox for the cards group pattern
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by jeffchew** [comment]
Holding on this for now until we complete discussions around https://github.com/carbon-design-system/ibm-dotcom-library/issues/1855.

**Comment by jeffchew** [comment]
@kennylam this is one of the followup issues after `CardGroup` is created.
