### ISSUE TITLE
Pattern: Change the Logo grid based on the Solution page designs and updated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1846]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Logo grid` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2032  )
- Functional specs issue (#645  )
- [Design and Functional specs Box link](https://ibm.ent.box.com/folder/112347802132)
- Design QA testing issue (#2277 )
 - Prod QA testing issue (#2276 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by ljcarot** [comment]
@reesedownes @jeffchew Is this on track to finish by Friday? thx
