### ISSUE TITLE
Pattern: Change the Content block based on the Solution page designs and updated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1847]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Content block` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
 - Design Issue (#1989)
- Functional spec issues (#1821) and (#2051)
- [Functional specs Box folder](https://ibm.ent.box.com/folder/99481428439)
- [Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-contentblock--default)
- Design QA testing issue (#2148 )
 - Prod QA testing issue (#2149 )
- Summary for the changes:  The CTA should include a button style option.  ![Content Block solution page change.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/e00a5e4b-91c4-4e75-a330-76bc64741213)

> 👀See section 4 of the functional specs for specifics

NOTE: As it appears the button is already included in CTA, we have noticed that the ContentBlock propType definition is too loose, and allows for anything through. This ticket will be to refine the ContentBlock to better align with the requirements of the functional specifications.

#### Acceptance criteria
 - [ ] Style button option is allowed
- [ ] Update README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage

**Comment by jeffchew** [comment]
Hey @ljcarot @RobertaJHahn not sure if this is demoable, this is just setting up prop configurations in the component itself, and the work is mostly tech related 

cc: @guilhermelMoraes
