### ISSUE TITLE
Pattern: Change the Content item based on the Solution page designs and upated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1848]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Content item` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#1990 )
- Functional specs issue (#1824 )
- Design QA testing issue (# )
 - Prod QA testing issue (# )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by ellenchoi1** [comment]
@RobertaJHahn this ticket can be closed as per the dev team's update that the work has already been done and we were retro-actively updating the func specs. I think the only outstanding item is for you to be able to link this ticket to the previous dev ticket where the work was actually done.

**Comment by RobertaJHahn** [comment]
This dev work was finished by Anna under issue (#1672)  Closing this issue.
