### ISSUE TITLE
Sass build of IDL Patterns and components is throwing errors

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#185]
> Is this issue related to a specific component? I see it for Leadspace Pattern and Masthead

> What version of the IBM.com Library are you using? 1.0.0

ERROR in ./node_modules/@carbon/ibmdotcom-styles/scss/patterns/leadspace/_leadspace.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError
(9:6) Unknown word
   7 | 
   8 | @mixin leadspace {
>  9 |   .#{$prefix}--leadspace {
     |      ^
  10 |     position: relative;
  11 |     padding-top: carbon--rem(370px) / carbon--mini-units(40) * 100%;
    at runLoaders (/Users/smula@us.ibm.com/ibmcomdrupal/ibm_com_drupal/scripts/pattern-automation/convert-react-to-html/node_modules/webpack/lib/NormalModule.js:313:20)
    at /Users/smula@us.ibm.com/ibmcomdrupal/ibm_com_drupal/scripts/pattern-automation/convert-react-to-html/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/smula@us.ibm.com/ibmcomdrupal/ibm_com_drupal/scripts/pattern-automation/convert-react-to-html/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/smula@us.ibm.com/ibmcomdrupal/ibm_com_drupal/scripts/pattern-automation/convert-react-to-html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at process.then.catch.error (/Users/smula@us.ibm.com/ibmcomdrupal/ibm_com_drupal/scripts/pattern-automation/convert-react-to-html/node_modules/css-loader/dist/index.js:122:5)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@carbon/ibmdotcom-styles/scss/patterns/leadspace/_leadspace.scss:
    Entrypoint mini-css-extract-plugin = *
       1 module
    
    ERROR in ./node_modules/@carbon/ibmdotcom-styles/scss/patterns/leadspace/_leadspace.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/@carbon/ibmdotcom-styles/scss/patterns/leadspace/_leadspace.scss)
    Module build failed (from ./node_modules/css-loader/dist/cjs.js):
    CssSyntaxError
    
    (9:6) Unknown word
    
       7 | 
       8 | @mixin leadspace {
    >  9 |   .#{$prefix}--leadspace {
         |      ^
      10 |     position: relative;
      11 |     padding-top: carbon--rem(370px) / carbon--mini-units(40) * 100%;

**Comment by jeffchew** [comment]
@annawen1 can you fix in your PR?
cc: @larahanlon2 @kennylam

**Comment by annawen1** [comment]
> @annawen1 can you fix in your PR?
> cc: @larahanlon2 @kennylam

Yep I'll put the fix in

**Comment by annawen1** [comment]
@sridharmula looking at the files, we have an `index.scss` that contains the global imports for the masthead and the leadspace.

`../packages/styles/scss/patterns/leadspace/index.scss`
`../packages/styles/scss/components/masthead/index.scss` 

The index.scss files combine all the styling for the subcomponents under masthead and for leadspace. Can you try using index instead?

**Comment by sridharmula** [comment]
ok sure @annawen1

**Comment by annawen1** [comment]
closing this as @kennylam worked with @sridharmula to solve this issue
