### ISSUE TITLE
Pattern: Change the Link list based on the Solution page designs and upated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1850]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Link list` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2030  )
 - [Visual Designs & Design Specs Box link](https://ibm.ent.box.com/folder/101876058407)
- Functional specs issue (#1826  )
- [Functional specs Box link](https://ibm.ent.box.com/file/613262819069)
- Design QA testing issue (#2263 )
 - Prod QA testing issue (#2264 )

#### Acceptance criteria
- [ ] Update content item — horizontal to leverage link list.
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by kathysaraf** [comment]
The link list func spec updates include the jump style cta added and the position of the cta (to the left, right or below the text): https://ibm.ent.box.com/file/613262819069
