### ISSUE TITLE
Pattern: Change the Table of contents based on the Solution page designs and updated functions specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1851]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Table of contents` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2008  )
- Functional specs issue (#1827  ) and (#2052)
- [Design and Functional specs Box link](https://ibm.ent.box.com/folder/90702727404)
**Functional Specs updates:**  
- Added Link List — text as optional 3 annotations
- shifted sticky/fixed behavior to table of content 2 in annotations
- Design QA testing issue (#2258 )
 - Prod QA testing issue (#2259 )

#### Acceptance criteria
- [x] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [x] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by jeffchew** [comment]
Note, another adopter is now asking for this as well.

**Comment by ellenchoi1** [comment]
@RaphaelAmadeu version 1.3 of the func specs is available on box: https://ibm.box.com/s/yfuicifhfeaefp4rl0pp62dpeacr18ry. this version was created for #1783 and is inclusive of the functionality added by James in version 1.2.1 from #1827
