### ISSUE TITLE
Pattern: Develop Content block - with cards:  Prod level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1855]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Content block - with cards`

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2033  )
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/111084561933)
- Functional specs issue (#1832  )
- Design QA testing issue (#2170 )
 - Prod QA testing issue (#2171 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by jeffchew** [comment]
Holding on this for now, thinking of simplifying this work but need to come to a consensus first. The idea is to enhance the `ContentGroupCards` instead to be able to switch between using a `ContentGroup` and a `ContentBlock`. Will confirm if this is the new approach.

**Comment by ellenchoi1** [comment]
@kennylam per the func specs, we will allow for "copy" to be passed in when using the image variation of the card. can you confirm if this parameter was included? i didn't see it in storybook.
