### ISSUE TITLE
Pattern: Develop Feature card block - large:  Prod level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1857]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Feature - block`

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
 - Assume CTA pattern business logic class has been created.  
- Design specs issue (#2004  )
- Functional specs issue (#1834  )
- [Design & Functional specs Box folder](https://ibm.ent.box.com/folder/110327688617)
- Design QA testing issue (#2119 )
 - Prod QA testing issue (#2120 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by kathysaraf** [comment]
done and ready for review

**Comment by RobertaJHahn** [comment]
@reesedownes Hi Maurice, is this code merged?  Could you link the PR to this issue?

**Comment by reesedownes** [comment]
@RobertaJHahn yep. here it is: 

https://github.com/carbon-design-system/ibm-dotcom-library/pull/2334

**Comment by RobertaJHahn** [comment]
@reesedownes I posted a message on Slack about making comments in the QA issues when the dev work is finished.  Could you please post messages in the Design QA issue (#2119) and Prod QA issue (#2120) letting the testers know that this pattern is ready to be tested?  Thanks.
