### ISSUE TITLE
Content Block Media CTA arrow styles being overridden by .bx--feature-card__card

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1869]
Using v1.5.1-rc.0, the Content Block Media CTA has a Feature Card that feature card has an blue arrow.  This arrow's css selector:

.bx--card--inverse .bx--card__cta, .bx--card--inverse .bx--card__cta a, .bx--card--inverse .bx--card__cta a:visited {
    color: #78a9ff;
}

Seems to have been overridden by the another css selector such that the arrow appears to be white:

.bx--feature-card__card.bx--card--inverse .bx--card__cta, .bx--feature-card__card.bx--card--inverse .bx--card__cta:visited {
    float: right;
    color: #ffffff;
}

**Comment by oliviaflory** [comment]
@kexuibm I believe the Feature Card is intended to have a white arrow as it appears in the [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default)

<img width="716" alt="Screen Shot 2020-03-26 at 10 54 14 AM" src="https://user-images.githubusercontent.com/45692622/77660823-2c542400-6f50-11ea-9cb7-0acfff3818fa.png">


Let us know if it's not rendering correctly.

**Comment by wonilsuhibm** [comment]
Confirmining that the white arrow is correct.

**Comment by ljcarot** [comment]
@wonilsuhibm @ltitle Please make sure Ke is working from the correct spec for Content Block with Media by providing a link.

**Comment by RobertaJHahn** [comment]
Adding to Sprint 20-07 and will close at the end of that sprint if no additional support is needed from DDS.

**Comment by ljcarot** [comment]
Lila confirmed where correct specs are and that link should be white.  This is how it is working in code as shown in Storybook.  Closing this issue.
