### ISSUE TITLE
cardsectionimages has styling issues on the label field

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1874]
Using v1.5.1-rc.1 On the Card Section Images Pattern, each image card has a label and the Label color is darker than the color used in the Visual design.
https://ibm.box.com/s/td94d8jdb0odjbyohgbmuhvh8lkmem6b

**Comment by oliviaflory** [comment]
I believe the card section images label color was updated to `$text-02` (HEX value: 393939) during development to pass accessibility requirements.

We are working on updating the design specs in issue #1519 scheduled for our next sprint.


The [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-cardsectionimages--default) should reflect the correct values


@wonilsuhibm Can you please confirm that this information is correct.

**Comment by RobertaJHahn** [comment]
Issue (#1866) created to update content section images in Storybook.

**Comment by ljcarot** [comment]
@RobertaJHahn The issue 1866 noted above seems unrelated to updating Storybook. Perhaps you transposed numbers.

**Comment by RobertaJHahn** [comment]
Closing as the work will be managed under issue (#1519).
