### ISSUE TITLE
Content Block Mixed has Pictograms that are too small

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1875]
Using v1.5.1-rc.1, in the Content Block Mixed Pattern.  The Content Group Pictograms is rendering each pictograms smaller than they are shown in the Visual Design for the Learn Page.

https://ibm.box.com/s/td94d8jdb0odjbyohgbmuhvh8lkmem6b

**Comment by oliviaflory** [comment]
This is a known issue that is coming from the Carbon pictogram repo. 

We have a request into fix the problem which is being tracked in #1453 on our board, and here on [Carbon](https://github.com/carbon-design-system/carbon/issues/5693)

**Comment by RobertaJHahn** [comment]
We will close this issue once issue (#1453) is closed.

**Comment by RobertaJHahn** [comment]
Closing this issue as #1453 has been iceboxed.
