### ISSUE TITLE
Card Section Simple Pattern Top Level Card Link is not the same height as the other cards

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1880]
Using v1.5.1-rc.1, it looks like the Card Section Simple Pattern has a styling issue where if the Top Level Card is the first element in the row it does not have the same height as all the other cards.  Please see the screen shot below.

<img width="1244" alt="Screen Shot 2020-03-26 at 5 13 41 PM" src="https://user-images.githubusercontent.com/55464272/77697554-6ee42380-6f85-11ea-93ce-7e17651f79b7.png">

**Comment by RobertaJHahn** [comment]
This might be related to issue (#1727)
