### ISSUE TITLE
Content Group Simple is missing an data-autoid attribute for optional CTA

### ISSUE THREAD

**Issue by gregj0** [carbon-design-system/ibm-dotcom-library#1884]
### The problem
_{{The Content Group Simple has an optional CTA.  We do not have a way to exclude all of the CTA markup.  There is a data-autoid on dds--card but that leaves unused markup.   We are currently using the one on dds--card  now so this is not a MVP blocker but needs to be cleaned up in the future )}}_

### The solution
_{{Add data-autoid to where the class bx-content-group__cta-row  is defined so we can exclude content based on it when no CTA is included.}}_

### Additional information
 _{{Please provide any additional information or resources for reference}}_
 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

**Comment by RobertaJHahn** [comment]
Defect review meeting:  This defect is the same as issue (#1747).  This missing data-autoid affects the analytics. Drupal can go into Production without this fix, but that will create technical debt on both their team and the Analytics teams. Requesting that we reconsider and include this fix in a patch. Delivery date of the patch would be Friday, April 3.

**Comment by RobertaJHahn** [comment]
Because the placement of the autoid is not in the correct level, if the element is removed there is an additional 3px space.  Ask is to move the austoid 1 level up.

**Comment by RobertaJHahn** [comment]
meeting with Ke:  The can go live with the MVP with this issue.

DDS:  added to April release.
