### ISSUE TITLE
HTTP Error page redesign for Carbon

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#190]
_Wonil-Suh1 created the following on Nov 12:_  

 ## User story

As an ibm.com user I need a helpful error page template so that I can understand the situation, and determine the next steps.

The error pages were implemented on v18.  This work is needed for Carbon.  

### Note

- Research
- Design exploration
- Design
- Review & approval
- Development
 
### Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/293_

**Comment by jeffchew** [comment]
_On Nov 13, Wonil-Suh1 commented:_
The webmaster team (Ervin Bolat) is conducting a test with new elements on the page.

https://www.ibm.com/404?optimizely_token=331d63878ae458212fffe4fa0fa3056fdc2882ad2f62f7b05c920593009440c2&optimizely_x=12052510043&optimizely_x_audiences=&optimizely_preview_layer_ids=12055062673&optimizely_snippet=s3-3867211201

**Comment by jeffchew** [comment]
_On Dec 10, Lisa-Lurie commented:_
@Benjamin-Hansen1 would you help us follow up on this please? How did that test do? Do we have next steps?
@Wonil-Suh1

**Comment by jeffchew** [comment]
_On Dec 10, Lisa-Lurie commented:_
And what do we think about the IBM logo upside down? I'm wondering if it's the right tone for the brand. (i.e. the upside down logo doesn't instill trust.)

**Comment by jeffchew** [comment]
_On Aug 13, Wonil-Suh1 commented:_
![error-page--current--404](https://media.github.ibm.com/user/25726/files/8aa70a80-bda4-11e9-9ac9-ce1dc6a19860)
![error-page--current--xxx](https://media.github.ibm.com/user/25726/files/8aa70a80-bda4-11e9-8de4-83ff2fa98a84)

**Comment by jeffchew** [comment]
_On Aug 13, Wonil-Suh1 commented:_
Converting this to an epic to handle different aspects of the issue.

**Comment by oliviaflory** [comment]
<img width="1680" alt="Screenshot 2019-11-25 at 18 24 34" src="https://user-images.githubusercontent.com/45692622/69565889-d95b6780-0f83-11ea-9ae4-9bd9b7d9a158.png">

couldn't manage to reproduce this one, so only have the screen shot.

**Comment by RobertaJHahn** [comment]
Content from this issue has been moved to the [Ideation epic 32](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/32)

Closing this issue.
