### ISSUE TITLE
Learn Page Template - Table of contents, selector and the content section are mismatched.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1914]
## Detailed description

Browser - Firefox
Device - Windows 10

Issue:- When user selects 'Content block simple' and clicks on 'content block segmented', selector remains on the 
'Content block simple' whereas the content is from 'content block segmented'.

## Additional information

![TOC.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8b407968-e42e-4817-9112-05ba5b6af46e)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr 
Could you please test this again using our canary staging? thanks!
https://ibmdotcom-react-canary.mybluemix.net/
