### ISSUE TITLE
Research Codesandbox CI feature with IBM.com Library

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-dotcom-library#1915]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
get more information on utilizing Codesandbox's CI workflow for importing and building sandboxes from the IBM.com library repo

> so that I can:
create isolated sandboxes with IBM.com library patterns and components.

#### Additional information
Possible solutions:

- Direct importing a [branch](https://codesandbox.io/docs/git) or [entire repo](https://codesandbox.io/docs/importing)
- [Deploy from PR](https://codesandbox.io/docs/ci)

#### Acceptance criteria
 - [ ] Determine best solution that allows for all components and patterns to have sandbox examples
 - [ ] Must use latest package release

**Comment by jeffchew** [comment]
@kennylam is it possible to just pull `latest` in the codesandbox setup? e.g.:

`@carbon/ibmdotcom-react@latest`
`@carbon/ibmdotcom-styles@latest`
?

**Comment by RaphaelAmadeu** [comment]
After me and @kennylam testing repl.it, we ended up agreeing that the platform does not suit our needs although it has support for `.env` variables, it's very slow if compared to codesandbox, and it easily runs out of memory very often, so the application does not run at all.

@jeffchew , @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing this issue.  Opened a new issue to investigate additional options as codesandbox does not perform as expected.  Issue (#2198 )
