### ISSUE TITLE
TOC highlighted text is not bold as per design

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#1918]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
bug

> Is this issue related to a specific component? TOC

> What did you expect to happen? What happened instead? What would you like to
> see changed? Highlighted text should be bold as per design document.

> What browser are you working in?chrome and FF

> What version of the IBM.com Library are you using?v1.5.1-rc.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes
![image](https://user-images.githubusercontent.com/29663915/77928429-625a1680-7276-11ea-82ef-6a4216eada12.png)

**Comment by ljcarot** [comment]
@sridharmula The TOC component is providing the correct text weight for the highlighted item.  You have provided an image but where is that image from.  Also please share a screenshot of what you are seeing, where you are seeing it with the problem etc.

**Comment by sridharmula** [comment]
@ljcarot @wonilsuhibm this is per our tester testing it. This is the design link which we got. highlighted link has different font and non highlighted links have different font.
https://ibm.ent.box.com/file/642090151123

**Comment by wonilsuhibm** [comment]
@sridharmula Where do you see different font weight? The only difference should be the color.

**Comment by sridharmula** [comment]
@wonilsuhibm sorry the title talks about the bold that was the initial screen shot which I got from tester which was bold. But when I look at the design ui it has different font color for highlighted and non highligted.

**Comment by ljcarot** [comment]
Is this a bug or working as designed @wonilsuhibm @ltitle ?

**Comment by jacobottesen-dgc** [comment]
@ljcarot I confirmed with Lila that it is working as designed
