### ISSUE TITLE
Linklist is rendering too high on a pattern

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1920]
Using v1.5.1-rc.1, the Link List is rendering too high on a pattern.

Here is what it looks like in the Visual Specs:
<img width="744" alt="Screen Shot 2020-03-30 at 3 13 04 PM" src="https://user-images.githubusercontent.com/55464272/77952027-00f76f00-7299-11ea-810a-56227b56c26a.png">

Here is what it looks like on NextJS:

<img width="1549" alt="Screen Shot 2020-03-30 at 3 14 02 PM" src="https://user-images.githubusercontent.com/55464272/77952109-1d93a700-7299-11ea-97a7-46c3e4e8f636.png">

**Comment by RobertaJHahn** [comment]
Jeff has added this bug to the March 6, 2020 engineering huddle meeting agenda to see how this issue can be fixed.  A new decorator pattern may be needed to fix this issue.

**Comment by jeffchew** [comment]
@wonilsuhibm @photodow 
Some notes we have from our engineering huddle to handle this:
- We are thinking of enhancing the ContentBlock sub-pattern to accept a LinkList which is optional, we would need to modify all of the decorator patterns to accommodate this
- One thought would be to perhaps allow any optional content on the right column? Question for design if this is something that's been considered for future state of the ContentBlock in general?

**Comment by photodow** [comment]
@jeffchew can we sync up on this over slack, or a separate meeting? I don't know if it makes sense to do that, I'm a little concerned we're overloading and changing the purpose of content block here. I'm wondering if it would make more sense to add to something like the content block segmented, and content block simple before updating content block across the board. I also wonder if we should consider the possibility of a seperate type of decorator pattern to handle this instead so we can keep segmented and simple seperated.

**Comment by jeffchew** [comment]
> @jeffchew can we sync up on this over slack, or a separate meeting? I don't know if it makes sense to do that, I'm a little concerned we're overloading and changing the purpose of content block here. I'm wondering if it would make more sense to add to something like the content block segmented, and content block simple before updating content block across the board. I also wonder if we should consider the possibility of a seperate type of decorator pattern to handle this instead so we can keep segmented and simple seperated.

This might be better discussed over a meeting. I'll try to find a time that works for us, but I'm not convinced we'll find a solution for this by `v1.6.0` code freeze.

cc: @RobertaJHahn @wonilsuhibm @ljcarot @photodow

**Comment by jeffchew** [comment]
After discussing with the engineering team and @photodow , we have decided to add `LinkList` as an optional item in the `ContentBlock`. This will allow the LinkList being aligned properly with the copy in the ContentBlock itself. If LinkList is not defined, the ContentBlock will take on the full width of the container as it exists today.

I'll be opening a new issue for James to update the functional specs. Engineering team has estimated this effort and will bring this in.

cc: @RobertaJHahn @wonilsuhibm @kennylam @annawen1 @ljcarot
