### ISSUE TITLE
IBM.com style model research part 3

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1921]
### Notes

In order to support our adopters and help them make the best decisions re: style models for ibm.com, we need to identify and communicate design research best practices.

### Problem

When designers are tasked with designing ibm.com experiences, they don't always know where to start. Design research can provide insights and best practices for designers to follow and apply to their work. IBM has robust user research tools but less design (visual, UX, interaction) guidelines.

### Additional Information
 - This issue is for additional research work.  Additional research issues are:  (#1538), (#1718)
      

### Tasks
1. Map out design research flow/steps 
2. Identify existing tools and resources that designers can use to get started
3. Propose new methods or tools that we need to provide
4. Consider how this fits into style model, library, system etc.

**Comment by larahanlon2** [comment]
Update: after meeting with Wonil last sprint, this research phase will focus on **color themes** and usage in UI. The goal is to understand best practices and trends on dark Vs light UI so we can inform the overall design of ibm.com pages.

**Comment by RobertaJHahn** [comment]
Closing this issue as the work will be managed on the DDS Ideation board.  Issue (#9)
