### ISSUE TITLE
Create Northstar release R147

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1923]
#### User Story

> As a `[user role below]`:
Release manager

> I need to:
Release R147 of Northstar v18 to the EI server

> so that I can:
release the next version of Northstar to the public

#### Additional information

- Release Management Playlist: https://ibm.ent.box.com/notes/498576715683, under `Rolling Deployment`
- Release Plan: https://github.ibm.com/webstandards/digital-design/issues/1855

#### Acceptance criteria
 - [ ] R147 rolling deployment successfully completed
 - [ ] Release created in the v18 repository
- [ ] Release announced on #ibm-digital-design slack channel

**Comment by jeffchew** [comment]
Moving this to sprint 8 since the planned release is April 13th.

**Comment by jeffchew** [comment]
Release has been completed and communicated:
https://github.ibm.com/webstandards/v18/releases/tag/R147
