### ISSUE TITLE
Lightbox media viewer: unable to scroll to the bottom of the content

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1927]
## Detailed description

> Describe in detail the issue you're having.

[storybook](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--default)
When the browser window is short, the text is cut off even when scrolled to the bottom.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Yes. The lightbox media viewer.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Scrolling to the bottom should reveal the entire text.

> What browser are you working in?

Chrome 80.0.3987.149 (Official Build) (64-bit) on Mac.

> What version of the IBM.com Library are you using?

1.5.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A

## Steps to reproduce the issue

1. Open [lightbox media viewer](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--default)
2. Make the window short.

## Additional information

- See the screen show in the comment below.

**Comment by wonilsuhibm** [comment]
<img width="922" alt="Screen Shot 2020-03-31 at 9 54 35 AM" src="https://user-images.githubusercontent.com/30183447/78034377-a6602080-7335-11ea-8332-b2b554f6bfae.png">

**Comment by wonilsuhibm** [comment]
And it happens in this layout as well.
<img width="1535" alt="Screen Shot 2020-03-31 at 9 55 31 AM" src="https://user-images.githubusercontent.com/30183447/78034512-d4456500-7335-11ea-8f1a-a6af9c29648b.png">

**Comment by wonilsuhibm** [comment]
Here is also a video of this behavior.

[lightbox-media-viewer--scroll-issue.mov.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/4409964/lightbox-media-viewer--scroll-issue.mov.zip)

**Comment by Praveen-sr** [comment]
Issues related to above bug,
1. On iPhone and Android mobiles - landscape mode - Lightbox media viewer unable to scroll to the bottom of the content 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/faf14fc6-efb1-4463-9453-0be1ca65c766)

2. On zooming to 200% on Firefox browser, unable to read the content
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/161542ae-271d-421a-b9df-c84a136adb3b)
