### ISSUE TITLE
Masthead L0 mega-menu UX designs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#193]
_spbokma created the following on Dec 13:_  

 ## User story

As a user of IBM.com I need way to see a number of related topics within a navigation section so that I can quickly see what type of content and information I will find within that section of the website.

## Deliverables

- wireframes
- principles for specific models
- governance

### Notes

Exploring different mega-menu options to support different offerings, topics, content types and structural models

IBM.com homepage team has offered support to build/update the masthead navigation and mega-menus for the homepage for user testing and deployment on the live EN-US site.

### Tasks
define:
- [ ] structural model(s)
- [ ] define pattern(s) to support content types
- [ ] create wireframes
- [ ] define standards, governance & usage

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/400_

**Comment by jeffchew** [comment]
_On Mar 25, Wonil-Suh1 commented:_
I'll take a look at the design. Thanks!

**Comment by jeffchew** [comment]
_On Mar 25, Wonil-Suh1 commented:_
![masthead-menu-exploration](https://media.github.ibm.com/user/25726/files/ffae9c00-4ef8-11e9-9533-9ce30374593f)

**Comment by jeffchew** [comment]
_On Mar 25, Wonil-Suh1 commented:_
I feel that w need to look at the typography and layout a bit. Asked for the Sketch file.

**Comment by jeffchew** [comment]
_On Mar 25, Wonil-Suh1 commented:_
Updated to reflect IDL specs better.

@LARAHANL @Olivia-Flory @chsanche please take a look and let me know.

![masthead-v6 copy 11](https://media.github.ibm.com/user/25726/files/b7629e80-4f37-11e9-8655-c8cd7442864e)

![masthead-v6 copy 12](https://media.github.ibm.com/user/25726/files/b7629e80-4f37-11e9-905e-6e8704d6b796)

**Comment by jeffchew** [comment]
_On Mar 26, Wonil-Suh1 commented:_
Sketch file here: https://ibm.box.com/s/xofyf8ujffuu5booj2df5byhew1o0zu2

**Comment by jeffchew** [comment]
_On Mar 26, Olivia-Flory commented:_
I think they're looking good!

Would we use IDL colors for something like this? Or would we use the gray we have available in v18 or v19a? I don't mean to muddy the convo around color, but just want to make sure we're using them in the right places.

**Comment by jeffchew** [comment]
_On Mar 26, Wonil-Suh1 commented:_
@spbokma you expressed concerns around the text length. Can you get samples? Best case and worst?

**Comment by jeffchew** [comment]
_On Mar 27, LARAHANL commented:_
Looks good @Wonil-Suh1 !

I prefer the white background option. 
I wonder what it would be like if the left 'side bar' was gray 90 similar to L1 designs? 
For example:
![screen shot 2019-03-27 at 11 49 13](https://media.github.ibm.com/user/11951/files/98265700-5086-11e9-8f56-e38af977a06b)


Also would there be a need to include sub sections or headings within the mega menu? 
For example (old exploration):
![screen shot 2019-03-27 at 11 44 41](https://media.github.ibm.com/user/11951/files/f0108e00-5085-11e9-8d55-62c2ed9226e1)

**Comment by jeffchew** [comment]
_On May 13, spbokma commented:_
Testing happening on the ibm.com homepage starting 5/13 for two weeks to 

staging:
http://wwwstage-ext.ibm.com.cs186.net/thought-leadership/prototypes/project-masthead/
user: staging
password: IBM19Jul

---From Irina Lubenskaya (Art Director for homepage)---
we are planning to run it live serving to 50% of the audience (IBM homepage)

1. Here are our KPI for the masthead and footer. Basically, it’s CTRs
https://ibm.ent.box.com/file/449565386095  that’s our monthly analysis (see pages 9 and 10 related to the masthead specifically). We have years of these data.
2. We can run a survey and look at NPS comments as well

Notes:
we have seen a steady decline in CTRs MtM
our hope is that the new masthead will change it
people tend to use search and also the masthead megamenues are not the best experience

we are tagging the links differently from the current tagging

**Comment by jeffchew** [comment]
_On Sep 24, spbokma commented:_
User data I received/got walked through from William Tang & Rajeshwari J Nagaraj on 9/20/19, showing clicks/visit within ibm.com homepage mega-menus. As well as a recommendation for future mega-menus, which align towards a version currently in exploration…but needs dev evaluation for rendering time and making sure it doesn't slow down the display of menus.

[IBM Mega Menu - Dropdown Enhancement - V3 - 092019.pptx](https://github.ibm.com/webstandards/digital-design/files/435889/IBM.Mega.Menu.-.Dropdown.Enhancement.-.V3.-.092019.pptx)

**Comment by RobertaJHahn** [comment]
@jeffchew I thought that we had bumped up the stalebot to 60 days.

**Comment by jeffchew** [comment]
> @jeffchew I thought that we had bumped up the stalebot to 60 days.

It has been configured to 60 days, but the messaging was still old. I updated the message to now say 60 days.

**Comment by RobertaJHahn** [comment]
The work Olivia is doing with the Reboot team replaces Scott's work.  Closing this issue.
