### ISSUE TITLE
Video player - Lightbox version: tabbing

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1935]
## Detailed description

> Describe in detail the issue you're having.

[Storybook](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player)
When I use the tab key, there is a step that has no visual representation between the speaker icon and the maximize icon.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

I think it's a bug.

> Is this issue related to a specific component?

Video player in the lightbox.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the tabbing to jump to the maximize icon because there was nothing between the speaker icon and the max icon.

> What browser are you working in?

Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac

> What version of the IBM.com Library are you using?

1.5.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Open [this storybook page](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player)
2. start tabbing

## Additional information

- See the attached video capture in the comment below.

**Comment by wonilsuhibm** [comment]
[video-tabbing.mov.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/4410779/video-tabbing.mov.zip)

**Comment by jeffchew** [comment]
@wonilsuhibm Should we have QA team take a pass through this one and give their evaluation?
cc: @RobertaJHahn @ljcarot

**Comment by wonilsuhibm** [comment]
@jeffchew Yes, we should.

**Comment by Praveen-sr** [comment]
@wonilsuhibm Checked this scenario, its the seek bar / video progress bar between the speaker icon and the maximize icon.
Its not seen properly for the user.

![image](https://user-images.githubusercontent.com/60002341/78219756-d2b6a100-74dd-11ea-8eae-bbe563f29ea0.png)

**Comment by RobertaJHahn** [comment]
This is an issue with the Kaltura video player product itself.  It is not in our control to address.  We will closed this issue, but let Jerry Ringuette know about it as a potential enhancement to the Kaltura product.
