### ISSUE TITLE
IBM Cloud navigation notifications - UX

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#194]
_spbokma created the following on Dec 13:_  

 ## User story

As an IBM Cloud user I need be able to be informed of new information related to my Cloud products and services so that I can quickly see what action items (success, warnings, errors & general info) I need to address.

## Deliverables

- bullet points
- what should we expect

### Notes

Looking are leveraging the Carbon Design notification menu, so the Cloud website aligns to the Cloud console experience. To also create a unified user experience, design treatment and single code base. -- http://www.carbondesignsystem.com/components/notification/code

### Tasks
define:
- [ ] structural model
- [ ] usage
- [ ] standards & governence
- [ ] redline/spec
- [ ] interaction(s)
- [ ] animation(s)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/403_

**Comment by jeffchew** [comment]
_On Jan 07, spbokma commented:_
![mastheadspecifications-notificationmenu](https://media.github.ibm.com/user/2785/files/61392f26-1268-11e9-97a1-b5979734bacd)

**Comment by jeffchew** [comment]
_On Jan 07, spbokma commented:_
![namingconvention](https://media.github.ibm.com/user/2785/files/877e46d0-1268-11e9-8b32-4d6375a84e44)

**Comment by jeffchew** [comment]
_On Jan 14, Lisa-Lurie commented:_
Dependency on back end, can it actually pull in the content it needs. @jeffdos

**Comment by jeffchew** [comment]
_On Mar 27, spbokma commented:_
Waiting to hear if Carbon team work around this feature is/isn't going to be leveraged on the marketing site and how it technically be done.

**Comment by jeffchew** [comment]
_On Aug 09, hahnrob commented:_
Technical challenge.  Will resurface later.

**Comment by ljcarot** [comment]
We used to have a notifications service but had to shut it down due to no funding/support for it.
