### ISSUE TITLE
Component: LightboxMedia viewer - On iPhone, image and content are overlapping.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1943]
## Detailed description

Device - iPhone
Browser - Safari, chrome

Issue :- On iPhone, when we change image ratios on knobs - image and content are overlapping 

## Additional information

![iPhoneXS v12-lightbox.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3eb8578c-3479-4a49-904a-08ff102d6f25)

![iPhoneXS v12-lightbox1.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/714a986d-8332-4595-ac5b-33fbcf5aa100)

![iPhoneXS v12-lightbox2.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/01fa054f-4251-4a91-9662-9b15f85fa97d)

**Comment by jacobottesen-dgc** [comment]
This looks like an issue I don't know how to solve. Can @jeffchew @wonilsuhibm help with this?
