### ISSUE TITLE
Patterns: Features Bands

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#195]
_LARAHANL created the following on Dec 19:_  

 ### User story
As a author of ibm.com pages I need a pattern that I can use to describe features of product.

### Notes
We need to provide DGC teams with example bands and layouts so they can start designing with IDL.

### History
A few bands have been designed for this user needs through STUF, and NUT works, as well as in collaboration with Watson Marketing team.

### Examples
![screen shot 2019-08-09 at 9 47 06 am](https://media.github.ibm.com/user/25726/files/abacea00-ba8a-11e9-9f18-6903aa0f799b)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/414_

**Comment by jeffchew** [comment]
_On Dec 19, LARAHANL commented:_
Using Mural to map out content we might include: https://app.mural.co/t/ibm14/m/ibm14/1545222710734/1ae170819c6320267b72a871ea7d1f8a72eda1ba

**Comment by jeffchew** [comment]
_On Feb 01, Wonil-Suh1 commented:_
@LARAHANL thank you for setting up the mural board!

**Comment by jeffchew** [comment]
_On Feb 01, LARAHANL commented:_
@Wonil-Suh1 sure! I've got [this issue](https://github.ibm.com/webstandards/digital-design/issues/466) open for principles (which you'll find in the Mural). If you have time to read through / add comments that would be awesome.

**Comment by jeffchew** [comment]
_On Aug 06, larahanlon commented:_
**Need to:**
1. Collect band examples from Wonil
2. Consider best way to share these bands with DGC adopters eg. Patterns repo
3. What additional guidelines do we need to provide?

**Comment by larahanlon2** [comment]
This is old work and no longer relevant as per new pattern ontology. Closing.
