### ISSUE TITLE
Media > Video | Design QA | Styling

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/ibm-dotcom-library#1953]
## Detailed description

> Describe in detail the issue you're having.

[Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)

Caption font size is currently 16 but should be 14, per $body-long-01 specs:

body-long-01
Type: IBM Plex Sans
Size: 14px / .875rem
Line-height: 20px / 1.25rem
Weight: 400 / Regular
Letter-spacing: .16px

[Carbon Typography Page](https://carbondesignsystem.com/guidelines/typography/expressive/)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug.

> Is this issue related to a specific component?

Media > Video

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Caption font size is currently 16 but should be 14, per $body-long-01 specs:

> What browser are you working in?

Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac.

> What version of the IBM.com Library are you using?

1.5.1

## Steps to reproduce the issue

1. Open [Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)
2. Use Inspect to view font-size (see screenshot below)

## Additional information

![Caption_font_size_16_changeto_12.jpg](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/e0695460-a89f-4561-af13-bcca62ffc01a)

[Visual specs for Media > Video](https://ibm.box.com/s/36x742wza48h9zl5p3jfkq55me0fbcij)

**Comment by RobertaJHahn** [comment]
Media component is scheduled for sprint 20-08.  This font size will be corrected when developing the media component.  Closing this issue.
