### ISSUE TITLE
Media > Video | Design QA | Padding | Caption 

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/ibm-dotcom-library#1954]
## Detailed description

> Describe in detail the issue you're having.

[Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)

Padding above caption text is 16 px.  It should be 8px.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug.

> Is this issue related to a specific component?

Media > Video

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Padding above caption text is 16 px.  It should be 8px.

> What browser are you working in?

Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac.

> What version of the IBM.com Library are you using?

1.5.1

## Steps to reproduce the issue

1. Open [Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)
2. Use Inspect to view padding in the caption (see screenshot below)

## Additional information

![Caption_top_padding_16_changeto_8.jpg](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/c59b25dd-4d4f-4736-b8d4-a9b50f50fbe7)

[Visual specs for Media > Video](https://ibm.box.com/s/36x742wza48h9zl5p3jfkq55me0fbcij)

**Comment by RobertaJHahn** [comment]
Media component development is scheduled in sprint 20-08.  This spacing will be corrected there.  Closing this issue
