### ISSUE TITLE
Storybook: Remove Json objects as knobs

### ISSUE THREAD

**Issue by reesedownes** [carbon-design-system/ibm-dotcom-library#1956]
When clicking "Open canvas in new tab", the component/pattern currently resets to the default state  - i.e. no knobs turned on. Explore adding functionality to Storybook that would retain the current state of knobs when opening a component/pattern into a new window. 

####  Additional information
- Identify stories that are passing large Json objects and break them down into more manageable knobs

**Comment by RobertaJHahn** [comment]
This will be an engineering Huddle topics to create the additional stores to do the work.

**Comment by jeffchew** [comment]
Duplicate epic: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2955
