### ISSUE TITLE
June 2020 Release Plan (v1.8.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1961]
# Timeline

- **June 12, 2020**: Code freeze
- **June 15-22, 2020**: Release Candidate(s) and testing
- **June 24, 2020**: Full Release

# React

## Features 
- **Content block - with cards - Prod level version** (#1799 )
- **Leadspace - block - New Prod level version** (#1804 )
- **Logo grid changes needed for the Solutions page template** (#1805 )
- **Content block changes needed for the Solutions page template** (#1811 )
- **Link list changes needed for the Solutions page template** (#1815 )
- **Table of Contents changes needed for the Solutions page template** (#1816 )
- **Logo - Prod level version** (#1818 )
- **Content block - segmented changes needed for the Solutions page template** (#1798 )
- **Card link - Prod level version** (#2191 )
- **Video player changes included in the June (v1.8.0) release** (#2327 )
- **Feature card arrow should be Blue fix** (#2207 )
- **Card link - Add disabled state** (#2208 )
- **Feature Card type spec fix** (#2547 )
- **Feature Card include an additional focus state border** (#2206 )
- **Table of Contents scrolling behavior fixes** (#2424 )
- **Update Markdown Utility with Learn Template enhancements** (#2473 )
- **Update Content Group Pattern with Learn template enhancements** (#2472 )

## Fixes
- **Pattern: Feature Card Block Large: Spacing fixes** (#2410 )
- **CTA Section Text width fixes** (#2358 )
- **Callout-with-Media styling fixes** (#2395 )
- **Feature Card Block Large responsive behavior fix** (#2412 )
- **Feature Card Block Large incorrect icon size fix** (#2400 )
- **Feature Card Block Large Spacing fixes** (#2410 )
- **CTA Section button spacing fix for the mobile breakpoint**  (#2356 )
- **Table of Contents children and optional rule scroll away fix** (#2516 )
- **Leadspace block media caption styling and spacing fix** (#2613 )
- **Calloutquote block pattern does not render maximum length quote copy correctly** (#2661 )
- **Content group horizontal: Text color fix** (#2671 )
- **Content item horizontal: Text color fix** (#2675  )
- **Footer IBM links violate react rules fix** (#2656 )
- **Callout Quote: Incorrect text styles** (#2398 )
- **Feature Card Block Large: fix for misalignment to grid** (#2407 )
- **Feature Card grid alignment fix** (#2550 )

### Sub-patterns

Sub-patterns have been consolidated into `components`. With this change, the scss imports now fall under the `components` folder instead of `sub-patterns`. A deprecation warning will show for imports pointing to the `sub-patterns` folder, which we will ultimately remove in a future release.

# Services

## Features 

- **Update the TRANSLATION_HOST environment variable to be `create-react-app` compliant** (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2761)

**Comment by jeffchew** [comment]
Release created: https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.8.0
