### ISSUE TITLE
Pattern:  Media, Video and Image (related) | Padding | Top and Bottom

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/ibm-dotcom-library#1962]
## Detailed description

> Describe in detail the issue you're having.

[Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)

[Image Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-imagewithcaption--default)

There is no padding on top and bottom of Video player.  The overall component spec for Media requires 32px padding for top and bottom.  A related issue is that the Image currently has 48px padding on top and the bottom.  However,  the ontology outlines that this padding, for both Image and Video, will be coded within the Media component, not Image or Video.  So, the near term fix is matching Image and Video to have zero padding above and below.  Next fix: Media component functional spec and code must be finished in order to achieve the 32px padding for both Video and Image.  The related work for this is update and completion of the functional specs for Image, Video, Media, and Media - manager, and complete respective the updates and new code for them.  Please see the attached set of diagrams, also the animated gif, outlining relationship between these parts that work together to create this component.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Media, Video and Image

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to see 32px of padding on top and bottom of Video, also Image, but this requires Media component to be completed.  

> What browser are you working in?

Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac.

> What version of the IBM.com Library are you using?

1.5.1

## Steps to reproduce the issue

1. Open [Video Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-videoplayer--default)
2. Use Inspect to view padding (see screenshot below)
3. Open[Image Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/components-imagewithcaption--default)
4. Use Inspect to view padding (see screenshot below)

## Additional information

![Video_32px_padding_issue.jpg](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/3b0ef3d9-1a51-4cd0-854f-6c76e6cacd35)

[Animated gif by @photodow showing how Media - manager works](https://ibm.box.com/s/1j5w6sjqbqevik8srrwhr3sfqpq2h96x)

**Comment by ljcarot** [comment]
@jeffchew In light of change regarding Media Manager, is this bug still accurate? Does this need to be rewritten?

**Comment by jeffchew** [comment]
> @jeffchew In light of change regarding Media Manager, is this bug still accurate? Does this need to be rewritten?

Yes, for now we are handling padding in ImageWithCaptions and VideoPlayer.

**Comment by RaphaelAmadeu** [comment]
@sethibm 
As we discussed about this some days ago with @photodow over slack,
are the updates requested in this ticket still necessary? 

Thanks!

**Comment by sethibm** [comment]
@RaphaelAmadeu Still working on the spacing part, but it's getting closer.  I think we need to finalize decision on what will be default setup for patterns at this level in the system.  Then it can be finalized for this particular pattern and you can update it.  I think it can happen by next week.  Possible to pause the story until then?  

cc: @photodow

**Comment by RobertaJHahn** [comment]
Moving to sprint 20-12 as the spacing work will not be finished until Friday, June 5.

**Comment by RobertaJHahn** [comment]
The development work is dependent on the overall spacing analysis.  Wonil, Seth and James will meet to decide on the spacing for this pattern and give Raph the info he needs.
