### ISSUE TITLE
[masthead] profile menu functional specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1967]
#### User Story
> As a `[user role below]`:
IBM.com Library developer

> I need to:
be able to reference the masthead's navigation functionality

> so that I can:
confidently execute on my stories, and support in the future

#### Additional information
 - [Masthead navigation design folder](https://ibm.box.com/s/mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)
 - [Profile service](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/services/src/services/Profile)
 - [Profile API](https://idaas.iam.ibm.com/v1/mgmt/idaas/user/status/)

<img src="https://images.zenhubusercontent.com/5898a60e51aa2c3057739766/a95e2410-2c48-4a7a-9c0b-b39678faa55f" width="300px" />

<img src="https://images.zenhubusercontent.com/5898a60e51aa2c3057739766/528d6cec-69a8-4001-b8e4-3ded0d4d176b" width="300px" />

Pulling this out into its own functional spec deliverable seeing how heavy functionally this single component is itself.
 - API management
 - dropdown
 - interaction states
 - authentication logic (menu options, icon differences)
 - translation?

#### Acceptance criteria
- [ ] functional specs created and shared
- [ ] design and development agreement
- [ ] stories (if necessary) to iterate and create

**Comment by RobertaJHahn** [comment]
Charlie Douglas is providing a redesign of the Profile area.  The functional spec work should be scheduled after Charlie finishes the design.

**Comment by ellenchoi1** [comment]
Func specs completed and links to specs added to epic: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1464

**Comment by RobertaJHahn** [comment]
There are some gaps between the functional specs and developed component.  Lara will be working on the design specs in sprint 20-12.  Ellen will transition her work to James so that both the design and functional specs can be used by the Prod QA testing team for their functional and cross browser testing.
