### ISSUE TITLE
Setup initial contribution guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#198]
_chsanche created the following on Jan 21:_  

 

# As a dotcom maker, I need a way to contribute my design and/or code back to the team, so that my creation can be distributed and utilized across IBM.com.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/481_

**Comment by RobertaJHahn** [comment]
Closing as all related issues are finished.
