### ISSUE TITLE
Locale banner – research NPS module

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1993]
#### User Story

> As a `[user role below]`:

DDS Designer

> I need to:

research how the NPS survey module works
> so that I can:

determine the right placement for the locale banner
#### Additional information

After reviewing the initial design studies #1942 with Mary O'Donnell and Tina Williams on April 6th, they expressed some concerns around the placement of the locale banner when the NPS survey module is present.

We need to do some research on how the NPS survey is triggered, how we could reconcile the two modules on the same page
- what is the timing of the NPS survey (seems to be delayed by a few seconds)

@wonilsuhibm will reach out to Jo Welsh to start the conversation.

Designs presented on April 6:
<img width="1115" alt="Screen Shot 2020-04-06 at 3 51 00 PM" src="https://user-images.githubusercontent.com/45692622/78780312-623fd200-796c-11ea-9ee9-0aa6f6c5bb8a.png">

<img width="1104" alt="Screen Shot 2020-04-06 at 3 51 44 PM" src="https://user-images.githubusercontent.com/45692622/78780320-65d35900-796c-11ea-9599-c493f56306a2.png">

NPS module screen shot:
<img width="1279" alt="Screen Shot 2020-04-06 at 3 13 26 PM" src="https://user-images.githubusercontent.com/45692622/78780253-4d633e80-796c-11ea-9e54-d069b01647df.png">

#### Acceptance criteria
 - [x] Meet with Jo Welsh and find out how to NPS survey is controlled
 - [ ] Determine how the two modules could work together.
 - [ ] _{{And another}}_

**Comment by oliviaflory** [comment]
@jacobottesen-dgc here are my notes from the meeting:

Meeting with Joe Welsh and Kathy April 14

- NPS has some logic that there should never be two overlays on the page. The competition with two overlays should never happen. What is displayed depends on which pop up or overlay comes in first (reference to timing delay).

- Joe thinks the NPS survey is delayed by 30–45 seconds.

- Bottom banner option is better for not interacting with the “site feedback” tab as seen on the [Analytics page](https://www.ibm.com/analytics?lnk=hpmpr_bua)

- Side notification is ok if it doesn’t cover the site feedback, could we move it over so it doesn't cover it?

- Let’s consider collapsing the locale banner if users choose to not interact with it and scroll around the page.
   - Question: How long would we delay this? 


- Our engineers need to talk to Jo engineers to discuss the timing / how the pop-ups detect what is happening on the page.

- Wonil: we are considering creating a pop up manager

- Jo and Kathy don’t think the locale and NPS would look good together overlapping, the collapsed version will work.

**Comment by jacobottesen-dgc** [comment]
Action items:

– Explore collapsed versions of locale banner
– Figure out how long the locale banner should delay
– Research motion examples for floating banner collapsing 
– Set up discussion with DDS and Jo’s engineers (discuss the timing, how the pop-ups detect what is on the page)

**Comment by jacobottesen-dgc** [comment]
Meeting with Jeff, Wonil, Olivia, and a dev from Jo Welsh's team has been scheduled for April 23rd.

**Comment by jacobottesen-dgc** [comment]
Met with dev on Jo Welsh's team to discuss NPS survey with locale change banner.
