### ISSUE TITLE
Locale banner mobile studies

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1994]
#### User Story

We need to explore alternate designs for the mobile version of the locale banner so we do a user test to see if the user understands the message

#### Additional information

After sharing the initial design studies with Mary O'Donnell and Tina Williams, they expressed some concerns that the current design covers up too much of the content and the user will feel "blocked" by the locale banner.

We need to explore some alternate options:
1.  Should the banner be fixed in position so the user can scroll past it and view the content on mobile?
2. Explore truncating the message on mobile and indicate to users the locale has changed, tap the truncated message to view options.
  - need to consider the placement of the mobile message with the 
    - Let's talk 
    - NPS survey
    - Site feedback tab (?) 
 

Designs presented April 6: [Box folder](https://ibm.ent.box.com/file/645547951928)
Reference `Visual refinement` and `Initial Visual finals 4/6/20`
![Screen Shot 2020-04-06 at 3.51.00 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/db6139f8-4bb3-43c1-8a8e-2325642b0f72)
![Screen Shot 2020-04-06 at 3.51.44 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/88b99aed-7aeb-40cc-aa8a-b82379d2d916)

Example of truncated message

#### Acceptance criteria
 - [ ] Review designs with Wonil, Lara, Olivia
 - [ ] Present final direction to stakeholders (Tina & Mary)
 - [ ] _{{And another}}_

**Comment by jacobottesen-dgc** [comment]
I have been working through a options for mobile. View keynote prototype here: https://ibm.box.com/s/i1npmyfmn3gvqd9kn92in3f3txta8kok

**Comment by jacobottesen-dgc** [comment]
I explored all the different mobile viewport sizes. It looks like iPhone 5 has a issues with overlap from UMX and feedback for both scenarios. Scenario 2 also has some small overlap in iPhone 6/7/8

![Screen Shot 2020-04-20 at 10.29.19 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/13b82a78-1306-416b-931e-163bda845278)

![Screen Shot 2020-04-20 at 10.29.51 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/c0280d6b-e4d0-44fc-a69c-2e170ffd11a1)

**Comment by jacobottesen-dgc** [comment]
Meeting scheduled with UMX offering manager for April 23rd. 
Follow up meeting scheduled with Tina & Mary for April 24th.

**Comment by jacobottesen-dgc** [comment]
Follow up meeting scheduled with UMX developer for April 29th.

**Comment by jacobottesen-dgc** [comment]
Sketch file could be found in box: https://ibm.box.com/s/shephqs5l6b30fph8aladp2to1cu2we6
