### ISSUE TITLE
Locale banner – mobile user test

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1995]
#### User Story

> As a `[user role below]`:

DDS designer
> I need to:

test the mobile version of the locale selector
> so that I can:

determine if users understand 

#### Additional information

 - [ ] write user test
 - [ ] review user test with stakeholders, researcher, dds lead (?)
- [ ]  conduct user test
- [ ] synthesize results
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] user test results are presented to stake holders
 - [ ] agreement from stake holders
 - [ ] _{{And another}}_

**Comment by RobertaJHahn** [comment]
Closing this issue.  The work will be managed on the Ideation board.
