### ISSUE TITLE
Pattern: Callout - quote visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2002]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - Visual Designs & Design Specs Box folder
 - Links to the visual designs and design specs will be updated once received and reviewed by the Reboot designers.

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Review meeting is scheduled with Lila on Monday, April 13.

**Comment by ltitle** [comment]
Visual designs and design specs provided here: https://ibm.ent.box.com/folder/110327678801
Includes sketch file and pdf

**Comment by ltitle** [comment]
Updated background color token in both visual spec files in box to $inverse-02

**Comment by RobertaJHahn** [comment]
Reviewed in a April 21, 2020 design spec review meeting with DDS dev's and designers.
