### ISSUE TITLE
Pattern: Feature - block visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2004]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder](https://ibm.ent.box.com/folder/110327688617)

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
Visual designs and design specs provided here: https://ibm.ent.box.com/folder/110327688617
Includes sketch file and pdf
