### ISSUE TITLE
Pattern: CTA - block visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2005]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - Visual Designs & Design Specs Box folder
 - Links to the visual designs and design specs will be updated once received and reviewed by the Reboot designers.

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Design review meeting is scheduled with Lila Monday, April 13.

**Comment by ltitle** [comment]
Visual designs and design specs provided here: 
https://ibm.ent.box.com/folder/110020318891
Includes sketch file and pdf

**Comment by ltitle** [comment]
Will now be delivered as part of batch 2. CTA section was delivered in batch 1 instead.

**Comment by RobertaJHahn** [comment]
Design review meeting with DDS designers and developers conducted April 21, 2020. Lila will post the sketch and pdf files into the Box folder.
