### ISSUE TITLE
Storybook issue - On Leadspace, 32px padding is given on both the sides. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2006]
## Detailed description
Devices - Windows, Mac and Mobile 

Issue :- On Leadspace, 2 rem (32px) padding is given on both the sides. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b7be1631-ecbd-410f-af95-6e27a535dd47)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/181e2905-d609-40bd-b02f-807a6265a90c)

**Comment by RobertaJHahn** [comment]
dup of issue (#1780)  Closing
