### ISSUE TITLE
Pattern: Callout visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2010]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/110530875791)
 

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Design review meeting with DDS designers and developers conducted April 21, 2020.  Lila to post sketch and pdf files into the Box folder.

**Comment by ltitle** [comment]
@RobertaJHahn Sketch and PDF for visual deisgn and specs are posted in this folder:
https://ibm.ent.box.com/folder/110530875791
