### ISSUE TITLE
Pattern: Quote visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2011]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/110531199928)

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Visuals reviewed with DDS dev's and designers in April 21, 2020 meeting.  Lila to post files to Box folder.

**Comment by ltitle** [comment]
@RobertaJHahn Sketch and PDF for visual specs posted here: https://ibm.ent.box.com/folder/110531199928
