### ISSUE TITLE
Button group | 320px fixed button width and responsive setup need adjustments

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/ibm-dotcom-library#2016]
## Detailed description

> Describe in detail the issue you're having.

320px fixed button width is incorrect, per latest visual spec.  The buttons should flex per the internal content, with 16px padding to left of the text, and 64px spacer to right of the text in button, up to a max 320px button width.  

Also, a related bug, per the visual spec, needs to react to total width of the button group, as related to the container or available space, for when the buttons stack, rather than sit left to right.  The rule: when container or available space is less than the sum of all button widths + the padding between the buttons, all of the buttons will stack vertically.

Please see the visual spec for reference:

[Visual spec >](https://ibm.ent.box.com/file/651713722198)

[Storybook >](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/patterns-sub-patterns-buttongroup--default)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Button group

> What did you expect to happen? What happened instead? What would you like to
> see changed?

see above

> What browser are you working in?

Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac.

> What version of the IBM.com Library are you using?

1.5.1

## Steps to reproduce the issue

1. Open [Button group Storybook](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/patterns-sub-patterns-buttongroup--default)
2. Use Inspect to button size and how they react responsively, whether ordered left to right or stacked vertically (see screenshot below)

## Additional information

![Screen Shot 2020-04-09 at 5.14.00 PM.png](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/cefd5550-8652-4d1b-be57-6f8cb9dc9012)

![Screen Shot 2020-04-09 at 5.14.57 PM.png](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/73dec13b-bc10-419e-b417-d33c6340fbf2)

![Screen Shot 2020-04-09 at 5.15.31 PM.png](https://images.zenhubusercontent.com/5e5e747dbf668377018d1b14/42e55acd-9664-4008-b0c4-dd20f68d663e)

<img width="1170" alt="Screen Shot 2020-04-09 at 5 18 34 PM" src="https://user-images.githubusercontent.com/58601040/78941703-2ac54880-7a86-11ea-94ef-542b1717c962.png">

[Visual spec >](https://ibm.box.com/s/281fxfhiqxyjrfl7p8jw4znzvabnw4ql)

[Storybook >](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/patterns-sub-patterns-buttongroup--default)

**Comment by kennylam** [comment]
@sethibm While the styles say 12px it actually comes out to 16px because it accounts for the button's `border` and `outline`, which add to the overall spacing. But it does look like the `min-width` of the buttons need to lessen a bit. Is this correct @oliviaflory @wonilsuhibm?

**Comment by oliviaflory** [comment]
We should be using whatever internal spacing comes with the Carbon buttons and not alter that.

I think what @sethibm is trying to demonstrate is that the button group seems to be forcing the button width to 320px whether the content is short or long. 

The desired behavior is for the buttons to flex in size depending on the content within them, with a max width of 320px. 

Looks like he wants to update the space between the two buttons when they're side by side to 16px, currently 32px.


<img width="786" alt="Screen Shot 2020-04-24 at 10 49 12 AM" src="https://user-images.githubusercontent.com/45692622/80225590-44839580-8619-11ea-95c7-ea2bd3a4a989.png">


@sethibm @wonilsuhibm can you confirm?

**Comment by sethibm** [comment]
Hi @kennylam @oliviaflory, yes, confirmed with your input and diagram.  The issue is not with the internal padding setup within the buttons.  This was just to show that part, but not to change it.  

Summarizing Olivia's clarification, and the additional rule for when the buttons stack, needed changes are the following (this is also in the visual spec):

- Buttons need to flex in size depending on the content / text within them (and default Carbon padding), with a max width of 320px.  

- With more than one button, width of all buttons set to width of the widest button 

- Update the space between the two buttons when they're side by side to 16px, currently 32px.

- When container or available space is less than the sum of all button widths + the padding between the buttons, all of the buttons will stack vertically.

Sound good? Thoughts?

CC @wonilsuhibm
