### ISSUE TITLE
Update functional specs for ContentBlock to include LinkList

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2017]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
include a `LinkList` to the right of the copy within a `ContentBlock`

> so that I can:
properly provide a context of links for my ContentBlock pattern

#### Additional information

 - This stems from the issue https://github.com/carbon-design-system/ibm-dotcom-library/issues/1920, where we are currently laying out the `LinkList` in a separate `Layout` with the corresponding `ContentBlock` decorator pattern. The issue is that the `LinkList` is too high up and next to the heading, where it should be aligned with the copy instead.
 - Dev work is completed in issues (#2023) and (#2054).  These issues are included in the April 2020 release v1.6.0

#### Acceptance criteria
 - [ ] Updated functional specifications for the `ContentBlock`
 - [ ] updated corresponding functional specifications for decorator patterns utilizing the `ContentBlock`

**Comment by jeffchew** [comment]
@photodow this is the issue for updating the functional specifications, needs an estimate and priority.

cc: @wonilsuhibm @RobertaJHahn @ljcarot

**Comment by ellenchoi1** [comment]
No visual specs needed as dev work was completed in #1920

**Comment by ellenchoi1** [comment]
Version 1.3 uploaded to box: https://ibm.box.com/s/uaq0ovswviefwbv7gd4jn13llvqb23f8
