### ISSUE TITLE
Create "Contact us" Feedback Design for DDS

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#202]
_Benjamin-Hansen1 created the following on Mar 04:_  

 ## User story

As a user of the DDS site, I need an easy way to provide input to the DDS team about the site (general feedback, suggestions, bug/404 reports, requests for support/help), so that I can help the DDS team improve the site and, in the long run, improve the quality and speed of my work.

## Notes
There is currently no feedback loop on the DDS site - except a buried invitation to a Slack channel or Github at the bottom of some pages, which users don't see and don't know how to use when they do see it. A method of contact/feedback should be commonly available on every DDS page. 

The design and implementation should follow our DDS Contact Us module at https://www.ibm.com/standards/web/components/contact-module/. It will take brief work (an hour) of a small design team to spec the design, and minimal work by a dev to implement across all DDS pages. 

## Deliverables
- [ ] Designs spec
- [ ] Module added to all DDS pages
- [ ] Process documentation for receiving and acting on feedback

## Acceptance criteria
- [ ] Users are able to submit feedback or ask questions from the website

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/608_

**Comment by jeffchew** [comment]
_On Apr 05, chsanche commented:_
@Benjamin-Hansen1 We can work on this together. Especially this is website related.

**Comment by jeffchew** [comment]
_On May 08, chsanche commented:_
@Wonil-Suh1 
Currently on our website...when users click on the "Support" in the footer areas, it takes the users to [IBM Support](https://www.ibm.com/support/home/?lnk=fcw). Do you know why we set it up this way?

I also noticed the Carbon website did not have the "Contact Us" feature as well. Is this done intentionally?

**Comment by jeffchew** [comment]
_On Jun 14, linda-carotenuto commented:_
Instead of building anything new, let's make better use of the native Github create issue experience.  On Carbon, you can choose the type of Issue that is being raised. https://github.com/carbon-design-system/carbon-website/issues/new/choose .  It seems a template somewhere defines that.  
![image](https://media.github.ibm.com/user/6173/files/5785ef00-8eb9-11e9-8237-30d2d4f133b8)

**Comment by jeffchew** [comment]
_On Jun 17, james-dow commented:_
@linda-carotenuto not clear from your comment, but I just wanted to quickly point out that we already have a few templates similar to what you have provided. We could add more, remove, or whatever. 

https://github.ibm.com/webstandards/digital-design/issues/new/choose

Correct me if I'm wrong, but my understanding this issue is trying to address the current disconnect between our website (where users are), and GitHub (where we enter users to enter bugs). To your point though I think we could tie the two together a little better even if we're just linking out to the link above.

**Comment by jeffchew** [comment]
_On Jun 17, linda-carotenuto commented:_
Yes, let's tie the two together better by linking wherever and whenever possible to https://github.ibm.com/webstandards/digital-design/issues/new/choose instead of building our own contact module.   Do we feel the 3 choices we have are sufficient?

**Comment by jeffchew** [comment]
_On Jun 25, chsanche commented:_
@Benjamin-Hansen1 @linda-carotenuto 

#### If this is for the **Wedding Cake Website**.

Carbon does not have "Contact Us" but the [Support](https://www.carbondesignsystem.com/help/support) session. Can you take a look at what they have and see If we would like to implement the "Contact Us" feature on the new Gatsby website still? 

👉 If it's a yes, then let's have it on the IA work and see what do they think.
👉 If it's a no, then we can take a look at their Github issue creation experience as well and see what we can purpose to make it better.

We should be aligned before we do more work to it. Sounds good?

#### If this is for the **Cupcake Website**.
I agreed with Linda on linking it to the Git repo.

@Wonil-Suh1 FYI.

**Comment by RobertaJHahn** [comment]
Direction has changed.  Closing
