### ISSUE TITLE
Pattern: Create the Cards group functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2028]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Cards group` functional specs 

> so that I can:
so that I can properly code the `Cards group` pattern that meets the Solution template requirements

#### Additional information

- Design Issue (#2027  )
- Development issue (#2029)

#### Acceptance criteria
 - [ ] Documented `Cards group` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Completed first draft of func specs: https://ibm.box.com/s/j4z8axez3kee7jhdr8jt41cjq5ecsswm

**Comment by RobertaJHahn** [comment]
4/20/2020: Initial review with DDS engineering.  Ellen will work with the Reboot team regarding any changes discussed in the meeting.

**Comment by RobertaJHahn** [comment]
5/4/2020: Review of the revised specs with the engineers.

**Comment by ellenchoi1** [comment]
Reviewed and signed off on in engineering epic and story refinement meeting 5/4/2020
