### ISSUE TITLE
[NextJS] Create NextJS boilerplate application 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2047]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
have a NextJS boilerplate application with the IBM.com Library

> so that I can:
quickly deploy an application/website with the IBM.com Library that is compliant for IBM.com

#### Additional information

 - The test NextJS application can be used as a starting point: https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test
 - Should consider including any recommended linting setup (working being done here: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1937)
 - Current NextJS application has a workaround for setting the HTML lang attribute, should think of a more appropriate NextJS approach for setting it instead, that accommodates NextJs static deployments (this is the key part, setting the `lang` in `_document.js` via querystring works if it isn't a static deployment
- Set up placeholders for including items mentioned in https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/docs/building-for-ibm-dotcom.md (e.g. DDO object, alt languages, etc)

#### Acceptance criteria
 - [ ] Github repo with NextJS boilerplate
 - [ ] Proper documentation, easy enough for developers new to React

**Comment by jeffchew** [comment]
Bumping to high priority after discussing with @ljcarot

**Comment by annawen1** [comment]
Template currently lives on: https://github.com/annawen1/ibm-dotcom-library-nextjs-template
