### ISSUE TITLE
Component: Masthead L0 (React) Accessibility & Design QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2049]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `react Masthead`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- The Masthead was developed in the Fall of 2019 before the functional specs and QA testing processes were in place.  This testing is scoped for the testing that can be done without the functional specs.  The scope includes the Accessibility, Keyboard and Design review.
 - [Link to the pdf version of the designs](https://ibm.ent.box.com/file/653169404332)

#### Acceptance criteria
- [x] Accessibility testing is complete
- [x] Keyboard testing is complete
- [x] Design review is completed bu the India team members
- [x] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Lara will be creating the pdf file containing the Masthead visual designs and she will send a notification shortly.  I have created issue (#2050) for this work.  

cc:  @larahanlon2

**Comment by larahanlon2** [comment]
@Praveen-sr @chetankan here is the [PDF visual spec](https://ibm.box.com/s/3kzuz1px79mdi5cmc5mnrfo7zvqmjfru) for `masthead L0` only. Please let me know if you have questions/issues.

FYI @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Accessibility, Keyboard and Design review is complete.
