### ISSUE TITLE
Component:  Masthead L0 - provide the visual designs for the Prod QA testers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2050]
#### User Story

> As a `[user role below]`:
Digital Design Production QA tester

> I need to:
have links for the Masthead L0 visual designs in a format that can be opened on a Windows machine

> so that I can:
properly test the Masthead component

#### Additional information

 - [Link to the Masthead Box folder](https://ibm.ent.box.com/folder/59063660753)
 - The `masthead--visual-specs--UPDATE--march2020.sketch` is the sketch file in the Masthead folder for testing
 - Masthead (React) Prod QA testing issue (#2049)
 - Masthead (Vanilla) Prod QA testing issue (#1465)

#### Acceptance criteria
 - [x] The pdf version of the above mentioned sketch file is created and added to the Masthead Box folder
 - [x] A link is added to the `Masthead Prod QA testing issues`
 - [x] A message is posted in each `Masthead Prod QA testing issue` to Praveen and Chetan letting them know that the pdf design file(s) are available.

**Comment by larahanlon2** [comment]
Update: added [PDF visual spec](https://ibm.box.com/s/3kzuz1px79mdi5cmc5mnrfo7zvqmjfru) for `masthead L0` only.
