### ISSUE TITLE
Pattern: Update the Table of Contents functional specifications based on visual designs provided by Lila

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2052]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Table of Contents` functional specs 

> so that I can:
so that I can properly code the `Table of Contents` pattern that meets the Solution template requirements

#### Additional information

- The visual designs are scheduled to be provide by Lila in Sprint 20-10.  This issue is to account for the work to review the functional specs created in Sprint 20-07 and make any changes needed to align with the designs provided by Lila.         
- Design Issue (#2008  )
 - Development issue (#1851 )

#### Acceptance criteria
 - [ ] Documented `Table of contents` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
In the meeting today we decided to add an optional prop to allow any type of children to be passed into the space above the table of contents.

We also decided to add an optional divider that sits in between this childrern content, and the table of contents.

>❓we ran out of time before I could get an answer, but is this optional divider only present when children conten is passed in, or is it another boolean prop?

**Comment by photodow** [comment]
Here are the updates to the table of content. We can review together to make sure I got them all, or let me know if I missed something before if you get a chance.

https://ibm.ent.box.com/file/653668321798

**Comment by RobertaJHahn** [comment]
5/11/2020:  Reviewed in the meeting with DDS engineers.
