### ISSUE TITLE
Component:  Masthead:  Accessibility - Voiceover iPhone - Screen reader is not identifying the search icon

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2056]
## Detailed description
Issues :-
1. Screen reader is not identifying the search icon , screen reader users will not come to know about the presence of the mentioned control.
Instead when the focus comes to the mentioned  icon screen reader is reading " 
combo box list box collapsed", when we double tap here no action is happening.
2.  We understood from the sighted users that, Search edit combo list box
hidden by default and is supposed to be displayed only after activating the search icon. 
But, Screen reader is still identifying it even when it is visually hidden. 

Expected :-
1. Screen reader should identify the search icon.
2. When it is visually hidden, the screen reader should not identify this field.

## Additional information
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4dad413c-de50-4d95-8985-f0361b798609)

**Comment by kennylam** [comment]
@Praveen-sr @chetankan I am unable to reproduce this issue. The screen reading is working on my iPhone (actual device), running iOS 13.3.1. See attached video for screen recording from phone.

[RPReplay_Final1586876925.mp4.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/4476184/RPReplay_Final1586876925.mp4.zip)

**Comment by Praveen-sr** [comment]
Notes from the April 14 QA meeting: A blind user navigates the elements by swiping right or left. Another way of navigating is when the element pops up. A blind user cannot navigate this way.

Once the element is activated, the blind user swipes right. and the screen reader announcement should follow immediately.
