### ISSUE TITLE
Component: Masthead: Accessibility - Voice over iPhone - Issues related to Profile icon and hamburger menu

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2057]
## Detailed description
Device - iPhone

Issue :- 
1. screen reader is identifying the Profile icon control as menu item without any label.
2. Even when the hamburger  menu is collapsed screen reader is reading the options .

Expected :- 
1. Giving appropriate label.
2. screen reader should not read visually hidden components

**Comment by kennylam** [comment]
@Praveen-sr @chetankan I am unable to reproduce this issue. The screen reading is working on my iPhone (actual device), running iOS 13.3.1. See attached video for screen recording from phone.

[RPReplay_Final1586878623.mp4.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/4476247/RPReplay_Final1586878623.mp4.zip)


cc: @jeffchew @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Notes from the April 14 QA meeting:  A blind user navigates the elements by swiping right or left.  Another way of navigating is when the element pops up.  A blind user cannot navigate this way. 

Once the element is expanded, the blind user swipes right. and the screen reader announcement should follow immediately.
