### ISSUE TITLE
Component:  Masthead:  Accessibility - screen reader - Issues related to search edit combo list box

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2059]
## Detailed description

Device - Windows 10
Browser - Firefox

Issues :- 
1. This field is hidden by default and is supposed to be displayed only after activating the search icon. But, Screen reader is still identifying it even when it is visually hidden. 
2. No label for this control. ( Note: Placeholder is given instead of label.)

Expected :- 
1. When it is visually hidden, the screen reader should not identify this field. 
2. Placeholders should not be used as only means of label. provide a visual label and associate the same using label tag and for attribute. If that is not possible, Provide aria label

**Comment by kennylam** [comment]
@Praveen-sr @chetankan This is the correct behavior according to 

https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

cc: @jeffchew
