### ISSUE TITLE
Component: Masthead: Accessibility - Behavior of Search Edit Combo in tab/shift tab navigation.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2060]
## Detailed description

Issues :- 
Once the Search Edit Combo is displayed, when we navigate to the next control in the page with tab key, Search Edit Combo box disappears. Note: the same happens in Shift Tab navigation as well. This behavior confuses and disorients the user.

Expected :- 
When the user navigates to the next or previous control in the page, the search edit combo should not disappear.

**Comment by kennylam** [comment]
@chetankan @Praveen-sr  The functionality of the search is for it to close when it loses focus. This occurs whether the user is using a keyboard/mouse or screen reader. 

@jeffchew @ljcarot @wonilsuhibm If anything this is a UX issue, not accessibility. To me it doesn't make sense for the search to be persistent even after it loses focus. What do you guys think?

**Comment by kennylam** [comment]
@chetankan @Praveen-sr @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2095
