### ISSUE TITLE
Component:  Masthead:  Accessibility - Masthead Search open by default - Voice over iPhone - controls which aren't visually present are read. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2062]
## Detailed description

Device - iPhone 
Pattern / Component - Masthead - Search by open default 

Issue :- 
1. visually only Search  edit combo , search icon, close icon and the text "stock chart"
is present , but for screen reader users  screen reader is reading  controls which are not available visually.
for example hamburger menu, IBM logo link,  user profile button etc.
2. screen reader is not identifying the mentioned controls, screen reader users will not come to know about the presence of the mentioned control in left and right swipe.
Note: in form navigation screen reader is identifying the mentioned control.

NOTE: The above issues are present on  [Web components](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default) as well, need to fixed.

Expected :-
1. screen reader should not read visually hidden components
2. Screen reader should identify the control.

**Comment by RobertaJHahn** [comment]
@kennylam Another bug that I am closing based on the MegaMenu discussions in the 7/13 QA meeting.
