### ISSUE TITLE
Pattern: Masthead - Profile icon menu drop down spacing between section is not 48px.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2065]
## Detailed description

Issues :- The spacing between profile menu drop down section is not 48px,

Expected :- The spacing must be 48px, as per the design specs.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7923643a-4906-4733-8cd4-611516bf2a68)

**Comment by kennylam** [comment]
@Praveen-sr @chetankan @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2068

The deploy links are in the comments of the PR above.
