### ISSUE TITLE
Component:  Masthead: On hover, the platform background color is different compared to the menu list.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2066]
## Detailed description

Issue :- 
on hover, the platform background color is different compared to the menu list.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/47382c6b-014e-45f7-ae94-016b763d08b2)

**Comment by kennylam** [comment]
@Praveen-sr @chetankan @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2070

The deploy links are in the comments of the PR above.
