### ISSUE TITLE
Component:  Masthead: Menu item chevron is small compared to design specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2069]
## Detailed description

Issue :- The Menu item chevron is small compared to design, according to design chevron must be 20px icon.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8eb8e4bf-97ca-403f-bdd3-5d4466c4b447)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2238
