### ISSUE TITLE
Design kits – release to all of IBM planning

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#2072]
#### User Story

> As a `[user role below]`:

Designer at IBM
> I need :

access to the type styles and components available
> so that I can:

design a page that is production ready.

#### Additional information

 - We are planning to release the website to all of IBM so they can use the IBM.com Library 
- Currently, the Expressive design kit and IBM.com Library kit are in the same folder for our _closed adopters_
    - need to consider a new place for the Expressive kit

 - The current IBM Library Expressive design kit has a few issues that we need to consider:
    - Expressive type styles are not a part of the Carbon design kit, but we don't want team's using the productive headings on IBM.com 

    - The type styles could change value depending on how we implement the expressive theme.
    - The components in the Expressive kit are not available in code right now.
      - how does removing any components negatively effect the current users of the expressive kits?
   
  
How can we best serve our adopters and make it as easy and clear as possible for them to design for IBM.com?

#### Acceptance criteria
 - [x] Present idea for best experience for adopters to Linda, Wonil and Jeff
 - [x] Write any stories to update design kit

**Comment by oliviaflory** [comment]
Notes from meeting with Wonil, Lara and Jenny:

1. We will remove the existing Expressive kits and tell our sponsor adopter adopters

2. We will provide themed IBM.com Library kits (4 themes) 
   - type styles added
   - color tokens added
   - IBM.com components (new) added

3. MVP for Friday the 24th:
   - Release IBM.com Library (White theme)
   - Designers will use Carbon kits for components

**Comment by oliviaflory** [comment]
Here is a draft communication we should send out to any adopters who currently have access to the expressive kits with the expressive components before we remove it from the box folder. 

Hi everyone,
The IBM.com Library team has been working to develop an “expressive theme” of Carbon for IBM.com. At this time we do not have a solid timeline for when the expressive theme will be available for production, and therefor will be removing the expressive theme design kit. We feel this is the best decision until we have a solid timeline for you and your development teams. 
In the meantime we recommend using the Carbon design kit for core components, and utilizing the IBM.com Library for the type scales, masthead and footer.
We apologize for any inconvenience this may cause you, please reach out to Linda Carotenuto with any questions.

cc: @wonilsuhibm @ljcarot

**Comment by ljcarot** [comment]
Can you provide a link to where someone can find the Carbon design kit?

**Comment by oliviaflory** [comment]
That's a great idea Linda, I will include a link for the Carbon kits in the email. 

We will also have a link to the Carbon kits on our IBM.com Library site.

**Comment by ljcarot** [comment]
Ok, so we should spell out how they would use the core Carbon and why they would use the ibm.com library ones.

**Comment by oliviaflory** [comment]
I had written this to explain when to use Carbon, and when to use IBM.com Library for the email:
>In the meantime we recommend using the Carbon design kit for core components, and utilizing the IBM.com Library for the type scales, masthead and footer.

Jenny and Jacob are working with me to add those instructions to the website as well.

**Comment by oliviaflory** [comment]
Per conversation with Wonil, we will put the Expressive theme files in the Archive folder within the IBM.com Library design kit Box folder.
