### ISSUE TITLE
Increase unit test coverage for LocaleModal (React)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2077]
#### User Story

> As a `[user role below]`:
IBM.com Library Developer

> I need to:
have minimum of 80% unit test coverage of the LocaleModal

> so that I can:
test the functionality of the LocaleModal via unit tests

#### Additional information

![Screen Shot 2020-04-14 at 11 56 54 AM](https://user-images.githubusercontent.com/1641214/79253100-ab9e8e80-7e50-11ea-83d8-48b182b11ea0.png)

#### Acceptance criteria
 - [ ] Minimum 80% unit test coverage

**Comment by RobertaJHahn** [comment]
Prod QA issue was created.  Issue (#3236)

**Comment by RaphaelAmadeu** [comment]
https://github.com/carbon-design-system/ibm-dotcom-library/pull/3222
Link to PR
