### ISSUE TITLE
Increase unit test coverage for LocaleAPI (Services)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2080]
#### User Story

> As a `[user role below]`:
IBM.com Library user

> I need to:
have minimum 80% unit test coverage of the LocaleAPI

> so that I can:
ensure the service has proper code coverage

#### Additional information

![Screen Shot 2020-04-14 at 1 16 58 PM](https://user-images.githubusercontent.com/1641214/79254236-709d5a80-7e52-11ea-971c-ff7ea1e961fc.png)

#### Acceptance criteria
 - [ ] Minimum 80% unit test coverage of the LocaleAPI

**Comment by jeffchew** [comment]
@RobertaJHahn FYI, moving this to the next release.

cc: @ccwilson-us-ibm-com @asudoh

**Comment by RobertaJHahn** [comment]
Moved to next sprint and updated airtable.
