### ISSUE TITLE
Pattern: Update the CTA section functional specifications based on visual designs provided by Lila

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2094]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA section` functional specs 

> so that I can:
so that I can properly code the `CTA section` component that meets the Solution template requirements

#### Additional information

- The visual designs were provided by Lila in Sprint 20-08.  This issue is to account for the work to review the functional specs created in Sprint 20-07 and make any changes needed to align with the designs provided by Lila.        
- Design Issue (#2031 )
 - Development issue (#1852 )

#### Acceptance criteria
 - [x] Reviewed the `CTA section` functional specifications
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] If no changes are needed, sent a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by RobertaJHahn** [comment]
@photodow @kathysaraf @mbarry325 We missed this unassigned issue during the mid-sprint review meeting earlier today.  I created this issue as a reminder to check the functional specs created last sprint against the designs Lila delivered on Monday.

**Comment by photodow** [comment]
Just looked it over. Looks good, and will move to done.

**Comment by RobertaJHahn** [comment]
Reopened this issue to capture the changes decided in the April 21 visual specs review meeting with Lila.  The Content block pattern will not be separate, but included in the Content section pattern.

**Comment by kathysaraf** [comment]
updates done and ready
