### ISSUE TITLE
React error in masthead

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#2099]
"@carbon/ibmdotcom-react": "^1.5.1-rc.1",
"@carbon/ibmdotcom-styles": "^1.5.1-rc.1",
"@carbon/icons": "^10.9.2",
"@carbon/type": "^10.9.2",
"carbon-components": "^10.10.3",
"carbon-components-react": "^7.10.3",

![image](https://user-images.githubusercontent.com/15310250/79442874-65c10200-7fd9-11ea-86bb-fdd64dadce3d.png)

**Comment by jeffchew** [comment]
Hi @kyjak , is this impacting your application at all?
