### ISSUE TITLE
Language only selector in Footer locale selector - Prod level version

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#2100]
As per a meeting, if dotcom will provide a language rather a country selector,
KC will need also a callback on selection click so we can handle the url rewrite.
Right now, the footer takes the href from link rel="alternate" hreflang="cn-zh" href="/cn-zh" 
we need to suppress this behavior and get a callback instead.

**Comment by jeffchew** [comment]
Hi @kyjak ,

I want to clarify what the scope of the feature request is:

1) Create a property on the footer level to replace the locale button with a `languageOnly` option
2) Provide a data structure for populating the language selector. Example:

```
languageData = [
  {
    label: 'English',
    url: 'https://www.ibm.com/',
    callback: () => {}
  },
  ...
]
```

3) The logic will be url by default, or if callback is defined, will use that instead
4) The language selector will be a standard dropdown

**Comment by kyjak** [comment]
hello,
yes, we can provide an array with available languages to the footer.
there is no need for a separate callback on each entry, a global one with a parameter what language was chosen is enough.
so something like
languageData = [
{
label: 'English', code: 'en'
},
{
label: 'Slovak', code: 'sk'
}
]
and after picking a common callback (set as a prop for example for the footer) would be called as callback('sk')

but other web projects might have different needs, maybe they need also url and separate callback, so we are open to a dialog on this. not sure if KC is the only one for this feature.

we also have a filtering mechanism to search for a language, but that needs confirmation
from our designers, but 90% sure it will stay. look on the current KC page for inspiration

**Comment by jeffchew** [comment]
Right, we may just have an open callback method that is injected into the `Footer`, which is used by the item on select. We can just pass in the event object so you can do whatever is needed with it. Something like this:

```
languageData = [
  {
    label: 'English', value: 'en'
  },
  {
    label: 'Slovak', value: 'sk'
  },
  ...
]
```

and:

```
<Footer 
    languageOnly={true} 
    languageCallback={event => yourCallbackMethod(event)} 
    languageData={languageData} 
/>
```

We were thinking possibly to use the Carbon ComboBox for filtering:
https://react.carbondesignsystem.com/?path=/story/combobox--default

Thoughts @ljcarot @wonilsuhibm ?

**Comment by jeffchew** [comment]
@RobertaJHahn we probably need to turn this into an epic. We will will stories for:
- design/visual specs
- functional spec updates
- dev story for implementation
- prod qa
- design qa

**Comment by kyjak** [comment]
this seems to be implemented already, closing
