### ISSUE TITLE
Update LightboxMediaViewer to use Modal instead of ComposedModal

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2101]
#### User Story

> As a `[user role below]`:
IBM.com Library Developer

> I need to:
have LightboxMediaViewer uses the Modal instead of ComposedModal

> so that I can:
ensure the Carbon modal used is supported in the future

#### Acceptance criteria
 - [ ] LightboxMediaViewer using Modal instead of ComposedModal

**Comment by asudoh** [comment]
Refs:

https://carbon-website-q8k84dquw.now.sh/components/modal/code
carbon-design-system/carbon-website#1126

**Comment by RaphaelAmadeu** [comment]
This issue can be closed, as the `ComposedModal` is the latest Modal component on Carbon.
After a meeting with @kennylam and @asudoh , we agreed in contributing back to Carbon the accessibility fix for `ComposedModal`.

Thanks!
cc: @jeffchew @RobertaJHahn

**Comment by kennylam** [comment]
PR created for this change in the Carbon component

https://github.com/carbon-design-system/carbon/pull/6120
