### ISSUE TITLE
Pattern: CTA section Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2113]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `CTA section`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Functional specs issue (#2094) 
- Dev Issue (#1852)
 - [Design and Functional specs Box folder](https://ibm.ent.box.com/folder/109648616047) 

 #### Tasks
Ensure the `CTA section` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by guilhermelMoraes** [comment]
@RobertaJHahn @wonilsuhibm good morning! Just bringing to your attention that the `CTASection` development was finished. 

Here's the link to the Pull request: https://github.com/carbon-design-system/ibm-dotcom-library/pull/2336

Here's the link to the `CTASection` preview: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2336/index.html?path=/story/patterns-sections-ctasection--default

**Comment by ltitle** [comment]
@RobertaJHahn All design QA tickets have been logged for this pattern

https://github.com/carbon-design-system/ibm-dotcom-library/issues/2355
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2356
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2357
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2358
