### ISSUE TITLE
Pattern: CTA section QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2114]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `CTA section`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- Design Issue (#2031)
- Functional specs issue (#2094) 
- Dev Issue (#1852)
 - [Design and Functional specs Box folder](https://ibm.ent.box.com/folder/109648616047) 

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I am starting to create the testing issues for the Solutions page template patterns.  This issue is scheduled to be done in sprint 20-10 (May 11 - 22).  It is blocked by the development issue, but the work may begin as soon as the development is finished.  You should get a notification from the developer when their work is finished.

**Comment by guilhermelMoraes** [comment]
@Praveen-sr @chetankan just bringing to your attention that the `CTASection` development was finished.

Here's the link to the Pull request: #2336

Here's the link to the `CTASection` preview: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2336/index.html?path=/story/patterns-sections-ctasection--default

**Comment by RobertaJHahn** [comment]
5/14/2020:  Prod QA testing has started.
