### ISSUE TITLE
Pattern: Callout - quote QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2115]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Callout - quote`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- Design specs issue (#2002  )
- [Visual and design specs Box link](https://ibm.ent.box.com/folder/110327678801)
- Functional specs issue (#1830  )
 - Callout [#1809] [[Directory](https://ibm.box.com/s/6b6pdgql2y3zxja2soj058t0ev8zwzik)]
 - Quote [#1806] [[Directory](https://ibm.box.com/s/0hjsr1foe5y849xs6ixc5g25uf9lgjr6)]
 - Dev issue (#1853)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I am starting to create the testing issues for the Solutions page template patterns.  This issue is scheduled to be done in sprint 20-10 (May 11 - 22).  It is blocked by the development issue, but the work may begin as soon as the development is finished.  You should get a notification from the developer when their work is finished.

**Comment by chetankan** [comment]
@RobertaJHahn @Praveen-sr  : Functionality testing is done, and screen reader is in progress.
