### ISSUE TITLE
Pattern: Callout - quote Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2116]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Callout - quote`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Dev Issue (#1853 )
 - Design specs issue (#2002  )
- [Visual and design specs Box link](https://ibm.ent.box.com/folder/110327678801)
- Functional specs issue (#1830  )
 - Callout [#1809] [[Directory](https://ibm.box.com/s/6b6pdgql2y3zxja2soj058t0ev8zwzik)]
 - Quote [#1806] [[Directory](https://ibm.box.com/s/0hjsr1foe5y849xs6ixc5g25uf9lgjr6)]

 #### Tasks
Ensure the `Callout - quote` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn All issues for design QA have been logged:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2399
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2398

Open item that @photodow is looking into for making sure we can have all 3 fields show for the quote source.
