### ISSUE TITLE
Pattern: Callout - with media Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2117]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Callout - with media`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Functional specs issue (#1831 ) 
- Dev Issue (#1854 )
 - [Design and Functional specs Box folder](https://ibm.ent.box.com/folder/110327422852) 

 #### Tasks
Ensure the `Callout - with media` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by andysherman2121** [comment]
@wonilsuhibm @robertajhahn development is finished

**Comment by ltitle** [comment]
@RobertaJHahn All design QA issues have been logged for this pattern:

https://github.com/carbon-design-system/ibm-dotcom-library/issues/2395
