### ISSUE TITLE
Pattern: Feature card block - large:  Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2119]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Feature - block`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2004  )
- Functional specs issue (#1834  )
- [Design & Functional specs Box folder](https://ibm.ent.box.com/folder/110327688617)

 #### Tasks
Ensure the `Feature - block` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by reesedownes** [comment]
This is ready for testing

https://github.com/carbon-design-system/ibm-dotcom-library/pull/2334

**Comment by reesedownes** [comment]
@wonilsuhibm @RobertaJHahn didn't tag you both before

**Comment by ltitle** [comment]
@RobertaJHahn All design QA tickets have been logged for this pattern
