### ISSUE TITLE
Update Locale Modal to use the ModalWrapper instead of ComposedModal

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2124]
#### User Story

> As a `[user role below]`:
IBM.com Library Developer

> I need to:
have LocaleModal uses the ModalWrapper instead of ComposedModal

> so that I can:
ensure the Carbon modal used is supported in the future

#### Acceptance criteria
 - [ ] LocaleModal using ModalWrapper instead of ComposedModal

**Comment by kennylam** [comment]
duplicate of #2101
