### ISSUE TITLE
Component - Masthead - On mobile landscape mode - menu does't have a scroll option.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2128]
## Detailed description
Device :- iPhone and Android
Browsers :- Safari and Chrome 

Issue :- 
On Mobile landscape mode, menu option which are at the end are not visible as the user can not scroll down to see the menu options.

## Additional information
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4c349a39-2c8f-4c22-84ae-9293c7ba4419)

On portrait mode : all the options are visible 

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/bc6833a7-7eef-4db5-80c7-d2ef6a443820)

**Comment by RobertaJHahn** [comment]
Code is merged.  Closing
