### ISSUE TITLE
Create translation files for IBM.com Library

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-dotcom-library#2137]
### The problem
The following languages require translations for use in the IBM.com Library:

- ~German~
- French
- ~Italian~
- Spanish (Castilian)
- Spanish (LA)
- Portuguese (Brazil)
- ~Polish~
- ~Russian~
- Turkish
- ~Chinese (simplified)~
- Chinese (traditional)
- Japanese
- Korean
- Arabic (edited) 

### The solution
Translation files are required for IBM.com Library components, such as the masthead, footer, and locale selector.

### Additional information
https://github.ibm.com/webstandards/ibm-dotcom-library-translations

**Comment by jeffchew** [comment]
Couple of thoughts:
1) Can we rename the repo to: `IBM.com - Translations`? (drop the `Library`)
2) rename the `translations` folder to `countrylist`
3) possibly speak with Miroslav and migrate the masthead/footer translations into this repo? (e.g. `/masthead-footer` folder in the root
4) If #3 is a go, then we can create a Jenkins job to support this too

**Comment by RobertaJHahn** [comment]
@jeffchew @ljcarot Cna I close this issue or should it move to sprint 20-10?
