### ISSUE TITLE
Test Migrate Functional Specs to Confluence

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2138]
#### User Story
> As a `[user role below]`:
IBM.com Library functional analyst

> I need to:
understand the effort to migrate functional specs to Confluence

> so that I can:
understand the effort required and what the process across other teams might look like.

#### Additional information
The IBM.com Reboot, and Drupal team is evaluating using confluence. We need to look at the effort on our side, and how our pieces fit in. To start things off we'll migrate one or two of our functional specs to help with some of that evaluation.

#### Acceptance criteria
 - [ ] Content Block — Segmented
 - [ ] Leadspace
 - [ ] `Stretch goal` any lower level patterns needed to support the above.

**Comment by RobertaJHahn** [comment]
Kathy and James will follow-up with Lily to see whether this work is still needed.

**Comment by photodow** [comment]
Changed pipeline to icebox since this is currently on hold while the budget discussions happen.
