### ISSUE TITLE
Pattern: Content Block(with aside elements):- Copy text and linklist section are not getting displayed properly on mobile devices.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2142]
Issue description:- In 'Content Block-->with aside elements' sub-pattern copy text is displayed with no spacing on left side of the screen whereas linklist section is not getting displayed properly. Happening on all mobile devices(iOS and Android) 
## Steps to reproduce the issue

1. Enter the url in the mobile browser.
2. Select 'Content Block' in sub-pattern section.
3. Select 'with aside elements' in content block
4. observe the 'Copy' text and 'Linklist' section.

OS:- iOS 13,12. Android 9,8
Devices:- iPhone, Galaxy, Google Pixel
Browsers:- Safari, Chrome, UC

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/patterns-sub-patterns-contentblock--with-aside-elements
![Content block copy text .png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/6f528b13-d8fd-46e5-a8c8-5e2168730909)![Content block linklist section.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/6a405eae-58c9-4936-8f9e-c0aa6c13901d)

**Comment by chetankan** [comment]
@jeffchew @RobertaJHahn : Same issue with **'Content Block Simple'** pattern where on selecting render aside element, copy text is displayed with no spacing on left side of the screen whereas linklist section is not getting displayed properly. Happening on all mobile devices.

Note:- As discussed in yesterday's call , nature of issue is same but in different pattern so i am adding comment here.

**Comment by annawen1** [comment]
Thanks @chetankan PR has been raised and merged into release branch to fix this issue for ContentBlock, ContentBlockMedia, ContentBlockSegmented, ContentBlockSimple, and ContentBlockMixed.
