### ISSUE TITLE
Locale banner mobile prototype

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#2144]
### Objectives
Build a mid-to-high fidelity prototype that reflects the mobile design so that it can be tested against users.

### Acceptance criteria
- [ ] A prototype has been built and is available for user testing

**Comment by RobertaJHahn** [comment]
Closing as this work has been transferred to the Ideation Board.  Here is the link.

https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/23
