### ISSUE TITLE
Pattern: Callout Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2150]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Callout`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2010)
 - Functional spec issue (#1837)
- [Functional specs](https://ibm.ent.box.com/file/653654334281)
 - Dev issue (#1860)
 - Prod QA testing issue (#2151 )

 #### Tasks
Ensure the `Callout` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by andysherman2121** [comment]
@wonilsuhibm @RobertaJHahn Development of the Callout component is finished

**Comment by RobertaJHahn** [comment]
Closing this issue as the testing will be done as part of the Callout with Quote and Callout with media patterns.
