### ISSUE TITLE
Fix the bottom nav location

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#2154]
#### Task: 

Make sure the bottom nav is in the correct location on the homepage.

(Left: What's on our website// Right: What it should look like)![Bottom nav.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/56ec15bb-0448-4de3-8d1d-4c9e838d6dfb)

**Comment by JennySanchez** [comment]
@wonilsuhibm @jeffchew Can you two take a look at this and see if this is something we can get the fix in before the release this Friday?

FYI - @RobertaJHahn

**Comment by RobertaJHahn** [comment]
This issue may be fixed by upgrading to the current Carbon Gatsby version.

**Comment by JennySanchez** [comment]
@wonilsuhibm @jacobottesen-dgc 

I clicked around and it looks fine to me but for testing purposes. Can you two help by clicking around the website via the bottom nav to see if anything broke before we merge the change?

Deploy preview link is here:
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/413/index.html

**Comment by jacobottesen-dgc** [comment]
The resource card on the homepage is gone. Do we want that?

![Screen Shot 2020-04-22 at 2.41.18 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/dbff9b81-3c60-4d52-bc8e-a523d1047632)

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Yes, we do. So weird, it was there earlier. 

@kennylam Can you help by taking a look? I am not sure if this has anything to do with the image update we talked about earlier.

Thank you!

**Comment by kennylam** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #430](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/430) via [**ZenHub**](https://www.zenhub.com/)
