### ISSUE TITLE
Pattern- Content Item- Spacing issue between component copy text and caption text

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2166]
Issue description:- In content item pattern on selecting 'Video' under media type there is not spacing between video caption and component copy text.

## Steps to reproduce the issue

1. Enter url in the browser. 
2. Select 'Video' under media type
3. Observe the spacing difference between caption text and component copy text.

OS:- Windows 10, Mac, iOS 12, 13, Android 8,9
Browsers:- Chrome, Firefox, Safari, UC, Edge

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/patterns-sub-patterns-contentitem--default![Spacing issue in content item pattern.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/95e530e1-051e-41e5-975e-e9f2d100e0bf)

**Comment by greeshmareddyg** [comment]
@chetankan @RobertaJHahn There is a 32px space between caption and the copy in desktop and mobile. 

![image](https://user-images.githubusercontent.com/21186867/82473647-e622c900-9a97-11ea-8794-7fcdcf1684fc.png)

![image](https://user-images.githubusercontent.com/21186867/82473690-f6d33f00-9a97-11ea-9d04-604aedf7c3fe.png)

**Comment by chetankan** [comment]
@RobertaJHahn @greeshmareddyg : I have verified in 'React-experimental' env and now spacing is 32px between media type and copy text.

**Comment by greeshmareddyg** [comment]
@chetankan @RobertaJHahn yeah, we merged the fix yesterday.
