### ISSUE TITLE
Component - Lightbox Media Viewer - Description display issue on entering more text on mobile devices.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2167]
Issue description:- On mobile devices in lighbox media viewer component on entering large amount of text in description , description text is going behind the video player and title text is not visible.

## Steps to reproduce the issue

1. Enter url in the browser.
2. Enter large amount of text in description field.
3. Open the pattern in new page.
4. Check if description and title is displayed properly.

OS:- iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, UC

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player![Embedded video player with more text.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/78b9effe-225f-4166-a769-1de17751fc37)

**Comment by greeshmareddyg** [comment]
@chetankan could you please check if we still have this issue. I tried to enter some text, looks fine.

![image](https://user-images.githubusercontent.com/21186867/82585464-0750eb80-9b64-11ea-86e7-cb282cab66d5.png)

**Comment by chetankan** [comment]
@greeshmareddyg : Lightbox Media Viewer---> Embedded Video Player , in knobs section there is no description section to enter text.

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player 

![Embedded videoplayer knobs section.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/f1887a30-7cab-4e72-8244-2db47780bc6a)

**Comment by greeshmareddyg** [comment]
@chetankan Yeah, with the current video component we can't send the description, it is coming from API with video. I have tested with the dev tool by entering a large text.

**Comment by RobertaJHahn** [comment]
Closing this issue based on Greeshma's comments.
