### ISSUE TITLE
Pattern: Content block - with cards:   Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2170]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content block - with cards`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Dev Issue (#1855 )
 - Design specs issue (#2033  )
- [Visual and design specs Box link](TBD)
- Functional specs issue (#1832  )

 #### Tasks
Ensure the `Content block - with cards` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is done and all issues have been logged:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2417
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2418
