### ISSUE TITLE
Component: Create the Language only selector functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2183]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Language only selector` functional specs 

> so that I can:
so that I can properly code the `Language only selector` component

#### Additional information

- Jeff's implementation suggestions are included in the linked epic (#2100)
- The KC team beginning their Carbon implementation with design studies.  [Existing Knowledge Center site](https://www.ibm.com/support/knowledgecenter/)
- Language only selection in the footer is also required by other sites.  
- An experimental `language only selector` was provided to the Knowledge Center team for their design research.  This work informs the development of the Production level version.  This experimental work is managed in epic (#2100)
- Design Issue (#  )

#### Acceptance criteria
 - [ ] Documented `Locale Selector` Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by ljcarot** [comment]
I don't recall why we iceboxed this issue @jeffchew @RobertaJHahn  do you?

**Comment by RobertaJHahn** [comment]
Closing.  See comments in epic (#2100)
