### ISSUE TITLE
Pattern: Card visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2190]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - Visual Design & Functional Specs Box folder link

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
@RobertaJHahn Sketch and PDFs for visual design specs are posted here: https://ibm.ent.box.com/folder/95514001950

@photodow This includes the video card. Specs posted here: https://ibm.ent.box.com/file/657576937319

**Comment by RobertaJHahn** [comment]
5/4/2020:  Lila and Shixie reviewed the updated Card visual designs and specs with the DDS and Drupal designers and engineers.  The review included the new video cards requirement included for the Solution template.
