### ISSUE TITLE
Pattern: Card link visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2192]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Design & Functional Specs Box folder link](https://ibm.ent.box.com/folder/111327301483)

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
@RobertaJHahn PDF and Sketch file for visual specs posted here: https://ibm.ent.box.com/folder/111327301483
