### ISSUE TITLE
[Card] Hover image darken/lighten 8% instead of 20%

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#2195]
Currently, images in `Card` get a 20% darken effect on Hover. Need to update this effect to: 

**White and Gray 10 themes:** 
default cards: `darken(8%)`
inverse cards: `lighten(8%)`

**Gray 90 and Gray 100 themes:** 
default cards: `lighten(8%)`
inverse cards: `darken(8%)`

See prototype: https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A81&scaling=min-zoom

![image](https://user-images.githubusercontent.com/15144993/80248130-4f502180-863d-11ea-8b15-dfb3c31f944d.png)

**Comment by annawen1** [comment]
Hi @shixiedesign this bug has been reported already here: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2205

We can track the bug with the issue above and close this one to reduce duplication. Thanks!

**Comment by RobertaJHahn** [comment]
@annawen1 #2205 is for feature card.  Will that fix apply to all of the Card patterns?

cc: @ltitle @shixiedesign

**Comment by annawen1** [comment]
@RobertaJHahn `FeatureCard` uses `Card` and `Card` is where the darken/lighten styles are being applied. So adjustment to `Card` component will apply to all other `Card` patterns. 

I guess we can open this one back up and close #2205
