### ISSUE TITLE
[Card] Hide "static" cards as an option from Storybook

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#2197]
Currently, there are "[static cards](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-card--static)" where only the link *inside* the card is clickable. We want to hide this option because: 

1. This is not good UX 
2. Upon investigation, there's no use case for a "static" cards. All cards should be completely clickable anywhere on the card

**Slack discussion result:** 
Instead of removing this card all together, just hide the card from Storybook to keep it in case an unforeseeable future need for it arise.

This is related to https://github.com/carbon-design-system/ibm-dotcom-library/issues/2196

**Comment by larahanlon2** [comment]
We need to understand where static card is beign used today and if there is a need for it moving forward. Maybe designers do not need to see or use this but do devs? TBC.

**Comment by RobertaJHahn** [comment]
Moving into backlog for a developer to investigate how/whether this pattern is being used.
