### ISSUE TITLE
Component: Masthead: On hover, the search and profile background color is different compared to the menu list.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2204]
## Detailed description

Issue:- When user hover on search and profile icon, background color is lighter shape compared to menu and IBM logo background.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/49beda2c-2bf4-432a-8915-f871aae7c4e8)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2236
