### ISSUE TITLE
[Feature Card] Hover image darken/lighten 8% instead of 20%

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2205]
This change is the result of design changes.  The designs have been updated with these changes.  
Currently, images in Card with images get a 20% darken effect on Hover. Need to update this effect to:

**White and Gray 10 themes:**
default cards: darken(8%)
inverse cards: lighten(8%)

**Gray 90 and Gray 100 themes:**
default cards: lighten(8%)
inverse cards: darken(8%)

See prototype: https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A81&scaling=min-zoom

<img width="1001" alt="Screen Shot 2020-04-27 at 9 33 52 AM" src="https://user-images.githubusercontent.com/47458576/80384287-50b26180-886a-11ea-80fc-fffa839e53b9.png">

**Comment by annawen1** [comment]
We have a ticket for the `Card` component on the darken/lighten style (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2195). Since fix for the `Card` component will also apply to the `FeatureCard` and other Card patterns, I'll close this ticket to avoid duplication.
