### ISSUE TITLE
[Feature card] Arrow should be Blue

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2207]
This change is the result of design changes.  The designs have been updated with these changes.  

The arrow in feature card should be $link-01. See below
<img width="1530" alt="Screen Shot 2020-04-27 at 9 38 48 AM" src="https://user-images.githubusercontent.com/47458576/80384773-e8b04b00-886a-11ea-81b3-ed74231bf0c8.png">

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu I assigned this request to you as well.  (Sorry, but your worked on this pattern.)  This issue has been assigned to the June release.  The code freeze is June 12.  

cc:  @jeffchew

**Comment by peter-garvin** [comment]
Looks like its correct now:
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-sub-patterns-featurecard--default

**Comment by RaphaelAmadeu** [comment]
@peter-garvin 
In this case, can we close this issue?
