### ISSUE TITLE
Finalize RTL language guidelines 

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#2209]
#### User Story

> As a `IBM.com creator`:
> I need to:
understand how to design and develop RTL

> so that I can:
correctly implement RTL pages throughout the IBM.com experience.
#### Acceptance criteria
 - [ ] _{{Finalized RTL content with content strategist}}_
 - [ ] _{{Produce production ready images}}_
 - [ ] _{{Review with RTL language expert}}_

Box note rough draft: https://ibm.box.com/s/oxlh87ivzrlz9x0j2wnm01ztsn0lnzns

**Comment by RobertaJHahn** [comment]
Moving to backlog as the RTL expert has to be identified.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #638](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/638) via [**ZenHub**](https://www.zenhub.com/)
