### ISSUE TITLE
July 2020 Release Plan (v1.9.0) 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2220]
# Timeline

- **July 17, 2020**: Code freeze
- **July 20 - 27, 2020**: Release Candidate(s) and testing
- **July 29, 2020**: Full Release

## Global
- **Upgrade to Carbon 10.15.0** (#3163)

### Features
- We're excited to bring you the expressive theme, available as a framework agnostic solution in our styles package! We have a lot of documentation to update on our end, but the technical implementation is available for testing. You can see a working version available, along with implementation details at http://carbon-expressive.mybluemix.net/ (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2784)

#### Patterns are now Components!

Similar to the pivot from `v1.8.0` release for `sub-patterns`, we have now consolidated all `patterns / blocks` and `patterns / sections` into `components`, so now all `coded things` are considered as `components`! With this change, the `scss` imports have now been remapped under `/scss/components`, however we have kept a deprecation import so that nothing breaks (for now) on the application side.  A deprecation warning will show for imports pointing to the patterns folder, which we will ultimately remove in a future release.

### Features
- **Link with icon inverse theming enhancement** (#2294 )
- **Content Block Segmented - copy field should be made optional** (#2574 )
- **Masthead L0 (React) - Production level** (#1464 )
- **Pattern: Callout - with data: include single proof point - Services template MVP requirements** (#2819 )
- **CalloutData**:  _new experimental pattern created_ (#2873)
- **Added codesandbox example implementations** (#2846, #2844, #2843, #2808, #2806, #2804, #2773, #2763, #2759, #2745, #2809)
- **TableOfContents**:  _fixed missing hover and hidden default label_ (#2606)
- **CTA section - remove the horizontal rule when no content items are given** (#2778 )
- **Link with icon - Allow a user to set icon on the right or the left of text** (#2416 )
- **Pattern: Content block - headlines - new Reboot pattern** (#3005 )

### Fixes
- **Fix Leadspace Block: Grid alignment** (#2618 )
- **Pattern: Content item horizontal: Bottom padding fix** (#2676 )
- **Pattern: Leadspace Block: Link list rules fix** (#2619 )
- **Pattern: Content group: Text lengths fix** (#2623 )
- **[Card] Hover image darken/lighten 8% instead of 20%** (#2195 )
- **Inline and Linklist Video Player error fix** (#2502 )
- **VideoPlayer**:  _ensure only the video thumbnail for the video clicked gets removed from DOM_ (#2857)
- **LanguageSelector**:  _placeholder prop added_ (#2807)
- **LeadspaceBlock**:  top & bottom spacing (#2892)
- **CTASection**:  _adjust spacing when no content items_ (#2796, #2197)
- **Quote**:  _optional `copy2` prop added to the component_ (#2605)
- **Content item horizontal: Misalignment to grid fix** (#2673 )
- **Content block - with cards: Fix grid alignment in Storybook at large breakpoints** (#2418 )
- **Remove different color background between logo cards for g10 and g90 - Storybook** (#2829 ) 
- **Pattern: Leadspace block: Make spacing between intro and media 32px on small breakpoint** (#2617 )
- **Callout with data: Spacing fixes** (#2966 )
- **Pattern: Leadspace Block: Link list rules** (#2619 )
- **Pattern: Content group: Text lengths** (#2623 )
- **Pattern:  Content block - with cards: Ensure correct grid usage in Storybook** (#2418 )
- **Pattern: Callout with data: Source text width** (#2976 )
- **Pattern:  CTA Section - incorrect horizontal rule fix** (#2355 )
- **Pattern: Content group horizontal: Grid alignment fix** (#2670 )
 - **Experimental Language selector current language display label fix** (#2319 )
- **LinkList `default` and `vertical with cards` grid fix** (#2832 )
- **Fix spacing under the intro paragraph in each content group pattern** (#2624 )
- **Card Link: Incorrect grid alignment fix** (#2594 )

### Features
- This is a brand new package in the IBM.com Library, and is our strategic future for any non-React implementations! We are still in pre-release for this, and will be looking at an MVP of this for later this year. (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2882)
- Masthead (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2861)
- CardLink (#2987)
- LightboxMediaViewer(#3130)
- Text CTA (#3129)
- Expressive Modal (#2988)

**Comment by jeffchew** [comment]
@RobertaJHahn release has been created: https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.9.0

cc: @kennylam
