### ISSUE TITLE
Pattern: Change the Card functional specifications to include video

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2226]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card` functional specs 

> so that I can:
so that I can properly code the `Card` component that meets the Solution template requirements

#### Additional information

- Design Issue (#2190 )
- The Card pattern will support presenting a video within the card.
- Sketch and PDFs for visual design specs are posted here: https://ibm.ent.box.com/folder/95514001950
- Includes the video card specs posted here: https://ibm.ent.box.com/file/657576937319
 - Development issue (#2227 )

#### Acceptance criteria
 - [ ] Created the `Card` functional specifications and posted to Box folder
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] If no changes are needed, sent a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by RobertaJHahn** [comment]
Lila provided visual specs for video.  This issue is open to determine the impact to the Card func specs or any other specs based on implementation.  Is this work included in the CTA component or included in the Card.

**Comment by photodow** [comment]
Shixie reviewed the video card in our last design review. Here are a couple notes on the topic, and outstanding concerns...

Designs and specs should be updated in the box folder with the latest...
https://ibm.ent.box.com/folder/95514001950

#### Notes
- Poster image is coming from API
  - [ ] @jeffchew and @kennylam will review the kaltura API for capabilities, dimensions and such.
  - [ ] @ellenchoi1 is setting up a meeting with Media Center to discuss our image requirements
- Duration will obviously come from API
- Heading will default come from API, but can optionally be overridden from the adopter in cases where it's too long.
- The play button icon overlaying the image has opacity and is seperate. No interaction. Interactions follow the card pattern to date (minus any open bugs)
- Video is open in the Light box media viewer when click. The video API will drive this.
  - [ ] @photodow will reach out to Jill Stuart to see if copy is needed (it's currently built with copy today)
  - Heading and copy both will be generated by the API
- All this conversation made me realize we're missing the poster image for the current video player. Here is the issue for this: #2312
- [ ] Need to update the functional specs based on these updates.

**Comment by RobertaJHahn** [comment]
Progress on this work is blocked by some decisions needed by the Reboot team.

**Comment by ellenchoi1** [comment]
SEO analysis provided on potential page discoverability when videos are played in a lightbox viewer concluded there is no negative impact therefore we are okay to move forward with this work.

**Comment by RobertaJHahn** [comment]
Closing based on Ellen's comment above.
