### ISSUE TITLE
lightbox html issue

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#2229]
## Detailed description
Title and description is not injecting to the right div tag instead it's adding it to the parent div tag. 

> Describe in detail the issue you're having.
ex:
    <section class="bx--lightbox-media-viewer" data-autoid="dds--lightbox-media-viewer">
      <div class="bx--modal is-visible bx--modal--expressive bx--modal--expressive--fullwidth" data-autoid="dds--expressive-modal" **description="{{ content.field_description }}**"
           open="" role="presentation"
           tabindex="-1" **title="{{ node.field_imagefile_s.title }}"**>
        <div class="bx--modal-container">
          <button class="bx--modal-close" data-autoid="dds--expressive-modal__close" title="Close" type="button">
            <svg aria-label="Close" class="bx--modal-close__icon" focusable="false"
                 height="20" preserveAspectRatio="xMidYMid meet" role="img" viewBox="0 0 32 32" width="20"
                 xmlns="http://www.w3.org/2000/svg">
              <polygon
                points="24 9.4 22.6 8 16 14.6 9.4 8 8 9.4 14.6 16 8 22.6 9.4 24 16 17.4 22.6 24 24 22.6 17.4 16 24 9.4"></polygon>
            </svg>
          </button>
          <div class="bx--modal-content">
            <div class="bx--lightbox-media-viewer__container">
              <div class="bx--lightbox-media-viewer__row">
                <div class="bx--lightbox-media-viewer__media bx--no-gutter"></div>
                <div class="bx--lightbox-media-viewer__media-description bx--no-gutter">
                  <div class="bx--lightbox-media-viewer__content"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

> Is this a feature request (new component, new icon), a bug, or a general
> issue? Yes

> Is this issue related to a specific component?LightboxMediaViewer

> What did you expect to happen? What happened instead? What would you like to
> see changed? Title and description to added to right div tag 

> What browser are you working in? Chrome

> What version of the IBM.com Library are you using?1.6.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by annawen1** [comment]
Hi @sridharmula could you provide us with more details? 

We currently are not injecting the title and description into any html tags for the lightbox. Are you perhaps looking for the title and description classnames?

`bx--lightbox-media-viewer__content__title` and `bx--lightbox-media-viewer__content__desc`

**Comment by sridharmula** [comment]
@annawen1 in the story book we have title and desc displayed  on the right side  assuming which was generated from media object
media={
      src: select('Image', images, images['1280 x 720 (16:9)']),
      alt: 'Image alt text',
      title: text(
        'title (required)',
        'Curabitur malesuada varius mi eu posuere'
      ),
      description: text(
        'description (required)',
        `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est.Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin, sodales nulla quis, consequat libero. Here are some common categories:`
      ),
      type: 'image',
    }
but when we try to generate the html for Drupal those two fields are injecting to parent div tag.

 https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-lightboxmediaviewer--default

**Comment by annawen1** [comment]
Closing this as I believe the issue has been resolved
