### ISSUE TITLE
Pattern: Create the Card link functional specifications based on visual designs provided by Lila

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2233]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card link` functional specs 

> so that I can:
so that I can properly code the `Card` component that meets the Solution template requirements

#### Additional information

- Design Issue (#2192 )
 - [Visual Design & Functional Specs Box folder link](https://ibm.ent.box.com/folder/111327301483)
 - Development issue (#2235 )

#### Acceptance criteria
 - [ ] Created the `Card` functional specifications and posted to Box folder
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] If no changes are needed, sent a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Completed initial draft of func specs: https://ibm.box.com/s/ustc10nb9q03g0ya3pyhymqn3j68pgq1

**Comment by RobertaJHahn** [comment]
4/20/2020:  Reviewed func specs with dev.
