### ISSUE TITLE
Pattern: Card link Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2234]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card link`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design issue (#2192)
- There is a feature request that has been included in these latest designs.  This code version should include this feature request and should be verified as part of this QA effort.  It is:  
- **[Card link] Add disabled state**  (#2208)
- Functional specs issue (#2233) 
- Dev Issue (#2235)
 - [Visual Design & Functional Specs Box folder link](https://ibm.ent.box.com/folder/111327301483)

 #### Tasks
Ensure the `Card link` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn Is this ready? Is there a storybook link?

**Comment by RobertaJHahn** [comment]
Kenny just merged the code today.  Here is the storybook link.

https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-cardlink--default

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is now complete for this pattern. Pete has logged the following issue:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2594
