### ISSUE TITLE
Pattern: Create the Feature Card functional specifications based on visual designs provided by Lila

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2239]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Feature Card` functional specs 

> so that I can:
so that I can properly code the `Feature Card` component that meets the Solution template requirements

#### Additional information

- Design Issue (#2194 )
 - [Visual Design & Functional Specs Box folder link](https://ibm.ent.box.com/folder/111333289858)
 - Development issue (#2240 )

#### Acceptance criteria
 - [x] Created the `Feature Card` functional specifications and posted to Box folder
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] If no changes are needed, sent a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
CTA updated dependency name
https://ibm.ent.box.com/file/661397996455

Feature Card renamed to feature card block medium, and updated dependencies.
https://ibm.box.com/s/iopzz39fsrhmyvdanjjyq4he83zg6b93

Created new Feature card functional spec.
https://ibm.ent.box.com/file/661404545463

Content block with media updated resource name (shouldn't impact development)
https://ibm.ent.box.com/file/607045243803

**Comment by RobertaJHahn** [comment]
5/11/2020:  specs reviewed with the DDS engineers.  Dev story sized.
