### ISSUE TITLE
Pattern: Feature Card Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2241]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Feature Card`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2194  )
- Functional specs issue (#2239  )
 - [Visual Design & Functional Specs Box folder link](https://ibm.ent.box.com/folder/111333289858)
- There are 2 feature requests created that have been included in these latest designs.  These issues will be closed as part of the overall design QA work.  They are:  
- **[Feature Card] focus state additional border**  (#2206)
- **[Feature card] Arrow should be Blue** (#2207)

- Dev Issue (#2240)

 #### Tasks
Ensure the `Feature Card` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm @RobertaJHahn 
This pattern was merged in and it's ready for QA,
Thank you!

**Comment by ltitle** [comment]
@RaphaelAmadeu @RobertaJHahn Can you please provide the storybook link for testing

**Comment by RaphaelAmadeu** [comment]
@ltitle here it is

https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-sub-patterns-featurecard--default

**Comment by ltitle** [comment]
@RobertaJHahn Design QA has been completed for this pattern. Pete has logged the following issues: 

https://github.com/carbon-design-system/ibm-dotcom-library/issues/2547
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2548
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2549
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2550
