### ISSUE TITLE
Component: Locale Modal QA testing - Production level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2246]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library Locale Modal 

> I need to:
have a version of the component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
 - This component was originally created in the Fall of 2019.  The original issues are included in the IBM Enterprise Digital Design System Github.  
 - [Locale Selector component MVP link](https://github.ibm.com/webstandards/digital-design/issues/1077)
 - [Locale Selector enhancements included in release 2](https://github.ibm.com/webstandards/digital-design/issues/1804)
- Functional spec issue (#1315)
- Local Modal functional specs:  https://ibm.ent.box.com/file/655028173280
- [Design specs Box link](https://ibm.ent.box.com/file/532225637250)
 - Ignore designs on pages 1, 4 & 5
 

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
@chetankan You mentioned that you needed the design specs, but it looks like there is a link to designs in the Additional Information section above.  Is there something specific you are missing?

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan I am trying to close out sprint 20-09.  Is the testing finished or should I move this issue to the current sprint.  Could you provide a link to your testing evidence?

**Comment by Praveen-sr** [comment]
@RobertaJHahn We have completed functional, design and accessibility testing.

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Thank you.  Closing this issue.
