### ISSUE TITLE
Pattern: Change the Card section - simple and Card section - with images functional specifications to support their use in the Cards Group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2252]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card section - simple` and `Card section - with images` functional specs 

> so that I can:
so that I can properly code the `Card section - simple` and `Card section - with images` patterns

#### Additional information

  - Changes are needed to the Card section - simple and Card section - with images patterns to support their use in the Cards Group pattern.
 - [Card section - simple Box folder link](https://ibm.ent.box.com/folder/99476973715)
 - [Card section - with images box folder link](https://ibm.ent.box.com/folder/102045217811)
- Cards group functional specs issue (#2028)

#### Acceptance criteria
 - [ ] Documented `Card section - simple` and `Card section - with images` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by ellenchoi1** [comment]
Card section - simple func specs v2.0 uploaded to box: https://ibm.box.com/s/6prfrgt7dftdg47ejy3q3m4x7h47kbmo

Card section - with image func specs v2.0 uploaded to box: https://ibm.box.com/s/u4acyo9oeqya8xidimxtidh8k8y08fza

**Comment by ellenchoi1** [comment]
Func specs reviewed with dev team and signed off. Moving ticket to done.
