### ISSUE TITLE
Remove the Card section pattern from storybook

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2255]
Remove the `Card section` pattern from storybook.  This pattern is no longer needed as a standalone pattern since it is covered by the `Card section - simple` and `Card section - images` patterns.

This decision was made in the BA - Engineering functional specs review meeting on April 30, 2020.

**Comment by jeffchew** [comment]
This has already been done by @kennylam , I think we can close this.
