### ISSUE TITLE
Update footer design specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#2256]
#### User Story

The footer visual specs need to be reviewed and updated. The current spec file has some discrepancies between the gray 90 theme and may not pass accessibility standards.

#### Additional information

1.  Focus states speced as Blue60 which is not accessible on Gray90 background. 
    - Review focus state for all interactive elements and define the correct token

2. HEX values are outdated values and need to be removed.
    - use $tokens in the specs 
    - HEX values should only be used when we are hard coding an element.

3. Text links have two conflicting specs for default state
    - Text should use text token colors _not ui tokens_ 

4. Locale button should not duplicate specs of secondary button
    - we shouldn't duplicate specs for a core component so designers and developers don't think we are altering the behavior. Specs should call out secondary button and the unique icon.

#### Acceptance criteria
- [ ] Review specs with Olivia & Wonil
- [ ] Spec file is updated on Box
- [ ] PDF created
- [ ] Any development updates are noted in a new issue.

**Comment by jacobottesen-dgc** [comment]
@oliviaflory I'll get working on this right now

**Comment by jacobottesen-dgc** [comment]
Sent updated footer specs to Raph
Link to specs: https://ibm.box.com/s/fr28j7klp0zqbgs6qti9pv65rpqief6f
