### ISSUE TITLE
Pattern: Table of Contents Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2258]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Table of Contents`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2008  )
- Functional specs issue (#1827  ) and (#2052)
- [Design and Functional specs Box link](https://ibm.ent.box.com/folder/90702727404)
- [Storybook](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--with-heading-content)
**Functional Specs updates:**  
- Added Link List — text as optional 3 annotations
- shifted sticky/fixed behavior to table of content 2 in annotations
- Dev issue (#1851)
 - Prod QA testing issue (#2259 )

 #### Tasks
Ensure the `Callout` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm @RobertaJHahn 
The update for TableOfContents got merged in and it's ready for review,
Thank you!

**Comment by ltitle** [comment]
@RaphaelAmadeu @RobertaJHahn Can you please provide the storybook link for testing?

**Comment by ltitle** [comment]
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--with-heading-content

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is completed for this pattern. Shixie has logged the following issues:

- [ToC] Children and optional rule should scroll away, not sticky https://github.com/carbon-design-system/ibm-dotcom-library/issues/2516

- [ToC] Blue bar on selected item should slide up and down the rail, not fading on and off  https://github.com/carbon-design-system/ibm-dotcom-library/issues/2520

- [ToC] mobile scrolling page vibrates to the position of ToC dropdown https://github.com/carbon-design-system/ibm-dotcom-library/issues/2545

- [ToC] Buggy scrolling and state change
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2559

- [ToC] Styling issues
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2557
