### ISSUE TITLE
Pattern: Content block - segmented Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2260]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content block - segmented`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#1988)
 - Functional spec issue (#1821) and (#2051)
- [functional specs Box link](https://ibm.ent.box.com/file/651677070757)
 - Dev issue (#1845)
 - Prod QA testing issue (#2262 )

 #### Tasks
Ensure the `Content block - segmented` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn Visual specs posted here (pdf and sketch):
https://ibm.ent.box.com/folder/99730444060

**Comment by RobertaJHahn** [comment]
@ltitle Development is finished for this pattern.  The Design QA testing is scheduled to begin Monday, May 25.

Deploy preview created for package React:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2396/index.html

Built with commit: 12e7c2b27cd18980b68b2aa0bc742543852a395f

**Comment by ltitle** [comment]
@photodow Please confirm if we will need any QA for this story or if the code is just being reverted. If needed I can QA the text links when ready.

**Comment by RobertaJHahn** [comment]
Moving to sprint 20-12 for the follow-up work noted by Lila above.
