### ISSUE TITLE
Pattern: Link list Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2263]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content block - segmented`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2030  )
 - [Visual Designs & Design Specs Box link](https://ibm.ent.box.com/folder/101876058407)
- Functional specs issue (#1826  )
- [Functional specs Box link](https://ibm.ent.box.com/file/613262819069)
 - Prod QA testing issue (#2264 )

 #### Tasks
Ensure the `Link list` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
@kennylam Could you please provide the storybook link for Shixie?

@shixiedesign

**Comment by RobertaJHahn** [comment]
This design QA testing was not finished within DDS sprint 20-11.  The testing was moved to the Reboot backlog and will be tested within the DDS sprint 20-12 if they have time.  Removing the link to the epic (#1819) and included in the DDS sprint 20-12.  Will make a decision about whether to close this issue at then end of sprint 20-12.

**Comment by ltitle** [comment]
@RobertaJHahn @kennylam We still need the storybook link for this pattern. Thank you

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is completed for this pattern. Jina opened the following issues:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2832
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2833
