### ISSUE TITLE
Pattern: Leadspace block Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2265]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Leadspace block`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (# 2034 )
- Functional specs issue (#1835  )
 - [Design and functional specs Box link](https://ibm.ent.box.com/folder/111803008955)
 - Prod QA testing issue (#2266 )

 #### Tasks
Ensure the `Leadspace block` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
@greeshmareddyg Could you provide the storybook link for the Design QA tester?  Thanks.

**Comment by greeshmareddyg** [comment]
@RobertaJHahn Here it is, https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-leadspaceblock--default

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is now complete for this pattern. I have logged the following issues:

https://github.com/carbon-design-system/ibm-dotcom-library/issues/2613
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2614
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2615
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2616
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2617
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2618
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2619
