### ISSUE TITLE
Pattern: Logo grid Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2277]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Logo grid`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Functional specs issue (#645 ) 
- Dev Issue (#1846 )
- [Design and Functional specs Box link](https://ibm.ent.box.com/folder/112347802132)

 #### Tasks
Ensure the `Logo grid` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
@reesedownes Could you provide the Storybook link for the Design QA tester?  Thanks.

**Comment by reesedownes** [comment]
Logo Grid is now available for testing:

https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-logogrid--default

**Comment by RobertaJHahn** [comment]
This design QA testing was not finished within DDS sprint 20-11.  The testing was moved to the Reboot backlog and will be tested within the DDS sprint 20-12 if they have time.  Removing the link to the epic (#1805) and included in the DDS sprint 20-12.  Will make a decision about whether to close this issue at then end of sprint 20-12.

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is complete for this pattern. Jina opened the following issues: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2828
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2829
