### ISSUE TITLE
Component - Locale Modal -  dummy scroll option is displayed on country selection modal.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2279]
## Detailed description

Browsers :- Chrome and Firefox

Issue :- On country selection modal, a dummy scroll option is shown. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/fec65d89-2845-4805-861f-8adb0451dcd5)

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr @chetankan 
https://github.com/carbon-design-system/ibm-dotcom-library/pull/2282
