### ISSUE TITLE
Component - Locale modal - Modal heading and the label text is not as per the design specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2280]
## Detailed description

Issue:- The Modal heading is given as "Select region" and label is as "Select region"

Expected :- As per design specs, heading is "Select your geographic area" and label is "Select your region".

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/675f5612-4781-43cf-8bc1-7ef53dbb126b)

**Comment by kennylam** [comment]
@larahanlon2 Is this copy correct? Just confirming that the first pane of `LocaleModal` should say "Select your geographic area" or "Select Region"?

**Comment by larahanlon2** [comment]
Hey @kennylam "Select your geographic area" is correct. Please update the eyebrow label to also say this so both are the same.

(We can't use "Region" because it's not politically appropriate).

**Comment by ljcarot** [comment]
@larahanlon2 Do you recall who said Region is not approp
riate?

**Comment by larahanlon2** [comment]
@ljcarot both Mary O'Donnell and Tina Williams.

**Comment by kennylam** [comment]
thanks @larahanlon2! @ljcarot Suggest opening an issue for proper copy for translation files (search, locale) and closing this one since it's confirmed correct.

**Comment by RobertaJHahn** [comment]
5/6/2020:  Linda commented that the use of "your" in the description is not desired.  Labeling as a design story to update the designs.
