### ISSUE TITLE
Pattern: Content group - horizontal visual design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2286]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/112271053028)

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
5/7/2020 Visual specs presented to the DDS engineers and designers.  Links to specs will be posted by Lila.

**Comment by ltitle** [comment]
@RobertaJHahn VIsual design specs (sketch and PDF) are posted here:
https://ibm.ent.box.com/folder/112271053028
