### ISSUE TITLE
Pattern: Enable inverse theming to the Button Group pattern

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2291]
#### User Story
As a user of the button group pattern, I need a way to use this in the inverse theme so that I can build patterns that require inverse color theme.

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- This pattern should have inverse theming enabled.  Background information is included in issue (#2212)
- [Design and Functional specs Box folder](https://ibm.ent.box.com/folder/100581127894)
- Prod QA testing issue (#2458 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by oliviaflory** [comment]
I reviewed this issue with @photodow and @greeshmareddyg today, the inverse of this pattern is not needed immediately by Reboot, so we agreed to hold off on enabling inverse theming until we can look at how we are handling theming and inverse tokens across all of our patterns.

I will create a story to look into this to review with designers and developers and add it as a dependency to this issue.

cc: @RobertaJHahn @jeffchew
