### ISSUE TITLE
Link with icon inverse theming enhancement

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2294]
This epic contains links to the issues needed to enhance the `Link with icon` pattern

#### Additional information
- This pattern is used in the Callout Quote pattern included in the Reboot Services template.
- [Link with icon visual specs](https://ibm.ent.box.com/folder/107613134184)
- [Link with icon functional specs](https://ibm.ent.box.com/file/682502793940)

**Comment by photodow** [comment]
Here are the updated functional specs for this.
https://ibm.ent.box.com/file/682502793940
