### ISSUE TITLE
Pattern: Content item - horizontal functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2298]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content item - horizontal` functional specs 

> so that I can:
so that I can properly code the `Content item - horizontal` pattern that meets the Solution template requirements

#### Additional information

- scope includes English and 3 minimal quote variations.  
 - Design Issue (#2283  )
 - [Visual Designs & Functional Design Specs Box folder link](https://ibm.ent.box.com/folder/112262788897)
 - Development issue (#2299 )

#### Acceptance criteria
 - [ ] Documented `Content item - horizontal` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Initial draft v1.0 uploaded to box: https://ibm.box.com/s/911wx1w694l21iazjcw9powshyxmk0du

**Comment by ellenchoi1** [comment]
Version 1.1 uploaded to box: https://ibm.box.com/s/911wx1w694l21iazjcw9powshyxmk0du

Updates made based on discussions in engineering meeting to reflect that this sub-pattern is dependent on LinkList, not CTA. Refer to change log for details of updates.
