### ISSUE TITLE
Create Personae: DDS Developer

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#230]
_Benjamin-Hansen1 created the following on May 24:_  

 ## User story

As a Digital Design System team member, I need to understand our users, their behaviors, needs, processes, drivers, etc.- so that I can make sure the DDS experience provides ultimate value to them.

## Notes
The persona will include a high-level user journey showing the desired to-be state. A separate user journey will include detail on delighters, pain points, etc.  

## Deliverables

- [ ] Summarize information we already know 
- [ ] Interview developers to fill gaps and verify persona
- [ ] Document and publish persona

## Acceptance Criteria

- [ ] Published persona presented to DDS team (Playback) 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/885_

**Comment by ljcarot** [comment]
Closing this issue since we no longer have user researcher to help create personae.
