### ISSUE TITLE
Pattern: Content item - horizontal Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2300]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content item - horizontal`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2283  )
- Functional specs issue (#2298  )
- [Functional specs](https://ibm.ent.box.com/folder/112262788897)
 - Prod QA testing issue (#2301 )

 #### Tasks
Ensure the `Content item - horizontal` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
Pattern is ready for testing.  

Deploy preview created for package React:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html

Built with commit: e74cb4281124b5d8536d1e7315ddbb8c63e83855

**Comment by ltitle** [comment]
@RobertaJHahn Design QA for this pattern is now complete. The following issues have been opened:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2673
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2675
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2676
