### ISSUE TITLE
Pattern: Content group - horizontal functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2302]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content group - horizontal` functional specs 

> so that I can:
so that I can properly code the `Content group - horizontal` pattern that meets the Solution template requirements

#### Additional information

- scope includes English and 3 minimal quote variations.  
 - Design Issue (#2286  )
- [Visual Designs & Functional specs Box folder](https://ibm.ent.box.com/folder/112271053028)
 - Development issue (#2314 )

#### Acceptance criteria
 - [ ] Documented `Content item - horizontal` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by ellenchoi1** [comment]
Initial draft of func specs v1.0 uploaded to box: https://ibm.box.com/s/rv5kmm0a4d9ded74v6yfk8ad5id5ghmx

**Comment by ellenchoi1** [comment]
Version 1.1 uploaded to box to correct dependency: https://ibm.box.com/s/rv5kmm0a4d9ded74v6yfk8ad5id5ghmx

This pattern is using ContentBlock **not** ContentGroup as documented in v1.0.

**Comment by ellenchoi1** [comment]
Minor updates to version 1.1. uploaded to box: https://ibm.box.com/s/rv5kmm0a4d9ded74v6yfk8ad5id5ghmx

Updates to reflect that the previously documented 8 content item max will not be enforced by the pattern (will be enforced by the adopter). Refer to change log for details of updates.
