### ISSUE TITLE
Video Component light box media viewer does not work for many Kaltura Videos

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2303]
The Lightbox Media Viewer for Video does not seem to be working for many Kaltura Video IDs.

For example the following videos are publically available on Media Center but does not work when loaded from the Media Viewer:

https://mediacenter.ibm.com/media/1_2cuh9fvy

**Comment by annawen1** [comment]
we need to update the `partnerId` and `uiconfiId` to match the ones from `v18`. The media center videos seem to be authorized to play only on ibm.com domains as well.

**Comment by ljcarot** [comment]
Can we make this high severity - like sev 2?

**Comment by jeffchew** [comment]
> Can we make this high severity - like sev 2?

@ljcarot This is fine, though we can actually configure partnerID and confID through environment variables, but may need to update documentation on that. 

@kexuibm , here are the partner ID/confID's for IBM prod, but you won't be able to see the videos render in lower environments unless you are pointing to `*.ibm.com`:

```
KALTURA_PARTNER_ID=1773841
KALTURA_UICONF_ID=27941801
```

We will update the Kaltura player defaults to IBM prod, but since this is already configurable via environment variables we don't think there is a need to patch this.

cc: @annawen1

**Comment by kexuibm** [comment]
@jeffchew  @RobertaJHahn  I think this defect needs to be reopened.  So after plugging in the production Kaltura Partner and UI Conf IDs, the video itself loads in the light box however the attending title, description, and duration metadata does not load. 

Upon closer inspection, I noticed that the following Kaltura API calls is failing with an Invalid Widget ID error.
https://cdnapisec.kaltura.com/api_v3/index.php?service=multirequest&apiVersion=3.1&expiry=86400&clientTag=kwidget%3Av2.82.1&format=1&ignoreNull=1&action=null&1:service=session&1:action=startWidgetSession&1:**widgetId=1773841**&2:ks=%7B1%3Aresult%3Aks%7D&2:service=media&2:action=get&2:entryId=1_r1eanmna&kalsig=2c9c034a8648a8ae777bdc564dc2574c

It seems like the widgetId parameter in this call needs to be formatted to be _1773841 rather than just 1773841.

Here is what the Link List and Video in Light Box looks like when this happens, note that title, description, and duration is missing.

<img width="441" alt="Screen Shot 2020-05-13 at 12 02 01 PM" src="https://user-images.githubusercontent.com/55464272/81836897-14415f80-9512-11ea-81a8-454f8a2f2c90.png">

<img width="1437" alt="Screen Shot 2020-05-13 at 12 02 19 PM" src="https://user-images.githubusercontent.com/55464272/81836933-1efbf480-9512-11ea-89db-efb485f0e38a.png">

**Comment by RobertaJHahn** [comment]
@annawen1 Ke asked us to take a look at this defect again because the metadata from the Production Kaltura videos are not being rendered correctly.  See his comments above.

**Comment by kexuibm** [comment]
@jeffchew, @annawen1   and @RobertaJHahn  I think this defect needs to be re-opened. We pulled down v1.7.0-rc.1 and we are noticing that the Lightbox Video Player is failing to load when a Content Block Segmented or Content Block Simple Pattern meets the following conditions:

1.  The Pattern has both an Inline Video and a Linklist containing a video.
2.  The LinkList Video has the same Kaltura ID as the one in the Inline Video.

Here is an example in a Drupal Lower Environment:
https://ode15.cms.ibm.net/analytics/test-kx-no-alias3

When the user clicks on the Folgers Coffee Video Link, the lightbox opens with a broken video player.  

<img width="1637" alt="Screen Shot 2020-05-20 at 5 38 44 PM" src="https://user-images.githubusercontent.com/55464272/82500114-d66baa80-9ac0-11ea-8fc8-f1cb001b581f.png">


When the user closes that lightbox, the inline video player also is in an error state.

<img width="1533" alt="Screen Shot 2020-05-20 at 5 38 29 PM" src="https://user-images.githubusercontent.com/55464272/82500134-dcfa2200-9ac0-11ea-86bd-9f2cb0a75090.png">
