### ISSUE TITLE
Component - Footer - Cookie preferences font color is blue

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2305]
## Detailed description

Issue :- On footer, the Cookie preferences font color is not as other links, its font is blue.

Expected :- The font color must be same as other link options.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/eaf680db-03da-4694-97eb-ea984845583c)

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu This fix needs to be included in the May code release with the other updates included in issue (#1668)

**Comment by RaphaelAmadeu** [comment]
This bug is being addressed in issue #1668

**Comment by RaphaelAmadeu** [comment]
This was fixed on the issue mentioned above, Thanks!
