### ISSUE TITLE
Update VideoPlayer functional specs to include thumbnail lightbox launch

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2306]
#### User Story

> As a `[user role below]`:
IBM.com developer

> I need to:
see the functionality for video player lightbox launcher

> so that I can:
make the correct updates

#### Additional information
 - [videoPlayer](https://ibm.ent.box.com/folder/108837570522)
 - [Media](https://ibm.ent.box.com/folder/107606353006)
 - [LightBoxMediaViewer](https://ibm.ent.box.com/folder/84558325642)
 - #1824, #2025

Basically the video player needs to optionally be able to open up the lightbox media viewer from a poster image for smaller thumbnail sizes. Whether we include a type/prop that indicates full width, or thumbnail we should, or it's guidelines and governance we should try to talk to design about to solidify. As of right now the poster only plays inline.

Reach out if you have questions...

#### Acceptance criteria
 - [ ] VideoPlayer functional specs updated to reflect optional lightbox media viewer launch from poster image.

**Comment by ellenchoi1** [comment]
Confirmed with Lila that this is no longer part of the design. Updated Leadspace block designs reflect that it is using the default poster image sizing of Video: https://ibm.ent.box.com/folder/111803008955

@RobertaJHahn can you please close this ticket?

**Comment by RobertaJHahn** [comment]
thanks for letting me know.  Closing.
