### ISSUE TITLE
[VideoPlayer]: Missing poster image

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2312]
## Detailed description

Different review meetings I was in the past two days brought to light a small issue with our video player component. It appears as if we're not using a poster image for our videos as the design specs have indicated. The chrome is still visible, and the video play icon doesn't match. According to the functional specs once the poster image is clicked the embedded video player will replace it and begin playing the video.

##### As-is
![image](https://user-images.githubusercontent.com/3793636/81102019-9a3b2600-8ed4-11ea-8922-9381f902760d.png)

##### Expectation
![image](https://user-images.githubusercontent.com/3793636/81102079-afb05000-8ed4-11ea-9f0e-c7038a324d81.png)

## Additional information

- [Functional specs](https://ibm.box.com/s/drvsm6ez6kr206csllb5z1zvoxl11i62)
- [Design specs](https://ibm.box.com/s/36x742wza48h9zl5p3jfkq55me0fbcij)
- [Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/components-videoplayer--default)

**Comment by photodow** [comment]
May need to open up a separate issue for this, but are we using the video title to populate the caption underneath the video player? The screenshot in the as-is above looks like the video title, and the caption are two different things. I believe the caption is supposed to be the title and the duration of the video.

**Comment by annawen1** [comment]
@photodow the video caption is currently populated by the video description.

**Comment by photodow** [comment]
Thanks for confirming. I'll open a separate bug for that change. I believe the intent is it's the video's title goes there.

**Comment by annawen1** [comment]
@Praveen-sr @chetankan FYI to this change for the video player. Also when opening the lightbox with video, the video will play automatically - this is expected functionality that was missed.
