### ISSUE TITLE
Pattern: Content group - horizontal Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2315]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content group - horizontal`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- Design specs issue (#2286 )
- [Visual Designs & Functional specs Box folder](https://ibm.ent.box.com/folder/112271053028)
- Functional specs issue (#2302  )
 - Prod QA testing issue (#2316 )

 #### Tasks
Ensure the `Content group - horizontal` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
@ltitle This pattern is ready for testing.  

Deploy preview created for package React:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html

Built with commit: e74cb4281124b5d8536d1e7315ddbb8c63e83855

**Comment by ltitle** [comment]
@RobertaJHahn Design QA for this pattern is now complete. I have logged the following issues: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2669
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2670
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2671
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2672
