### ISSUE TITLE
Experimental Language selector does not display current language label

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#2319]
Trying out the new language selector, if you hit the X button to enter a langauge
name by keyboard, and do not pick a language, rather leave the component, so it looses focus,
the language selector stays empty. no language label displayed.
fix: language selector should reset the label if it looses focus when cleared

**Comment by jeffchew** [comment]
Unassigning this from myself in case other devs want to pick this up.
