### ISSUE TITLE
Create Personae: DDS Executive

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#232]
_Benjamin-Hansen1 created the following on May 24:_  

 ## User story

As a Digital Design System team member, I need to understand our users, their behaviors, needs, processes, drivers, etc.- so that I can make sure the DDS experience provides ultimate value to them.

## Notes
The persona will include a high-level user journey showing the desired to-be state. A separate user journey will include detail on delighters, pain points, etc.  

## Deliverables

- [ ] Summarize information we already know 
- [ ] Interview designers to fill gaps and verify persona
- [ ] Document and publish persona

## Acceptance Criteria

- [ ] Published persona presented to DDS team (Playback) 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/887_

**Comment by jeffchew** [comment]
_On Aug 14, Wonil-Suh1 commented:_
@Benjamin-Hansen1 @linda-carotenuto Not sure if this is a high priority item for sprint 17. I suggest that we focus on designers and developers this year, sticking with the principle of being essential and tactical.

**Comment by jeffchew** [comment]
_On Aug 14, Benjamin-Hansen1 commented:_
I agree @Wonil-Suh1 - We can do this whenever we get to it, and I currently have no data for it at all - so, big effort, low priority.

**Comment by ljcarot** [comment]
No user research role on team any longer to do this personae
