### ISSUE TITLE
Footer: Active & Focus state issue w/ text links

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#2340]
## The active and focus state on some of the links in the footer do not correctly display

Issue:
![Screen Shot 2020-05-11 at 10.52.59 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/2c48f916-282d-419d-90ea-27c9a2b030d6)

Correct: 
![Screen Shot 2020-05-11 at 10.53.26 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/363b2a1e-b471-4d43-a8ea-8237d15539b8)

> The active & focus state on the text links on the footer should be:
 color: $text-01
min-width: 2 columns
border: solid 1px $focus

But currently the border doesn't go around the text link on the left side. This issue is happening only on the first column on text links in the footer.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Google Chrome
## Steps to reproduce the issue

1. Go to footer in storybook https://ibmdotcom-react.mybluemix.net/?path=/story/components-footer--default
2. Select a text link in the first column and hold to view active & focus state

**Comment by annawen1** [comment]
This issue has been reported here: 
Component - Footer - keyboard - Focus on 1st column of the links is not full border. #2304

Will close this ticket to reduce duplicates.
