### ISSUE TITLE
Pattern: CalloutQuote - Mobile - Link arrow icon is smaller in size, not as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2348]
## Detailed description
Device - iPhone 11 , Samsung S10

Issue:- When user give long text for the link, the arrow link gets smaller in size.

## Steps to reproduce the issue

1. Open the Storybook on mobile
2. Navigate to Callout Quote pattern
3. On knobs, edit/change the link text to large text
4. Verify the link arrow icon

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a074e046-dab7-4bc8-ac55-66c1a4e94c16)

**Comment by caiobozato** [comment]
@Praveen-sr Could you please test again and see if this issue still happen?

For me another issue is happening:

![mobile-issue.jpeg](https://images.zenhubusercontent.com/5eed1fec732800bd837801c2/5e7de533-ace6-43ff-a1c5-c45494e4facf)

I'm working to fix this above, btw.

**Comment by Praveen-sr** [comment]
@caiobozato Re tested issue you mentioned, its because of no spacing in between the words. This very long word without spacing is not a valid scenario.

Issue :- When user gives long text (with spacing) for the link, the text actually wraps to next line and the arrow link gets smaller in size.
