### ISSUE TITLE
[CTA Section] incorrect horizontal rule

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2355]
Horizontal rule for this pattern should be **$ui-03** and should not extend to the right edge. See image below
 
 
 
Incorrect:
<img width="1122" alt="Screen Shot 2020-05-12 at 11 00 45 AM" src="https://user-images.githubusercontent.com/47458576/81717399-1e932900-9440-11ea-8cf9-35b51c6e87aa.png">
 
 
 
Correct:
<img width="1416" alt="Screen Shot 2020-05-12 at 11 01 07 AM" src="https://user-images.githubusercontent.com/47458576/81717395-1cc96580-9440-11ea-844d-ea698e56f8cc.png">

**Comment by RobertaJHahn** [comment]
Fixed under issue (#2796).  Closing this issue.
