### ISSUE TITLE
[CTA Section] Text width 

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2358]
Text width in the smaller paragraphs at times seems like its too long. Can you confirm that it is 90% of the intended column width? (6-col for lg+, 4-col for sm–md)

<img width="797" alt="Screen Shot 2020-05-12 at 11 24 42 AM" src="https://user-images.githubusercontent.com/47458576/81719989-69627000-9443-11ea-91db-dd2989c4a887.png">

**Comment by guilhermelMoraes** [comment]
@peter-garvin double checked here and both the content-items heading's and copy's spans only 90% of the available columns. In the `sm` breakpoint (320px) it changes to 100%

**Comment by guilhermelMoraes** [comment]
@peter-garvin would you please let me know if there's anything else about this one regarding the `ContentItem`'s spacing that needs my attention? Thanks

**Comment by peter-garvin** [comment]
Nope, looks good to me! thank you
