### ISSUE TITLE
Internal: Use optional chaining and nullish coalescing operators

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#2366]
#### User Story

> As a `[user role below]`:

Maintainer or contributor of `ibm-dotcom-library` codebase

> I need to:

Use ES2020 optional chaining and nullish coalescing operators

> so that I can:

Write more idiomatic code

#### Acceptance criteria
 - [ ] The change won't cause breaking change for our library users
 - [ ] The change won't break our UI code

**Comment by RobertaJHahn** [comment]
@jeffchew This story needs a sizing.  Maybe you can include the sizing methodology as an agenda item in your meetings with Akira.
