### ISSUE TITLE
Pattern:- FeatureCardBlock Large:- Mismatch of pixel value at bottom of page.(iOS, Android)

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2369]
Issue Description:- As per visual specs there should be 32px difference between i\link icon and bottom of page, but where as in mobile devices it is less than 32 px. 

## Steps to reproduce the issue

1. Enter url in mobile browser.
2. Click on 'FeatureCardBlock Large' pattern.
3. Scroll down to bottom of page 
4. Observe the difference between link icon and bottom of page.

OS:- iOS 12, 13 Android 8,9
Browsers:- Safari, Chrome, UC

URL:- https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-featurecardblocklarge--default

![FeatureCard Large in mobile.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/05addcfc-45d3-4792-b630-d6a45b47ddf8)![FeatureCard Large specs.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/fc4cdb65-f9ef-4ec5-b5d6-c1d4fe41cfcb)

**Comment by reesedownes** [comment]
@Praveen-sr @chetankan can you please check using this address:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2719/index.html?path=/story/patterns-blocks-featurecardblocklarge--default

this is a separate fix, but it includes icon and styling fixes that i believe also address this issue. this code was merged into our master branch.

![Screen Shot 2020-06-11 at 9.22.59 AM.png](https://images.zenhubusercontent.com/5e70ee056aaeb9007aeb5f97/68f6293b-ad33-4c58-8b72-c50e841724a0)

**Comment by RobertaJHahn** [comment]
@chetankan can you retest this?  See comment from Maurice above.

cc:  @reesedownes

**Comment by chetankan** [comment]
@RobertaJHahn  @reesedownes : Retested this issue on mobile device, still spacing difference between link icon and bottom of page is less and 32px and spacing between copy text and  link icon is also less than 32px where as as per visual specs spacing difference should be 32px between copy text and link icon.

**Comment by chetankan** [comment]
@RobertaJHahn  @reesedownes : Tested on mobile device spacing is proper now.

**Comment by RobertaJHahn** [comment]
@reesedownes Closing this issue based on Chetan's comments above.
