### ISSUE TITLE
Create new "DDS Patterns" page based on Solution page design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2371]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
see various patterns from the solution page design in a single page

> so that I can:
see and identify any issues with the patterns when assembled in a page

#### Additional information

 - `TODO: include link to designs`
- request to not call it the "Solutions" page, should call it the "DDS Patterns" page for now, will think of a better name later
- NextJS repo: https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test

#### Acceptance criteria
 - [ ] Page is added to the NextJS repo
 - [ ] Discrete style and js imports per pattern

**Comment by RobertaJHahn** [comment]
@ellenchoi1 @kathysaraf @photodow Jeff created this issue based on the QA meeting discussions earlier today.  He included a comment asking whether there is a link to designs that the dev's should use to build this page.  Should I just include links to all of the patterns included in the May release?

**Comment by jeffchew** [comment]
@ltitle do you have link to the latest designs we can use for this?

**Comment by jeffchew** [comment]
> @ellenchoi1 @kathysaraf @photodow Jeff created this issue based on the QA meeting discussions earlier today. He included a comment asking whether there is a link to designs that the dev's should use to build this page. Should I just include links to all of the patterns included in the May release?

@RobertaJHahn we would ideally have a full page we can work off of rather than per pattern.

**Comment by ltitle** [comment]
@jeffchew Right now all the designs are finalized at the pattern level. It sounds like we have a need for a full page comp to see how the patterns would fit together. Would we need this for all breakpoints? We will probably need a story for the Reboot design team to provide this.

**Comment by jeffchew** [comment]
> @jeffchew Right now all the designs are finalized at the pattern level. It sounds like we have a need for a full page comp to see how the patterns would fit together. Would we need this for all breakpoints? We will probably need a story for the Reboot design team to provide this.

@ltitle the original visual designs may suffice?

**Comment by ltitle** [comment]
@jeffchew Ok so just at XL breakpoint

**Comment by ltitle** [comment]
@jeffchew You can use this PDF as a reference. There are two pages that should cover all the solutions patterns. https://ibm.ent.box.com/file/665456059374

**Comment by RaphaelAmadeu** [comment]
@ltitle 
Could you please check the provided link,
It's unavailable for me,
Thanks!

**Comment by RaphaelAmadeu** [comment]
@ltitle 
Here we have an initial version of the page
https://ibmdotcom-nextjs.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/15/index.html

**Comment by ljcarot** [comment]
[DDS Patterns page.xlsx](https://github.com/carbon-design-system/ibm-dotcom-library/files/4720649/DDS.Patterns.page.xlsx)
@RaphaelAmadeu Take a look at this spreadsheet for mapping of solution page to DDS patterns and then see if you can layout the DDS patterns to match.
