### ISSUE TITLE
Build NextJS page for next wave (May) of patterns and components

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#2372]
> As an adopter, I need to see what the patterns look like so that I can evaluate early the usefulness of the newly design sections of a page.

Additional information
Solution page and services page are likely to use these patterns.

Acceptance criteria
 - [ ] Page can be viewed from NextJs as a published URL for both text and staging.

**Comment by jeffchew** [comment]
@ljcarot looks like you created this just as I created this one: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2371

**Comment by ljcarot** [comment]
I'll close this one.
