### ISSUE TITLE
Component: Footer - iPhone Voice over - "Expand /Collapsed" panels label on footer links is announced twice.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2383]
## Detailed description

Device - iPhone 

Issue :- 
For the show/hide panels, along with Label,  the word "Expand /Collapsed "  added, and this , along with the actual ARIA Expand/Collapse  announcement creates dual  announcement .

Expected : 
Since already aria expand/collapsed is used to convey the toggle behavior there is no need for and additional expand/collapsed announcement hence it would be better to remove it.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/fa27794a-7ca2-4808-8b14-526a307309ad)

**Comment by guilhermelMoraes** [comment]
Okay, so looks like this problem can be resolved just by updating the `carbon-components-react` package. In their latest version, they get rid of the title "Expand/Collapse" prop and a placeholder that appears when we don't pass the `title` prop to the `AccordionItem` - the component causing this issue.
I've opened a PR that is resolving this issue, though, it's a workaround. My question is: should we update the Carbon dependencies or go ahead if this workaround? 

@jeffchew @kennylam @asudoh

**Comment by asudoh** [comment]
While the workaround itself looks good; Given we have just done a release it sounds a good timing to do something like core dependency update, but specific to `carbon-components-react` wondering if we have some routine we do for this kind of update.

**Comment by kennylam** [comment]
@asudoh I agree we should try to stay on top of Carbon versions.

**Comment by jeffchew** [comment]
@kennylam @asudoh @RaphaelAmadeu let's get the carbon dependencies updated, and let's run percy in the PR update and make sure nothing's broken!

**Comment by RobertaJHahn** [comment]
Closing this issue as the Carbon upgrade fixes it.
