### ISSUE TITLE
Learn Pattern updates planning - June 2020 delivery

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2386]
The Reboot team plans to deliver 1 - 3 designs for either new or changes to existing patterns.  The new and changed patterns should be included in the June DDS release (ibm.com Library v1.8.0).  Code Freeze is June 12th.

#### Planned schedule
- Reboot designs:          May 11 - June 2 
- Functional specs:     May 18 - June 4
- DDS pattern dev & QA schedule:      June 4 - June 10  

#### Additional Information
- **The DDS BA will work with the Reboot designers to define the DDS work needed.**

#### Acceptance Criteria
- [ ] Meetings/conversations conducted with the Reboot designers to plan the work
- [ ] Epics created for each pattern with instructions for the developers and links to the designs and functional specs
- [ ] Coordination with the DDS PM to create the Dev, Prod QA and Design QA issues linked to the pattern epic.

**Comment by photodow** [comment]
Based on the email Linda shared earlier here is what we know so far.

- [TBD] Ability to add descriptive text for each section under the heading 
- [TBD] Solution cards - an option that allows for a better narrative than the card layout right now; and overall linking needs based on Michael’s audit & gap findings
- [[Markdown utility](https://ibm.ent.box.com/file/604090824435)] Support lists (bullets & numbers) in paragraphs
- [[Markdown utility](https://ibm.ent.box.com/file/604090824435)] Support contextual inline links in paragraphs 

The last two are potentially easy updates, but the first two we definitely need some more information about. The second item might clearly be a new pattern, but we'll need design specs. The first item, on the other hand, is just so general. What heading? Are they referring to sections the same way we are?

**Comment by ellenchoi1** [comment]
@RobertaJHahn -- @photodow and @kathysaraf  and I have discussed how we might organize work like this, possibly leveraging the "project" feature of Zenhub. I will add this as an agenda in our BA working session meeting this afternoon to finalize how we want to break down and track this work. That being said, are there any updates or additional details from the reboot team on the scope of the Learn page enhancements?

**Comment by photodow** [comment]
One question or to do, we had from our meeting today was setting up a meeting with reboot to figure out where they are, and what they're thinking. I know we're less than 2 weeks out from their proposed deadline. Not sure if we should be proactive in setting that up, or wait for them to reach out when they're ready.
