### ISSUE TITLE
Investigate integration of Karma accessibility testing into the IBM.com Library

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2387]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
automate the functional accessibility testing in the IBM.com Library

> so that I can:
reduce the level of manual accessibility testing

#### Additional information

 - Shared with us: https://github.ibm.com/IBMa/Tools-Karma-Plugin/blob/prod/src/README.md
 - Should determine what is involved to set up and if there are additional stories to create after standing this up

#### Acceptance criteria
 - [ ] Evaluate the Karma tool and determine if this is something to utilize
 - [ ] Set up initial architecture if moving forward

**Comment by asudoh** [comment]
Blocked by: IBMa/equal-access#104

**Comment by jeffchew** [comment]
@asudoh I think this can be closed out now, right?
