### ISSUE TITLE
Functional specs gap analysis

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2390]
#### User Story
> As a `[user role below]`:
Functional analyst

> I need to:
make sure every component/pattern has functional specs

> so that I can:
provide proper documentation to my teammates.

#### Additional information
 - [IBM.com Library](https://ibm.ent.box.com/folder/94084789008)

Just need to go through and see what could have been overlooked whether it doesn't exist, or we added a placeholder for the temporary interim. Then I can create functional spec stories for the functional analysts to pick up.

#### Acceptance criteria
 - [ ] New issues created for placeholder functional specs to be update
 - [ ] New issues created for non-existing functional specs to be created

**Comment by photodow** [comment]
Just some quick notes on what I've noticed so far. Will review with the other functional analysts on Monday hopefully.

- Update Quote with 3rd line source
- Image with caption Lightbox boolean and larger image?
- Remove props from specs into separate document
- Lightbox media viewer updates
	- image updates
	- ensure it’s all up to date
- Add change log to functional spec stories, and version number to names
- LinkWithIcon left icon? Is there a story for this?
- Expressive Modal needs to be updated
- Content layout needs to be updated
- Utilities documented?
	+ Markdown to Html
	- same height
	- altlangs
	- decodeString
	- escaperegexp
	- featureflag
	- geolocation
	- ipcinfoCookie
	- serialize
	- settings
	- smoothScroll
	- unique
- Services documented?
	- Analytics
	- DDO
	- Locale
	- MarketingSearch
	- Profile
	- SearchTypehead
	- Translation
	- VideoPlayer
	- global
- What’s happening with simple overview?
- Logo grid duplicate in section pattern
- What’s happening with simple benefits?

**Comment by ellenchoi1** [comment]
@photodow I was talking to the devs about the data model/props in the func specs as I was working on #2414 and got confirmation that they feel they should own this documentation and will maintain in the codebase and ensure that it's included in the readme in storybook. Also confirmed that Drupal would not need this in the func specs and are fine getting it from the readme. I think we can just slowly phase this out of the func specs as we update and/or create new ones.

**Comment by photodow** [comment]
@ellenchoi1 I had a similar discussion with @jeffchew which is why I put it on this list here.

**Comment by RobertaJHahn** [comment]
Gap analysis is finished.  Closing this issue.  The individual issues to complete the work will be created by Roberta and reviewed by James.  The individual issues will be inserted into the pipeline as velocity permits.
