### ISSUE TITLE
August Release Plan (v1.10.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2408]
# Timeline

- **August 17, 2020**: Code freeze
- **August 17 - 24, 2020**: Release Candidate(s) and testing
- **August 26, 2020**: Full Release

# Features

## Global
- Upgrade to Carbon v10.17.0 (#3461 )

### Features

- Enable the Expressive Theme in the IBM.com Library (https://github.com/carbon-design-system/ibm-dotcom-library/issues/3127)

In `v1.9.0`, we have released the expressive theme implementation that is now available for all teams (IBM.com and non-IBM.com teams alike) can take advantage of. In this release, the expressive theme will be enabled by default. This will ensure the consistent experience of marketing/editorial moments throughout the IBM.com experience. To learn more about the expressive theme, visit https://www.ibm.com/standards/web/ibm-dotcom-library/guidelines/expressive-theme.

- **components**:  Productive zoning capability (#3293)

### Fixes

- **Footer:** fixes footer theme styles ([#3677](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3677)) ([aa55335](https://github.com/carbon-design-system/ibm-dotcom-library/commit/aa55335)), closes [#3642](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3642)
- **MegaMenu:** prevent shift of IBM logo when opening mobile nav ([#3679](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3679))([48e431c](https://github.com/carbon-design-system/ibm-dotcom-library/commit/48e431c))
- **CalloutQuote:** adjust grid ([#3209](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3209)) ([9098b1e](https://github.com/carbon-design-system/ibm-dotcom-library/commit/9098b1e)), closes [#2399](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2399)
- **Card:** button width is auto according to the available space ([#3221](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3221)) ([27b81a2](https://github.com/carbon-design-system/ibm-dotcom-library/commit/27b81a2)), closes [#2736](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2736)
- **Card:** svg min width ([#3336](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3336)) ([766be3c](https://github.com/carbon-design-system/ibm-dotcom-library/commit/766be3c)), closes [#3245](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3245)
- **footer:** fixed spacing of the legal nav list ([#3345](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3345)) ([f2cb7f2](https://github.com/carbon-design-system/ibm-dotcom-library/commit/f2cb7f2))
- **MegaMenu:** add padding to the view all cta focus state ([#3521](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3521)) ([2b5fb4b](https://github.com/carbon-design-system/ibm-dotcom-library/commit/2b5fb4b)), closes [#3498](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3498)
- **MegaMenu:** align megamenu content with grid ([#3570](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3570)) ([097b696](https://github.com/carbon-design-system/ibm-dotcom-library/commit/097b696)), closes [#3502](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3502)
- **MegaMenu:** change overflow scroll style from x to y ([#3566](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3566)) ([c5d0fe8](https://github.com/carbon-design-system/ibm-dotcom-library/commit/c5d0fe8)), closes [#3543](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3543)
- **TableOfContents:** active selector bug ([#3457](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3457)) ([798fa3b](https://github.com/carbon-design-system/ibm-dotcom-library/commit/798fa3b)), closes [#3298](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3298)
- **TableOfContents:** hover styling ([#3328](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3328)) ([89f870f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/89f870f)), closes [#3246](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3246)

### Features 

- Enhance the video player to support 1:1, 4:3 and 16:9 aspect ratios:  Epic (#2834 )
- Masthead Mega Menu (https://github.com/carbon-design-system/ibm-dotcom-library/issues/3120)

For L0 experiences, we are introducing the new look and feel of the Masthead menu! Our team has worked closely in support of the CET Discoverability initiative working with the IA team on IBM.com Reboot and are excited to see this roll out throughout the IBM.com experience! 

- **left-nav:** support focus wrapping ([#3348](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3348)) ([8414000](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8414000)), closes [#3160](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3160)
- **Masthead:** add megamenu to mobile nav ([#3464](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3464)) ([5422747](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5422747)), closes [#3300](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3300)
- **MegaMenu:** MegaMenu component ([#3395](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3395)) ([c962e2f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/c962e2f)), closes [#3279](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3279)
- **MegaMenu:** set up auto ids ([#3517](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3517)) ([f106790](https://github.com/carbon-design-system/ibm-dotcom-library/commit/f106790)), closes [#3381](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3381)
- **VideoPlayer:** adding stories for different aspect ratios ([#3434](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3434)) ([055e10f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/055e10f)), closes [#3396](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3396)

### Fixes

- **expressivetheme:** enable css custom properties with the theme ([#3699](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3699)) ([cdf12a3](https://github.com/carbon-design-system/ibm-dotcom-library/commit/cdf12a3)), closes [#3698](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3698) [#3643](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3643)
- **masthead:** locked focus while left menu active ([#3705](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3705)) ([ff766f7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/ff766f7)), closes [#3663](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3663)
- **masthead:** ssr fix for scroll check ([#3704](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3704)) ([c087815](https://github.com/carbon-design-system/ibm-dotcom-library/commit/c087815)), closes [#3661](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3661) [#3661](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3661)
- **MegaMenu:** add tabindex attr for safari not detecting event ([#3673](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3673)) ([b3c1c7e](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b3c1c7e)), closes [#3641](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3641)
- **MegaMenu:** disable body scroll when megamenu is open ([#3676](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3676)) ([828bfa7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/828bfa7)), closes [#3633](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3633)
- **MegaMenu:** disable scrolling for mobile nav ([#3692](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3692)) ([44167d5](https://github.com/carbon-design-system/ibm-dotcom-library/commit/44167d5)), closes [#3661](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3661)
- **MegaMenu:** pass href prop to the CategoryGroup so link can be accessed as expected ([#3668](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3668)) ([abfbb56](https://github.com/carbon-design-system/ibm-dotcom-library/commit/abfbb56))
- **CalloutWithMedia:** g90 theme rendering well ([#3392](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3392)) ([c0c6351](https://github.com/carbon-design-system/ibm-dotcom-library/commit/c0c6351)), closes [#3383](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3383)
- **docs:** fixed codesandbox links pointing to old folders ([#3544](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3544)) ([902a1c3](https://github.com/carbon-design-system/ibm-dotcom-library/commit/902a1c3)), closes [#3541](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3541)
- **jest:** remove console errors ([#3490](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3490)) ([e43bbfe](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e43bbfe))
- **lightboxMediaViewer:** update react version ([#3489](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3489)) ([d58e6fa](https://github.com/carbon-design-system/ibm-dotcom-library/commit/d58e6fa)), closes [#3295](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3295)
- **LinkwithIcon:** disabled hover styling ([#3384](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3384)) ([af30476](https://github.com/carbon-design-system/ibm-dotcom-library/commit/af30476)), closes [#3294](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3294)
- **LocaleModal:** accessibility issue on navigation ([#3466](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3466)) ([e7e10a9](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e7e10a9)), closes [#3412](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3412)
- **LocaleModal:** changing icon size and margin ([#3532](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3532)) ([69109dd](https://github.com/carbon-design-system/ibm-dotcom-library/commit/69109dd)), closes [#3329](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3329)
- **LocaleModal:** html semantic, filter by region, scrollTop by region ([#3513](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3513)) ([5a703d1](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5a703d1)), closes [#3409](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3409)
- **LocaleModal:** modal close btn accessibility ([#3447](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3447)) ([88b3a53](https://github.com/carbon-design-system/ibm-dotcom-library/commit/88b3a53)), closes [#3410](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3410)
- **LocalModal:** reset scroll to top ([#3465](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3465)) ([8ffa44d](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8ffa44d)), closes [#3350](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3350)
- **masthead:** left menu focus ([#3611](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3611)) ([26ce5f9](https://github.com/carbon-design-system/ibm-dotcom-library/commit/26ce5f9)), closes [#3588](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3588)
- **Masthead:** edit hamburger menu autoid to new format ([#3618](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3618)) ([eaf073f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/eaf073f))
- **MastheadSearch:** fix UC browser ([#3442](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3442)) ([5d5f0c9](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5d5f0c9)), closes [#2896](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2896)
- **MegaMenu:** assign button role for the back button in mobile menu ([#3610](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3610)) ([f840b28](https://github.com/carbon-design-system/ibm-dotcom-library/commit/f840b28)), closes [#3587](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3587)
- **MegaMenu:** break down MegaMenu into smaller components ([#3488](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3488)) ([cf32071](https://github.com/carbon-design-system/ibm-dotcom-library/commit/cf32071)), closes [/github.com/carbon-design-system/ibm-dotcom-library/pull/3395#issuecomment-669766125](https://github.com//github.com/carbon-design-system/ibm-dotcom-library/pull/3395/issues/issuecomment-669766125)
- **MegaMenu:** prevent menu items from overlapping ([#3565](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3565)) ([8bd6375](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8bd6375)), closes [#3519](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3519)
- **MegaMenu:** set correct aria label to hamburger menu when open/closed ([#3608](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3608)) ([e780ffa](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e780ffa)), closes [#3584](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3584)
- **MegaMenu:** tweak data-autoids for the mobile navigation ([#3576](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3576)) ([7520594](https://github.com/carbon-design-system/ibm-dotcom-library/commit/7520594)), closes [#3381](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3381)
- **side-nav:** cope with large list of parent menu items ([#3607](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3607)) ([bce8890](https://github.com/carbon-design-system/ibm-dotcom-library/commit/bce8890)), closes [#3512](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3512)
- **storybook:** fix to storybook react docs pages ([#3572](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3572)) ([2a8c72d](https://github.com/carbon-design-system/ibm-dotcom-library/commit/2a8c72d)), closes [#3571](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3571)
- **VideoPlayerAPI:** stop video when modal closes ([#3427](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3427)) ([b61b5ee](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b61b5ee)), closes [#3295](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3295)
- **callout-data:** fixed wrong story display on iframe mode ([#3241](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3241)) ([217095b](https://github.com/carbon-design-system/ibm-dotcom-library/commit/217095b))
- **components:** revert type size back to one of v1.8.0 ([#3293](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3293)) ([b97771b](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b97771b)), closes [#3287](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3287)
- **CTASection:** add sameHeight to content items ([#3330](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3330)) ([18aff80](https://github.com/carbon-design-system/ibm-dotcom-library/commit/18aff80))
- **CTASection:** buttongroup styling ([#3254](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3254)) ([4857422](https://github.com/carbon-design-system/ibm-dotcom-library/commit/4857422)), closes [#3016](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3016)
- **docs:** wrong scss import path in docs ([#3335](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3335)) ([57ee99b](https://github.com/carbon-design-system/ibm-dotcom-library/commit/57ee99b)), closes [#3332](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3332) [#3333](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3333)
- **LightboxMediaViewer:** modal dialog accessibility ([#3275](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3275)) ([e0dd2d2](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e0dd2d2)), closes [#2727](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2727)
- **TableOfContents:** Sticky offset not working ([#3255](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3255)) ([195a26e](https://github.com/carbon-design-system/ibm-dotcom-library/commit/195a26e)), closes [#2979](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2979)

### Features

- Web Components MVP (https://github.com/carbon-design-system/ibm-dotcom-library/issues/2882)

We're excited to bring the initial footprint of the web components package of the IBM.com Library! This will strategically be one of our primary focuses on how we continue to build and enhance the library in the foreseeable future. This takes full advantage of the `carbon-web-components` (the web component variant of Carbon, https://github.com/carbon-design-system/carbon-web-components) where we are also beginning to take an active part in its continued support. 

- **locale-modal:** introduction ([#3185](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3185)) ([1357b6e](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/1357b6e)), closes [#2883](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/2883)
- **dotcom-shell:** introduction ([#3505](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3505)) ([0a0601b](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/0a0601b))
- **footer:** introduction ([#3411](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3411)) ([93db39f](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/93db39f)), closes [#2862](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/2862)
- **left-nav:** support focus wrapping ([#3348](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3348)) ([8414000](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/8414000)), closes [#3160](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3160)
- **masthead:** support profile API ([#3463](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3463)) ([1f41b05](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/1f41b05)), closes [#3432](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3432)
- **footer:** introduce cookie preference placeholder ([#3656](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3656)) ([a5ce796](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/a5ce796)), closes [#3583](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3583) [#3624](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3624)

### Fixes

- **footer:** fix for store initialization ([#3595](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3595)) ([3194a6a](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/3194a6a)), closes [#3589](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3589) [#3590](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3590) [#3594](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3594)
- **Footer:** add aria label to IBM logo in footer ([#3613](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3613)) ([3bc71e9](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/3bc71e9)), closes [#3609](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3609)
- **masthead:** added entry point to self-init redux store ([#3579](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3579)) ([5a40b84](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/5a40b84))
- **cta:** prevent lightbox from opening for non-video ([#3508](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3508)) ([6659a35](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/6659a35)), closes [#3440](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3440)
- **devenv:** use ibm-common.js ([#3578](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3578)) ([36b148c](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/36b148c)), closes [#3575](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3575)
- **lightbox-media-viewer:** fix the size ([#3507](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3507)) ([e51f270](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/e51f270)), closes [#3349](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3349)
- **lightboxMediaViewer:** handle video close ([#3500](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3500)) ([aef7d8f](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/aef7d8f)), closes [#3331](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3331)
- **link:** change disabled handling ([#3506](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3506)) ([4a87bf0](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/4a87bf0)), closes [#3405](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3405)
- **localModal:** scroll to top ([#3501](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3501)) ([22056a9](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/22056a9)), closes [#3476](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3476)
- **components:** revert type size back to one of v1.8.0 ([#3293](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3293)) ([b97771b](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/b97771b)), closes [#3287](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3287)
- **masthead:** add label to profile trigger button ([#3205](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3205)) ([21aafc1](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/21aafc1)), closes [#3156](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3156)
- **Masthead:** missing aria-label on masthead search ([#3256](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3256)) ([b30261a](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/commit/b30261a)), closes [#3158](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/web-components/issues/3158)

### Fixes

- **VideoPlayerAPI**:  stop video when modal closes (#3427)

**Comment by asudoh** [comment]
`v1.10.0` has been released:

* https://www.npmjs.com/package/@carbon/ibmdotcom-react/v/1.10.0
* https://www.npmjs.com/package/@carbon/ibmdotcom-services/v/1.10.0
* https://www.npmjs.com/package/@carbon/ibmdotcom-styles/v/1.10.0
* https://www.npmjs.com/package/@carbon/ibmdotcom-utilities/v/1.10.0
* https://www.npmjs.com/package/@carbon/ibmdotcom-vanilla/v/0.10.0
* https://www.npmjs.com/package/@carbon/ibmdotcom-web-components/v/0.3.0
* https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.10.0
