### ISSUE TITLE
Pattern: Update functions specs for ImageWithCaption

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/ibm-dotcom-library#2414]
## Detailed description

> Describe in detail the issue you're having.

- Currently the data needed to generate the LightboxMediaViewer are already passed in to the `ImageWithCaption` component. Just need to pass in a `lightbox` boolean prop to turn on/off the launching lightbox functionality. No need for the `lightbox` object specified in the data model sections

- Lila mentioned that the `copy` field only ever appears in the lightbox description field. We will need to change the `Caption` section. In `@sm` breakpoint we only show the heading, not the copy.

- The `heading` prop is also optional.

### Additional Info: 
- [ImageWithCaption func specs](https://ibm.ent.box.com/file/640289462720)

**Comment by ellenchoi1** [comment]
Version 1.1 of func specs uploaded to box: https://ibm.box.com/s/mclmewshqcme7g6gykepok78rm882a0j

Refer to change log for details of updates.
