### ISSUE TITLE
Pattern: Make the code changes to the Table of Contents that improve the scrolling behavior

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2424]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
change the `Table of Contents`

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Updated functional specs (v 1.3) uploaded to box: https://ibm.box.com/s/yfuicifhfeaefp4rl0pp62dpeacr18ry
- The hover and color changes in the functional specs are included in issue (#2606)
- Functional specs issue (#1783  )
- Prod QA testing issue (#2425 )

#### Functional spec changes and highlights
- 'On scroll' and 'on swipe' behavior updated to reflect that Anchor Link that will display in selected state is whatever table of contents section is the top-most section currently in view i.e. if a user is scrolling back up the page, the Anchor Link in selected state will update as soon as the bottom of the previous section appears in view. Currently, selected state only updates when the anchor (e.g. section header) aligns with the top of the page.
- In desktop experience, Scroll Indicator movement (on page scroll or on click of unselected section) will be smooth scroll. Currently, it is more of a jump motion.

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by ellenchoi1** [comment]
Updated ticket info to call out changes expected with this dev ticket (separate from scope of #1851 and #1914).

**Comment by RobertaJHahn** [comment]
Increasing the priority of this issue because it is included in the June release and the Reboot designers have created a bug for the scrolling behavior.  (issue #2520)

I am also closing the bug created by the Reboot team as a duplicate.  The work will be managed in this issue.

**Comment by RobertaJHahn** [comment]
Removed the hover and color changes from this issue (#2606) so that the work can be included in the June release.  The hover and color changes will be included in the July release.
