### ISSUE TITLE
Lightbox Image - Title and Description should be optional based on content model.

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#2431]
## Detailed description
Based on Content Model for the informative image both title(Caption) and description should be optional but lightbox pattern is expecting to be required field.
Some conversation with Jill and Lila
https://ibm-digitalcms.slack.com/archives/C2PLX8GQ6/p1589402308241300?thread_ts=1589385351.234100&cid=C2PLX8GQ6

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue? bug

> Is this issue related to a specific component? Lightbox Media Viewer Image

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
This issue is fixed in PR (#2413).  Closing.
