### ISSUE TITLE
Content Item - Horizontal link type requirements

### ISSUE THREAD

**Issue by ellenchoi1** [carbon-design-system/ibm-dotcom-library#2441]
## Detailed description

CTA link type should also support downloads but currently only supports local and external.

This is a bug per v1.1 of Content Item - Horizontal func specs: https://ibm.box.com/s/pj2wnlct4lfprz0anybc6ksi9qkqstgh
This sub-pattern is dependent on the Link List sub-pattern for the CTA elements and the download type is accounted for per v1.1 of Link List func specs: https://ibm.box.com/s/kkstacfm9ma5dle30dboj5yorz3ytv5d

Observed in stage: https://ibmdotcom-react-staging.mybluemix.net/

**Comment by RaphaelAmadeu** [comment]
The `ContentItem` CTA already supports the download type in code, so the storybook should be updated to reflect it.

**Comment by kennylam** [comment]
This was added in https://github.com/carbon-design-system/ibm-dotcom-library/pull/2360.
