### ISSUE TITLE
React DocGen: Prop table in Storybook

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#2443]
# The solution

This issue is for keeping track of our effort to introduce prop table in Storybook, possibly integrated with READMEs, as a follow-up to #2422.

### Acceptance Criteria

- [ ] Integrate info addon in storybook for props table

**Comment by jeffchew** [comment]
@asudoh is this work going to be covered in https://github.com/carbon-design-system/ibm-dotcom-library/issues/2442?

**Comment by asudoh** [comment]
Great point @jeffchew - This task should be done with #2442 as a single effort (hard-dependencies between one and another). So, should we merge them?

**Comment by jeffchew** [comment]
I think that makes sense, I'll close this issue out then.
