### ISSUE TITLE
Add the Selenium tests to the DDS repo and Jenkins

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2455]
The QA team members have created Selenium tests in their own environment.  They should be moved into the ibm.com Library repo and included in Jenkins so that the tools used by the DDS squad are in a centrally managed environment.

**Comment by Praveen-sr** [comment]
@jeffchew @RobertaJHahn  We have updated pattern, section and components test scripts to Git (QA-Branch).
