### ISSUE TITLE
Integrate license file formatting in the CI process

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#2475]
### The problem

#2343 introduced `lint-staged` integration to check license header formatting. But it checks only against files that are being changed.

### The solution

Integrate that check with the CI process.

**Acceptance criteria**

- [ ] Having license header check integrated to our CI that runs against every pull request

**Comment by jeffchew** [comment]
@asudoh this is pretty much running across all files, right? Would we add as part of our `ci-check`?

**Comment by asudoh** [comment]
You are right @jeffchew - Yes integrating it to `ci-check` would make the most sense.
