### ISSUE TITLE
Pattern: ContentGroup Horizontal - No spacing between links, when link text is long.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2476]
## Detailed description

Issue :- When link text is long, the link text wraps and no spacing between 2 links.

Expected : There must be spacing between links as per the specs.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/79df4d90-ea25-4023-80f2-31b63a19327a)

**Comment by annawen1** [comment]
@kennylam is this bug still valid with the recent updates for ContentGroupHorizontal that went in?

**Comment by kennylam** [comment]
@annawen1 No, no longer an issue since those links are now vertical only.
