### ISSUE TITLE
Services template updates planning - July 2020 delivery

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2478]
The Reboot team plans to deliver 1 - 3 designs for either new or changes to existing patterns.  Reboot target delivery is June 22.  The new and changed patterns should be included in the July DDS release (ibm.com Library v1.9.0).  Code Freeze is July 17th.

#### Planned schedule
- Reboot designs:          May 26 - June 22 
- Functional specs:     June 15 - June 25
- DDS pattern dev & QA schedule:      June 23 - July 03  

#### Additional Information
- **The DDS BA will work with the Reboot designers to define the DDS work needed.**

#### Acceptance Criteria
- [ ] Meetings/conversations conducted with the Reboot designers to plan the work
- [ ] Epics created for each pattern with instructions for the developers and links to the designs and functional specs
- [ ] Coordination with the DDS PM to create the Dev, Prod QA and Design QA issues linked to the pattern epic.

**Comment by RobertaJHahn** [comment]
Box note that contains the Services template MVP patterns:  https://ibm.ent.box.com/notes/677586401007?s=j845wnqyyrxrfydjv7a392mz0iakkut5

**Comment by photodow** [comment]
So here is what I have…

1 new pattern
1 update
3 possible updates pending review

- `new` Callout data point 
   <img src="https://images.zenhubusercontent.com/5898a60e51aa2c3057739766/4cab4e54-16a9-4647-9e34-117da3bd70bc" width="200px" />
- `update` CTA added to content block with cards? 
- `update` Content group horizontal (variant or not?)
- `update` Link List added to content block segmented (try to avoid, can drupal add it themselves?)
    <img src="https://images.zenhubusercontent.com/5898a60e51aa2c3057739766/cfd1290d-0945-4cc6-a76a-e03e4ce6f97f" width="200px" />
- `update` CTA Section (technical review / gap analysis needed to double check. functional specs should support this)

Here are the rough designs to start with...
https://ibm.ent.box.com/file/679166003833

**Comment by RobertaJHahn** [comment]
Recording of the June 15 pattern review meeting is posted to this Box Note.  https://ibm.ent.box.com/notes/443167473382

**Comment by RobertaJHahn** [comment]
**June 16, 2020 Meeting with Jeff, James, Linda and Roberta to talk about the services work to be done.**  
 - Callout data point - Roberta to scheduled meeting to name the pattern
- Content group horizontal - James to work with Lila to see whether current functions will work so that there will be no change for DDS
- Content block - media - Linda will work with Raph to add the existing Link List pattern below the content block media to see the spacing.
