### ISSUE TITLE
Pattern:  Card video enhancement

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2482]
This epic will contain a description of the overall scope, development instructions and links to all of the issues required to complete the work.

#### Additional Information
- The CHQ content team had concerns about supporting video interaction within a card.  As a result the original issues were closed.  The Reboot team decided to move forward with the implementation.  Background on this topic is included in issue (#2226)
- The Card pattern will support presenting a video within the card.
- Sketch and PDFs for visual design specs are posted here: https://ibm.ent.box.com/folder/95514001950
- Includes the video card specs posted here: https://ibm.ent.box.com/file/657576937319 
- Functional specs version 1.1 uploaded to box: https://ibm.box.com/s/3ma5hudlb59s3jossq96yxduqyj68pq7

#### Acceptance criteria
- [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] Designs and functional specs are reviewed with the DDS developers for sizing and issue refinement.

**Comment by ellenchoi1** [comment]
@jeffchew Functional specs version 1.1 uploaded to box: https://ibm.box.com/s/3ma5hudlb59s3jossq96yxduqyj68pq7. Also updated epic description to include link.

**Comment by RobertaJHahn** [comment]
Release v1.8.0 is finished.  All linked issues are closed.  Closing this epic.
