### ISSUE TITLE
Pattern: Card video enhancement Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2485]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card` pattern

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (# )
- [Storybook link](TBD)

 #### Tasks
Ensure the `Card` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by annawen1** [comment]
@RobertaJHahn @wonilsuhibm this enhancement has been completed. You can view here:

https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-cta--default

(in the knobs, set `style` to card and `type` to video)

**Comment by ltitle** [comment]
@RobertaJHahn Design QA is complete. We did not open any issues!
