### ISSUE TITLE
Automated test for bundle size

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#2493]
### The problem

In our old codebase we had a build size problem due to Carbon dependency (#2438 #2477), and it's easy to regress it back depending on how we use Carbon.

### The solution

Introduce an automated test to check if a module in our codebase yields to a gigantic bundle size.

### Acceptance criteria

- [ ] Automated test that catches if a module in our codebase yields to a gigantic bundle size.

**Comment by jeffchew** [comment]
Lining up for sprint 12, I think there are other items we should probably hit up first but this is good to keep on our radar.

cc: @RobertaJHahn
