### ISSUE TITLE
Block Link component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#250]
_hahnrob created the following on Jun 20:_  

 This is an Epic that contains links to all of the work required to create the block link component 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1075_

**Comment by jeffchew** [comment]
_On Jun 20, scarnes9 commented:_
@hahnrob Just wanted to post a note on here, re: block links, if your team can consider some adjustments to them looking ahead?  

On Industries and at MSC, we noticed that the latest design standards look the same as v18, but some team members feel that the interaction does not look or function in a contemporary or elegant way.  We hand-coded a few subtle changes to show as a demo.  Some of the adjustment ideas include:

* providing the whole IBM color palette for rollover options
* coding a subtle fade animation between the colors on roll on and off, rather than an abrupt instant shift
* providing for subtle text animations on block link rollover

Demo / Examples:
https://wwwstage.ibm.com/industries/assets/demo/card-rollover/

User: staging
Pass: IBM19July

Here is some context in our Design Library:
https://ibm.invisionapp.com/share/Q4GVGW2A82D#/screens/319071090_Standards_-_Interaction

Please note these come from frustration with the current Drupal blocklinks.  I'm not sure what the latest version is on your end...

CC @Wonil-Suh1

**Comment by jeffchew** [comment]
_On Jun 20, Wonil-Suh1 commented:_
Hey Seth, thank you so much for the comment. We are redefining these as cards, and treat block links as a very different component - really as a `rich link`. See the examples below:

https://www.ibm.com/search?lang=en&cc=us&bookmark=eyJzZXJ2aWNlTmFtZSI6Imtub3dsZWRnZUNlbnRlciIsInRvdGFsIjozMDAzLCJjb3VudCI6Mywic21Db3VudCI6MCwib2Zmc2V0IjowLCJmYWlsZWRQYWdlcyI6W119LXsic2VydmljZU5hbWUiOiJlc3FzIiwidG90YWwiOjM4NDc2OSwiY291bnQiOjE3LCJzbUNvdW50IjowLCJvZmZzZXQiOjAsImZhaWxlZFBhZ2VzIjpbXX0teyJwYWdlIjoxLCJxdWVyeSI6Im1hZ25pZmllciJ9&q=watson%20engine

That said, here are my thoughts on your suggestions:

- can you provide why you would need whole color palette? We are leaning towards providing options that have been vetted and curated to maintain a higher level of consistency across IBM.com.

- Subtle, non-intrusive fade sounds good. The fade speed will have to be sped up though, following the IDL motion guidelines. ( [IDL Motion](https://www.ibm.com/design/language/elements/motion) )

- I have a mixed feelings these - I totally understand the rationale, but is this the right kind of motion that represents IDL is what I'm struggling with. Something to explore.

Thank you again!!!!

**Comment by jeffchew** [comment]
_On Jun 24, Wonil-Suh1 commented:_
Chatting with the Product Discovery team, the main identified adopter of this component, they may not need it or the way we defined this component may not work for them for these because their new search result item pattern may need multiple CTAs.

![screen shot 2019-06-24 at 3 52 43 pm](https://media.github.ibm.com/user/25726/files/20bd8f00-9698-11e9-8134-1d597c7fdf24)

**Comment by jeffchew** [comment]
_On Jun 26, scarnes9 commented:_
@Wonil-Suh1 Thanks, I did not see your bulleted notes below this and am just seeing now.  Some replies:

- can you provide why you would need whole color palette? We are leaning towards providing options that have been vetted and curated to maintain a higher level of consistency across IBM.com.

We would not need the whole color palette.  It would be great to have a vetted, curated set of colors that allow creation of elegant designs matching the color scheme of a given page.  The block links In Drupal offer very limited options and do not seem curated in this respect, see attached:

![blocklink_color_choices](https://media.github.ibm.com/user/82603/files/a882d500-9821-11e9-9eb8-24f640842c15)

- Subtle, non-intrusive fade sounds good. The fade speed will have to be sped up though, following the IDL motion guidelines. ( IDL Motion )

Gotcha, sounds good!  I think the developer arbitrarily picked that fade speed for the example and we were in a hurry.

- I have a mixed feelings these - I totally understand the rationale, but is this the right kind of motion that represents IDL is what I'm struggling with. Something to explore.

Yes, am not sure the example with the text link animation to the right for example is best, but the challenge now is that we have zero ways create a card blocklink that shows as active, except the outline or full color background on rollover.  Our feeling is these two styles often look dated or do not fit in a design layout at times, so we tried to create at least one example where the link moves on rollover and changes color, so the user sees both the cursor change and the link move, indicating active state.

**Comment by RobertaJHahn** [comment]
There is a card link component.  Closing this epic based on Wonil's recommendation.
