### ISSUE TITLE
Content block intro needs a type token change 

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#2501]
### The problem
[Previously we requested](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1600) the intro paragraph section of content block to be changed from `expressive-heading-03` to `expressive-paragraph-01`. This was needed because the line-height for heading-03 was too tight when first built.

However, the IDL and Carbon team have now decided to update line heights across type sets so that all line-heights will be divisible by 4. As a result, heading-03 will not have such tight line-height and will be a better overall type scale for this layout. 

<img width="1314" alt="Screen Shot 2020-05-26 at 10 11 00 AM" src="https://user-images.githubusercontent.com/53093550/82917738-cb41d000-9f41-11ea-84c0-09e891904709.png">

### The solution
Please replace the `expressive-paragraph-01` type token with `expressive-heading-03` across all content blocks that use it.

### Additional information
- See this issue #1600 for the old request.
- Lila has reviewed and approved this revert change.

**Comment by ltitle** [comment]
@RobertaJHahn This change will apply to patterns for both Learn and Solutions. I will not log another issue from the design QA of those patterns (content block - segmented and leadspace-block) because it is documented here.
