### ISSUE TITLE
Inline and Linklist Video Player error

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2502]
We pulled down v1.7.0-rc.1 and we are noticing that the Lightbox Video Player is failing to load when a Content Block Segmented or Content Block Simple Pattern meets the following conditions:

The Pattern has both an Inline Video and a Linklist containing a video.
The LinkList Video has the same Kaltura ID as the one in the Inline Video.
Here is an example in a Drupal Lower Environment:
https://ode15.cms.ibm.net/analytics/test-kx-no-alias3

When the user clicks on the Folgers Coffee Video Link, the lightbox opens with a broken video player.

<img width="1637" alt="Screen Shot 2020-05-20 at 5 38 44 PM" src="https://user-images.githubusercontent.com/55464272/82920056-cfbbb800-9f44-11ea-8979-97a504ed83a1.png">

When the user closes that lightbox, the inline video player also is in an error state.
<img width="1533" alt="Screen Shot 2020-05-20 at 5 38 29 PM" src="https://user-images.githubusercontent.com/55464272/82920133-e5c97880-9f44-11ea-8db2-5da3632231e1.png">

**Comment by ljcarot** [comment]
@ltitle Wondering if you can try to get confirmation from Content strategists on Reboot if the use case Ke tested above would happen:  Essentially would the same video (same Kaltura ID) be displayed in both the embedded player and the link list on a page?  thx

**Comment by ltitle** [comment]
@ljcarot @kexuibm  I spoke with Tina Rapp and Jeff Eaton. They both agreed that while it may not be our best recommendation we should still support the ability for pages to reuse the same video in more than one place in case it is needed. 

Some examples they provided for context:
- A single video being used to different points in various locations
- A round of up resources
- A team that has very few assets so needs to reuse what they have in multiple places throughout the page

**Comment by ljcarot** [comment]
Thank you @ltitle .  @jeffchew @RobertaJHahn lets put this in backlog For sprint 12
