### ISSUE TITLE
Pattern:- Leadspace Block :- Spacing mismatch at top and bottom of page.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2511]
Issue Description:- As per specs there should be 64px spacing between heading and top of page where as it is less than 64px.

There should be 64px spacing between cta copy button and horizontal line where as it is more than 64px.

## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'Leadspace Block' in pattern section.
3.Check the spacing between top of page and heading text
4. Check the spacing difference between cta copy button and horizontal border line.

OS:- Mac, Windows 10
Browsers:- Chrome , Firefox, Safari, Edge.![Leadspace block top spacing.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/1453209e-5962-45fe-8ad8-dd2de03c31fb)![Leadspace bottom spacing.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/59c35d67-94d6-4e86-b4e0-044524e4d593)

**Comment by andysherman2121** [comment]
Spoke with @ltitle. The specs had an error in it, the tokens we used were correct
