### ISSUE TITLE
Develop the modal w/ margins component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#253]
_hahnrob created the following on Jun 20:_  

 

#### User Story

> As a `[user role below]`:
As a developer using the Digital Design System

> I need to:
have an Expressive Modal in the Locale Selector

> so that I can:
include this component in the Locale Selector in the web site I am developing

#### Additional information

- This issue is dependent on the design and the [package architecture https://github.com/carbon-design-system/ibm-dotcom-library/issues/253](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/860) 
- [final design and specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
              - Includes:  Functional labels, Visual redlines, Behavior and interaction specs, Desktop and mobile
 - [Box link to Mary O'Donnell's functional specs](https://ibm.ent.box.com/folder/88263129224)
 - While this expressive modal is included in the Locale Selector, it will be developed as a generic component.
 - Try to leverage the current Carbon modal and applying the expressive theme.  
 - [Carbon Modal](https://www.carbondesignsystem.com/components/modal/code)

#### Acceptance criteria
 - [ ] Component has been tested using Netlify
 - [ ] The component development follows a modular component pattern
 - [ ] The component should be accessible via ES6 import
 - [ ] The component should be visible within the living documentation of the Dotcom components
 - [ ] Presented and approved Product Owner

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1078_

**Comment by jeffchew** [comment]
_On Aug 05, hahnrob commented:_
T-shirt Sizing:  Medium

**Comment by jeffchew** [comment]
_On Sep 10, james-dow commented:_
I wanted to make sure I put this here for whoever ends up picking up this ticket. It's the APIs currently being used in v18 for the Locale selector.

- [Locale Selector API](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)
- [User Locale API](https://api.www.s81c.com/webmaster/dbip/)

**Comment by jeffchew** [comment]
_On Sep 17, hahnrob commented:_
Avi's meeting notes from Sept 16 Locale Selector JS file:  

Thanks to all of you for attending the call today.

The purpose of the call was to understand and discuss the current and future process/tool/owner for updating the locale selector JS file that it is used by ibm.com DDS team.

[https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)

This is the recap and key points:

1) Originally, ECM/IConS was used to author and generate the locale selector JS file. After the sunset of ECM/IConS, the file gets updated manually whenever there is a change. Changes are not frequent.

2) Updating the file is one small step in a multi-step process for adding/changing locales to Drupal/ibm.com

3) Tina owns the list of locales and will coordinate with the web master/MSC teams whenever the file needs to be updated.

4) A JSON format of the file is required for the new version of ibm.com design (Carbon). Once the new design is deployed, both JS and JSON files need to be updated and kept in synch. 

Please let me know if I missed/misstated anything major.

Thanks!

Avi Rakhsha
 Sr. Manager, Digital Content Platforms 
 avi_rakhsha@us.ibm.com

**Comment by jeffchew** [comment]
_On Oct 03, hahnrob commented:_
Design review meetings conducted Oct 3.

**Comment by jeffchew** [comment]
`ButtonGroup` work has been merged in to support this story: https://github.com/carbon-design-system/ibm-dotcom-library/pull/545

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.
