### ISSUE TITLE
Component:  Masthead L0 (React) Design spec update to reflect the currently available version in ibm.com Library

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2546]
The Masthead component was developed late 2019.  The available designs include future plans and changes based on user testing and studies.  In order for the currently available Masthead to be tested, the Prod QA testing team must have designs that reflect the current state.  

#### Additional information
- Design and Functional specs Box folder:  https://ibm.ent.box.com/folder/59063660753

####  Acceptance Criteria
- Updated designs of the current Masthead L0 posted to the Box folder

**Comment by larahanlon2** [comment]
Updates L0 specs can be found here (Sketch): https://ibm.box.com/s/5urb46tm7y10j98qhh2x8bkpntccs6qj

And here (PDF):
https://ibm.box.com/s/gmvjidq4uj73i6msuqhkjqfw2kre3g1g
