### ISSUE TITLE
[Feature Card] fix focus, selected state 

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2548]
Focus and selected state should have a 2px blue 60 border + 1px background-color border separation between focus and the rest of the card. You can reference how carbon does focus for the secondary button.

Also, the border should be going over the entire card, including image, on selected

current focus
<img width="843" alt="Screen Shot 2020-05-27 at 12 49 11 PM" src="https://user-images.githubusercontent.com/47458576/83061977-7aa2a380-a023-11ea-97d4-4f3aa199054e.png">

current selected
<img width="826" alt="Screen Shot 2020-05-27 at 12 49 15 PM" src="https://user-images.githubusercontent.com/47458576/83062001-85f5cf00-a023-11ea-88a5-5fd5761147d6.png">

correct focus & selected
<img width="1097" alt="Screen Shot 2020-05-27 at 2 07 24 PM" src="https://user-images.githubusercontent.com/47458576/83062026-9148fa80-a023-11ea-8094-49aeeb988e0b.png">

Carbon button
<img width="930" alt="Screen Shot 2020-05-27 at 2 10 49 PM" src="https://user-images.githubusercontent.com/47458576/83062613-8e9ad500-a024-11ea-9cf4-6feb01bf2d8c.png">

**Comment by RobertaJHahn** [comment]
@peter-garvin This is a dup of (#2206).  This issue has been assigned to the June release.  Closing this dup issue.
