### ISSUE TITLE
[Feature Card] fix image hover state

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2549]
Image hover is darkening, but it should be an **8% Lighten** for light themes so that it appears that the entire card is getting lighter on hover

Current:
<img width="1520" alt="Screen Shot 2020-05-27 at 2 21 59 PM" src="https://user-images.githubusercontent.com/47458576/83063280-79727600-a025-11ea-8f39-4d153c56d2b0.png">

Correct:
<img width="992" alt="Screen Shot 2020-05-27 at 2 21 16 PM" src="https://user-images.githubusercontent.com/47458576/83063294-8000ed80-a025-11ea-808f-b5b92c35840e.png">

**Comment by RobertaJHahn** [comment]
This is a dup of issue (#2195).  Closing this issue.
