### ISSUE TITLE
[Feature Card] Check grid alignment

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2550]
I cannot tell how it is aligning in desktop breakpoints, but it looks like in the medium bp it is 32px away from the edge. If it is in condensed grid mode, it should be 16px. Looks correct on mobile

<img width="702" alt="Screen Shot 2020-05-27 at 2 35 34 PM" src="https://user-images.githubusercontent.com/47458576/83064587-99a33480-a027-11ea-958c-a82e6976f755.png">

<img width="1469" alt="Screen Shot 2020-05-27 at 2 35 25 PM" src="https://user-images.githubusercontent.com/47458576/83064599-9d36bb80-a027-11ea-93cb-6f62f5b404e2.png">

**Comment by jeffchew** [comment]
@RobertaJHahn fyi since we are EOD I recommend we push this to `v1.9.0` release. I'm going to update it now but wanted to make you aware.

cc: @ljcarot @greeshmareddyg
