### ISSUE TITLE
Markdown Utility Learn Enhancements Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2552]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Markdown Utility`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- The development work is scheduled to be finished by Friday, June 5.  You will receive a message when the code is available for testing.
- The Design QA testing must be finished by June 10 to have the priority assigned to defects and possibly included in the June release.  
- Dev Issue (#2551 )
- [Storybook link](TBD)

 #### Tasks
Ensure the `Markdown Utility` has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn can you please clarify what markdown utility means?

**Comment by ltitle** [comment]
@RobertaJHahn Confirmed with Wonil and Jeff that we do not need design QA for this so the issue can be closed.

**Comment by RobertaJHahn** [comment]
Closing this issue based on Lila's comment above.
