### ISSUE TITLE
Content group Learn Enhancements Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2558]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Content group` pattern

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design and Functional specs information**
- The development work is scheduled to be finished by Friday, June 5.  You will receive a message when the code is available for testing.
- The Prod QA testing must be finished by June 10 to have the priority assigned to defects and possibly included in the June release.  
 - Dev issue (#2554) 

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by guilhermelMoraes** [comment]
@Praveen-sr @chetankan hi! Just to let you guys know that the development of the #2554 is finished by now. Here is the link to the deploy preview: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2620/index.html?path=/story/overview-getting-started--page

**Comment by chetankan** [comment]
@RobertaJHahn  @ljcarot : We have checked in 'ContentGroupPictogram' and 'ContentGroupSimple' it is working fine.
