### ISSUE TITLE
[ToC] Buggy scrolling and state change.

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#2559]
### ToC stops working properly after a few clicks. 

This could be an issue with my computer / browser so please try to reproduce.
I'm using Mac Chrome Version 81.0.4044.138 (Official Build) (64-bit). 
Observed below behavior after clicking on the items a few times. The first item becomes not-selectable. Selected state blue bar is stuck on second item, even when scrolled all the way to the top. 

![May-27-2020 16-53-05](https://user-images.githubusercontent.com/15144993/83071565-5652c100-a03b-11ea-9669-e9e04aeeae8a.gif)

### Steps to reproduce: 
1. go to https://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=patterns-sub-patterns-table-of-contents--with-heading-content
2. randomly click on a few ToC items
3. click on first ToC item and see if it gets selected. Often fails when I tried.

**Comment by RobertaJHahn** [comment]
@chetankan @Praveen-sr Can you try to recreate this bug.  Seems like an issue that you would have found.  Wondering if this is an edge case.

**Comment by chetankan** [comment]
@RobertaJHahn : I tired above mentioned scenario on Mac with Chrome 81ver it  is working fine.
Even checked with Windows 10 with Chrome 81 ver here also it is working fine.
