### ISSUE TITLE
Develop left panel container for v1.1.0 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#257]
_hahnrob created the following on Jun 20:_  

 As a developer, I need to create the Left Panel component within the Dotcom components package so that adopters can utilize this component in their application

#### Additional information
- Discussing with the team, this is meant to be part of a `<Layout>` component, with the option to make containers within `sticky`. For this story, this will be a left panel container with main container for content. This `<Layout>` container can accommodate for future layouts like a sticky right panel container.
 - This issue is dependent on the design and the [package architecture https://github.com/carbon-design-system/ibm-dotcom-library/issues/257](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/860)
 - The priority is documented in the component [Airtable](https://airtable.com/tblYos5iDYwTP6MCK/viw85GYbUVISjrXj9?blocks=hide)
 - Assigned priority:  https://github.com/carbon-design-system/ibm-dotcom-library/issues/257
 - This component is needed by the Product Discovery and the MyIBM Products adopters.  Product Discovery adoption is scheduled for 4Q 2019.
 - [Left Panel container design spec research https://github.com/carbon-design-system/ibm-dotcom-library/issues/257](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1303)

#### Acceptance criteria
 - [ ] Component has been tested using Netlify
 - [ ] The component development follows a modular component pattern
 - [ ] The component should be accessible via ES6 import
 - [ ] The component should be visible within the living documentation of the Dotcom components
 - [ ] Presented and approved Product Owner

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1082_

**Comment by jeffchew** [comment]
_On Oct 02, hahnrob commented:_
Review of left panel container design specs completed Oct 3.

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.
