### ISSUE TITLE
Pattern: ContentBlock Segmented -  On iPad, all sub section are not stretched to full screen size as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2570]
## Detailed description

Device : iPad 

Issue :- On ipad, the sub section are not stretched to full screen size, they are cut to half. Only the link list is stretched to full screen.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/967c50e0-f520-482a-ad29-afa044c47ba9)

Expected :- 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/41da8f30-77d1-40d3-9d3e-f35c8e1a5a70)

**Comment by kennylam** [comment]
@Praveen-sr This is correct according to the [visual specs](https://ibm.ent.box.com/file/662609167728). Once under `1056`, the side elements will drop to the bottom and the main content section is 100% width at `sm` breakpoint (672)

**Comment by guilhermelMoraes** [comment]
As Lila said yesterday, there's just a small fix to be made in the `LinksList`,
 which I'm working right now
cc: @RobertaJHahn @ltitle
