### ISSUE TITLE
Component: Table of Content:- Title with long text overlaps on jump to icon(Mobile)

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2572]
Issue Description:- If title text is long in that case text is overlapping on 'Jump to ' icon. Happening on mobile devices only.

## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'Table of Content'
3. In knobs section go to menu items and add long title. (Ex:- Cras molestie condimentum Cras molestie condimentum)
4. Open it in new page and observe jump to section.

OS:- iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, UC![TOC with long title text.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/2a350ed5-d767-4c11-ba40-8eb2c2c7b7dc)

**Comment by chetankan** [comment]
@RaphaelAmadeu @RobertaJHahn : Retested this issue on canray env, on entering long text it is not overlapping on 'Jump to ' icon.

Note:- When user clicks on 'Jump to' icon, drop down option are not getting displayed.

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Moved this issue back to Review based on Chetan's comments above.  This fix is included in the June release.  The code freeze is at the end of day on Friday, June 12.
