### ISSUE TITLE
Content Block Segmented - copy field should be made optional change as well as v1.9.0 fixes

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#2574]
**This epic contains links to all of the work required to complete this feature request.  Functional spec documentation is included below.**

#### User Story
> As a `[user role below]`:
a drupal adopter

> I need to:
copy fields to be optional

> so that I can:
meet the requirements for the solution template

#### Additional information
 - [Functional specs](https://ibm.box.com/s/k1s20tmml53qfcie7bavgb0h3pap8211)

The block copy 1.2, and content item copy 4.1 needs to be optional.

![image](https://user-images.githubusercontent.com/3793636/83680159-358feb80-a5a6-11ea-98e0-7e84b0ee2c38.png)

**Comment by RobertaJHahn** [comment]
Functional specs say that the field is required as required in the Learn template.  https://ibm.ent.box.com/file/651677070757

Changing this to a feature request.

**Comment by sbahl1** [comment]
Thank you @RobertaJHahn for staying on top of this

**Comment by RobertaJHahn** [comment]
James will confirm that making the copy optional with Lila.  The current content model does not reference this copy element at all.  If we will make the copy optional, the functional specs will be updated.

**Comment by ellenchoi1** [comment]
@RobertaJHahn James will be picking up this work since the specs are in a pages file and it'll be quicker for him.

**Comment by photodow** [comment]
Made copy field in content block, and content item optional.

https://github.com/carbon-design-system/ibm-dotcom-library/issues/2647

**Comment by RobertaJHahn** [comment]
Functional specs were reviewed with the developers in the Monday, June 8, 2020 engineering meeting.
