### ISSUE TITLE
[Functional specs]  Separate data model out

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2585]
### The problem
It's been brought to my attention that the data model isn't needed by dev anymore, and it's too technical for the functional specs.

### The solution
In response to this we need to go through every functional spec, and remove it from the document and move it to another document.

### Additional information
 - Functional specs don't contain data model anymore

**Comment by RobertaJHahn** [comment]
@photodow This issue was not closed out in sprint 20-12.  Moving to 20-13.

**Comment by photodow** [comment]
Sounds good. This one confused me when I looked at it last week. It didn't show up in sprint 12 when I looked. No worries though, we can get it done this sprint. Thanks roberta!
