### ISSUE TITLE
Clean up airtable and IBM.com library directory

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2589]
### The problem
- Directories are now out of date based on what's being organized in code. #2467 
- We have a couple old patterns that need to be archived

## The Solution
We need to go through the Airtable and IBM.com library and make sure everything is up to date and aligned.

## Acceptance criteria
- [ ] Airtable, IBM.com Library directory is aligned and up to date.

**Comment by RobertaJHahn** [comment]
@ljcarot Can I close this issue or should I move it to sprint 20-15

**Comment by ljcarot** [comment]
We can close since the directory cleanup is happening as part of cupcake publishing and if probably isn’t critical to keep Airtable list to reflect same
