### ISSUE TITLE
Utilities and services functional spec planning

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2590]
## Summary
As we have recently gotten caught up with our backlog of functional specs, I wanted to start a discussion around utilities and services, and see if these need corresponding functional specs as well. I had a brief conversation with Jeff a while back and he brought up the idea of technical documentation. Is JSDocs good enough for all of this? Do we pick and choose a couple to have functional specs?

I look at particular something like translation/locale as having a lot of documentation and has caused a lot of confusion on how it exactly is supposed to work.

##### Utilities [[code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/utilities)] 
- Markdown to Html
- same height
- altlangs
- decodeString
- escaperegexp
- featureflag
- geolocation
- ipcinfoCookie
- serialize
- settings
- smoothScroll
- unique

##### Services [[code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/services/src/services)]
- Analytics
- DDO
- Locale
- MarketingSearch
- Profile
- SearchTypehead
- Translation
- VideoPlayer
- global

## Acceptance criteria
 - [ ] Decision on how these types of things should be documented if documented at all
 - [ ] Either close this issue, or create functional spec stories for the decided upon utilities and services.

**Comment by RobertaJHahn** [comment]
Jeff decided that functional specs are not needed for the utilities.  Additional issues to create the func specs will not be created.
