### ISSUE TITLE
Link with icon – inverse visual specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#2597]
#### User Story

> As a `[user role below]`:

Designer

> I need to:

provide visual specs for inverse link

> so that:

it can be used within patterns.

#### Additional information

 - used within Callout quote pattern
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] Visual specs created
 - [ ] Visual spec file on Box
 - [ ] Notify BA and dev team of the update

**Comment by oliviaflory** [comment]
@wonilsuhibm could you please review the inverse specs for Link with icon [Box](https://ibm.ent.box.com/folder/107613134184)

Note: 
1. We don't have a token for inverse disabled 
2. We don't have a token for inverse visited (though we could change this to blue or not include a visited state)
3. I am recommending we hard code these values for now, and we can propose a token if we need.
4. I followed the interaction states that are shown on the [Notification](https://www.carbondesignsystem.com/components/notification/usage) with a link, which you can see in the live demo, all the interactive states are the same color, but have varying text decorations when the link is inverted. 

For this release, this seems like a good option until we determine if we should be using inline theming.

Once you approve, please let @photodow know he can review for updating the functional specs.

**Comment by wonilsuhibm** [comment]
@oliviaflory thank you. 

This all looks good. 

- We should look into removing the visited state color.
- The disabled state has slightly higher contrast, which I like—just curious, do you know how they came to this particular color?

@photodow I think this is ready for func specs.
