### ISSUE TITLE
Pattern: ContentBlock Segmented - No spacing between bottom section and the border line.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2603]
## Detailed description

Issue :- No spacing is provided between the bottom section and the border line.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/701c408c-2624-4910-bfe1-398d19ebbca3)

**Comment by caiobozato** [comment]
@Praveen-sr I don't see the Horizontal line at the end of `ContentBlock Segmented`: https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblocksegmented--default

Could you please specify where you found the issue mentioned above?

**Comment by Praveen-sr** [comment]
@caiobozato Steps to reproduce :

1. Open storybook and navigate to Contentblock Segmented - with aside elements
2. Click on knobs section 
3. In knobs, we have an option "border", enable that option.
4. Now go back to the pattern and scroll to the end of the pattern

Issue :- No spacing is provided between the bottom section and the border line.
