### ISSUE TITLE
Callout Quote Block Pattern missing a property for property

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2605]
Using Callout Quote Block pattern from release 1.7.0.

It seems like there is a missing property for the Callout Quote specifically the company that provided the quote.

![image](https://user-images.githubusercontent.com/55464272/83412270-d1272d80-a3e7-11ea-878f-70e34039db35.png)

For example in the Visual design, there is no property for the company field( NBCUniversal ).

**Comment by ljcarot** [comment]
@RobertaJHahn do you know who did the func spec for Callout Quote?

**Comment by RobertaJHahn** [comment]
The second link under the copy line should be `copy 2` and not company as suggested by Ke.  The field should also be optional.

**Comment by kexuibm** [comment]
@RobertaJHahn  and @jeffchew I don't see an additional copy field (copy2)  in the  Callout Quote Block Pattern in release 1.8.0.    Can you please re-open this defect?

**Comment by ljcarot** [comment]
@guilhermelMoraes Can you confirm additional copy field was added?

**Comment by ljcarot** [comment]
@kexuibm This is slated for Release 1.9.0.  That's why you didn't see it in 1.8.0.  You will see it in Beta Release 13 that gets created on Friday July 3.

**Comment by guilhermelMoraes** [comment]
@ljcarot it was added, but I didn't add the knob in the panel of the `CallOutQuote` story. My apologies for that. I'm wrapping up a PR right now to fix this anyway, so it will be in better shape when the release is ready.
