### ISSUE TITLE
CalloutQuote Block Pattern has styling issues when rendered in Layout

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2607]
In release 1.7.0, the CalloutQuote Block pattern seems to have a styling issue when it is rendered within a Layout component.  Basically the Quote Source Copy would wrap into 2 lines instead of staying as one line.

<img width="1202" alt="Screen Shot 2020-06-01 at 9 41 04 AM" src="https://user-images.githubusercontent.com/55464272/83414784-0e8dba00-a3ec-11ea-9dbc-fca41756860a.png">

So in the above screenshot, the Quote Source Copy Manager of Platform Devops is wrapping into 2 lines.   This seems to happen for us when the block is wrapped in the Layout component.

Here is my layout configuration for this block pattern:

  <Layout nested={true} type="2-1" border={true}>
    <div>
      <CalloutQuote quote={quote} />
    </div>
    <div></div>
  </Layout>

**Comment by annawen1** [comment]
@kexuibm @RaphaelAmadeu I wonder if this is the same as [Feature-card-block-large block pattern is not styled correctly when in Layout #2649](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2649) on whether the CalloutQuote should be rendered in Layout.

**Comment by annawen1** [comment]
Hey @kexuibm, @ltitle commented on the [Feature-card-block-large block pattern is not styled correctly when in Layout #2649](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2649) ticket and I believe it is the same for the CalloutQuote here where intent is to not put it in Layout.
