### ISSUE TITLE
Content Block Segmented Items array should be optional?

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#2608]
### The problem
_{{A clear and concise description of what the problem this new feature is trying to solve. (ex. I'm always frustrated when...)}}_
From Drupal Side we are trying to integrate Proof Section in Solution(Services) Content model. For the Proof Section we are using Content Block Segmented Pattern where It has Items array a required field but in the Proof section it doesn't render Items array. It only renders Headline, Image(or video) and link. Can we make Items array as optional in Content Block Segmented?

### The solution
_{{A clear and concise description of what you want to happen}}_
Can we make Items array as optional in Content Block Segmented? for Solution(Services) Content Model to work cleanly

### Additional information
 _{{Please provide any additional information or resources for reference}}_
 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

**Comment by annawen1** [comment]
@sridharmula can you provide a visual spec for how the proof section would look like? It sounds like we could possibly use another component instead

**Comment by RobertaJHahn** [comment]
@photodow I have converted this issue to an epic because the work will take more than one sprint to finish, including the dev and Prod QA.  The next step is to work with the designers and document the functional specs for the dev work.  Let me know if you have any questions.  Thanks

**Comment by RobertaJHahn** [comment]
This is a Drupal request.  Closing this issue.  Decision has been made to replace Drupal v2 with AEM.
