### ISSUE TITLE
Component: LinkList - Accessibility - jaws is identifying links only as texts, the user does not know that these are interactive elements.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2611]
## Detailed description

Link list - Default and Vertical

Issue :- Learn more, Containerization A Complete Guide, Microservices and containers, Folgers Coffee (1:00) - jaws is identifying these links only as texts hence the user does not know that these are interactive elements.

Note: On Content Block Segmented - jaws is identifying these links only as texts.

## Additional information
Link List:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/9c514040-cd0a-4489-8fef-7f6297585fe7)

Content Block Segmented:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ab0618c8-0ec0-4720-a599-4b8d475ef591)

**Comment by guilhermelMoraes** [comment]
@Praveen-sr looks like this issue was reported and fixed already. Here's the link: https://github.com/carbon-design-system/ibm-dotcom-library/pull/2634 

cc @RaphaelAmadeu

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn 
I think we can close this, as Gui has already fixed it

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn I think we can close this issue as this was fixed by Gui in another one

**Comment by Praveen-sr** [comment]
@RobertaJHahn Re checked this issue, jaws is identifying links now. Thanks!

**Comment by RobertaJHahn** [comment]
Closing as the bug has been fixed in PR (#2634)
