### ISSUE TITLE
Pattern / Component - Leadspace Block & Link List - keyboard focus is not covering all four sides of the element.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2612]
## Detailed description

Issue :- Visual focus is there but its not covering all four sides of the element.

## Additional information
Leadspace block:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dffe441b-0b72-45f1-8821-24cf5151d96c)

Link list :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c3728690-880f-4fb5-bc64-f4ed38810947)

**Comment by jeffchew** [comment]
@guilhermelMoraes can you take this one as well since you're already looking at `LinkList`?

**Comment by guilhermelMoraes** [comment]
@jeffchew yes, sure

**Comment by Praveen-sr** [comment]
@RobertaJHahn Re checked this issues, keyboard focus on elements is working as expected.
