### ISSUE TITLE
Pattern: Leadspace block: media caption styling and spacing

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2613]
## Leadspace block: media caption styling and spacing

> Describe in detail the issue you're having.

Caption below media (video or image) is not styled properly. Spacing between media and caption is also not correct.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Yes, media components with captions

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**Current styling:** 
text: 16/24px
color: black
**Current spacing:**
0px from media

![image](https://user-images.githubusercontent.com/57198117/83427677-173bbb80-a3ff-11ea-8761-71532b51e252.png)

**Expected styling:**
text: $caption-01 (14/20px)
color: $text-05
**Expected spacing:**
Caption is 8px from bottom of media

![image](https://user-images.githubusercontent.com/57198117/83427704-228ee700-a3ff-11ea-93a9-f987324c5592.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react-experimental.mybluemix.net/iframe.html?id=patterns-blocks-leadspaceblock--default

**Comment by RobertaJHahn** [comment]
Olivia will contact Lila for a design spec change.  The Caption 01 should not be used.  Label 01 will be used instead.

**Comment by ltitle** [comment]
@RobertaJHahn I did not create specs for this I default to what Olivia and Seth have spec'd so if they say Label-01 that is fine.

**Comment by andysherman2121** [comment]
Both Caption-01 and Label-01 are showing up as 10px not 14px. We need to figure out which token we should be using or if Carbon needs to update this

**Comment by andysherman2121** [comment]
Using body-short-01 per @oliviaflory
