### ISSUE TITLE
Pattern: Leadspace block: CTA button does not span full width on small breakpoint

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2616]
## Leadspace block: CTA button

> Describe in detail the issue you're having.

Button is not spanning 100% of 4 columns on Small breakpoint
Need CTA button option without icon for all breakpoints - **already fixed**

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Leadspace - block (same as all leadspace patterns)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook:**
Button does not span full width on Small breakpoint
No option for CTA button without icon - **already fixed**

![image](https://user-images.githubusercontent.com/57198117/83430294-67b51800-a403-11ea-8958-8f8e06ae7379.png)

**As expected:**
Button spans 100% of 4 column container on Small breakpoint
CTA button without icon for all breakpoints

![image](https://user-images.githubusercontent.com/57198117/83430336-7c91ab80-a403-11ea-8f3d-73302321d9ec.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-leadspaceblock--default

**Comment by ljcarot** [comment]
@andysherman2121 can you confirm that what you are working on with respect to fixing this bug will also fix the CTA section button as well.  @chetankan opened this https://github.com/carbon-design-system/ibm-dotcom-library/issues/2874 and I think it is duplicate to this one.  Please confirm and if yes, I'll close his.

**Comment by andysherman2121** [comment]
@ljcarot Yup can confirm this is a duplicate

**Comment by andysherman2121** [comment]
https://github.com/carbon-design-system/ibm-dotcom-library/pull/3254
This PR fixes the bug
