### ISSUE TITLE
Pattern: Content group: Spacing

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2624]
## Content group: Spacing

> Describe in detail the issue you're having.

Different spacing is needed under the intro paragraph for each content group pattern. Therefore the item level needs to be able to hold the extra spacing and turn it on and off

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content group
Content group simple
Content group with pictograms
Content group with cards

> What did you expect to happen? What happened instead? What would you like to
> see changed?

### **Content group simple**

**As seen in Storybook:**
Using 64px spacing between intro text and media or content item
64px padding below intro text

Example with media

![image](https://user-images.githubusercontent.com/57198117/83454923-effae380-a42a-11ea-9d7a-457612e6039d.png)

Example with content item

![image](https://user-images.githubusercontent.com/57198117/83454875-df4a6d80-a42a-11ea-9eb7-1d5d7367af97.png)

**As expected:**
Using 32px spacing between intro text and media or content item
32px padding below intro text

Example with media:
![image](https://user-images.githubusercontent.com/57198117/83454634-795de600-a42a-11ea-8c6a-fd8d88d75ccd.png)

Example with content item
![image](https://user-images.githubusercontent.com/57198117/83454987-11f46600-a42b-11ea-9030-886fb32e37c1.png)

---------------

### **Content group with pictograms**

**As seen in Storybook:**
Using 96px spacing between intro text and pictogram item
64px padding below the intro text + 32px padding above the pictogram item

![image](https://user-images.githubusercontent.com/57198117/83455844-972c4a80-a42c-11ea-8a03-329f94115b05.png)

32px padding above and below all pictogram items
![image](https://user-images.githubusercontent.com/57198117/83456276-63055980-a42d-11ea-8c37-8bf875785941.png)

**As expected:**
Using 64px spacing between intro text and pictogram item
Can accomplish by using 32px padding below intro text + 32px padding above pictogram item (just an idea to keep consistent with the need for 32px padding above and the fact that pictogram item seems to already have top padding)

![image](https://user-images.githubusercontent.com/57198117/83455965-c93dac80-a42c-11ea-874e-1d6a096d0bc3.png)

The last pictogram item in the series needs to remove bottom padding to have consistent spacing in Content block mixed groups (otherwise it is adding 32px with the 96px to create 120px between sections that come after pictogram group)
![image](https://user-images.githubusercontent.com/57198117/83456956-b2985500-a42e-11ea-97f9-ec25bd8b096f.png)

---------

### **Content group with cards**
VISUALS ARE CURRENTLY FINE BUT WILL BE IMPACTED BY CHANGES ABOVE. SEE BELOW FOR RECOMMENDATIONS

**As seen in Storybook:**
Using 64px spacing between intro text and cards group
This spacing amount is currently correct, however, if we reduce the spacing below the intro text to 32px to accommodate Content group simple and Content group with pictograms we will need another solution for Content group with cards as well.

**As expected:**
Using 64px spacing between intro text and cards group
32px between Group title and cards when there is no intro text
Solution idea: Add 32px spacing above Cards group to create the 64px when there is an intro paragraph. Turn 32px spacing above cards off when there is no intro paragraph?

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2620/index.html?path=/story/patterns-blocks-contentgroupsimple--default

**Comment by ltitle** [comment]
This issue is fairly complex. Please let me know if you want to discuss further.

**Comment by photodow** [comment]
@ltitle let me know if I'm over simplifying this...

1. Set default content group spacing...

```scss
.bx--content-group__copy {
  margin-bottom: $carbon--layout-03; // 32px
}
```

2. Override content group spacing to match specs...

```scss
.bx--content-group-cards__copy {
  margin-bottom: $carbon--layout-05; // 64px
}
```

I think that'll fix the following requirements here...

- [x] Content group simple copy `32px` (group default copy)
- [x] Content group with pictograms `64px` (`32px` group default copy, `32px` pictogram item)
- [x] Content group with cards `64px` (override)

**Comment by ltitle** [comment]
@photodow Yes I think what you proposed above makes sense as long as the content group with cards get an override to produce the 64px spacing when there is an intro paragraph and 32px spacing without a paragraph. 

One other issue I called out here (not related to intro paragraphs) is that the pictogram item has top and bottom padding. We need to remove or collapse the bottom padding when it is the last item in the list because it is adding with the padding for the next sub-section and the space becomes too large (120px (32px + 96px) instead of 96px)

**Comment by RaphaelAmadeu** [comment]
@ltitle 
I've made updates in the ContentGroupPictograms, and checked all the another spacings mentioned on the issue as well.

You can check it here,
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2851/index.html

Thank you!
