### ISSUE TITLE
Content block segmented: missing CTA at item level

### ISSUE THREAD

**Issue by jpathan-dev** [carbon-design-system/ibm-dotcom-library#2637]
## Detailed description

> Describe in detail the issue you're having.
CTA does not render from the given items array

`var items = [
  {
    heading: '{{ content.field_subheadline }}',
    image: {
      heading: '{{ content.field_short_copy }}',
      image: {
        sources: [
          {
            src: '{{ file_url(node.field_imagefile_s.entity.uri.value) }}',
            breakpoint: 320,
          },
          {
            src: '{{ file_url(node.field_imagefile_s.entity.uri.value) }}',
            breakpoint: 400,
          },
          {
            src: '{{ file_url(node.field_imagefile_s.entity.uri.value) }}',
            breakpoint: 672,
          },
        ],
        alt: '{{ node.field_alttext.value }}',
        defaultSrc: '{{ file_url(node.field_imagefile_s.entity.uri.value) }}',
      },
    },
    copy: '',
    cta: {
      href: "{{ content.field_link[0]['#url'] }}",
      copy: "{{ content.field_link[0]['#title'] }}",
      type: 'local',
      stype: 'text'
    },
  },`
> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug
> Is this issue related to a specific component?
Content Block Segmented
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
chrome

> What version of the IBM.com Library are you using?
Tested on 1.7.0 and 1.7.0-rc.1
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes
![Screen Shot 2020-06-04 at 8 22 55 PM](https://user-images.githubusercontent.com/62308387/83823215-6143cc00-a6a1-11ea-91d1-76310c3e143a.png)

**Comment by andysherman2121** [comment]
This was the original issue: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1845

Raph had previously fixed it with this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/2396

It wasn't merged till after a code freeze so it's been canary for a few weeks
