### ISSUE TITLE
Pattern: Change the Content block - segmented pattern to make the copy field optional

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2638]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
change the `Content block - segmented` pattern

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic for the Functional specs information**
- Prod QA testing issue (#2639 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] block copy is now optional
 - [ ] content item copy is now optional
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished
- [ ] The Canary URL is added to the Prod QA issue for their testing

**Comment by ljcarot** [comment]
@andy is this ready for QA team to test?  cc: @RobertaJHahn

**Comment by andysherman2121** [comment]
@ljcarot Yup. @chetankan @Praveen-sr ready for testing

**Comment by andysherman2121** [comment]
@chetankan @Praveen-sr The copy field is only optional in the actual codebase, not in storybook. I'm creating an optional copy knob so that you guys can test

**Comment by andysherman2121** [comment]
@chetankan @Praveen-sr You guys can use this link to test the optional copy knob 

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2975/index.html
