### ISSUE TITLE
Can't select region in Footer

### ISSUE THREAD

**Issue by litao8976** [carbon-design-system/ibm-dotcom-library#2642]
Can't select region in Footer

Hi team, my footer shows as below

<img width="634" alt="footer" src="https://user-images.githubusercontent.com/4714096/83599874-df1fae80-a59f-11ea-8c2a-a92001945b19.png">

<img width="632" alt="footer-filter" src="https://user-images.githubusercontent.com/4714096/83599882-e1820880-a59f-11ea-870c-eb2e747d40ba.png">

The version is  "@carbon/ibmdotcom-react": "^1.7.0", 
I'm using create react app, already eject and set the  CORS_PROXY=https://cors-anywhere.herokuapp.com/

I also checked the data from react dev tool. I can get the data in LocaleModal, but in the LocaleModalRegions component the data is null array.

<img width="1251" alt="regionList" src="https://user-images.githubusercontent.com/4714096/83600239-b6e47f80-a5a0-11ea-8ad6-1b43e1525bb8.png">

<img width="1292" alt="LocaleModal" src="https://user-images.githubusercontent.com/4714096/83600244-b9df7000-a5a0-11ea-9fc2-6c8e08046f52.png">

Could anyone give me some advice how to fix this issue ?
Many thanks!

**Comment by andysherman2121** [comment]
@litao8976 Hi Tony, here's the link to configure multiple locale/language alternatives. https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/docs/building-for-ibm-dotcom.md

**Comment by litao8976** [comment]
Hi @andysherman2121 ,
Thank you so much for your comments. My issue already been fixed by following the guide you provided. Very appreciated!

**Comment by andysherman2121** [comment]
@litao8976 awesome, glad we could help
