### ISSUE TITLE
Content block segmented optional copy

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2647]
#### User Story
> As a `[user role below]`:
a drupal adopter

> I need to:
copy fields to be optional

> so that I can:
meet the requirements for the solution template

#### Additional information
 - [Functional specs](https://ibm.box.com/s/k1s20tmml53qfcie7bavgb0h3pap8211)

The block copy 1.2, and content item copy 4.1 needs to be optional.

![image](https://user-images.githubusercontent.com/3793636/83680159-358feb80-a5a6-11ea-98e0-7e84b0ee2c38.png)

#### Acceptance criteria
 - [ ] block copy is now optional
 - [ ] content item copy is now optional

**Comment by RobertaJHahn** [comment]
Functional specs were reviewed with the developers.  The documentation included in this issue was added to the epic (#2574)  Closing this issue.
