### ISSUE TITLE
Footer language selector "The prop `placeholder` is marked as required in `ComboBox`, but its value is `undefined`."

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#2657]
1.7.0 version
a property is missing for the language selector, not sure If it is our mistake, but we did set
all properties to the footer as required per docs.

![image](https://user-images.githubusercontent.com/15310250/83756636-a0592980-a66f-11ea-9a5d-d95e9e986977.png)

**Comment by guilhermelMoraes** [comment]
@kyjak hi! Can you, please, provide a step by step of how to reproduce this problem? Thanks

**Comment by guilhermelMoraes** [comment]
@kyjak hi! 😄  Are you still facing this problem? I'm not being able to reproduce it. The console throws a few messages, but none of them is related to that property. Please let me know if you need help. Otherwise, we can go ahead and close this issue.

**Comment by kyjak** [comment]
Yes, the problem still persists, our dev env.
http://dev.ibmdocs-internal-427985-6099123ce774e592a519d7c33db8265e-0000.us-south.containers.appdomain.cloud/en/ssw_aix_72/install/configassist.html
