### ISSUE TITLE
Mega menu component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#266]
_hahnrob created the following on Jun 25:_  

 This is an Epic that contains links to all of the work required to create the block link component 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1121_

**Comment by RobertaJHahn** [comment]
Scott is doing user testing and research.  Moving this issue to Icebox until more information is available from his work.

**Comment by RobertaJHahn** [comment]
The work Olivia is doing with the Reboot team replaces Scott's work.  Closing this issue.
