### ISSUE TITLE
Masthead platform name + navigation rendering issue

### ISSUE THREAD

**Issue by Palke** [carbon-design-system/ibm-dotcom-library#2663]
If the Masthead has enabled both options (platform name, navigation) rendering is broken. 

Not sure if this is a bug or they are not supposed to be used together - there is no information available about it.

Steps to replicate:
1) https://ibmdotcom-react.mybluemix.net/?path=/story/components-dotcom-shell--default
2) Enable knob: "platform" and "navigation"
3) Break it

<img width="900" alt="image" src="https://user-images.githubusercontent.com/54019675/83798283-b76a3c80-a6ac-11ea-9605-40f38a9f9f55.png">

v1.7.0

**Comment by kennylam** [comment]
This is resolved in `v1.8.0`

https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default
