### ISSUE TITLE
Pattern: Content group horizontal: Grid alignment

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2670]
## Content group horizontal: Grid alignment

> Describe in detail the issue you're having.

The pattern is not properly aligning to the grid. Some text is not sitting on columns.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content group horizontal (may be dependent on content item horizontal)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook:**
Text and links in the second column at the item level is not aligned with the grid. This can be seen at Medium, Large, XL and Max breakpoints

![image](https://user-images.githubusercontent.com/57198117/83901319-90e9e700-a728-11ea-95ef-5c58ac4c7605.png)

**Expected from visual specs:**
Text aligns on grid columns at all breakpoints

![image](https://user-images.githubusercontent.com/57198117/83901405-b676f080-a728-11ea-9d47-b3bca10317e3.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html?path=/story/patterns-blocks-contentgrouphorizontal--default

**Comment by RobertaJHahn** [comment]
Notes from June 11, Leadership planning meeting.

The grid alignment will be fixed all at once.  Wonil will perform an audit and provide the information to Roberta so that Dev issue can be created.  This issue and (#2673) will be referenced in the new dev issue and closed.
