### ISSUE TITLE
Pattern: Content group horizontal: End of section rule

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2672]
## Content group horizontal: End of section rule

> Describe in detail the issue you're having.

The horizontal rule at the end of the section is missing from the pattern

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content group horizontal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook:**
No horizontal rule at the end of the section:

![image](https://user-images.githubusercontent.com/57198117/83902073-c17e5080-a729-11ea-82ff-295b99b4759e.png)

**As expected from visual specs:**
Horizontal rule at end of section

![image](https://user-images.githubusercontent.com/57198117/83902180-e70b5a00-a729-11ea-9580-1bdc36351ab2.png)
![image](https://user-images.githubusercontent.com/57198117/83902184-ea9ee100-a729-11ea-8422-2679f19853ac.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html?path=/story/patterns-blocks-contentgrouphorizontal--default

**Comment by kennylam** [comment]
Fixed in https://github.com/carbon-design-system/ibm-dotcom-library/pull/2562
