### ISSUE TITLE
Pattern: Content item horizontal: Misalignment to grid

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2673]
## Content item horizontal: Misalignment to grid

> Describe in detail the issue you're having.

Pattern is not properly aligning to the grid columns and layout

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content item horizontal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook:**
Pattern is spanning 11 columns rather than 10
Pattern is starting on the 3rd column rather than the 5th
Description text and links are not aligned to a grid column

As seen in Large, XL and Max breakpoints
![image](https://user-images.githubusercontent.com/57198117/83903548-584c0c80-a72c-11ea-96f1-66e49f450f16.png)

Medium breakpoint:
![image](https://user-images.githubusercontent.com/57198117/83903609-73b71780-a72c-11ea-9c40-0eb72e326a8b.png)

As expected from visual specs:
Pattern spans 10 columns
Pattern begins on the 5th column
All text and links are aligned to grid columns

![image](https://user-images.githubusercontent.com/57198117/83903759-b1b43b80-a72c-11ea-8a91-840852c9a924.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html?path=/story/patterns-sub-patterns-contentitemhorizontal--default

**Comment by RobertaJHahn** [comment]
Notes from June 11, Leadership planning meeting.

The grid alignment will be fixed all at once.  Wonil will perform an audit and provide the information to Roberta so that Dev issue can be created.  This issue and (#2670) will be referenced in the new dev issue and closed.
