### ISSUE TITLE
Pattern: Content item horizontal: Bottom padding

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#2676]
## Content item horizontal: Bottom padding

> Describe in detail the issue you're having.

Bottom padding for each item on Small breakpoint needs to be reduced

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content item horizontal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook:**
48px spacing on the bottom of each content item on Small breakpoint. 32px padding is being added with 16px padding below the link text

![image](https://user-images.githubusercontent.com/57198117/83910427-83d4f400-a738-11ea-884d-7b24bce0ea2e.png)

**As expected from visual specs:**
32px spacing on the bottom of each content item on Small breakpoint unless it is the end of the section 

![image](https://user-images.githubusercontent.com/57198117/83910445-8df6f280-a738-11ea-8b7a-4afca27e11cd.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html?path=/story/patterns-sub-patterns-contentitemhorizontal--default

**Comment by guilhermelMoraes** [comment]
@ltitle I believe someone has already fixed this problem. This is how the `ContentGroupHorizontal` looks like right now. 

![Captura de Tela 2020-06-23 às 16 50 33](https://user-images.githubusercontent.com/42848561/85452874-af960d80-b571-11ea-859d-4362ee7ce563.png)

**Comment by ltitle** [comment]
Great thank you!
