### ISSUE TITLE
Create Get Started documentation for IBM.com makers

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#2683]
The problem:
During the DDS Hills Workshop, we identified the pain point that designers/developers need a quick way to get started building their site in Carbon.

### The solution
Whether we create a video recording or simple instructions, we should have a resource for IBM.com makers to use to get started without relying on DDS team and/or having their team be fully assigned.  It should allow initial design and creation of a simple page (aka Hello World).

### Additional information
Ideally the get started should serve both designers and developers but it may need to be in 2 parts if we learn the needs are different depending on the role.

**Comment by RobertaJHahn** [comment]
This work is being managed on the Digital Design Ideation board under [issue #63](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/63)  Closing this issue.
