### ISSUE TITLE
Inline Video Player does not stop playing when Lighbox Video Player plays.

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2687]
When a page has both the inline video player and the lighbox video player that is launched from the linklist, there is a behavior where:

1.  User plays the inline video player.

2.  User clicks on the video link in a Link list and plays the lightbox video.

The observed issue is that the inline video player is still playing while the lightbox video is also playing.  Should the inline video player pause when the lightbox video player is playing?

Here is an example Drupal page where this is happening:
https://ode15.cms.ibm.net/analytics/test-simple-pattern

**Comment by ljcarot** [comment]
@kexuibm We think that this is an edge case and it would be very challenging to have something monitoring if another player is already playing somewhere else on the page so given the overhead to fix this for such an edge case, I'm going to suggest we icebox this until we get real customer reporting problem.
