### ISSUE TITLE
Fix the console errors coming from React package

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2693]
## Detailed description

> Describe in detail the issue you're having.

When running unit tests, there are a number of console errors appearing in the output. These should be fixed.

## Steps to reproduce the issue

1. Run `yarn test:unit` under `/packages/react`

## Additional information

<img width="1021" alt="Screen Shot 2020-06-08 at 3 21 08 PM" src="https://user-images.githubusercontent.com/1641214/84071437-b29ed480-a99b-11ea-90ac-f383e6184cb1.png">

**Comment by caiobozato** [comment]
@jeffchew @asudoh @RobertaJHahn unassigned myself because next two weeks I'll be working on Support pages with @guilhermelMoraes
