### ISSUE TITLE
IBM.com layout options per user intent

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#270]
_Wonil-Suh1 created the following on Jun 27:_  

 *Use this template to create an issue for the ideating column when the solution to a problem is unclear, or when the work is rather generative.*

#### Introduction
Let's build a library of high level layout options, mapped to user intents such as reading, transacting, navigating, etc, in preparation for 1. user journey project; 2. publication on website

#### The problem
- As teams start designing, they need a list of curated layout options so that the experiences they build are aligned with ones built by other teams.

#### Expected otcomes
- A list of layout options with user intent and 5E mapping (AirTable was suggested)
- A Sketch file(s) that showcase the various layouts

#### Additional information
Will look into Duo explorations, STUF frame work, and DGC squad experiences. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1136_

**Comment by larahanlon2** [comment]
Closing this out because it's not our work anymore. It's for Web Simplification.
