### ISSUE TITLE
Component : CTA - Keyboard -The Focus is going out of the model page. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2725]
## Detailed description

Issue :- The Focus is going out of the model page. 

Expected Result:-
When the model page is open focus should be trapped with the model page, it should not go to the browser or parent page.

**Comment by diegomarcuz** [comment]
Hey @Praveen-sr, I need your help
I didn’t understand well what you mean here, could you please clarify?

**Comment by Praveen-sr** [comment]
@diegomarcuz 
1. On CTA,  go to knobs section
2. In Type edit/ change it to VIdeo
3. Click on the link and a video modal opens 
4. Here when the user navigates using tab/shift tab key, the focus is expected to be trapped within the modal

Ram, re tested this scenario on react-staging server, issue is fixed.

**Comment by diegomarcuz** [comment]
As Praveen commented above and on the QA review meeting issue was fixed.

Just a representation what happens (on the close button, focus needs to happen when tab key is clicked)

![Screen Shot 2020-06-29 at 10.32.37.png](https://images.zenhubusercontent.com/5eed25994ac8fb057241e3b2/cf5b5823-a519-4824-aafa-6c9344cd5313)

cc: @RobertaJHahn
