### ISSUE TITLE
fix dependency mapping of `dompurify` in utilities package

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2748]
## Detailed description

> Describe in detail the issue you're having.

The NextJS staging environment did not build properly as `dompurity`, which is an import for the `markdownToHTML` utility, was identified as a devDependency so it isn't getting picked up on the application side. A fix has already been pushed directly to the release branch, but this is an issue to track this fix in case other adopters pick up this issue in `v1.8.0-rc.0`.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

markdownTo
> What did you expect to happen? What happened instead? What would you like to
> see changed?

Need to move `dompurity` into `dependencies` in the utilities package

> What version of the IBM.com Library are you using?

`v1.8.0-rc.0`

## Additional information

- ibmdotcom-nextjs-staging will be failing until we get this fix in `rc.1`.

**Comment by asudoh** [comment]
FYI; Seems that we need to do similar for `marked`, too: https://github.com/carbon-design-system/ibm-dotcom-library/blob/7fea9b2/packages/utilities/package.json#L70 https://github.com/carbon-design-system/ibm-dotcom-library/blob/41ebf6f/packages/utilities/src/utilities/markdownToHtml/markdownToHtml.js#L9
