### ISSUE TITLE
Component: Image With Caption :- On mobile device in landscape mode image is not visible.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2768]
Issue Description:- On mobile landscape mode 'Image with Caption' component image is not visible .

## Steps to reproduce the issue

1.Enter url in mobile browser.
2. Select 'ImageWithCaption' component.
3. Turn to landscape mode.
4. Click on image.

OS:- iOS 12, 13  Android 8,9
Browsers:- Chrome, Safari, UC Browser.

URL :- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-imagewithcaption--default

![imagewithcaption in landscpae mode.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/76bedd02-443c-43dc-90e9-32c0bd22d811)

**Comment by RobertaJHahn** [comment]
@caiobozato Hi Caio, This issue has been moved into the Done pipeline, but the linked PR #3116 is still open.  Is this work done and the issue can be closed?
