### ISSUE TITLE
Component : Quote :- Spacing between text and quotes on mobile devices.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2770]
Issue Description:- On mobile devices there is more pace between 'Quote' and beginning of  quote copy text on mobile devices.

## Steps to reproduce the issue

1. Enter url in the mobile browser.
2. Select 'Quote' component.
3. Open in new page.
4. Check the spacing between quote and start of text.

OS:- iOS 12, 13  Android 8,9
Browsers:- Chrome, Safari, UC browser.

URL;- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-quote--default

![Quote component on mobile.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/f4756dcd-ce6f-45b3-a804-6fe1453ee93a)

**Comment by RaphaelAmadeu** [comment]
@chetankan 
Could you please test it using the latest version?
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-quote--default
thank you!

**Comment by chetankan** [comment]
@RaphaelAmadeu @RobertaJHahn : Retested in canary env and it is working fine.

**Comment by RaphaelAmadeu** [comment]
@RobertaJHahn 
I think we can close this issue,
Thanks!
