### ISSUE TITLE
Carbon Theme implementation

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2777]
The theming has been implemented using the inverse checkbox and the Carbon Theme options.  This approach is causing inconsistency in the designs.  

####  Additional Information
- The following patterns include the inverse theme checkbox
    -Card(Static/Clickable)
    -ImageWithCaption
    -VideoPlayer
    -ContentBlockSimple(Default)

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Here is the issue we talked about in our meeting earlier today.  Linda would like you to review the patterns and provide us with a list of the patterns that must be updated.  Thanks.

**Comment by chetankan** [comment]
@RobertaJHahn :- Below mentioned 'Patterns/Components' have inverse option 

1. Card(Static/Clickable)
2. ImageWithCaption
3. VideoPlayer
4. ContentBlockSimple(Default)

**Comment by RobertaJHahn** [comment]
Design decisions made:  1) Inverse theme will only be used for Card

Dev issues needed:  1)  Remove inverse from the above patterns.  2)  Prod QA issues are needed.
