### ISSUE TITLE
Black theme for masthead

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#2791]
Mentioned during meetings, KC needs a footer like styling for the header (basically inverse of the white one we have now).
We could override the styling ourselves, but in case there is more adopters looking for this feature, might be good idea to do it here.

**Comment by RobertaJHahn** [comment]
Moving this feature request forward is dependent on the overall design decision about whether a black theme Masthead will be generally available.  Color theme research is underway.  The design decision will be made based on the design research.

**Comment by wonilsuhibm** [comment]
@kyjak The masthead is a standard for IBM.com. Can you share more about why dark theme is necessary? Also design proposals please?

**Comment by kyjak** [comment]
Contact either Karen Buchanan or Andree Proulx.
I think this was discussed already in the past on a higher level, I just know we need it.

**Comment by wonilsuhibm** [comment]
We met with the Knowledge Center team and here are the conclusions:
- The IBM.com portion of Knowledge Center (home page, some of the navigational pages) will use the default (white) IBM.com masthead.
- The product documentation will most likely use the Carbon UI Shell with all of the color themes available to match that of the respective product experience.
