### ISSUE TITLE
Component :- Masthead :- On mobile search icon should not be visible on clicking hamburger icon.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2794]
Issue Description :- On mobile devices when user clicks on 'Hamburger menu' icon in that case search icon or profile icon should not be visible where as in stage env clicking on hamburger icon search icon is visible.

## Steps to reproduce the issue

1. Enter url in mobile browser.
2. Click on 'Hamburger menu' icon.
3. Check if search icon is visible or not.

OS:- iOS 12, 13  Android 8,9
Browsers:- Chrome, Safari , UC browser.

URL :- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-masthead--with-platform![Masthead searchbox.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/e2603448-206f-4595-9756-0dcfa7e8c798)

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr @chetankan 
PR https://github.com/carbon-design-system/ibm-dotcom-library/pull/2797

**Comment by chetankan** [comment]
@RobertaJHahn : Retested on stage env it is working fine now.
