### ISSUE TITLE
Pattern: CTA section visual design & design spec Services template changes provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2795]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Services template.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
- **Scheduled delivery date:  June 22**
- [Visual Designs & Design Specs Box folder](https://ibm.ent.box.com/folder/109648616047)
 

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
6/22/2020:  Designs reviewed with Lila in the engineering meeting for a sizing.

**Comment by ltitle** [comment]
@RobertaJHahn Design spec PDF and Sketch files are now posted here: 
https://ibm.ent.box.com/folder/109648616047
