### ISSUE TITLE
Wrong hover state on footer links

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#2801]
## Wrong hover state on footer links

-->

## A few links in the footer on story book do not have the correct hover state. The hover state on the links should go from $text-02 to $text-01 but currently there is no change in color. 

Links with this issue are: 

- Case studies
- Demos
- Redbooks
- Services
- Industries
- Federal and state contracts
- Careers
- Events
- Latest news
- Strategic partnerships
- Investor relations

Incorrect hover state:
![Screen Shot 2020-06-17 at 10.30.16 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/f7c6fa05-6611-423a-b462-738db5fbc400)

Correct hover state:
![Screen Shot 2020-06-17 at 10.30.42 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/5aecd50b-8e5b-47a4-a3fb-297e968522a3)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The hover state on links should be $text-02 to $text-01 but no color change is happening. 

> What browser are you working in?
Chrome, Safari 
## Steps to reproduce the issue

1. Go to https://ibmdotcom-react.mybluemix.net/iframe.html?id=components-footer--default&_ga=2.200702190.1578434434.1592326270-372237420.1590174837
2. Hover over links

**Comment by kennylam** [comment]
@jacobottesen-dgc I'm unable to reproduce in any browser.

![image](https://user-images.githubusercontent.com/909118/84931401-c1bf0a00-b0a0-11ea-8e97-6f98b05229ed.png)

**Comment by jacobottesen-dgc** [comment]
Did you use Safari as the browser?
