### ISSUE TITLE
Component Design Kit gray 10 theme MVP

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#281]
_Wonil-Suh1 created the following on Jul 17:_  

 User story
As an adopter of the Carbon + dotcom add-on, I need a design kit with components for digital design (16px type size) in gray 10 theme so that I can start designing with the new design system.

Notes
As we start enabling our DGC partners they need a design kit that has the components that reflect the 16px type size for marketing and editorial experiences.

include all states of components
keep naming convention that is already established by design kit guild
We will start with the white theme kit

### Acceptance criteria
- [ ] Design Kit has been updated with gray 10 theme tokens
- [ ] Has been tested by other designers 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1243_

**Comment by RobertaJHahn** [comment]
dup of (#4024)  Closing
