### ISSUE TITLE
Pattern: CTA section Services template changes Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2812]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `CTA section`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (#2796 )
- [Storybook link](TBD)

 #### Tasks
Ensure the `CTA section` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed

**Comment by ltitle** [comment]
@RobertaJHahn @kennylam The design QA is now complete. Two issues were opened:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/3016
https://github.com/carbon-design-system/ibm-dotcom-library/issues/3017
