### ISSUE TITLE
Pattern: Content group - horizontal visual design & design spec Services template changes provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2815]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Services template.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
- **Scheduled delivery date:  June 22**
- Visual Designs & Design Specs Box folder
 - Links to the visual designs and design specs will be updated once received and reviewed by the Reboot designers.

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [x] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
@RobertaJHahn PDF and sketch files posted here:

**Content group horizontal** visual specs: https://ibm.ent.box.com/folder/112271053028
**Content item horizontal** visual specs (referred to by content group horizontal): https://ibm.ent.box.com/folder/112262788897

**Comment by RobertaJHahn** [comment]
6/22/2020:  Designs reviewed by Lila with engineers for sizing.
