### ISSUE TITLE
Pattern: Callout - with data Services template pattern Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2824]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Callout - with data`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (#2823 )
- [Storybook link](https://ibmdotcom-react-experimental.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2873/index.html?path=/story/patterns-blocks-calloutdata--default)

 #### Tasks
Ensure the `Callout - with data` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [x] Pattern is reviewed by designer and design defects are identified
- [x] New issues are opened to log individual defects
- [x] Screenshots of as-is and to-be design should be added to the issue when needed

**Comment by RaphaelAmadeu** [comment]
This pattern is ready for Design QA,
Thank you!
@RobertaJHahn @ltitle

**Comment by ltitle** [comment]
@RobertaJHahn Design QA for this pattern is now complete. The following issue was opened: #2976
