### ISSUE TITLE
Learn Page :- Linklist icon and spacing issue.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2826]
Issue Description:- On 'Learn' page linklist icons are not aligned properly and there is no spacing between links.

## Steps to reproduce the issue

1. Enter url in browser.
2. Click on 'Learn Page'.
3. Scroll to 'Link List ' section.

OS:- Win 10, Mac, iOS 12, 13  Android 8,9
Browsers:- Chrome, Safari, FF, Edge, UC Browser.

URL:- https://ibmdotcom-nextjs-staging.mybluemix.net/learn.html

![Linklist on learn page.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/1177294f-55c2-4f6b-aa8f-4c2e31002f8a)

**Comment by RaphaelAmadeu** [comment]
![Screen Shot 2020-07-21 at 15.51.56.png](https://images.zenhubusercontent.com/5af9cd024b5806bc2bd31a6f/bc0ffafa-308b-4f6e-a7d2-13ed4cc919aa)

After checking the provided link, it's looking fine, can we close out this issue?

**Comment by RaphaelAmadeu** [comment]
@chetankan could you please give us an update on this?

**Comment by chetankan** [comment]
@RaphaelAmadeu :- Verified and it is working fine. We can close this one.
