### ISSUE TITLE
Pattern: Logo grid: Grid

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/ibm-dotcom-library#2828]
## Logo grid: Grid

> Describe in detail the issue you're having.

Current version is center aligned and off the grid. It should follow the grid from design guide.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Logo grid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Story book(top image), Required design (bottom image)
Story book's grid is not following the design guide desktop - mobile.

![image](https://user-images.githubusercontent.com/67110948/85040422-ca721780-b156-11ea-81bd-92558698a084.png)

> What browser are you working in?

Chrome

> What version of the IBM.com Library are you using?

IBM.com Reboot

## Steps to reproduce the issue
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-logogrid--default

**Comment by RobertaJHahn** [comment]
This is a dup of issue (#2604)  Closing.
