### ISSUE TITLE
Pattern: Logo grid: Carbon theme

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/ibm-dotcom-library#2829]
## Logo grid: Carbon theme

> Describe in detail the issue you're having.

Storybook's carbon theme's g10,g90 have different background color between logo cards. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Logo grid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Story book `carbon theme` shows color error for g10 and g90 like image below. 
It needs to remove different color background between logo cards. 

![image](https://user-images.githubusercontent.com/67110948/85041483-fa6dea80-b157-11ea-9e9b-7c9ee727ee38.png)

![image](https://user-images.githubusercontent.com/67110948/85041602-2f7a3d00-b158-11ea-96a0-543ebab826a0.png)

> What browser are you working in?

Chrome

> What version of the IBM.com Library are you using?

IBM.com Reboot

## Steps to reproduce the issue
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-logogrid--default

**Comment by RobertaJHahn** [comment]
Design decision:  Remove the Carbon Theme tab in Storybook for Logo Grid.  Strategic design decision about the theming will be made.  Epic has been created for this work.
