### ISSUE TITLE
1:1 Aspect Ratio Video Player for George Hammer 

### ISSUE THREAD

**Issue by quincymass** [carbon-design-system/ibm-dotcom-library#2834]
### The problem
_{{  The standard for video production has evolved and produced a new format that enables video to better integrate with social solutions and new web standards.  In addition to existing standards, IBM is now creating video contend in 1:1 aspect ratio (square format) but the existing player is unable to present the content in the new dimensions.  It is critical to IBM image that the player is able to display/play 1:1 video as it does all other formats.  Submitted by Jerry Ringuette on behalf of Cory Calhoun/George Hammer with Q3 delivery requested.)}}_

### The solution
_{{IBM MediaCenter is able to transcode the video in the proper format, but the Carbon player will need to be updated to recognize the new aspect ratio.}}_

### Additional information
 _{{Here is a link to a page that demonstrates the new format and how the Northstar player reacts: https://pages.github.ibm.com/mediacenter/docs/aspect-ratio/1x1/}}_
 - Engineering to review the technical work to be done.  Determine whether func spec changes are required.  Tag @photodow and @RobertaJHahn if func spec changes are needed.
 - Eng will reach out to Jerry and Felipe to get sample test videos

**Comment by quincymass** [comment]
Submitted - by Jerry Ringuette - jerryr@us.ibm.com on behalf of Cory Calhoun Cory.Calhoun@ibm.com

**Comment by tweenn** [comment]
If I may add a helping hand, here's a little code example on how to get a video information on kaltura's player api, with mediacenter's public credentials/information and calculate the aspect-ratio without embedding the video.
```js

const PID = '1773841'; // Mediacenter Kaltura's Production Partner ID
const uiConfID = '27941801' // Northstar Video Player ID
const scriptSRC = `https://cdnapisec.kaltura.com/p/${PID}/sp/${PID}00/embedIframeJs/uiconf_id/${uiConfID}/partner_id/${PID}`;

let kAPI = {};

/**
 * @comment There is not much error handling on getting
 * kaltura's player api script as this is not the focus
 * of the example, so don't mind the resolve(false) and
 * no rejection statement
 */
const getMediacentersKalturaAPI = async () => {
	const getScript = await new Promise((resolve, reject) => {
		let scriptObject = document.createElement('script');
		const scriptParentNode = document.getElementsByTagName('script')[0];

		scriptObject.async = 1;

		scriptObject.onload = scriptObject.onreadystatechange = function( _, isAbort ) {
			if(isAbort || !scriptObject.readyState || /loaded|complete/.test(scriptObject.readyState) ) {
				scriptObject.onload = scriptObject.onreadystatechange = null;
				scriptObject = undefined;

				if(!isAbort) {
					resolve(true);
				} else {
					resolve(false);
				}
			} else {
				resolve(false);
			}
		};

		scriptObject.src = scriptSRC;
		scriptParentNode.parentNode.insertBefore(scriptObject, scriptParentNode);
	});

	if (getScript) {
		kAPI = new kWidget.api({
			wid: `_${PID}`
		});
	};
};

const getMediacentersVideoInfo = async (videoID) => {
	return await new Promise((resolve, reject) => {
		kAPI.doRequest({
			service: 'media',
			action: 'get',
			entryId: videoID
		},
		function(answer) {
			resolve(answer);
		});
	});
};

const getVideoAspectRatio = (width, height) => {
	/**
	 * List retrieved from https://en.wikipedia.org/wiki/Aspect_ratio_(image)
	 * in "Previous and currently used aspect ratios" tab
	 */
	const availableRatios = {
		1: '1x1',
		1.19: '19x16',
		1.25: '5x4',
		1.33: '4x3',
		1.37: '11x8',
		1.43: 'imax',
		1.5: '3x2',
		1.55: '14x9',
		1.6: '16x10',
		1.66: '5x3',
		1.75: '7x4',
		1.77: '16x9',
		1.85: '37x20',
		2: '18.5x9',
		2.16: '~28x13',
		2.2: '11x5',
		2.35: '~47x20',
		2.39: '~43x18',
		3.55: '32x9',
		3.6: '18x5'
	};

	let videoAspectRatio = (width / height).toString().split('.');
	if (videoAspectRatio[1]) {
		videoAspectRatio[1] = videoAspectRatio[1].substring(0, 2);
	}
	videoAspectRatio = videoAspectRatio.join('.');

	return availableRatios[videoAspectRatio] || 'undefined-aspect-ratio';
};

(async () => {
	await getMediacentersKalturaAPI();
	const videoParams = await getMediacentersVideoInfo('0_ibuqxqbe');

	/**
	 * @comment Kaltura's api will return the following:
	 * on Success:
	 * 		- The searched video parameters
	 * on Anything Else
	 * 		- The request/xhr result
	 * 		which will always have aa answer objectType
	 * So, if there is no objectType, it means success!
	 */
	if (videoParams.objectType !== undefined) {
		const aspectRatio = getVideoAspectRatio(videoParams.width, videoParams.height);
		console.log(aspectRatio);
	};
})();
```

**Comment by tweenn** [comment]
I was talking about the above example-code with @caiobozato - and remembered that it wasn't taking into account the fact that width and height object params are exclusive to video and image types and since Mediacenter support audio, requesting those params would result in untreated undefined values.

So I've just made an update to take that in account.

And the updated code will only return the aspect ratio in case of video as Mediacenter should only stream audio and video, not images.

Thanks Caio!

**Comment by RobertaJHahn** [comment]
@photodow Kenny has made this change.  Here is a copy of the message he posted to the dev issue (#3087).  I am assigning this epic to sprint 20-15 to make the func spec changes.  

_I don't believe functional specs are required other than updating the documentation to list the available aspect ratios: 16x9, 9x16, 2x1, 1x2, 4x3, 3x4, 1x1_

**Comment by photodow** [comment]
@RobertaJHahn done! Here are the updated functional specs.

https://ibm.ent.box.com/file/694007179724

**Comment by RobertaJHahn** [comment]
@photodow Thanks for the func spec updates.  

@Praveen-sr @chetankan I sent an email to the Product Owner asking him to provide an 1:1 aspect ratio video for testing.  I'll let you know once I receive it.
