### ISSUE TITLE
DDS Patterns page: Updates to content

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#2841]
The problem
It would be more helpful if the DDS patterns page used the name of the pattern in the heading or title.  

The solution
See Learn page by way of example...http://ibmdotcom-nextjs-staging.mybluemix.net/learn.html
Update the Table of Contents to reflect the name of the pattern too.  

<img width="288" alt="DDS Pattern - name of pattern" src="https://user-images.githubusercontent.com/23237857/85172075-51e68600-b23e-11ea-90a5-e6f87c2527b9.png">

**Comment by jeffchew** [comment]
@ljcarot I snuck this in today actually, just merged it: https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test/pull/24

**Comment by ljcarot** [comment]
Great! thank you!

**Comment by ljcarot** [comment]
@jeffchew Check out Feature card block large on Solutions page.  Doesn't look correct.  I thought it should be more like in the visual where the image is on left and copy on the right.
![image](https://user-images.githubusercontent.com/23237857/85209239-3fcf1b00-b304-11ea-93e8-615845aa1bb8.png)
