### ISSUE TITLE
Pattern: Link with icon inverse theming Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2869]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `link with icon`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (#2295 )
- [Storybook link](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2887/index.html?path=/story/components-link-with-icon--default)

 #### Tasks
Ensure the `Link with icon` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RaphaelAmadeu** [comment]
This update was done, and it's ready for Design QA

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2887/index.html?path=/story/components-link-with-icon--default

@oliviaflory @RobertaJHahn
