### ISSUE TITLE
Pattern: CTA Section & Leadspace Block :- CTA button is not stretched out as per specs on mobile devices. 

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2874]
Issue Description :- As per visual specs 'CTA Copy' button should be stretched out but on mobiles devices it is not. 
## Steps to reproduce the issue

1. Enter url in mobile browser.
2. Select 'CTA Section' or 'Leadspace Block'
3. Scroll down to 'CTA Copy' button.

OS:- iOS 12, 13  Android 8,9
Browsers:- Chrome, Safari, UC Browser.

URL :- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/patterns-blocks-leadspaceblock--default

![CTA button on leadspace block.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/2cfda7d7-1f5f-49f2-bced-4ac5e900d3b6)![CTA copy button visual specs.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/17ac6db5-3e71-4c00-996f-75d67a619aab)

**Comment by ljcarot** [comment]
Closing as this is duplicate with 2616
