### ISSUE TITLE
Learn & Solution Page :- TOC jump to menu is not sticky on Mobile

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2875]
Issue Description :-  In 'Learn & Solution' page on mobile device when user selects any title from 'TOC--> Jump to' section user is navigated to the selected title but 'jump to' section is getting disappeared.

Scope:  Assume that L0 exists for now.

## Steps to reproduce the issue

1. Enter url in mobile browser.
2. Click on 'Jump To' section.
3. Select a title from drop down.
4. After navigating to selected title check if 'jump to' section is displayed.

OS;- iOS 12, 13  Android 8,9
Browsers:- Safari, Chrome, UC Browser.

URL:- https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html

URL:- https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html

**Comment by RobertaJHahn** [comment]
@sethibm Seth will investigate and document the design decision for the spacing between the TOC and the Masthead.  The gap between TOC and MH is not defined.  Then we can assign to Dev.

**Comment by sethibm** [comment]
- Starter note here: @RobertaJHahn, the issue, at least from how it's described, is not spacing, rather that menu is not sticky I believe? Maybe I missed where this changed during QA review meeting.  However, please see below video about a potential padding / spacing issue. 

- On stickiness, please see attached export from visual spec, showing TOC should be sticky and remain attached below Masthead, when user either scrolls down, or clicks / taps any of the dropdown items in the TOC.  It currently disappears and this is an error.  It should be persistent and stick below masthead.

![tablet-mobile_scroll-behavior](https://user-images.githubusercontent.com/58601040/85769167-bd6d9f00-b6e7-11ea-909b-397561ac812c.jpg)

- @wonilsuhibm @larahanlon2 One question to clarify here. This visual spec shows medium breakpoint with 16px left and right padding on TOC, in above image.  It goes to 100% width for small breakpoint.  Is this a bug that needs to be fixed, or was a decision made to make it 100% width on both small and medium breakpoint? 

- Another potential issue to log:  For max, xlg, lg breakpoints, visual spec says TOC should maintain 32px top padding when user scrolls down.  It does not do so in this example link, rather touches the masthead with 0px padding.  See this video:

[TOC-32px-padding.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/4832986/TOC-32px-padding.zip)

Viz spec guidance:
<img width="1064" alt="32pxtoppadding" src="https://user-images.githubusercontent.com/58601040/85771796-41c12180-b6ea-11ea-9051-3a19055dbf7a.png">

Is this another bug that should be logged, or same as one noted in comment above?

**Comment by larahanlon2** [comment]
@sethibm there is another [issue open](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2557) re: design from Shixie. Ari has been working on that and I have been trying to support. Maybe check to make sure there is no crossover with this issue.

RE: sticky behavior below the masthead, I recall there was a conversation about this on one of the QA meetings last week. I do not know what the decision was in the end – whether to fix it or deprioritize for now. Maybe Wonil or @RobertaJHahn can chime in here?

**Comment by sethibm** [comment]
Thanks @larahanlon2.  I see that the 16px issue on left and right side for md breakpoint is covered in Shixie's issue, so I removed it here.

The remaining question is whether a new bug should be logged, around whether we want to match visual specs that require persistence of 32px top padding for TOC when user scrolls down.

**Comment by sethibm** [comment]
@RobertaJHahn This bug is clarified in comments and can be addressed by a developer.  I'm not sure whether to leave it here or move to another column, so I'm leaving it here for now.
