### ISSUE TITLE
September Release Plan (v1.11.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2877]
# Timeline

- **September 11, 2020**: Code freeze
- **September  14-21, 2020**: Release Candidate(s) and testing
- **September 23, 2020**: Full Release

## Global

* **Upgrade Carbon to v10.19.0** (#3867) ([be42e2f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/be42e2f)), closes [#3867](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3867) [#3866](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3866)

### Breaking Change

The environment variable `SEARCH_TYPEAHEAD_HOST` has been renamed to `SEARCH_TYPEAHEAD_API`.

### Fixes

* **Card**: moved scss to the styles package (#3688) ([b978d18](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b978d18)), closes [#3688](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3688)
* **LocaleModal**: merge styles (#3612) ([95b00a1](https://github.com/carbon-design-system/ibm-dotcom-library/commit/95b00a1)), closes [#3612](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3612) [#3482](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3482) [#3406](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3406)
* **styles**: dedupe Carbon grid in the bundle (#3811) ([4119a43](https://github.com/carbon-design-system/ibm-dotcom-library/commit/4119a43)), closes [#3811](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3811) [#3809](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3809)

### Features

* **card-with-pictogram**: adding new card variation (#3654) ([3bdc14e](https://github.com/carbon-design-system/ibm-dotcom-library/commit/3bdc14e)), closes [#3654](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3654)
* **Footer**: add micro variation (#3645) ([14acb43](https://github.com/carbon-design-system/ibm-dotcom-library/commit/14acb43)), closes [#3428](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3428) 
 [#3645](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3645) [#3431](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3431)
* **search**: add redirect and typeahead hooks (#3918) ([84c0481](https://github.com/carbon-design-system/ibm-dotcom-library/commit/84c0481)), closes [#3918](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3918) [#3766](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3766)

### Fixes 

* **calloutQuote**: remove footer styles (#3891) ([9a8cba7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/9a8cba7)), closes [#3891](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3891) [#3711](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3711)
* **CardGroup**: passing pictogram prop to card from CardGroup (#3689) ([fa2b2ef](https://github.com/carbon-design-system/ibm-dotcom-library/commit/fa2b2ef)), closes [#3689](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3689) [#3654](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3654)
* **CardLink**: remove specific styles (#3835) ([a6a2580](https://github.com/carbon-design-system/ibm-dotcom-library/commit/a6a2580)), closes [#3835](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3835) [#3473](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3473)
* **ContentGroupHorizontal**: margin size (#3593) ([e6988f2](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e6988f2)), closes [#3593](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3593) [#3262](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3262)
* **Footer**: micro footer mobile layout styles (#3844) ([60a35ff](https://github.com/carbon-design-system/ibm-dotcom-library/commit/60a35ff)), closes [#3844](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3844) [#3771](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3771)
* **Footer**: update micro footer styles (#3825) ([77d4667](https://github.com/carbon-design-system/ibm-dotcom-library/commit/77d4667)), closes [#3825](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3825) [#3759](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3759) [#3760](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3760)
* **HorizontalRule**: change style prop name to type (#3892) ([3317f57](https://github.com/carbon-design-system/ibm-dotcom-library/commit/3317f57)), closes [#3892](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3892)
* **leadspace**: fixes codesandbox leadspace example (#3581) ([59414e1](https://github.com/carbon-design-system/ibm-dotcom-library/commit/59414e1)), closes [#3581](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3581)
* **LinkList**: update styles in aside element (#3845) ([d518bf9](https://github.com/carbon-design-system/ibm-dotcom-library/commit/d518bf9)), closes [#3845](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3845) [#3454](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3454)
* **Masthead**: indicate the active navigation item in Masthead navigation links (#3890) ([42b1599](https://github.com/carbon-design-system/ibm-dotcom-library/commit/42b1599)), closes [#3890](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3890) [#3826](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3826)
* **Masthead**: set selected menu item font weight to semibold (#3909) ([cc74a21](https://github.com/carbon-design-system/ibm-dotcom-library/commit/cc74a21)), closes [#3909](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3909) [#3907](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3907)
* **masthead**: remove hide L0 logic (#3960) ([fe2ae3f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/fe2ae3f)), closes [#3960](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3960) [#3958](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3958)
* **MastheadLeftNav**: when user goes through menu levels, set scrollTop to 0 (#3921) ([0ecc2a5](https://github.com/carbon-design-system/ibm-dotcom-library/commit/0ecc2a5)), closes [#3921](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3921) [#3730](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3730)
* **MegaMenu**: explicity set focus to HeaderMenu L0 item when clicked (#3751) ([626d40f](https://github.com/carbon-design-system/ibm-dotcom-library/commit/626d40f)), closes [#3751](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3751) [#3617](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3617) [#3731](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3731)
* **Megamenu**: update mobile styles (#3858) ([3c9e01c](https://github.com/carbon-design-system/ibm-dotcom-library/commit/3c9e01c)), closes [#3858](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3858) [#3504](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3504) [#3510](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3510) [#3516](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3516)
* **TOC**: font-size on ios landscape mode (#3614) ([4893525](https://github.com/carbon-design-system/ibm-dotcom-library/commit/4893525)), closes [#3614](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3614)
* **ToC**: increasing mobile component clickable area (#3853) ([80a4543](https://github.com/carbon-design-system/ibm-dotcom-library/commit/80a4543)), closes [#3853](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3853) [#3726](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3726)

### Breaking Change

The `<HorizontalRule />` has a change in prop name, namely the `style` prop is now called `type`.

## Web Components

The Web Components package is packed with a ton of new components, in our efforts to bring feature parity with the React package! This will be the continuing wave of available web components in the IBM.com Library for the next series of releases.

### Features

* **Card**: create web component (#3887) ([574d764](https://github.com/carbon-design-system/ibm-dotcom-library/commit/574d764)), closes [#3887](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3887) [#3855](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3855) [#3556](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3556)
* **Card**: supports onClick (#3812) ([9245135](https://github.com/carbon-design-system/ibm-dotcom-library/commit/9245135)), closes [#3812](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3812) [#3756](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3756)
* **Card**: fix icon placement option and styles (#3919) ([cba5762](https://github.com/carbon-design-system/ibm-dotcom-library/commit/cba5762)), closes [#3919](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3919) [#3917](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3917)
* **content-block**: introduction (#3870) ([1484022](https://github.com/carbon-design-system/ibm-dotcom-library/commit/1484022)), closes [#3870](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3870) [#3640](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3640) [#3734](https://github.com/
* **cta**: introduce card CTA (#3855) ([e3a53c6](https://github.com/carbon-design-system/ibm-dotcom-library/commit/e3a53c6)), closes [#3855](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3855) [#3556](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3556)
* **FeatureCard**: new web component (#3725) ([a1419a7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/a1419a7)), closes [#3725](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3725) [#3554](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3554)
* **FeatureCardBlockLarge**: web component version (#3829) ([9844f92](https://github.com/carbon-design-system/ibm-dotcom-library/commit/9844f92)), closes [#3829](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3829) [#3558](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3558)
* **horizontal-rule**: hr web component (#3856) ([feab658](https://github.com/carbon-design-system/ibm-dotcom-library/commit/feab658)), closes [#3856](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3856) [#3536](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3536)
* **Icon**: icon web component (#3830) ([dd5dae7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/dd5dae7)), closes [#3830](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3830) [#3538](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3538)
* **image**: created web component image component (#3750) ([b6ffdd4](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b6ffdd4)), closes [#3750](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3750)
* **lightbox-media-viewer**: introduce image viewer (#3869) ([8aa9831](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8aa9831)), closes [#3869](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3869) [#3550](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3550)
* **LinkList**: Component created (#3564) ([6140ae7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/6140ae7)), closes [#3564](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3564) [#3372](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3372)
* **link-list**: test added (#3924) ([19557c7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/19557c7)), closes [#3924](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3924) [#3372](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3372)
* **masthead**: extract out the search feature (#3757) ([8bcdd8a](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8bcdd8a)), closes [#3757](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3757) [#3397](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3397)
* **masthead**: support for dynamic language switch (#3915) ([5cd27da](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5cd27da)), closes [#3915](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3915) [#3899](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3899)
* **package.json**: add update snapshot npm script to web-components package.json (#3621) ([1a9d286](https://github.com/carbon-design-system/ibm-dotcom-library/commit/1a9d286)), closes [#3621](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3621)

### Fixes

* **card-footer**: fix duplicate content (#3916) ([17d9952](https://github.com/carbon-design-system/ibm-dotcom-library/commit/17d9952)), closes [#3916](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3916)
* **card-link**: witdth in web-component story now matches react (#3591) ([13fb347](https://github.com/carbon-design-system/ibm-dotcom-library/commit/13fb347)), closes [#3591](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3591) [#3407](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3407)
* **dotcom-shell**: fix style imports (#3810) ([8304c76](https://github.com/carbon-design-system/ibm-dotcom-library/commit/8304c76)), closes [#3810](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3810)
* **footer-nav-group**: fix missing rotate feature of chevron (#3878) ([62ada29](https://github.com/carbon-design-system/ibm-dotcom-library/commit/62ada29)), closes [#3878](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3878) [#3530](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3530)
* **left-nav**: fix left nav not being able to open (#3664) ([5779b83](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5779b83)), closes [#3664](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3664)
* **locale-search**: fix clear button (#3715) ([06f8cb7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/06f8cb7)), closes [#3715](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3715) [#3714](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3714)
* **locale-search**: reset query on page navigation (#3768) ([fdbd16a](https://github.com/carbon-design-system/ibm-dotcom-library/commit/fdbd16a)), closes [#3768](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3768) [#3769](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3769)
* **LocaleModal**: remove header focus (#3888) ([b86894c](https://github.com/carbon-design-system/ibm-dotcom-library/commit/b86894c)), closes [#3888](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3888) [#3527](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3527)
* **masthead-leftnav**: increasing overlay z-index (#3871) ([3e56272](https://github.com/carbon-design-system/ibm-dotcom-library/commit/3e56272)), closes [#3871](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3871) [#3695](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3695)
* **masthead-menu-button**: fix toggle event (#3840) ([916bbc7](https://github.com/carbon-design-system/ibm-dotcom-library/commit/916bbc7)), closes [#3840](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3840) [#3834](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3834)
* **masthead-search**: fire custom event (#3900) ([1842cd9](https://github.com/carbon-design-system/ibm-dotcom-library/commit/1842cd9)), closes [#3900](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3900) [#3894](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3894)
* **masthead-search**: performance improvements (#3710) ([5674d18](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5674d18)), closes [#3710](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3710) [#3707](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3707)
* **Masthead**: hide nav items from screen readers when not displayed (#3542) ([1387a46](https://github.com/carbon-design-system/ibm-dotcom-library/commit/1387a46)), closes [#3542](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3542) [#3159](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3159)
* **Masthead**: keep focus in sub menus (#3723) ([af1ce57](https://github.com/carbon-design-system/ibm-dotcom-library/commit/af1ce57)), closes [#3723](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3723) [#3663](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3663)

**Comment by andysherman2121** [comment]
@RobertaJHahn The release v1.11.0 has been pushed out
