### ISSUE TITLE
Service: Create the Locale service functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2889]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `DDO` functional specs 

> so that I can:
so that I can properly code the `Locale` service

#### Additional information

  - The Locale service has been developed.  This story is to document the Locale service that exists today as the baseline for future changes.

#### Acceptance criteria
 - [ ] Documented `Locale` functional specifications

**Comment by RobertaJHahn** [comment]
@photodow Did you finish these functional specs?  Should I move this issue to sprint 20-19?

**Comment by photodow** [comment]
@RobertaJHahn here is the functional specs

https://ibm.box.com/s/skhwbr2updkqj4cljkqy9zern6dbhu0o
