### ISSUE TITLE
Service: Create the Translation service functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2891]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Translation` functional specs 

> so that I can:
so that I can properly code the `Translation` service

#### Additional information

  - The Translation service has been developed.  This story is to document the Translation service that exists today as the baseline for future changes.

#### Acceptance criteria
 - [ ] Documented `Translation` service functional specifications

**Comment by photodow** [comment]
Here is the link to the functional specs for this.

https://ibm.ent.box.com/file/655018269775
