### ISSUE TITLE
Web Components education

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2901]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
become educated regarding the Web Components technology

> so that I can:
develop a new skill and create / change the ibm.com Library Web Components

#### Additional information

 - https://www.youtube.com/watch?v=9FB0GSOAESo
 - https://developers.google.com/web/fundamentals/web-components/shadowdom
 - https://developers.google.com/web/fundamentals/web-components/customelements
 - https://channel9.msdn.com/posts/Anders-Hejlsberg-Introducing-TypeScript
 - https://www.sitepen.com/typescript-cheat-sheet
- (Once all above are finished) https://github.com/carbon-design-system/ibm-dotcom-library/blob/6372912/packages/web-components/docs/coding-conventions.md

#### Acceptance criteria
 - [ ] Required courses listed above are finished

**Comment by RobertaJHahn** [comment]
@jeffchew @asudoh Here is the developer training issue scheduled in the next sprint.  If you could add links and any other instructions for the developers, that would be great.

**Comment by asudoh** [comment]
Thanks @RobertaJHahn! Here are some learning materials:

https://www.youtube.com/watch?v=9FB0GSOAESo
https://developers.google.com/web/fundamentals/web-components/shadowdom
https://developers.google.com/web/fundamentals/web-components/customelements
https://channel9.msdn.com/posts/Anders-Hejlsberg-Introducing-TypeScript
https://www.sitepen.com/typescript-cheat-sheet

**Comment by jeffchew** [comment]
@annawen1 @kennylam @RaphaelAmadeu @ariellalgilmore @andysherman2121 fyi, you can adjust playback speed at least for Youtube in case you want to speed up the video.

**Comment by RaphaelAmadeu** [comment]
@jeffchew You can do it on the typescript one too
