### ISSUE TITLE
field_paragraph is missing in featuredtestimonial

### ISSUE THREAD

**Issue by ararames** [carbon-design-system/ibm-dotcom-library#2908]
when we try to ingest `featured_testimonial` we observed `field_paragraph` is missing in the pattern. 
Here is a screen shot below for reference:

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/22956510/85796264-a343b900-b707-11ea-8c1d-16523545fb6e.png">

**Comment by annawen1** [comment]
Hi @ararames can you provide more details? What version of @carbon/ibmdotcom-react are you using? Looking at the screenshot, looks like you are trying to inject the [CalloutQuote](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-calloutquote--default) pattern?

The CalloutQuote takes in a `quote` prop:
<img width="940" alt="Screen Shot 2020-06-26 at 9 40 43 AM" src="https://user-images.githubusercontent.com/54281166/85863560-51477580-b791-11ea-8888-7bec97ff8419.png">

**Comment by ararames** [comment]
> Hi @ararames can you provide more details? What version of @carbon/ibmdotcom-react are you using? Looking at the screenshot, looks like you are trying to inject the [CalloutQuote](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-calloutquote--default) pattern?
> 
> The CalloutQuote takes in a `quote` prop:
> <img alt="Screen Shot 2020-06-26 at 9 40 43 AM" width="940" src="https://user-images.githubusercontent.com/54281166/85863560-51477580-b791-11ea-8888-7bec97ff8419.png">

Hi Anna,
I am trying with 1.8 and even I also tried checking with 1.7. the `field_paragraph` is missing in both the versions.
yes I am trying to inject CalloutQuote pattern.

**Comment by annawen1** [comment]
@ararames did you make any progress on this issue? The last time we spoke with Ke, you guys were going to look into your injestion process

**Comment by annawen1** [comment]
as per conversation with @ararames, this ticket can be closed
