### ISSUE TITLE
Solutions page: Logo grid - on keyboard navigation, focus stays twice in each card.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2911]
## Detailed description

Issue :- 
1. On keyboard navigation, Focus stays twice in each card.
2. Visual focus is also not there while navigating through images

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/61287628-d356-4ed2-bd5e-8b73802cd5ef)

**Comment by caiobozato** [comment]
@Praveen-sr I've navigated through the page and wasn't table to reproduce the issue:

![logo-grid.gif](https://images.zenhubusercontent.com/5eed1fec732800bd837801c2/defcb361-e820-4a02-85ea-d44ca6c1c7c0)

Could you please clarify how to reproduce the issue?
