### ISSUE TITLE
[LinkWithIcon]: allow left/right icon placement

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-dotcom-library#2918]
## Detailed description

> Describe in detail the issue you're having.

Changes from #2852 now cause link icons to display in the wrong direction, since currently the `vertical` orientation always displays icons on the left. This causes issues when a vertical `LinkList` is used in another component with a requirement of icons being on the right.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Feature request to have option of displaying links left or right in `LinkWithIcon`.

> Is this issue related to a specific component?

`LinkWithIcon`

> What browser are you working in?

> What version of the IBM.com Library are you using?

`v1.8.0`

## Steps to reproduce the issue

See [example](http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-contentitemhorizontal--default)

## Additional information

![image](https://user-images.githubusercontent.com/909118/85871409-5c53d300-b79c-11ea-8ca3-1c6fd8f37175.png)

**Comment by annawen1** [comment]
@kennylam is already working on enhancing the LinkWithIcon component here: https://github.com/carbon-design-system/ibm-dotcom-library/pull/2980
