### ISSUE TITLE
Pattern: Left Nav tool chest pattern (search result page)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#292]
_Wonil-Suh1 created the following on Jul 22:_  

 # As a user of highly interactive page such as the search result page, I need a way to control / manipulate the content on the page.

This is to design / provide design support to the search result page being designed by the Product Discovery team.
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1275_

**Comment by RobertaJHahn** [comment]
Can be closed.  There is a component already available.
