### ISSUE TITLE
Static HTML page: Products static page visual design & design spec provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2944]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Services template.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
- **Scheduled delivery date:  July 7**
- The design review meeting with DDS will be scheduled during the week of July 6
- Design links will be posted to this issue following the meeting.
 

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by shixiedesign** [comment]
Hi team, [this link is continuously updated] here you can see the latest designs and spec document.
https://share.goabstract.com/59213ea1-fbe8-447f-a078-7fc357c2535d
 If you are a new user of Abstract, make an account with IBM email, and click request access, then ping me on Slack! I can approve and access is instantly granted. Thanks!
