### ISSUE TITLE
Left panel container design specs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#295]
_Wonil-Suh1 created the following on Jul 25:_  

 ### User story
As an adopter, I need a standardized way that will allow me to add left side panel that can house my interface elements such as filters, navigational elements, TOC, etc.

### Notes
This is to create left panel container specs that cover items such as:
- Layout options (grids & position)
- Paddings and margins
- Margins= soecs for internal groupings
- Examples of how different content pieces can be housed

The initial adopters include Product Discovery squad's search result page, Discover pages from Web Simplification project, and potentially My IBM pages.

### Acceptance criteria
- [x] Design specs are available
- [x] Design examples are available

### Next steps
Approval and guidelines will be handled through follow up issues. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1302_

**Comment by jeffchew** [comment]
_On Aug 27, spbokma commented:_
Concepts sketched out during a meeting between Wonil, Jeff and Scott on 8/26
![screen shot 2019-08-27 at 12 49 58 pm](https://media.github.ibm.com/user/2785/files/d9879080-c8ca-11e9-866a-cfd71d0f179a)

It continue discussing naming, layout, structure, usage, governance and what it looks like across the different grid/browser sizes

**Comment by RobertaJHahn** [comment]
[design specs](https://ibm.ent.box.com/folder/89972208850)

[Sketch file](https://ibm.ent.box.com/file/539512317899)

**Comment by wonilsuhibm** [comment]
![component--left-panel-container--max](https://user-images.githubusercontent.com/30183447/66766938-4d7ef780-ee7d-11e9-93e9-cdfa78a36b6d.png)

![component--left-panel-container--max--scroll-behavior](https://user-images.githubusercontent.com/30183447/66766953-52dc4200-ee7d-11e9-812a-3c07062bbb47.png)

![component--left-panel-container--xlg](https://user-images.githubusercontent.com/30183447/66766964-5c65aa00-ee7d-11e9-8954-d2e88c452349.png)

![component--left-panel-container--lg](https://user-images.githubusercontent.com/30183447/66766973-61c2f480-ee7d-11e9-8a28-4311ddbfaddc.png)

![component--left-panel-container--md](https://user-images.githubusercontent.com/30183447/66766983-69829900-ee7d-11e9-8747-1521e9c59c03.png)

![component--left-panel-container--md--hover-state](https://user-images.githubusercontent.com/30183447/66766988-6edfe380-ee7d-11e9-9fed-dff2f43b8ac5.png)

![component--left-panel-container--md--click-state](https://user-images.githubusercontent.com/30183447/66766987-6edfe380-ee7d-11e9-8edc-840a2a70aa96.png)

![component--left-panel-container--md--scroll-behavior](https://user-images.githubusercontent.com/30183447/66766990-6edfe380-ee7d-11e9-9c5c-86d66cc881e7.png)

**Comment by RobertaJHahn** [comment]
Design / engineering review completed Oct 3.  Closing
