### ISSUE TITLE
Cleanup of Storybook stories for CTASection

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2953]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
see variations of the CTASection component in storybook

> so that I can:
quickly see what available variations there are for the CTASection component

#### Additional information

 - Storybook URL: http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-ctasection--default
 - Should break down the types into their own stories
 - Break down any knobs with JSON

#### Acceptance criteria
 - [ ] Multiple storybook variations for CTASection component
 - [ ] No knobs with JSON
 - [ ] Add actual prop names in knob description in parenthesis

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu I don't see a PR linked to this issue.  It is in the `Done` pipeline.  Can it be closed?
