### ISSUE TITLE
Pattern: Content Block Cards - It isn't able to find how to add video as link 

### ISSUE THREAD

**Issue by diegomarcuz** [carbon-design-system/ibm-dotcom-library#2985]
## Detailed description

> Describe in detail the issue you're having.

When I use Content Block Cards pattern and want to add a video as link, we weren't able to find how to add it. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

We are using a pattern called Content Block Cards, but I think the possible bug could be in the CardGroup component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would want to use a video in the content block cards pattern

> What browser are you working in?

Google Chrome

> What version of the IBM.com Library are you using?

1.8.0

## Steps to reproduce the issue

1. Step one

Go to: https://ibmdotcom-nextjs.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/30/services.html

2. Step two

See the tab called "Content Block Cards and Card Link" to see how the card link is working

PR related: [carbon-design-system/ibm-dotcom-library-nextjs-test](https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test/pull/30)

**Comment by annawen1** [comment]
Currently the ContentBlockCards pattern is using `<Card />` subcomponent that does not support video. We need to swap it out with the `<CTA />` component instead

**Comment by diegomarcuz** [comment]
> Currently the ContentBlockCards pattern is using `<Card />` subcomponent that does not support video. We need to swap it out with the `<CTA />` component instead

Thanks @annawen1
