### ISSUE TITLE
Carbon Theme: Logo Grid - On g10 & g90 theme, grid has two layout with different background colors.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2996]
## Detailed description

Issue :-  On g10 & g90 theme, grid has two layout with different background colors.

Note: As discussed on call -- **Need to disable (turn off) carbon theme for this pattern.**

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b16b0035-3107-4300-9763-e9174208f0f1)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3877fb84-8bd2-4da1-b3fd-03e2b16afb58)

**Comment by ariellalgilmore** [comment]
Closing issue: fixed already in this PR [#3023](https://github.com/carbon-design-system/ibm-dotcom-library/pull/3023)
