### ISSUE TITLE
Pattern: Content block - headlines visual design & design spec provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3006]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Services template.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
- **Scheduled delivery date:  July 3**
- Visual Designs & Design Specs Box folder
 - Links to the visual designs and design specs will be updated once received and reviewed by the Reboot designers.

#### Acceptance Criteria
 - [x] Visual designs and specs received from Reboot designers
- [x]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
@RobertaJHahn Design specs (sketch and PDF) are now posted here https://ibm.ent.box.com/folder/117051778931

**Comment by RobertaJHahn** [comment]
Designs reviewed with DDS engineers July 6, 2020
