### ISSUE TITLE
Pattern: Develop Content block - headlines based on the Reboot designs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3007]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create the `Content block - headlines`

> so that I can:
provide the ibm.com adopter developers patterns they can use to build ibm.com web pages

#### Additional information

- **This pattern will be available behind a feature flag.  Reboot will be doing user testing to decide on final design.**
- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic for the Design specs information**
- Design QA testing issue (#3008 )
- [Visual Designs & Design Specs Box folder](https://ibm.ent.box.com/folder/117051778931)

#### Engineering notes
- We can probably leverage the `ContentBlock` for the outer component, and also the `ContentItem` for the individual items. We should probably create as its own sub-component, but we probably don't need to export it for now.
- Use the `sameHeight` utility to make sure that the links match each other in heights
- Interesting horizontalrule logic, we should make sure that we can capture all of that correctly.

#### Acceptance criteria
- [x] Include README for the react pattern and corresponding styles, and how to enable via feature flag
- [x] Designs were provided by Reboot, include Lila as a Reviewer in the Pull Request
- [x] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [x] The Storybook link is added to the Design QA issue for their testing
- [x] Canary storybook should not show this story, it should only appear in the experimental storybook

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr @chetankan This is ready for testing https://github.com/carbon-design-system/ibm-dotcom-library/pull/3040.

[Deploy preview](https://ibmdotcom-react-experimental.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3040/index.html?path=/story/patterns-blocks-contentblockheadlines--default) link.
