### ISSUE TITLE
Pattern: Content block - headlines Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3008]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Content block - headlines`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- [Visual Designs & Design Specs Box folder](https://ibm.ent.box.com/folder/117051778931)
- Dev Issue (#3007 )
- [Storybook link](https://ibmdotcom-react-experimental.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3040/index.html?path=/story/patterns-blocks-contentblockheadlines--default)

 #### Tasks
Ensure the `Content block - headlines` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [x] Pattern is reviewed by designer and design defects are identified
- [x] New issues are opened to log individual defects
- [x] Screenshots of as-is and to-be design should be added to the issue when needed

**Comment by kennylam** [comment]
@RobertaJHahn this has been approved by @ltitle in #3040
