### ISSUE TITLE
Pattern: CTA section: Buttons

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#3016]
## CTA section: Buttons

> Describe in detail the issue you're having.

- Spacing between buttons is too small
- Buttons should only stack on Small breakpoint
- Buttons on Small breakpoint should be full width

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

CTA Section Pattern (default version)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**As seen in Storybook: Space between buttons is 16px**

![image](https://user-images.githubusercontent.com/57198117/86404576-df35cb80-bc7d-11ea-8d71-f29076595656.png)

**As expected from visual specs: Space between buttons is 32px**

![image](https://user-images.githubusercontent.com/57198117/86404596-ea88f700-bc7d-11ea-8780-331d70553a32.png)

------------------

**As seen in Storybook: Buttons are stacking at Small and Medium breakpoints**

![image](https://user-images.githubusercontent.com/57198117/86404783-3cca1800-bc7e-11ea-80f1-ab36b1bfc10e.png)

**As expected in visual specs: Buttons should only stack on Small breakpoint**

![image](https://user-images.githubusercontent.com/57198117/86404685-0c827980-bc7e-11ea-9454-0dbd2807026e.png)

![image](https://user-images.githubusercontent.com/57198117/86404699-12785a80-bc7e-11ea-8aa5-17f6dbf4ce87.png)

------------------

**As seen in Storybook: Buttons are not full width on Small breakpoint**

![image](https://user-images.githubusercontent.com/57198117/86404727-20c67680-bc7e-11ea-8b66-d3b5e41364b1.png)

**As expected in visual specs: Buttons should be full width on Small breakpoint**

![image](https://user-images.githubusercontent.com/57198117/86404702-13a98780-bc7e-11ea-94f1-88fea5732943.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2992/index.html?path=/story/patterns-sections-ctasection--default

**Comment by RobertaJHahn** [comment]
This is still not working on newer models for both iPhone and Android phones with width greater than 320px.  Reopening this issue.

**Comment by ariellalgilmore** [comment]
@RobertaJHahn can we close this issue again? Talked to the team and it is currently inline with the design specs

**Comment by RobertaJHahn** [comment]
@ariellalgilmore OK, closing.
