### ISSUE TITLE
Pattern(CalloutData): iframe - white space not displaying properly and text overlapping

### ISSUE THREAD

**Issue by caiobozato** [carbon-design-system/ibm-dotcom-library#3027]
## Detailed description

> Describe in detail the issue you're having.

When you add some white space on `Data` field and opens the component in the iframe, the space is displayed as urlencoded text `%20` also, a large text overlaps the pattern container.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Yes, `CalloutData` pattern

> What browser are you working in?

Google Chrome

## Steps to reproduce the issue

1. Step one
Go to https://ibmdotcom-react-experimental.mybluemix.net/
2. Step two
Select `CalloutData` pattern
3. Step three
Click on knobs, select `Data` and add a larger text with white spaces
4. Step four
Click to open into iframe

## Additional information

Outside the iframe:
<img width="1027" alt="callout-data-issue-1" src="https://user-images.githubusercontent.com/26546511/86616488-48725300-bf8c-11ea-95db-be1a0fb40b10.png">

Displaying the component into iframe:
<img width="1171" alt="callout-data-issue-2" src="https://user-images.githubusercontent.com/26546511/86616499-4c05da00-bf8c-11ea-8e0f-e8206228bd23.png">

**Comment by asudoh** [comment]
Filed: storybookjs/storybook#11641.
