### ISSUE TITLE
Website: cupcake overall design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#304]
_Wonil-Suh1 created the following on Aug 02:_  

  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1349_

**Comment by jeffchew** [comment]
_On Aug 08, chsanche commented:_
@hahnrob I think this task issue should be an Epic.

**Comment by JennySanchez** [comment]
@wonilsuhibm Is this task is still relevant? If it is, can you share what we are trying to solve and what are the expected outcomes to the task?
