### ISSUE TITLE
NextJS template and test application is slow for local development

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3043]
## Detailed description

> Describe in detail the issue you're having.

It takes a few minutes or more for the application to rebuild every time a change is made locally.

https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test
https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-template

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@annawen1 @guilhermelMoraes this looks like it is isolated to Gui's machine? Can we close?

**Comment by guilhermelMoraes** [comment]
@jeffchew yeah, I think @kennylam changes to the repo were enough to speed up things a little bit...The biggest problem stills being my hardware :(

**Comment by annawen1** [comment]
@guilhermelMoraes I think we'll close the ticket then. If you manage to get a new computer and still have issues then we can open another ticket.
