### ISSUE TITLE
Creation of the Canada Cookie Notice

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#305]
_Jeff-Chew created the following on Aug 02:_  

 #### User Story

> As a `[user role below]`:
Canadian user of IBM.com

> I need to:
see a notice regarding cookie usage when I first visit IBM.com

> so that I can:
be notified of cookie usage on IBM.com

#### Additional information
 - Northstar Services notes: https://ibm.ent.box.com/notes/492522538488
 - Canada cookie notice required by law/legal on Canada pages. 
When a user views a canada page, and we detect we haven't shown them the notice yet (only show once), we show a notice at the bottom of the page about using cookies. We keep track (as possible) and only show it to the user 1 time. Of course, if they disable or clear cookies/storage we end up showing them again. This is fine and agreed on. 
 - We probably need to include this for IBM.com library, depending on our adopters the inclusion of this may be necessary if they are switching over completely to IBM.com library and their pages will be viewed in Canada.
 - http://northstarexamples.mybluemix.net/v18/docs/classes/IBMCore.common.module.canadanotice.html
- Need to determine if new designs are necessary for this

#### Acceptance criteria
 - [ ] All related utilities should be in the utilities package
 - [ ] Behavior should be the same as northstar version
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1356_

**Comment by jeffchew** [comment]
_On Sep 09, hahnrob commented:_
This separate Canadian notice can be handled with the TrustArc solution managed by Juan Leon.  Here is a copy of the emails:

##### Aug 22, 2019 Juan Leon response:
Let's talk about this on Monday, and set the standard for it.
Regards,
  Juan.

##### Aug 22, 2019 Jeff Chew question:
Thanks Juan,
If the IBM.com library team provided an element in the footer with the data-autoid attribute, would Tealium be able to target and insert the link?


##### Aug 22, 2019 Juan Leon response:
Hi Jeff,
I think we should be able to handle cookie compliance with the TrustArc solution that we manage through Tealium. The integration will be needed to define a common definition for the footer and a placeholder to have the "Cookie preferences" menu item added by TrustArc.
Regards,
 Juan

##### Aug 22, 2019 Jeff Chew email to Juan Leon:

Hi Juan,
We are in the middle of taking inventory of Northstar components and have two separate implementatons for cookie compliance, one is specifically the canada cookie popup, and the other is the TrustE module. We were wondering if these implementations could be consolidated to one (perhaps TrustE) or do we still need to support both?
Cheers,
Jeff

**Comment by jeffchew** [comment]
_On Oct 08, hahnrob commented:_
Truste module injection was completed in Sprint 18.  [Issue 1359](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1359)  Closing this issue.

**Comment by jeffchew** [comment]
_On Oct 08, Jeff-Chew commented:_
@hahnrob @linda-carotenuto this story should actually remain open. The cookies preferences was completed so the Truste module is in place for GDPR, but we confirmed the Canada notice is not completed yet. We need to follow up with Juan Leon on timing.

**Comment by RobertaJHahn** [comment]
Oct 19, 2019 email from Juan Leon:  
Hi Jeff, 
@Hiren is reaching out to the page owners to get them to adopt our solution with TrustE (TrustArc). So, we will follow up on this, I have created a ticket to keep track of this activity:
[https://github.ibm.com/digital-behavior/support/issues/779](https://github.ibm.com/digital-behavior/support/issues/779)
 
Regards,
  Juan.

**Comment by RobertaJHahn** [comment]
@ljcarot @jeffchew I have added Juan's Oct 19 email to this issue.  Do you think that we can close this issue as Juan will manage the adoption with the business owners of the Canada website pages?
