### ISSUE TITLE
Footer – incorrect link color on hover state 

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#3068]
## Footer (Vanilla) – incorrect link color on hover state 
-->

## A few links in the footer on story book do not have the correct hover state. The hover state on the links should go from $text-02 to $text-01 but currently there is no change in color.

Incorrect hover state:
![Screen Shot 2020-07-08 at 10.55.10 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/77d5b669-5320-4c14-a4f0-f8e6cd4c07e6)

Correct hover state:
![Screen Shot 2020-07-08 at 10.55.20 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/fc86276b-4cf1-4fc2-a2eb-abcd79e9ee9a)

Links with issue:

- Redbooks
- Services
- Industries
- Case studies
- Demos
- Federal and state contracts
- Events
- Latest news
- Strategic partnerships
- Investor relations

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What browser are you working in?
Safari, Chrome

## Steps to reproduce the issue

1. View vanilla footer: https://ibmdotcom-vanilla.mybluemix.net/?path=/story/components-footer--default
2. Hover on links

**Comment by asudoh** [comment]
Designers; Looks that currently footer link explicitly uses the same color for `:visited` and `:visited:hover` state: https://github.com/carbon-design-system/ibm-dotcom-library/blob/v1.8.0/packages/styles/scss/components/footer/_footer.scss#L50-L53

For `:visited:hover` state, should we apply the same color for `:hover`?

**Comment by jacobottesen-dgc** [comment]
@asudoh Yes, lets do that. 

enabled and visited = $text-02
hover and visted-hover = $text-01

Thanks Akira!
