### ISSUE TITLE
Cleanup of Storybook stories for Layout

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3084]
#### User Story

> As a `[user role below]`:
IBM.com Library tester

> I need to:
see variations of the Layout component in storybook

> so that I can:
quickly see what available variations there are for the Layout component

#### Additional information

 - Should break down the types into their own stories
 - Break down any knobs with JSON

#### Acceptance criteria
 - [ ] Multiple storybook variations for Layout component
 - [ ] No knobs with JSON
 - [ ] Add actual prop names in knob description in parenthesis

**Comment by kennylam** [comment]
@RobertaJHahn We've decided to remove this from Storybook examples and instead follow-up with the design team to create documentation on its usage on the IBM.com website.
