### ISSUE TITLE
1:1 aspect ratio Video Player engineering investigation and development

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3087]
#### User Story

> As a `[user role below]`:
Business Analyst

> I need to:
understand the engineering implementation capabilities

> so that I can:
correctly document the functional specifications

#### Additional information

 - [Current video functional specifications](https://ibm.ent.box.com/folder/108837570522)
- Engineering will the technical work required to provide the 1:1 aspect ratio requested.  
- Engineering will determine whether func spec changes are required.  If required, Engineering will post a message tagging @photodow and @RobertaJHahn 
 - Eng will reach out to Jerry and Felipe to get sample test videos
- This analysis is required to move the development work forward.  Additional issues will be created based on the results of this review.

#### Acceptance criteria
 - [ ] The current functional specs have been reviewed
 - [ ] Technical implementation issues have been worked out with Felipe and Jerry
 - [ ] Message has been sent to James and Roberta if functional spec changes are needed.

**Comment by RobertaJHahn** [comment]
@kennylam Did you finish developing this component?  I am wondering whether two of the tasks listed in the Additional Information section are finished.  

- Engineering will determine whether func spec changes are required.  If required, Engineering will post a message tagging @photodow and @RobertaJHahn 
 - Eng will reach out to Jerry and Felipe to get sample test videos

Are func specs required?  The next step would be for Chetan or Praveen to perform the QA testing.  They will need test videos to do this.   Do you have test videos that you can attach to this issue or even guidance in how they might test.  

Thanks.

**Comment by kennylam** [comment]
@RobertaJHahn I don't believe functional specs are required other than updating the documentation to list the available aspect ratios: `16x9`, `9x16`, `2x1`, `1x2`, `4x3`, `3x4`, `1x1`
