### ISSUE TITLE
Mobile view of Leadspace (left) rendering issues

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3114]
## Detailed description

> Describe in detail the issue you're having.

The text and button is not blending well with the Leadspace image in mobile breakpoint:

![Screenshot_2020-07-10 Storybook](https://user-images.githubusercontent.com/1641214/87167285-ba9fac00-c29a-11ea-8b53-95d8b7191a47.png)

This was reported by an adopter:
https://cognitive-app.slack.com/archives/C2PLX8GQ6/p1594373993032700

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Leadspace

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I believe the idea is content below the image and not overlaid in it, @wonilsuhibm @larahanlon2 @oliviaflory can weigh in here.

> What version of the IBM.com Library are you using?

`v1.8.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by larahanlon2** [comment]
It looks like the lead space is missing the gradient overlay. Also, the button looks like a ghost button but it should be a primary button if there is only one CTA.
