### ISSUE TITLE
React:  MegaMenu MVP

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3120]
This MegaMenu MVP delivers the component selected by the Reboot squad from the research of several design options.  

#### Additional Information:
Target dates:  
- Olivia design delivery:  July 24
- Functional specs:  7/22 - 7/28
- Development:  7/27 - 8/07
- Visual QA:  8/10 - 8/12
- Prod QA:  8/12 - 8/14
- Code Freeze:  Aug 14
- Full Release:  Aug 26

[MegaMenu final designs](https://ibm.ent.box.com/folder/118692148518)
[Mega menu functional specs](https://ibm.ent.box.com/file/697324485102)
[Masthead L0 & Mobile Navigation functional specs](https://ibm.ent.box.com/file/697806634725)
[MegaMenu Nav Labels](https://ibm.ent.box.com/file/684998200276)

- Globalization scope:  **us-en only**

**Comment by photodow** [comment]
@kennylam @annawen1 functional specs are done. let me know if you have any questions.
