### ISSUE TITLE
Migrate patterns (sections/blocks) into components folder

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3132]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
see a simpler view of available components in Storybook

> so that I can:
find what I need for my application

#### Additional information

- After discussion with engineers and designers, we have agreed that all "coded things" are now components
- Work is similar to the work done in: https://github.com/carbon-design-system/ibm-dotcom-library/issues/2467
- Should also migrate the styles files to the components folder in the styles package
- [Staging URL to be used as a reference for the udpates](https://ibmdotcom-react-staging.mybluemix.net/?path=/story/overview-getting-started--page)

#### Acceptance criteria
 - [ ] sections/blocks moved to the components folder in React and Styles
 - [ ] Updates to READMEs in storybook
 - [ ] Refactored patterns using these components to ensure nothing is broken
 - [ ] Create breadcrumb imports in styles package (similar to sub-pattern style imports)
 - [ ] Add deprecation notice to the release issue
 - [ ] Updates to CSB examples

**Comment by RobertaJHahn** [comment]
Added this issue to the 7/17 Leadership meeting agenda.  Need to talk about the impact this change has on all of the documentation

**Comment by RobertaJHahn** [comment]
Places to change:
1)  Code - done [Staging URL[(https://ibmdotcom-react-staging.mybluemix.net/?path=/story/overview-getting-started--page)
2)  Cupcake website:  Update the Gatsby navigation (Jenny and Anna)
3)  Design folders:  ibm.com Library, IBM Digital Design and IBM Digital Design Squad  (Lara to own and potentially delegate the work)

Listed in priority order.

Time frame to begin the work is September.  Roberta to work with team members to define the work and create the issues for work assignments.
