### ISSUE TITLE
Web component: text - CTA Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3149]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library Masthead web component

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Overview and scope statement**
 - Dev issue (#3148) 
- Once development is finished the updated code is available in the [**Web Components Canary Environment**](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/overview-getting-started--page) for testing.
- The [**React canary environment**](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/overview-getting-started--page) component should be used for comparison

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Pattern is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by asudoh** [comment]
@Praveen-sr @chetankan Development is finished.  You can begin the testing using the Web components canary URL included in the Additional Information section of this issue. Thanks!

**Comment by RobertaJHahn** [comment]
Testing is not finished.  Moving to sprint 20-17.

Prod QA team is having an issue opening the CTA.  They get an error.  opened a bug (#3440)

**Comment by RobertaJHahn** [comment]
Accessibility testing is finished.

**Comment by RobertaJHahn** [comment]
@asudoh See my Aug 13 comment above.  There is a second error documented in issue #3440 that is blocking the testing.  Can you check on this?  Moving this issue to sprint 20-19.

cc:  @jeffchew

**Comment by Praveen-sr** [comment]
@RobertaJHahn We have one open issue [#4011](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/4011) , once this is resolved I'll re test.

**Comment by RobertaJHahn** [comment]
@Praveen-sr Copying the latest comment from Akira in issue (#3440) here.  

 #3855 contains the fix. QA team can try it out via the staging URL: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/3855/index.html

Looks like you can retest now.
