### ISSUE TITLE
Web Component: Lightbox media viewer

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3150]
# The problem

Need a Lightbox media viewer that we can created in a sophisticated way, and works with all JavaScript frameworks.

### The solution

Create a Lightbox media viewer with Shadow DOM and Custom Elements standards.

#### Additional Information
- Prod QA testing issue (#3152)

### Acceptance Criteria
- [ ] Creation of the `Lightbox media viewer` component in web-components
- [ ] Include README for adopters
- [ ] Feature parity with the React version
- [ ] Include story variations
- [ ] Include `data-autoid` attributes, same as the React Lightbox media viewer and include in README
- [ ] Post a message in the Prod QA testing issue tagging Praveen and Chetan when ready to test

**Comment by RobertaJHahn** [comment]
@asudoh Can Praveena and Chetan test this component?  Looks like the PR is merged, but I don't see a message posted in the Prod QA testing issue (#3152).  If work is finished, once you post the QA testing message you can move this issue to the Done pipeline.  Thanks.

**Comment by asudoh** [comment]
@RobertaJHahn My apologies, I meant to update #3152 but it slipped through the cracks. Updated.
