### ISSUE TITLE
Masthead:- Accessibility :- The options with in the   Hamburger menu 

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3157]
Issue Description :- The options are not available immediately after the  triggering element.
visually it is appearing after the triggering element but for the screen reader users it is available after the user profile button.

Recommended Fix:- screen reader should identify the options immediately after the triggering element.

URL : 
http://ibmdotcom-web-components-canary.mybluemix.net/?

Happening on :- Voiceover , iPhone

**Comment by RaphaelAmadeu** [comment]
This was fixed on this PR in `carbon-custom-components`
https://github.com/carbon-design-system/carbon-web-components/pull/460
Thanks!
