### ISSUE TITLE
Web Components education continued

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3208]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
become educated regarding the Web Components technology

> so that I can:
develop a new skill and create / change the ibm.com Library Web Components

#### Additional information

 - https://www.youtube.com/watch?v=9FB0GSOAESo
 - https://developers.google.com/web/fundamentals/web-components/shadowdom
 - https://developers.google.com/web/fundamentals/web-components/customelements
 - https://channel9.msdn.com/posts/Anders-Hejlsberg-Introducing-TypeScript
 - https://www.sitepen.com/typescript-cheat-sheet
- (Once all above are finished) https://github.com/carbon-design-system/ibm-dotcom-library/blob/6372912/packages/web-components/docs/coding-conventions.md

#### Acceptance criteria
 - [ ] Required courses listed above are finished

**Comment by jeffchew** [comment]
@RobertaJHahn I removed @greeshmareddyg and @Diego-Marcuz from this, we need a separate issue for the carbon digital badge training: https://carbondesignsystem.com/tutorial/react/overview, sorry if I wasn't clear.

**Comment by RobertaJHahn** [comment]
@jeffchew I have created issue (#3234) for Greeshma and Diego's training.
