### ISSUE TITLE
Pattern: feature with media: guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#321]
_Wonil-Suh1 created the following on Aug 06:_  

 ### User story
As a maker of IBM digital experience such as IBM.com, I need to be able to see the full feature pattern, understand how to use it when designing or developing, so that I can build a great IBM digital experience.

### Notes
This story may have to be broken into multiple stories such as author, design, and develop.

### Acceptance criteria
- [ ] Guidelines are written
- [ ] Guideline pages are designed
- [ ] Guideline pages are developed and ready to be released
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1382_

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available. The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
Closing this issue as all other issues related to this work have been closed.  See epic (#322)
