### ISSUE TITLE
Solutions page: CTA section is not aligned and text is overlapping

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3227]
#### **Jeff would like this fix included in the v1.9.0 hot fix**

@Praveen-sr commented on [Mon Jul 20 2020](https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test/issues/41)

## Detailed description

Issue :- CTA Section is not aligned properly and the text is overlapping 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/43ee44bb-c5ef-4175-b5e3-d10ca158a3f2)

**Comment by diegomarcuz** [comment]
This issue isn't related to the ibmdotcom library, I needed to add grid system for CTASection on the Solution Page so the PR is the one above.
