### ISSUE TITLE
Component :- Card Link :- CardLink is clickable even though it is disabled

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3229]
#### **Jeff would like this fix included in the v1.9.0 hot fix**

Issue Description:- 1) In cardlink component when user selects 'Disabled' in knobs section,whole card should be grayed out, but still disabled icon is displayed in blue color

2) Even though cardlink is disabled when user clicks on it , user is navigated to example.com page.  

## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'CardLink' component.
3. Select 'Disabled' option in knobs.
4. Check the disabled icon, and click on cardlink.

OS:- Win 10, Mac, iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, Edge, Firefox.

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-cardlink--default

![cardlink in disabled state.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/ed04af21-a6dc-4495-9aab-239df963a061)

**Comment by kennylam** [comment]
@Praveen-sr @chetankan @RobertaJHahn PR has been created

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3247/index.html?path=/story/components-cardlink--default
