### ISSUE TITLE
pattern: simple overview

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#323]
_Wonil-Suh1 created the following on Aug 06:_  

 ### User story
As a user of IBM.com, I need a way to get a high level overview of the content/product presented on the page that I am looking at, and understand the value for my goal.

### Example from STUF design exploration
![screen shot 2019-08-09 at 9 43 11 am](https://media.github.ibm.com/user/25726/files/21fd1c80-ba8a-11e9-91d1-f758e0c1a68b)
In the above example, the link should not be there.

![https://media.github.ibm.com/user/25726/files/b4534c00-c8e3-11e9-9d45-4635319fd826](https://media.github.ibm.com/user/25726/files/b4534c00-c8e3-11e9-9d45-4635319fd826)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1384_

**Comment by RobertaJHahn** [comment]
Closing as the pattern strategy has been changed with the new ontology.
