### ISSUE TITLE
Case studies template doesn't allow relative URLs in specific fields

### ISSUE THREAD

**Issue by elainemaekawa** [carbon-design-system/ibm-dotcom-library#3232]
Case studies template: Some of the fields are not allowed to have Drupal URLs (relative ones) causing problems when the pages are globalized.

> Describe in detail the issue you're having.
--> Some of the fields to add URLs have "This must be an external URL such as http://example.com." below the field, although it has this comment, this field is being used to add internal URLs (Drupal). This happens on "Taxonomy" tab. As I don't have access to edit it, I am not sure if it can be built in another way, so it would be easier if these fields get updated to receive Drupal/relative URLs. Because by using absolute URLs with the Drupal pages, the user is not being correctly redirected.

> Is this a feature request (new component, new icon), a bug, or a general issue?
This is a template limitation.

> Is this issue related to a specific component?
Yes, it is happening on "Taxonomy" tab reflecting on "Solution components" band on the page.

> What did you expect to happen? What happened instead? What would you like to see changed?
I would like to see the fields being able to receive any type of URLs, as other fields in the same template that says "Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. Enter <nolink> to display link text only.". As I am not familiar with the template, I don't know if the content can be moved to fields with this comment, so it would be better to all field to accept all types of links.

> What browser are you working in?
Chrome

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Case studies pages are starting the Globalization process at the moment, looks like it wasn't noticed before.

## Steps to reproduce the issue (it is not an issue to be reproduced, but to see it, you can:)

1. Open edit page
2. Go to "Taxonomy" tab
3. You will be able to see some of the fields allow only external links and some of them allow all types

## Additional information

- Example page: https://cms.ibm.com/case-studies/jenzabar-ibm-cloud-bare-metal-storage

<img width="811" alt="Screen Shot of Software links field" src="https://user-images.githubusercontent.com/67021524/88085756-abebab80-cb5c-11ea-9a5b-145d9871a1aa.png">

<img width="842" alt="Screen Shot of Solution Area links field" src="https://user-images.githubusercontent.com/67021524/88085906-e2c1c180-cb5c-11ea-9131-bbce20e26bc0.png">

- From what I understand, the solutions used in the case needs to go to the correct field, but only "Solutions Area" allows internal URLs.

**Comment by RobertaJHahn** [comment]
This looks like a Drupal issue.  We will send an email to Ke with a link to this issue so they can log it in the Jira on their side.

**Comment by ljcarot** [comment]
@elainemaekawa Can you report your problem in either ServiceNow or in slack channel #HC-Drupal-Marketing-Support?  Your problem needs to be addressed at that layer.  This repo is for ibm.com library users.

**Comment by elainemaekawa** [comment]
Sure, I can, thank you.
