### ISSUE TITLE
Web Components: Hide some portions in story from Percy

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#3242]
### The problem
Some portions in our stories, notably video player, tends to cause false positives in Percy.

### The solution
Introduce Percy specific CSS.

### Additional information
https://github.com/carbon-design-system/ibm-dotcom-library/pull/3211#issuecomment-662125357

**Comment by jeffchew** [comment]
Adding this comment, we might need to pass in manual data for navigation for the visual regression as well: https://github.com/carbon-design-system/ibm-dotcom-library/pull/3197#issuecomment-662589467

**Comment by jeffchew** [comment]
This looks to be stabilized now, so going to move to done.
