### ISSUE TITLE
Component:- Leadspace with Image(Stage):- Copy text is not visible without gradient overlay on mobile and tablet.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3248]
#### **Jeff would like this fix included in the v1.9.0 hot fix**

Issue Description:- In 'Leadspace with Image' on deselecting 'Gradient Overlay' option copy text and secondary button text is not clearly visible. Happening on 'Default with Image' and 'Small with Image'.
 
## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'Leadspace with Image' component.
3. In knobs section deselect gradient overlay.

OS:- iOS 12, 13 Android 8,9![Leadspace without gradient.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/a1c65e73-e7ed-48cd-a37e-068ed7d6dc2f)
Browsers:- Safari, Chrome, UC

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-leadspace--default-with-image

#### Additional Information
 - Solution:  Dev should set the gradient on by default in Storybook

**Comment by ariellalgilmore** [comment]
Gradient is already defaulted to true for storybook
