### ISSUE TITLE
Pattern: ContentBlock Mixed - No spacing between bottom section and the border line.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3259]
## Detailed description

Issue :- No spacing is provided between the bottom section i.e card and the border line.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1e8a64ae-fb65-41c2-926f-d58ee25dc024)

**Comment by guilhermelMoraes** [comment]
Removing myself as I'm working on the support page and will most likely be unable to finish this one this sprint.

**Comment by IgnacioBecerra** [comment]
I believe issue [#3662 ](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3662) is the same as this one. It's in review at the moment, so will place this issue in Review as well, unless it's okay for this issue to be closed.

**Comment by RobertaJHahn** [comment]
Closing as a dup of (#3662). 

cc:  @IgnacioBecerra
