### ISSUE TITLE
Component: lightbox (image viewer) MVP design specs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#326]
_Wonil-Suh1 created the following on Aug 06:_  

  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1387_

**Comment by wonilsuhibm** [comment]
Visual design specs have been completed and are available in this [Box folder](https://ibm.box.com/s/mpeo1wy0jogkwxn68fahlg62q799ixox).

**Comment by sannminwin** [comment]
Hey @wonilsuhibm ,
is this spec version 1.2.0 the latest ?

**Comment by wonilsuhibm** [comment]
@sannminwin Just uploaded an updated PDF with the desktop image layout behaviors in the Box folder. [Direct link to the file](https://ibm.box.com/s/8hkf85xzjunh9pyiid64jhlpzpueaxiw)
