### ISSUE TITLE
Pattern: ContentBlock Cards - Video Modal background is transparent, parent page content is seen for the user. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3260]
## Detailed description

Issue :- Video Modal background is transparent, parent page video / heading content is seen for the user. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7e78e7d6-b68a-4a5b-b610-c1c368bd7718)

**Comment by andysherman2121** [comment]
Spoke with both @wonilsuhibm @annawen1. We agreed this isn't a bug. The parent page should be visible when the modal is open.
