### ISSUE TITLE
Pattern: Cardsection images,  ContentBlock cards (with images) & ContentBlock segmented  - text font size must be 14px

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3261]
## Detailed description

Issue :- On Cardsection images,  ContentBlock cards (with images) & ContentBlock segmented  - text font size is 16px 

Expected :- text font size must be 14px. (Discussed on call with Designer )

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5f6cb5d3-8165-4be5-9e0a-4911b4323be0)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b1635ee7-7746-4c02-8ff9-af118ec8ad7b)

**Comment by guilhermelMoraes** [comment]
Checked and it's working as expected. All the listed components have `font-size: 14px`. 
![Captura de Tela 2020-08-04 às 10 32 56](https://user-images.githubusercontent.com/42848561/89299967-def26c80-d63d-11ea-8e75-083f228ff63f.png)

cc: @RobertaJHahn I think we can close this one, as it was probably addressed in another PR
