### ISSUE TITLE
React:  MegaMenu Visual QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3265]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `MegaMenu`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- The work should be done immediately following the dev work.  The planned schedule is 8/10 - 8/12
- Dev Issue (#3279)
- [react canary link](https://ibmdotcom-react-canary.mybluemix.net/?path=/docs/overview-getting-started--page)

 #### Tasks
Ensure the `MegaMenu` React component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by annawen1** [comment]
@wonilsuhibm @RobertaJHahn The MegaMenu has been completed. Only thing is the animation when switching between L0 nav items - this will be in the next iteration

You can test here: https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-dotcom-shell--default or https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default

**Comment by RobertaJHahn** [comment]
@oliviaflory The Visual QA testing is scheduled the sprint from 8/10 - 12.  This schedule assumes that any high priority defects you find will be fixed in the last 2 days of this week.  The code freeze is Friday, May 14.

**Comment by oliviaflory** [comment]
Thank you @RobertaJHahn

**Comment by RobertaJHahn** [comment]
@oliviaflory No, just add them as bugs and we will prioritize and move into development based on the comments in the review meetings.  Thanks.

**Comment by RobertaJHahn** [comment]
@oliviaflory Haave you finished the visual QA testing?  Can I close?

**Comment by oliviaflory** [comment]
I believe so, we can close!
