### ISSUE TITLE
Component: lightbox (image viewer) guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#327]
_Wonil-Suh1 created the following on Aug 06:_  

  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1388_

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
Keeping this issue open and linking it to a new epic (#1231) so that it can be tracked with the designers are available.
