### ISSUE TITLE
Masthead (L1) navigation dropdown display issue on tablet	

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#3272]
## Detailed description

**_Only happening on iPad pro 12, 11_**

Original issue: https://jsw.ibm.com/browse/WS-1073

On tablet in landscape mode when user clicks on navigation links Ex:- Technologies or Business Needs link are getting displayed behind leadspace text.

## Steps to reproduce:
1) Enter products url in browser.
2) Turn tablet in landscape mode.
3) Click on 'Technologies'  in masthead.
4) Now click on 'Business Needs' .

OS: iOS 12, 13
Browsers:- Safari, Chrome
Devices :- iPad pro 12, 11

Please refer attached screen shot.

![image](https://user-images.githubusercontent.com/15144993/88419399-1eee5f80-cdb3-11ea-8971-8bedefda3f74.png)
![image](https://user-images.githubusercontent.com/15144993/88419408-231a7d00-cdb3-11ea-8db1-684334544a6a.png)
![image](https://user-images.githubusercontent.com/15144993/88419413-27469a80-cdb3-11ea-8aa2-e746b7ee5ccc.png)

**Comment by RobertaJHahn** [comment]
@chetankan @Praveen-sr Could you testing this to see whether you can replicate the issue?  Thanks.

**Comment by RobertaJHahn** [comment]
Yes, this issue was found in the React version when quickly switching between the menu drop downs.  They can not validate this behavior in the Carbon version because only link 4 has a drop down.

Next step:  DDS engineering will create a code sand box so that Prod QA can validate the issue in Carbon.

**Comment by guilhermelMoraes** [comment]
@Praveen-sr @chetankan here's the link where you guys can validate if the bug is happening in Carbon as well 

https://jmn5i.csb.app/# 

Please, tell me if this is enough for you guys to test it. I can add/remove links as you guys wish.

cc @RobertaJHahn

**Comment by chetankan** [comment]
@guilhermelMoraes :- Can you please add some text in 'ui shell content' section ,link shared by you doesn't contain any text so  we were not able to reproduce the issue.

@RobertaJHahn @Praveen-sr .

![Carbon.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/c0e72929-c0e8-47d7-a2d3-f9cd7ecc2281)

**Comment by guilhermelMoraes** [comment]
Link updated, @Praveen-sr @chetankan! 

Please, let me know if the text in place is enough.

**Comment by chetankan** [comment]
@guilhermelMoraes : Verified issue on this link  https://jmn5i.csb.app/# , and it is working fine.
@Praveen-sr @RobertaJHahn
