### ISSUE TITLE
 Pattern: testimonial band: study

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#329]
### user story
As a customer of IBM looking for the right product for my needs, I would like to hear how other IBM customers are using IBM products and how they like them.

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1390_

**Comment by RobertaJHahn** [comment]
Web Simplification will perform a study and provide the content model.  This work will be needed for the Product page in the future.  Moving to Icebox pipeline.

**Comment by RobertaJHahn** [comment]
All other issues for related work have been closed by stalebot.  Closing this issue.  Will create a new one if/when this work becomes a priority as no work has been done up to this point.
