### ISSUE TITLE
Content copy and image fixes

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#3292]
### For the Layout Patterns pages published in Sprint 20-15

- [x] Content Group Simple

![Screen Shot 2020-07-27 at 4.38.11 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/4a8e9ca9-de21-4aef-ad17-fb0401334a56) 
![Screen Shot 2020-07-27 at 5.37.19 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/df8f5cad-5420-4976-a3dc-62da5a2f7245)

https://ibm-dotcom-library.mybluemix.net/patterns/content-group-simple

---

- [x] Feature Card Large

![feature-card-block-large-issues.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/28ce7db8-d288-4e0d-8b9d-3df4923163c2)

---

- [x] Content group pictograms

There's an extra space after the vision and before the "("

![Screen Shot 2020-07-27 at 5.39.37 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/18ca7f76-40bf-4510-874f-faab3c923af8)

---

- [x] Content block simple

![Screen Shot 2020-07-27 at 5.43.09 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/2f057b56-16e6-4107-a1d2-bdb54b0df983)

![Screen Shot 2020-07-27 at 5.43.22 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/d69047c9-0b8c-4093-936e-5de0daee07c9)

---

- [x] Card section with images

![Screen Shot 2020-07-27 at 5.46.07 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/833db85e-3425-40d7-a347-1b13db0d9a36)

**Comment by JennySanchez** [comment]
- [ ] Update the pattern call out treatment. 

We will use Cap and " " when calling out a pattern name in a sentence. 

For example, `The content block — simple pattern is typically used for the introductory section on a page.` 

should be 

`The "Content block — simple" pattern is typically used for the introductory section on a page.`

**Comment by JennySanchez** [comment]
- [ ] Update the "Specification documentation" section to "Design and functional specifications"

**Comment by JennySanchez** [comment]
- [ ] Update the link code to be open the linked page in a separate browser instead of the same browser page.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez All links have been updated  for links and Cap/em dash are in the PR:

https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/556

Please review and approve once preview deploy link is ready. Thanks!

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #558](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/558) via [**ZenHub**](https://www.zenhub.com/)
