### ISSUE TITLE
wrong type validation for Card component

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#3296]
We use the Card in IBM docs project and display an icon in place of eyebrow,
as 
![image](https://user-images.githubusercontent.com/15310250/88646916-d0e49f00-d0c5-11ea-9041-10c7dfe5a579.png)

this works, but please adjust the type for the property so it accepts object, not string.

![image](https://user-images.githubusercontent.com/15310250/88643715-5c5c3100-d0c2-11ea-9a19-97809e9d31fb.png)

**Comment by RobertaJHahn** [comment]
Next step is to review their request with Design, functional and engineering.  Roberta will add this topic to the next KC status meeting.

**Comment by RobertaJHahn** [comment]
Roberta will ask Miraslav to provide a screen capture of the icon the propose to use.  Provide this information to the designers and James so they can make a decision.

**Comment by RobertaJHahn** [comment]
email sent to KC status meeting contacts requesting images of the proposal.

**Comment by kyjak** [comment]
This is not a feature request, you don't have to do anything, but fix the PropType of the Card's eyebrow property to accept an object rather than a string only. (It already works with an icon, so no coding needed, just make the warning go away)

**Comment by RobertaJHahn** [comment]
@ljcarot @wonilsuhibm @oliviaflory  Please see response Miroslav to my request above.

**Comment by photodow** [comment]
@kyjak the prototype is there because strings are only what's allowed at this point. So to remove the proptype, and allow other types inside would be a feature request.

**Comment by kyjak** [comment]
created a feature request https://github.com/carbon-design-system/ibm-dotcom-library/issues/3605
closing this one
