### ISSUE TITLE
 Pattern: testimonial band: guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#332]
_Wonil-Suh1 created the following on Aug 06:_  

  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1393_

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available. The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
Closing this issue as all other issues related to this work have been closed by the stalebot.
