### ISSUE TITLE
Guidelines: layout patterns authoring

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#335]
_Wonil-Suh1 created the following on Aug 06:_  

 As a maker or IBM.com experiences, I need to know what kind of layout options are available so that I can design and develop in a way that is better aligned with the rest of ibm.com. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1396_

**Comment by larahanlon2** [comment]
Closing this issue because it's not relevant. Opening new issues to reflect updated work.
