### ISSUE TITLE
React: CTA Section Reboot requested change design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3364]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/109648616047)

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by ltitle** [comment]
@RobertaJHahn Updated designs are posted here in version 1.2.0 https://ibm.ent.box.com/folder/109648616047
