### ISSUE TITLE
Pattern: simple overview band specs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#337]
_Wonil-Suh1 created the following on Aug 06:_  

 ### User story
As a user of IBM.com, I need a way to take a high level overview of the content/product presented on the page that I am looking at.

### Acceptance criteria
- [ ] specs are available

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1398_

**Comment by jeffchew** [comment]
_On Oct 09, Wonil-Suh1 commented:_
The latest specs are here:
![pattern--simple-overview--specs--max](https://media.github.ibm.com/user/25726/files/af65e880-ea9c-11e9-8525-fe6fd4fde23c)
![pattern--simple-overview--specs--xlg](https://media.github.ibm.com/user/25726/files/8a717580-ea9c-11e9-9493-6bdc1908bddf)
![pattern--simple-overview--specs--lg](https://media.github.ibm.com/user/25726/files/8e04fc80-ea9c-11e9-8b0f-31e7758be505)
![pattern--simple-overview--specs--md](https://media.github.ibm.com/user/25726/files/92311a00-ea9c-11e9-9f45-4b739ef14455)
![pattern--simple-overview--specs--sm](https://media.github.ibm.com/user/25726/files/94937400-ea9c-11e9-9a35-1127a34aa05e)

**Comment by jeffchew** [comment]
_On Oct 09, Wonil-Suh1 commented:_
@chsanche @larahanlon @Olivia-Flory @Jacob-Ottesen @spbokma please review and comment.

**Comment by jeffchew** [comment]
_On Oct 09, Olivia-Flory commented:_
Looks pretty good! 

Would it be helpful to see the same `label` content from max and xl on the large, medium and small breakpoints? Wondering if the 80% width will be cause problems on the medium breakpoint specifically. Unless we are proposing changing content per breakpoint?

**Comment by jeffchew** [comment]
_On Oct 09, chsanche commented:_
Looks good! One nitpicky thing is I wish the space indicator can be shown on the content area but not on the side.

`Question:` Is the pink color the color we are going to use for all the spac kind of documents? I asked bc if that is the case, we need to make sure we all do the same thing.

**Comment by wonilsuhibm** [comment]
Updated specs per discussion on Oct 14th.

![pattern--simple-overview--specs--max](https://user-images.githubusercontent.com/30183447/66771314-eca8ec80-ee87-11e9-8fc8-ec2ee0d167a4.png)

![pattern--simple-overview--specs--xlg](https://user-images.githubusercontent.com/30183447/66771317-efa3dd00-ee87-11e9-9166-3aa505277b84.png)

![pattern--simple-overview--specs--lg](https://user-images.githubusercontent.com/30183447/66771330-f7fc1800-ee87-11e9-9c5e-1de487fb4602.png)

![pattern--simple-overview--specs--md](https://user-images.githubusercontent.com/30183447/66771331-f894ae80-ee87-11e9-9838-8a7332d3dbad.png)

![pattern--simple-overview--specs--sm](https://user-images.githubusercontent.com/30183447/66771332-f894ae80-ee87-11e9-94d9-a77fc5270d96.png)

**Comment by wonilsuhibm** [comment]
[Latest specs](https://ibm.box.com/s/rg30kcpyxnp1usx4fumi54trc60q8pb9)

[Sketch](https://ibm.box.com/s/86y1lohzc01pry5wxd57t762rzfav4a7)
