### ISSUE TITLE
Web Component:- Locale Modal:- There is no space between geo cards on locale modal

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3406]
Issue Description:- In locale modal components there is no spacing between geo cards.

## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'Locale Modal' component.
3. Observe if there is spacing between cards.

OS:- Win 10, Mac, iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, Firefox, Edge, UC

URL:- http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-locale-modal--default

![Locale Modal without spacing.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/98211f58-6617-4d01-a3d7-ee1580c57874)

**Comment by jeffchew** [comment]
Added blocker https://github.com/carbon-design-system/ibm-dotcom-library/issues/3482 to this issue, as that should resolve the issue with the styling.

@RobertaJHahn Moving this to the next release.

cc: @ariellalgilmore

**Comment by RobertaJHahn** [comment]
airtable updated.
