### ISSUE TITLE
Web component: Card Link - card width and top alignment is not as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3407]
## Detailed description

Issue :- On web component Card Link - 
1. Card width is 420px but on 'react' its 320px
2. Card is aligned 48px from top, but on 'react' no spacing from top.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/985f5edd-0f95-4ea4-a316-edefdd653e13)

**Comment by RaphaelAmadeu** [comment]
The spacing you see on top is not from card-link, but from web-components storybook.
