### ISSUE TITLE
Pattern: simple next step (CTA) band

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#341]
_Wonil-Suh1 created the following on Aug 06:_  

 ### User story
As a user of IBM.com, I need a way to go to the next step in my journey after consuming the content of the page I am looking at currently.

### Examples
![screen shot 2019-08-09 at 9 51 54 am](https://media.github.ibm.com/user/25726/files/908eaa00-ba8b-11e9-86da-b3fe561504c4)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1402_

**Comment by RobertaJHahn** [comment]
Closing this epic as all linked issues are closed.
