### ISSUE TITLE
Component:- Locale Modal:- Search by Location or Language modal: Close button 

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3410]
Issue Description:-Close button is announced as "Select geographic area button" instead.

Recommended Fix:- Provide label as "close"

Happening on screen reader.

url:- https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-locale-modal--default

**Comment by caiobozato** [comment]
@chetankan Could you please test again?

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3447/index.html?path=/story/*

**Comment by caiobozato** [comment]
@Praveen-sr mentioned on QA call today now it's working as expected. 

I'm going to convert the Draft PR to an official one and will ask engineers to review it.

@RobertaJHahn FYI

**Comment by Praveen-sr** [comment]
Working fine. Now the label is announced as "close modal" Tested in FF with JAWS

**Comment by caiobozato** [comment]
@Praveen-sr Thanks! Moving to review to wait for PR review.
