### ISSUE TITLE
Component :- Locale Modal:- Search by Location or Language modal: Location and Language options

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3412]
Issue Description:-

 1. Location and Language options are not identified by the screen reader while navigating with up/down arrow keys
2. In tab/shift tab navigation, screen reader is identifying each option as link but, forms mode is getting triggered each time.

Happening on screen reader.

URL:- https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-locale-modal--default

**Comment by caiobozato** [comment]
@Praveen-sr @chetankan Could you please re test? 

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3466/index.html?path=/story/components-locale-modal--default

**Comment by Praveen-sr** [comment]
@caiobozato Ram re tested this on the above link, now screen reader(JAWS) is identifying the list of options as links. Working as expected. Thanks!
