### ISSUE TITLE
Web Component: Lightbox Media Viewer - video modal size is small and not in sync with react version.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3413]
## Detailed description

Issue :-  Lightbox Media Viewer - video modal size is small and not in sync with react version.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dbbc7f5a-4380-4f0c-add3-c65c7f4610ec)

Expected :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/bb0fdc78-8785-4f23-a246-74d5b964f7d0)

**Comment by guilhermelMoraes** [comment]
@Praveen-sr can you please test it again? Comparing both versions side by side looks like pretty much the same. 

[Lightbox media viewer | WEB-COMPONENTS (CANARY)](http://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-lightbox-media-viewer--embedded-video-player)

[Lightbox media viewer | REACT (CANARY)](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-lightboxmediaviewer--embedded-video-player)

cc @RobertaJHahn

**Comment by Praveen-sr** [comment]
@guilhermelMoraes Re tested this on both "Web- component and React canary" - both the video modal size is in sync now. Working as expected. Thanks!
cc @RobertaJHahn
