### ISSUE TITLE
Custom search in masthead - engineering

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#3415]
This Knowledge Center feature request involves both Design and Engineering work.  DDS Design will be considering the KC request along with the global ibm.com needs.  Engineering will provide hooks to type ahead search and redirect URL.  This epic includes links to the issues for all of the work needed to provide this feature.

KC request:  
_For certain pages, KC needs to switch the masthead search for KC search, rather the ibm.com one.
We would need:_
_- a hook for keyboard event (user types a phrase)_
_- a hook when search is launched (icon click/enter/whatever the masthead considers as a search action)_
_- able to switch between ibm.com and kc search based on a prop_

**Comment by RobertaJHahn** [comment]
Jeff suggests providing the feature behind a feature flag so that it would be available to them to provide feedback on the metrics.  Design is needed.  Roberta will schedule a 30 minute meeting:  Attendees - Wonil and Olivia optional, Kenny, Jeff, Akira and KC status attendees.

**Comment by RobertaJHahn** [comment]
Meeting scheduled with KC team Aug 18, 2020
