### ISSUE TITLE
Pattern: simple overview band guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#342]
_Wonil-Suh1 created the following on Aug 06:_  

 ### User story
As a user of IBM.com, I need a way to take a high level overview of the content/product presented on the page that I am looking at.

### Notes
This will probably have to be divided into smaller stories.

### Acceptance criteria
- [ ] Design guidelines are ready for publishing
- [ ] Dev guidelines are ready for publishing

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1403_

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.
