### ISSUE TITLE
Web Component:  Accordion & Content block - accordion design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3421]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Accordion Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/119040241002)
- [Content block - accordion Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/119674330757) 

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Draft design specs reviewed in 8/5/2020 meeting.  Final specs will be delivered next week.

**Comment by ltitle** [comment]
@RobertaJHahn @jyoon25 has provided both visual specs:
Accordion: https://ibm.ent.box.com/folder/119040241002
Content block–accordion: https://ibm.ent.box.com/folder/119674330757

**Comment by RobertaJHahn** [comment]
@ltitle @jyoon25 Got it.  Thanks.
