### ISSUE TITLE
Web Components: Integrate ProfileAPI into Masthead

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3432]
## Detailed description

> Describe in detail the issue you're having.

After a closer look, it looks like the ProfileAPI is not getting called in order to determine the authenticated state of the user.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Masthead

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Replace the `authenticated` property and have that completely driven by the ProfileAPI call.

Also need to doublecheck, but the profile menu items should be driven by the translation file.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@asudoh would you be able to look at this one? If not can see if someone else can pick up.

**Comment by asudoh** [comment]
@jeffchew Sure I can take a look.
