### ISSUE TITLE
Integrate dds-modal with dds-lightbox-media-viewer-container

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3435]
## Detailed description

> Describe in detail the issue you're having.

Right now it looks like the dds-modal is part of the storybook story, and not part of the component itself. We should be making it easy enough for adopters to implement the lightboxmediaviewer with something like this:

### JS

```javascript
import '@carbon/ibmdotcom-web-components/es/components/lightbox-media-viewer/lightbox-video-player-container';

// Opens the lightbox media viewer
document.getElementById('my-video').open = true;
```

### HTML

```html
<dds-lightbox-video-player-container
    id="my-video"
    video-id="0_uka1msg4"
>
</dds-lightbox-video-player-container>
```

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@RobertaJHahn moving this to the next release as this won't make the code freeze.

**Comment by RobertaJHahn** [comment]
@jeffchew OK, moved to sprint 20-17.

**Comment by guilhermelMoraes** [comment]
Removing myself as I'm working on the support page and will most likely be unable to finish this one this sprint.
