### ISSUE TITLE
Component:- CTA :- After clicking on text link video player is getting displayed

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3440]
Issue Description :- 1) In CTA component on clicking text link, video player is getting displayed with message saying "Error, No source video was found".

2) Link type with  'Local', 'Regular', 'Jump' on click  are getting opened in new tab instead on same tab.

## Steps to reproduce the issue

1.Enter url in the browser.
2. Select 'CTA' component.
3. Open in new tab and click on text link.
4. Switch back to the tab from where link is clicked on.

OS:- Win 10, Mac, iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, Firefox, Edge, UC

URL:- http://ibmdotcom-web-components-canary.mybluemix.net/

![CTA web component.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/d2487ada-d67c-4c3b-87ed-b40045eb3ae0)

**Comment by RobertaJHahn** [comment]
The second bug included in the description above has not been fixed.  Moving this issue to sprint 20-17 to work on this fix.

**Comment by RobertaJHahn** [comment]
@asudoh It appears that the second bug documented in this description is not fixed.  (I may be wrong.)  Could you take a look at this?  It is blocking the Prod QA testing by the India team.  Thanks.

cc:  @Praveen-sr

**Comment by asudoh** [comment]
@RobertaJHahn Thank you for checking - #3855 contains the fix. QA team can try it out via the staging URL: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/3855/index.html

**Comment by Praveen-sr** [comment]
@RobertaJHahn Re tested this on [Web component staging](https://ibmdotcom-web-components-staging.mybluemix.net/?path=/story/components-cta--default), above two issues are fixed now.  
cc @asudoh

**Comment by asudoh** [comment]
Thanks @Praveen-sr for checking!
