### ISSUE TITLE
Locale modal list view has incorrect color/tokens

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#3445]
## Detailed description

**Describe in detail the issue you're having.**
During QA call, it was noticed that the `search input` and the language labels have incorrect color values.

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Locale modal

**What did you expect to happen? What happened instead? What would you like to see changed?**

### 1. As per design specs, `search input` should have a gray background. See below

Storybook currently has a white input field with a bottom gray rule.
<img width="823" alt="Screen Shot 2020-08-05 at 11 05 52 AM" src="https://user-images.githubusercontent.com/53093550/89430275-948bf100-d70c-11ea-9896-e1b15876b491.png">
 
Actual design specs:
<img width="1113" alt="Screen Shot 2020-08-05 at 11 05 44 AM" src="https://user-images.githubusercontent.com/53093550/89430345-a79ec100-d70c-11ea-919f-e2a31a9585ec.png">

### 2. The language label should use the type token `body-short-02, text-05` (16px, gray 60)

Storybook currently shows a very faint gray color impacting accessibility:
<img width="446" alt="Screen Shot 2020-08-05 at 11 07 42 AM" src="https://user-images.githubusercontent.com/53093550/89430583-dddc4080-d70c-11ea-950b-dbc3b677db53.png">

**What browser are you working in?**
All

## Steps to reproduce the issue

Open [locale modal](https://ibmdotcom-react.mybluemix.net/?path=/story/components-locale-modal--default) and click a geographic region card

**Comment by oliviaflory** [comment]
Hey @larahanlon2, was checking out the type token colors and I think Carbon updated text-03 since we speced locale selector

$text-03 is "placeholder text" and is now gray 40 #A8A8A8 (Note: in the past we've heard that placeholder text is not held to the same standards for accessible contrast as regular content)

So I was thinking text-05 might work better considering the original intent? 
$text-05 is "tertiary text" and gray 60 #6F6F6F

**Comment by larahanlon2** [comment]
Thanks so much @oliviaflory for confirming this! I agree with your suggestion, $text-05 should work just fine.
