### ISSUE TITLE
Content block aside elements not aligning correctly

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#3454]
## Detailed description

**Describe in detail the issue you're having.**
The aside elements for both `content block simple`, `content block media` `content block mixed` and `content block segmented` are not top-aligning as intended. 

Current story:
<img width="1448" alt="Screen Shot 2020-08-05 at 1 35 53 PM" src="https://user-images.githubusercontent.com/53093550/89445605-65cc4580-d721-11ea-905b-a28249a898e5.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
`content block simple` and `content block segmented` and `content block mixed` and `content block media`

**What did you expect to happen? What happened instead? What would you like to see changed?**
The heading of the `aside elements` title should be top-aligned to the intro copy of the `content block`.
As per design spec:
<img width="997" alt="Screen Shot 2020-08-05 at 1 37 57 PM" src="https://user-images.githubusercontent.com/53093550/89445686-7d0b3300-d721-11ea-95dc-a67fdda89f3b.png">

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
The latest

## Steps to reproduce the issue

https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentblocksegmented--with-aside-elements
## Additional information

https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentblockmixed--with-aside-elements

https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentblockmedia--with-aside-elements

https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentblocksimple--with-aside-elements

- Screenshots or code
- Notes

**Comment by diegomarcuz** [comment]
Waiting a Lara's help, because I have some design questions

**Comment by diegomarcuz** [comment]
@larahanlon2, Could you check again ?? This is the deploy preview: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3680/index.html

**Comment by larahanlon2** [comment]
Looks great! I don't see any issues now. Thanks @diegomarcuz

**Comment by diegomarcuz** [comment]
Thanks @larahanlon2
