### ISSUE TITLE
v 1.9.0 takes more memory and time in react-scripts build process

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/ibm-dotcom-library#3455]
## Detailed description

> Describe in detail the issue you're having.
Please refer to the conversation in the slack channel.
https://chiefdataoffice.slack.com/archives/C2PLX8GQ6/p1596640981224300

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@yellowdragonfly can you let us know which imports you are using for styles? 

cc: @andysherman2121

**Comment by yellowdragonfly** [comment]
here is my import:
@import '@carbon/type/scss/type';
@import 'carbon-components/scss/globals/scss/styles.scss';
@import '@carbon/ibmdotcom-styles';

**Comment by jeffchew** [comment]
Attached style imports from another adopter:

[global.scss.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/5035504/global.scss.zip)

**Comment by yellowdragonfly** [comment]
[DataPrefCenterIBMDOTCOM.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/5065541/DataPrefCenterIBMDOTCOM.zip)
the simple project to reproduce the issue sent to Andrew Sherman

**Comment by andysherman2121** [comment]
@yellowdragonfly Can you let us know if you've experienced a difference in build times? As we've updated the library since this was originally posted

**Comment by yellowdragonfly** [comment]
@andysherman2121 version V1.11.0 is much better. This issue is considered to be solved. Thank you.
