### ISSUE TITLE
Remove web-component specific styles for Footer

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3497]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
ensure all styles for Footer live in the styles package

> so that I can:
manage styles for the Footer regardless of framework

#### Additional information

 - Current masthead styles in `web-components`: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/web-components/src/components/footer/footer.scss
 - The way footer styles are structured (with nesting) it is preventing a cleaner inclusion of the styles package styles into web components

#### Acceptance criteria
 - [ ] No more custom styles for `dds-footer` in `web-components`

**Comment by asudoh** [comment]
@jeffchew Footer doesn't have any custom styles except ones that are absolutely necessary. For example, `:host(#{$dds-prefix}-footer), :host(#{$dds-prefix}-legal-nav) { display: block; }` is there because the default `display` style for non-intrinsic elements is `inline` and the CSS rule adjusts that. Such nature makes the CSS rule Web Components-specific.

**Comment by guilhermelMoraes** [comment]
@asudoh @jeffchew do we have any updates on this? I'm interested in getting this issue.

**Comment by jeffchew** [comment]
Due to risk, we are moving this out to the next release.

cc: @RobertaJHahn

**Comment by asudoh** [comment]
@guilhermelMoraes Given footer's WC-specific styles are absolutely-necessary ones, I don't think this issue involve any action item.

**Comment by RobertaJHahn** [comment]
@jeffchew I have moved this issue to the next sprint, but based on Akira's comments above, should I close it?

**Comment by jeffchew** [comment]
@RobertaJHahn yes, let's close this out. Thank you all!
