### ISSUE TITLE
Mega menu mobile – overlapping menu items or double menus.

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3512]
## Detailed description

> Describe in detail the issue you're having.

When viewing the mobile menu on my iPhone in Safari, if the content within a category is a shorter length than the previous high level category I can see _both_ sets of menu text. In some cases the text is overlapping, and other cases not.

In the screen shots below "Security, Supply chain, Payment plans for products, View all" are a part of the Products & Solutions menu, however I am viewing Products & Solutions > Top products or Supply chain sub categories.

| Products & Solutions > Top products | Products & Solutions > Supply chain |
|--- |--- |
| ![IMG_1796](https://user-images.githubusercontent.com/45692622/89906067-e9ba7d80-dbb8-11ea-8ba2-5d52d5c7bb5a.PNG) | ![IMG_1797](https://user-images.githubusercontent.com/45692622/89906072-eaebaa80-dbb8-11ea-92df-6df35c8c7d91.PNG)| 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Mega menu mobile

> What did you expect to happen? What happened instead? What would you like to
> see changed?

User should only see the content from a single category or sub category they are viewing.

> What browser are you working in?

Safari iOS 13.6 on iPhone 7

> What version of the IBM.com Library are you using?

Latest canary

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

August

## Steps to reproduce the issue

1. Open mega menu mobile from latest canary 
2. Products & Solutions > Top products
3. Scroll down in menu
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by Praveen-sr** [comment]
Adding another issue to above list,

Issue: On Mobile - Hamburger menu - while clicking on "Data & Analytics, IT infrastructure and security" menu options, user is navigated to end of the list options and user needs to scroll up to see start of the list. 

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6ecf21ca-22aa-483e-b097-fc107a9194cb)
