### ISSUE TITLE
Web Component: Footer - Navigating through footer 'default' and 'short' links, page does not refresh and load.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3528]
## Detailed description

Issue :- **Storybook issue**
Navigating through footer 'default' and 'short' links, page does not refresh and load new content.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/11de440a-20b0-411f-a005-919d80351a9b)

**Comment by asudoh** [comment]
Looking at http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-footer--default and http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-footer--short, it appears that the problem is no longer reproducible. @Praveen-sr Could you please check? Thanks!

**Comment by Praveen-sr** [comment]
@asudoh Re checked this on web-components - its working fine now.
