### ISSUE TITLE
Web Component: - Footer:- Locale selector should be uniform across different environments

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3529]
Issue Description:- Locale selector should be displayed in uniform manner across different env. In web-component locale selector is displayed as "English-United States" where as in react env it is displayed as "United States-English". 

OS:- Wins 10, Mac, iOS 12, 13 Android 8,9
Browsers:- Chrome, Safari, Firefox, Edge, UC browser.

Web-Component URL:- http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-footer--default

React-Canary URL:- https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-footer--default![Footer in react canary.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/96327153-963f-4ac0-a433-d7377c8d8608)

![footer in web component.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/17923897-8212-4052-80be-357ae54876b6)

**Comment by asudoh** [comment]
Checking http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-footer--default, seems that it's now "United States - English". @Praveen-sr Could you please check? Thanks!

**Comment by Praveen-sr** [comment]
@RobertaJHahn Tested this on web components and react, its working fine.
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e85265d3-8862-4dd0-bd35-0f238a1bcf5b)

cc @asudoh

**Comment by asudoh** [comment]
💯 - Thanks a lot @Praveen-sr!
