### ISSUE TITLE
Component:- Mega Menu :- Payment plans and view all product links are not clickable on iphone

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3531]
Issue Description:- 1) 'Payment plans for products and solutions' and 'View all products' under products and solutions under mega menu are not clickable on iphone/ safari browser. Even though if user clicks on payment plans or view all products link focus shifts to close icon on hamburger icon. 

2) 'View all services' links under 'Service and Consulting' menu needs to click twice to navigate to target page.(iPhone / Safari)

## Steps to reproduce the issue

1. Enter url in the browser.
2. Click on hamburger menu.
3. Click on 'Products and Solutions'.
4. Click on 'Payment plans for products and solutions' or 'View all products'

OS:- iOS 12, 13
Browser:- Safari (iPhone)

URL:- https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-dotcom-shell--default

**Comment by kennylam** [comment]
@Praveen-sr @chetankan I can't reproduce this on an actual iPhone 6/7.
