### ISSUE TITLE
Develop the Footer vanilla component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#356]
_Jeff-Chew created the following on Aug 14:_  

 #### User Story

> As a `[user role below]`:
Developer

> I need to:
utilize a vanilla javascript version of the footer from the IBM.com library

> so that I can:
integrate the ibm.com footer in my application

#### Additional information
 - should utilize the styles package for styling of the component
 
#### Acceptance criteria
 - [ ] Include storybook html story
 - [ ] minimum 80% unit test coverage 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1463_

**Comment by RobertaJHahn** [comment]
@andysherman2121 @jeffchew This sprint 22 issue is still in Review.  Can I close it or should I move it to sprint 23?

**Comment by andysherman2121** [comment]
@RobertaJHahn Move to sprint 23 please. Finishing it up now

**Comment by RobertaJHahn** [comment]
Done
