### ISSUE TITLE
request a way to indicate the active navigation item in Masthead navigation links

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/ibm-dotcom-library#3562]
https://chiefdataoffice.slack.com/archives/C2PLX8GQ6/p1597261757330000?thread_ts=1597248749.329100&cid=C2PLX8GQ6

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/00a00284-71c9-4dca-9ec9-de61a4547e1b)

**Comment by RobertaJHahn** [comment]
Direction from design is needed when the MegaMenu is collapsed.  MyIBM, Profile and Data Privacy should all be handling this navigation the same way.

Turning this issue into an epic.

**Comment by RobertaJHahn** [comment]
Aug 24, 2020 meeting with Keegan:  We need to provide a reactive state capability.  Would like to provide in the Sept release.

Next steps:  Design issue needed on Agile (update the specs), then the follow-on dev issues (full React component first)

**Comment by yellowdragonfly** [comment]
Why is this issue closed?

**Comment by annawen1** [comment]
Hi @yellowdragonfly, we have now included a prop called `selectedMenuItem` to the Masthead component. This prop takes in a string matching the `titleEnglish` value of the L0 item that needs to be rendered with the selected state.

You can see it working here in our storybook: https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-masthead--default

**Comment by yellowdragonfly** [comment]
Anna, thanks for the update. I checked this feature in V1.11.0, it works great. But in smaller screen size when the menu items shrink inside  the hamburg icon, there is no indication which item is active in the hamburg menu. I view this feature as partially implemented so this ticket should remain open.

**Comment by annawen1** [comment]
Hi @yellowdragonfly the menu item should have the selected state styles even in the hamburger menu as shown in screenshot below:

<img width="751" alt="Screen Shot 2020-09-28 at 10 38 45 AM" src="https://user-images.githubusercontent.com/54281166/94446579-d4081400-0176-11eb-8d7d-19a809ee0940.png">

Can you double check on your end? And if you still aren't seeing it can you comment on this ticket with how you are testing?

**Comment by yellowdragonfly** [comment]
@annawen1 Here is our system: https://proxy1.marketplace-test.ibmcloud.com/profile/dataprivacypreferences/welcome/us-en

It doesn't show the active menu in the hamburg. Could you check it out?

**Comment by jeffchew** [comment]
> @annawen1 Here is our system: https://proxy1.marketplace-test.ibmcloud.com/profile/dataprivacypreferences/welcome/us-en
> 
> It doesn't show the active menu in the hamburg. Could you check it out?

Hi @yellowdragonfly , @annawen1 is looking into this. Can you open a new issue though as this is unrelated to this issue?

**Comment by yellowdragonfly** [comment]
@annawen1, on release 1.12.0, with what I did for 1.11.0 -- set selectedMenuItem props to match the titleEnglish value of the L0 item, it no longer works. Is there anything else I need to set?

**Comment by annawen1** [comment]
@yellowdragonfly ah I had made some changes that I noticed affected nav items with no dropdown menu. I did fix that along with the selected item not showing in mobile, but those changes didn't make it into v1.12.0. Is it possible for you to use the canary release (v1.13.0-canary.318685426.0) or revert back to v1.11.0 for now?

**Comment by yellowdragonfly** [comment]
I will stay with V1.11.0. Thank you for your reply!
