### ISSUE TITLE
Component: Mega menu - Menu options are overlapping when quickly switching between the menu drop downs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3567]
## Detailed description

Issue :- Menu options are overlapping when quickly switching between the menu drop downs.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d23a7863-19d1-48c9-82c0-9ba83f43ccc4)

**Comment by annawen1** [comment]
I've tried replicating this on browserstack windows 10 on chrome and firefox with no luck.

**Comment by kennylam** [comment]
I've also tested in FF/Chrome/Edge in native Windows 10 and cannot reproduce. After a session of furiously clicking and trying to break these menus, no luck. This could be a result of performance in Browserstack, which is noticeably slower than non-VM browsers. I suggest closing this until reported again by an actual adopter.

cc: @jeffchew @RobertaJHahn

**Comment by RobertaJHahn** [comment]
@kennylam @annawen1 Seems like an edge case that we should not loose sleep over.  Closing.
