### ISSUE TITLE
Web Components: Some service API calls takes long time to get response

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#3575]
## Detailed description

> Describe in detail the issue you're having.

In Web Components storybook, the masthead menu items takes long time (>5s) to populate. Looking at the Redux logger in local dev env, the cause seems to be `LocaleAPI.getLang()`, which takes >5s to come back with a response.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

A bug.

> Is this issue related to a specific component?

Yes, `LocaleAPI` and `TranslateAPI` in `@carbon/ibmdotcom-services`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Getting faster response.

> What browser are you working in?

Chrome 84.

> What version of the IBM.com Library are you using?

Latest `master`.

**Comment by jeffchew** [comment]
@RobertaJHahn fyi, lining this one up for v1.11.0.
