### ISSUE TITLE
ContentBlockCards - Same height not working

### ISSUE THREAD

**Issue by caiobozato** [carbon-design-system/ibm-dotcom-library#3586]
**This component is used by the Reboot team on the Support Landing page.  The bug fix is needed by the end of the day Friday, Aug 28.**

## Detailed description

> Describe in detail the issue you're having.

The `ContentBlockCards` cards are not getting the same height

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Yes, `ContentBlockCards` but is happening with `CardGroup` too

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The cards should have same height

> What browser are you working in?

Google Chrome

> What version of the IBM.com Library are you using?

1.10.0-alpha.4682

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Support Landing L0 - This should be fixed by EoW, next week visual QA will be done. It's for Reboot team

## Steps to reproduce the issue

1. Go to https://support-page.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/4/index.html
2. Cards don't have the same height

## Additional information

![image](https://user-images.githubusercontent.com/26546511/90409454-8da39d80-e07f-11ea-949f-362d2f1149d6.png)

I already tried to run `yarn update` but didn’t have success.

**Comment by caiobozato** [comment]
@RobertaJHahn @jeffchew I fixed the issue using the `sameHeight` utility: http://support-page-test.mybluemix.net/

But this issue should be left open because none of the components which use `sameHeight` are working as expected on `Next js` template.

@guilhermelMoraes FYI

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes Is this still an issue?  Has it been resolved?

**Comment by RobertaJHahn** [comment]
Slack response from Gui:  Hey, Roberta! Yeah, sure, go ahead and close. It was fixed but probably addressed in another ticket
