### ISSUE TITLE
Masthead | Search autosuggest not working in Firefox

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#359]
_Jeff-Chew created the following on Aug 16:_  

 ### Detailed description

@Kenny-Lam noticed this while testing the masthead locally. Autosuggest currently isn't working in Firefox.

### Steps to reproduce the issue

1. Go to https://ibmdotcom-react.netlify.com in Firefox
2. Activate search and type in a query (minimum 3 characters)
3. Search results not appearing

### Additional information

- Currently the preview isn't there as it's not merged to the main test environment. Will update the ticket once we can reproduce there.
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1473_

**Comment by photodow** [comment]
@jeffchew, @JennySanchez and I wasn't able to duplicate this issue in Firefrox. If you're still having issues, what version of the firefox and the react library are you using?

**Comment by RobertaJHahn** [comment]
Can not be replicated.  Closing
