### ISSUE TITLE
[MM] My IBM maintaining focus when switching to mega menu

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3617]
## Detailed description

> Describe in detail the issue you're having.

If I open the My IBM dropdown, then open one of the mega menus, the My IBM icon does not lose it's focus state.

![MM My IBM focus Aug-18-2020 17-16-37](https://user-images.githubusercontent.com/45692622/90566544-ab9ff980-e176-11ea-901d-08e07b36daa7.gif)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Masthead + mega menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would have assumed clicking on one of the mega menu labels would deselect the My IBM dropdown and it would no longer have an activated focus state

> What browser are you working in?

Chrome
Version 84.0.4147.125 (Official Build) (64-bit)
MacBook pro, osCatalina 10.15.5

> What version of the IBM.com Library are you using?

Latest canary, seen on homepage staging and in storybook

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Click on My IBM icon in masthead (do not select anything else)
2. Click on mega menu
3. See focus on My IBM and mega menu is open
4. etc.

## Additional information

![Screen Shot 2020-08-18 at 5.03.39 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/18c9a6b4-9c10-448d-845e-fb55cc3e64be)

**Comment by RobertaJHahn** [comment]
Praveen and Chetan tested this bug fix.  Looks good.  Can be closed.
