### ISSUE TITLE
Component: Perform Lightbox gap analysis of the code, design and functional specs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#362]
#### User Story

> As a `[user role below]`:
DDS BA

> I need to:
review the design specs, functional specs and code 

> so that I can:
be sure that all are aligned and provide a quality experience for the designers and developers that use the ibm.com Library patterns and components to build their web sites.

#### Additional information

- [Design specs issue #659](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/659)
- [Functional specs issue #683](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/683)
 - [alpha dev issue #706](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/706)

#### Acceptance criteria
 - [x] Gap analysis of alpha code and design & functional specs
 - [ ] If applicable, create and size stories for additional work

**Comment by photodow** [comment]
So I went through and conducted the gap analysis. Stories to be created are as follows...

##### ExpressiveModal
- [ ] Full Width height 100% - margin
- [ ] 2x Grid alignment
   - `sm` padding: 16px
   - `md` `lg` `xlg` `max` padding: 32px
  - `max` ignore grid's additional 8px
- [ ] Position close button
   - `sm` top: 0; right: 0;
   - `md``lg` `xlg` `max` top: 16px; right: 16px;

##### LightboxMediaViewer
- [ ] `sm` `md` clear close button padding-top: 16px;
- [ ] Fix alignment issues
   - Image left aligned, bottom aligned
   - Image max-height: 100%
   - `sm` Image takes up rest of space that content doesn't fill, and as content becomes less image area gets bigger
   - `sm` Image vertical center if height is less than 100% and left aligned
  -  Container needs to vertical center
