### ISSUE TITLE
[MM] Top products & platforms link error

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3620]
**This bug should be retested once the data is updated by Anna.  Task (#3658)**

## Detailed description

The `Top products & platforms` nav label takes me here:
https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html

instead of here:
https://www.ibm.com/products

## Steps to reproduce the issue

1. Go to https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html
2. Click on `Products & Solutions` in the nav
3. Click on `Top products & platforms` in the nav

## Additional information

<img width="354" alt="Screen Shot 2020-08-18 at 4 40 46 PM" src="https://user-images.githubusercontent.com/45607819/90568493-95dc0580-e171-11ea-92c7-ee2321cefc01.png">

**Comment by RobertaJHahn** [comment]
Anna is updating the megamenu data.  This bug should be retested once the data is updated.

**Comment by RobertaJHahn** [comment]
The data update issue is (#3658)

**Comment by annawen1** [comment]
This issue should be fixed in https://github.com/carbon-design-system/ibm-dotcom-library/pull/3668
