### ISSUE TITLE
[MM] Industries link error

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3622]
**This bug should be retested once the data is updated by Anna.  Task (#3658)**

## Detailed description

The `Industries` label takes me here:
https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html

instead of here:
https://www.ibm.com/industries

## Steps to reproduce the issue

1. Go to https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html
2. Click on `Products & Solutions` in the nav
3. Click on `Industries` in the nav

## Additional information

<img width="189" alt="Screen Shot 2020-08-18 at 4 53 12 PM" src="https://user-images.githubusercontent.com/45607819/90569338-531b2d00-e173-11ea-9cf8-73c20ac44ef2.png">

**Comment by RobertaJHahn** [comment]
The data update issue is (#3658)

**Comment by annawen1** [comment]
This issue should be fixed in https://github.com/carbon-design-system/ibm-dotcom-library/pull/3668
