### ISSUE TITLE
[MM] Replace Manufacturing with Oil & Gas

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3623]
**This bug should be retested once the data is updated by Anna.  Task (#3658)**

## Detailed description

On the staging site, the `Manufacturing` label takes you to https://www.ibm.com/industries/manufacturing.

However, the spreadsheet has the label `Oil & gas` in its place with a link that goes to https://www.ibm.com/industries/oil-gas

## Steps to reproduce the issue

1. Go to https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html
2. Click `Products & Solutions` in the nav
3. Click the `Manufacturing` label under the `Industries` section
4. etc.

## Additional information

<img width="267" alt="Screen Shot 2020-08-18 at 5 03 09 PM" src="https://user-images.githubusercontent.com/45607819/90570167-c7a29b80-e174-11ea-9d10-c8a8bd20697e.png">
<img width="1011" alt="Screen Shot 2020-08-18 at 5 03 24 PM" src="https://user-images.githubusercontent.com/45607819/90570170-c8d3c880-e174-11ea-880e-c8180dc74f14.png">

**Comment by RobertaJHahn** [comment]
The data update issue is (#3658)

**Comment by lily-kenney** [comment]
This bug is not valid as manufacturing is the updated one. I've updated the spreadsheet to reflect this change.
