### ISSUE TITLE
Footer Logo/Text loading in dark on the NextJS staging environment

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3642]
## Detailed description

> Describe in detail the issue you're having.

https://ibmdotcom-nextjs-staging.mybluemix.net/

<img width="1670" alt="Screen Shot 2020-08-19 at 11 03 18 AM" src="https://user-images.githubusercontent.com/1641214/90652317-f1f36800-e20b-11ea-93d8-0de34b5846db.png">

Storybook appears to be fine.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
We should investigate this if it's an environment issue or something else.

**Comment by oliviaflory** [comment]
Note: on mobile the hover color for links in the accordion seem off as well.
