### ISSUE TITLE
Locale Modal cannot launch itself in Italian

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/ibm-dotcom-library#3644]
hi, we are using ibm.com react component Locale Modal in the Footer. We noticed that when the current locale is it-it, if Locale Modal is chosen, it crashes and everything goes white. BTW we are still on v1.9.0. Tried on today's new release V1.10.0-rc.0, same result.
Basically Locale Modal cannot launch itself in Italian.

**Adopter:  Data Privacy**

**Comment by yellowdragonfly** [comment]
Here is the link to our app: https://myibm.ibm.com/profile/dataprivacypreferences
Once you are on the site, go to ibm.com footer and use the Locale selector to change the language to Italian. Once the page is in Italian, click on the Locale selector again, the Locale crashes. 
Let me know if you need more information.

**Comment by jeffchew** [comment]
@yellowdragonfly this was a content fix for the italian country list for the Locale Modal. Changes have been pushed up and now appears to be functioning fine.

cc: @ljcarot @RobertaJHahn
