### ISSUE TITLE
[MM] cannot see last item in mobile menu

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3646]
## Detailed description

> Describe in detail the issue you're having.

When browsing the mobile mega menu, I cannot see the last menu item `WebSphere` in the Top Products & Platforms category

[Screen recording](https://ibm.ent.box.com/file/709883372853)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

mega menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Safari
iOS 13.6
iPhone 7

> What version of the IBM.com Library are you using?

Latest canary, seen on Homepage staging environment

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
The details from this issue will be added to (#2661)

**Comment by RobertaJHahn** [comment]
Information transferred to issue (#3661) Closing
