### ISSUE TITLE
[MM] In certain conditions, the menu from Products & Solutions remain even when you navigate to other L0s

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/ibm-dotcom-library#3647]
## Detailed description

> Describe in detail the issue you're having.

When I trigger the Products & Solutions menu and scroll down and then attempt to click on an item (and it causes the menu to jump) and then go on another L0 menu (either Learn & Support or Explore More) - I see the Products & Solutions menu reappear underneath those other 2 L0 menus. This doesn't appear to happen for Services & Consulting and only the other two menus.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Carbon mega menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I wouldn't expect to see the other mega menu for the other L0s to display when I'm not on those L0s.

> What browser are you working in?

Mac, Safari version 13.1.2 (15609.3.5.1.3)

> What version of the IBM.com Library are you using?

The one that's ingested on https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Carbon mega menu + US HP launch, targeted for 8/31

## Steps to reproduce the issue

1. Go to https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html
2. Open up the Products & Solutions mega menu
3. Scroll down to the end of the menu
4. Click on an industry (e.g. Manufacturing). The menu will kind of jump on
5. Click on either "Learn and Support" or "Explore More" - you'll see the Products & Solutions mega menu appear under those two other menus.

## Additional information

Video at: https://ibm.box.com/s/jutc7uferone7bbbdbchbwlasa0j68bw

**Comment by RobertaJHahn** [comment]
@chetankan @Praveen-sr Can you test this is all browsers.  Lily only has Safari and we would like to know all places to make this fix.  This is a high priority.  Will add to the Monday, US meeting agenda.

**Comment by RobertaJHahn** [comment]
Checked by Praveen and Chetan.  Not happening.  Closing.
