### ISSUE TITLE
[MM] IBM logo changing positions in L0 when mobile menu is opened

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3657]
## Detailed description

> Describe in detail the issue you're having.

The IBM logo is changing positions in the L0 when the mobile menu is opened and closed

![MM-logo-jump-Aug-19-2020 18-10-36](https://user-images.githubusercontent.com/45692622/90695046-ad85bd80-e247-11ea-9b65-ae52a205074a.gif)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

L0 + mega menu(?)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Logo should not move.

> What browser are you working in?

Checking for updates
Version 84.0.4147.125 (Official Build) (64-bit)

> What version of the IBM.com Library are you using?

Latest canary, viewed on homepage staging.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Open homepage staging
2. click on hamburger menu
3. close hamburger menu
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by ljcarot** [comment]
I don’t see Ibm logo at all when I click on hamburger menu. I’m on iPhone

**Comment by wonilsuhibm** [comment]
I also observe this on desktop: as you resize the browser window, the logo's position jumps at 1056px wide, then again when the hamburger opens:
![ibm-logo-position](https://user-images.githubusercontent.com/30183447/90775177-89b58c80-e2c6-11ea-967b-3abfd2448fb5.png)

**Comment by RobertaJHahn** [comment]
We would like to get this bug included in v1.10.0.  If it can't get into the release, then it needs to be included in a follow-on patch.
