### ISSUE TITLE
Component: Masthead - On iPhone voice over,  first level of options within the Hamburger are read on second level.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3663]
## Detailed description

Device - On iPhone Voice over 

URL - https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-masthead--default

Issue :- After expanding the hamburger menu - from within the Hamburger, when Second level menu options are available, Screen reader still reads the First level options. This would confuse the screen reader user.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/98a766e5-9837-407c-a88f-5e0158d50c06)

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu  Ram re tested this on staging, issue is not fixed.
After expanding the level 0 menus, the Level One options are displayed. Along with that the Level 0 options are also read by the screen reader but those are not visually present.

**Comment by RobertaJHahn** [comment]
This was checked by Ram.  It is still not working.
