### ISSUE TITLE
Ability to customize IBM 8-bar logo on the U.S. home page 

### ISSUE THREAD

**Issue by ilrina** [carbon-design-system/ibm-dotcom-library#3666]
### The problem
The US home page team has a local access to the IBM 8-bar logo file in the Masthead and has been changing the logo in response to significant cultural moments. For example: Rainbow logo for the Pride month, Pan-African logo in response to the Black Lives Matter movement, Magenta logo for the Breast Cancer Awareness month. 

Our metrics show a significant amount of clicks on the IBM logo on the home page that result in reloading the home page. To mitigate this frustrating experience, we are using the tool tips pattern to add a message. The Pride Month message contained a link to the Pride page.

![Screen Shot 2020-08-20 at 10 17 49 AM](https://user-images.githubusercontent.com/6701695/90791595-66470d80-e2d7-11ea-8eb4-63c7ad4de3bd.png)

### The solution
The Team would like to retain these options within Carbon:
-Ability to replace the logo file
-Ability to add the tool tip overlay with a message
-Ability to have a contextual link in the tool tip

**Comment by RobertaJHahn** [comment]
I have consolidated this request into a single epic (#3667).  The Functional spec work has been included in sprint 20-19.  Closing this issue.
