### ISSUE TITLE
[CardGroup] Add 1px border to touching cards 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#3675]
## Summary 

![image](https://user-images.githubusercontent.com/15144993/90815809-445e8280-e2f9-11ea-9a6c-2741640eb274.png)

### The problem

Current [card groups]( https://ibmdotcom-react.mybluemix.net/?path=/story/components-cardgroup--default
) has 1px gutter between cards, which is too subtle. We need a bit more visual definition. Also this would align us with the Carbon gatsby card group's implementation.

![image](https://user-images.githubusercontent.com/15144993/90815593-ed58ad80-e2f8-11ea-9125-e4a4ede8c678.png)

Carbon website & IDL site https://www.ibm.com/design/language/resources 
![image](https://user-images.githubusercontent.com/15144993/90815527-d619c000-e2f8-11ea-9185-6f85b31dd95d.png)

### The solution

@photodow and I discussed the feasibility of this. We want to avoid every nth-child to make sure the solution is scalable. Looks like there is a method that could work.  

![image](https://user-images.githubusercontent.com/15144993/90815954-7bcd2f00-e2f9-11ea-977a-cfb0f6893085.png)

**Comment by photodow** [comment]
Here is a prototype I put together while talking through this with Shixie.

https://codesandbox.io/s/festive-davinci-1pfn6?file=/src/styles.scss
