### ISSUE TITLE
[MM] Update some of the mega menu labels + links

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/ibm-dotcom-library#3678]
**This work should begin after the bugs are fixed.  The target to finish all content updates is the end of this sprint, Friday Aug 28.**

## Detailed description

> Describe in detail the issue you're having.

This story is to update some of the mega menu labels + links per requests from various BUs in anticipation of the mega menu launch.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

New requests

> Is this issue related to a specific component?

Carbon mega menu

## Changes
The changes are outlined below. They have all been incorporated into the spreadsheet: https://ibm.box.com/s/z6juz774mcrpi0wzoapqutzit5jup3b0 (carbon tab)

**1. Under Products & Solutions > Industries**
Change Oil & Gas to Manufacturing with URL https://www.ibm.com/industries/manufacturing

**2. Under Services & Consulting > Talent & Transformation**
Update the 'talent acquisition' URL to https://www.ibm.com/talent-management/talent-acquisition

**3. Under Services & Consulting**
Move the ‘Hybrid multicloud services’ category above ‘Talent & transformation’ category 

**4. Under Explore more**
Change the ‘About IBM’ URL to https://www.ibm.com/ibm/us/en/

**Comment by annawen1** [comment]
@amandafbooth 

Services & Consulting > Talent & Transformation > Talent acquisition already links to https://www.ibm.com/talent-management/talent-acquisition?lnk=hpmsc_buta&lnk2=learn
