### ISSUE TITLE
[MM] Link error for Customer service

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3681]
**This work should begin after the bugs are fixed.  The target to finish all content updates is the end of this sprint, Friday Aug 28.**

## Detailed description

The `Customer service` tab takes you to ibm.com/watson when it should take you to https://www.ibm.com/watson/ai-customer-service (which currently redirects to https://www.ibm.com/cloud/ai/customer-service)

## Steps to reproduce the issue

1. Click `Products & Solutions`
2. Look under the `Artificial intelligence` section
3. Click on the `Customer service` label

## Additional information

<img width="265" alt="Screen Shot 2020-08-21 at 9 54 24 AM" src="https://user-images.githubusercontent.com/45607819/90903990-517c7f80-e394-11ea-86e6-dfe250dd5322.png">

**Comment by annawen1** [comment]
@amandafbooth currently `Customer service` is linked to https://www.ibm.com/watson/ai-customer-service?lnk=hpmps_buai&lnk2=learn. Seems like the parameters attached are causing problems...will remove `?lnk=hpmps_buai&lnk2=learn`
