### ISSUE TITLE
[MM] The Blockchain sections don't match

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3682]
**This work should begin after the bugs are fixed.  The target to finish all content updates is the end of this sprint, Friday Aug 28.**

## Detailed description

The categories and destinations of the `Blockchain` labels do not match the spreadsheet

## Steps to reproduce the issue

1. Click `Products & Solutions`
2. Look under the Blockchain section
3. Look at the spreadsheet: https://ibm.ent.box.com/services/box_for_office_online/4881/684998200276/c0b568.565f9c8e405e635bbf0634953be5c3e7d2dbc8b97a7997fd277f58a0a97c6e32?node_type=file

## Additional information
<img width="253" alt="Screen Shot 2020-08-21 at 10 01 55 AM" src="https://user-images.githubusercontent.com/45607819/90905177-6a396500-e395-11ea-944a-493883e2d5a4.png">
<img width="1061" alt="Screen Shot 2020-08-21 at 10 02 14 AM" src="https://user-images.githubusercontent.com/45607819/90905187-6c9bbf00-e395-11ea-8ec6-a36aad174b2f.png">

I don't think the newest version of this in the spreadsheet went through a content review

**Comment by lily-kenney** [comment]
FYI... I've assigned this to myself for now. I'm working with Keegan to determine what the labels should be for Blockchain.

**Comment by ljcarot** [comment]
Thx @lily-kenney I've added "Reboot owned" label too so we know DDS doesn't need to change anything yet.

**Comment by annawen1** [comment]
Putting https://github.com/carbon-design-system/ibm-dotcom-library/issues/3674 on hold until the data for blockchain has been confirmed here

CC: @lily-kenney

**Comment by lily-kenney** [comment]
@annawen1 - updated the ticket and spreadsheet with what we want to launch with.
