### ISSUE TITLE
[MM] Link error for Compliance

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3686]
**This work should begin after the bugs are fixed.  The target to finish all content updates is the end of this sprint, Friday Aug 28.**

## Detailed description

The `Compliance` label goes to https://www.ibm.com/security but in the spreadsheet goes to https://www.ibm.com/security/compliance

## Steps to reproduce the issue

1. Click `Products & Solutions`
2. Click `Compliance` label under `Security` section

**Comment by annawen1** [comment]
@amandafbooth `Compliance` actually is linked to https://www.ibm.com/security/compliance?lnk=hpmps_buse&lnk2=learn. If you hit that url directly in your browser, notice that it redirects to https://www.ibm.com/security instead. Seems like there is some redirect rule put in place.

**Comment by ljcarot** [comment]
@lily-kenney fyi, can you please help investigate? Thx

**Comment by lily-kenney** [comment]
@amandafbooth and @annawen1  - I'm looking into this right now.

**Comment by lily-kenney** [comment]
@annawen1 - please remove the compliance link. So it should only have:


Security |   | https://www.ibm.com/security
-- | -- | --
  | Data security | https://www.ibm.com/security/data-security
  | Identity & access management | https://www.ibm.com/security/identity-access-management
  | Security information & event management | https://www.ibm.com/security/security-intelligence
  | View all Security products | https://www.ibm.com/us-en/products/category/technology/security
