### ISSUE TITLE
[MM] Link error for View all Supply chain products

### ISSUE THREAD

**Issue by amandafbooth** [carbon-design-system/ibm-dotcom-library#3687]
**This work should begin after the bugs are fixed.  The target to finish all content updates is the end of this sprint, Friday Aug 28.**

## Detailed description

The link from `View all Supply chain products` shows up as no results, probably because the end part of the link, `?lnk=hpmps_busc&lnk2=learn`, registered as part of the supply chain management tag. When I removed that part from the link, it worked.

## Steps to reproduce the issue

1. Click `Products & Solutions`
2. Click `View all Supply chain products` label in the `Supply chain` section
3. Delete the following from the url and refresh: `?lnk=hpmps_busc&lnk2=learn

## Additional information

<img width="1219" alt="Screen Shot 2020-08-21 at 11 20 01 AM" src="https://user-images.githubusercontent.com/45607819/90912529-6232f280-e3a0-11ea-859d-c15a52f8ad70.png">
<img width="1045" alt="Screen Shot 2020-08-21 at 11 20 24 AM" src="https://user-images.githubusercontent.com/45607819/90912533-63641f80-e3a0-11ea-85e2-d3bba2d69527.png">

**Comment by annawen1** [comment]
Removing the `?lnk=hpmps_busc&lnk2=learn` from `https://www.ibm.com/us-en/products/categories?businessTopics[0][0]=cat.topic:SupplyChainManagement?lnk=hpmps_busc&lnk2=learn`
