### ISSUE TITLE
[TOC] tablet, mobile interaction

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/ibm-dotcom-library#3726]
TOC for tablet and mobile version needs to be all clickable.  This component is used in the Support page.

## Detailed description

> Describe in detail the issue you're having.

Text is only clickable things in current tablet and mobile. All box needs to be clickable.

![image](https://user-images.githubusercontent.com/67110948/91230101-f1217100-e6f8-11ea-8d6f-05ec16f2ccef.png)
![image](https://user-images.githubusercontent.com/67110948/91230245-2af27780-e6f9-11ea-9550-f967b9508b84.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

TOC

> What did you expect to happen? What happened instead? What would you like to
> see changed?

All box needs to be clickable and it shows all of the options when user taps it. 
 
![image](https://user-images.githubusercontent.com/67110948/91229917-9e47b980-e6f8-11ea-8872-8570e8fc882d.png)
![image](https://user-images.githubusercontent.com/67110948/91229930-a3a50400-e6f8-11ea-8680-376c8cd6c34a.png)

> What browser are you working in?

Tablet and Mobile version

> What version of the IBM.com Library are you using?

https://ibmdotcom-react.mybluemix.net/iframe.html?id=components-table-of-contents--manually-define-menu-items

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This is part of new support landing page (Launch date: about Sept 7)

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes Jeff would like you to fix the component and then apply the canary version to the support page.  I have assigned the work to sprint 20-18 (the sprint beginning next Monday).  Based on the schedule, this component has to be fixed some time during the week of Aug 31.
