### ISSUE TITLE
Outstanding feedback from Masthead pull request

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#373]
_Jeff-Chew created the following on Aug 28:_  

 

### Detailed description

The Masthead pull request was getting fairly large and didn't want to delay the 0.3.0 release any further. This ticket is to track addressing of outstanding feedback reported here:
https://github.com/carbon-design-system/ibm-dotcom-library/pull/50

### Additional information

- @Kenny-Lam please provide any additional details

#### Acceptance Criteria
 - [ ] Additional stories are created for the unresolved feedback documented in the PR.
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1538_

**Comment by kennylam** [comment]
@jeffchew @RobertaJHahn This can be closed. The only remaining stories would be L1/L2, which are not yet ready for development (we're currently working with the Drupal team to get access to L1 from their end). The L1 is currently behind a feature flag and is basically FPO. Can create new stories for those outstanding features when ready for dev.
