### ISSUE TITLE
Component: Mega Menu - scrolling issue on second level menu options

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3730]
## Detailed description

On iPhone - Safari & chrome

URL : https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-masthead--default

Issue : when user clicks on level 1 option and scrolls down the options and goes to level 2, user is navigated to end of level 2 options. 

## Steps to reproduce the issue

1. Open Mega menu on Mobile and click on hamburger menu
2. Click on Product& Supply and scroll down  
3. Click on supply chain option 
4. scroll is at the bottom of the page.

## Additional information

![Megamenu2.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6cf4258c-dfd4-4aac-9d24-32958cf6718c)

**Comment by RobertaJHahn** [comment]
@annawen1 This is the bug we talked about in the meeting with Praveen and Chetan earlier today.

cc:  @jeffchew @ljcarot
