### ISSUE TITLE
[HP] [MM] multiple menus open at once

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3731]
## Detailed description

> Describe in detail the issue you're having.

Click My IBM (don’t close)
Click any mega menu link (don’t close)
Then click any other mega menu link

My IBM icon maintains focus (known issue: #3617 ) if user clicks and doesn't select anything in the dropdown menu, then clicks on any mega menu item.

If the user clicks a second, or third mega menu they will see multiple menus overlaid on top of each other

**My IBM focus, single menu**
<img width="1572" alt="Screen Shot 2020-08-26 at 9 58 41 AM" src="https://user-images.githubusercontent.com/45692622/91313662-9f71f880-e783-11ea-8f32-7c0fc0521353.png">

**Double menu**
<img width="1572" alt="Screen Shot 2020-08-26 at 9 42 55 AM" src="https://user-images.githubusercontent.com/45692622/91313693-a7ca3380-e783-11ea-93e0-4f2d18a1f17e.png">

**Triple menu**
<img width="1573" alt="Screen Shot 2020-08-26 at 9 56 38 AM" src="https://user-images.githubusercontent.com/45692622/91313710-ae58ab00-e783-11ea-8bfe-6a736955a816.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

mega menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Only one menu should be open at a time

> What browser are you working in?

Chrome
Version 85.0.4183.83 (Official Build) (64-bit)

Safari
Version 13.1.1 (15609.2.9.1.2)

> What version of the IBM.com Library are you using?

Latest release that was integrated with Homepage (Aug 26)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Click My IBM (don’t close)
2. Click any mega menu link (don’t close)
3. Then click any other mega menu link
4. Click another mega menu

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
@annawen1 This is the new bug created by Olivia.  I think she made you aware of it.  I don't have a severity yet, but it seems important so I am moving into the current sprint.

**Comment by RobertaJHahn** [comment]
We will identify the root cause and then patch with dates TBD.

**Comment by RobertaJHahn** [comment]
Praveen and Chetan tested this bug fix.  Looks good.  Can be closed.
