### ISSUE TITLE
Component: Mega Menu (Mobile) - scrolling issue on Products & Solutions only

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library#3732]
When scrolling to bottom of Products & Solutions list in Portrait mode, the scroll bar won't stay at the very bottom, instead it moves up slightly.  It means I can't see the last 3 links on the list.

Work around is shifting to Landscape mode and I can scroll to bottom.

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue? Bug

> Is this issue related to a specific component? Mega menu on Mobile

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expect to scroll to bottom of list and stay there

> What browser are you working in?

> What version of the IBM.com Library are you using? 1.10.0.rc-2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one - go to HP Staging URL https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html on iPhone Xr
2. Step two - click Hamburger menu and select Products & Solutions
3. Step three - scroll to bottom of list, note last item should be 'View all products', release fingertip action from scroll and notice the list moves back up and cuts off the last 3 options.
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by annawen1** [comment]
@ljcarot which browser do you see this issue happening? I'm not able to replicate on my iphone 8 currently, will check on browserstack

**Comment by ljcarot** [comment]
Both Chrome and Safari
