### ISSUE TITLE
[MM]: When clicking on empty space, megamenu does not close causing stacking

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/ibm-dotcom-library#3758]
## Detailed description

> Describe in detail the issue you're having.

When clicking on any empty area not associated with a link on the megamenu, the megamenu opens and closes and then remains stuck open. When user then clicks on another L0 nav item, the menu stacks on top.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

MegaMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The menu should not close when user clicks on the empty space and when user opens another menu, the previous one should close.

> What browser are you working in?

Chrome, Safari, FireFox

> What version of the IBM.com Library are you using?

v1.10.0

## Steps to reproduce the issue

1. Click on any L0 nav item (ie, Products & Solutions)
2. Click on any empty space within the megamenu
3. Click on another L0 nav item (ie. Services & Consulting)
4. See how the menus stack

## Additional information

![Aug-27-2020 09-19-59](https://user-images.githubusercontent.com/54281166/91447917-394ea980-e847-11ea-86d4-1764f1fcd258.gif)

**Comment by oliviaflory** [comment]
hmm, when I was discussing functional specs with James I didn't want it to close if the user accidentally clicked on an empty space within the background of the mega menu container. 

But the overlapping action is a problem because clicking on an empty space seems to lose the focus and then the menus don't realize one is open.

**Comment by wonilsuhibm** [comment]
Agreed—even when clicking in the large empty space on either side when the browser is large, it should not close as long as the click happens inside the megamenu container.

**Comment by RobertaJHahn** [comment]
Praveen and Chetan tested this bug fix.  Looks good.  Can be closed.
