### ISSUE TITLE
React: Expose hooks for Masthead search to enable switching between ibm.com and scoped search

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3766]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Masthead` hooks

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic for the Design and Functional specs information**
- Prod QA testing issue (#3872)

#### Acceptance criteria
- [ ] Built as a pure React component/variant
- [ ] Include README for the react component and corresponding styles
- [ ] Add any necessary stable selectors
- [ ] Create codesandbox example under `/packages/react/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by RobertaJHahn** [comment]
@jeffchew Here is the template for the KC dev MH feature request.  I have added review of this issue to Monday's engineering meeting agenda for a sizing.  We should also talk about whether the Prod QA team can test this feature.  I did not create that issue.

**Comment by jeffchew** [comment]
From the epic:
```
For certain pages, KC needs to switch the masthead search for KC search, rather the ibm.com one.
We would need:
- a hook for keyboard event (user types a phrase)
- a hook when search is launched (icon click/enter/whatever the masthead considers as a search action)
- able to switch between ibm.com and kc search based on a prop
```

We will need to configure the search redirect to go to another location (right now I think it is hardcoded to go to `ibm.com/search`. The other thing is to be able to configure the typeahead functionality.
