### ISSUE TITLE
Styles Package: Distributed file sizes are too large

### ISSUE THREAD

**Issue by KaiWedekind** [carbon-design-system/ibm-dotcom-library#3809]
## Styles Package: Distributed file sizes are too large

> Describe in detail the issue you're having.

The bundled file sizes for ibm-dotcom-styles.css and ibm-dotcom-styles.min.css are too large.
I have build the files by running `yarn build` and also checked the versions in the node_modules when installing the package, it's the same.

- ibm-dotcom-styles.css [19,8 MB]
- ibm-dotcom-styles.min.css [13,6 MB]

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected a smaller file size.
From my investigation I found that the component modules are imported multiple times and this created css duplicates in the bundled css files.

> What version of the IBM.com Library are you using?

1.10.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM /mysupport experience

## Steps to reproduce the issue

1. Go into the styles package
2. Run `yarn build` or `npm run build`
3. Check the file sizes in dist folder

## Additional information

If possible I'd like to see an example of a gulp task where I can just bundle the css of a specific component.

**Comment by asudoh** [comment]
Hi @KaiWedekind thank you for reporting! You are right that our CSS bundle looks big at a glance:

```shell
[~/git/ibm-dotcom-library/packages/styles/dist]% ls -l
total 65512
drwx------   4 asudoh  staff       128 Aug 31 08:04 ./
drwx------  18 asudoh  staff       576 Aug 31 08:39 ../
-rw-------   1 asudoh  staff  19902563 Jul 30 10:27 ibm-dotcom-styles.css
-rw-------   1 asudoh  staff  13634729 Jul 30 10:27 ibm-dotcom-styles.min.css
```

It's the size _before_ web server typically compresses the content before sending it over wire. If we look at after-compressed size, it's around 445K (that looks normal from my perspective for "all-in-one" bundle):

```shell
[~/git/ibm-dotcom-library/packages/styles/dist]% gzip -c ibm-dotcom-styles.min.css | wc
    1625   10990  445136
```

> From my investigation I found that the component modules are imported multiple times and this created css duplicates in the bundled css files.

This is an interesting point. If it's actually happening we need to fix it. Carbon Design System, that our library here is based on, has [a mechanism to de-dupe those](https://github.com/carbon-design-system/carbon/blob/v10.17.0/packages/import-once/scss/import-once.scss), and from my glance at our codebase we are using it, too ([example](https://github.com/carbon-design-system/ibm-dotcom-library/blob/v1.10.0/packages/styles/scss/components/buttongroup/_buttongroup.scss#L62-L64)).

That said, please feel free to speak up if you have any specific CSS code that you think should be de-duped. Thanks!

**Comment by KaiWedekind** [comment]
Hi @asudoh, thank you for your response.

When I search for `.bx--grid {` in `ibm-dotcom-styles.css` I get 1221 results.

![image](https://user-images.githubusercontent.com/12070900/91842225-f67c3f80-ec53-11ea-8832-505ec7e35a49.png)

This code fragment appears more than 400 times in the file, and that's only for `.bx--grid`
![image](https://user-images.githubusercontent.com/12070900/91842330-24fa1a80-ec54-11ea-84b0-b8acad28879c.png)

**Comment by asudoh** [comment]
I see thank you for the details @KaiWedekind, let us take a look.
