### ISSUE TITLE
Update the design specs to indicate the active navigation item in Masthead navigation links

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3821]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the Masthead design specs

> so that I can:
correctly change the Masthead component 

#### Additional Information
-  [Masthead component:  Agile epic #3562 

#### Acceptance Criteria
- [ ] A Sketch file is updated with the `Masthead` design and specs
- [ ] The updated design specs and pdf version are added to the Box folder 
- [ ] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by larahanlon2** [comment]
Hey @wonilsuhibm I updated the spec file with L0 nav states. Also re-added an artboard showing the hamburger menu active nav state on mobile. Can you take a look and let me know if this is what you needed? Thanks!

**PDF is here:** https://ibm.box.com/s/gmvjidq4uj73i6msuqhkjqfw2kre3g1g
**Sketch file is here:** https://ibm.box.com/s/5urb46tm7y10j98qhh2x8bkpntccs6qj

**Comment by wonilsuhibm** [comment]
@larahanlon2 This looks good. Thank you! @RobertaJHahn the specs have been updated.
