### ISSUE TITLE
Masthead L0:  Visual QA of the active links navigation feature request

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3828]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Masthead L0`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (#3826 )
- [Storybook link](TBD)

 #### Tasks
Ensure the `Masthead L0` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by annawen1** [comment]
@larahanlon2 The development of this feature has been merged. You should be able to see the changes in 
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-dotcom-shell--default 
or
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default

There is a `selected menu item (selectedMenuItem)` knob that you can use to see how the `selected` state looks for different menu items
