### ISSUE TITLE
Running `yarn test:unit` in web components ends with exit 134

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3836]
## Detailed description

> Describe in detail the issue you're having.

Either running `yarn test:unit` or running specifically `yarn gulp test:unit` under `/packages/web-components` causes an exit 134 signal even if tests are successful:

<img width="967" alt="Screen Shot 2020-09-01 at 4 43 07 PM" src="https://user-images.githubusercontent.com/1641214/91904844-9dbc9f00-ec73-11ea-9fce-41e7b05a86af.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Unit tests in web components

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Properly signal exit 0 after successful unit test run

> What browser are you working in?

Terminal

> What version of the IBM.com Library are you using?

Canary

## Steps to reproduce the issue

1. Navigate to `/packages/web-components`
2. run `yarn test:unit`

## Additional information

- This is blocking the preflight checks for publishing

**Comment by asudoh** [comment]
Closer reports can be found at 3511 in karma-runner/karma and 10037 in webpack/webpack. I cannot reproduce the issue in my env. From 10037 in webpack/webpack, some possibilities are:

* Temporarily downgrading Node (Less than `v12.16.2`)
* Ensuring `chokidar`/`fsevents` libraries are up-to-date (in the version range of other dependencies)

**Comment by jeffchew** [comment]
Confirmed that downgrading to node `v12.16.1 ` works. I'm wondering if there's any documentation we should add in the meantime so that other devs don't run into this issue? We should also make sure any CIs are not configured to use that version of node (I don't think they are at the moment).

**Comment by jeffchew** [comment]
@RobertaJHahn removing this from the release since this is documentation.
