### ISSUE TITLE
Web Component: Feature card - image appears to be shrunk on mobile view

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3842]
## Detailed description
On iPhone & Android phones

Issue: Feature card - image appears to be shrunk on mobile view

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c2646562-d88f-4e34-855a-33d26d1bcabd)

**Comment by jeffchew** [comment]
@RobertaJHahn this has already been fixed, closing.
