### ISSUE TITLE
Learn Page - User clicks on masthead menu options from bottom of the page, page resets to top of the page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3847]
## Detailed description

Issue: When user clicks on masthead menu options from bottom of the page, once he closes the menu option, user is directed to top of the page

## Additional information

![LearnPage.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/af727b5f-b8a3-4abb-828c-451c5c5098c7)

**Comment by IgnacioBecerra** [comment]
I can't seem to reproduce the bug, might be fixed already.

**Comment by ljcarot** [comment]
I agree with you @IgnacioBecerra .  It appears to be fixed.  I'll close.  Thx for checking.
