### ISSUE TITLE
Analytics: Add event triggers for Masthead

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#389]
_Jeff-Chew created the following on Sep 06:_  

 

#### User Story

> As a `[user role below]`:
IBM Data Analyst

> I need to:
have dynamic event triggers from the IBM.com Library's Masthead

> so that I can:
track dynamic events within the Masthead in my analytics tool

#### Additional information

 - http://ibmdev.webmaster.ibm.com/v18/metrics/
- Will need more details on what events need to be triggered from Juan Leon and team

#### Acceptance criteria
 - [ ] Event triggers added to the Masthead per specs provided by Juan Leon's team (https://ibm.ent.box.com/s/jw44u3vh2cxg0exgjwthvk03do79iki4)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1601_

**Comment by jeffchew** [comment]
_On Sep 30, Anna-Wen commented:_
After speaking to Juan, it seems he is tracking click interactions for the masthead. He only wants to track hover on L0/L1 items that expose a dropdown. So when users hover on those items but don't click on any dropdown items it might indicate that the menu items not clear enough. However our current masthead does not support dropdown on hover - only on click.

@hahnrob @Jeff-Chew thinking of moving this back to Backlog until we have hover implemented

**Comment by wonilsuhibm** [comment]
@jeffchew @RobertaJHahn There is hover state where the menu items change bg color, but there won't be any dropdown opening on hover. So no tracking hover is fine. Does this help?

**Comment by RobertaJHahn** [comment]
@jeffchew Decision regarding hover tracking is made by Wonil.  Looks like a small update.  Just need to decide what sprint to put the work in.

**Comment by jeffchew** [comment]
This doesn't sound like behavior that needs to be tracked.

**Comment by RobertaJHahn** [comment]
Removed sizing.  Closing this issue.
