### ISSUE TITLE
Expressive design kit – white theme

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#3893]
#### User Story

> As a `[user role below]`:

DDS designer
> I need to:

update the expressive design kit
> so that:

designers have a kit that is aligned with the expressive theme code
#### Additional information
Follow instructions from box document

High level tasks
- [x] Update type styles
- [x] Update type token values
- [x] Adjust height of components to accommodate label size increase
- [x] Check components against storybook and make adjustments

#### Acceptance criteria
 - [x] All updates have been made
 - [x] Reviewed by Olivia
 - [x] Uploaded to Box

**Comment by jacobottesen-dgc** [comment]
Expressive white theme kit can be viewed here: https://ibm.box.com/s/8m8bntkcqhsxktktx94gqzyxdseq0y4l

Currently being reviewed by Olivia.

**Comment by oliviaflory** [comment]
Looks great @jacobottesen-dgc, closing this issue
