### ISSUE TITLE
Web component: Masthead - search bar does not show autocomplete suggestions.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3894]
## Detailed description

Issue: Masthead - On search bar, when user enters a keyword it does not show autocomplete suggestions.

Note: This scenario is working fine on react version.

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7d0e2fad-b514-4488-9943-50395148618e)

Expected:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c4dfc6e1-8b17-4167-8e72-6aab272e26a0)

**Comment by jeffchew** [comment]
@asudoh would you be able to take a look?
