### ISSUE TITLE
React: Promo banner (behind feature flag)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3928]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create the `Promo banner`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic for the Design and Functional specs information**
- Prod QA testing issue (#3952)
- Feature flag documentation: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/docs/feature-flags.md

<img width="1585" alt="Screen Shot 2020-09-11 at 5 12 16 PM" src="https://user-images.githubusercontent.com/1641214/92973343-006f2100-f452-11ea-9371-2650ec47eb85.png">

#### Acceptance criteria
- [x] Built as a pure React component/variant
- [x] Build behind a feature flag
- [x] Include README for the react component and corresponding styles
- [x] Add any necessary stable selectors
- [x] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by guilhermelMoraes** [comment]
<img width="1005" alt="Screen Shot 2020-09-14 at 10 06 57" src="https://user-images.githubusercontent.com/42848561/93089695-0e9b8800-f672-11ea-94fe-4c8c143dad12.png">

@jeffchew this was achieved by passing down an SVG to the `heading` prop of `ContentItemHorizontal`. The difference between the one in the Support page L0 and the one available in our library is the spacing between the copy and the CTA. Should we discuss with the team about creating a new pattern from scratch or just add a new variation to the `ContentItemHorizontal`?

**Comment by jeffchew** [comment]
Yes, good idea, I think we can probably have this conco in a slack thread in the engineering channel.

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes I just created the Prod QA testing issue (#3952).  You can include the comment on that issue when you are finished.
