### ISSUE TITLE
JavaScript error in masthead

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#3934]
## Detailed description

> Describe in detail the issue you're having.

Saw JavaScript error working with masthead:

![image](https://user-images.githubusercontent.com/1259051/93072129-f2243d80-f6bb-11ea-9439-6f6e7e5e60b8.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

A bug.

> Is this issue related to a specific component?

Yes, `<dds-masthead-logo>`, `<dds-masthead-button>` and `<dds-masthead-global-bar>`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the error doesn't happen.

> What browser are you working in?

Safari `13.1.2`

> What version of the IBM.com Library are you using?

Latest `master`

**Comment by jeffchew** [comment]
@asudoh how do I replicate the issue?

**Comment by asudoh** [comment]
@jeffchew Simply accessing masthead with the specific browser reproduced the issue. If you see otherwise probably some other factor is in play.
