### ISSUE TITLE
Pattern: rich overview, visual design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#394]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As a user of IBM.com, I need a way to understand the benefits and value of the product / solution / offering presented on the page quickly through text and media such as video so that I can make a decision on whether I should continue with the page or not.

### Notes
This is a pattern that is not clearly defined from our past work.

### Acceptance criteria
- [ ] Design has been produced
- [ ] Design has been approved by DGC design leadership
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1609_

**Comment by larahanlon2** [comment]
This is old work and no longer relevant as per new pattern ontology. Closing.
