### ISSUE TITLE
NextJS page - The footer links are stacked on top of one another.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3941]
## Detailed description

**Jeff would like this fix included in the v1.11.0rc scheduled for Wednesday, Sept 16.**

Issue: The footer links (Contact IBM, Privacy, Terms of use, Accessibility & Cookie preferences) are stacked on top of one another.

Expected : The links must be arranged column wise. 

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e3aedff0-c26c-4865-9bd3-4ceb71fbc7ff)

Expected :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4af2a0ce-cd3d-4a49-aaa6-d35dd3464572)

**Comment by jeffchew** [comment]
Turned out that the styles package was not published for some reason. @andysherman2121 and I did a manual publish of the styles package, though we will need to do another `rc` release for the other packages to reference the proper styles package.

**Comment by jeffchew** [comment]
@Praveen-sr this is ready for retest on https://ibmdotcom-nextjs-staging.mybluemix.net.

**Comment by Praveen-sr** [comment]
@jeffchew Thanks, re tested this on nextJS working fine now.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/827d7e5b-78c7-44c5-b8c7-ef54ce138796)
