### ISSUE TITLE
Navigation on scroll doesn't open menu items

### ISSUE THREAD

**Issue by dallashudgens** [carbon-design-system/ibm-dotcom-library#3961]
## Detailed description

When you scroll down the page, the navigation becomes sticky. If the user tries to click one of the menu items, it doesn't open. Instead, it jumps you to the top of the screen, and doesn't open the list of menu items. 

I believe it might be an issue with the masthead navigation component. 

I expected to be able to open the navigation menus no matter where scrolled on the page. 

I mainly use Chrome. I haven't tried this in firefox.

This specific issue is occuring with the new Support Landing page design. I can attach a video of the [behavior](https://ibm.box.com/s/u0x4qyx1kailkzx5k1m754hgf2j5zqdq)

## Steps to reproduce the issue

1. Go to http://support-page-test.mybluemix.net/
2. Scroll down the page
3. Click on one of the menu items with children (say Documentation)
4. The page will jump to the top

## Additional information

- [Video of the experience](https://ibm.box.com/s/u0x4qyx1kailkzx5k1m754hgf2j5zqdq)

**Comment by asudoh** [comment]
It looks as though the link `href` is running instead of [the code to expand the menu](https://github.com/carbon-design-system/ibm-dotcom-library/blob/v1.9.0/packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js#L81-L85). #3890 contains code to disable the link `href`. Wondering if it solves this issue. CC @jeffchew @annawen1

**Comment by asudoh** [comment]
@annawen1 confirmed that #3890 addresses this issue (thanks!). @dallashudgens Would it be possible for you to try [`v1.11.0-rc.0` release](https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.11.0-rc.0)? Thanks!

**Comment by RobertaJHahn** [comment]
Anna will ask Gui to use the canary version as mentioned.  Then will close.

**Comment by annawen1** [comment]
Spoke to @guilhermelMoraes, the [test page](http://support-page-test.mybluemix.net/) is using the latest canary version and the issue has been resolved. Closing ticket
