### ISSUE TITLE
Search bar appearing on left side of v18 L0 on Watson Works page

### ISSUE THREAD

**Issue by elliotttrice** [carbon-design-system/ibm-dotcom-library#3962]
## Detailed description

> Describe in detail the issue you're having.
On https://www.ibm.com/watson/watson-works, Search flashes on top of Products and Solution label on left side

> Is this a feature request (new component, new icon), a bug, or a general
> issue? Bug

> Is this issue related to a specific component? masthead v18

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in? 85

> What version of the IBM.com Library are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. See video below

## Additional information

- [Video of bug](https://ibm.ent.box.com/file/719908166186)

**Comment by ljcarot** [comment]
@elliotttrice We've investigated and it appears to be something related to how Watson Works has added the L0 to their page/site.  It would be helpful if you have a contact for that segment in Drupal and we can pass this bug to them.
