### ISSUE TITLE
Web component: Card - With inverse enabled, on hover background changes to g10/white.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3966]
## Detailed description

Issue: On Card - With "inverse" option enabled, hover on the card,  background changes to g10/white.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d2d7210e-7ecb-450a-854a-3bab8da39bef)

Expected:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/12162358-d314-4473-8188-50d13bdb61f6)

**Comment by ariellalgilmore** [comment]
@RobertaJHahn this has been fixed
