### ISSUE TITLE
Footer: - Select Geographic area link, getting a dotted line visual focus when we reaches to the mentioned element.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3967]
## Detailed description

Issue: We are getting a dotted line visual focus when we reaches to the mentioned element.

Expected :  Provide thick and strong visual focus 1. If, Visual Focus Indicator with 3 CSS px stroke then provide a sufficient contrast that is equal to 3:1.  2. Visual focus indicator for a link that is a 1 CSS px then provide a sufficient contrast greater than 4.5:1 
For more information please find the below link, https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum) 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6ada2b14-152d-45c2-8b09-d45ba2466edc)

**Comment by RobertaJHahn** [comment]
@Praveen-sr What environment is this bug found in?

**Comment by Praveen-sr** [comment]
@RobertaJHahn This is on [react-staging](https://ibmdotcom-react-staging.mybluemix.net/) and [NextJS](https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html)

**Comment by jeffchew** [comment]
@RobertaJHahn this has already been fixed.
