### ISSUE TITLE
Inspect element in dev.console fails

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/ibm-dotcom-library#3968]
If you go to the ibmdocs page, any page, https://ibmdocs-dev.mybluemix.net/en/SSLTBW_2.4.0
open the development tools in chrome
hit the arrow icon and try to select any DOM element to see the styles, the console will freeze.
we are not able to style/develop things without this.

after rolling back commits, we identified that upgrade from dotcom 1.7.0 to 1.10.1 cause this.
in 1.7.0 we can inspect styles with no errors/freezing.

**Comment by asudoh** [comment]
A possible cause is #3809, where it seems to happening in https://ibmdocs-dev.mybluemix.net/en/SSLTBW_2.4.0, too.

@kyjak - Would you be able to try out [`v1.11.0-rc.0` release](https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.11.0-rc.0)? Thanks!

**Comment by kyjak** [comment]
yes, helps, thank you
