### ISSUE TITLE
Web Components: Provide CDN version of pre-built bundle with dotcom-shell

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/ibm-dotcom-library#3980]
### The problem

Many of our v18 users want to use our library not requiring heavy toolstack but just with loading `.js`/`.css`.

Web Components library tried to meet such requirement with ECMAScript module, but it's blocked by:

1. No browser has implemented [import maps spec](https://github.com/WICG/import-maps), that is required for browser to understand `import { LitElement } from 'lit-element'` code (to figure out where `lit-element` module `.js` file is)
2. Some CDNs (e.g. JSPM/UNPKG) tries to make above work by replacing NPM module name with actual CDN path on-the-fly, but it has performance problem by having to load many modules, and tends to hit many glitches

### The solution

Create pre-built bundle.

### Additional information

- We can make use of the EI server and upload to there (`https://1.s81c.com/common/ibm-dotcom-library/@{version}/**`)

### Acceptance criteria

- [ ] Create generated bundle that includes the `dotcom-shell`
- [ ] Publish up to EI server (`beta`, `next` and `latest`)

**Comment by jeffchew** [comment]
Should we have one where it's just dotcom shell, and another one with the kitchen sink?

We can host the artifact on EI server so it's behind akamai cache, so uploading should be fairly trivial. There's already a CDN version of v18 on there as well (under `http://www.ibm.com/common/v18`), we could create a folder like `http://www.ibm.com/common/ibm-dotcom-library`.

**Comment by asudoh** [comment]
> Should we have one where it's just dotcom shell, and another one with the kitchen sink?

I'm thinking of it and asked the requester of this feature if she's using only dotcom shell, but she responded that it's not the case. So we may need to do some sort of [code-splitting pattern](https://webpack.js.org/guides/code-splitting/).

**Comment by jeffchew** [comment]
> I'm thinking of it and asked the requester of this feature if she's using only dotcom shell, but she responded that it's not the case. So we may need to do some sort of [code-splitting pattern](https://webpack.js.org/guides/code-splitting/).

Right, perhaps we could create a webpack config that traverses the component folder, and creates an artifact for each component? Then people can inject by using something like:

```
<script src="//1.www.s81c.com/common/ibm-dotcom-library/dotcom-shell.js" /> 
<script src="//1.www.s81c.com/common/ibm-dotcom-library/lead-space.js" />
<script src="//1.www.s81c.com/common/ibm-dotcom-library/feature-card.js" />
```

Would the main one be `dotcom-shell.js` which includes `lit-element`, `lit-html`, etc, or we have something that separates the core necessary libraries into a `main.js` or `library.js` that is required to include with whatever component you're adding?

**Comment by asudoh** [comment]
@jeffchew Good thought, one thing to add is that I was thinking of bigger chunks to avoid [performance problems by loading many resources ([ref](https://docs.google.com/document/d/1ds9EEkcDGnt-iR8SAN-_7nsOfw7gsMfhZjzZ_QAIyjM/mobilebasic)).

**Comment by jeffchew** [comment]
> @jeffchew Good thought, one thing to add is that I was thinking of bigger chunks to avoid performance problems by loading many resources ([ref](https://docs.google.com/document/d/1ds9EEkcDGnt-iR8SAN-_7nsOfw7gsMfhZjzZ_QAIyjM/edit)).

Is this still an issue with http/2?

**Comment by asudoh** [comment]
Yes. The link above explains the problem in HTTP/2 context. BTW many (or all?) of the authors of the link above are the authors of [WebBundles spec](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html).

**Comment by jeffchew** [comment]
> Yes. The link above explains the problem in HTTP/2 context. BTW many (or all?) of the authors of the link above are the authors of [WebBundles spec](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html).

The results are as-of 2017, which seems heavily outdated. Perhaps this isn't an issue anymore? From what I can recall, at least performance audits from Google for former accounts at my last agency, they were heavily pushing the technology teams to utilize http/2 and es modules as much as possible.

**Comment by asudoh** [comment]
Again the test was with HTTP/2, so I don't think it's outdated. Loading many resources is not only a problem with HTTP connection but also with amount of disk cache access, service worker access, etc. If loading many resources were not a problem Web Bundles spec would not have been there.

**Comment by jeffchew** [comment]
@asudoh as discussed, if you can open a PR with the build mechanism (rollup), I will hook up the CI part of it.

**Comment by jeffchew** [comment]
@asudoh between build code and CI/CD do you think 5 is the right estimate, or maybe 8?

**Comment by asudoh** [comment]
@jeffchew A safer number (8) sounds good to me.

**Comment by jeffchew** [comment]
@RobertaJHahn here is the story regarding the CDN url that we talked about in sprint planning.

**Comment by jeffchew** [comment]
To catch up on this, a couple of issues were raised to the webmaster team:
- Create the folder `/common/ibm-dotcom-library` for us on the production server
- Open cross origin calls to the akamai server (it is currently only open for `www.ibm.com`

With this, the pipeline has been built out, but to a temporary folder that our team has access to on the production environment. This story can only be completed up to the release of automated beta releases, as we do not currently have a release candidate or full release with the build script available in the codebase. An additional story will be created to capture the closure of that.
