### ISSUE TITLE
React: Change Masthead L1 from behind the feature flag

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#4010]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
remove the feature flag from the `Masthead L1` component

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create a separate sub-story to Masthead L1 in storybook
- Bring in the white background style from the test pages
- Update documentation
- Prod QA testing issue (#4015)
- Feature flag documentation: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/docs/feature-flags.md
-  [Current Functional specs Box link](https://ibm.ent.box.com/folder/118448193520)

#### Acceptance Criteria
- [ ] Updated version of the existing component is available for testing and included in v1.12.0 release
- [ ] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by jeffchew** [comment]
@asudoh @annawen1 can we pass this to @Praveen-sr to test?

cc: @RobertaJHahn

**Comment by asudoh** [comment]
@jeffchew Right thank you for catching! Updated the QA issue.
