### ISSUE TITLE
Web component: CTA - Feature card with video - thumbnail image is covering full card

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#4011]
## Detailed description

On Web components (https://ibmdotcom-web-components-staging.mybluemix.net/?path=/story/components-cta--default)

Issue:  CTA - Feature card with Video enabled, thumbnail  is covering image section of the feature card.
Not as per sepecs.

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/641ea5f8-41da-4279-9ed0-52808b03171b)

Expected: 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ca0daaae-e9b7-4038-b8ce-3ff381221a42)

**Comment by jeffchew** [comment]
This is already fixed.
