### ISSUE TITLE
Pattern: promo, guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#402]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As a maker of IBM digital experience such as IBM.com, I need to be able to see the promo pattern, understand how to use it when designing or developing, so that I can build a great IBM digital experience.

### Notes
This story may have to be broken into multiple stories such as author, design, and develop.

### Acceptance criteria
- [ ] Guidelines are written
- [ ] Guideline pages are designed
- [ ] Guideline pages are developed and ready to be released
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1617_

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available. The design kit and components will continue.
