### ISSUE TITLE
Pattern: logo grid: visual design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#404]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As an IBM.com user, I need to be able to see what other companies are using the product/solution/offering presented on the page so that I can make a better decision.

### Notes
Here is an example of the band used in the past:
![Screen Shot 2019-09-08 at 7.12.24 PM.png](https://zenhub.ibm.com/images/594927b571aa2e2d5884e3f8/2f95b89b-48cd-471a-93f7-b132b0e89a6c)

### Acceptance criteria
- [ ] Visual design has been completed
- [ ] Visual design has been approved by DGC design leadership 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1619_

**Comment by wonilsuhibm** [comment]
Based on the meeting with Jill and Lila, the final designs for the non-interactive logo grid are captured in the `final design` page of this [Sketch file](https://ibm.box.com/s/vha7x9514lnuqw1t2vwrw23xqij49zo4)
