### ISSUE TITLE
Pattern: logo grid: design study

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#405]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As an IBM.com user, I need to be able to see what other companies are using the product/solution/offering presented on the page so that I can make a better decision.

### Notes
Here is an example of the band used in the past:
![Screen Shot 2019-09-08 at 7.12.24 PM.png](https://zenhub.ibm.com/images/594927b571aa2e2d5884e3f8/2f95b89b-48cd-471a-93f7-b132b0e89a6c)

All files are collected here: https://ibm.box.com/s/n3obhi5j6bk4atdtd5ilrtgf2l9t3j66

### Acceptance criteria
- [ ] How competitors and other companies are doing this has been collected
- [ ] Multiple design directions have been explored
- [ ] Final design direction has been identified 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1620_

**Comment by wonilsuhibm** [comment]
Met with Jill and Lila.

- Color background may be difficult for authors - transparent bg? different bg options?

- Try with more variations of logos - aspect ratio, long text - look at this site: https://www.ibm.com/watson/customer-engagement/partners/explorer/#/

- Clickable logo grid? To go to case studies. We may need to add some affordance.

- The body copy is probably an authoring option

- Cardinality of logos: min 3. When does it trigger carousel?

- Randomize the order? Customers are curated, partners are randomized -> two separate patterns.

- On smaller screens, drop the number of logos shown

- Do we look into creating DAM kind of centralized logo asset management system??? whose scope is it?

**Comment by wonilsuhibm** [comment]
Follow up meeting with Jill and Lila.
We decided to focus on non-interactive logo grid for the final design work. The studies are captured in this [Sketch file](https://ibm.box.com/s/vha7x9514lnuqw1t2vwrw23xqij49zo4) under the two study pages.
