### ISSUE TITLE
Pattern: logo grid: design specs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#406]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As an IBM.com user, I need to be able to see what other companies are using the product/solution/offering presented on the page so that I can make a better decision.

### Notes
Here is an example of the band used in the past:
![Screen Shot 2019-09-08 at 7.12.24 PM.png](https://zenhub.ibm.com/images/594927b571aa2e2d5884e3f8/2f95b89b-48cd-471a-93f7-b132b0e89a6c)

#### Additional Information
 - [Logo Grid Design Study # 405](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/405)
 - [Logo Grid Visual Design # 404 ](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/404)

### Acceptance criteria
- [ ] Design specs are available
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1621_

**Comment by wonilsuhibm** [comment]
We have this coming in from the IBM.com reboot team. Let's close this story.
