### ISSUE TITLE
search function stopped working in language selector

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/ibm-dotcom-library#4063]
search function stopped working in language selector in v1.11.0

Adopter:  **Privacy Preference**

**Comment by ljcarot** [comment]
@yellowdragonfly there is no search function in language selector, do you mean Locale Selector?

**Comment by ljcarot** [comment]
@yellowdragonfly It would be helpful if you can provide either a url where you see this, a recording of your experience or a screenshot. Thank you.

**Comment by yellowdragonfly** [comment]
https://proxy1.marketplace-test.ibmcloud.com/profile/dataprivacypreferences/welcome/us-en

**Comment by jeffchew** [comment]
Hi @yellowdragonfly , this appears to be a style collision issue where the hidden class is not getting honored, and this only appears to be in the full bundled CSS (we aren't seeing this in our Storybook or NextJS test application).

For now, what you can do to get around this is adding this to your code:

```
.bx--locale-modal__locales-hidden {
  display: none !important;
}
```

We will take on this bug and get into the next release in the meantime.

cc: @kennylam @IgnacioBecerra @ljcarot @asudoh @RobertaJHahn
