### ISSUE TITLE
Pattern: logo grid: guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#407]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As a maker of IBM digital experience such as IBM.com, I need to be able to see the logo grid pattern, understand how to use it when designing or developing, so that I can build a great IBM digital experience.

### Notes
This story may have to be broken into multiple stories such as author, design, and develop.

### Acceptance criteria
- [ ] Guidelines are written
- [ ] Guideline pages are designed
- [ ] Guideline pages are developed and ready to be released
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1622_

**Comment by RobertaJHahn** [comment]
Removed the `inactive` label.  The Web Simplification work has been prioritized over this pattern.

**Comment by RobertaJHahn** [comment]
Reopened this issue and attached it to a new epic (#1231) so that the work will not be lost and can be scheduled when the design team has time.

**Comment by RobertaJHahn** [comment]
Not stale
