### ISSUE TITLE
Pattern: logo grid

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#408]
_Wonil-Suh1 created the following on Sep 08:_  

 ### User story
As an IBM.com user, I need to be able to see what other companies are using the product/solution/offering presented on the page so that I can make a better decision.

### Notes
Here is an example of the band used in the past:
![Screen Shot 2019-09-08 at 7.12.24 PM.png](https://zenhub.ibm.com/images/594927b571aa2e2d5884e3f8/2f95b89b-48cd-471a-93f7-b132b0e89a6c)

The Sketch file is [here](https://ibm.box.com/s/c9ehbeflxk9fex3cr8u7p5eb3ftv6zwp). 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1623_

**Comment by RobertaJHahn** [comment]
Follow-on work for the Solutions page is managed in epic (#1805).  Closing
