### ISSUE TITLE
Mobile Footer Adds Extra Space

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#410]
_james-dow created the following on Sep 10:_  

 ### Detailed description

The footer when on mobile and positioned at the bottom of the screen will leave a large gap of whitespace. I think this is happening because the accordion content is pushing the page down further while invisible. This may actually be more of a bug on Carbon's Accordion than it is on our footer. Until we can get that fixed I think a simple solution is to add `overflow: hidden;` to the Accordion's content area. I haven't seen any negative repercussion of this yet.

### Steps to reproduce the issue

1. Go to https://ibmdotcom-react.netlify.com/?path=/story/dotcom-shell--default
2. Resize window to mobile view
3. Scroll to the bottom of the page.

<img src="https://media.github.ibm.com/user/19/files/8a634600-d335-11e9-9209-4ca4640e3a7f" width="450px" />

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1637_

**Comment by jeffchew** [comment]
@photodow wasn't this fixed already?

**Comment by photodow** [comment]
Yeah, did we create a duplicate issue in digital-design too? It looks like it can be closed.

Here is the one we worked off of https://github.com/carbon-design-system/ibm-dotcom-library/issues/170
