### ISSUE TITLE
Centralize the IBM Logo for IBM.com

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#411]
_james-dow created the following on Sep 10:_  

 ### Detailed description

Not sure if this is necessarily a bug, but maybe more of a technical debt item that I wanted to make sure we didn't forget.

Ultimately we need to figure out how to best leverage and unify the IBM logo across IBM.com. Especially for our own components like the `masthead`, and `footer`. Right now we are using two different IBM logos for those components.  **When consolidating the logos, the banding issue must also be resolved.**

#### Additional Information
Currently, the SVG logo is showing banding issue on some monitors. It depends on the monitor's DPI, but here is a screen capture:

![Screen Shot 2019-10-04 at 6.26.04 PM.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/a97a448b-435a-4ebc-9f4d-cd3db4921c28)

 - [Closed Banding issue #165](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/165)

#### Two logos
- [FooterLogo.js](https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/src/components/Footer/FooterLogo.js)
- [IbmLogo](https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/src/components/Icon/IbmLogo.js)

#### Questions
 - Can we leverage `@carbon/icons-react` for this?
 - Can we explore using an [SVG Sprite](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)

#### Acceptance Criteria
 - [ ] Single logo is used for the Masthead and Footer
 - [ ] The IBM logo banding issue on some monitors is resolved.  
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1639_

**Comment by jeffchew** [comment]
@photodow why was this pulled into this sprint? We didn't triage this or set a priority for this yet.

cc: @RobertaJHahn

**Comment by photodow** [comment]
@jeffchew sorry if I did something out of order. I was told to cherry-pick items that could be done quickly. If that's not true, then I can return it to be triaged, no problem.

**Comment by jeffchew** [comment]
Oh ok got it, didn't realize you were cherry-picking this, but I guess we need to set parameters on what the max size of a cherry-picked item should be. I was thinking a 1 (this was sized as a 2), but we should probably define that going forward.

cc: @RobertaJHahn @ljcarot @wonilsuhibm

**Comment by RobertaJHahn** [comment]
I have added this topic to the Huddle meeting agenda today.  Might also be good to get feedback from team members to refine the process.  

@jeffchew @photodow @ljcarot @wonilsuhibm

**Comment by jeffchew** [comment]
Thank you @RobertaJHahn , I have already made updates to the DDS support documentation based on various feedback already in the past couple of weeks:
https://ibm.ent.box.com/notes/506284098346

We can discuss in huddle.

**Comment by RobertaJHahn** [comment]
Additional comments from [issue 165](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/165)

Kenny Lam:  @wonilsuhibm Do you have a better asset you can provide?

Wonil:  @kennylam I'm suspecting that it might be coming from SVG rendering, which tends to be too sharp with little or no anti-aliasing.

I'm attaching a zip file with different sizes. Any chance we can test them out so that we can find the right resolution?

[ibm--8bar-logo--png--sizes.zip](https://github.com/carbon-design-system/ibm-dotcom-library/files/3698224/ibm--8bar-logo--png--sizes.zip)
