### ISSUE TITLE
Customize My Profile menu Login & Logout links in Masthead component <For IBM Startups React web app>

### ISSUE THREAD

**Issue by shrinandhini2801** [carbon-design-system/ibm-dotcom-library#4118]
### The problem
_Startups application is built using react and we are using ibmdotcom and carbon components through out the app. In Masthead , I want to make the app redirect to custom login url when the login dropdown from My profile menu is clicked.

### The solution
_Feature to add custom values to the my profile menu

### Additional information
 _The reason why we need to redirect to custom Url is to store the session cookie based on which the API calls will be handled. 

PS: our app is yet to be hosted so i couldn't share the staging url for your reference. The tentative go live date might fall between next week and a week after ( Not confirmed yet).

**Comment by motou** [comment]
maybe duplicate of #3854 ?

**Comment by jeffchew** [comment]
Yes @motou we were just going through #3854 during our triage meeting. We will see if we can consolidate the issues.

cc: @RaphaelAmadeu @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing this issue as a dup of (#3854)
