### ISSUE TITLE
Locale Selector as a Service

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#412]
_james-dow created the following on Sep 10:_  

 #### User Story
> As a `[user role below]`:
As a dotcom developer/adopter

> I need a:
service to make calls to get the most up to date and supported locale information

> so that I can:
can properly set the translation for my users

#### Additional information
I'm not sure if this is a single service, or maybe 2 or 3 (we might want to consider breaking this down further?), but I see us needing some sort of service around the locale selector as we begin to develop the component/pattern out.

- [Locale Selector API](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)
- [User Locale API](https://api.www.s81c.com/webmaster/dbip/)

#### Acceptance criteria
 - [ ] Make call to get list of all available locale's
 - [ ] global AddEventListener to check the user is on the correct locale
 - [ ] Set the user's current locale
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1642_

**Comment by photodow** [comment]
@jeffchew @annawen1 Is this currently being worked on?

https://github.com/carbon-design-system/ibm-dotcom-library/pull/526

**Comment by jeffchew** [comment]
@photodow this might be a duplicate to work we've already identified for the Locale Selector, so we can probably close this.

cc: @RobertaJHahn

**Comment by annawen1** [comment]
Yeah I think we can close this

**Comment by RobertaJHahn** [comment]
This work is being managed in the [locale selector MVP Issue #252 ](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/252)
