### ISSUE TITLE
Locale Selector Motion: Search

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#413]
_james-dow created the following on Sep 10:_  

 ### Detailed description

We need to do an animation exploration around the Locale Selector for when a user searches for a language/location

### Additional information

- [Lara identified some moments to explore](https://ibm.ent.box.com/file/504039567025)
- [Original Design Exploration](https://github.ibm.com/webstandards/digital-design/issues/787)
- [To be developed in Sprint 19](https://github.ibm.com/webstandards/digital-design/issues/1078)
- [Invision Prototype of Design Changes](https://ibm.invisionapp.com/share/26NZ77UF57S)
- [IBM Design Language: Motion](https://www.ibm.com/design/language/elements/motion/basics)
- [Locale Selector API](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)
- [User Locale API](https://api.www.s81c.com/webmaster/dbip/)

### Before / After

<img src="https://media.github.ibm.com/user/19/files/bbd81380-d32d-11e9-9a21-cc7ab08e3a3c" width="300" /> <img src="https://media.github.ibm.com/user/19/files/2721e580-d32e-11e9-84ce-cf45ff81049f" width="300" />

### Acceptance criteria
- [ ] Quick prototypes to demonstrate explorations
- [ ] At least 3 alternatives 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1643_

**Comment by ljcarot** [comment]
@photodow Is this issue still valid?  Should we put in backlog?  Stalebot made it inactive so want to check on what we should do with it?

**Comment by photodow** [comment]
@ljcarot probably? It kind of depends on where the updated locale selector work lands. I haven't heard any updates on the latest around that.

**Comment by ljcarot** [comment]
@jeffchew How should we handle this issue?  It has both Design and Dev labels.
