### ISSUE TITLE
Investigate Github reporting to manage tickets

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#427]
_hahnrob created the following on Sep 10:_  

 

#### User Story

> As a `[user role below]`:
As a DDS developer and designer

> I need to:
have a report and/or process to help identify the tickets that are logged against Northstar and Carbon for ibm.com

> so that I can:
investigate and resolve the adopters' issues.

#### Additional information

 - 

#### Acceptance criteria
 - [x] Report options and recommended process that is discussed with the Leadership team

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1672_

**Comment by RobertaJHahn** [comment]
Moved to the public github.  Created a support process that will continue to be refined.  [link to support process](https://ibm.ent.box.com/notes/506284098346).   Closing.
