### ISSUE TITLE
Pattern:  Review & update simple overview band development

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#434]
_hahnrob created the following on Sep 11:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a simple overview band pattern

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
 - [pattern: simple overview band specs #337](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/337)
 - [hyphens - css tricks](https://css-tricks.com/almanac/properties/h/hyphenate/)
 - [widows](https://developer.mozilla.org/en-US/docs/Web/CSS/widows)
 - [orphans](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans)
 - Code is still behind a feature flag
 - Gap analysis should have been performed as part of the alpha dev story.  (add issue here)

#### Acceptance criteria
 - [ ]  Code updates based on the final design and functional specs, beta version of the code
 - [ ] code is tested in:  latest Chrome, latest iOS and latest Android

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1686_

**Comment by jeffchew** [comment]
Removed the `inactive` label. @RobertaJHahn @ljcarot @wonilsuhibm think we can align this with perhaps an alpha story?

**Comment by wonilsuhibm** [comment]
Yes, I think the main difference between this and the Simple long form is probably char count and type scale. @ljcarot Based on the latest thinking behind the layout pattern, we can potentially add a quick story, I would say 3 points, to update the type scale and the specs accordingly, and develop this as a variation of Simple long form.

**Comment by RobertaJHahn** [comment]
@jeffchew @ljcarot @wonilsuhibm I created 2 additional issues.  One for the [functional specs #730](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/730) and the second for the [alpha development #727](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/727).  All issues are in backlog.

**Comment by RobertaJHahn** [comment]
Created a new QA process.  This issue is obsolete.  Closing.
