### ISSUE TITLE
Pattern:  develop lead space, centered

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#437]
_hahnrob created the following on Sep 11:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a centered lead space pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
- [Design specs](https://ibm.box.com/s/y2xfx4efs8mqwpie7oddownko4u055l4)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1689_

**Comment by sannminwin** [comment]
FYI, 
@RobertaJHahn 
@wonilsuhibm 

I added link to latest specs provided by @wonilsuhibm.

**Comment by wonilsuhibm** [comment]
Final specs have been added to the description.
