### ISSUE TITLE
Pattern:  Sticky Table of Content specs from web simplification

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#444]
_hahnrob created the following on Sep 16:_  

 Specs will be provided by Lila.  Target delivery date is Sept 23.

#### Additional Information
 - [discover pattern specs.sketch from Lila](https://www.ibm.com/cloud/virtual-servers-cloud/about-virtual-machines/index.html)

#### Acceptance Criteria
 - [ ] Specs received from Web Simplification and reviewed with DDS engineering 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1708_

**Comment by jeffchew** [comment]
_On Oct 03, hahnrob commented:_
design review meeting scheduled Oct 8.

**Comment by jeffchew** [comment]
_On Oct 08, hahnrob commented:_
specs reviewed in the Oct 8 meeting.

**Comment by RobertaJHahn** [comment]
![pattern--tableof-contents--design-specs--max](https://media.github.ibm.com/user/25726/files/751a0800-f334-11e9-9b1c-12205a6e66af)

![pattern--tableof-contents--design-specs--max--scroll](https://media.github.ibm.com/user/25726/files/76e3cb80-f334-11e9-915c-2e5355eaeb86)

![pattern--tableof-contents--design-specs--xlg](https://media.github.ibm.com/user/25726/files/7a775280-f334-11e9-980b-2edc351f72b8)

![pattern--tableof-contents--design-specs--lg](https://media.github.ibm.com/user/25726/files/8236f700-f334-11e9-9a3d-5e5faf775730)

![pattern--tableof-contents--design-specs--md](https://media.github.ibm.com/user/25726/files/8531e780-f334-11e9-9174-8b57bb20fe38)

![pattern--tableof-contents--design-specs--md--scroll](https://media.github.ibm.com/user/25726/files/895e0500-f334-11e9-9f97-a4d5772e0c2e)

![pattern--tableof-contents--design-specs--md--open](https://media.github.ibm.com/user/25726/files/8c58f580-f334-11e9-9d2a-d0f356c19ad1)

![pattern--tableof-contents--design-specs--sm](https://media.github.ibm.com/user/25726/files/8fec7c80-f334-11e9-92fa-3851bdb8ab9a)

Spec source files are [here](https://ibm.box.com/s/yfuicifhfeaefp4rl0pp62dpeacr18ry)
