### ISSUE TITLE
Pattern: develop sticky Table of Contents

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#445]
_hahnrob created the following on Sep 16:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a sticky table of content pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

- Story within Storybook with corresponding knobs
- minimum 80% unit test coverage
- Utilize Carbon
- [Specs](https://ibm.box.com/s/18w1s9z4j57as682hmkl0du57mwh380u)
- [Spec issue](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1708)
 - [About virtual server example web page](https://www.ibm.com/cloud/virtual-servers-cloud/about-virtual-machines/index.html)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1709_

**Comment by wonilsuhibm** [comment]
New specs have been added to the [spec issue](https://github.ibm.com/webstandards/digital-design/issues/1708)

**Comment by jeffchew** [comment]
@sannminwin FYI, `Layout` component has been completed and can be used for this story.

**Comment by sannminwin** [comment]
@RobertaJHahn 
@ljcarot 
@jeffchew 
Hello Team,
Sticky table of contents is ready for PR.
Thanks

[Link to PR](https://github.com/carbon-design-system/ibm-dotcom-library/pull/667)
