### ISSUE TITLE
Pattern: List section specs from web simplification

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#448]
_hahnrob created the following on Sep 17:_  

 Specs will be provided by Lila.  Target delivery date is Sept 23.

#### Additional Information
 - [discover pattern specs.sketch from Lila](https://www.ibm.com/cloud/virtual-servers-cloud/about-virtual-machines/index.html)

#### Acceptance Criteria
 - [x] Specs received from Web Simplification and reviewed with DDS engineering 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1713_

**Comment by jeffchew** [comment]
_On Oct 03, hahnrob commented:_
Lila reviewed with DDS engineering on Sept 26.

**Comment by RobertaJHahn** [comment]
[sketch file](https://ibm.ent.box.com/file/539555558681)

[specs](https://ibm.ent.box.com/folder/89980342746)
