### ISSUE TITLE
Pattern: develop list section

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#449]
_hahnrob created the following on Sep 17:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a list section content pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
 - [Pattern: Examples section specs from web simplification](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1713)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1714_

**Comment by sannminwin** [comment]
created pull request for List Section pattern -  https://github.com/carbon-design-system/ibm-dotcom-library/pull/573/

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.

**Comment by jeffchew** [comment]
Note, this story did not make code freeze for `v1.1.0`. It will be available as alpha via canary releases, and will also be part of `v1.2.0`.

cc: @RobertaJHahn @ljcarot @wonilsuhibm @sannminwin

**Comment by ljcarot** [comment]
Reopening since this needs to continue in Sprint 21.

**Comment by sannminwin** [comment]
We will only need to build list section without cards or pictograms.
