### ISSUE TITLE
Component Design kit: update component state example pages

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#458]
_Olivia-Flory created the following on Sep 17:_  

 

# As an external user of the Digital Design Expressive (white theme) design kit, I need to see all the state examples of a component on a single page to understand how the component is supposed to look and which states are available.

## Additional information
The Carbon design kit provides visual examples of each state a component so external users can reference the design kit in a singular place. When the Expressive kit is released to external users they need to see the same examples in our version of the kit. This will help us stay aligned with Carbon.
Example page:
![Screen Shot 2019-09-17 at 3.10.34 PM.png](https://zenhub.ibm.com/images/5bc1083e9c7a4b4b3d71ae3e/fc938dcb-e404-49fa-a406-e7ec86e78bb8) 

*Most pages will only need the symbols to be reconnected/updated as the core 32 symbols are already documented in the kit*

List of pages
- [ ] Accordion
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] Dropdown
- [ ] File uploader
- [ ] Form
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Notification
- [ ] Number input
- [ ] Overflow menu
- [ ] Pagination
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Tooltip

## Acceptance criteria
- [ ] Each component has it's own page
- [ ] All states are displayed with the corresponding state label
- [ ] Design completed and matches Carbon template
- [ ] Design reviewed by DGC design leadership (Wonil Suh)

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1724_

**Comment by oliviaflory** [comment]
not stale
