### ISSUE TITLE
Engineering research of the Carbon side nav component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#461]
_hahnrob created the following on Sep 17:_  

 

#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
understand the Carbon side nav component

> so that I can:
properly develop the Digital Design left panel container

#### Additional information

 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] documented understanding of the Carbon component design and implementation

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1727_

**Comment by RobertaJHahn** [comment]
@kennylam some how this issue was assigned to Lara.  Could you please add your comments so that I can close the issues and release 19.  Thanks.
