### ISSUE TITLE
DDS Proxy server shows 429 error after too many requests

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#464]
_Jeff-Chew created the following on Sep 18:_  

 

### Detailed description

If the proxy server is used too much, it will eventually show a 429 error and requests are no longer going through. This typically would require a restart of the server.

### Steps to reproduce the issue

1. Run multiple network requests to the translation server
2. See console log once the server start hitting 429 errors:

![image.png](https://zenhub.ibm.com/images/5cdaf422acece451e3801796/4fcaf54c-f242-4418-82c1-3d07fa5a9c6f)

### Additional information

- Server is on IBM Cloud: https://ibm.ent.box.com/notes/493566104030
- Proxy server details: https://ibm.ent.box.com/notes/519117657731 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1732_

**Comment by kennylam** [comment]
@jeffchew @ljcarot looks like the only way around this is to upgrade our plan
https://www.ibm.com/support/pages/what-does-http-429-too-many-requests-message-mean-api-connect-service

**Comment by ljcarot** [comment]
Let's move to the next tier.  Do you know how to upgrade @kennylam

**Comment by jeffchew** [comment]
@ljcarot I have more of a budget question. I believe this was under Avi's purview before he left. Do we know if this will continued to be paid by his budget, or we need to figure out who is paying for this in 2020?

**Comment by ljcarot** [comment]
We would need to check with Basel. He has taken over Avi’s things.

**Comment by jeffchew** [comment]
Sent an email to Basel asking about this.

**Comment by RobertaJHahn** [comment]
@jeffchew Moving this to sprint 20-03 so that it doesn't get lost.  Looks like you are waiting for a response from Basel.

**Comment by jeffchew** [comment]
Kicking this out, this doesn't seem to be a problem at the moment.

**Comment by RobertaJHahn** [comment]
Closing issue as it still does not seem to be a problem.  Will reopen or create an new issue, if needed.
