### ISSUE TITLE
Pattern:  develop simple long form section (w/o images)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#466]
_hahnrob created the following on Sep 19:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a simple long form section pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
 - [Pattern: Simple long form section specs from web simplification https://github.com/carbon-design-system/ibm-dotcom-library/issues/466](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1734)
- [Specs](https://ibm.box.com/s/0sp0686h0mz638is8fwkpxtpzr8aqkgb)
- [Sketch file](https://ibm.box.com/s/tj2qewm3ss2krnupugba1nbro4ezzvi1)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1735_

**Comment by sannminwin** [comment]
created pull request.
https://github.com/carbon-design-system/ibm-dotcom-library/pull/561/

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.

**Comment by jeffchew** [comment]
Note, this story did not make code freeze for `v1.1.0`. It will be available as alpha via canary releases, and will also be part of `v1.2.0`.

cc: @RobertaJHahn @ljcarot @wonilsuhibm @sannminwin

**Comment by ljcarot** [comment]
Reopening since this work is continuing into Sprint 21

**Comment by sannminwin** [comment]
I have updated the simple long form and available for review now.
Thanks

[preview](https://deploy-preview-561--ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/simple-long-form--default)
[pull request](https://github.com/carbon-design-system/ibm-dotcom-library/pull/561)
