### ISSUE TITLE
Pattern:  Use cases specs from web simplification

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#468]
_hahnrob created the following on Sep 19:_  

 Specs will be provided by Lila.  Target delivery date is Sept 23.

#### Additional Information
 - [discover pattern specs.sketch from Lila](https://www.ibm.com/cloud/virtual-servers-cloud/about-virtual-machines/index.html)

#### Acceptance Criteria
 - [ ] Specs received from Web Simplification and reviewed with DDS engineering 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1737_

**Comment by jeffchew** [comment]
_On Oct 03, hahnrob commented:_
Design review meeting scheduled Oct 17.

**Comment by RobertaJHahn** [comment]
Design review conducted on Oct 16.

**Comment by wonilsuhibm** [comment]
Specs from Lila are [here](https://ibm.box.com/s/n5gatqgw08zvjun272y0o3wnbhrs73ow)
