### ISSUE TITLE
Pattern: develop use cases pattern

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#469]
_hahnrob created the following on Sep 19:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a use case pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
- [Web Simplification design & specs](https://ibm.ent.box.com/folder/93008842052)
 - [Pattern: Use cases specs from web simplification #468](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/468)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1738_

**Comment by RobertaJHahn** [comment]
@sannminwin I have updated the use case dev issue with the box folder link provided by Wonil.

**Comment by sannminwin** [comment]
Thanks @RobertaJHahn

**Comment by sannminwin** [comment]
@RobertaJHahn 
@ljcarot 
@jeffchew 

Hello Team,
Pull request is created for use cases pattern.

[PR Link](https://github.com/carbon-design-system/ibm-dotcom-library/pull/689)
