### ISSUE TITLE
Pattern: develop next steps (cards w/o images) pattern

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#472]
_hahnrob created the following on Sep 19:_  

 

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a use case pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

 - Story within Storybook with corresponding knobs
 - minimum 80% unit test coverage
 - Utilize Carbon
 - [Pattern: next steps (cards w/o images) specs from web simplification](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1740)
 - Card MVP will be created without the magic link.
 - [Updated specs v2](https://ibm.ent.box.com/file/543848934998)

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1741_

**Comment by sannminwin** [comment]
Hi team
@wonilsuhibm 
@oliviaflory 
@RobertaJHahn 

I am started working on cards w/o images pattern.
Could someone pls comfirm that the specs from the link below is latest?
https://ibm.ent.box.com/file/543848934998

Thanks

**Comment by sannminwin** [comment]
@RobertaJHahn 
@jeffchew 

Created pull request for cards without images pattern.

https://github.com/carbon-design-system/ibm-dotcom-library/pull/728/
