### ISSUE TITLE
Cupcake website page creation - Patterns/Lead Space page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#477]
_chsanche created the following on Sep 23:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/477.
- Lead Space page on v19a website Components section can be viewed [here](https://www.ibm.com/standards/web/components/lead-space/).
- Carbon does not have Lead Space as a component or patterns.
(Anna mentioned - "Only the gatsby template has that. We don't have that for product.")

#### Task
- Collaborate with Lara for the content creation.
- Content draft box doc can be found [here](https://ibm.box.com/s/gyvd3zvxl4vdf1rk0u2y65obceg1c2mp)

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1751_

**Comment by jeffchew** [comment]
_On Sep 23, chsanche commented:_
**Note:** @larahanlon worked on the Lead Space last sprint and Anna created a storybook for it: https://deploy-preview-78--ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/leadspace--default-with-image

**Comment by JennySanchez** [comment]
This is the duplicated issue of #28 and will be closed.
