### ISSUE TITLE
Component Design kit: radio button; add horizontal variation 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#488]
_Olivia-Flory created the following on Sep 26:_  

 Add horizontal variation of radio button to design kit

3 items
6 items

Reference smart layout settings: https://github.com/carbon-design-system/carbon-design-kit/issues/218

**Acceptance criteria**
White kit
- [ ] symbol structure matches carbon
- [ ] kit uploaded to box. 

Gray 90 kit
- [ ] symbol structure matches carbon
- [ ] ~kit uploaded to box.~

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1776_

**Comment by oliviaflory** [comment]
not stale!
