### ISSUE TITLE
Review and update copy for locale selector

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#493]
_larahanlon created the following on Sep 30:_  

 ### User story
As an ibm.com user, I need a way to know when and why I am leaving my preferred language so that I can make a decision about my language of choice as I continue.

### Notes
See final design specs https://github.com/carbon-design-system/ibm-dotcom-library/issues/493

### Tasts
- [x] Lara to share locale designs with Jim
- [x] Jim to review copy across all locale touchpoints
- [x] Jim to make recommendations for copy edits/additions
- [x] Lara and Jim to document and provide to dev

### Deliverables
- [x] Proposed copy changes or additions for locale selector experience

### Acceptance Criteria
- [x] Mary O' Donnell reviews copy changes
- [x] Linda reviews copy changes
- [x] Jeff & dev team accepts copy changes
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1789_

**Comment by jeffchew** [comment]
_On Sep 30, jamespistilli commented:_
@larahanlon Will review and circle back

**Comment by jeffchew** [comment]
_On Sep 30, larahanlon commented:_
PDF of design specs. Please refer to copy on **pages 1, 3, 16, 20** in particular. 
[ibmdotcom--locale-selector--SPECS-ENG.pdf](https://github.ibm.com/webstandards/digital-design/files/439546/ibmdotcom--locale-selector--SPECS-ENG.pdf)

**Comment by jeffchew** [comment]
_On Oct 03, jamespistilli commented:_
First draft sent to @larahanlon on 10.3 (Box links below here)

https://ibm.box.com/s/rw41g18q7nif2bm3ay681iyu6vedf97w
https://ibm.box.com/s/fpecp5ymozrpb01zure6l8m3r4h26i2j

**Comment by jeffchew** [comment]
_On Oct 03, larahanlon commented:_
Thank you @jamespistilli

**Comment by larahanlon2** [comment]
This was complete multiple sprints ago. Linked to #501 which is complete. Will close.
