### ISSUE TITLE
Pattern design kit: centered lead space pattern

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#496]
_Wonil-Suh1 created the following on Oct 01:_  

 ### User story
As a designer working on an innovation project, I need to be able to use the centered lead space pattern without having to recreate it every time I use it so that my designs are to the specs and consistency is maintain across different touch points in the user's journey.

### Notes
This is a discovery story to build centered lead space symbols to understand the mechanisms and limitations of Sketch symbols to inform the larger strategy for the final design kit(s).

### Acceptance criteria
- [ ] 5 pattern symbols for the 5 break points have been built
- [ ] Different line numbers can be handled
- [ ] Different numbers of buttons can be handled
- [ ] Different background image can be added
- [ ] Background gradient can be turned on / off
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1793_

**Comment by jeffchew** [comment]
@wonilsuhibm @larahanlon2 @oliviaflory do we have this captured already or we still need this issue?

**Comment by oliviaflory** [comment]
We might need this issue, but it depends a little on what we decide to do with the pattern design kit.
