### ISSUE TITLE
Pattern design kit: simple benefits

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#497]
_Wonil-Suh1 created the following on Oct 01:_  

 ### User story
As a designer working on an innovation project, I need to be able to use the simple benefits pattern without having to recreate it every time I use it so that my designs are to the specs and consistency is maintain across different touch points in the user's journey.

### Notes
This is a discovery story to build simple benefits symbols to understand the mechanisms and limitations of Sketch symbols to inform the larger strategy for the final design kit(s).

### Acceptance criteria
- [ ] Different line numbers in each column can be handled
- [ ] Links in each column can be turned on/off
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1794_

**Comment by oliviaflory** [comment]
**November 7 notes**
We will prioritize the web simplification patterns.
We are still conducting the research for the pattern kit as of Nov 7th.

**Comment by RobertaJHahn** [comment]
Moving this issue to Icebox pipeline, pending decision about whether we will need a pattern design kit.

**Comment by RobertaJHahn** [comment]
Keeping this issue active, based on Olivia's comments above.

**Comment by oliviaflory** [comment]
@wonilsuhibm do you want to keep this issue open? 

Could we close and add a new one when we can actually start thinking about pattern design kit(s)?

**Comment by wonilsuhibm** [comment]
Yes, we are not even sure if we need a pattern design kit yet. Let's close it.
