### ISSUE TITLE
Cupcake website page creation - Guidelines/Color page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#499]
_chsanche created the following on Oct 02:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the colors

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/499.
- Color guideline page on v19a website can be viewed [here](https://www.ibm.com/standards/web/elements/color.html).
- Color guideline page on the Carbon website can be viewed [here](https://www.carbondesignsystem.com/guidelines/color/overview)

#### Task
- Collaborate with Wonil for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1797_

**Comment by JennySanchez** [comment]
@wonilsuhibm 

The link to view the Color guideline page for the Cupcake website is [here](https://ibm.box.com/s/j1nxqxeca9xgdebl1sio8ft8bd3zm51g).
FYI - the image is too big for attachment.

---

Two things to point out to you for your thought.

1. For the color introduction, I have a screenshot of the Order Management website, but is there any IBM.com specific UI I can use? 

![Screen Shot 2019-10-23 at 3.24.35 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d0150146-9bc1-40da-9451-a608c42df84d)

2. After ideating a few ideas and talked to Olivia, we both think linking the color token will be the best for our adopters to find the latest color token information without duplicate the page content, making the website page super long, or invent a new pattern for presenting content on the website. Please let me know what do you think.

![Screen Shot 2019-10-23 at 3.35.18 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/9384d535-e5b6-4ff3-9aa5-24b21b84618b)

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.
