### ISSUE TITLE
Finalize the Locale Selector copy specs 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#501]
_hahnrob created the following on Oct 03:_  

 

#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
understand the locale selector functional specifications

> so that I can:
properly develop this component/service

#### Additional information

 - [Enable a user to view the locale yellow banner in his language](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1433)
 - [Enable a user to see the locale banner if they land on a translated ibm.com site page and there is a localized version of the page available https://github.com/carbon-design-system/ibm-dotcom-library/issues/501](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1431)

#### Acceptance criteria
 - [ ] Meetings to help define the way the Locale Selector should function based on global requirements
 - [ ] Developer level documentation that will enable them to create the component

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1801_

**Comment by jeffchew** [comment]
_On Oct 10, Wonil-Suh1 commented:_
From the SEO team (Ellen Mamedov):

"Instead of using a modal overlay to use a notification bar under the menu (like we do when we suggest alternative versions of the page when we think they would want a different version). Google generally doesn’t like interstitials which in some cases can include popups that cover content when the page loads. It’s also better ux because if that is the page users want to be on, they don’t have to click something to read the content."

**Comment by larahanlon2** [comment]
Copy for locale selector can be found [here](https://ibm.box.com/s/xcsxydu3pi5dxtrhxqanweq78j6xw0jm).

- This copy has been edited and reviewed by Jim Pistilli.
- This document and field names aligns with the specs ([visual](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8) and [functional](https://ibm.box.com/s/5cubvqd96izgl7cgmc820kxqvkjw88cr)), including all use cases.
