### ISSUE TITLE
Gatsby publishing how-to session for the Cupcake website stream

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#502]
_chsanche created the following on Oct 04:_  

 

#### User Story

> As a user role below:
DDS Cupcake website content creator

> I need to:
understand the Gatsby theme and know how to publish content with the theme

> so that I can:
publish content efficiently.

#### Additional information

 - Gasby theme can be viewed here.

- Training attendees are: Wonil, Lara, Scott, Olivia, James, Jim, Jacob and Jenny.

#### Acceptance criteria
 - [ ] Jim, Jacob, and Jenny know how to publish website content with the Gatsby set up

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1803_

**Comment by jeffchew** [comment]
_On Oct 04, chsanche commented:_
*FYI:* I will add Jacob to this task issue once he has an Git account.

**Comment by jeffchew** [comment]
_On Oct 04, jamespistilli commented:_
@chsanche Was this related to a particular epic that might have useful information for us? 

Thanks

**Comment by jeffchew** [comment]
_On Oct 04, chsanche commented:_
@jamespistilli This is under the Cupcake MVP epic. I am not sure if there's any other Epic that should be connected to. @hahnrob Can you share your thought?

**Comment by jeffchew** [comment]
_On Oct 07, hahnrob commented:_
@chsanche @jamespistilli I checked another training issue and it is related the release epic: [Design kit training #1725](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1725).  Since this issue includes Gatsby publishing training for the cupcake website, I think that the linking this issue to the cupcake MVP is fine.

**Comment by jeffchew** [comment]
_On Oct 07, chsanche commented:_
Perfect. Thank you, @hahnrob.

**Comment by jeffchew** [comment]
_On Oct 07, chsanche commented:_
**Update:** Training scheduled for 10/15 1:00 pm EST.

**Comment by JennySanchez** [comment]
The learning session scheduled and completed.

Step by step document created by Kenny can be viewed here: 
https://ibm.box.com/s/as8fo8gcecvizngxgq2dpuk4po2alq7t
