### ISSUE TITLE
Locale Modal enhancements - first iteration (a.k.a Locale Selector)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#503]
_hahnrob created the following on Oct 04:_  

 This is an epic to consolidate the Locale Selector enhancements. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1804_

**Comment by RobertaJHahn** [comment]
Release complete.  All linked issues closed.  Closing this epic.
