### ISSUE TITLE
Locale Selector:  develop the modal page load logic

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#505]
_hahnrob created the following on Oct 04:_  

 

#### User Story

> As a `[user role below]`:
As a developer using the Digital Design System

> I need to:
have different messaging appear based on the user information when the modal loads

> so that I can:
include this component in the Locale Selector in the web site I am developing

#### Additional information

- This issue is dependent on the design and the [package architecture https://github.com/carbon-design-system/ibm-dotcom-library/issues/505](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/860) 
- [final design and specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
              - Includes:  Functional labels, Visual redlines, Behavior and interaction specs, Desktop and mobile
 - [Box link to Mary O'Donnell's functional specs](https://ibm.ent.box.com/folder/88263129224)

#### Acceptance criteria
 - [ ] Component has been tested using Netlify
 - [ ] The component development follows a modular component pattern
 - [ ] The component should be accessible via ES6 import
 - [ ] The component should be visible within the living documentation of the Dotcom components
 - [ ] Presented and approved Product Owner

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1806_

**Comment by jeffchew** [comment]
@RobertaJHahn I'm taking this out of the Locale Selector MVP, we should create a separate epic perhaps for this treatment.

cc: @ljcarot @wonilsuhibm

**Comment by RobertaJHahn** [comment]
@jeffchew @wonilsuhibm @ljcarot I have created an epic to capture the work included in the next Locale Selector version.  This issue is linked to it.  I have not linked the issue to a release as we don't know what release will include these updates.

**Comment by RobertaJHahn** [comment]
Locale Selector work has not been prioritized because of the Web Simplification priorities.

**Comment by RobertaJHahn** [comment]
Not stale
