### ISSUE TITLE
Locale Selector:  develop the locale selector animated transitions

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#508]
_hahnrob created the following on Oct 04:_  

 

#### User Story

> As a `[user role below]`:
As a developer using the Digital Design System

> I need to:
have animated transitions included the Locale Selector transitions

> so that I can:
include this component in the Locale Selector in the web site I am developing

#### Additional information

- This issue is dependent on the design and the [package architecture https://github.com/carbon-design-system/ibm-dotcom-library/issues/508](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/860) 
- [final design and specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
              - Includes:  Functional labels, Visual redlines, Behavior and interaction specs, Desktop and mobile
 - [Box link to Mary O'Donnell's functional specs](https://ibm.ent.box.com/folder/88263129224)

#### Acceptance criteria
 - [ ] Component has been tested using Netlify
 - [ ] The component development follows a modular component pattern
 - [ ] The component should be accessible via ES6 import
 - [ ] The component should be visible within the living documentation of the Dotcom components
 - [ ] Presented and approved Product Owner

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1809_

**Comment by jeffchew** [comment]
@RobertaJHahn I'm taking this out of MVP, unless there are any disagreements, I don't think it's necessary for the initial version.

cc: @ljcarot @wonilsuhibm

**Comment by ljcarot** [comment]
@jeffchew Is there a follow-on Issue for the Locale Selector work past MVP that this should be tied to?

**Comment by jeffchew** [comment]
There might be some motion research stories that are out there, would have to find it...

**Comment by RobertaJHahn** [comment]
Research work has not been scheduled due to the Web Simplification priorities.

**Comment by RobertaJHahn** [comment]
not stale
