### ISSUE TITLE
Locale Selector:  Document the information needed in the merged country/language file

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#518]
_hahnrob created the following on Oct 09:_  

 

#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have a file in a specific format that contains the data I need

> so that I can:
correctly develop the Locale Selector application

#### Additional information

 - Tina Williams owns the IBM country list which includes the Locale codes needed.  A consolidated file that contains the locale codes and translated display names is needed for the Locale Selector application to provide the desired user experience.
 - [US-English country list](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)
 - [France-French country list](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/frfr-utf8.js)
 - Linda will schedule the meeting with Tina.  The documented requirements are needed for this meeting.

#### Acceptance criteria
 - [x] Documented requirements for Tina Williams to create the consolidated file needed

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1820_

**Comment by RobertaJHahn** [comment]
Meeting conducted with tina Oct 17.
