### ISSUE TITLE
Locale Selector:  develop a utility to provide the translated display name of the country & language

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#519]
_hahnrob created the following on Oct 09:_  

 

#### User Story

> As a `[user role below]`:
As a DDS developer

> I need to:
develop a utility that provides the translated country and language display names using the Locale code

> so that I can:
include the desired names in the Locale Selector application to the ibm.com users

#### Additional information

- This issue is dependent on the design and the [package architecture https://github.com/carbon-design-system/ibm-dotcom-library/issues/519](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/860) 
- [final design and specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
              - Includes:  Functional labels, Visual redlines, Behavior and interaction specs, Desktop and mobile
 - [Box link to Mary O'Donnell's functional specs](https://ibm.ent.box.com/folder/88263129224)
 - [US-English country list](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/usen-utf8.js)
 - [France-French country list](https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/frfr-utf8.js)
 - Asking Tina Williams to provide a merged country list.  [Issue 1820](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1820)

#### Acceptance criteria
 - [ ] Component has been tested using Netlify
 - [ ] The component development follows a modular component pattern
 - [ ] The component should be accessible via ES6 import
 - [ ] The component should be visible within the living documentation of the Dotcom components
 - [ ] Presented and approved Product Owner

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1821_

**Comment by jeffchew** [comment]
@kennylam did you end up building this out with your Locale Selector story?

cc: @RobertaJHahn

**Comment by RobertaJHahn** [comment]
@jeffchew  This issue has been sitting out here from awhile and has not been assigned to a sprint.  Do you know what is going on?
