### ISSUE TITLE
Cupcake disclaimer messaging

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#520]
_jamespistilli created the following on Oct 09:_  

 

#### User Story

 As a `web visitor of the forthcoming Cupcake website`:

 I need to:
Be alerted at the very beginning of the page that the contents below are part of a controlled adoption and subject to change, and should be treated as so.

 so that I can:
Be aware that the contents of the page is not finalized.

#### Additional information

 - [ ] Jim to provide a few options for disclaimer messaging, approved by @chsanche 

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1823_

**Comment by JennySanchez** [comment]
@jimpistilli Whenever you have the draft ready, please post the draft here.

**Comment by jimpistilli** [comment]
@JennySanchez Here are a few ideas:

![image](https://user-images.githubusercontent.com/32171262/66952000-aab7ac00-f029-11e9-909b-b532a2db63b2.png)

**Comment by JennySanchez** [comment]
@jimpistilli I like option one the best. Can we add something to address the content on the website is for IBM.com adopters only?

Option one = Please note that this page is part of a controlled adoption of the new Carbon Design System, and is subject to change.

@wonilsuhibm Any other thoughts?

**Comment by jimpistilli** [comment]
@JennySanchez I can, though anything from @wonilsuhibm before I do that?

**Comment by JennySanchez** [comment]
@jimpistilli No. Let's move forward with the next iteration, please.

**Comment by jimpistilli** [comment]
@JennySanchez As discussed:

_Please note that this page is part of a controlled adoption of the new Carbon Design System, and is subject to change. It is only for adopters of IBM.com at this time._

And reminding @wonilsuhibm we are ending the sprint so if you have any comments, if you could please let us know today (10/28).  Thanks.

cc: @ljcarot

**Comment by JennySanchez** [comment]
@jimpistilli Got it. Thanks.

**Comment by wonilsuhibm** [comment]
Thank you. One comment, regarding this part:
_...It is only for adopters of IBM.com at this time._

Should it be more like this:

_...It is only for DGC squads building IBM.com services and experiences._

**Comment by jimpistilli** [comment]
@wonilsuhibm Thanks.

@JennySanchez Below is updated copy, reflecting Wonil's comment.

_Please note that this page is part of a controlled adoption of the new Carbon Design System, and is subject to change. It is only for DGC squads building IBM.com services and experiences._

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.
