### ISSUE TITLE
Create a prioritized list of the components needed by Unified Search and Checkout Configurator Platform (CCP)for Carbon team

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#521]
_hahnrob created the following on Oct 10:_  

 

#### User Story

> As a `[user role below]`:
Carbon Offering Manager

> I need to:
receive a list of the components in priority order that factors in the Search and CCP needs

> so that I can:
schedule the Carbon theming work in a way that supports the DDS delivery commitments to their adopters

#### Additional information

 - link to the list???

#### Acceptance criteria
 - [ ] List provided to Carbon developer and Offering Manager

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1824_

**Comment by jeffchew** [comment]
_On Oct 10, hahnrob commented:_
@Olivia-Flory Olivia, we found out in our CCP status meeting today that they plan to use the expressive theme.  I have expanded the scope of this issue to include both Search and CCP.  I also increased the story point to 2.  Adjust as you think is needed.

**Comment by jeffchew** [comment]
_On Oct 10, Olivia-Flory commented:_
Thanks for the update @hahnrob 

Do you know which project(s) I should ask to review with Commerce squad? I thought they had quite a lot of pages/experiences they are looking into, do we know which are the priority / closest to being ready for development?

**Comment by jeffchew** [comment]
_On Oct 11, hahnrob commented:_
@Olivia-Flory The topic was brought up in the [Commerce Configurator Platform meeting yesterday](https://ibm.ent.box.com/notes/441915982996).  I think the analysis is needed for all of the Commerce squads, but the immediate need is for Search and CCP squads as they have the most immediate need.  To keep the scope of the work down in sprint 20 I have only included both the Search and CCP squads in this issue.  As an FYI, the Commerce squads are:  CCP, My IBM Products & Billing, Profile, Quote to Order, Self-Service Checkout, Product Support and URX.

**Comment by oliviaflory** [comment]
James and I met with the Unified Search team to review Lila's WIP designs. The following components will be needed:
### Unified Search
#### Core components
Tabs
- will need to alter equal width Carbon has on tab components

Checkbox
- Nixon will have to add background highlight, and potentially apply `$text-02` token to default checkbox 

Modal(s)
- Search tips modal – Lila would prefer if the background could be white
- Filter modal – would take over the screen on small breakpoints 

Buttons
- these are located within modal, could be fixed or fluid

Horizontal rule
- within modal
- both fluid and fixed sizes

Link
- anchor link
- back to top link (link + icon variant)
- text link (Search tips)

Pagination
- would like to use the more advanced pagination variant.

Tags
- filterable tags for small screen filtering.

---
#### Custom components
Block link or transparent tile, we will discuss options with Nixon
- transparent background
- hover state background change
- using `expressive-heading-03` styled like a link on default and hover

Single select
- filter categories where you can only choose one or none

**Comment by oliviaflory** [comment]
### Checkout 
**Needed**
- accordion
- button
- checkbox
- dropdown
- form
- icon button
- link
- loading
- tabs
- text input
- tooltip

**Likely needed**
- content switcher
- modal
- progress indicator

**Less likely needed**
- tag

----

### Other Commerce work streams
**Needed**
- list
- notification
- overflow menu
- search
- tile
- Shell or left panel 

**Likely needed**
- data table
- pagination
- number input
- radio button
- structured list

**Comment by oliviaflory** [comment]
**Consolidated list of components, items 1–10 are needed by both teams.**
1. buttons
2. links
3. tabs
4. checkbox
5. pagination
6. modals
7. tags
8. search
9. horizontal rule (dotcom library)
10. tooltip
---
11. accordion
12. dropdown
13. form
14. icon button
15. loading
16. text input
17. content switcher
18. progress indicator
19. list
20. notification
21. overflow menu
22. tile
23. Shell or left panel (dotcom library)
24. data table
25. pagination
26. number input
27. radio button
28. structured list
