### ISSUE TITLE
Work with Tina Williams to provide a consolidated country list

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#523]
_hahnrob created the following on Oct 10:_  

 

#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have a consolidated country list

> so that I can:
develop a utility that provides the translated display name of the country and language for the Locale Selector

#### Additional information

 - [Document the information needed in the merged country/language file](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1820)
 - [Develop a utility to provide the translated display name of the country & language](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1821)
 - MVP will include the country names and languages in English

#### Acceptance criteria
 - [ ] Meetings with Tina to 1)  agree to create the consolidated file needed by DDS development  2) agree to maintain the consolidated file on an ongoing basis  3)  define the date the file will be available 

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1826_

**Comment by RobertaJHahn** [comment]
@ljcarot @jeffchew Met with Tina Williams on Oct 16.  She does not have the staff to customize own a consolidated file for us, but agreed to work with us and Mary O'Donnell to refine the design and possibly include a smaller number of languages in the MVP.  If not possible, we can include English only in the MVP and get feedback from the Geo Rep's regarding the design.  (e.g. mentioned in the meeting.  We present the countries and languages in alphabetical order in the drop down list.  This order does not make sense in Japanese.)

**Comment by jeffchew** [comment]
Sent the attached files along to Tina and Miroslav's team regarding the consolidated country lists:

> We would like to move forward with having Miroslav's team managing the country lists if that is ok for everyone? I re-added the jsononly zip file for Tina's benefit, and in addition I have already created a version of usen that has the consolidated North America/Latin America lists into a single geographical area. 
>
>I created a quick script for sorting the country list alphabetically once combining the two regions together, which you can see here and can be applied to the other files:
>
> https://codepen.io/jeffchew/pen/oNNBLzL
> 
>Is there also an order in which these geo areas need to appear? (e.g. Americas first?) This will need to be represented in these JSON files, as the UI will render based on these data files including render order.

- [US/EN JSON data file](https://app.zenhub.com/files/193129061/acee3965-594f-4eda-86d9-9d77089cd885/download)
- [Zipped JSON files](https://app.zenhub.com/files/193129061/8bf799b6-6697-41a5-bc20-d68b04f203ea/download)

And received confirmation that we will be moving forward with Miroslav taking ownership of the data file updates. Also, Americas will be listed first in the geographic areas list.
