### ISSUE TITLE
Pattern:  Rich overview study part 2

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#525]
#### User Story

> As a `[user role below]`:
user of ibm.com

> I need to:
understand the benefits and value of the product / solution / offering presented on the page quickly through text and media such as video

> so that I can:
make a decision on whether I should continue with the page or not.

#### Additional information

 - [Pattern: rich overview, visual design study #393](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/393)
 - Add links to the additional info provided by Jill (needed from @larahanlon2)

#### Acceptance criteria
 - [x] Collect examples
 - [x] Identify design direction through exploration
 - [x] Incorporate Jill's feedback into the designs

**Comment by wonilsuhibm** [comment]
We should connect with Jill and Lila about their planned simple long form rich media exploration.

**Comment by larahanlon2** [comment]
Uploaded 100+ design studies on Wake and InVision for people to browse! 
**Wake:** https://ibm.wake.com/5267
**InVision board:** https://ibm.invisionapp.com/boards/9E3PPF9SGCX/

Moving this issue to `done` column as it is no longer a priority for development.

**Comment by larahanlon2** [comment]
Adding feedback from IDL (November 14 review)
- Start to align/connect these kinds of studies with IBM.org, originals team etc.
- Reserving the left 2–3 colums of grid for headline or TOC is a good approach
