### ISSUE TITLE
IBM design sites IA & nav structure

### ISSUE THREAD

**Issue by ScottBokma** [carbon-design-system/ibm-dotcom-library#536]
Per Elliott's ask to work with other internal design systems team to unify standard sites navigation and to work with Mike Abbink for overall vision. Mike assigned Sadek Bazaraa as the lead to work with, as well as the individuals listed below on the specific pieces listed below.

1. Interoperation/macro IA for Carbon, Brand Center and Experience Guides, with what gets handled where (Scott Bokma)
2. Carbon wedding cake IA (Jan Child & Scott Bokma)
3. Brand Center (Sadek Bazaraa leading that and we have something in a good place to test or get your thoughts on)
4. Experience Guides (Watson, Cloud, Security, Services)
We need the most help on the experience guides. With Maui Francis & Kelvin Chu (Watson/Cloud) and Haidy Francis (Security) both exploring on this but ultimately these sites need the same taxonomy and iA for the most part.

List created by Elliott (1) and Mike (2-4)

#### Acceptance criteria
 - [ ] IA and nav structure map
 - [ ] Possible prototype to show user flow/interactions

**Comment by ScottBokma** [comment]
Insight from Robin Cannon:
Jan is definitely the right point person from the Carbon side of things to be engaging with on IA, but it would also be useful to engage @Matt Rosno and @alison (Carbon OM and Dev Manager respectively) so that they have awareness.

Definitely interested in testing some of the ideas you have so far for feedback.

I think the distinction between the Design System level and Experience Guide level sites is where I've seen the most confusion; in particular a) experience guide sites overestimate how "unique" something is to their product or business unit, and don't surface universally and b) replication of material that is available at the Design Language or Design System level, when the Experience Guide should be more limited/specific in its content.

**Comment by ScottBokma** [comment]
Core users:
Carbon – developers & designers
Brand Center & Experience Guides – designers
IBM Design & IBM Design Language – designers

**Comment by RobertaJHahn** [comment]
@ScottBokma Unfortunately, you weren't able to present the results of your work in the sprint review meeting.  Did you finish the prototype?  Should I close this issue or move it to sprint 21?

**Comment by ScottBokma** [comment]
@RobertaJHahn I have a V2 sitemap and prototype finished. I can just walk Elliott through the work in a meeting and report the feedback here. 

We can close this issue.
