### ISSUE TITLE
Dot com pattern vertical spacing specs

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#537]
### user story
As a designer creating IBM.com layout patterns and templates, I need guidelines around proper vertical spacing so that what I design is consistent with the rest of the user experience.

### Acceptance criteria
- [ ] Spacing guideline for known patterns are published and available to designers.

**Comment by wonilsuhibm** [comment]
The first draft shared with IDL:

![ibm-dot-com--spacing-hierarchy--max](https://user-images.githubusercontent.com/30183447/67129533-f35b9a80-f1cc-11e9-8e0c-4b6a2ba62307.png)

![ibm-dot-com--spacing-hierarchy--xlg](https://user-images.githubusercontent.com/30183447/67129539-f6ef2180-f1cc-11e9-80a0-3b66e15ac556.png)

![ibm-dot-com--spacing-hierarchy--lg](https://user-images.githubusercontent.com/30183447/67129545-fa82a880-f1cc-11e9-83fb-a68cc9a7cf2d.png)

![ibm-dot-com--spacing-hierarchy--md](https://user-images.githubusercontent.com/30183447/67129555-fe162f80-f1cc-11e9-8834-7f7b4e6d8944.png)

![ibm-dot-com--spacing-hierarchy--sm](https://user-images.githubusercontent.com/30183447/67129560-02424d00-f1cd-11e9-8d4c-6f21636c6752.png)

**Comment by RobertaJHahn** [comment]
@wonilsuhibm Just wondering if I can close this issue or move it to sprint 21 because you need more time for reviews.

**Comment by wonilsuhibm** [comment]
We can close this, we have more than enough as MVP to continue the pattern works.
