### ISSUE TITLE
Create email accounts for DDS team and adopter support

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#539]
### The problem
We do not have a proper email address for our adopters to get in touch with our team.

### The solution
Create proper email address/addresses to meet adopter's needs.

### Additional information
Through a [Slack discussion](https://cognitive-app.slack.com/archives/GBG66T9NK/p1571080299082400):
- Jeff mentioned we have an email account for the engineering team.
- Olivia mentioned we need an email account for our team Sketch Cloud account.
- We know we need an email account for adopter support purposes.

👉 **Question:** Is there any other email accounts we need to create? 

### Resource:

- Document shared by Jeff on how to create an email account: https://ibm.ent.box.com/notes/493614117176

**Comment by RobertaJHahn** [comment]
The Leadership team has decided that adopter support requests will be submitted using Slack or Github issues.  Closing this issue.
