### ISSUE TITLE
[LinkWithIcon] Alignment of focus state

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#540]
## Detailed description

> Describe in detail the issue you're having.

The focus state isn't vertically centered around the link. The top margin is larger than the bottom margin, and ideally it would be equal.

Let me know if this isn't possible or if it's because of the line height. I would have thought the focus outline would be 22px high to match the line height

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

LinkWithIcon

## Steps to reproduce the issue

1. Go to https://ibmdotcom-react.netlify.com
2. View the LinkWithIcon story
3. Keyboard tab to the LinkWithIcon

## Additional information

<img width="354" alt="67017678-1bada100-f0c8-11e9-9ca6-bb57acacc7f6" src="https://user-images.githubusercontent.com/1641214/67119792-d9628d80-f1b5-11e9-9d60-1363cc5c0557.png">

Related to PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/532

**Comment by RobertaJHahn** [comment]
@oliviaflory engineering would like to see examples of this button within multiple contexts to prioritize and size.  Jeff will work with you on this.

**Comment by RobertaJHahn** [comment]
Will not be concerned about the inline treatment.  Will merge without the inline design.
