### ISSUE TITLE
Cupcake website page creation - Components/Masthead page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#542]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the masthead component

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.

#### Task
- Collaborate with @ScottBokma  for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the page with markdowns as the next step.

**Comment by jeffchew** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-website #14](https://github.com/carbon-design-system/carbon-for-ibm-website/issues/14) via [**ZenHub**](https://www.zenhub.com/)
