### ISSUE TITLE
Create a merged Clickable Tile specification

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#547]
#### User Story

> As a `[user role below]`:
As a DDS developer

> I need to:
have merged specification documentation for a clickable tile 

> so that I can:
develop a universal component that can be used across multiple components

#### Additional information

 - [final designs and specs](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)
              - Includes:  Functional labels, Visual redlines, Behavior and interaction specs, Desktop and mobile
 - [Carbon clickable tile](https://www.carbondesignsystem.com/components/tile/code#clickable-tile)
 - [discover pattern specs.sketch from Lila](https://www.ibm.com/cloud/virtual-servers-cloud/about-virtual-machines/index.html)

#### Acceptance criteria
 - [ ] Consolidated specs for the universal clickable tile component

**Comment by wonilsuhibm** [comment]
### Different card size behaviors, the first draft. @photodow please take a look and let me know if this makes sense or if you have questions.
![card-aspect-ratio](https://user-images.githubusercontent.com/30183447/67436636-df44de00-f5bc-11e9-86e2-9a44a217c43b.png)

**Comment by wonilsuhibm** [comment]
### Overall characteristics and behaviors
![tile-specs--content-types](https://user-images.githubusercontent.com/30183447/67685454-7fa75380-f96b-11e9-8961-bb0d5a9ca17e.png)

![tile-specs--interaction-types](https://user-images.githubusercontent.com/30183447/67685471-8766f800-f96b-11e9-961c-3c7277e0a5b3.png)

![tile-specs--sizing-behaviors](https://user-images.githubusercontent.com/30183447/67685476-8a61e880-f96b-11e9-9c04-8f5d459c97a7.png)

### Common specs
![clickable-tile-specs--white](https://user-images.githubusercontent.com/30183447/67685204-060f6580-f96b-11e9-9824-e66064b351a6.png)

### For Learn page
![clickable-tile--link-card](https://user-images.githubusercontent.com/30183447/67685524-9c438b80-f96b-11e9-9b39-ede71a95f589.png)

![clickable-tile--link-card--sm](https://user-images.githubusercontent.com/30183447/67685530-9ea5e580-f96b-11e9-8b92-d5c7767e5efd.png)

### For Locale selector
![clickable-tile--locale-selector](https://user-images.githubusercontent.com/30183447/67685547-a9607a80-f96b-11e9-9a47-1c980ee1963f.png)

![clickable-tile--locale-selector--sm](https://user-images.githubusercontent.com/30183447/67685552-ab2a3e00-f96b-11e9-8731-0b8efaacc174.png)

**Comment by wonilsuhibm** [comment]
@photodow @sannminwin Take a look and let me know if you have any concerns, questions, suggestions.

**Comment by RobertaJHahn** [comment]
Clickable tile presented in the Oct 28 sprint review meeting.  Closing
