### ISSUE TITLE
Customizable footer: research

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#556]
### Overarching user story
As an IBM.com user, I need to be able to see what else is available not only in all of IBM.com, but in the section that I am looking at currently, like Cloud, Watson, Security, etc.

### User story
As the DDS team, we need to understand what needs are there regarding customizable footer so that we can start designing a customizable footer.

### Acceptance criteria
- [ ] Different needs have been identified enough for UX design to begin.
- [ ] Appropriate next steps and corresponding user stories have been created.

**Comment by ScottBokma** [comment]
Documenting, visual mapping and IA of current alt-footers on IBM.com

Footers documented:
• IBM.com homepage
----Hero brands----
• IBM Watson
• IBM Cloud
• IBM Security
• Services
----Additional systems----
• IBM Cloud Garage
• IBM Developer
• IBM Blockchain
• THINK
• IBM iX
----Other footers----
• IBM Research
• IBM PartnerWorld
• IBM Security Learning Academy
• IBM Skills Gateway

[IBM_CurrentFooters_IA-mapping.pdf](https://github.com/carbon-design-system/ibm-dotcom-library/files/3799039/IBM_CurrentFooters_IA-mapping.pdf)

**Comment by ScottBokma** [comment]
Footer Audit findings
![auditFindings](https://user-images.githubusercontent.com/53090172/68051424-be1b7600-fcbd-11e9-975a-cb52f106448e.png)

Visual examples of alt-footers
![FooterAudit](https://user-images.githubusercontent.com/53090172/68051450-ca9fce80-fcbd-11e9-87e5-b694d192480a.png)

**Comment by ScottBokma** [comment]
Footer audit:
![auditFindings](https://user-images.githubusercontent.com/53090172/68053109-83b3d800-fcc1-11e9-82be-612dca151c3b.png)


Visual audit:
![FooterAudit](https://user-images.githubusercontent.com/53090172/68053115-89a9b900-fcc1-11e9-8efb-a77627f964b6.png)

**Comment by ScottBokma** [comment]
**Exploration of options for the footer supporting customizable elements from specific offerings.**
• Social icons/links (most common pattern on other sites)

**Outstanding questions:**
• What requirements are needed for a custom footer to be applied?
• Should ‘hero brands’ be the only approved custom footer?
• Should ‘additional systems’ have a custom footer?

-- Opt 1 at 1312px wide --
![Alt-footer_options_1312px-opt1](https://user-images.githubusercontent.com/53090172/68400795-9eb19c80-0146-11ea-9a6f-c85bc8402e94.png)

-- Opt 1 at 672px wide --
![Alt-footer_options_672px-opt1](https://user-images.githubusercontent.com/53090172/68400806-a40ee700-0146-11ea-88b2-607a237946b1.png)


-- Opt 2 at 1312px wide --
![Alt-footer_options_1312px-opt2](https://user-images.githubusercontent.com/53090172/68400817-a8d39b00-0146-11ea-9480-a6219eceb1fe.png)

-- Opt 2 at 672px wide --
![Alt-footer_options_672px-opt2](https://user-images.githubusercontent.com/53090172/68400831-ae30e580-0146-11ea-8234-b65baff8a9f5.png)


-- Opt 3 at 1312px wide --
![Alt-footer_options_1312px-opt3](https://user-images.githubusercontent.com/53090172/68400847-b38e3000-0146-11ea-8de4-d51a4c09c439.png)

-- Opt 3 at 672px wide --
![Alt-footer_options_672px-opt3](https://user-images.githubusercontent.com/53090172/68400857-b852e400-0146-11ea-8025-4fe28fd6936d.png)
