### ISSUE TITLE
[ButtonGroup] Update ButtonGroup story to add/remove buttons

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#558]
@jeffchew don't kill me for suggesting this, but it might be good if we could provide an option to add or remove buttons.

```javascript
const buttonCount = number('Number of buttons', 2);
const buttons = [];

for (let i = 0; i < buttonCount; i++) {
  buttons.push({
    link: text(`Link ${i+1}`, `https://example.com`),
    copy: text(`Button ${i+1}`, `Button ${i+1}`),
    renderIcon: iconMap[select(`Icon ${i+1}`, iconOptions, iconOptions['Arrow Right'])],
  })
}
```

_Originally posted by @photodow in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjA3OTI2MTczOnYy/pull_request_review_threads/discussion_

**Comment by RobertaJHahn** [comment]
Design question:  @wonilsuhibm Do we want to have this flexbility?

**Comment by photodow** [comment]
@RobertaJHahn @wonilsuhibm I believe this only for demo purposes using storybook knobs. The component itself already has the capability of adding or removing buttons depending on the object you pass in.

**Comment by emerson-pereira** [comment]
Created PR #851
