### ISSUE TITLE
Masthead and footer do not work as expected when Javascript is disabled

### ISSUE THREAD

**Issue by ncheaz** [carbon-design-system/ibm-dotcom-library#614]
## Detailed description

There are two separate issues when Javascript is disabled:

- The masthead search is unusable, clicking on the magnifying glass will not expand the searchbox, so no text can be entered manually

- The footer is missing all links

For the masthead search, it would be nice to have the option to post to a custom URL when pressing enter or clicking on the magnifying glass

For the footer, it would be nice to have the links render as usual, and the locale selector work do a navigation to the appropriate localized page.

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
ibmdotcom-react version "1.1.0-rc.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM.com search
You can see the beta for ibm dotcom library migration here and try out with Javascript disabled:  https://ibm-com-search-beta.mybluemix.net/search?lang=en&cc=us&q=search%20probe

## Steps to reproduce the issue

1 Disable Javascript in your browser.
2. Got to https://ibm-com-search-beta.mybluemix.net/search?lang=en&cc=us&q=search%20probe
3. Try to enter a search term
4. Look at the footer and see no links

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@ncheaz for the Masthead, as we discussed there are newer features address in the `v1.1.0` release that may resolve your problems there. This includes the `searchOpenOnload` prop, and the `SEARCH_REDIRECT_ENDPOINT` environment variable that exposes the updating of the redirect url for the form post.

For the footer, we spoke internally about it and think that there is an SSR issue with the footer, and created this story: https://github.com/carbon-design-system/ibm-dotcom-library/issues/616

cc: @ljcarot @wonilsuhibm @andysherman2121 @ScottBokma

**Comment by RobertaJHahn** [comment]
SSR fix in [Issue 616](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/616) is included in [ibm.com Library v1.1.1 patch](https://github.com/carbon-design-system/ibm-dotcom-library/issues/617)

Closing this issue.  Will create a new issue if Nixon has any issues related to the recommendations provided by Jeff.
