### ISSUE TITLE
[FeatureFlag] Expand functionality of the featureFlag utility

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#618]
If we want the feature flag in a broader scope like stories, then maybe we could look at expanding the `featureFlag` utility function. I only used JSX when creating it because that's all I thought we'd be using it for at the time. We could maybe move to a callback approach.

```javascript
function featureFlag(flag, cb) {
  if (flag) {
    if (typeof cb === 'function') {
      return cb(flag)
    } else {
      return cb;
    }
  }

  return null;
}
```

_Originally posted by @photodow in https://github.com/carbon-design-system/ibm-dotcom-library/timeline_

**Comment by jeffchew** [comment]
@photodow This might actually be a good huddle discussion before we proceed on this.

**Comment by photodow** [comment]
Ok, cool. I added it to Monday's agenda, and also quickly put together and RFC #623 for the team to review ahead of it.
