### ISSUE TITLE
In Carbon search box, placeholder text needs to be translated as per the locales

### ISSUE THREAD

**Issue by alainmachu** [carbon-design-system/ibm-dotcom-library#631]
The placeholder text in the search box (Search...) is always in English whatever locales we are in.
It should be translated as per the locales (French for fr-fr, German for de-de, etc.). 

![place hlder text to be translated](https://user-images.githubusercontent.com/48733809/68250262-8fb7d680-ffee-11e9-97e9-18d01efa79f4.jpg)

**Comment by annawen1** [comment]
@jeffchew @kennylam not sure where the translated text for search placeholder is coming from...I looked at the results from the `TranslationAPI` but all I can find is `search: "Search"` under `misc` key which doesn't seem like it gets translated.

<img width="562" alt="Screen Shot 2019-11-06 at 2 28 42 PM" src="https://user-images.githubusercontent.com/54281166/68330747-c4d13100-00a1-11ea-9a18-14af6fe51c9b.png">

**Comment by jeffchew** [comment]
Hi @alainmachu , after @kennylam dug into this, we discovered that the placeholder translation is not available in the translation files. We will be reaching out to the translation team that currently owns the management of these files (which are also shared with v18), and see if we can get translated placeholder text. In the meantime, @kennylam has exposed the placeholder text as a prop which can be updated externally. By default, it will fall back to english.
