### ISSUE TITLE
Masthead (and DotcomShell) briefly renders and disappears

### ISSUE THREAD

**Issue by jcpalaci** [carbon-design-system/ibm-dotcom-library#634]
## Detailed description

> Describe in detail the issue you're having.

When I try to implement `DotcomShell` or `Masthead`, the component doesn't render properly, it briefly shows on screen but then it disappears. I can also replicate this behavior in https://ibmdotcom-react.netlify.com/

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Masthead (and DotcomShell)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Masthead (and DotcomShell) rendering properly

> What browser are you working in?

Safari, Chrome, Firefox

> What version of the IBM.com Library are you using?

1.1.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com search

## Steps to reproduce the issue

See Additional information

## Additional information
 - **The scope of this ticket will be to create a hotfix to default to us-EN if there are any rendering issues based on invalid translation data.**

- Screenshots or code

Using this test page:
```
import React from 'react';
import { DotcomShell } from '@carbon/ibmdotcom-react';
import '@carbon/ibmdotcom-styles/scss/components/masthead/index.scss';
import '@carbon/ibmdotcom-styles/scss/components/footer/index.scss';
import '@carbon/ibmdotcom-styles/scss/components/dotcom-shell/_dotcom-shell.scss';

export default class App extends React.Component {
  render() {
    return (
      <DotcomShell navigation={'default'} footerType="short">
        Hi there!
      </DotcomShell>
    );
  }
}
```
I'm getting this error (`Cannot read property 'megapanelContent' of undefined`):
![image](https://user-images.githubusercontent.com/57272532/68311906-df8eb000-0077-11ea-90a2-57b2690084e0.png)

If I use `navigation={null}` that seems to clear the error. But if I add a `lang="en-US"` in the HTML tag, then I see a different error (Cannot read property 'trim' of undefined):
![image](https://user-images.githubusercontent.com/57272532/68313585-6d6b9a80-007a-11ea-988e-be12a118e833.png)

If I disable the search box (`hasSearch={false}`), then the Masthead shows OK this time.

- Notes

I'm located in Guadalajara, Mexico; working from home. Later today will test in the office (where usually I got an IP from the US)

**Comment by jeffchew** [comment]
@jcpalaci Adding in notes here (@kennylam please add in any additional details), this seems to be an issue with inconsistencies with translation data, specifically for Guadalajara, Mexico. The data used is the same as what is used for v18, so this is a pre-existing issue but the work here is to create more defense code around when the data structure for translations do not match most other regions.
