### ISSUE TITLE
Add data-autoid attributes to optional fields for Patterns

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#637]
### The problem
When the Drupal Core Team is generating twig templates from the IDL React Pattern Apps, some of the knobs in the pattern markup are optional fields.  When we convert these optional fields into Drupal Twig Templates we would need a selector for our automation to inject twig conditional statements to render that field's markup depending on whether the content for that field exists in Drupal.

### The solution
Per conversation with @jeffchew  the solution we propose is for IDL team to inject data-autoid for each optional field/knob at 2 places:

1.  The tag where that optional knob is being rendered
2.  The nearest parent div for that tag.

So for example in the Lead Space pattern there is the following markup generated by the react pattern:

<div class="bx--leadspace__row" > <p class="bx--leadspace__desc" data-autoid="leadspace__description">[KNOB VALUE]</p></div>

we would like to modify it to look like this:

<div class="bx--leadspace__row"  **data-autoid="leadspace__description_container"**> <p class="bx--leadspace__desc" **data-autoid="leadspace__description**">[KNOB VALUE]</p></div>
          

### Additional information
We would like for this feature to be propagated to all 6 patterns being delivered in the 12/6 release.

**Comment by nmangold** [comment]
I'm not sure we need the data-autoid attribute on the (1) tag where the optional field is being rendered, or necessarily (2) the nearest parent. 

We need the data-autoid attribute, or a unique selector, on the outermost container that contains only the optional field. For several of the patterns I've seen so far, this is usually the row container. However, that would not be the case with inline elements.

The goal is to hide the container markup for the optional field if the field is empty, but not if the container contains other elements that may or may not  be empty.

**Comment by jeffchew** [comment]
@RobertaJHahn fyi, Drupal team is requesting if we can fit this into our next sprint.

cc: @ljcarot @wonilsuhibm
