### ISSUE TITLE
Write the logo grid functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#645]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have logo grid functional specifications 

> so that I can:
correctly develop the logo grid pattern

#### Additional information

 - The functional specs will be worked on in parallel with the design specs Issue (#2032)
 - Dev Issue (#1846)

#### Acceptance criteria
- [ ] Documented `Logo grid` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by RobertaJHahn** [comment]
Not stale.  Waiting to schedule when resources available.

**Comment by ellenchoi1** [comment]
version 1.0 of func specs uploaded to box: https://ibm.box.com/s/2c2dt2fivbmbcce29oul7hjaktjaqj26

**Comment by ellenchoi1** [comment]
minor updates made to version 1.0, based on discussions in engineering review, uploaded to box: https://ibm.box.com/s/2c2dt2fivbmbcce29oul7hjaktjaqj26. refer to change log for details of updates.
