### ISSUE TITLE
Pattern:  Content array with pictograms design provided by Web Simplification

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#650]
#### Notes
 - Lila is the web simplification designer.  This issue is to track the transition of the design work to the DDS engineering team members.  

#### Additional Information
 - [Design specs](https://ibm.ent.box.com/folder/89982493307)

#### Acceptance Criteria
 - [x] Specs received from Web Simplification and reviewed with DDS engineering

**Comment by wonilsuhibm** [comment]
The visual specs are available [here](https://ibm.box.com/s/ai326isog3uovcgvhuq82e26x6fwb0j0)

**Comment by wonilsuhibm** [comment]
This story was completed in sprint 18. Closing.

**Comment by RobertaJHahn** [comment]
Meeting conducted with Lila and DDS team Nov 21, 2019.
