### ISSUE TITLE
Pattern: final development of content group - with pictograms

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#651]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library

> I need to:
have a content group - with pictogram pattern that can be used

> so that I can:
leverage it within my application

#### Additional information

![image](https://user-images.githubusercontent.com/3793636/69695600-e9ba3200-10aa-11ea-9f5d-11445bdac4fc.png)

 - [Pictogram Array Functional Specs](https://ibm.box.com/s/xngulixjv6oem8sdgreoslw2tu9d6udr)
 - Pictogram Array Visual Specs [[sketch](https://ibm.box.com/s/iyrjxcp1lwymla8891hgsyl8bl4m0fvn)][[png](https://ibm.box.com/s/ai326isog3uovcgvhuq82e26x6fwb0j0)]
 - Content group #745 
 - Pictogram object #744
 - Markdown utility #743

#### Acceptance criteria
 - [ ] tested React component within the Patterns Storybook
 - [x] Story within Storybook with corresponding knobs
 - [ ] minimum 80% unit test coverage
 - [x] Utilize Carbon
 - [ ] Content Group with title
 - [x] List of Pictogram Content Objects
 - [x] Part of `@carbon/ibmdotcom-patterns`
 - [ ] Design, Development, & OM Approved

**Comment by photodow** [comment]
@RobertaJHahn @jeffchew based on #680 I broke this story down into a couple of stories #745, #744, #743, updated the description with the correct links and updated its dependencies and acceptance criteria.

**Comment by RobertaJHahn** [comment]
Obsolete.  This work is being managed under the ontology refactoring effort.  Issue (#1158)
