### ISSUE TITLE
Pattern: Content array with cards design provided by Web Simplification

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#653]
### Notes
 - Lila is the web simplification designer.  This issue is to track the transition of the design work to the DDS engineering team members.  

#### Additional Information
 - [Link to Design Specs](https://ibm.ent.box.com/folder/90717785380)

#### Acceptance Criteria
 - [x] Specs received from Web Simplification and reviewed with DDS engineering

**Comment by wonilsuhibm** [comment]
The latest specs are [here](https://ibm.box.com/s/gy1nsj9em79yi0zdn0oi7k8as934lx9i)
