### ISSUE TITLE
Carbon website cupcake vision (IA)

### ISSUE THREAD

**Issue by ScottBokma** [carbon-design-system/ibm-dotcom-library#669]
Working with Jan Child and Jean Ann Servaas to clean-up, align and unify Carbon and DDS IA as the two sites merge. Primarily focused on Pattern content and structure at this time for the DDS to publish content on the Carbon site.

**Comment by ScottBokma** [comment]
Meeting on 11/11 @ 5:30pm EST on the topic of Carbon website cupcake vision

**Agenda:**
• Carbon and Digital website strategy for bringing/publishing Digital content onto the Carbon site

**Attendies:**
Alison Joseph – Carbon
Jean Ann Servaas – Carbon
Jan Child – Carbon
Robin Cannon – Carbon

Changchen H Sanchez – Digital
Jacob Ottesen – Digital
Wonil Suh – Digital
Scott Bokma – Digital

Mike J Abbink – IDL
Sadek Bazaraa – IDL/Brand

**Comment by ScottBokma** [comment]
Meeting with Jan and Jean on Friday 11/15 to begin documenting alignments and mis-alignments on the current Carbon and DDS IA structure. Create a baseline and next steps to support merge and publication of site content.

**Comment by ScottBokma** [comment]
Documenting on the latest sitemap Jan has shared with Jenny's work on the pages/content DDS is looking to migrate onto the Carbon site. As well as noting questions I have on Jan's sitemap.

![Carbon-sitemap-withDDS-mirgation](https://user-images.githubusercontent.com/53090172/69360335-5cb14c00-0c58-11ea-8371-9fb9290a605b.png)

**Comment by ljcarot** [comment]
When can we start adding our Patterns to their website? @ScottBokma

**Comment by ScottBokma** [comment]
@ljcarot When we have access to do so and then content is ready, which either needs to be in the current page format they have or the future one they are working on (which still seems to change a bit: lots of discussions around anchor tags and when they should be located). Also need to cross check our patterns aren't similar to their current/future ones and are organized within the same categories.
