### ISSUE TITLE
Documentation folder structure

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#676]
### User story 1: developer
As a developer building out IBM.com library components and patterns, I need a clearly marked single destination where I can find all of the necessary information such as functional specs and visual specs in one location.

### User story 2: adopter
As an adopter of the IBM.com library working on an innovation project such as Web Simplification, Knowledge Center, Smart papers, or in-product documentation, I need a well organized single location where all the relevant information such as functional specs, design specs, research data, etc are stored to that I can design and innovate within standards efficiently.

### Note
- This story is to create a clean and scalable folder structure to store the following items:
   - functional specs
   - design specs
   - research data
   - design iterations
- Naming convention should be included
- It was decided by the Carbon for IBM.com team leadership that this folder structure should be on IBM Box and only available to IBM employees.
- There will be one branch for components and one branch for patterns
- Each deliverable such as the masthead or the use case pattern will have one folder to host all artifacts
   - Functional specs and visual specs on the root level of the deliverable's folder
   - Research and design iterations in subfolders
   - Links to artifacts that exist outside of Box ecosystem, such as storybook demo, invision prototype, etc, should be collected in a single Box Note on the deliverable's root level
- The previous explorations are captured in this [Box Note](https://ibm.box.com/s/8mpuxpa28g3jzdgkz67xx4k3pdhxjlf1)

### Acceptance criteria
- [ ] Folder structure with the following items covered is presented to and agreed upon by the team

**Comment by wonilsuhibm** [comment]
https://ibm.box.com/s/jppwd8hy0jeg2dlq2kgdtismcloipqmn

**Comment by ScottBokma** [comment]
Shouldn't we include the Carbon team in this folder structure conversation? As we merge the two site together...the folder structure should mirror parts of the site. So users aren't having to learn/navigate two different architectures to find the same content.

Have made comments in the box note using purple text.

**Comment by wonilsuhibm** [comment]
@ScottBokma yes we will. Let’s take a look internally and be aligned among ourselves first though.

**Comment by JennySanchez** [comment]
Looking good, @wonilsuhibm . I added comments in the Box doc.

**Comment by wonilsuhibm** [comment]
Reaching out to Jean A Servaas regarding Carbon practices.

**Comment by wonilsuhibm** [comment]
Carbon team does not seem to have any standards. Invited Jeannie and her team to add their thoughts as well.

**Comment by wonilsuhibm** [comment]
The link was fixed: https://ibm.ent.box.com/notes/557480296942

**Comment by wonilsuhibm** [comment]
Updated version to be shared in the squad huddle: https://ibm.box.com/s/xgnu4jldoou55leypgefpen989jq4je5
