### ISSUE TITLE
Pattern:  Create the Content Array (a.k.a. list section) with Pictograms functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#680]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have Content Array with Pictograms functional specs 

> so that I can:
so that I can properly code the content array with pictograms pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Learn-page-layout-pattern-roadmap#content-array-with-pictograms--epic-649--details-specs--research) - _This URL may change as this linked wiki page may move to the public github_
 - Design & engineering review meeting recording](https://ibm.ent.box.com/notes/558080021243)

#### Acceptance criteria
 - [ ] Documented functional content array with pictogram specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable

**Comment by RobertaJHahn** [comment]
Design / engineering meeting conducted Nov 19, 2019

**Comment by RobertaJHahn** [comment]
@photodow Can you please add the link to the specs in the Additional Information section above.  Development will be picking up the follow-on dev story in the next sprint beginning Monday, Nov 25.

**Comment by photodow** [comment]
Created new stories #743, #744, #745, and updated #651. 

Here are the functional specs: https://ibm.box.com/s/xngulixjv6oem8sdgreoslw2tu9d6udr

Sorry I didn't get this to y'all last week!

**Comment by RobertaJHahn** [comment]
Airtable updated with the new issues created by James.  Can be closed.
