### ISSUE TITLE
Pattern: Create the Content Array with cards functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#681]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have Content Array with cards functional specs 

> so that I can:
so that I can properly code the content array with cards pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Learn-page-layout-pattern-roadmap#content-array-with-cards--epic-652--details-specs--research) - _This URL may change as this linked wiki page may move to the public github_
 - [Nov 13 Design and Engineering review meeting recording](https://ibm.ent.box.com/notes/558080021243)

#### Acceptance criteria
 - [x] Documented content array with cards functional specifications
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [x] Final changes from reviewing team members included in the functional specs, if applicable
 - [x] Roadmap wiki is updated

**Comment by photodow** [comment]
@RobertaJHahn I pulled out the card link functional specs work so we can reference it later and created issue #768 to track that.

**Comment by photodow** [comment]
Here is the link for the Card Array functional specs: https://ibm.box.com/s/px2557guu928pwu3umr71t255u409teu
