### ISSUE TITLE
Pattern:  Create the Cards with Images functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#682]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the Cards with Images functional specs 

> so that I can:
so that I can properly code the content array with cards pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Learn-page-layout-pattern-roadmap) - _This URL may change as this linked wiki page may move to the public github_
 - 

#### Acceptance criteria
 - [x] Documented cards with images functional specifications
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [x] Final changes from reviewing team members included in the functional specs, if applicable
 - [x] Roadmap wiki page is updated

**Comment by photodow** [comment]
@jeffchew @wonilsuhibm @RobertaJHahn based on discussions this week I'm thinking about applying this to epic #470, and combing the functional specs for these two epics. #470, #655. Thoughts?

**Comment by jeffchew** [comment]
> @jeffchew @wonilsuhibm @RobertaJHahn based on discussions this week I'm thinking about applying this to epic #470, and combing the functional specs for these two epics. #470, #655. Thoughts?

I think this is where we are headed, just need to figure out the right name for it.

**Comment by jeffchew** [comment]
Just clarifying that these are the specs now right?
https://ibm.ent.box.com/file/593899274020

**Comment by photodow** [comment]
@jeffchew the link up there doesn't seem to work for me, but I saw your comments and I believe I addressed them. I'm moving to to done, but feel free to reach out if we need any other changes to be made.

https://ibm.box.com/s/1mywz2npzb3fzbz9gh94a6nfqndcvgiu
