### ISSUE TITLE
Pattern:  Create the Featured Link functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#683]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the Featured Link functional specs 

> so that I can:
so that I can properly code the Featured Link pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Pattern-roadmap) - _This URL may change as this linked wiki page may move to the public github_

#### Acceptance criteria
 - [ ] Documented Featured Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
 - [ ] Pattern roadmap wiki page is updated

**Comment by photodow** [comment]
Here are the [FeaturedLink functional specs](https://ibm.box.com/s/tlv7h1zgc886l5ovcap08uc1x97jpdo2). Let me know if there are any questions.
