### ISSUE TITLE
Component:  Create Lightbox component functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#688]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have documented functional specs for the lightbox component

> so that I can:
develop a component that accurately reflects the design

#### Additional information

 - The functional specs would be created along with the design specs.  [issue #326](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/326)

#### Acceptance criteria
 - [x] Documented functional specs for lightbox media viewer
 - [x] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments

**Comment by wonilsuhibm** [comment]
Hey James, the design for the MVP (no carousel, just a single image media viewer) is here: https://ibm.box.com/s/mpeo1wy0jogkwxn68fahlg62q799ixox

**Comment by photodow** [comment]
@wonilsuhibm is this a new component?

![image](https://user-images.githubusercontent.com/3793636/69981268-9eaf7d00-14f7-11ea-9e10-97bd4250b754.png)

**Comment by photodow** [comment]
@wonilsuhibm updated prototype based on what I'm seeing in the visual designs? Let me know if that's what you're expecting.

https://codepen.io/photodow/full/abbQqpz

**Comment by photodow** [comment]
Here is the link to the Lightbox functional specs. As mentioned on last weeks standup I'm still missing any changes to the responsive behavior.

https://ibm.box.com/s/hq4eq9fdgb279o40h5ur5eonpo58359e
