### ISSUE TITLE
IDL layout guideline absorption

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#697]
### User story
As a maker of an IBM experience in digital space, I need to understand how to create layouts that properly express IBM's philosophies and principles and ultimately help our customers.

### Notes
- This story is to study, understand, and strategize on how we can adopt IDL layout principles in the digital space.
- It will be a good idea to work with Carbon team designers or at least share.

### Acceptance criteria
- [ ] Strategy for adopting [IDL layout guidelines](https://deploy-preview-344--design-language-website.netlify.com/design/language/elements/layout/overview/)

**Comment by larahanlon2** [comment]
As per discussion, this story was added mid-sprint 22 so will need to roll over to 23.

**Comment by larahanlon2** [comment]
Identified a number of layout patterns for ibm.com that align to IDL principles. Ideally these could be combined with Wonil's layout examples to form the `layout overview` page for the cupcake website. Sketch file is [here](https://ibm.box.com/s/5axrui6992nrbhl8yecz08c3yw2h7cr4). 

<img width="1242" alt="Screen Shot 2019-12-04 at 7 00 34 PM" src="https://user-images.githubusercontent.com/53093550/70192084-a8d4a580-16c8-11ea-8479-f52c4db64274.png">
