### ISSUE TITLE
Component:  Develop standalone picture image - alpha version - Sprint 20-02

### ISSUE THREAD

**Issue by sannminwin** [carbon-design-system/ibm-dotcom-library#699]
Not urgent for this PR, but I can see this as a standalone component that can be reused.

_Originally posted by @jeffchew in https://github.com/carbon-design-system/ibm-dotcom-library/pull/689_

**Comment by ljcarot** [comment]
@wonilsuhibm @RobertaJHahn @jeffchew We have functional spec in progress for this component.  Do we have a visual spec too? Do we need one?

**Comment by jeffchew** [comment]
@photodow do you already have a story for this? This might be a duplicate.

**Comment by photodow** [comment]
@jeffchew this is not a duplicate. It's basically the development work that'll need to be done to create the component once the functional specs and such are done.

@ljcarot I know Wonil has already done some design work around this, and it looks like there may be more queued up to do more.

Here's the epic #746. It looks like there might still be some work to be done in #747, and #746.

Here is the [box folder](https://ibm.box.com/s/zaofzs8ssrfbkgker2lqxyvdnbpxvsly) with initial work around the component it looks like.

@wonilsuhibm feel free to elaborate on anything I might have missed.

**Comment by ljcarot** [comment]
If this is the dev story, we'll need to just clean up the naming of the component across the different issues.  @RobertaJHahn let me know if you have this component in AirTable.  I'm also going to add Web Simplification label.

**Comment by RobertaJHahn** [comment]
@ljcarot These issues and the epic are not in Airtable.  The comment in the Epic says that the work will not be introduced until 1Q2020.  We have not talked about this work yet in the roadmap planning meetings.  Agree with you that we should be naming things consistently.  Why are some issues called an `embeddable image component` and others are called a `responsive picture component`.

**Comment by ljcarot** [comment]
Not trying to raise alarm that this was missed.  I see it coming in from Web Simplification as something they will hand off to our team on or before Jan 17 so this is going to be likely priority for February Release.

**Comment by jeffchew** [comment]
I marked this under the v1.4.0 release.

**Comment by RobertaJHahn** [comment]
Obsolete.  Replace by the refactoring work.  Issue (#1148)
