### ISSUE TITLE
Pattern: Develop an alpha version of the cards with images

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#705]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
work closely with the Functional Analyst and designer to begin developing the cards with images

> so that I can:
become involved earlier in the design process and functional documentation to compress the schedule and develop a higher quality pattern

#### Additional information

- Story within Storybook with corresponding knobs
- minimum 80% unit test coverage
- Utilize Carbon
- [Content array with cards design story #656](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/656)
- [Content array with cards functional specs #682](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/682)

#### Acceptance criteria
 - [ ] alpha react component within the Patterns storybook
 - [ ] create a feature flag for this component
 - [ ] Gap analysis of alpha code and design & functional specs
 - [ ] If applicable, create and size stories for additional work

**Comment by mkothur** [comment]
PR Link (https://github.com/carbon-design-system/ibm-dotcom-library/pull/803)
