### ISSUE TITLE
Pattern: Develop an alpha version of the featured link

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#706]
#### User Story
> As a `[user role below]`:
DDS developer

> I need to:
work closely with the Functional Analyst and designer to begin developing the Featured link

> so that I can:
become involved earlier in the design process and functional documentation to compress the schedule and develop a higher quality pattern

#### Additional information
- Design specs [[sketch](https://ibm.box.com/s/22eumjqkfj273y9s3251zwgyz3zc7q0n)] [[png](https://ibm.box.com/s/rucd65orwmstyf6eesrelpm9wsrw4h32)] [#659]
- Featured Link functional specs #683

#### Acceptance criteria
 - [ ] alpha react component within the Patterns storybook
 - [ ] create a feature flag for this component
 - [ ] Gap analysis of alpha code and design & functional specs
 - [ ] If applicable, create and size stories for additional work

**Comment by photodow** [comment]
@carthick I updated the design specs up here to reflect what I have. There are actually two things to keep in mind with this that I'll be exploring through the functional specs work this sprint. I see this component having a dependency on the following two components. Reach up if you got any questions, and if we need to sync up.

 - #767 the responsive/embeddable image component
 - #768 Card Link component
