### ISSUE TITLE
Masthead L1 "title chip" needs hover state

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#711]
Current masthead L1 has no hover state for the main page title (dark chip zone). Missed this during design and spec phase! It will need to be added for design kit and future dev updates.

**Comment by larahanlon2** [comment]
@oliviaflory @wonilsuhibm 

I have three options for this (hover only, not focus). Thoughts? Other suggestions welcome!
![masthead--L1--title-hoverV1](https://user-images.githubusercontent.com/53093550/69192296-4b4e2f80-0af2-11ea-8de2-6054eb5f844d.png)

**Comment by wonilsuhibm** [comment]
Thank you, Lara.

I like options 2 and 2 (I'm guessing this is 3. :) ) Would love to see a quick motion demo of option 3 though. I like the celebratory aspect of the blue bar and the implied message that the whole thing is clickable.

**Comment by oliviaflory** [comment]
I like option 2, I think the overall background change would work better when there is an eyebrow. I wondered if the eyebrow would look funny on hover in option 1.

Question about option 3 does the blue bar span the width in selected and hover? Or does it span only under the text and expand to the full width of the background on hover? 

This might be a moment where we need to have a unique focus color, for the dark themes focus is white, but it get's pretty lost in the title chip.
<img width="1459" alt="Screen Shot 2019-11-20 at 12 38 34 PM" src="https://user-images.githubusercontent.com/45692622/69264657-bf8ddf00-0b95-11ea-8cc3-990d43c27d46.png">



----
On a different topic, I've been wondering about the size of the card, and how it's being implemented on dev side. 
Would it be easier to define a minimum padding (like button), with a minimum width and max width *vs* defining the size based on the columns?

**Comment by wonilsuhibm** [comment]
One additional thought: the full width blue bar may muddy the fact that there are two distinct interactive elements in the title card - the title and the back arrow.

As for the card size, it should be a rubber band with a `min-` and `max-width`.

**Comment by larahanlon2** [comment]
Thaaaaank you both.
I like option 2 or 3, slightly more on the 3 side.

Yeah, I don't think white focus is working here, it's barely noticable so I agree we would need a unique focus state. Thank you for whipping that up @oliviaflory! 

For option 3 I was thinking that the blue underline would just be full-width on default and then on hover the background only would change color state. Then, on focus the blue underline would disappear because the whole chip would have a 2px blue border. 

So for the size of the card this is what I spec'd up originally:
- The chip would have an internal min-padding-right of 64px at all times.
- However, the whole thing can't grow smaller than 3 columns + 16px padding-right _or_ 208px (if not using columns) and it can't grow wider than 4 columns + 16px padding-right _or_ 336px.

<img width="572" alt="Screen Shot 2019-11-20 at 1 25 49 PM" src="https://user-images.githubusercontent.com/53093550/69267111-8310b200-0b9a-11ea-8734-f0925272335f.png">
<img width="594" alt="Screen Shot 2019-11-20 at 1 34 08 PM" src="https://user-images.githubusercontent.com/53093550/69267145-93289180-0b9a-11ea-8cf0-578b82595a22.png">
<img width="542" alt="Screen Shot 2019-11-20 at 1 33 48 PM" src="https://user-images.githubusercontent.com/53093550/69267155-97ed4580-0b9a-11ea-85da-5f6290368fac.png">


I think it needs both a set padding between the title text and title edge AND min-max width between the chip and the rest of the L1 because otherwise something like this could happen if it's only based on padding-right:
<img width="675" alt="Screen Shot 2019-11-20 at 1 37 51 PM" src="https://user-images.githubusercontent.com/53093550/69267352-f74b5580-0b9a-11ea-9dfc-2c4c00946d52.png">

☝️Without a min total width of the chip itself, small page titles/L1 labels could create this really awkward size. It's not obviously left-aligned but it's not exactly centered...

Hope that all makes sense.

**Comment by wonilsuhibm** [comment]
Why 3 columns? A lot of pages will be using 4-12 layout, doesn't it make sense to max at 4 columns?

**Comment by wonilsuhibm** [comment]
https://ibm.box.com/s/mpeo1wy0jogkwxn68fahlg62q799ixox

**Comment by larahanlon2** [comment]
@wonilsuhibm yep that's what I proposed:
_...it can't grow wider than 4 columns + 16px padding-right or 336px._

But we need a minimum for the chip which is where the 3-col came from. If we have everything set to 4-col regardless of title character size then this will happen – the chip is super wide:
<img width="1329" alt="Screen Shot 2019-11-21 at 10 43 51 AM" src="https://user-images.githubusercontent.com/53093550/69353035-dee74380-0c4b-11ea-89a5-428c79b6da52.png">

We did agree a long time ago that we can't rely on aligning to columns only because navigation cannot be controlled in the same way as page content. So we need internal padding and external min-max width, right?

**Comment by larahanlon2** [comment]
This story will need to be added to sprint 23.

**Comment by larahanlon2** [comment]
Testing out hover state with the eyebrow. My preference is with 3 or 5. 

![xlg-1312px-16 column copy 65](https://user-images.githubusercontent.com/53093550/69827935-a5807c00-11e7-11ea-97ba-08f1bc515199.png)
![xlg-1312px-16 column copy 66](https://user-images.githubusercontent.com/53093550/69827936-a5807c00-11e7-11ea-9c83-0a1e56b7d133.png)

**Comment by wonilsuhibm** [comment]
Thank you @larahanlon2. Visually, I like 3 and 5. Affordance-wise, I'm not so sure. In this regard, 2 makes the most sense to me. Can we do some testing, show these options, ask what users expect to happen, and if they understand that there are two separate actions here?

**Comment by larahanlon2** [comment]
@wonilsuhibm @oliviaflory @ScottBokma @jacobottesen-dgc 

Could y'all please take a look at the following prototypes and let me know what works best from a **visual** and **interaction/UX perspective**?

Note: Not everything in the masthead is interactive – the goal is just to test the **hover** state of L1. Please go all the way down to `White papers` in the L1 and navigate back up. Thanks!

[Option 1
](https://ibm.invisionapp.com/share/JNNZITA7WMQ)
[Option 2
](https://ibm.invisionapp.com/share/Q8NZITC7DAF)
[Option 3
](https://ibm.invisionapp.com/share/YVNZITG89X3)
[Option 4](https://ibm.invisionapp.com/share/VCNZITEGRBY)

**Comment by oliviaflory** [comment]
I think the options got mixed up between your static and invision links somehow, so including screen shots / link to your prototype!

**From a visual and interactive perspective, [this one](https://ibm.invisionapp.com/share/YVNZITG89X3#/screens/319346564) ended up being my favorite** 
**(Option 4 in static visuals)**
- I liked the larger hit area for the "Get started" title chip link
- The Get started and Resources links were clearly separate interactions to me and I could easily anticipate different things to happen
- the larger hit area / hover area visually looked cleaner to me in comparison to the one that only extended 16px to the right and left of the text.
<img width="916" alt="Screen Shot 2019-12-03 at 6 03 26 PM" src="https://user-images.githubusercontent.com/45692622/70097403-4fe90c80-15f7-11ea-84a4-ddf1ea5aa7f4.png">

---
**Option 1**
- Hover state felt a little too tight to the Resources arrow here
- The hover state covering both Get Started and Resources feels like they'll go to the same place
<img width="915" alt="Screen Shot 2019-12-03 at 6 11 28 PM" src="https://user-images.githubusercontent.com/45692622/70097884-7491b400-15f8-11ea-9017-7a27ccbeac11.png">

**Option 2**
- From a visual standpoint, how tight the hover state gets to the Resources link was much more noticeable in this option
- However I think this works better than either of the options where the entire chip changes color.
- Would we update the other links on gray 10 to be this height?

<img width="677" alt="Screen Shot 2019-12-03 at 6 15 25 PM" src="https://user-images.githubusercontent.com/45692622/70098087-0c8f9d80-15f9-11ea-80af-a77841da2152.png">

**Option 3**
- This hover state made me think the "Get started" and "Resources" went to the same place until I hovered over Resources on it's own. I wonder if this would be confusing for users who are interacting with it the first time?

<img width="774" alt="Screen Shot 2019-12-03 at 6 58 38 PM" src="https://user-images.githubusercontent.com/45692622/70100236-259b4d00-15ff-11ea-8a3e-7718af1ef72a.png">

**Comment by larahanlon2** [comment]
Thank you so much @oliviaflory ! And yes, I totally botched the option order between the static and prototypes. 

I agree with your [pick](https://ibm.invisionapp.com/share/YVNZITG89X3#/screens/319346564) – this is also my preference. There is a clear distinction between the two CTAs in the chip when it goes down to that level. I also prefer the blue underline spanning the full with of the title chip here, as opposed to it hanging 16px off rightand left as it is today. It looks much cleaner to me.

My only gripe is that the hover state for title chip is shorter than the other L1 hover states. So when navigating across the L1 links the "shapes" and height is a little inconsistent:
<img width="1121" alt="Screen Shot 2019-12-03 at 8 32 53 PM" src="https://user-images.githubusercontent.com/53093550/70104514-3acaa880-160c-11ea-8e79-b61a0a7ce49b.png">

But I would rather have a clear UX / interaction model than streamlined visuals here and I think the title chip allows for that difference because it's treated uniquely anyway.

**Comment by larahanlon2** [comment]
For this ☝️option I actually moved the `eyebrow` up 2px to allow for a clean 48px hover state for the main title, which is the same height as L0. So in a way there still is visual consistency. **When there is NO `eyebrow` in use, I'm thinking the entire chip can be interactive, at the full 80px height:**

<img width="1431" alt="Screen Shot 2019-12-03 at 8 40 16 PM" src="https://user-images.githubusercontent.com/53093550/70104935-8c276780-160d-11ea-93ea-319bb30d5003.png">
<img width="1451" alt="Screen Shot 2019-12-03 at 8 40 20 PM" src="https://user-images.githubusercontent.com/53093550/70104936-8c276780-160d-11ea-9544-0536ba4ab7ee.png">
<img width="1416" alt="Screen Shot 2019-12-03 at 8 41 50 PM" src="https://user-images.githubusercontent.com/53093550/70104937-8c276780-160d-11ea-8a80-b2064f8beaf1.png">

**Comment by wonilsuhibm** [comment]
I'll go by the prototype option numbers.

### Option 1
This to me makes the most sense in terms of UX and affordance. But I do agree that the hover state is way too close to the eyebrow. I wonder if we need to push the eyebrow to higher, which will separate the two distinctive action items further, and resolve the hover issue. I also like the way this higher eyebrow looks and feels.

![Screen Shot 2019-12-03 at 8 38 41 PM](https://user-images.githubusercontent.com/30183447/70104733-f7bd0500-160c-11ea-81ad-f6ea970df8af.png)

### Option 2
The page title hover conflicts with the eyebrow a bit too much for me.

### Option 3
The full-bleed hover feels strange, visually unbalanced. Maybe the hover state can be padded instead of full-bleed like this (higher eyebrow here too):
![Screen Shot 2019-12-03 at 8 43 36 PM](https://user-images.githubusercontent.com/30183447/70105038-d0b30300-160d-11ea-95d1-2eb369af0e0d.png)

### Option 4
This is still confusing to me.

**Comment by wonilsuhibm** [comment]
I like higher eyebrow. I'd even try moving up by 4px:
![Screen Shot 2019-12-03 at 8 52 17 PM](https://user-images.githubusercontent.com/30183447/70105451-cfcea100-160e-11ea-8580-ff72df2ffb8e.png)

**Comment by larahanlon2** [comment]
Thanks @wonilsuhibm ! 

I really like the hover state with the 16px padding suggestion for **option 3**, instead of full width. I'm thinking that could work nicely:

<img width="1426" alt="Screen Shot 2019-12-03 at 8 51 17 PM" src="https://user-images.githubusercontent.com/53093550/70105538-145a3c80-160f-11ea-92ce-61f5c139d227.png">

<img width="1397" alt="Screen Shot 2019-12-03 at 8 51 24 PM" src="https://user-images.githubusercontent.com/53093550/70105539-145a3c80-160f-11ea-8584-ba8d9348c901.png">

<img width="1405" alt="Screen Shot 2019-12-03 at 8 51 58 PM" src="https://user-images.githubusercontent.com/53093550/70105540-145a3c80-160f-11ea-8fb3-886f15acb140.png">


Though I still don't love it with the `eyebrow` overall, with any of these options. What if we added a **subtle rule** between the eyebrow and title chip to help anchor the visual elements? Like so:

<img width="1485" alt="Screen Shot 2019-12-03 at 9 04 19 PM" src="https://user-images.githubusercontent.com/53093550/70106025-95660380-1610-11ea-8634-d74be1430b90.png">
<img width="1469" alt="Screen Shot 2019-12-03 at 9 04 28 PM" src="https://user-images.githubusercontent.com/53093550/70106027-95660380-1610-11ea-9fa1-d537bb9a4a95.png">
<img width="1503" alt="Screen Shot 2019-12-03 at 9 04 39 PM" src="https://user-images.githubusercontent.com/53093550/70106028-95660380-1610-11ea-8729-bdbe1173d20d.png">
<img width="1510" alt="Screen Shot 2019-12-03 at 9 04 47 PM" src="https://user-images.githubusercontent.com/53093550/70106029-95660380-1610-11ea-802f-47e0040cec31.png">

And what if...we bumped the whole L1 up to 96px in height so that there is a 48-48-48 visual rhythm from L0 to L1, including the space for the eyebrow. Like so:

_eyebrow:_
<img width="1615" alt="Screen Shot 2019-12-03 at 9 09 44 PM" src="https://user-images.githubusercontent.com/53093550/70106298-42d91700-1611-11ea-88d5-9c2dc6a4e9e2.png">

_no eyebrow:_
<img width="1606" alt="Screen Shot 2019-12-03 at 9 10 17 PM" src="https://user-images.githubusercontent.com/53093550/70106333-5dab8b80-1611-11ea-82c1-a0a7c81a7449.png">

**Comment by larahanlon2** [comment]
> I like higher eyebrow. I'd even try moving up by 4px:
> ![Screen Shot 2019-12-03 at 8 52 17 PM](https://user-images.githubusercontent.com/30183447/70105451-cfcea100-160e-11ea-8580-ff72df2ffb8e.png)

I'm hesitant to move the eyebrow too high. Users might end up clicking on the IBM logo. But with a taller L1 we could emphasize the distance between the two.

**Comment by wonilsuhibm** [comment]
Hmmm, the risk is in both ways - too close to the logo or too close to the page title. here are the two areas - 48px for the page title and 32px for the eyebrow. I say we center the eyebrow in the top 32px area.

![Screen Shot 2019-12-03 at 10 29 01 PM](https://user-images.githubusercontent.com/30183447/70110221-53db5580-161c-11ea-81c2-1369a047fdf7.png)

**Comment by wonilsuhibm** [comment]
Re 96px tall L1, I do love the idea of rhythm but it also feels a bit too tall. Let's take a look at the view in a typical laptop monitor size.

Another quick thought — if we end up with healthy L1 nav items, could we play with heading 03 for the L1 title in 96px container?

**Comment by oliviaflory** [comment]
> My only gripe is that the hover state for title chip is shorter than the other L1 hover states. So when navigating across the L1 links the "shapes" and height is a little inconsistent:
> <img width="1121" alt="70104514-3acaa880-160c-11ea-8e79-b61a0a7ce49b" src="https://user-images.githubusercontent.com/45692622/70153282-b2d0b700-167c-11ea-869f-f28670f94931.png">

👆 we _could_ look at shortening the L1 hover states to align with the title chip hover. Could be weird, but might be worth a second look if it feels strange.

---

> I really like the hover state with the 16px padding suggestion for **option 3**, instead of full width. I'm thinking that could work nicely:
> 
> <img alt="Screen Shot 2019-12-03 at 8 51 17 PM" width="1426" src="https://user-images.githubusercontent.com/53093550/70105538-145a3c80-160f-11ea-92ce-61f5c139d227.png">
> 
> <img alt="Screen Shot 2019-12-03 at 8 51 24 PM" width="1397" src="https://user-images.githubusercontent.com/53093550/70105539-145a3c80-160f-11ea-8584-ba8d9348c901.png">
> 
> <img alt="Screen Shot 2019-12-03 at 8 51 58 PM" width="1405" src="https://user-images.githubusercontent.com/53093550/70105540-145a3c80-160f-11ea-8fb3-886f15acb140.png">
> 

👆 My only thought about it changing height is that could be weird if you're navigating between different pages at one time? But if the most likely scenario is _no_ eyebrow the change wouldn't be as noticeable.

Additionally, is the L1 smart enough to know when there is or is not an eyebrow?

---

One last question is: does the eyebrow need an underline on hover? Can't believe I didn't think of this before, but a change in color is not enough from an accessibility standpoint. That's why Carbon has to have the underline on their link components.

**Comment by larahanlon2** [comment]
> Re 96px tall L1, I do love the idea of rhythm but it also feels a bit too tall. Let's take a look at the view in a typical laptop monitor size.
> 
> Another quick thought — if we end up with healthy L1 nav items, could we play with heading 03 for the L1 title in 96px container?

If there is no need for an eyebrow for complex levels of L1 then heading-03 could be very nice. I think we need to see how L1 performs / how teams manage and clean up their IA first, though. 

<img width="1414" alt="Screen Shot 2019-12-04 at 1 39 54 PM" src="https://user-images.githubusercontent.com/53093550/70171055-f7b81600-169b-11ea-8ec1-fc23dff581c0.png">

**Comment by larahanlon2** [comment]
> > My only gripe is that the hover state for title chip is shorter than the other L1 hover states. So when navigating across the L1 links the "shapes" and height is a little inconsistent:
> > <img alt="70104514-3acaa880-160c-11ea-8e79-b61a0a7ce49b" width="1121" src="https://user-images.githubusercontent.com/45692622/70153282-b2d0b700-167c-11ea-869f-f28670f94931.png">
> 
> 👆 we _could_ look at shortening the L1 hover states to align with the title chip hover. Could be weird, but might be worth a second look if it feels strange.
> 
> > I really like the hover state with the 16px padding suggestion for **option 3**, instead of full width. I'm thinking that could work nicely:
> > <img alt="Screen Shot 2019-12-03 at 8 51 17 PM" width="1426" src="https://user-images.githubusercontent.com/53093550/70105538-145a3c80-160f-11ea-92ce-61f5c139d227.png">
> > <img alt="Screen Shot 2019-12-03 at 8 51 24 PM" width="1397" src="https://user-images.githubusercontent.com/53093550/70105539-145a3c80-160f-11ea-8584-ba8d9348c901.png">
> > <img alt="Screen Shot 2019-12-03 at 8 51 58 PM" width="1405" src="https://user-images.githubusercontent.com/53093550/70105540-145a3c80-160f-11ea-8fb3-886f15acb140.png">
> 
> 👆 My only thought about it changing height is that could be weird if you're navigating between different pages at one time? But if the most likely scenario is _no_ eyebrow the change wouldn't be as noticeable.
> 
> Additionally, is the L1 smart enough to know when there is or is not an eyebrow?
> 
> One last question is: does the eyebrow need an underline on hover? Can't believe I didn't think of this before, but a change in color is not enough from an accessibility standpoint. That's why Carbon has to have the underline on their link components.

1. I hear you. I did take a look again at the shorter L1 hover but I don't think we should revert to that for the sake of the eyebrow-chip need. It starts to look less "designed". The top of L1 looks like wasted space:
<img width="1163" alt="Screen Shot 2019-12-04 at 1 45 15 PM" src="https://user-images.githubusercontent.com/53093550/70171352-8e84d280-169c-11ea-9a6f-af0bca7612f4.png">

2. My understanding is that part of the dev work with Ishita on Drupal team is to understand how the L1 would work with and without the eyebrow. What is the navigational tree? How is the data stored and pulled in? What are the rules etc. etc. So right now the eyebrow is not smart enough because it's not really functional.

3. There is already a blue underline for the `eyebrow` on hover:
<img width="850" alt="Screen Shot 2019-12-04 at 1 50 57 PM" src="https://user-images.githubusercontent.com/53093550/70171651-284c7f80-169d-11ea-8fa3-a8cadcb43623.png">

**Comment by larahanlon2** [comment]
Ok @wonilsuhibm @oliviaflory I think I arrived at a good solution! Let me know what you think.

**Below are a bunch of iterations of the same hover style but with different eyebrow styles.**
1. eyebrow = 16*16 icon + 14px type
2. eyebrow = 16*16 icon + 12px type
3. eyebrow = 14px arrow glyph + type
4. eyebrow = 12px arrow glyph + type

**And [here](https://ibm.invisionapp.com/share/EUNZJA985WZ#/319351726_L1--test--v1-2) is the prototype of** `3. eyebrow = 14px arrow glyph + type`.

My preference is either this option ☝️or `1. eyebrow = 16*16 icon + 14px type` because:
- There is **consistency** in how we're treating all interactive links in the L0 and L1 by using a `hover-background` on everything.
- There is a **greater hit target** for the eyebrow so users _don't_ click on either the L1 title link or IBM logo. 
- I had to move the eyebrow over to the right so the arrow **aligns-left with the L1 title text** to allow for the hover padding. I think this works and is actually how the locale selector eyebrow aligns so again it's more consistent with other components.

___________
### 1. eyebrow = 16*16 icon + 14px type

![L1-hover state-chip hover 1](https://user-images.githubusercontent.com/53093550/70350561-f706b780-1834-11ea-9ca0-bfaa31961a1a.png)

### 2. eyebrow = 16*16 icon + 12px type

![L1-hover state-chip hover 2](https://user-images.githubusercontent.com/53093550/70350570-f9691180-1834-11ea-94d5-15d430ff271a.png)

### 3. eyebrow = 14px arrow glyph + type

![L1-hover state-chip hover 3](https://user-images.githubusercontent.com/53093550/70350581-fd952f00-1834-11ea-99d0-3aae37ca1322.png)

### 4. eyebrow = 12px arrow glyph + type

![L1-hover state-chip hover 4](https://user-images.githubusercontent.com/53093550/70350588-ff5ef280-1834-11ea-9e45-f830bcb667eb.png)

**Comment by wonilsuhibm** [comment]
Thank you, Lara. I like #1 16*16 arrow icon + 14px type.

The glyph arrow feels unpolished and different fro other icons.

12px type feels too small.

**Comment by oliviaflory** [comment]
Sorry for the delay, I am seconding Wonil, I prefer the regular icon, I think Mike will too lol. I think the 14px type pairs better with our overall type scale, we're probably not going to have 12px in the currently type scale.

**Comment by larahanlon2** [comment]
Great! 100% agree with this option! Thank you both @wonilsuhibm @oliviaflory
