### ISSUE TITLE
IBM logo in Masthead is not aligned with content in big screens

### ISSUE THREAD

**Issue by jcpalaci** [carbon-design-system/ibm-dotcom-library#719]
## Detailed description

> Describe in detail the issue you're having.

IBM logo in Masthead is not aligned with content in big screen sizes (MAX breakpoint)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Masthead (styles)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

IBM logo being aligned with content in all breakpoints

> What browser are you working in?

All

> What version of the IBM.com Library are you using?

1.1.2 (also happens on 1.1.1)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com search

## Steps to reproduce the issue

1. Open https://ibmdotcom-react.netlify.com/iframe.html?id=dotcom-shell--default using a big screen or zoom out to simulate one

## Additional information

- Screenshots or code

**Big Screen (MAX breakpoint)**
![image](https://user-images.githubusercontent.com/57272532/69359795-e1976800-0c4e-11ea-9cc7-5f730fbc3b30.png)

**Large Screen (XLG) breakpoint**
![image](https://user-images.githubusercontent.com/57272532/69359872-16a3ba80-0c4f-11ea-8bbd-1f860e2fda91.png)

- Notes

We applied a fix for this in our app, changig `bx--header`'s `max-width` to `98rem`:
```
// Align IBM logo with content in big screen sizes
.#{$prefix}--header {
  max-width: 98rem;
}

```
https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/styles/scss/components/masthead/_masthead.scss#L53

**Comment by jeffchew** [comment]
@kennylam @RobertaJHahn this seems like an easy lift, want to bring this into the next sprint? Do we have room?

**Comment by ljcarot** [comment]
Working as designed. For more detail on the behaviour, please consult with Wonil Suh or Lara Hanlong.

**Comment by kennylam** [comment]
Actually @ljcarot, just went over this with @larahanlon2 and @wonilsuhibm and it turns out it should be aligned as reported in this issue (sorry about that, i thought it was correct). Will reopen and get this taken care of.

@RobertaJHahn @jeffchew
