### ISSUE TITLE
Video player -  Embedded Production version 

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#724]
#### User Story

> As a visitor to IBM.com I need to be able to watch informative videos so that I can learn more about topics, technologies, products, and how to do things that will help me and my business.

#### Additional information

 - Previous work has already been done by Conrad Ennis from the Brand team. His sketch file is posted here https://ibm.ent.box.com/file/562872283117 Conrad has offered to provide insights and guidance to whoever is to work on this next. The main focus will be finalizing the design at all breakpoints, comprehensive functionality and content.
 - The design has been largely modeled after YouTube but there has not been any usability testing done.
 - [Jerry Ringuette](https://w3.ibm.com/bluepages/profile.html?uid=932315897) is the MediaCenter Offering Manager
 - [Felipe Zuntini Abella](https://w3.ibm.com/bluepages/profile.html?uid=012403631) is the MediaCenter lead developer
 - [Telium Box folder](https://ibm.box.com/s/5bwa91c76gp10g7q1qj0xmau1ipdsp91)  Access to this Box folder may be needed from Juan Leon

#### Acceptance criteria
 - [ ] Visual designs at all breakpoints
 - [ ] Documented interaction and design specs

**Comment by RobertaJHahn** [comment]
Roberta to schedule meeting with Jerry, Felipe, Wonil, Irene, Jill, Lila, Alain, and Ke.

**Comment by RobertaJHahn** [comment]
Initial meeting scheduled Jan 8, 2020.  Invitees:  Alain Machu, Conrad Ennis, Felipe Zutini, Jerry Ringuette, Irene Joo, Jill Stuart, Ke Xu, Lila Title, Wonil Suh

**Comment by RobertaJHahn** [comment]
Jan 20, 2020 Engineering meeting notes to breakdown into multiple issues:
1) Create a service to grab the meta data for the video. 5 points sprint 20-02
2) Create an Inline embed (default) version of the video player. 5 points sprint 20-02
3) Create the link version of the video component that opens into the Lightbox media viewer. 3 points sprint 20-03
4) Enable the Lightbox media viewer to render the Kaltura embedded player. 8 points sprint 20-02
5) Enable the metrics for the video player. 4 different events to track. Start, play, pause and end 5 points sprint 20-03
6) Swap the default icons in the Kaltura video player with the Carbon icons. Other Carbon style updates TBD. Contact Felipe to see whether there is code that we can use. 5 points sprint 20-03
