### ISSUE TITLE
Pattern: Create the simple overview band functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#730]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have Simple Overview Band functional specs 

> so that I can:
so that I can properly code the content array with cards pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Learn-page-layout-pattern-roadmap#content-array-with-cards--epic-652--details-specs--research) - _This URL may change as this linked wiki page may move to the public github_

#### Acceptance criteria
 - [ ] Documented content array with cards functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable

**Comment by photodow** [comment]
@wonilsuhibm is this still relevant?

**Comment by RobertaJHahn** [comment]
Closing as this work is no longer relevant with the new ontology.
