### ISSUE TITLE
[LeadSpace] Update styles to apply color theme as a container modifier

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#732]
#### User Story

> As a `[user role below]`:
IBM.com adopter

> I need to:
apply a color theme modifier class at the same level as the container level class of the leadspace

> so that I can:
easily switch color themes

#### Additional information

 - Currently, the color theme class is a parent class to the `bx--leadspace` class. This will need to be modified to be the same level as `bx--leadspace`.

#### Acceptance criteria
 - [ ] Updated storybook stories, scss, and React prop for switching themes

**Comment by ljcarot** [comment]
Will this be in Release v1.2.0 @jeffchew
