### ISSUE TITLE
Expressive theming: token change impact study

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#739]
This story is to understand the impact that type scale, container, icon, and padding change will have on components, in order to review the code changes.

### Acceptance criteria
- [ ] A list of things to look at and confirm with code.

**Comment by oliviaflory** [comment]
Link to initial [Carbon documentation](https://github.com/carbon-design-system/carbon/issues/4330) around where components break during first theming approach. Could be useful for reference

**Comment by oliviaflory** [comment]
### Type token values comparing Carbon and what we'd like to change for Dotcom purposes.

![Type tokens](https://user-images.githubusercontent.com/45692622/70065823-b3ece000-15b9-11ea-80be-d135d3d384a1.png)

**Comment by oliviaflory** [comment]
### Icon sizes

<img width="597" alt="Icon sizes" src="https://user-images.githubusercontent.com/45692622/70072933-f4eaf180-15c5-11ea-81cf-0e519c4fe14a.png">

**Comment by oliviaflory** [comment]
### Container size and type size relationship, comparing Carbon values to Dotcom

High level guidelines for container sizes within expressive theme. 

Top and bottom padding defined for both `$body-short-01` and `$body-long-01` line heights depending on *which* type token the component uses.

Any containers that are not set to these exact sizes or defined by the content within (ie modal, multi line code snippet, multi line notification) should be addressed separately.

![container-size](https://user-images.githubusercontent.com/45692622/70077391-c291c200-15ce-11ea-8f1d-d71341cdb5a3.png)

**Comment by oliviaflory** [comment]
### Design intent for single icon within a container 

Icons should be vertically centered within 32, 40, and 48px rectangular container sizes.
Icons should be horizontally centered within a 48px wide space within 32, 40 and 48px rectangular container sizes.

If the container is a square, icons should be vertically and horizontally centered within the square container. (ie icon button, icon only button)

![container-icon-relationship](https://user-images.githubusercontent.com/45692622/70078135-2963ab00-15d0-11ea-9cde-edd9422ae378.png)

**Comment by wonilsuhibm** [comment]
@oliviaflory should we keep `productive-heading-01` as is, and update `expressive-heading-01` instead?

**Comment by oliviaflory** [comment]
We have to update `productive-heading-01` to 16px because it is used within some components and we aren't swapping out type tokens in this approach.

Component examples:
- data table
- notification
- structured list
- tabs

**Comment by wonilsuhibm** [comment]
Okay, understood the need to update `productive-heading-01`. Shouldn't we also update `expressive-heading-01` as well, since there is no proper body size for it. Unless we keep it for the smaller type scales, but then it feels diverging from the productive theme.

**Comment by oliviaflory** [comment]
> Okay, understood the need to update `productive-heading-01`. Shouldn't we also update `expressive-heading-01` as well, since there is no proper body size for it. Unless we keep it for the smaller type scales, but then it feels diverging from the productive theme.

Agreed with Wonil, it will make more sense in the system if we update `expressive-heading-01` to 16/24px or 1 / 1.5 REM. @jeffchew would you mind making that update? 

And looks like I calculated the REM value wrong for the line height in the `productive-heading-01`. Line height = 22px or 1.375 REM.
