### ISSUE TITLE
Markdown utility

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#743]
#### User Story
> As a `[user role below]`:
IBM.com developer

> I need to:
repeat common markdown conversions

> so that I can:
meet the pattern requirements for rich text

#### Additional information

We might have more needs arise from this as we learn more about our rich text needs, but for now the most common thing we're seeing is the need for italics within some of our patterns following markdown syntax. In other places we need a little more rich text including links and such.

 - [Pictogram Array Functional Specs](https://ibm.box.com/s/xngulixjv6oem8sdgreoslw2tu9d6udr)
 - [Card Array Functional Specs](https://ibm.box.com/s/px2557guu928pwu3umr71t255u409teu)
 - [Markdown guidelines](https://www.markdownguide.org/basic-syntax/)
 - [Markdown processors](https://github.com/markdown/markdown.github.com/wiki/Implementations)

#### Acceptance criteria
 - [ ] Convert Markdown to HTML
 - [ ] Turn on/off specific rules (e.g. italics turned on while everything else is turned off)
 - [ ] `@carbon/ibmdotcom-utility` that can be used in react and vanilla.

**Comment by photodow** [comment]
@jeffchew do we need functional specs for utilities like this?

**Comment by jeffchew** [comment]
No, I think we should just describe in the acceptance criteria what we need here and then engineering can carry out.

**Comment by jeffchew** [comment]
@photodow is this ready for dev? I want to pull this into sprint 24 for the long break.

**Comment by photodow** [comment]
@jeffchew yeah, this should be ready to pick up.
