### ISSUE TITLE
Content group - with pictogram: Content Entity

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#744]
#### User Story
> As a `[user role below]`:
As an IBM.com developer

> I need to:
create a content object component with a pictogram

> so that I can:
reuse it in the pictogram array pattern

#### Additional information

![image](https://user-images.githubusercontent.com/3793636/69694858-46681d80-10a8-11ea-99f5-d564ee1c43b8.png)

> ❓Can we merge the simple array, and pictogram array here? There are a couple of small differences like the left column pictogram. It might be worth a conversation.

 - [Pictogram Array Functional Specs](https://ibm.box.com/s/xngulixjv6oem8sdgreoslw2tu9d6udr)
 - Pictogram Array Visual Specs [[sketch](https://ibm.box.com/s/iyrjxcp1lwymla8891hgsyl8bl4m0fvn)][[png](https://ibm.box.com/s/ai326isog3uovcgvhuq82e26x6fwb0j0)]
 - Markdown utility #743
 - `@carbon/pictograms` [[website](https://www.carbondesignsystem.com/guidelines/pictograms/library)] [[npm](https://www.npmjs.com/package/@carbon/pictograms)] [[npm react](https://www.npmjs.com/package/@carbon/pictograms-react)]
 - [LinkWithIcon](https://ibmdotcom-react.netlify.com/?path=/story/link-with-icon--default)
 - > *Simple Array Visual Specs [[sketch](https://ibm.box.com/s/00upfv34of6qgeqyil13jjengaefxll9)] [[png](https://ibm.box.com/s/cvcc83kpy8ekcaoa5lz6edjiksmw0izr)]*

#### Acceptance criteria
 - [x] Pass in any pictogram from `@carbon/pictograms`
 - [x] Title
 - [ ] Text (italic markdown only)
 - [ ] CTA (optional)
 - [ ] Design, Development, and OM approval

**Comment by jeffchew** [comment]
@photodow is this an old issue? Probably should close this if we have the production level one in the pipeline.

cc: @RobertaJHahn

**Comment by photodow** [comment]
@jeffchew as long as we have another story to cover this work that's ok.

**Comment by RobertaJHahn** [comment]
Closing per comments above.
