### ISSUE TITLE
Component: embeddable image component design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#747]
#### User Story

As I go through various IBM pages, I would love to view images presented in a standard way which will allow me to view the image in the best way (appropriate resolution and aspect ratio in the given browser size and device screen size, screen reader, informative caption, etc).

#### Notes
- Some studies were done as a part of the lightbox media view component design. The Sketch file is [here](https://ibm.box.com/s/mpeo1wy0jogkwxn68fahlg62q799ixox)

#### Acceptance criteria

- [ ] A way to choose one of the standard aspect ratios (1x1, 2x1, 16x9, 4x3) is provided
- [ ] A way to set different images for different breakpoints
- [ ] A way to set different images for different screen resolutions
- [ ] A way to change aspect ratio based on breakpoint
- [ ] A way to set caption
- [ ] Accessibility requirements are met
- [ ] A way to trigger lightbox media viewer

**Comment by RobertaJHahn** [comment]
Design is not needed.  The work is purely functional.
