### ISSUE TITLE
Component:  Image Functional Specs - alpha version

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#767]
#### User Story
> As a `[user role below]`:
IBM.com developer for Carbon

> I need to:
build a responsive picture component

> so that I can:
be sure I'm following the standards when creating patterns and other components.

#### Additional information
As mentioned in issue #699 we need a component for responsive images, and thus need some functional specs. In a call, I had the other day with the web simplification team they mentioned certain limitations to help standardize the image sizes, aspect ratios, number of images allowed, aligned to what breakpoints, and possibly more. I'll be reaching out to the team to help define some of this.

![image](https://user-images.githubusercontent.com/3793636/70094323-e8779080-15e7-11ea-9736-d1b0edfb1bb9.png)

 - [Request for Responsive Picture Component #699](https://github.com/carbon-design-system/ibm-dotcom-library/issues/699)

###### Components/patterns already using something similar
 - [pattern/useCasesGroup](https://github.com/carbon-design-system/ibm-dotcom-library/blob/13e21b52b71a9a00057b14d73db5df0af3efcbf5/packages/patterns-react/src/patterns/UseCases/UseCasesGroup.js#L62-L72)
 - [pattern/leadspaceImage](https://github.com/carbon-design-system/ibm-dotcom-library/blob/0aecec572ee6d408b5d228588183da0d13cd39f8/packages/patterns-react/src/patterns/LeadSpace/LeadSpaceImage.js#L40-L55)

###### Patterns with imagery
- [Card with image](https://ibm.box.com/s/riny5aabsllfxf8dyn2g2b9ykpnejya7)
- Leadspace
   - [Centered leadspace](https://ibm.box.com/s/w9g5arb8pcrw2sheyonuolaukqvjgcly)
- [Use case](https://ibm.box.com/s/9khxckrhvj93y7os2gzbkuuu9e32aka4)
- [Featured link](https://ibm.box.com/s/22eumjqkfj273y9s3251zwgyz3zc7q0n)
- *[Logo grid](https://ibm.box.com/s/vha7x9514lnuqw1t2vwrw23xqij49zo4) (maybe not needed)*
- ~*[Pictogram array](https://ibm.box.com/s/iyrjxcp1lwymla8891hgsyl8bl4m0fvn) (maybe not needed)*~
- [Embeddable image](https://ibm.box.com/s/dtn9t9o1iy8h26rb66mr05gns98v42st)
- [Media viewer](https://ibm.box.com/s/cha02r05cctumwappc2g1y26pemtbu9t)
- *[Carousel](https://ibm.box.com/s/1dqloxyk7kj3wduwj1tlqr6dgtsokgdq) (TBD)*
- [Video player](https://ibm.box.com/s/4h5elmai87ydbr4uy4gecslm547gl7n8)
- Long form?
- Segmented long form?
- Simple array?

#### Acceptance criteria
 - [x] functional spec file created and shared
 - [x] design and development agree
 - [x] stories created for development to begin prioritizing

**Comment by photodow** [comment]
Here is the latest file for the [image component functional specs](https://ibm.box.com/s/1bbrspqkipecv2o010l8czzese084cix)

**Comment by jeffchew** [comment]
@photodow added comments/questions to the doc, not sure if you got notifications or not.
