### ISSUE TITLE
Pattern:  Card - update functional specifications

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#768]
#### User Story
> As a `[user role below]`:
IBM.com developer for Carbon

> I need to:
a single card component

> so that I can:
reuse it across multiple patterns

#### Additional information
I'm seeing card links being used multiple times across the different patterns. I'm thinking we should pull them out into their own component/pattern, and account for the different variations through modifiers or something of the like so we can reduce our footprint. Ultimately this means we'll need a functional spec to determine this work.

![image](https://user-images.githubusercontent.com/3793636/70096831-9df91280-15ed-11ea-952b-e41a2a4546c8.png)

###### Currently being used
 - `component/cardlink`  [[code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/components/CardLink)] [[storybook](https://ibmdotcom-react-experimental.netlify.com/?path=/story/card--link)]
 - `pattern/simpleLongForm`  [[code](https://github.com/carbon-design-system/ibm-dotcom-library/blob/33df19f0439c3ed6e79dc24f185b091bd7c49156/packages/patterns-react/src/patterns/SimpleLongForm/SimpleLongForm.js#L73-L78)] [[storybook](https://ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/simple-long-form--default)]
 - `pattern/useCases`  [[code](https://github.com/carbon-design-system/ibm-dotcom-library/blob/13e21b52b71a9a00057b14d73db5df0af3efcbf5/packages/patterns-react/src/patterns/UseCases/UseCasesGroup.js#L43-L48)] [[storybook](https://ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/use-cases--default)]

###### In progress (as of authoring this issue)
 - [feat(pattern): card array first implementation #758](https://github.com/carbon-design-system/ibm-dotcom-library/pull/758)
 - [feat(pattern): created card without images pattern #728](https://github.com/carbon-design-system/ibm-dotcom-library/pull/728)
 - [Feat/locale filter #725](https://github.com/carbon-design-system/ibm-dotcom-library/pull/725)

###### Patterns/components with cards
 - [Card with images](https://ibm.box.com/s/riny5aabsllfxf8dyn2g2b9ykpnejya7)
 - [Card array / Card without images](https://ibm.box.com/s/fx8odkidz7h63yh242p4k8wrtz77gxj1)
 - [List section](https://ibm.box.com/s/owlpnu8303gg6nse6yvtjyjow90e6tb7)
 - [Simple cards](https://ibm.box.com/s/ikjbami4rj89a2ctt2w397fd27ruty3w)
 - [Simple long form](https://ibm.box.com/s/hcjf4950rnwchvhahl4k63vj0dm3oszb)
 - [Use cases](https://ibm.box.com/s/9khxckrhvj93y7os2gzbkuuu9e32aka4)
 - [Featured link](https://ibm.box.com/s/22eumjqkfj273y9s3251zwgyz3zc7q0n)
 - [Locale selector](https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8)

#### Acceptance criteria
 - [x] Audit of known cards being used
 - [x] functional specs created and shared
 - [x] web simplification team approval
 - [x] design and development agreement
 - [x] stories (if necessary) to iterate and create

**Comment by photodow** [comment]
[Create a merged Clickable Tile specification #547 (closed)](https://github.com/carbon-design-system/ibm-dotcom-library/issues/547) might be relevant to this story.

**Comment by RobertaJHahn** [comment]
@photodow Moving this issue to Sprint 20-01.

**Comment by photodow** [comment]
Here are the functional specs
https://ibm.box.com/s/y1h8lgvn8zjdzr9r0owi7gvy5mjz7lcd

Here are the design specs for now
https://ibm.box.com/s/wlp3d380mgrxt5g3i6itekfawl2s2ubz

Asside from the issues already in the backlog due to previous gap analysis here are the issues created:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1283 https://github.com/carbon-design-system/ibm-dotcom-library/issues/1282 https://github.com/carbon-design-system/ibm-dotcom-library/issues/1281
