### ISSUE TITLE
Intro copy for FAQ page (cupcake site)

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#771]
Intro copy for FAQ page

**Comment by jimpistilli** [comment]
FAQ

_Below are some of the most frequently asked Carbon for IBM.com questions. If there is a question not answered below, please don't hesitate to contact us. [Contact us link here]

cc: @jacobottesen-dgc @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Please open the issues for website task on our [website gitboard](https://github.com/carbon-design-system/carbon-for-ibm-website/issues/16#workspaces/ibmcom-library-5d449f3642eb1962336cbe52/board?repos=202376156).

@RobertaJHahn This issue can be closed.
