### ISSUE TITLE
February 2020 Release Plan (v1.4.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#772]
# Timeline

- **February 14, 2020**: Code freeze
- **February 17, 2020 - February 21, 2020**: Release Candidate(s) and testing
- **Feb 25, 2020**: Full Release

# New Changes

Our team has completed a major assessment of the ontology of our patterns, and have since come up with the following changes:

- Patterns are now classified as either `sections`, `blocks`, or `sub-patterns`. More details around this coming soon to our website!
- Reclassified a handful of components as `sub-patterns`:
  - ButtonGroup
  - TableOfContents
  - Layout
  - ContentGroup
  - CardLink
- With the above, we have also decided to decommission the `@carbon/ibmdotcom-patterns-react` package, and have all fall under the `@carbon/ibmdotcom-react` package. All README files have been updated to reflect the new change, which for the most part should just be repointing the pattern imports to the new package. 
- Many pattern names have been renamed and restructured based on the new pattern ontology. They will still remain behind a feature flag until all has been finalized and we deem to be production ready.

![Renamedpatterns](https://user-images.githubusercontent.com/1641214/74245844-a6d32800-4cb1-11ea-89d8-18d2c661dae5.png)

# Features

## Patterns
**Learn Page template**
- **Table of Contents** (#1064 ): Includes feature request to dynamically generate the links based on the page content.  
- **Content block - mixed** (#1263 ):  Alpha version behind a feature flag.  
- **Content block - segmented** (#1267 ):  Alpha version behind a feature flag.  
- **Content block - simple** (#1275 ):  Alpha version behind a feature flag.  
- **Content block - with media** (#1238 ):  Alpha version behind a feature flag.  
- **Content group - simple** (#1243 ):  Alpha version behind a feature flag.  
- **Content group - with cards** (#1172 ):  Alpha version behind a feature flag.  
- **Content group - with pictograms** (#1165 ):  Alpha version behind a feature flag.  

**Production level QA testing will be performed on the patterns listed above.  Known QA issues will be resolved in the March release.**

## Sub-Patterns
- **Content Item** (#1176)
- **Content block** (#1169 )
- **Content group** (#1173 )
- **Card** (#1202 ): Alpha version behind a feature flag.  
- **Pictogram Item** (#1164 ):  Alpha version behind a feature flag.  

## Components (React)
- **CTA** (#1168 )

## Vanilla
- **Masthead** (#355): New look, L0/L1 navigation, search bar with typeahead, profile icon for login/logout
- **Dotcom Shell** (#546): A UI shell structure includes Masthead and Footer providing a starting point for building an IBM.com page.

**Comment by andysherman2121** [comment]
https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.4.0
