### ISSUE TITLE
Masthead: mobile menu should be full-width and cover L0

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#781]
Because we're using Carbon UI header, the [hamburger] menu doesn't behave/appear the same as ibm.com masthead specs. 

Current implementation:
<img width="406" alt="Screen Shot 2019-12-06 at 11 30 47 AM" src="https://user-images.githubusercontent.com/53093550/70338963-e138c880-181b-11ea-8fde-fda866c5d8fa.png">

In the original design,`mobile` menu should slide over the entire screen, covering the L0. The `platform name` would appear at the top of the menu list. Like so:

<img width="805" alt="Screen Shot 2019-12-06 at 11 16 59 AM" src="https://user-images.githubusercontent.com/53093550/70337924-f3b20280-1819-11ea-8d2d-4b125d21571f.png">

The `platform name` is used as a title and navigational link.
The `close-icon` is used to bring the user back to the previous page view and show L0 again.
Like so:

<img width="1225" alt="Screen Shot 2019-12-06 at 11 20 27 AM" src="https://user-images.githubusercontent.com/53093550/70338234-89e62880-181a-11ea-866b-cb3aa9f60404.png">

**This model allows the user to focus more on menu navigation. It prevents them from tapping on IBM logo, Search or Login which is distracting them from the main task at hand.**

**Comment by RobertaJHahn** [comment]
@kennylam @larahanlon2 I am moving this epic back into the Prioritized Epics pipeline.  During the Triage meeting, we decided to turn this original issue into an epic and use linked issues to manage the multiple tasks associated with this work.  We also agreed that the first issue would be to work with Carbon regarding the strategic solution.  I have created [Issue 824](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/824) to capture this work.  I assigned it to the first sprint in 2020 as many people will begin taking holiday vacation.
