### ISSUE TITLE
Pattern:  Content group - with cards design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#790]
#### User Story

> As a `[user role below]`:
DDS Designer 

> I need to:
test the `Content group - with cards`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
 - alpha Dev link (#704 )
- Design folder with func specs and visual specs is here: [Box](https://ibm.box.com/s/709822ny79gfn2s3b68noeg1gd14s6zk)

 #### Tasks
Ensure the `Content group - with cards` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm @RobertaJHahn 
This pattern is ready for review, thanks!

**Comment by oliviaflory** [comment]
@RaphaelAmadeu do you have a link to the pattern? I want to make sure I'm testing the correct one, I wasn't sure if it was in [ibmdotcom-react](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-get-started--read-me) or [ibmdotcom-react-experimental](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/overview-get-started--read-me)

**Comment by RaphaelAmadeu** [comment]
@oliviaflory, here it is, https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default

thanks!
