### ISSUE TITLE
[Expressive] Dev support for updating Carbon components with Expressive Theme

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#800]
#### User Story

> As a `[user role below]`:
IBM.com Application developer

> I need to:
apply the expressive theme to Carbon components

> so that I can:
build my IBM.com application to design specifications

#### Additional information

 - [Netlify fo Carbon Expressive](https://carbon-expressive.netlify.com)
 - Support to make as many updates as possible to the Carbon components with the expressive theme
- Overrides are on a per-component basis
- Design story: #799

#### Acceptance criteria
 - [ ] Updates to Carbon components based on allocated story points

**Comment by RobertaJHahn** [comment]
Decided that we will create separate issues for the dev support needed for the expressive changes to the Carbon components.  Issues are managed using the Epic (#799 ) Closing this issue.
