### ISSUE TITLE
Component: Finalize changes to the Lightbox component functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#814]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have documented functional specs for the lightbox component

> so that I can:
develop a component that accurately reflects the design

#### Additional information

 - The functional specs would be created along with the design specs.  [issue #326](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/326)

#### Acceptance criteria
 - [x] Final changes from reviewing team members included in the functional specs, if applicable
 - [x] ~Roadmap wiki is updated~ (not relevant)
 - [x] ~Dev stories created~ (will create stories after gap analysis)

**Comment by photodow** [comment]
Here is the latest on [Lightbox Media Viewer functional specs](https://ibm.box.com/s/hq4eq9fdgb279o40h5ur5eonpo58359e)
