### ISSUE TITLE
[Utility] Same Height

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#816]
#### User Story
> As a `[user role below]`:
Carbon for IBM.com developer

> I need to:
apply the same height across a number of elements based on the largest element

> so that I can:
deliver my work without reinventing the wheel

#### Additional information

We have a need that keeps arising where a list of components need to be the same size as the largest in the list. This work should create a utility to manage that.

###### CardArray example
![image](https://user-images.githubusercontent.com/3793636/70641224-e5d9f400-1c02-11ea-8ef3-1bb6934e7048.png)

> Reach out if you need any additional information.

#### Acceptance criteria
 - [ ] Target a specific list of elements to compare
 - [ ] Identify the largest element
 - [ ] Resize all smaller elements to match the largest in the list
 - [ ] Handle events like `resize` and `onload`?
 - [ ] Development approval
 - [ ] `@carbon/ibmdotcom-utility` that can be used in react and vanilla.

**Comment by jeffchew** [comment]
@photodow I'm going to pull this into sprint 24.
