### ISSUE TITLE
Masthead:  Work with Carbon to define strategic solution for the mobile menu

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#824]
#### User Story

> As a `[user role below]`:
consumer of the Carbon design system

> I need to:
have a Carbon mobile Masthead L0 that can be included in the ibm.com Masthead

> so that I can:
provide this component to the DDS adopters in the most efficient way

#### Additional information

 - A tactical solution has been defined and included in [Issue #782](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/782)
 - A strategic solution is needed.

#### Acceptance criteria
 - [ ] Agreed design is defined, agreed and documented with Carbon

**Comment by kennylam** [comment]
After speaking with @larahanlon2 and @wonilsuhibm, we decided to keep the current positioning of the Carbon hamburger menu, i.e. it will stay in the same place whether the side nav is open or closed:

![Jan-02-2020 11-54-06](https://user-images.githubusercontent.com/909118/71679899-aa8c9a00-2d56-11ea-8c83-e8f648a0084e.gif)

The `ibmdotcom` design will not be used for the time being (hamburger close button moves to right when visible):

![Screen Shot 2020-01-02 at 11 46 53](https://user-images.githubusercontent.com/909118/71679950-ce4fe000-2d56-11ea-95af-9e1bbd8c33ea.png)

**Comment by larahanlon2** [comment]
Agreed!
