### ISSUE TITLE
Expressive theme – Checkbox

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#825]
# Checkbox

### Label
- label line height should be 18px. Check $label-01 spec.
- ~spacing between label and first checkbox item should be 8px~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes

### Checkbox icon
- icon should be 20x20px. I _thought_ Carbon was using that, but looks like 16x16 when I inspect it?
- ~Space between icon and checkbox item should be 8px, I can't understand how they built this, so can you confirm it's correct?~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes

### Checkbox item
- _How is Carbon's line height 24px?!? That doesn't exist in the type scale_
  - I might need to sit with the developer to figure this part out

- Design intent: 
  - ~8px spacing between each item~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes
  - type size = $body-short-01 

![Screen Shot 2019-12-11 at 2.53.14 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/0fde3c2b-203e-4fb2-8258-51e864784260)

**Comment by annawen1** [comment]
For the checkbox item line height is at 24px since they are hardcoding it instead of using the token
<img width="495" alt="Screen Shot 2019-12-17 at 4 29 47 PM" src="https://user-images.githubusercontent.com/54281166/71036041-d66b1700-20ea-11ea-84fa-189a0182b311.png">

**Comment by annawen1** [comment]
Same was done with the label
<img width="373" alt="Screen Shot 2019-12-17 at 5 11 59 PM" src="https://user-images.githubusercontent.com/54281166/71038726-79725f80-20f0-11ea-917e-f3a9711cedd7.png">

**Comment by annawen1** [comment]
@joshblack is the line height something we should be overwriting when applying the expressive theme? Looks like the `line-height` was set for experimental checkbox styles.

**Comment by joshblack** [comment]
Good question, I think this may need to be changed if the drawn checkbox and box are also updating in size, meaning from 16 -> 20px 👍
