### ISSUE TITLE
[Card Array]  Use new markdown utility

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#827]
## Detailed description

The [CardArray](https://ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/content-array-with-cards--default) isn't converting markdown italics into markup.

###### Example of it not converting markdown
![image](https://user-images.githubusercontent.com/3793636/70665302-e6d64a00-1c31-11ea-94e5-5c59b35d1130.png)

###### Example of what it should look like
![image](https://user-images.githubusercontent.com/3793636/70665341-f9e91a00-1c31-11ea-8f5c-1d54a39eb026.png)

## Additional information

- [CardArray Functional Specs](https://ibm.box.com/s/px2557guu928pwu3umr71t255u409teu)
- [CardArray](https://ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/content-array-with-cards--default)
- [CardLink](https://ibmdotcom-react.netlify.com/?path=/story/card--link)

**Comment by RaphaelAmadeu** [comment]
This update is being done along with the updates on this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/902

**Comment by RaphaelAmadeu** [comment]
This was done in the latest merge.
