### ISSUE TITLE
[Card Array] Update to use CardLink component

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#829]
## Detailed description

A lot of the issues we're having with the CardArray pattern can be solved just by using the CardLink component. Once that's done we can take another look to see what changes (if any) need to be made to the CardLink Component. If we need to make changes, then maybe we can add a variation/modifier to the CardLink Component.

![image](https://user-images.githubusercontent.com/3793636/70667544-c5c42800-1c36-11ea-8470-ffa9509647af.png)

###### Issues identified this should help fix...
 - [x] Card needs to be clickable
 - [x] Icon incorrect styling and positioning
 - [x] Incorrect typography
 - [x] Incorrect spacing

## Additional information

- [x] Add CardLink component
- [x] Remove any duplicated card CSS and functionality

**Comment by RaphaelAmadeu** [comment]
This update is being done along with the updates on this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/902

**Comment by RaphaelAmadeu** [comment]
This update is being done along with the updates on this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/902

**Comment by RaphaelAmadeu** [comment]
This was done in the latest merge.
