### ISSUE TITLE
[LocaleSelector] Mobile issues for region selector view

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#835]
## Detailed description

> Describe in detail the issue you're having.

Various loading issues in mobile for the region selector view. See below:

<img width="493" alt="Screen Shot 2019-12-12 at 8 55 34 AM" src="https://user-images.githubusercontent.com/1641214/70718288-f00cf880-1cbd-11ea-9b51-b258dbc67112.png">

1) Close button is covered by the masthead
2) height issues with the tiles

> What browser are you working in?

Browserstack: Pixel 3XL (Android) Chrome browser

> What version of the IBM.com Library are you using?

v1.2.0-rc.1

**Comment by jeffchew** [comment]
Also on Iphone XS iOS 12:

<img width="547" alt="Screen Shot 2019-12-12 at 9 27 48 AM" src="https://user-images.githubusercontent.com/1641214/70720407-bd64ff00-1cc1-11ea-97b4-417b72fe7de6.png">

**Comment by ljcarot** [comment]
I agree with Sev 1 priority
