### ISSUE TITLE
[LocaleSelector] Change placeholder text to "Search by location or language"

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#837]
## Detailed description

> Describe in detail the issue you're having.

By request from Mary O'Donnell and team, they would like to change the placeholder text for the country/language search to "Search by location or language"

> What browser are you working in?

All browsers

> What version of the IBM.com Library are you using?

1.2.0-rc.1

<img width="796" alt="Screen Shot 2019-12-12 at 9 15 12 AM" src="https://user-images.githubusercontent.com/1641214/70719418-f3a17f00-1cbf-11ea-8ab5-aa950e7bedb5.png">

**Comment by ljcarot** [comment]
It is important to make this text change, probably a sev 3.
