### ISSUE TITLE
[LocaleSelector] Mobile landscape experience awkward/partially unusable

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#845]
## Detailed description

> Describe in detail the issue you're having.

When in mobile landscape, the locale selector region selector is not scrollable. Also when searching, the virtual keyboard covers the results list.

> What browser are you working in?

Samsung Galaxy S9+, iPhone XS iOS 12

![mobile-landscape-ios](https://user-images.githubusercontent.com/1641214/70755882-1310ca00-1d09-11ea-8476-78b14dd22b65.gif)

![mobile-landscape](https://user-images.githubusercontent.com/1641214/70755889-17d57e00-1d09-11ea-8d6b-bed01a091d0b.gif)

**Comment by ljcarot** [comment]
How easy is this one to fix before Monday's release?  Or do we address in a patch?

**Comment by jeffchew** [comment]
@annawen1 @kennylam any ideas?

**Comment by annawen1** [comment]
I think @kennylam mentioned he had a fix for the scrolling(?) As for the keyboard covering the results list should we get some input from design on how to handle that?

**Comment by kennylam** [comment]
@jeffchew @annawen1 this is fixed, but in a branch for next sprint. I'll get it into a PR for this release.
