### ISSUE TITLE
Locale change banner design study for Carbon code base

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#855]
### User story
As a user of IBM.com, I would like to know when I am forwarded to a page that has a different locale setting than my preferences or the previous pages.

### Notes
- This story is based on SEO's recommendation to not use the popup for locale change.
- The existing banner design seems to be problematic in that users either miss it or are not helped by it.
- The locale change notification design needs to be fitted into a banner.
- The language might have to be trimmed down to fit in a smaller banner.

### Specs and documentations
- Copy specs: https://ibm.ent.box.com/file/554715195147
- Design specs: https://ibm.box.com/s/isie20a89socbo9ael687u6pb75uz9f8
- Func specs: https://ibm.box.com/s/5cubvqd96izgl7cgmc820kxqvkjw88cr

### Acceptance criteria
- [ ] Wireframes is available
- [ ] Test the banner size VS message

**Comment by ljcarot** [comment]
@wonilsuhibm How big of an effort is the banner design study?

**Comment by wonilsuhibm** [comment]
@ljcarot I'd say both this is 5-8 points as we are probably setting up a precedent for banners here, and the final design story (#856) is 3 points.

**Comment by wonilsuhibm** [comment]
![Screen Shot 2020-03-02 at 6 09 10 PM](https://user-images.githubusercontent.com/30183447/75727226-6f550b80-5cb2-11ea-98e1-db28bdcf75c0.png)

**Comment by larahanlon2** [comment]
@oliviaflory spec links added to story description above. You can also click through prototypes used for testing [here](https://ibm.invisionapp.com/share/26NZ77UF57S) and German on [here](https://ibm.invisionapp.com/share/RMNZ8KVBWNJ).

**Comment by jacobottesen-dgc** [comment]
I got some great feedback from the team on different explorations. 

Sketch file in Box: https://ibm.box.com/s/u3c17tr2s5vameevr9kvwbytv867xkh9

For next steps refer to task: #856
