### ISSUE TITLE
Locale change banner visual design updates desktop

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#856]
As a DDS designer I need to review the NPS survey module information so I can determine the best design direction for the local banner

Some updated to the desktop designs might be needed after we meet with Jo Welsh to find out more about the NPS module implementation #1993 

**Acceptance criteria**
- [ ] Designs consider the NPS module implementation
- [ ] Designs reviewed with Design team

**Comment by jacobottesen-dgc** [comment]
Explored a few a collapsed version of the locale banner.

![Screen Shot 2020-04-24 at 9.06.18 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/b3ec26fc-9dfa-455d-913d-f6f9d8e66425)

**Comment by jacobottesen-dgc** [comment]
Updates to sketch file can be found in box: https://ibm.box.com/s/shephqs5l6b30fph8aladp2to1cu2we6
