### ISSUE TITLE
Locale banner functional specs

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#858]

**Comment by photodow** [comment]
Probably don't want to close this one?

**Comment by JennySanchez** [comment]
@wonilsuhibm @photodow Can either one of you add task description to this task? Thanks!

**Comment by RobertaJHahn** [comment]
Closing.  Work is managed under the issue (#1315)

**Comment by photodow** [comment]
@RobertaJHahn reopening as this work is separate from #1315, and will still need to be done once the design work is done.

**Comment by RobertaJHahn** [comment]
Closing this issue as the func specs will be managed in the Epic (#859)
