### ISSUE TITLE
Expressive – Modal

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#862]
## Modal

Modal actually looks pretty good! 

Other than the button area...

The text within the buttons looks a little low, and doesn't seem to have the correct allocation for the type? 
<img width="392" alt="Screen Shot 2019-12-16 at 2 01 34 PM" src="https://user-images.githubusercontent.com/45692622/70935376-07c1e500-200e-11ea-837d-1db5f4f43cb4.png">
<img width="222" alt="Screen Shot 2019-12-16 at 2 01 42 PM" src="https://user-images.githubusercontent.com/45692622/70935401-16100100-200e-11ea-9eca-e48c9243f80b.png">

~Please confirm that the top and left padding is 16px~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes
<img width="292" alt="Screen Shot 2019-12-16 at 2 07 07 PM" src="https://user-images.githubusercontent.com/45692622/70935409-19a38800-200e-11ea-85c9-b381b9f1c206.png">

**Comment by annawen1** [comment]
Leaving this as is for now after conversation with @oliviaflory
