### ISSUE TITLE
Expressive – Text input

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#868]
### Label
- line height is 16px, should be 18px
<img width="231" alt="Screen Shot 2019-12-16 at 4 31 22 PM" src="https://user-images.githubusercontent.com/45692622/70945436-2f6f7800-2023-11ea-8099-7081f3fd774e.png">
<img width="180" alt="Screen Shot 2019-12-16 at 4 30 45 PM" src="https://user-images.githubusercontent.com/45692622/70945430-2bdbf100-2023-11ea-8ec0-a72f216c1d43.png">

### Helper text
- ~confirm space between Label and Helper text is 2px~
- ~is this using a spacing token? or could we increase the spacing here?~
- **Update** Wonil and I would like to try not changing the padding for the first round of these changes
<img width="335" alt="Screen Shot 2019-12-16 at 4 33 07 PM" src="https://user-images.githubusercontent.com/45692622/70945470-47df9280-2023-11ea-88cd-1715926c8f92.png">

### Required field
- line height is 21px, should be 18px
- keep spacing between validation text and form field 4px
<img width="328" alt="Screen Shot 2019-12-16 at 4 31 50 PM" src="https://user-images.githubusercontent.com/45692622/70945648-a6a50c00-2023-11ea-9518-755d81100a12.png">
<img width="191" alt="Screen Shot 2019-12-16 at 4 31 56 PM" src="https://user-images.githubusercontent.com/45692622/70945665-ae64b080-2023-11ea-88a0-4ee1c552962f.png">

### Icons
- all icons are still 16px, need to be 20x20px
  - required field icon
  - toggle password variant
<img width="290" alt="Screen Shot 2019-12-16 at 4 32 21 PM" src="https://user-images.githubusercontent.com/45692622/70945713-cb00e880-2023-11ea-9cac-7db7449874df.png">
<img width="94" alt="Screen Shot 2019-12-16 at 4 48 37 PM" src="https://user-images.githubusercontent.com/45692622/70945788-ecfa6b00-2023-11ea-8989-8a084866b5ec.png">
<img width="97" alt="Screen Shot 2019-12-16 at 4 49 47 PM" src="https://user-images.githubusercontent.com/45692622/70945882-1b784600-2024-11ea-8dd0-3cf661070995.png">

- ~single icon should have 16px padding right, or centered within a 48x48px box. I'm not sure how they are positioning the icons here~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes
<img width="643" alt="Screen Shot 2019-12-16 at 4 35 03 PM" src="https://user-images.githubusercontent.com/45692622/70946026-6003e180-2024-11ea-9d45-644d974087e2.png">

- ~when there are two icons present (example: eye and error state) the icons should have 8px of spacing _between_ them, and 16px on either side (or keep positioning from centered within 48x48px box from single icon)~
**Update** Wonil and I would like to try not changing the padding for the first round of these changes
<img width="97" alt="Screen Shot 2019-12-16 at 4 49 47 PM" src="https://user-images.githubusercontent.com/45692622/70946065-80cc3700-2024-11ea-8d45-4594e1eaa136.png">
<img width="656" alt="Screen Shot 2019-12-16 at 4 35 56 PM" src="https://user-images.githubusercontent.com/45692622/70946145-ace7b800-2024-11ea-80dc-20934148537c.png">

**Comment by oliviaflory** [comment]
I got an error when I tried to view the "Fully controlled toggle password visibility" variant in Storybook, so I cannot comment on that one.

**Comment by annawen1** [comment]
The required field red text line-height seems hard coded to 1.5 (in `_form.scss`)
<img width="422" alt="Screen Shot 2020-01-02 at 2 15 38 PM" src="https://user-images.githubusercontent.com/54281166/71686962-acf8ef00-2d6a-11ea-80ee-b4ef8da90d3b.png">
