### ISSUE TITLE
Expressive – Number input

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#869]
### Label
- line height should be 18px, currently 16px
   - Note this was the same for text input
<img width="340" alt="Screen Shot 2019-12-16 at 5 09 37 PM" src="https://user-images.githubusercontent.com/45692622/70949300-6cd80380-202b-11ea-8fcb-7ce6a433a553.png">

### Field
- Looks like they might be using 300 weight on the placeholder or input text or something is making the text render lighter. Unclear why this is because it should be regular weight (400)
<img width="177" alt="Screen Shot 2019-12-16 at 5 43 39 PM" src="https://user-images.githubusercontent.com/45692622/70949414-b6285300-202b-11ea-993b-3c088ccd6fb3.png">

- doesn't look like the Placeholder text color is rendering correctly, seems like it is $text-01
<img width="170" alt="Screen Shot 2019-12-16 at 5 50 42 PM" src="https://user-images.githubusercontent.com/45692622/70949743-a0fff400-202c-11ea-950d-01550fae4256.png">

**Carbon example**
<img width="171" alt="Screen Shot 2019-12-16 at 5 50 49 PM" src="https://user-images.githubusercontent.com/45692622/70949750-a65d3e80-202c-11ea-8139-aabf928481b0.png">

 ### Icon
- Icon needs to be updated to 20px. Each carat is likely it's own icon
- ~the icon _should_ have 16px padding on the right side, but doesn't on Carbon side... can we center the icon within a 48px wide box?~ **Update** Wonil and I would like to try not changing the padding for the first round of these changes
<img width="227" alt="Screen Shot 2019-12-16 at 5 10 13 PM" src="https://user-images.githubusercontent.com/45692622/70949336-84af8780-202b-11ea-8598-5d54733d56f4.png">

- double check focus / hit areas when updating the icons, it should extend to the top and bottom of the field container
<img width="435" alt="Screen Shot 2019-12-16 at 5 46 52 PM" src="https://user-images.githubusercontent.com/45692622/70949590-2c2cba00-202c-11ea-8e9a-c58c6ecf2359.png">
<img width="201" alt="Screen Shot 2019-12-16 at 5 47 07 PM" src="https://user-images.githubusercontent.com/45692622/70949593-2df67d80-202c-11ea-98cc-ec4262e52f8c.png">

**Carbon example**

<img width="172" alt="Screen Shot 2019-12-16 at 5 48 26 PM" src="https://user-images.githubusercontent.com/45692622/70949697-7615a000-202c-11ea-9cdb-fbecfed3786b.png">

### Validation state
- line height is 21px, should be 18px
   - Note this was the same for text input
<img width="315" alt="Screen Shot 2019-12-16 at 5 51 41 PM" src="https://user-images.githubusercontent.com/45692622/70949838-e0c6db80-202c-11ea-98ac-a5051b64a60c.png">

- Icon needs to be updated to 20px.
- ~confirm space between two icons (carats and error icon) is 8px~ **Update** Wonil and I would like to try not changing the padding for the first round of these changes
-

**Comment by annawen1** [comment]
Looks like the carbon example placeholder text matches what we currently have now in terms of the font weight and color: 
http://react.carbondesignsystem.com/?path=/story/numberinput--default
<img width="196" alt="Screen Shot 2020-01-02 at 2 50 08 PM" src="https://user-images.githubusercontent.com/54281166/71689102-34486180-2d6f-11ea-8071-e7b387a7f221.png">

The label and error red text line-heights seem to be hard coded like mentioned in https://github.com/carbon-design-system/ibm-dotcom-library/issues/868
