### ISSUE TITLE
Pattern:  Featured Link functional QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#870]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library Featured Link Pattern

> I need to:
have a version of the pattern or component that has been tested on the latest Chrome browser and on the IOS and Android operating systems

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browserstack](https://ibm.ent.box.com/notes/578734426612)
- [Featured Link alpha dev story #706](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/706)
 - [Designs and functional specs](https://ibm.ent.box.com/folder/94763747291)

#### Acceptance criteria
- [ ] The pattern has been tested on the latest Chrome browser and on the IOS and Android operating systems
- [ ] Minimum functional unit test coverage of 80%
- [ ] Defects are recorded and retested when fixed

**Comment by jeffchew** [comment]
@RobertaJHahn @photodow I have added some details to this story, let me know if you think I'm missing anything.

**Comment by RobertaJHahn** [comment]
@jeffchew @photodow I would like to complete these issues and use them as models for the new one's.  i reviewed my notes from the Huddle last week.  We decided that a Deliverables section would be important to clarify the work to be done.  I added a deliverables section.
