### ISSUE TITLE
December 2019 v1.2.1 Patch release plan

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#878]
# Timeline

- **December 17th, 2019**: Code freeze
- **December 17th - 20th, 2019**: Release Candidate(s) and testing
- **December 23, 2019**: Full Release

# Features

## Bugs

- Footer Accordion Theme Slightly Off (#876 )
- Footer – secondary button theme is incorrect (#877)

**Comment by annawen1** [comment]
version `v1.2.1` has been released
