### ISSUE TITLE
Locale selector mobile landscape view design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#883]
### User story
As a user of IBM.com, I need to be able to use the new locale selector on small devices in landscape view.

### notes
- The new locale selector is difficult to use on mobile devices in landscape mode because of the virtual keyboard.

**Comment by wonilsuhibm** [comment]
My sense is that this is not a problem that we can solve. On a small mobile screen, almost no experience works properly especially when the keyboard is involved, and most users know to rotate their device. My suggestion is to close this issue. @ljcarot @jeffchew @larahanlon2

**Comment by ljcarot** [comment]
@wonilsuhibm ok to close. Did you open this on behalf of someone?

**Comment by wonilsuhibm** [comment]
@ljcarot I added this after discovered the issue — but after discussing with Jeff and Lara for possible solutions, we decided to leave it as is.
