### ISSUE TITLE
Create the Masthead L0 functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#884]
This is an epic that will link the issues needed to complete this work.  

The Masthead was designed and created before the Functional Analyst role was filled.  There are some large and important components that should be documented.  The Masthead is one of them.

**Comment by RobertaJHahn** [comment]
@photodow @ljcarot @jeffchew We had created an action from the Sprint 23 Retro to create an epic for the Masthead functional documentation.  We'll need to create an issue for the first 2 week block of work to be done.  @photodow could you create that first issue, link it to this epic and put it in the Sprint 20-02?  That will give us some time to talk about any other work that is needed.  Thanks.

**Comment by photodow** [comment]
😬

**Comment by photodow** [comment]
not stale

**Comment by RobertaJHahn** [comment]
Closing this epic.  All of the L0 functional spec issues have been moved to the `Component: Create Masthead L0 (React) - Production level` Issue (#1464)
