### ISSUE TITLE
[Masthead] L1 functional specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#886]
#### User Story
> As a `[user role below]`:
IBM.com Library developer

> I need to:
be able to reference masthead l1 behavior

> so that I can:
confidently execute on my stories, and support in the future

#### Additional information
 - [Masthead navigation design folder](https://ibm.box.com/s/mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)

#### Acceptance criteria
- [ ] functional specs created and shared
- [ ] web simplification team approval
- [ ] design and development agreement
- [ ] stories (if necessary) to iterate and create

**Comment by photodow** [comment]
not stale

**Comment by RobertaJHahn** [comment]
Moved to backlog due to Solution page priorities

**Comment by RobertaJHahn** [comment]
Not stale

**Comment by photodow** [comment]
This should be good, here is the link to the functional specs.

https://ibm.ent.box.com/file/694005937260
