### ISSUE TITLE
Canadian web pages - privacy regulation changes in v18/v19a

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#905]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
make changes to the Canadian privacy notifications

> so that I can:
ensure IBM complies with their regulations

#### Additional information

 - Required changes to make the Canadian notifications compliant:
 -  **Remove the Canada-specific pop-up banner that you see when you get on ibm.com/ca because the notice will now be part of code injected by DBDM team using TrustArc.**
 -  **Investigate if v18 code controls the position of AdChoice on the Canada site. If it does, then move the AdChoice icon above the fold on every webpage on the ibm.com/ca domain. This is a requirement of the DAAC program.**
 - **Investigate if v18 code controls the link for the AdChoice on the Canada site. If it does, then replace the current link with link that takes visitors to the DAAC tools/opt-out page: https://youradchoices.ca/en/tools**
 - Additional documentation is included in the Digital Design [Issue #1837](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/digital-design/1837)

#### Acceptance criteria
- [x] Old cookie banner notice is removed
- [x]  AdChoice is positioned to above fold
- [x] AdChoice link is changed

**Comment by RobertaJHahn** [comment]
@jeffchew @ljcarot I created the new issue in the ibm.com Library repo for the Canada compliance work and assigned it to the first sprint of 2020.

**Comment by jeffchew** [comment]
PR opened for the quick adchoice fix: https://github.ibm.com/webstandards/v18/pull/694
