### ISSUE TITLE
Pattern:  Featured Link Design QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#912]
#### Additional Information
 - [Develop an alpha version of the featured link #706](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/706)
 - Design specs [sketch](https://ibm.box.com/s/22eumjqkfj273y9s3251zwgyz3zc7q0n) and [png](https://ibm.box.com/s/rucd65orwmstyf6eesrelpm9wsrw4h32) 
 - [Designs provided by Web Simplification #659](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/659)
- [Featured Link functional specs #683](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/683)

 #### Tasks
Ensure the `Featured Link` pattern has been tested and reviewed by design + dev.

#### Acceptance criteria
- [x] Design review performed and Github issues created for all defects found
- [x] Defects are created and reviewed after fixes are made
- [ ] Approval that the code delivered works as designed

**Comment by larahanlon2** [comment]
Closing this as @photodow and I QA'd this pattern last sprint and opened new stories to address known defects. Lila has seen the issues and current pattern but will QA all patterns at a later date.
