### ISSUE TITLE
Cookie consent notice design update

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#926]
### User story
As a user of IBM.com, I'd like to see well-designed cookie notifications that are easy to understand in a way that is pleasant and consistent with the rest of IBM.com experiences.

### Notes
- This is to update the cookie notification screens to proper IDL standards.

<img width="1451" alt="screen_shot_2019-12-17_at_2 21 08_pm-2" src="https://user-images.githubusercontent.com/30183447/71823685-e3ce4e00-3065-11ea-9db1-d6dd72254c08.png">

![image-2.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/1ef1ba78-95e5-4dff-a0ba-98180158381c)

### Resources
- [Box fodler](https://ibm.box.com/s/sp8pcnyrpfuiat78xo0m7j0gzcrjk5ty)

**Comment by wonilsuhibm** [comment]
John Wafer from CIO contacted me today, identified our contacts from his perspective.
CIO: Seda Oczes and Brian Jensen
Prrivacy Office: Michelle Jutras-Steiner

**Comment by wonilsuhibm** [comment]
Emily Walters (emily.walters@uk.ibm.com) reached out with concerns around the mobile view and that you can't interact with the site without accepting it.

**Comment by juanleon9** [comment]
Hi @wonilsuhibm, can you give me access to the Box Folder?

**Comment by mjabbink** [comment]
This is especially bad in mobile. The close icon can get cropped which is not good and very frustrating.

**Comment by juanleon9** [comment]
Is this pattern no longer in plan?
