### ISSUE TITLE
Cookie notice design update: research

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#927]
### user story
As a designer to work on the new design of the cookie notice, I need to understand what I am designing in order to achieve the goal successfully.

### Notes
- We need to meet the team that owns these screens (Juan Leon and co)
- We also need to connect with the IDL team around the design direction

### Acceptance criteria
- Requirements have been captured
- Requirements and current design have been reviewed by the team and the team has formed a POV on the next steps.

**Comment by RobertaJHahn** [comment]
Meet with Juan to understand what the possible changes may be done with a third party vendor.

**Comment by wonilsuhibm** [comment]
Met with Juan Leon, agreed on the following:
- [ ] Juan will share the latest design files
- [ ] We will provide updated design for the initial screen as the MVP (to do in the follow-up story)

**Comment by RobertaJHahn** [comment]
Follow up story (#1361)
