### ISSUE TITLE
Expressive theme – pagination

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#954]
### Pagination (Default)

- [ ] Update chevron icons to 20x20 px
![Screen Shot 2020-01-06 at 1.56.47 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/5df0fd3a-bad0-4978-b3ad-fbf476b5ff43)

![Screen Shot 2020-01-06 at 1.57.27 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/eda7262f-0faa-4990-8413-524600658934)

- [ ] ~Update arrow icon to 20x20, looks like they're using paths to define these, let's try **8 x 12.5** and review together. I can't find where I can adjust in the inspect element to determine a size I like.~ 
Edit from @annawen1: spoke with Olivia and we agreed to keep the arrow icon size as it is now.
![Screen Shot 2020-01-06 at 2.02.18 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/58bd7400-55da-4d9b-8a91-b0f971531a13)

---

**Note** 
I can't find all the variations that Carbon shows on their website in our storybook... but maybe somethings are hidden?

### Pagination nav
<img width="352" alt="Screen Shot 2020-01-06 at 2 09 53 PM" src="https://user-images.githubusercontent.com/45692622/71841903-771b7980-308e-11ea-87f7-fe5bd1bd76e0.png">

- [ ] Make sure arrow icons are updated to the same size we determine in default pagination

### Pagination nav with select
<img width="436" alt="Screen Shot 2020-01-06 at 2 10 08 PM" src="https://user-images.githubusercontent.com/45692622/71841946-94504800-308e-11ea-90ef-1e482caf9f55.png">
- [ ] Make sure arrow icons are updated to the same size we determine in default pagination
If overflow is an icon, make sure it's updated to 20x20px 

### Pagination nav as anchor tags
*Question: is this the same as "Pagination nav" but with anchor elements added?
- [ ] If this is a separate component, make sure arrow icons are updated to the same size we determine in default pagination

**Comment by annawen1** [comment]
@oliviaflory Looks like the other variations (pagination nav with select + pagination nav) are not only available in Vanilla JS
