### ISSUE TITLE
Expressive theme – Tooltip

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#957]
### Default
Having trouble inspecting the tooltip because I can't force it to stay open...
<img width="300" alt="Screen Shot 2020-01-06 at 3 14 05 PM" src="https://user-images.githubusercontent.com/45692622/71846323-48a29c00-3098-11ea-89cd-cee08c2c3b16.png">

- [ ] link looks like it might still be 14px, should be 16/22px 

### Only custom icon
<img width="189" alt="Screen Shot 2020-01-06 at 3 16 22 PM" src="https://user-images.githubusercontent.com/45692622/71846313-44767e80-3098-11ea-8dbe-d38549a58482.png">
- [ ] Is it possible for this version to have a 20x20 icon, or will it change all the icons in the "default" tooltip group?

## Definition tooltip
⭐️  looks good!

## Icon tooltip
- [ ] Could you tell me what size the container is? It looks a little smaller than the "default uncontrolled tooltip"
- [ ] When the tooltip is direction left or right, there's a *tiny* white line that appears between the carat and container box. I'm not seeing it in the Carbon storybook example, can you check if it's a bug in our storybook?
<img width="117" alt="Screen Shot 2020-01-06 at 3 28 14 PM" src="https://user-images.githubusercontent.com/45692622/71846818-7805d880-3099-11ea-90b6-2ed9c761f034.png">

**Comment by annawen1** [comment]
@oliviaflory yeah seems like bumping up the icon for `Only custom icon` will change the icon size for the default variation as well...
