### ISSUE TITLE
Expressive theme – dropdown

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#962]
### Dropdown default
<img width="323" alt="Screen Shot 2020-01-07 at 9 45 33 AM" src="https://user-images.githubusercontent.com/45692622/71904115-84d70a80-3133-11ea-97c1-110ce310f20c.png">

- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- [ ] error icon should be vertically centered like the arrow and text

### Dropdown default inline
<img width="322" alt="Screen Shot 2020-01-07 at 10 00 26 AM" src="https://user-images.githubusercontent.com/45692622/71904858-ef3c7a80-3134-11ea-903c-052d3e8c2091.png">

- [ ] update inline dropdown height to 40px
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)

<img width="442" alt="Screen Shot 2020-01-07 at 10 04 15 AM" src="https://user-images.githubusercontent.com/45692622/71904946-1d21bf00-3135-11ea-9ba2-7448a7941b71.png">

- [ ] update error icon to 20x20px
- Note: hardcoded line height of 21px doesn't look great on error state

---
## Other variations:
*I'm not sure what the difference is for the other variations under the dropdown in storybook, but same changes apply as default dropdowns and default inline*

### Items as strings
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- [ ] error icon should be vertically centered like the arrow and text

### items as strings inline
- [ ] update inline dropdown height to 40px
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- Note: hardcoded line height of 21px doesn't look great on error state

### Items as components
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- [ ] error icon should be vertically centered like the arrow and text

### items as components inline
- [ ] update inline dropdown height to 40px
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- Note: hardcoded line height of 21px doesn't look great on error state

### Fully controlled
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- [ ] error icon should be vertically centered like the arrow and text

### Fully controlled inline
- [ ] update inline dropdown height to 40px
- [ ] update dropdown arrow to 20x20px (maybe it is already updated?)
- [ ] update error icon to 20x20px
- Note: hardcoded line height of 21px doesn't look great on error state

**Comment by andysherman2121** [comment]
Closing this. Fixed all issues above due to fixing different stories with the same classes.
Multi Select component update fixes inline dropdown height
Select component fixes the icon sizes
