### ISSUE TITLE
March 2020 Release Plan (v1.5.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#964]
# Timeline

- **March 6, 2020**: Code freeze
- **March 9, 2020 - March 13, 2020**: Release Candidate(s) and testing
- **March 18, 2020**: Full Release

# Features

## Styles
- **Expressive Theme Foundation** (#712 )

## React
**Production level and accessibility testing performed**
- **Table of Contents** (#984 )
- **Card section - simple** (#1147 )
- **Card section - with images** (#1148 )
- **Lead space** (#1149 )
- **Content block - mixed groups** (#1151 )
- **Content block - segmented** (#1152 )
- **Content block - simple** (#1153 )
- **Content block - with media** (#1154 )
- **Content group - simple** (#1156 )
- **Content group - with cards** (#1157  )
- **Content group - with pictograms** (#1158  )
- **Feature Card** (#1138 )

## Sub-patterns

- **Card** (#1202 )
- **Content section** (#1198 )
- **Link List** (#1254 ) 

## Services
- **Service to grab the video metadata** (#1065 )

## Feature Requests
- **Nested layout sub-pattern modifications** (#1581 )
         - **Content block - segmented:  the supporting link feature is missing** (#1541 )

## Defect Fixes
- **Leadspace: Content not staying aligned to the grid** (#1182 )
- **Leadspace: Top spacing fixes** (#1184 )
- **Leadspace-centered (no image) - Bottom spacing fixes** (#1186 )
- **Leadspace: Button text and icon size** (#1187 )
- **CSS for Content Block Patterns is missing some styles** (#1488 )
- **Content Block Patterns have the same data-autoid value** (#1490 )
- **Content Block Patterns seems to be missing Grid Styles** (#1537 )
- **Content Block Simple pattern does not have caption for image** (#1589 )
- **Content Block Media is not generating all css** (#1592 )
- **Card Section Simple has a generic data-autoid** (#1621)
- **Card Section Simple Pattern seems to be missing CSS** (#1624 )
- **Link List Top and Bottom Spacing** (#1667 )
- **CTA is no longer rendering URL when style is text** (#1682 )

**Comment by RaphaelAmadeu** [comment]
The release has been done,
https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.5.0
Thanks!
