### ISSUE TITLE
[Automation] Migrate IBM.com Library releases to Jenkins

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#968]
#### User Story

> As a `[user role below]`:
IBM.com Library Release Manager

> I need to:
initialize IBM.com Library releases from Jenkins

> so that I can:
further automate the creation of IBM.com Library releases

#### Additional information

 - Releases are currently managed via command line with the following shell script: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/tasks/publish.sh
- Additional script to create automatic releases from change logs completed here: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/tasks/tag-release.sh
- Pushing to Git might pose an issue, as that was never resolved when creating the Northstar releases Jenkins jobs.

#### Acceptance criteria
 - [ ] Jenkins job(s) created for creating IBM.com Library releases
 - [ ] Removal of the existing shell scripts
 - [ ] Update documentation ([IBM.com Library Publishing](https://ibm.ent.box.com/notes/499310803218), [IBM.com Library Release Management Playlist](https://ibm.ent.box.com/notes/497596874716), [IBM.com Library Patch Release Management Playlist](https://ibm.ent.box.com/notes/525233931289))

**Comment by jeffchew** [comment]
Iceboxing this for now. The current flow seems to be fine for the time being.

**Comment by RobertaJHahn** [comment]
3/24 Slack from Jeff:  I think we can close. I like the idea of the other devs having some knowledge of the inner workings of releases, rather than just pushing a button. in many cases, it's actually necessary.

Closing.
