### ISSUE TITLE
Pattern demo component: design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#972]
### User story
As a maker of IBM.com pages and templates, I need a way to preview a layout pattern, play with it, and understand its interactive and responsive behaviors.

### Notes
- This story is to do UI design.
- We have a design that was done a long time ago. This design doesn't align with the Carbon team's component demo tool's design at the moment. We should try to align as much as possible.
- We have done some initial user research in #684

### Acceptance criteria
- [ ] UI designs have been produced, reviewed, and accepted.

**Comment by jacobottesen-dgc** [comment]
I have wrapped up the design work and now have 3 options to decide from. Next steps for the task are in #1518
