### ISSUE TITLE
Pattern demo component: user test

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#975]
### User story
As a maker of IBM.com pages and templates, I need a way to preview a layout pattern, play with it, and understand its interactive and responsive behaviors.

### Notes
- This story is to test the wireframes

### Acceptance criteria
- [ ] Design has been tested

**Comment by jacobottesen-dgc** [comment]
All research insights can be found this box note: https://ibm.box.com/s/4sdlosi78alhvwg2d2phxnbhhszggvuu

Next steps:
Finalized designs for demo window in sprint 4 issue #972
