### ISSUE TITLE
[ImageCards] Updates to condensed grid per PR feedback

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#976]
@mkothur naw, @annawen1's right. We need the spacing inbetween. That comes from the Condensed Grid. We don't have to build that into each component, we just have to use what's already there. If Carbon decides one day they want to change the condensed grid to `3px`, then we have to go to a bunch of components and patterns to make sure we updated.

Here are a couple resources...
https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss#L19-L44
https://carbon-elements.netlify.com/grid/examples/preview/#condensed-grid
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation/#the-condensed-grid

Reach out if you have any questions or concerns.

_Originally posted by @photodow in https://github.com/carbon-design-system/ibm-dotcom-library/pull/803_

**Comment by photodow** [comment]
Here's a reduced case using codesandbox to show how to use the condensed grid. It's already in the `CSS`, so you just have to use the proper class name `bx--grid--condensed` at a parent level...

https://codesandbox.io/s/pedantic-galileo-o7ei3
