### ISSUE TITLE
Card Array responsive error

### ISSUE THREAD

**Issue by andysherman2121** [carbon-design-system/ibm-dotcom-library#982]
When adjusting the viewport size, the buttons move outside of their respective boxes. They drop below the borderlines. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue? A bug

> Is this issue related to a specific component? Yes, card array

> What did you expect to happen? What happened instead? What would you like to
> see changed? When adjusting the screen size, you expect for the buttons to stay within their boxes. 

> What browser are you working in? Chrome, Safari, Firefox

## Steps to reproduce the issue

Adjust the screen width to 1230px. You'll begin to see the buttons drop

## Additional information

![Screen Shot 2020-01-07 at 3 58 17 PM](https://user-images.githubusercontent.com/56688604/72005567-e2468680-321b-11ea-9f1f-4d3bfea2f968.png)

**Comment by RaphaelAmadeu** [comment]
This issue should be fixed with the new adjustments on the `sameHeight` utility.

**Comment by RaphaelAmadeu** [comment]
This bug was fixed on the latest merge.
