### ISSUE TITLE
Pattern:  Updates to Table Of Contents for Web Simplification Learn Page MVP

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#984]
Per conversation with @jeffchew  and @annawen1 

We need the following changes to the Table of Contents Component 👍 

1.  The ability for the react app to auto generate the table of content markup via the selection of anchor tag attributes that would be rendered in each pattern.
e.g 
<section ....
<a special-attr="[title of TOC link]"
</section>

2.  Add the anchor tag into the markup for each Learn page pattern except centered lead space and card section.

3.  Remove the margin from each pattern's section column and divider when that pattern is rendered inside of the TOC component.

**Comment by larahanlon2** [comment]
FYI Table of Contents design specs are now available on Abstract: https://share.goabstract.com/dbaeb532-b588-4138-8a07-3d04f01b4f34?
