### ISSUE TITLE
Card Array button error

### ISSUE THREAD

**Issue by andysherman2121** [carbon-design-system/ibm-dotcom-library#986]
The margin between the button and the body text is incorrect

## Detailed description

> The margin between the button and the body text above needs to be 32px. Currently it's set to a minimum margin of 32px. The minimum margin above the body text should be set to 32px, but that shouldn't be a fixed margin. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component? Card Array

> What browser are you working in? Chrome, Firefox, Safari

![Screen Shot 2020-01-09 at 10 30 23 AM](https://user-images.githubusercontent.com/56688604/72080672-2c3a7580-32cb-11ea-82f4-5df786f3a0b0.png)

The 32px margin above the button should be fixed

**Comment by RaphaelAmadeu** [comment]
This bug was fixed on the latest commit.
