### ISSUE TITLE
November 2019 Release Plan (v1.1.0)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#99]
# Timeline

- **October 25th, 2019**: Code freeze
- **October 28th - November 1st, 2019**: Release Candidate(s) and testing
- **November 4th, 2019**: Full Release

# Features

## React

- **Masthead/Footer** (#421): Integration of the TranslationAPI into the Masthead/Footer
- **Left panel container** (#257): Left panel container  in anticipation of use of left nav on pages
- **Expressive Modal** (#253): Variant of the Carbon `Modal` with an expressive theme
- **Link with Icon** (#163): Variant of the `Link` component with icon
- **Clickable Tile** (#504): Clickable tile component
- **Masthead Updates**:
  - Additional properties to show/hide the profile and search icons (#101)
  - Open the search box by default via prop (#593)
- **Analytics**:
  - Modal (#391)
  - Dynamic Tabs (#392):

## Patterns

- **Lead Space, Default** (#517): Lead space, left-aligned version

## Vanilla

- **Package Architecture** (#224): Initial Vanilla package architecture to support IBM.com Library Vanilla components
- **Horizontal Rule** (#553): A configurable `<hr />` element

## Services

- **TranslationAPI** (#515): Expand translation API to fetch data to display additional languages  worldwide

## Utilities

- **ipcinfoCookie** (#513): Utility for getting and setting the ipcinfo cookie
- **geolocation** (#514): Utility for fetching the geo location of the user

**Comment by photodow** [comment]
Closing after its release: https://github.com/carbon-design-system/ibm-dotcom-library/releases/tag/v1.1.0
