### ISSUE TITLE
Footer SSR breaks

### ISSUE THREAD

**Issue by sanjitbauli** [carbon-design-system/ibm-dotcom-library#993]
## Detailed description

```
TypeError: Cannot read property 'querySelectorAll' of undefined
    at altlangs (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-utilities/lib/utilities/altlangs/altlangs.js:28:48)
    at sortList (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-react/lib/components/LocaleModal/LocaleModal.js:157:54)
    at LocaleModal (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-react/lib/components/LocaleModal/LocaleModal.js:216:17)
    at processChild (/Users/sanjitbauli/workspace/urx-nxt/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:14)
```
> Its a bug 
> issue?

> The problem is with the footer component
>  The expected behavior is, the footer should render without any errors.

> happening in all browsers

> What version of the IBM.com Library are you using?

    "@carbon/ibmdotcom-react": "^1.2.1",
    "@carbon/ibmdotcom-services": "^1.2.1",
    "carbon-components": "^10.9.0",
    "carbon-components-react": "^7.9.0",

> What offering/product do you work on? Any pressing ship or release dates we
URX

When i am using the component only for the Front end, then the dds proxy returns 404
<img width="1036" alt="Screenshot 2020-01-10 at 4 51 39 PM" src="https://user-images.githubusercontent.com/272230/72149572-7dc92a00-33c9-11ea-86f0-c0460d4aa9aa.png">

<img width="1162" alt="Screenshot 2020-01-10 at 4 52 15 PM" src="https://user-images.githubusercontent.com/272230/72149620-92a5bd80-33c9-11ea-8a92-ebe2b8cdaa57.png">

**Comment by photodow** [comment]
Feel free to correct me, but this looks like it's a translation issue, and not an issue with any of our components?

In the example given it appears as if `inen` doesn't show up. `404`
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/inen-utf8.json

But if you use `usen` it doesn't give a `404`, and works as expected?
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/usen-utf8.json

Am I way off base with that?

**Comment by sanjitbauli** [comment]
@photodow - i explained about two different issues. 
The first one is about SSR which shows this error.
```
TypeError: Cannot read property 'querySelectorAll' of undefined
    at altlangs (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-utilities/lib/utilities/altlangs/altlangs.js:28:48)
    at sortList (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-react/lib/components/LocaleModal/LocaleModal.js:157:54)
    at LocaleModal (/Users/sanjitbauli/workspace/urx-nxt/node_modules/@carbon/ibmdotcom-react/lib/components/LocaleModal/LocaleModal.js:216:17)
    at processChild (/Users/sanjitbauli/workspace/urx-nxt/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:14)

```
And if i don't use SSR then also the footer translations trying to load the URL
https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/inen-utf8.json
when my url has in-en as locale.
example:
https://wwwstage.ibm.com/account/reg/in-en/signup?formid=urx-19776
Now if you look at my current implementation in the above page, it is loading the 
`https://www.ibm.com/common/v18/js/data/jsononly/inen.json` and it does exist.
Note: `https://wwwstage.ibm.com/account/reg/in-en/signup?formid=urx-19776` this URL has an older version of the dotcom package which is 1.1.2
See screenshot.
<img width="1380" alt="Screenshot 2020-01-11 at 1 34 21 PM" src="https://user-images.githubusercontent.com/272230/72201164-45802500-3477-11ea-9bd8-96560893c035.png">

**Comment by RobertaJHahn** [comment]
The country list should default to us-en.  This seems to not be happening in the Translation Service.

**Comment by jeffchew** [comment]
@annawen1 can we patch this into the `release/v1.3.0` branch?

cc: @kennylam

**Comment by annawen1** [comment]
@jeffchew not too sure, currently running into some importing errors...

**Comment by sanjitbauli** [comment]
I think the problem still exists.
With the old version, the footer file link on our stage
https://wwwstage.ibm.com/account/urxstatic/dds-proxy/https://www.ibm.com/common/v18/js/data/jsononly/usen.json

With the new version, it became 
https://wwwstage.ibm.com/account/urxstatic/dds-proxy/https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/usen-utf8.json
Which is not found.

**Comment by jeffchew** [comment]
@annawen1 can you take a look?

**Comment by sanjitbauli** [comment]
@jeffchew - please give me some time, looks like my reverse proxy set up has some issue. I will double-check and let you know if i found all good, i will close the issue.

**Comment by jeffchew** [comment]
great, thank you @sanjitbauli !

**Comment by sanjitbauli** [comment]
after doing some modification in my reverse proxy it started working. But i am not sure whether i really should do it.

See the code here
```
    server.get('/account/urxstatic/dds-proxy/:proxyUrl*', (req, res) => {
        req.url = req.url.replace('/account/urxstatic/dds-proxy/', '/'); // Strip '/proxy' from the front of the URL, else the proxy won't work.
        req.url = req.url.replace('https:/www', 'https://www'); // add slash missing (/) to domain
        req.url = req.url.replace('https:/1', 'https://1'); // add slash missing (/) to domain
        console.log('req.url', req.url);
        corsProxy.emit('request', req, res);
    });
``` 
Do you know i i need to do this `add slash missing (/) to domain`
