### ISSUE TITLE
Pattern:  Reconciliation of the Mixed Array pattern

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#995]
#### User Story

> As a `[user role below]`:
DDS design system developer and designer

> I need to:
have the mixed array pattern and sub-pattern relationships/names correctly defined and documented

> so that I can:
confidently include the patterns in an ibm.com website

#### Additional information

 - There are multiple array patterns and the design/implementation strategy has changed.  [Link to the existing wiki roadmap with old and new names.](https://github.ibm.com/webstandards/patterns/wiki/Pattern-roadmap)

#### Acceptance criteria
 - [x] Meetings scheduled to review the Mixed Array pattern strategy
 - [x] Decisions are documented 
 - [x] Decisions are communicated to the Web Simplification team

**Comment by larahanlon2** [comment]
If it's helpful, I setup [this Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1578930301842?sender=larahanlon9022&key=0b747bd0-8e19-47c8-93e3-5a903cbbc809) so we can braindump pattern name ideas or explore ontology stuff together.
