### ISSUE TITLE
Evaluate the Learn page Web Simplification v2 changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#997]
#### User Story

> As a `[user role below]`:
DDS engineering and design lead

> I need to:
review the new design and content model updates provided by Web Simplification

> so that I can:
determine what work has to be done and when it can be scheduled

#### Additional information

 - (Add links to the designs provided by Web Simplification here)
 - This review should be done immediately following the review of the WS designs, potentially during the week of Jan 20.

#### Acceptance criteria
 - [x] Meetings to review the updated designs
 - [x] Additional issues are created to manage the changes
 - [x] Forecast of the potential delivery date(s) provided to Sandeep and Alain

**Comment by photodow** [comment]
@larahanlon2 @RobertaJHahn @jeffchew @wonilsuhibm Just a quick breakdown of the work presented in the web simplification meeting just then. Let me know if I’m missing anything.

`new` video
`enhancement` Image (caption, lightbox)
`enhancement` Lightbox Media Viewer (video)
`new` Side Link List
`enhancement` ListSection / MixedArray breakdown
`new` ContentSection
`new` SimpleArray
`new` Long Form
`new` Segmented Long Form Decorator
`new` Simple Long Form Decorator
`enhancement` Layout (is the layout component ready for this already?)

**Comment by photodow** [comment]
Here is the link to the recorded presentation of the review.

https://ibm.webex.com/recordingservice/sites/ibm/recording/playback/4cc93769a249430ab3bd1b5d9b911eeb

**Comment by photodow** [comment]
From Lila, the v2 Simple Array design specs.

https://ibm.ent.box.com/folder/95195575998

**Comment by ljcarot** [comment]
@photodow Of the items listed above, can you map them to our existing patterns or are they all new patterns?  Are any of them actually components and not patterns?

**Comment by photodow** [comment]
@ljcarot I quickly added my understanding of pattern vs. component. We can change it if anyone feels it's slightly off. As for new or existing, I added links to existing in storybook, but that's the differenciation between `new` and `enhancement`. New means it doesn't exists, and enhancement means we just have a couple things to add to an existing component or pattern to get it up to par.

**Comment by RobertaJHahn** [comment]
@photodow The password is needed to play the recording.  The recording links should be kept together in the Box note with all of the adopter meeting recordings.  Here is a link to the Box Note.  If you could update the table with the missing information, that would be great.  

https://ibm.ent.box.com/notes/443167473382
